### ISSUE TITLE
V2 Iriconverter method getIriFromItem does not support composite keys with mapping

### ISSUE THREAD

**Issue by napalm33700** [api-platform/api-platform#100]
>       if (1 === count($identifiers)) {
            $identifiers = array_map(function ($identifierValue) {
                return rawurlencode($identifierValue);
            }, $identifiers);
        } else {
            $identifiers = array_map(function ($identifierName, $identifierValue) {
                return sprintf('%s=%s', $identifierName, rawurlencode($identifierValue));
            }, array_keys($identifiers), $identifiers);
        }

$identifierValue is an object, rawurlencode only takes string.

**Comment by teohhanhui** [comment]
@napalm33700 This should already have been fixed in #552

**Comment by dunglas** [comment]
@napalm33700 can you confirm that this bug is fixed?

**Comment by napalm33700** [comment]
It's fixed you can close that issue. Sorry for not reporting it earlier but V2is so awesome i was busy with it :)
