### ISSUE TITLE
MongoDB DocumentRepository wrong namespace

### ISSUE THREAD

**Issue by Dragonqos** [api-platform/api-platform#1007]
During my own tests on api-platform/core 2.4@beta with Mongo I found a bug
```
request.CRITICAL: Uncaught PHP Exception ApiPlatform\Core\Exception\RuntimeException: "
The repository for "App\Document\Channel" must be an instance of "Doctrine\ODM\MongoDB\Repository\DocumentRepository"." 
at /vendor/api-platform/core/src/Bridge/Doctrine/MongoDbOdm/CollectionDataProvider.php line 63
```

**How to reproduce:**
Create a documentRepository and extend it from existed Doctrine\ODM\MongoDB\DocumentRepository class:

**How to fix:** 
Go to api-platform/core/src/Bridge/Doctrine/MongoDbOdm/CollectionDataProvider.php line 23

namespace **_Doctrine\ODM\MongoDB\Repository\DocumentRepository_** is wrong and should be replaced with **_Doctrine\ODM\MongoDB\DocumentRepository_**

**Comment by alanpoulain** [comment]
I think you are using the wrong version of MongoDB ODM. Have you followed the documentation? https://api-platform.com/docs/core/mongodb/

**Comment by Dragonqos** [comment]
My bad, seems you right. It would be good to add this to composer suggests)
