### ISSUE TITLE
Can't start graphql server

### ISSUE THREAD

**Issue by egorzot** [api-platform/api-platform#1008]
Hi!
I tried to start graphql like in [docs](https://api-platform.com/docs/core/graphql/#enabling-graphql) and get an error:

```
docker-compose exec php composer req webonyx/graphql-php && bin/console cache:clear
ERROR: 
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml
```
I tried to find any docker-compose.* files in my project and vendor folder but they are missed. 
Using symfony 4.2.3.

**Comment by alanpoulain** [comment]
Have you installed the distribution? Where directory are you in? The docker-compose file is this one: https://github.com/api-platform/api-platform/blob/master/docker-compose.yml

**Comment by egorzot** [comment]
> Have you installed the distribution?

Yes , I installed it via symfony flex (api-pack package). 

In my composer.json:
` "api-platform/api-pack": "^1.1"`

And screenshot of [packages](https://s.mail.ru/6HRW/nZwDzbHBw) installed in vendor folder

**Comment by antograssiot** [comment]
but do you use docker-compose at all in your project and do you have a `php` container ?
Otherwise you just need to use `composer req webonyx/graphql-php && bin/console cache:clear`

**Comment by alanpoulain** [comment]
You are not using the distribution, that's why you don't have the docker-compose file. To install the distribution follow the documentation here: https://api-platform.com/docs/distribution/#using-the-official-distribution-recommended
If you want to continue to use Flex, @antograssiot showed you the way.

**Comment by egorzot** [comment]
I tried to install but got an error

`api-platform/api-platform v2.1.6 requires sensio/framework-extra-bundle ^3.0.2 `

How about to update this package dependencies? Last release is 5.2.4 version.

**Comment by antograssiot** [comment]
We are not supporting this version anymore and moreover, regarding your initial request, GraphQL support was added in 2.2 so you should try to upgrade beforehand.

**Comment by egorzot** [comment]
Thanks guys!
