### ISSUE TITLE
[Question] What is the purpose of DataFixtures ?

### ISSUE THREAD

**Issue by AlexandreHagen** [api-platform/api-platform#101]
Hi 
I would like to know for what we need to have DataFixtures in Api-platform? It is required? And if yes to what? 
Thanks.

**Comment by AlexandreHagen** [comment]
Ok this is linked to hautelook/alice-bundle. So I understand now.

**Comment by teohhanhui** [comment]
It is only there for having a demo of sorts you can get up and running with...
