### ISSUE TITLE
[Question] Can i use multiply dataProviders for one resource?

### ISSUE THREAD

**Issue by dvc** [api-platform/api-platform#1011]
Hello,

I have many CommandDTO with currentUser. And some groups of CommandDTO for update and delete some Entity.

I want to create some interfaces and traits for this DTO. Like CurrentUserAwareInterface, SomeEntityAwareInterface and so on. And create data providers like CurrentUserProvider, SomeEntityProvider.

Another case: i want to build some DTO via some data sources: SQL DB, Mongo, ElasticSearch, API... Some fields from one, other - from differents.

Of couse, it requires some options to force finish chain.

How to build this chain without pain? Decorates dataProviders? Inject one providers to enother?

**Comment by soyuka** [comment]
Usually I do one data provider where I join every sources and return my DTO. You can use composition in your data providers but I'm not sure that there is an interest.

**Comment by dvc** [comment]
@soyuka , thank you for answer!

I'm not sure too. I want to avoid coupling between common and special staff of building DTO. May be something like option/interface "continue" or "last/final" for DataProvider. CurrentUserAwareProvider is "continue" provider. SomeEntityAwareProvider - final.

May be easier to do common staff by 'kernel.*' event listeners. But it`s not so semantic than "data provider", imho.

I can configure my own Middleware chain for every subset, but it wheel one more custom abstraction. Too complex for combine 2-3 handlers.

**Comment by soyuka** [comment]
> "The first able to retrieve data for a given resource will be used". No chain.

Indeed, you'd have to do this by your own ( a data provider that chains yours).

**Comment by dvc** [comment]
Ok. Thank you. Close
