### ISSUE TITLE
Update api/.env

### ISSUE THREAD

**Issue by javaDeveloperKid** [api-platform/api-platform#1013]
Flex recipe for mercure bundle was changed in https://github.com/symfony/recipes/commit/908e6c1175764bc63953bccca9add5d466b88613#diff-a3b7af206c48dd165e54c630069474faR5. Need to update api/.env, changing  
 `MERCURE_JWT=...`
to 
 `MERCURE_JWT_SECURE=...`

**Comment by maxhelias** [comment]
Fixed by #1023
