### ISSUE TITLE
Connection between api platform and sql server

### ISSUE THREAD

**Issue by MoctarEbnou** [api-platform/api-platform#1014]
Hello
I want to know how can we connect the platformform API to the SQL server database.
thank you in advance

**Comment by vincentchalamon** [comment]
Hi @MoctarEbnou,

The connection between API Platform & your database server is done using the `DATABASE_URL` environment variable:
https://github.com/api-platform/api-platform/blob/f176aafd4ccea28a53c96d27130e7c918a294a1a/api/.env#L26-L31

Please have a look at the [Configuring the Database](https://symfony.com/doc/current/doctrine.html#configuring-the-database) documentation on Symfony.
