### ISSUE TITLE
Get and verify user posts in graphQL

### ISSUE THREAD

**Issue by younesdiouri** [api-platform/api-platform#1015]
Hello everybody, 
I've been using successfully api-platform with REST, and now I've looked into GraphQL. I have a relative question about security : 
- I have a User Class and a Post class, (oneToMany) and with JWT access a user can query the posts.
If I want to restrict some users to query specific posts and not others, naturally I cannot do it in the frontend, otherwise anybody can change the user_id.

- So I've found that we cannot use the EventListener with graphQL because it works with resolvers, and that Doctrine Event with lifecycle could be an [alternative solution](https://github.com/api-platform/api-platform/issues/734). But [here](https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/best-practices.html#use-events-judiciously)  it says that using events could have a negative effect on performance, and sometimes unstable with relations and "postload" callback.

Do someone know what is the best practice in this case, to validate the user's request :)  as I am quite new to the graphQL world ^^.

Thank you for your time & kind help.

Younes

**Comment by alanpoulain** [comment]
See: https://api-platform.com/docs/core/graphql/#events
