### ISSUE TITLE
Issue with Deploying to a Kubernetes Cluster

### ISSUE THREAD

**Issue by tmorea05** [api-platform/api-platform#1016]
Hi everybody,

I am stuck with the Initializing the Database section.

Everything worked fine but when i try to initialize my database running : 

`
PHP_POD=$(kubectl --namespace=bar get pods -l app=php -o jsonpath="{.items[0].metadata.name}")
kubectl --namespace=bar exec -it $PHP_POD -- bin/console doctrine:schema:create
`

I got this issue : 

`
error: error executing jsonpath "{.items[0].metadata.name}": Error executing template: array index out of bounds: index 0, length 0. Printing more information for debugging the template:
	template was:
		{.items[0].metadata.name}
	object given to jsonpath engine was:
		map[string]interface {}{"items":[]interface {}{}, "metadata":map[string]interface {}{"selfLink":"", "resourceVersion":""}, "kind":"List", "apiVersion":"v1"}
`

What can i do about it ?

Do you have an idea how to solve this ?

Thanks a lot for your time :)

Thomas,
A dummy api platfom lover.

**Comment by teohhanhui** [comment]
Did you find a solution for this? It'd be good to comment so that others who encounter the same problem in the future can benefit. :smile:

**Comment by teohhanhui** [comment]
Hmm... I've noticed that the documentation uses 2 different namespaces (`bar` and `baz`), so I think that's wrong.

Did you use your own namespace? :)

**Comment by Elaynne** [comment]
I had the same issue from this workshop https://github.com/aws-samples/aws-workshop-for-kubernetes

with this comand:

**kubectl -n default port-forward $(kubectl -n default get pod -l name=nginx-pod -o jsonpath='{.items[0].metadata.name}') 8080:80**                                                                                

> error: error executing jsonpath "{.items[0].metadata.name}": array index out of bounds: index 0, length 0
> Error from server (NotFound): pods "Error" not found

I made it work manually:

**kubectl -n default port-forward pod/name-of-my-pod 8080:80**

And I have no problem if I just:

**kubectl get pods -o=jsonpath='{.items[0].metadata.name}'**
