### ISSUE TITLE
@ApiSubresource route overriding other collection routes with same path

### ISSUE THREAD

**Issue by toby-griffiths** [api-platform/api-platform#1022]
I've noticed that if you add a `collectionOperations` that uses the same path as an existing `@ApiSubresource`, then the route operation is missing from the generated Swagger docs.

I've found the workaround is to re-name the {id} parameter to something else, that does not clash with the `@ApiSubresource` path, but this took some working out.  It looks like the `\ApiPlatform\Core\Swagger\Serializer\DocumentationNormalizer::normalize()` method does not combine the routes together, but instead allows the `@ApiSubresource` version to overwrite the other routes.

I think that `\ApiPlatform\Core\Swagger\Serializer\DocumentationNormalizer::normalize()` (or it's dependencies) could do with updating to combine not overwrite the route docs.

**Comment by soyuka** [comment]
Should be moved to the `api-platform/core` repository

**Comment by toby-griffiths** [comment]
Is there an easy way to do that?

**Comment by soyuka** [comment]
I think there is something with the github beta program, can't access it @dunglas mb you could move the issue?

**Comment by soyuka** [comment]
Moved to https://github.com/api-platform/core/issues/2706

**Comment by toby-griffiths** [comment]
Thank you @soyuka
