### ISSUE TITLE
Docs for custom action with ApiResource response

### ISSUE THREAD

**Issue by vicdelfant** [api-platform/api-platform#1037]
The majority of our entities is exposed using regular resources, but we have a few sets of data that don't relate to an actual entity. An example would be a counter that simply returns the total number of orders. For these situations, using a custom action seems the way to go. The GET call itself is working properly, but after having gone through pretty much every issue about documenting custom actions, I'm still stuck :)

I know I can manually document the action by using a decorator (this works) and the `defaults` key in the route annotation, but since I have a ready-to-go `CounterResponse` resource I'd much rather use this class and have the documentation be auto-generated for consistency. Just like is done for the normal resources, actually.

So, the main question is: how can I get API Platform to add a `GET /statistics/counter` operation in the docs that lists the `CounterResponse` as its response, with as few as annotations as possible?

Adding the `CounterResponse` to the `api_platform.mapping.paths` config causes the usual CRUD calls to be generated as well. Disabling them by adding `collectionOperations={}, itemOperations={}` to the `ApiResource` annotation fixes the docs, but breaks the API because a resource is required to have an identifier (or at least, that's what the exception is about).

Here's what I have:

### Action
```php
final class CounterAction
{
    /**
     * @Route(path="/statistics/counter", name="api_statistics_counter", methods={"GET"}, defaults={
     *     "_api_resource_class": "Application\Response\Statistics\CounterResponse"
     * })
     *
     * @return CounterResponse
     */
    public function __invoke()
    {
        return new CounterResponse([
            'number' => 255,
        ]);
    }
}
```

### Resource
```php
/**
 * @ApiResource()
 */
final class CounterResponse extends DataTransferObject
{
    /**
     * @ApiProperty()
     *
     * @var int
     */
    public $number;
}
```

### Expected/actual API response
```json
{
    "number": 255
}
```

### Desired docs output (+ UI of course)
The trick seems to be the `$ref`:
```json
        "\/statistics\/counter": {
            "get": {
                "summary": "Retrieves a CounterResponse resource.",
                "parameters": [],
                "responses": {
                    "200": {
                        "description": "CounterResponse resource response",
                        "schema": {
                            "$ref": "#\/definitions\/CounterResponse"
                        }
                    }
                }
            }
        },
```

**Comment by soyuka** [comment]
A Resource can't be a Response it looks wrong. 

What version of ApiPlatform are you using ? From where do you read the  `counter` data from? Is it from the collection itself (`count($results)`) or are you issuing a query?

I'd declare the controller as:

```
@ApiResource(
  collectionOperations={"get", "post", "counter"={"method"="GET", "controller"=Controller::class, "path"="/orders/counter"}
)
```
