### ISSUE TITLE
Using serialization groups with custom data provider

### ISSUE THREAD

**Issue by abengtson** [api-platform/api-platform#1042]
I am having issues using normalization_context and denormalization_context in my entities when using a custom data provider.  I cannot get this to return my denormalization context instead it always returns the normalization context. Example:

Entity
```
/**
 * @ApiResource(
 *     itemOperations={
 *         "get"={
 *              "method"="GET",
 *              "path"="/user/{id}",
 *              "normalization_context"={"groups"={"read"}},
 *              "denormalization_context"={"groups"={"write"}}
 *          }
 *     }
 * )
 */
class AgentClientInformation
{
    /**
     * @var string
     * @ApiProperty(identifier=true)
     * @Groups("read")
     */
    public $id;

    /**
     * @var array
     *
     * @Groups("write")
     */
    public $clients = [];


    public function __construct(string $id)
    {
        $this->id = $id;

        $this->clients = ['test', '1234', 1234];
    }
}
```

Data Provider:
```
public function getItem(string $resourceClass, $id, string $operationName = null, array $context = []):MyObj
    {
        $myObj = new MyObj($id);

        return $myObj;
    }
```

This seems like a bug to me or I am doing something wrong.  THanks

**Comment by soyuka** [comment]
Normalization is for when you return data, it looks legit.

By the way I invite you to check symfony's documentation about the serializer: https://symfony.com/doc/current/components/serializer.html

**Comment by abengtson** [comment]
@soyuka Thanks for responding, I am a bit confused on how I would return the group "write" as the response to someone hitting my endpoint.  I want "read" to be what the api consumes then response to be "write"  I thought that was the purpose of these tags.  I may be understanding this completely wrong, so any advice would be appreciated.

**Comment by soyuka** [comment]
No problem, is your avatar the Rocket League champion rank logo?
