### ISSUE TITLE
Subresources in graphQL - iterable instead of correct type (OneToMany relationship)

### ISSUE THREAD

**Issue by Maxell92** [api-platform/api-platform#1043]
Hello,

I have an entity with a property that has a collection of another entities (OneToMany relationship):

```
/**
 * @ApiResource()
 */
final class Warehouse
{
	/**
	 * @var int
	 *
	 * @ApiProperty(identifier=true)
	 */
	private $id;

	/**
	 * @var Customer[]
	 *
	 * @ApiSubresource()
	 */
	private $customers = [];

	/**
	 * @return int
	 */
	public function getId(): int
	{
		return $this->id;
	}

	/**
	 * @return Customer[]
	 */
	public function getCustomers(): array
	{
		return $this->customers;
	}
}
```
```
/**
 * @ApiResource()
 */
final class Customer
{
	/**
	 * @var int
	 *
	 * @ApiProperty(identifier=true)
	 */
	private $id;

	/**
	 * @var Warehouse
	 */
	private $warehouse;

	/**
	 * @return int
	 */
	public function getId(): int
	{
		return $this->id;
	}

	/**
	 * @return Warehouse
	 */
	public function getWarehouse(): Warehouse
	{
		return $this->warehouse;
	}
}
```

Customer's schema is fine:

<img width="181" alt="Screenshot 2019-03-12 at 12 49 00" src="https://user-images.githubusercontent.com/1649279/54197830-45b13c00-44c5-11e9-9e24-81b9f88f8167.png">

However Warehouse's schema has `iterable` type instead of Customers collection:

<img width="169" alt="Screenshot 2019-03-12 at 12 49 09" src="https://user-images.githubusercontent.com/1649279/54197890-67aabe80-44c5-11e9-88d5-93a0a8ff9098.png">

I tried adding / removing `@ApiSubresource()` annotation on both entities, using `@Groups` annotation (from https://api-platform.com/docs/core/serialization/#embedding-relations) or defining `swagger_context` as suggested in https://github.com/api-platform/api-platform/issues/894#issuecomment-452710758:

```
	 * @ApiProperty(
	 *     attributes={
	 *         "swagger_context"={"type"="array", "items"={"$ref"="#/definitions/Customer"}}
	 *     }
	 * )
	private $customers = [];
```

I also tried to update to dev-master from v2.3.6.

Any idea what is wrong with my mapping and how to fix it?

**Comment by Maxell92** [comment]
Seems this is same issue: https://github.com/api-platform/api-platform/issues/836

**Comment by safwanghamrawi** [comment]
Did you find a solution to fix this problem ?
When I defined class as an Entity I dont have this problem when I remove the ORM annotation from the class I have this issue.

**Comment by olup** [comment]
Any updates on this ? We are facing similar issues and it is quite a problem to be able to consume api on client side and generate proper types

**Comment by olup** [comment]
@Maxell92 could you solve your problem eventually ?

**Comment by safwanghamrawi** [comment]
Unfortunately, we use ORM annotation in our classes to have the right graphql schema with the relation but I dont think that is a good solution

**Comment by GLacourt** [comment]
Well i ran into the same issue and i take a couple of days to fix it. First when you use the phpdoc `Customer[]` it will resolve your type as iterable whatever you add `@ApiSubresource`.  If you want to resolve this problem you must use this syntax `Collection<Customer>`, take care to import `Collection` we a correct `use Doctrine\Common\Collections\Collection;`. If you stay here you should have an error, this is because API Platform use the version 0.3 or 0.4 of `phpdocumentor/type-resolver` and  you must use the version 0.5 at least. It works for me, hope it will help you

**Comment by alanpoulain** [comment]
Thank you for the workaround @GLacourt.
It should be fixed in the next patch version of API Platform.
