### ISSUE TITLE
POST new data by id not URI

### ISSUE THREAD

**Issue by AbdelilahJbr** [api-platform/api-platform#1047]
Hello

I have an entity Collaborator who has a relation with an other entity Imputation,
Is there anyway to post a new collaborator by giving the id not the URI,

Using this : 
![image](https://user-images.githubusercontent.com/44052672/54340871-a44af700-4638-11e9-8122-9c09ab8810e4.png)

Instead of this:
![image](https://user-images.githubusercontent.com/44052672/54340899-ba58b780-4638-11e9-9317-482805190998.png)

**Comment by soyuka** [comment]
Hi,
please read:

https://github.com/api-platform/core/issues/2521 

Although we definitely do not recommend that see https://github.com/api-platform/core/pull/2022#issuecomment-398851861
