### ISSUE TITLE
api platform Variable "showWebby" does not exist.

### ISSUE THREAD

**Issue by Belssem** [api-platform/api-platform#1048]
i've installed api platfrom using composer require api 
and i'm using Mongodb and document so when i navigate to localhost:8000/api I got this problem Variable "showWebby" does not exist. any solution plz ??

**Comment by alanpoulain** [comment]
Are you using the beta version of API Platform? You need to use it if you want the MongoDB support.

**Comment by AbdelilahJbr** [comment]
> Are you using the beta version of API Platform? You need to use it if you want the MongoDB support.

@alanpoulain I'm using doctrine mysql and I also got this problem Variable "showWebby" does not exist

**Comment by Belssem** [comment]
how can i install it plz?

**Comment by alanpoulain** [comment]
@AbdelilahJbr because the variable "showWebby" is only available for the beta.

**Comment by Belssem** [comment]
This is what my composer.json file looks like : 
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "alcaeus/mongo-php-adapter": "^1.1",
        "api-platform/api-pack": "^1.2",
        "doctrine/mongodb-odm-bundle": "^3.5",
        "doesntmattr/mongodb-migrations-bundle": "^2.0",
        "mongodb/mongodb": "^1.4",
        "sensio/framework-extra-bundle": "^5.2",
        "symfony/asset": "4.2.*",
        "symfony/console": "4.2.*",
        "symfony/dotenv": "4.2.*",
        "symfony/expression-language": "4.2.*",
        "symfony/flex": "^1.1",
        "symfony/form": "4.2.*",
        "symfony/framework-bundle": "4.2.*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/orm-pack": "*",
        "symfony/process": "4.2.*",
        "symfony/security-bundle": "4.2.*",
        "symfony/serializer-pack": "*",
        "symfony/swiftmailer-bundle": "^3.1",
        "symfony/translation": "4.2.*",
        "symfony/twig-bundle": "4.2.*",
        "symfony/validator": "4.2.*",
        "symfony/web-link": "4.2.*",
        "symfony/yaml": "4.2.*"
    },
    "require-dev": {
        "symfony/debug-pack": "*",
        "symfony/maker-bundle": "^1.0",
        "symfony/profiler-pack": "*",
        "symfony/test-pack": "*",
        "symfony/web-server-bundle": "4.2.*"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true,
        "platform": {
            "ext-mongo": "1.6.16"
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "4.2.*"
        }
    }
}
should i just modify it by adding  "api-platform/api-pack": "^2.4@beta", in requires ?? and then i update the composer ?

**Comment by dunglas** [comment]
Can you paste the full stack trace, and `config/packages/api_platform.yaml` please? It's weird that the `showWebby` variable is used, it shouldn't be the case by default.

**Comment by Belssem** [comment]
this is the content of "config/packages/api_platform.yaml"
api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity','%kernel.project_dir%/src/Document']

and this is again the composer.json file content : 
{
    "type": "project",
    "license": "proprietary",
    "require": {
        "php": "^7.1.3",
        "ext-ctype": "*",
        "ext-iconv": "*",
        "alcaeus/mongo-php-adapter": "^1.1",
        "api-platform/api-pack": "^1.2",
        "doctrine/mongodb-odm-bundle": "^3.5",
        "lexik/jwt-authentication-bundle": "^2.6",
        "sensio/framework-extra-bundle": "^5.2",
        "symfony-bundles/odm-fixtures-bundle": "^0.5.3",
        "symfony/asset": "4.2.*",
        "symfony/console": "4.2.*",
        "symfony/dotenv": "4.2.*",
        "symfony/expression-language": "4.2.*",
        "symfony/flex": "^1.1",
        "symfony/form": "4.2.*",
        "symfony/framework-bundle": "4.2.*",
        "symfony/monolog-bundle": "^3.1",
        "symfony/orm-pack": "*",
        "symfony/process": "4.2.*",
        "symfony/security-bundle": "4.2.*",
        "symfony/serializer-pack": "*",
        "symfony/swiftmailer-bundle": "^3.1",
        "symfony/translation": "4.2.*",
        "symfony/twig-bundle": "4.2.*",
        "symfony/validator": "4.2.*",
        "symfony/web-link": "4.2.*",
        "symfony/yaml": "4.2.*"
    },
    "require-dev": {
        "doctrine/doctrine-fixtures-bundle": "^3.1",
        "fzaninotto/faker": "^1.8",
        "symfony/debug-pack": "*",
        "symfony/maker-bundle": "^1.0",
        "symfony/profiler-pack": "*",
        "symfony/test-pack": "*",
        "symfony/web-server-bundle": "4.2.*"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "sort-packages": true,
        "platform": {
            "ext-mongo": "1.6.16"
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/"
        }
    },
    "replace": {
        "paragonie/random_compat": "2.*",
        "symfony/polyfill-ctype": "*",
        "symfony/polyfill-iconv": "*",
        "symfony/polyfill-php71": "*",
        "symfony/polyfill-php70": "*",
        "symfony/polyfill-php56": "*"
    },
    "scripts": {
        "auto-scripts": {
            "cache:clear": "symfony-cmd",
            "assets:install %PUBLIC_DIR%": "symfony-cmd"
        },
        "post-install-cmd": [
            "@auto-scripts"
        ],
        "post-update-cmd": [
            "@auto-scripts"
        ]
    },
    "conflict": {
        "symfony/symfony": "*"
    },
    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "4.2.*"
        }
    }
}

**Comment by Belssem** [comment]
how can i install the version 2.4 beta of the api platform ??

**Comment by dunglas** [comment]
@Belssem `composer require api-platform/core ^2.4@beta`

**Comment by Belssem** [comment]
@dunglas  i will download it now , i hope will works this time

**Comment by Belssem** [comment]
@dunglas  Thank you it works now  :D
