### ISSUE TITLE
Call API Platform default operations from a custom ones

### ISSUE THREAD

**Issue by tchafack** [api-platform/api-platform#1051]
Hello,
It's more a question than an issue.
I'm working on security zone. After spending days on Symfony and API Platform docs, i realised that my concern is particula. 
Talking about security in Symfony, I think it's cool for small or internal projects. We can add/remove profiles/roles like we want.

I want to do something special. I want user or client (who is not dev) to be able via the back office, add new profiles and assign rights. I use security zone instead of roles directly. I want to protect my actions(controller) under security zone. 

Each controller gets "getSecurityZone()" method which can allow me to check that first (onkernel event) to see if the current user has rights (depending on their -unique- role/profile) on the ressource.

    public function securityZone(): string
    {
        return 'BO_ZONE';
    }

My concern: I don't want to rewrite the logic to retrieve data since API Platform already does it. So i tried to use event to run my security check. It seems working but How to call default operation (like GET) from my action ?

My entity :

 

     *      },
     *      collectionOperations={
     *          "get"={
     *              "method"="GET",
     *              "path"="/users",
     *              "controller"=UserListAction::class,
     *              "defaults"={"_api_receive"=false},
     *              "swagger_context"={
     *                  "parameters"={
     *
     *                  }
     *              },
     *          },
     *          "post"
     *      }
     * )
     * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
     * @ORM\Table(name="users")
     */
    class User implements UserInterface
    {

My eventlistener :

    public static function getSubscribedEvents()
    {
        return [
            KernelEvents::VIEW => ['encodePassword', EventPriorities::PRE_WRITE],
            KernelEvents::CONTROLLER => ['micheckSecurity', EventPriorities::PRE_READ],
        ];
    }
    
    //..
    
    public function micheckSecurity(FilterControllerEvent $event)
    {
        $controller =  $event->getController();
        $method = $event->getRequest()->getMethod();
    
        if (Request::METHOD_GET !== $method || $controller->getSecurityZone() !== Constants::SECZONE_BO_ZONE)
            throw new AccessDeniedException("You are not author", 500);
        return;
    }

And my action(controller) :

    class UserListAction
    {
        public function __invoke()
        {
            //Call default operation which return collection
        }
    
        public function securityZone(): string
        {
            return 'BO_ZONE';
        }
    
    }

In my _invoke() method, I want to call the read method of API Platform which will return the collection automatically.

Thank you for your attention.

**Comment by vincentchalamon** [comment]
Hello @duhamelstuff,
If I understood correctly your need, you want to restrict users access to an operation depending on user roles? If so, you should use [access_control directives](https://api-platform.com/docs/core/security/#security).

For example, to restrict `POST /users` to admin, and `GET /users` to users with `ROLE_BO_ZONE` role:
```php
 *      },
 *      collectionOperations={
 *          "get"={"access_control"="is_granted('ROLE_USER') and is_granted('ROLE_BO_ZONE')"},
 *          "post"={"access_control"="is_granted('ROLE_ADMIN')"}
 *      }
 * )
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(name="users")
 */
class User implements UserInterface
{
```

**Comment by duhamelstuff** [comment]
Hello @vincentchalamon,
Thank you, I saw this in the doc and I realised now that I probably asked for 2 types of questions.

1. Use API Platform default operation in my action to avoid rewrite thething (specially for read operations). Actually here is how I did : 
**My service** : _I use API Platform data provider_
``` PHP
   /**
   * @var CollectionDataProviderInterface
   */
    private $collectionDataProvider;

    /**
    * UserService constructor.
    * @param CollectionDataProviderInterface $collectionDataProvider
    */
    public function __construct(CollectionDataProviderInterface $collectionDataProvider)
    {
        $this->collectionDataProvider = $collectionDataProvider;
    }

    /**
     * Retrieves data for a collection operation.
     *
     * @return iterable|null
     * @throws \ApiPlatform\Core\Exception\ResourceClassNotSupportedException
     */
     public function getList(string $className)
     {
         return $this->collectionDataProvider->getCollection($className);
     }
 ```

And here is my controller : 

```PHP
   class UserListAction extends BaseAction
   {
       public function __invoke(UserService $userService)
       {
           return $userService->getList(User::class);
       }
   ...
   }
```
Question: is it a rihgt way ?

2. Protect operation depending on user profiles : 
I think what Symfony and API Platform offer is good but not enough (I think) for what I need. I try to explain :sweat_smile: 
We can protect a controller from some roles. Each time we want to update the limitation, we have to update our codes. 2 concerns for me : we need to check every controller to add or remove roles. And as a dev, if my client need to update the access rights to its app, they need to call me to do that (yeah, it's more money for me but it's boring).
What I need : embed my controllers in a "zone" and give users rights on; and my client from the admin dashboard can simple create new profiles (instead of updating the source code) and set right.
I did something and it work, until now. Here it is : 
**My action/operation/controller** : _I embed it in a zone_
```PHP
   class UserListAction extends BaseAction
   {
       ...
       public function getSecurityZone(): string
       {
           return Constants::BO_ZONE;
       }
   }
```

**A EventSubscriber** : _It's a kind of listener before execution of any controller. I check if the user has right on the operation_
```PHP
class SecurityListener implements EventSubscriberInterface
{
    private $entityManager;
    private $user;

    public function __construct(EntityManagerInterface $em,
                                TokenStorageInterface $tokenStorage)
    {
        $this->entityManager = $em;

        if ($tokenStorage->getToken() === null || ! ($tokenStorage->getToken()->getUser() instanceof User)) {
            $this->user = null;
        }
        else {
            $this->user = $tokenStorage->getToken()->getUser();
        }
    }

    public function onKernelController(FilterControllerEvent $event)
    {
        $controller = $event->getController();

        /*
         * $controller passed can be either a class or a Closure.
         * This is not usual in Symfony but it may happen.
         * If it is a class, it comes in array format
         */
        if ($controller instanceof BaseAction)
        {
            if($this->user === null)
                throw new AccessDeniedHttpException(Constants::MSG_NOAUTHORISED);

            $right = $this->getSecurityAccess($this->user->getProfile(), $controller->getSecurityZone());

            if ($right == Constants::SECURITY_NOACCESS)
                throw new AccessDeniedHttpException(Constants::MSG_NOAUTHORISED);

            if (($event->getRequest()->getMethod() != 'GET') && ($right == Constants::SECURITY_READONLY))
                throw new AccessDeniedHttpException(Constants::MSG_NOAUTHORISED);
        }
    }

    ...
```
For the moment it works, and have I done done something wrong ? I'll be pleased to know :smile: 
Thank you.

**Comment by vincentchalamon** [comment]
Basically, your UserService::getList is just a decoration of the CollectionDataProvider::getCollection, so this service seems useless to me. You can directly inject the CollectionDataProvider in your UserListAction.

As your action is defined as a read-only collectionOperation, API Platform will automatically get the collection. Your UserListAction has basically the same behavior than the default one (calling the collectionDataProvider and return its result), so it's useless in your example. The only reason to do so is your second point: the necessity to use a custom security inside the controller.

About security, I still think the access_control is a better approach. As you apply the _SecurityZone_ in your controller, and you know which controller is executed by operation, you can easily move it to the access_control:
* `if($this->user === null)` is the same as `is_granted('ROLE_USER')`
* `$this->getSecurityAccess(...)` is the same as `is_granted('ROLE_BO_ZOLE')` with a custom voter
* `Constants::SECURITY_READONLY` is the same as `is_granted('ROLE_BO_READ_ONLY')` with a custom voter

```php
 *      },
 *      collectionOperations={
 *          "get"={"access_control"="is_granted('ROLE_USER') and is_granted('ROLE_BO_ZONE') is_granted('ROLE_BO_READ_ONLY')"},
 *          "post"
 *      }
 * )
```
Then, create a custom voters for `ROLE_BO_ZONE` & `ROLE_BO_READ_ONLY`.

This also has the advantage that you could use this security outside of your subscriber, and just use the security component as it should be :-)

**Comment by duhamelstuff** [comment]
Hello,
I absolutely with you that for this example it's useless. :sweat_smile:  For writing operation I can do some stuffs before; by the way for reading too. 

For security, how it would allow an end-user to update users access rights to some operations straight from they dashboard ? I want the user to be able (whenever) to change them without needing to update the source code.
Thanks

**Comment by vincentchalamon** [comment]
Just create as roles as you need in your application ([security roles hierarchy](https://symfony.com/doc/current/security.html#security-role-hierarchy)), and map them in the `roles` property on your User entity, saved as array in your database.

While loading the current user, Symfony security will load its roles from your entity, allowing you to call `is_granted` to check them: https://symfony.com/doc/current/security.html#roles. With this solution, you even won't need any custom voter!

Your admin user will be able to update the user roles through an [admin interface](https://api-platform.com/docs/admin/), and the only time you'll need to modify the code will be once you'll add new features with their new according roles.

**Comment by duhamelstuff** [comment]
Yes, I understand. in this case, I can effectively do like that.  
And how will the user do to add roles additional to those already existing, knowing that they should not to call a dev ?

**Comment by vincentchalamon** [comment]
What do you mean by `those already existing`? Don't they already have a User.roles property filled?

**Comment by duhamelstuff** [comment]
When developing, I can define ROLE_ONE, ROLE_TWO, ROLE_THREE and I use them as in the access_control.
What if months later, the user wants to add another type of profile, a fourth role (ROLE_FOUR)? Will they call the dev to update the code to add that role or can add the role directly in the admin interface?

**Comment by vincentchalamon** [comment]
If later you need a `ROLE_FOUR`, it means there is a new security written somewhere in your code, near a controller (or any feature), right?

**Comment by duhamelstuff** [comment]
Not necessarily (anyway, that's what I want). Controllers and code stay the same.
They should be on the user dashboard (no need to modify the code) a way to set rights access (on **existing**  controllers).
The security stay the same as well. In this case, we should have 3 things :
- a user role (as now)
- a security zone for my controllers (as **access_control**, not really)
- and, the most important, the right (level, which can be 0, 1 or 2) of any user with a certain role on a controller under any security zone.
In this case, use can create limitless roles (profiles) and assign rights ; all from their dashboard, no need to modify the code (I feel like I repeat myself :sweat_smile:)
The only moment we will need to update our code will be to add or update a feature.
