### ISSUE TITLE
GraphQL: Sorting nested ManyToMany relation not possible (?)

### ISSUE THREAD

**Issue by Coksnuss** [api-platform/api-platform#1052]
Suppose I have two entities `Song`' and `Playlist` whereas one Song can belong to many Playlists and vice versa. Lets say I want to retrieve a specific playlist with the first five songs, ordered alphabetically in descending order.

For this, I declare an OrderFIlter on the Playlist entity as follows:
```
@ApiFilter(OrderFilter::class, properties={"songs.title"})
```

In the GraphiQL interface, I can now issue the following query:

```
query findPlaylistWIthPaginatedSongs($id: ID!, $cursor: String) {
  playlist(id: $id, order: { songs_name: "DESC" } ) {
    title
    songs(first: 10, after: $cursor, order: { songs_name: "DESC" }) {
      edges {
        node {
          _id
          title
        }
      }
    }
  }
}
``` 

The "order" field is offered for both the root-level collection (`playlist`)  and the nested relation query (`songs`). However, neither of them (in any combination) do have any effect on the returned songs and their order. They are always returned in ascending order, according to their ID.

Is this a bug? Am I missing something? Is there a workaround?

**Comment by alanpoulain** [comment]
Fixed here: https://github.com/api-platform/core/pull/2976
