### ISSUE TITLE
Cannot return resource as output from Symfony MessageHandler

### ISSUE THREAD

**Issue by Devristo** [api-platform/api-platform#1060]
This project is making me quite happy so far! Thank you for that. On the 2.4 branch I hit the following issue:

**Description**
Cannot return resource from MessageHandler when using a DTO as input class.

Perhaps related to: https://github.com/api-platform/core/issues/2550

**Steps to reproduce**
Use latest HEAD of 2.4 branch.  Then follow the approach of https://gist.github.com/soyuka/312526207073dc0edb6add81d15f6249 with the following changes:

 - Return an instance of `Todo` in `InputTodoHandler`
 - Remove the `output=false` line in the `Todo` resource 

Perform a `POST /todo`. And you will get the following error:

`No item route associated with the type "App\\Entity\\InputTodo"`

**Expected result**
The created TODO resource.

Am I doing something wrong?  I managed to make it 'work' by adjusting the following snippet in `WriteListener`.

```php
case 'POST':
    $persistResult = $this->dataPersister->persist($controllerResult, $attributes);

    if (null === $persistResult) {
        @trigger_error(sprintf('Returning void from %s::persist() is deprecated since API Platform 2.3 and will not be supported in API Platform 3, an object should always be returned.', DataPersisterInterface::class), E_USER_DEPRECATED);
    }

    $event->setControllerResult($persistResult ?? $controllerResult);

    if (null === $this->iriConverter) {
        return;
    }

    $hasOutput = true;
    if (null !== $this->resourceMetadataFactory) {
        $resourceMetadata = $this->resourceMetadataFactory->create($attributes['resource_class']);
        $outputMetadata = $resourceMetadata->getOperationAttribute($attributes, 'output', ['class' => $attributes['resource_class']], true);
        $hasOutput = \array_key_exists('class', $outputMetadata) && null !== $outputMetadata['class'];
    }

    if ($hasOutput) {
        $request->attributes->set('_api_write_item_iri', $this->iriConverter->getIriFromItem($controllerResult));
    }
```

Such that the last if-statement is (note the `$persistResult ?? $controllerResult`):

```php
if ($hasOutput) {
    $request->attributes->set('_api_write_item_iri', $this->iriConverter->getIriFromItem($persistResult ?? $controllerResult));
}
```

Is this the bug or am I doing something wrong?

**Comment by soyuka** [comment]
I'll definitely try this in correlation with api-platform/core#2550 this afternoon and let you know my findings. Thanks for the report.

**Comment by Devristo** [comment]
Just a follow up: the fix above does not work as the response is not in json+ld/hydra format but just a plain object :/

**Comment by soyuka** [comment]
https://gist.github.com/soyuka/8a2ce9aeaac5b5d8df2a32791e2cf2da

Needs the following patch: https://github.com/api-platform/core/pull/2628
