### ISSUE TITLE
Building custom endpoint aggregating multiple Entities

### ISSUE THREAD

**Issue by Benew** [api-platform/api-platform#1061]
I'm building a Booking api. The core has 4 models.
- Product
- WeeklySlot (has one product, a day of week, timeStart and timeEnd)
- Slot (has one product, date, timeStart and timeEnd)

I need to provide a custom ApiResource, a 'virtual' endpoint aggregating `WeeklySlot`s and `Slot`s for a given period of time and optionally for a specific product.

`GET /calendar?startDate=&endDate=&product=` should return all available `WeeklySlot`s and `Slot`s between the two dates

What design pattern should I follow ? It's not a custom operation I know that now.

I'm very new to ApiPlatform and I'm struggling to find the right info.

I'm using Symfony 4.2 and `api-platform/api-pack` version 1.2

**Comment by patrickbussmann** [comment]
I'm interested in this, too.
Needed for a dashboard.
Instead having 4 calls (Products, Customers, Partners and Items) I want a custom controller which returns an array with the different entities.

**Comment by soyuka** [comment]
> a 'virtual' endpoint aggregating WeeklySlots and Slots for a given period of time and optionally for a specific product.

Sounds to me that you could fix this with a custom controller. 

Another solution would be to have a read-only aggregated resource (`calendar` might be one) that would have a custom data provider and where you'd disable the writeability (see documentation).
