### ISSUE TITLE
Kubernetes: Helm charts for Mercure setup?

### ISSUE THREAD

**Issue by comxd** [api-platform/api-platform#1063]
The new 2.4 version introduce Mercure support but seem not include the Helm charts for K8s support.

Current chart provided by @dunglas is here: https://hub.helm.sh/charts/stable/mercure

**Comment by pborreli** [comment]
will be fixed by #1066

**Comment by vincentchalamon** [comment]
https://github.com/api-platform/api-platform/pull/1066 has been merged, Helm chart documentation is available here: https://hub.helm.sh/charts/stable/mercure.
