### ISSUE TITLE
Getting Started - Testing PHPUnit Fails

### ISSUE THREAD

**Issue by develth** [api-platform/api-platform#1065]
Hello,

i just stepped through your getting started and reached the testing section. 
Sadly the execution of PHPUnit fails, if i go for the Code in the Document.

It always says:

    Error: Call to a member function getContainer() on null

This is caused in 

        $this->client = static::createClient();

Any ideas how to fix it?

Thanks!

**Comment by dunglas** [comment]
@develth We need a new release of `hautelook/alice-fixtures-bundle`. In the meantime, you can use the `dev-master` version.

**Comment by develth** [comment]
Switching ```hautelook/alice-bundle```to ```dev-master```fixed it.

Thanks
