### ISSUE TITLE
[Question] What is the best approach to create a route to check account user with confirmation email ?

### ISSUE THREAD

**Issue by AlexandreHagen** [api-platform/api-platform#107]
Hi

I need to create a route, with ```Api-platform v2``` and ```FosUserBundle```, to enable the user account after his registration.
However, I not sure which is the better solution.

- Create it own controller linked to ```User``` entity (custom operations)
- Create it own controller not linked to any entities (custom operations)
- Use ```FosRestBundle``` to create an Api Rest route (Very bad for my point of view) 

One of you have already done that ? Or have any ideas ?

**Comment by teohhanhui** [comment]
What about just doing a `PUT /users/{id}` with `"enabled": true` (or similar) as part of the body? Of course you'd also need an authentication token.

**Comment by AlexandreHagen** [comment]
Thanks @teohhanhui ! Indeed this one solution ! But how to pass and check the  ```confirmation_token``` ? For me, I think that the best solution I will be to have a route like : ```PUT: /users/{token}``` It is possible to generate several PUT routes for the same entity ? So have ```PUT: /users/{token}``` and ```PUT: /users/{id}``` in same time.

**Comment by teohhanhui** [comment]
`PUT /users/{token}` is definitely semantically wrong. The token is not an identifier for the user resource.

**Comment by teohhanhui** [comment]
> But how to pass and check the confirmation_token ?

Perhaps through the `Authorization` HTTP header. By `confirmation_token` I assume you're referring to the one generated by FOSUserBundle. Actually I'd suggest thinking about this in a different way: https://github.com/api-platform/core/issues/567#issuecomment-224572446

**Comment by AlexandreHagen** [comment]
Already I will try that way. Thanks @teohhanhui for your advices.
