### ISSUE TITLE
Api Platform installs : separate services in different docker-compose + .env-dist instead of .env

### ISSUE THREAD

**Issue by sushicodeur** [api-platform/api-platform#1073]
Hello,

I've been installing quite e few api-platform for many projects recently, and every time I start by modifying how docker-compose files are organized and ignoring .env and replace them with .env-dist so that no password or env dependent data gets versioned.

What I do with docker-compose is : 

* adding a `COMPOSE_FILE=docker-compose.yml:docker-compose.admin.yml:docker-compose:client.yml:...` in the root .env that includes only the services I want based on the env I'm in (dev, staging, prod, ...)
* split docker-compose.yml in many docker-compose.{service-name}.yml so I can `docker-compose up` the services I want
* add a docker-compose.dev.yml with tools I use in dev (essentially pgadmin)

Then I replace in docker-compose every sensible and env dependent data (passwords, ports, urls, ...) by .env variables

I think this has been discussed, but shouldn't Api Platform be shipped in such a way ?

**Comment by teohhanhui** [comment]
> every time I start by modifying how docker-compose files are organized and ignoring .env and replace them with .env-dist so that no password or env dependent data gets versioned.

I agree, but we cannot do that here, because we want to have "zero-setup". But I'd like to change things up a bit though, to be more similar to what I've done in https://github.com/Sylius/Sylius-Standard

> split docker-compose.yml in many docker-compose.{service-name}.yml so I can docker-compose up the services I want

No. You can always do `docker-compose up {service}`

**Comment by sushicodeur** [comment]
Thank you @teohhanhui 

I was sure it has been discussed, thanks for the clarification.

I still prefer a `docker-compose up` that already knows what service to launch, but, ok, will take time to tweak the config as I like it every time :)

Thank you.

**Comment by teohhanhui** [comment]
> I still prefer a docker-compose up that already knows what service to launch

I don't understand your point. The `docker-compose.yml` is supposed to declare all the services. Of course, you could have different files for different environments, but it doesn't make sense to have each service declared in a separate file.
