### ISSUE TITLE
[Bug] MetadataAwareNameConverter name converter not working

### ISSUE THREAD

**Issue by raresserban** [api-platform/api-platform#1075]
Hello,
I just upgraded from ApiPlatform 2.4 beta.1 to Api Platform 2.4.2 and the name converter is broken.
Before, the MetadataAwareNameConverter service was used, as per the documentation, and my properties were serialized using camelCase.
Now, they are serialized using snake_case while I didn't do any changes to my application.
I tried putting the `serializer.name_converter.metadata_aware` service both in the symfony serializer configuration and in the api platform configuration, but if I do so I get a `Circular reference detected for service "serializer.name_converter.metadata_aware` exception. I also tried with the `api_platform.name_converter` alias and still the same error...
What happened?It worked perfectly before...

**Comment by raresserban** [comment]
I managed to get camelCase working again by using this in the api platform configuration:
`name_converter: 'Symfony\Component\Serializer\NameConverter\MetadataAwareNameConverter'`

Still, the docs say that this should be the default and it clearly isn't anymore...

**Comment by teohhanhui** [comment]
See also https://github.com/api-platform/core/issues/2677

**Comment by soyuka** [comment]
superseeded by https://github.com/api-platform/core/issues/2677
