### ISSUE TITLE
Change denormalization context based on role (v2)

### ISSUE THREAD

**Issue by polc** [api-platform/api-platform#108]
Is there a way to make a resource property visible and editable only by admins (user with `ROLE_ADMIN`) ? 

I know I can create a custom validator for the editable part.

**Comment by teohhanhui** [comment]
And how would we declare it? What do you have in mind?

**Comment by polc** [comment]
I need a lot of flexibility for my use case something like that using Expression Language could work maybe: `@ApiProperty(readableAccessControl="has_role('ROLE_USER') or resource.isPublic == true")`

**Comment by dunglas** [comment]
Can't you use a custom denormalizer to do that?

**Comment by polc** [comment]
Yes I didn't thought about a denormalizer before https://github.com/api-platform/core/issues/583 discussion. But It would be very nice to have this supported out of box. 

I think it's a common use case, for my project for example I have the following use case: 

- Private note on users by admins
- Private user information viewable only by the user and the Super admin
- Public Group (name/description/members) but with private $conversations (I imagine something like `@ApiProperty(writableAccessControl="user in resource.members", readableAccessControl="user in resource.members")`

**Comment by soyuka** [comment]
I'm don't agree to the `has_role` thing tough. My roles are slightly more complicated than that and can't be gathered to a simple `ROLE_ADMIN`/`ROLE_USER`. If it's embedded, it'd have to be more powerful imo.

**Comment by polc** [comment]
It's easy to expose `is_granted `with ExpressionLanguage.

**Comment by polc** [comment]
What core developers think about this ? Good idea to implement or not common enough use case ?

**Comment by theofidry** [comment]
I find it tricky: there is a common use case when you have "simple" roles, but you can quickly end up with much more complex roles and for which the system you are thinking of might not be good enough, because it becomes too specific to the use case.

My fear is that we accept to support an "easy and common use case", but as more user are using it, keep requesting more feature to it. Moreover, this feature would apply to the Symfony bridge only. Maybe it would be better to have this feature in a dedicated bundle instead.

**Comment by teohhanhui** [comment]
I think we should instead look into out-of-the-box integration with Symfony Workflow (new component in 3.2), as suggested by @dunglas in https://github.com/api-platform/core/issues/583#issuecomment-228659741

Meanwhile, just use custom denormalizers. But then again @dunglas said it's a bad idea here: https://github.com/api-platform/core/pull/584#issuecomment-228742890 :stuck_out_tongue:

**Comment by Simperfit** [comment]
@polc does @teohhanhui answer to your question ?

**Comment by polc** [comment]
It can now be achieved using dynamic serialization context : https://api-platform.com/docs/core/serialization-groups-and-relations#changing-the-serialization-context-dynamically 

Symfony Workflow component integration is a good idea but not a priority I guess^^
