### ISSUE TITLE
Input / output at the operations level

### ISSUE THREAD

**Issue by kpn13** [api-platform/api-platform#1080]
Hi,

What do you think about moving the "input" and "output" properties at the operations level ?

Because I think it is something possible to have differents data representations depending of the operations. Whould you be against a PR about that? (no idea how difficult it is) 

An example of what it could look like : 

```
/**
 * @ApiResource(
 *     itemOperations={
 *          "put" = {"path"="/foo/{id}/bar", "input"=BookInputPut::class}
 *          "post" = {"path"="/foo/{id}/barfoo", "input"=BookInputPost::class}
 *     },
 * )
 */
```

**Comment by soyuka** [comment]
It's already supported

**Comment by kpn13** [comment]
Whoo amazing. Thanks
