### ISSUE TITLE
Best practice to include a COUNT query in collection operation

### ISSUE THREAD

**Issue by superbull** [api-platform/api-platform#1083]
In case I have below Entities:

```php
class Book
{
    private $id;
    private $title;
    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Review", mappedBy="book")
     */
    private $reviews;
}

class Review
{
    private $id;
    private $body;
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Book", inversedBy="reviews")
     */
    private $book;
}
```

When I retrieve a list of Books, I want also the **total number of the reviews** a book contains. The response should like below:
```json
{
  "hydra:member": [
    {
      "@id": "/books/e0820d66-81cd-4e48-8b09-f2931a39951b",
      "@type": "http://schema.org/Book",
      "title": "345",
      "reviewsCount": 20
    }
  ]
}
```

What is the right way to implement this in API Platform?

**Comment by teohhanhui** [comment]
Ideally, it should be something like:

```json
{
  "hydra:member": [
    {
      "@id": "/books/e0820d66-81cd-4e48-8b09-f2931a39951b",
      "@type": "http://schema.org/Book",
      "title": "345",
      "reviews": {
        "@id": "/books/e0820d66-81cd-4e48-8b09-f2931a39951b/reviews",
        "@type": "hydra:Collection",
        "hydra:totalItems": 20
      }
    }
  ]
}
```

**Comment by superbull** [comment]
Yes, it looks better.  
And then I found this might be related to the issue https://github.com/api-platform/core/issues/1686

**Comment by vincentchalamon** [comment]
Closing as a solution has been found on https://github.com/api-platform/core/issues/1686

**Comment by silviodeligios** [comment]
> Ideally, it should be something like:
> 
> ```json
> {
>   "hydra:member": [
>     {
>       "@id": "/books/e0820d66-81cd-4e48-8b09-f2931a39951b",
>       "@type": "http://schema.org/Book",
>       "title": "345",
>       "reviews": {
>         "@id": "/books/e0820d66-81cd-4e48-8b09-f2931a39951b/reviews",
>         "@type": "hydra:Collection",
>         "hydra:totalItems": 20
>       }
>     }
>   ]
> }
> ```

hi, i'm trying to achieve this but i can't figure out how to do it. Is this possible? Where can i found some documentation about it?
