### ISSUE TITLE
There is no PropertyInfo extractor

### ISSUE THREAD

**Issue by stipic** [api-platform/api-platform#1085]
When i made PUT/POST/... request on my entity

page_blocks

i get this error:

"There is no PropertyInfo extractor supporting the class \"stdClass\"."

```
"file": "/vendor/api-platform/core/src/Bridge/Symfony/PropertyInfo/Metadata/Property/PropertyInfoPropertyNameCollectionFactory.php",
            "line": 46,
```

Postman request:

PUT: /api/page_blocks
raw body:
```
{  
   "page":"/api/pages/2020",
   "type":"image",
   "draggable":true,
   "name":"featured_image",
   "label":"Header Featured Image",
   "description":"",
   "status":0,
   "content":"{\"fields\":{\"title\":{\"value\":\"\"},\"images\":[{\"id\":0,\"categoryId\":0,\"uri\":\"/api/pictures\",\"resource\":\"{}\",\"description\":\"\",\"alt\":\"\",\"type\":\"picture\",\"text\":\"\",\"src\":\"\"}],\"alternativeAudio\":{},\"caption\":\"\"},\"showCaption\":false,\"alternativeContent\":false,\"alternativeAudioContent\":false,\"blockLayout\":\"default\"}",
   "renderOrder":6,
   "groupName":"header",
   "className":"ImageBlockComponent",
   "parentId":0
}
```

**Comment by teohhanhui** [comment]
You have a `\stdClass` somewhere that you're trying to serialize?

**Comment by teohhanhui** [comment]
The code should only be run for `@ApiResource`, so something is not right...

**Comment by stipic** [comment]
@teohhanhui thanks for reply.

I really don't know where i use \stdClass
this is my entity:

`<?php
namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Gedmo\Mapping\Annotation as Gedmo;

/**
 * @ApiResource
 * @ORM\Entity(repositoryClass="App\Repository\PageBlockRepository")
 * @ORM\HasLifecycleCallbacks
 */
class PageBlock
{
    /**
	 * @Groups({"page","template_edit","template_list"})
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @Groups({"page","template_edit","template_list"})
     * @ORM\Column(type="string", name="name", length=512, options={"default": ""})
     */
	private $name;
	
	/**
     * @ORM\Column(type="string", name="label", length=512, options={"default": ""})
	 * @Groups({"page","template_edit","template_list"})
     */
	private $label;
	
	/**
     * @ORM\Column(type="string", name="description", length=512, options={"default": ""})
	 * @Groups({"page","template_edit","template_list"})
     */
	private $description;

    /**
     * @Groups({"page","template_edit","template_list"})
     * @ORM\Column(type="string", name="type", length=512, options={"default": ""})
     */
    private $type;

    /**
     * @Groups({"page","template_edit","template_list"})
     * @ORM\Column(type="boolean", name="draggable", options={"default": 1})
     */
    private $draggable;

    /**
     * @Groups({"page","template_edit","template_list"})
     * @ORM\Column(type="string", name="group_name", length=512, nullable=true, options={"default": ""})
     */
    private $groupName;
    
    /**
     * @ORM\Column(type="string", name="class_name", length=512, nullable=true, options={"default": ""})
	 * @Groups({"page"})
     */
    private $className;
    
    /**
     * @Groups({"page","template_edit"})
     * @ORM\Column(type="text", name="content", options={"default": "{}"})
     */
    private $content;

    /**
     * @Groups({"page","template_edit","template_list"})
     * @ORM\Column(type="integer", name="render_order", options={"default": 0})
     */
    private $renderOrder;
    
    /** 
	 * @ORM\ManyToOne(targetEntity="Page", inversedBy="blocks")
     * @ORM\JoinColumn(name="page", referencedColumnName="id")
     */
	public $page;
    
    /** 
	 * @ORM\ManyToOne(targetEntity="PageTemplate", inversedBy="blocks")
     * @ORM\JoinColumn(name="template", referencedColumnName="id")
     */
    public $template;
	
	/**
     * @Groups({"page"})
     * @ORM\Column(type="integer", name="parent_id", options={"default": 0})
     */
	private $parentId;


    public $subBlocks = array();
    public $data = array();

    /**
     * @var string $createdBy
     *
     * @Gedmo\Blameable(on="create")
	 * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     */
    private $createdBy;

    /**
     * @var string $updatedBy
     *
     * @Gedmo\Blameable(on="update")
	 * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="updated_by", referencedColumnName="id")
     */
    private $updatedBy;

	public function __construct() {
        
    }
    
    public function makeData()
    {
        $this->data = (array) json_decode($this->content);
    }
    
    /**
    * @ORM\PostLoad()
    */
    public function postLoad()
    {
        $this->makeData();
    }

    /**
     * Get the id of the product.
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * {@inheritdoc}
     */
    public function __toString()
    {
        return $this->getType();
    }
	
    /**
     * Get the value of name
     */ 
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set the value of name
     */ 
    public function setName($name)
    {
        $this->name = $name;
	}	
	
	/**
	 * Get the value of label
	 */ 
	public function getLabel()
	{
		return $this->label;
	}

	/**
	 * Set the value of label
	 */ 
	public function setLabel($label)
	{
		$this->label = $label;
	}
	
	/**
	 * Get the value of description
	 */ 
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Set the value of description
	 */ 
	public function setDescription($description)
	{
		$this->description = $description;
	}

    /**
     * Get the value of type
     */ 
    public function getType()
    {
        return $this->type;
    }

    /**
     * Set the value of type
     */ 
    public function setType($type)
    {
        $this->type = $type;
    }   
    
    /**
     * Get the value of groupName
     */ 
    public function getGroupName()
    {
        return $this->groupName;
    }

    /**
     * Set the value of groupName
     */ 
    public function setGroupName($groupName)
    {
        $this->groupName = $groupName;
    }   

    /**
     * Get the value of className
     */ 
    public function getClassName()
    {
        return $this->className;
    }

    /**
     * Set the value of className
     */ 
    public function setClassName($className)
    {
        $this->className = $className;
    }   

    /**
     * Get the value of content
     */ 
    public function getContent()
    {
        return $this->content;
    }

    /**
     * Set the value of content
     */ 
    public function setContent($content)
    {
        $this->content = $content;
    }

    /**
     * Get the value of draggable
     */ 
    public function getDraggable()
    {
        return $this->draggable;
    }

    /**
     * Set the value of draggable
     */ 
    public function setDraggable($draggable)
    {
        $this->draggable = $draggable;
    }

    /**
     * Get the value of parentId
     */ 
    public function getParentId()
    {
        return $this->parentId;
    }

    /**
     * Set the value of parentID
     */ 
    public function setParentId($parentId)
    {
        $this->parentId = $parentId;
    }

    /**
     * Get the value of renderOrder
     */ 
    public function getRenderOrder()
    {
        return $this->renderOrder;
    }

    /**
     * Set the value of renderOrder
     */ 
    public function setRenderOrder($renderOrder)
    {
        $this->renderOrder = $renderOrder;
	}
	
    /**
     * Set page.
     *
     * @param \App\Entity\Page|null $page
     *
     * @return PageBlock
     */
    public function setPage(\App\Entity\Page $page = null)
    {
        $this->page = $page;

        return $this;
    }

    /**
     * Get page.
     *
     * @return \App\Entity\Page|null
     */
    public function getPage()
    {
        return $this->page;
    }
	
    /**
     * Set template.
     *
     * @param \App\Entity\PageTemplate|null $template
     *
     * @return TemplateBlock
     */
    public function setTemplate(\App\Entity\PageTemplate $template = null)
    {
        $this->template = $template;

        return $this;
    }

    /**
     * Get template.
     *
     * @return \App\Entity\PageTemplate|null
     */
    public function getTemplate()
    {
        return $this->template;
    }


    /**
     * Get $createdBy
     *
     * @return  string
     */ 
    public function getCreatedBy()
    {
        return $this->createdBy;
    }

    /**
     * Set $createdBy
     *
     * @param  string  $createdBy  $createdBy
     *
     * @return  self
     */ 
    public function setCreatedBy(string $createdBy)
    {
        $this->createdBy = $createdBy;

        return $this;
    }

    /**
     * Get $updatedBy
     *
     * @return  string
     */ 
    public function getUpdatedBy()
    {
        return $this->updatedBy;
    }

    /**
     * Set $updatedBy
     *
     * @param  string  $updatedBy  $updatedBy
     *
     * @return  self
     */ 
    public function setUpdatedBy(string $updatedBy)
    {
        $this->updatedBy = $updatedBy;

        return $this;
    }
}
`

**Comment by teohhanhui** [comment]
I think you need to provide more of the stack trace to show where the exception is being thrown.

**Comment by stipic** [comment]
@teohhanhui 

this is stack trace API platform response

https://pastebin.com/KQbUhP4d

**Comment by teohhanhui** [comment]
You have an `\stdClass` object from your `data` property (under `fields` key). That seems to be the problem.

**Comment by teohhanhui** [comment]
But I'm curious why it's even hitting this code path. It doesn't seem correct that we hit the `PropertyNameCollectionFactory` when it's not a resource.

**Comment by teohhanhui** [comment]
Okay, now I understand why, and it's indeed wrong.

**Comment by stipic** [comment]
Data property under fields key was problem, yep. Thanks for quick reply and help.

**Comment by teohhanhui** [comment]
@stipic Could you help us try https://github.com/api-platform/core/pull/2679 :)

**Comment by stipic** [comment]
@teohhanhui 

It's working now. 

![image](https://user-images.githubusercontent.com/6907207/55465532-9cf68800-55fd-11e9-9a52-67fe91dcd52d.png)
