### ISSUE TITLE
Update the Custom Doctrine ORM Filter documentation

### ISSUE THREAD

**Issue by itaelle** [api-platform/api-platform#1091]
Hello guys,

There's something missing from the documentation there: [https://api-platform.com/docs/core/filters/#creating-custom-doctrine-orm-filters](https://api-platform.com/docs/core/filters/#creating-custom-doctrine-orm-filters)

The documentation example tells us to extend the `AbstractContextAwareFilter` which itself extends the `AbstractFilter` class.
Somehow this `ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\AbstractFilter` class now uses the `ApiPlatform\Core\Bridge\Doctrine\Orm\PropertyHelperTrait` which forces us to implement the **`splitPropertyParts()`** method.

It's not implemented, thus we end up with a wrong documentation example...

**Comment by vincentchalamon** [comment]
Hello @itaelle,

In fact, the [`AbstractFilter`] uses both `...Doctrine\Orm\PropertyHelperTrait` & `...Doctrine\Common\PropertyHelperTrait`.
The first one requires the method `splitPropertyParts` to be declared, which is done by the second one: https://github.com/api-platform/core/blob/345612c913e1aca6da4f4aa1cd885421ca6385ff/src/Bridge/Doctrine/Common/PropertyHelperTrait.php#L87

**Comment by vincentchalamon** [comment]
Closing as an answer has been found. If you need to reopen this issue, ping me here :-)
