### ISSUE TITLE
Add pagination support with application/json

### ISSUE THREAD

**Issue by PGLongo** [api-platform/api-platform#1092]
I think that could be a great idea to add pagination also in RAW JSON, for example I've found very useful using a custom HTTP header: **X-Total-Count**.

If you are interested I could work on it.

**Comment by teohhanhui** [comment]
No, please use a hypermedia format if you want hypermedia support. Otherwise we just end up creating our own format, which is bad.

**Comment by henri9813** [comment]
Hello,

@PGLongo , were you able to do it ?
