### ISSUE TITLE
WriteListener generates IRI from controller result instead of persister result.

### ISSUE THREAD

**Issue by jmwri** [api-platform/api-platform#1093]
Currently using api-platform/core=v2.4.2.

When using a DataPersister you are currently unable to return a new entity instance.
The current implementation of `WriteListener.php`, inside of `onKernelView()`.

See the snippet of code from WriteListener.php below (I've removed unrelated code):
```
// Save persister result
$persistResult = $this->dataPersister->persist($controllerResult, $attributes);

// Sets the correct result
$event->setControllerResult($persistResult ?? $controllerResult);

if ($hasOutput) {
    // Uses $controllerResult
    $request->attributes->set('_api_write_item_iri', $this->iriConverter->getIriFromItem($controllerResult));
}
```

Shouldn't the last 3 lines use the controller result from `$event`?

```
if ($hasOutput) {
    $request->attributes->set('_api_write_item_iri', $this->iriConverter->getIriFromItem($event->getControllerResult()));
}
```

The current implementation means you have to change the entity passed to the persister in-place.

I am happy to raise a PR for this.

**Comment by teohhanhui** [comment]
Please see https://github.com/api-platform/core/pull/2693 :smile:
