### ISSUE TITLE
Change the default bus

### ISSUE THREAD

**Issue by kpn13** [api-platform/api-platform#1095]
Is there a way to specify a different messenger bus when turning on the `messenger` property ?

**Comment by soyuka** [comment]
Hi, this looks related to symfony, did you have a look at the documentation for example https://symfony.com/doc/current/messenger/multiple_buses.html ?
Or maybe that you have a particular need, if that's the case please develop a little bit more on what you're trying to do.

**Comment by kpn13** [comment]
Hi, yes I already read this doc, but I'm sure it helps to define a different bus when api-platform dispatch my resource.

In fact my final need is this : I have two endpoints for executing an action on a resource let's say : 

- PUT /resource/{id}/foo
- PUT /resource/{id}/bar

I set the `messenger` property to true for both this endpoints, but I want two differents handlers for handle this two messages. For now, my two handlers are executing, which is the correct behaviour I think because the both handlers are capable of handle "resource".

This is why I thought to definie two buses for dispatch my two messages (one for each) and restrict one handler to one bus and the other handler to the other bus. But maybe it is not the correct approch.

Hope it's clearer.

**Comment by soyuka** [comment]
On both endpoints the message is of the same type?

I understand the need, and indeed it could be solved with multiple buses but this isn't supported yet.

Although, if you have two different inputs and you send them directly to your handlers you could avoid adding buses. 
For example (pseudo non-tested code):

```
namespace App\Resources;

use App\Message\Foo;
use App\Message\Bar;

@ApiResource(
  messenger="input", // send inputs to the messenger instead of the resource, no need to add a transformer
  itemOperations={
    "foo"={"path"="/resources/{id}/foo", "input"=Foo::class},
    "bar"={"path": "/resources/{id}/bar", "input"=Bar::class},
  }
)
class Resource {}
```

This way you have two handlers!

**Comment by kpn13** [comment]
Yes the message is the same type (same resource).

Yes, using `input` property to have differents handlers was my last choice because I would have like to not create new classes just for that. Moreover, one of my endpoint take no input in the request body, so I have nothing do unserialize. But I suppose it will work with an empty class.

Thank you for your help !

**Comment by soyuka** [comment]
I think it'd be interesting to have multiple buses then. We'd need to add a new configuration in the Api Resource attributes. I'm re-opening this as an enhancement, thanks for your input!

**Comment by soyuka** [comment]
moved to core
