### ISSUE TITLE
Resource not dispatch when a data persister support it ?

### ISSUE THREAD

**Issue by kpn13** [api-platform/api-platform#1100]
Hi, Is there a reason why a resource is dispatched (when using `messenger` property) only if there is no DataPersister which can handle this resource or is it some kind of conflict ?

**Comment by soyuka** [comment]
When activated, the messenger flag will tell api platform to use our [DataPersister](https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Messenger/DataPersister.php) to propagate your message through the bus.

**Comment by kpn13** [comment]
Ok so if I have a custom datapersister that supports my resource, it will be called instead [yours](https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Messenger/DataPersister.php) and the message will not be propagate, isn't it ?

**Comment by teohhanhui** [comment]
It seems like we have a priority issue. I suspect we should change the Messenger DataPersister to have a high priority (e.g. 1000), currently it's -900.

**Comment by kpn13** [comment]
Indeed, by changing the priority to a high value my resource is disptached !

**Comment by teohhanhui** [comment]
See https://github.com/api-platform/core/pull/2728

**Comment by soyuka** [comment]
> Ok so if I have a custom datapersister that supports my resource, it will be called instead yours and the message will not be propagate, isn't it ?

You have to make a choice between using your data persister and propagating the message right? In my opinion the correct solution here is to change how you `supports` your resource, and return `false` if you're in the case of a message propagation.

**Comment by teohhanhui** [comment]
> You have to make a choice between using your data persister and propagating the message right? In my opinion the correct solution here is to change how you supports your resource, and return false if you're in the case of a message propagation.

You might have a custom DataPersister but still want to use Messenger for other resources / operations. You're suggesting that all custom DataPersisters must handle the `messenger` property if you don't want to break the Messenger integration. It's not a viable solution.

**Comment by kpn13** [comment]
I agree with @teohhanhui . What is the point of being able to set the messenger property at the operation level if a custom data persister will always be called first ? For example we could have a create operation that will be async (using the messenger data persister) and a delete operation that will be sync (using a custom data persister). 

Moreover it is quite difficult to handle the choice in the support method of a custom data persister. 

 At least, It should be more explicit (or I missed that point) that a custom data persister will take the lead even when we use the messenger property (an improvement of the documentation that I will be happy to contribute).

**Comment by soyuka** [comment]
>  For example we could have a create operation that will be async (using the messenger data persister) and a delete operation that will be sync (using a custom data persister).

In this case you should always go through the messenger and use a different bus (one async, one sync) https://github.com/api-platform/core/issues/2729.

**Comment by kpn13** [comment]
Ok works for me but still, I found very confusing that a custom data persister breaks or prevents the messenger flow.

**Comment by soyuka** [comment]
To me the persistence should be handled through one way not multiple different ways for a same resource. If you want a resource to be handled by the messenger, I really don't get how it can be persisted with something else, and encouraging the use of 2 DataPersister in this case would be a bad practice in my opinion.

Another use case is that you're using a DataPersister for multiple resources. That's fine, and you're implementing something like our DoctrineDataPersister. In that case, the priority should be defined by the developer to be lower then the one from messenger.

I'm against changing the priority because it doesn't solve the problem it just offers a workaround that would probably end up with bad code on your end (like having 2 different ways of persisting a same resource, probably duplicating logic etc.). 
Also, if we say "custom data provider have a positive priority" it's easier to understand then "custom data provider must have a positive priority that's lower then 'insert future messenger data persister priority here'" which confuses people for no real benefit.

**Comment by kpn13** [comment]
Ok your point of view is clearer for me now. And I have to say you're probably right when you say it would end up with bad code. In fact, in my case, a custom data persister war originally a workaround until [api-platform/core#2729](https://github.com/api-platform/core/issues/2729).

**Comment by soyuka** [comment]
I'm having a hard time finding a proper way to implement this, let's continue this discussion there shall we? 
I've also put up some ideas around cqrs in https://github.com/soyuka/cqrs-api-platform/.

**Comment by teohhanhui** [comment]
> Another use case is that you're using a DataPersister for multiple resources. That's fine, and you're implementing something like our DoctrineDataPersister. In that case, the priority should be defined by the developer to be lower then the one from messenger.

That makes no sense to me.
