### ISSUE TITLE
Latest MySQL Docker Image Password Authentication

### ISSUE THREAD

**Issue by 9ae8sdf76** [api-platform/api-platform#1112]
My apologies if this is not the appropriate forum for this request, however I could not find anywhere else to post about this.

I am switching from the default PostgreSQL implementation over to MySQL, and I'm trying to use the latest version (8.x). In these newer version of MySQL, they use [Caching SHA-2 Pluggable Authentication](https://dev.mysql.com/doc/refman/8.0/en/caching-sha2-pluggable-authentication.html), which is not compatible with current versions of PHP (at least 7.3; haven't tried 7.4).

With that said, I am asking that the mysql docker image provided on quay.io set the `default-authentication-plugin` to `mysql_native_password` until such a time that PHP catches up with MySQL in that regard. 

Thank you.

**Comment by teohhanhui** [comment]
We don't provide any mysql image, since we use postgresql.

I'm sure you can change your mysql configuration easily: https://github.com/docker-library/docs/tree/master/mysql#configuration-without-a-cnf-file

**Comment by 9ae8sdf76** [comment]
Oh, how interesting. I'm still learning how to use Docker, and somehow I installed a mysql image from somewhere and inadvertently tagged it as from `quay.io/api-platform`. My thanks for the clarification, and for all of the hard work on this great platform! :)

**Comment by 9ae8sdf76** [comment]
Also, if anybody stumbles across this having the same issue, turns out you can [add the following to your docker-compose.yaml config](https://github.com/docker-library/docs/tree/master/mysql#-via-docker-stack-deploy-or-docker-compose):

`command: --default-authentication-plugin=mysql_native_password`

**Comment by teohhanhui** [comment]
> and inadvertently tagged it as from `quay.io/api-platform`

Yes, it's because of `CONTAINER_REGISTRY_BASE` configured in https://github.com/api-platform/api-platform/blob/master/.env :see_no_evil:
