### ISSUE TITLE
Interface 'Symfony\Component\Translation\TranslatorInterface' not found

### ISSUE THREAD

**Issue by StephanePate** [api-platform/api-platform#1113]
**Symfony version(s) affected**: 4.2.7

**Description**  
PHP Fatal error:  Interface 'Symfony\Component\Translation\TranslatorInterface' not found in /srv/api/vendor/symfony/validator/Util/LegacyTranslatorProxy.php on line 21

**How to reproduce**  
cache:clear

**Additional context**  
Execution of api-platform **update-deps.sh** script

Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 255
!!  PHP Fatal error:  Interface 'Symfony\Component\Translation\TranslatorInterface' not found in /srv/api/vendor/symfony/validator/Util/LegacyTranslatorProxy.php on line 21
!!  
!!  In LegacyTranslatorProxy.php line 21:
!!                                                                                 
!!    Attempted to load interface "TranslatorInterface" from namespace "Symfony\C  
!!    omponent\Translation".                                                       
!!    Did you forget a "use" statement for "Symfony\Contracts\Translation\Transla  
!!    torInterface"?                                                               
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd

**Comment by antograssiot** [comment]
It was reported in https://github.com/symfony/symfony/issues/31161 I think and fixed in https://github.com/symfony/symfony/pull/31164. 
Closing as not related to api-platform but to symfony anyway.

Regards
