### ISSUE TITLE
Documentation reference

### ISSUE THREAD

**Issue by slavo2** [api-platform/api-platform#1117]
I would like to suggest a documentation part, describing meaning, format and examples of use of particular ApiPlatform features, such as ApiResource and ApiProperty Annotations attributes (listed on one place).

**Comment by slavo2** [comment]
Cool, thank you @GregoireHebert .

Could you please provide some example, how to actually make properly a reference to some other resource.
(without subresourcing, without ORM, without embedding - just an identifier or IRI)
It could be obviously done as marking the field as a string, but maybe there is a better way, how to do it, so that the actual relation would be specified in the OpenApi doc.

**Comment by slavo2** [comment]
It would be good, if the documentation was also inline, part of phpDoc documentation to ApiResource and ApiProperty Annotations classes.

**Comment by oleg-brizy** [comment]
I am having hard times trying to customize `@ApiResource`. I don't know what parameters are possible and it doesn't throw any errors if I set a wrong parameter. I am inspiring from small examples from docs then I dig in vendor source code to find how that parameter is used.

A full reference of `@ApiResource` parameters would be very helpful (in my case I need more `graphql` parameters)

**Comment by soyuka** [comment]
Closing in favor of https://github.com/api-platform/api-platform/issues/1192
