### ISSUE TITLE
WebProfilerBundle not installed

### ISSUE THREAD

**Issue by dant89** [api-platform/api-platform#1118]
Having an issue in that installing the api platform pack via composer does not install symfony web profiler bundle, this should happen because the web profiler bundle is listed as a required dev package in the api platform core composer.json: `"symfony/web-profiler-bundle": "^4.2"`. It does however seem to install all other required Symfony packages?

**System:**
PHP version: 7.2.17
Composer version: 1.8.5
`"api-platform/api-pack": "1.2.0"`
`"api-platform/core": "v2.4.2"`

**Reproduce:**
`composer install api-platform/api-pack:^1.2`

**Comment by antograssiot** [comment]
Sorry but that's the expected behavior @dant89 . You l likely misread the core composer.json.
=> `symfony/web-profiler-bundle` is a dev-dependency.

If you need it in you application, you need to run `composer req symfony/profiler-pack --dev` or the debug-pack etc...

**Comment by dant89** [comment]
By default ` composer install` runs with the `--dev` flag so you would expect it to install?

**Comment by antograssiot** [comment]
No I would expect that if it is not in my composer.json
We would ve downloading fosuserbundle or nelmioapidocbundle or graphql library as well as every dev library used by any dev dependencies... that sounds terrible.

**Comment by dant89** [comment]
You are correct, my mistake! https://stackoverflow.com/a/36347991/1072492
