### ISSUE TITLE
cURL error on demo Greetings tutorial (API Platform v 2.4.2)

### ISSUE THREAD

**Issue by Rmy5** [api-platform/api-platform#1121]
Just following the "greetings" demo tutorial to try out API Platform v 2.4.2, I'm getting this 500 server error when trying to use POST operation:

{
  "@context": "/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "cURL error 6: Could not resolve host: cache-proxy (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/srv/api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php",
      "line": 185,
      "args": []
    },
    {
      "namespace": "GuzzleHttp\\Handler",
      "short_class": "CurlFactory",
      "class": "GuzzleHttp\\Handler\\CurlFactory",
      "type": "::",
      "function": "createRejection",
      "file": "/srv/api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php",
      "line": 149,
      "args": [
        [
          "object",
          "GuzzleHttp\\Handler\\EasyHandle"
        ],
        [
          "array",
          {
            "errno": [
              "integer",
              6
            ],
            "error": [
              "string",
              "Could not resolve host: cache-proxy"
            ],
            "url": [
              "string",
              "http://cache-proxy"
            ],
            "content_type": [
              "null",
              null
            ],
            "http_code": [
              "integer",
              0
            ],
            "header_size": [
              "integer",
              0
            ],
            "request_size": [
              "integer",
              0
            ],
            "filetime": [
              "integer",
              -1
            ],
            "ssl_verify_result": [
              "integer",
              0
            ],
            "redirect_count": [
              "integer",
              0
            ],
            "total_time": [
              "float",
              0.003019
            ],
            "namelookup_time": [
              "float",
              0
            ],
            "connect_time": [
              "float",
              0
            ],
            "pretransfer_time": [
              "float",
              0
            ],
            "size_upload": [
              "float",
              0
            ],
            "size_download": [
              "float",
              0
            ],
            "speed_download": [
              "float",
              0
            ],
            "speed_upload": [
              "float",
              0
            ],
            "download_content_length": [
              "float",
              -1
            ],
            "upload_content_length": [
              "float",
              -1
            ],
            "starttransfer_time": [
              "float",
              0
            ],
            "redirect_time": [
              "float",
              0
            ],
            "redirect_url": [
              "string",
              ""
            ],
            "primary_ip": [
              "string",
              ""
            ],
            "certinfo": [
              "array",
              []
            ],
            "primary_port": [
              "integer",
              0
            ],
            "local_ip": [
              "string",
              ""
            ],
            "local_port": [
              "integer",
              0
            ],
            "http_version": [
              "integer",
              0
            ],
            "protocol": [
              "integer",
              0
            ],
            "ssl_verifyresult": [
              "integer",
              0
            ],
            "scheme": [
              "string",
              ""
            ],
            "appconnect_time_us": [
              "integer",
              0
            ],
            "connect_time_us": [
              "integer",
              0
            ],
            "namelookup_time_us": [
              "integer",
              0
            ],
            "pretransfer_time_us": [
              "integer",
              0
            ],
            "redirect_time_us": [
              "integer",
              0
            ],
            "starttransfer_time_us": [
              "integer",
              0
            ],
            "total_time_us": [
              "integer",
              3019
            ]
          }
        ]
      ]
    },
    {
      "namespace": "GuzzleHttp\\Handler",
      "short_class": "CurlFactory",
      "class": "GuzzleHttp\\Handler\\CurlFactory",
      "type": "::",
      "function": "finishError",
      "file": "/srv/api/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php",
      "line": 102,
      "args": [
        [
          "object",
          "GuzzleHttp\\Handler\\CurlHandler"
        ],
        [
          "object",
          "GuzzleHttp\\Handler\\EasyHandle"
        ],
        [
          "object",
          "GuzzleHttp\\Handler\\CurlFactory"
        ]
      ]
    },
    {
      "namespace": "GuzzleHttp\\Handler",
      "short_class": "CurlFactory",
      "class": "GuzzleHttp\\Handler\\CurlFactory",
      "type": "::",
      "function": "finish",
      "file": "/srv/api/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php",
      "line": 43,
      "args": [
        [
          "object",
          "GuzzleHttp\\Handler\\CurlHandler"
        ],
        [
          "object",
          "GuzzleHttp\\Handler\\EasyHandle"
        ],
        [
          "object",
          "GuzzleHttp\\Handler\\CurlFactory"
        ]
      ]
    },
    {
      "namespace": "GuzzleHttp\\Handler",
      "short_class": "CurlHandler",
      "class": "GuzzleHttp\\Handler\\CurlHandler",
      "type": "->",
      "function": "__invoke",
      "file": "/srv/api/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php",
      "line": 28,
      "args": [
        [
          "object",
          "GuzzleHttp\\Psr7\\Request"
        ],
        [
          "array",
          {
            "synchronous": [
              "boolean",
              true
            ],
            "base_uri": [
              "object",
              "GuzzleHttp\\Psr7\\Uri"
            ],
            "handler": [
              "object",
              "GuzzleHttp\\HandlerStack"
            ],
            "allow_redirects": [
              "array",
              {
                "max": [
                  "integer",
                  5
                ],
                "protocols": [
                  "array",
                  [
                    [
                      "string",
                      "http"
                    ],
                    [
                      "string",
                      "https"
                    ]
                  ]
                ],
                "strict": [
                  "boolean",
                  false
                ],
                "referer": [
                  "boolean",
                  false
                ],
                "track_redirects": [
                  "boolean",
                  false
                ]
              }
            ],
            "http_errors": [
              "boolean",
              true
            ],
            "decode_content": [
              "boolean",
              true
            ],
            "verify": [
              "boolean",
              true
            ],
            "cookies": [
              "boolean",
              false
            ]
          }
        ]
      ]
    },
    {
      "namespace": "GuzzleHttp\\Handler",
      "short_class": "Proxy",
      "class": "GuzzleHttp\\Handler\\Proxy",
      "type": "::",
      "function": "GuzzleHttp\\Handler\\{closure}",
      "file": "/srv/api/vendor/guzzlehttp/guzzle/src/Handler/Proxy.php",
      "line": 51,
      "args": [
        [
          "object",
          "GuzzleHttp\\Psr7\\Request"
        ],
        [
          "array",
          {
            "synchronous": [
              "boolean",
              true
            ],
            "base_uri": [
              "object",
              "GuzzleHttp\\Psr7\\Uri"
            ],
            "handler": [
              "object",
              "GuzzleHttp\\HandlerStack"
            ],
            "allow_redirects": [
              "array",
              {
                "max": [
                  "integer",
                  5
                ],
                "protocols": [
                  "array",
                  [
                    [
                      "string",
                      "http"
                    ],
                    [
                      "string",
                      "https"
                    ]
                  ]
                ],
                "strict": [
                  "boolean",
                  false
                ],
                "referer": [
                  "boolean",
                  false
                ],
                "track_redirects": [
                  "boolean",
                  false
                ]
              }
            ],
            "http_errors": [
              "boolean",
              true
            ],
            "decode_content": [
              "boolean",
              true
            ],
            "verify": [
              "boolean",
              true
            ],
            "cookies": [
              "boolean",
              false
            ]
          }
        ]
      ]
    },
    {
      "namespace": "GuzzleHttp\\Handler",
      "short_class": "Proxy",
      "class": "GuzzleHttp\\Handler\\Proxy",
      "type": "::",
      "function": "GuzzleHttp\\Handler\\{closure}",
      "file": "/srv/api/vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php",
      "line": 37,
      "args": [
        [
          "object",
          "GuzzleHttp\\Psr7\\Request"
        ],
        [
          "array",
          {
            "synchronous": [
              "boolean",
              true
            ],
            "base_uri": [
              "object",
              "GuzzleHttp\\Psr7\\Uri"
            ],
            "handler": [
              "object",
              "GuzzleHttp\\HandlerStack"
            ],
            "allow_redirects": [
              "array",
              {
                "max": [
                  "integer",
                  5
                ],
                "protocols": [
                  "array",
                  [
                    [
                      "string",
                      "http"
                    ],
                    [
                      "string",
                      "https"
                    ]
                  ]
                ],
                "strict": [
                  "boolean",
                  false
                ],
                "referer": [
                  "boolean",
                  false
                ],
                "track_redirects": [
                  "boolean",
                  false
                ]
              }
            ],
            "http_errors": [
              "boolean",
              true
            ],
            "decode_content": [
              "boolean",
              true
            ],
            "verify": [
              "boolean",
              true
            ],
            "cookies": [
              "boolean",
              false
            ]
          }
        ]
      ]
    },
    {
      "namespace": "GuzzleHttp",
      "short_class": "PrepareBodyMiddleware",
      "class": "GuzzleHttp\\PrepareBodyMiddleware",
      "type": "->",
      "function": "__invoke",
      "file": "/srv/api/vendor/guzzlehttp/guzzle/src/Middleware.php",
      "line": 30,
      "args": [
        [
          "object",
          "GuzzleHttp\\Psr7\\Request"
        ],
        [
          "array",
          {
            "synchronous": [
              "boolean",
              true
            ],
            "base_uri": [
              "object",
              "GuzzleHttp\\Psr7\\Uri"
            ],
            "handler": [
              "object",
              "GuzzleHttp\\HandlerStack"
            ],
            "allow_redirects": [
              "array",
              {
                "max": [
                  "integer",
                  5
                ],
                "protocols": [
                  "array",
                  [
                    [
                      "string",
                      "http"
                    ],
                    [
                      "string",
                      "https"
                    ]
                  ]
                ],
                "strict": [
                  "boolean",
                  false
                ],
                "referer": [
                  "boolean",
                  false
                ],
                "track_redirects": [
                  "boolean",
                  false
                ]
              }
            ],
            "http_errors": [
              "boolean",
              true
            ],
            "decode_content": [
              "boolean",
              true
            ],
            "verify": [
              "boolean",
              true
            ],
            "cookies": [
              "boolean",
              false
            ]
          }
        ]
      ]
    },
    {
      "namespace": "GuzzleHttp",
      "short_class": "Middleware",
      "class": "GuzzleHttp\\Middleware",
      "type": "::",
      "function": "GuzzleHttp\\{closure}",
      "file": "/srv/api/vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php",
      "line": 70,
      "args": [
        [
          "object",
          "GuzzleHttp\\Psr7\\Request"
        ],
        [
          "array",
          {
            "synchronous": [
              "boolean",
              true
            ],
            "base_uri": [
              "object",
              "GuzzleHttp\\Psr7\\Uri"
            ],
            "handler": [
              "object",
              "GuzzleHttp\\HandlerStack"
            ],
            "allow_redirects": [
              "array",
              {
                "max": [
                  "integer",
                  5
                ],
                "protocols": [
                  "array",
                  [
                    [
                      "string",
                      "http"
                    ],
                    [
                      "string",
                      "https"
                    ]
                  ]
                ],
                "strict": [
                  "boolean",
                  false
                ],
                "referer": [
                  "boolean",
                  false
                ],
                "track_redirects": [
                  "boolean",
                  false
                ]
              }
            ],
            "http_errors": [
              "boolean",
              true
            ],
            "decode_content": [
              "boolean",
              true
            ],
            "verify": [
              "boolean",
              true
            ],
            "cookies": [
              "boolean",
              false
            ]
          }
        ]
      ]
    },
    {
      "namespace": "GuzzleHttp",
      "short_class": "RedirectMiddleware",
      "class": "GuzzleHttp\\RedirectMiddleware",
      "type": "->",
      "function": "__invoke",
      "file": "/srv/api/vendor/guzzlehttp/guzzle/src/Middleware.php",
      "line": 60,
      "args": [
        [
          "object",
          "GuzzleHttp\\Psr7\\Request"
        ],
        [
          "array",
          {
            "synchronous": [
              "boolean",
              true
            ],
            "base_uri": [
              "object",
              "GuzzleHttp\\Psr7\\Uri"
            ],
            "handler": [
              "object",
              "GuzzleHttp\\HandlerStack"
            ],
            "allow_redirects": [
              "array",
              {
                "max": [
                  "integer",
                  5
                ],
                "protocols": [
                  "array",
                  [
                    [
                      "string",
                      "http"
                    ],
                    [
                      "string",
                      "https"
                    ]
                  ]
                ],
                "strict": [
                  "boolean",
                  false
                ],
                "referer": [
                  "boolean",
                  false
                ],
                "track_redirects": [
                  "boolean",
                  false
                ]
              }
            ],
            "http_errors": [
              "boolean",
              true
            ],
            "decode_content": [
              "boolean",
              true
            ],
            "verify": [
              "boolean",
              true
            ],
            "cookies": [
              "boolean",
              false
            ]
          }
        ]
      ]
    },
    {
      "namespace": "GuzzleHttp",
      "short_class": "Middleware",
      "class": "GuzzleHttp\\Middleware",
      "type": "::",
      "function": "GuzzleHttp\\{closure}",
      "file": "/srv/api/vendor/guzzlehttp/guzzle/src/HandlerStack.php",
      "line": 67,
      "args": [
        [
          "object",
          "GuzzleHttp\\Psr7\\Request"
        ],
        [
          "array",
          {
            "synchronous": [
              "boolean",
              true
            ],
            "base_uri": [
              "object",
              "GuzzleHttp\\Psr7\\Uri"
            ],
            "handler": [
              "object",
              "GuzzleHttp\\HandlerStack"
            ],
            "allow_redirects": [
              "array",
              {
                "max": [
                  "integer",
                  5
                ],
                "protocols": [
                  "array",
                  [
                    [
                      "string",
                      "http"
                    ],
                    [
                      "string",
                      "https"
                    ]
                  ]
                ],
                "strict": [
                  "boolean",
                  false
                ],
                "referer": [
                  "boolean",
                  false
                ],
                "track_redirects": [
                  "boolean",
                  false
                ]
              }
            ],
            "http_errors": [
              "boolean",
              true
            ],
            "decode_content": [
              "boolean",
              true
            ],
            "verify": [
              "boolean",
              true
            ],
            "cookies": [
              "boolean",
              false
            ]
          }
        ]
      ]
    },
    {
      "namespace": "GuzzleHttp",
      "short_class": "HandlerStack",
      "class": "GuzzleHttp\\HandlerStack",
      "type": "->",
      "function": "__invoke",
      "file": "/srv/api/vendor/guzzlehttp/guzzle/src/Client.php",
      "line": 277,
      "args": [
        [
          "object",
          "GuzzleHttp\\Psr7\\Request"
        ],
        [
          "array",
          {
            "synchronous": [
              "boolean",
              true
            ],
            "base_uri": [
              "object",
              "GuzzleHttp\\Psr7\\Uri"
            ],
            "handler": [
              "object",
              "GuzzleHttp\\HandlerStack"
            ],
            "allow_redirects": [
              "array",
              {
                "max": [
                  "integer",
                  5
                ],
                "protocols": [
                  "array",
                  [
                    [
                      "string",
                      "http"
                    ],
                    [
                      "string",
                      "https"
                    ]
                  ]
                ],
                "strict": [
                  "boolean",
                  false
                ],
                "referer": [
                  "boolean",
                  false
                ],
                "track_redirects": [
                  "boolean",
                  false
                ]
              }
            ],
            "http_errors": [
              "boolean",
              true
            ],
            "decode_content": [
              "boolean",
              true
            ],
            "verify": [
              "boolean",
              true
            ],
            "cookies": [
              "boolean",
              false
            ]
          }
        ]
      ]
    },
    {
      "namespace": "GuzzleHttp",
      "short_class": "Client",
      "class": "GuzzleHttp\\Client",
      "type": "->",
      "function": "transfer",
      "file": "/srv/api/vendor/guzzlehttp/guzzle/src/Client.php",
      "line": 125,
      "args": [
        [
          "object",
          "GuzzleHttp\\Psr7\\Request"
        ],
        [
          "array",
          {
            "synchronous": [
              "boolean",
              true
            ],
            "base_uri": [
              "object",
              "GuzzleHttp\\Psr7\\Uri"
            ],
            "handler": [
              "object",
              "GuzzleHttp\\HandlerStack"
            ],
            "allow_redirects": [
              "array",
              {
                "max": [
                  "integer",
                  5
                ],
                "protocols": [
                  "array",
                  [
                    [
                      "string",
                      "http"
                    ],
                    [
                      "string",
                      "https"
                    ]
                  ]
                ],
                "strict": [
                  "boolean",
                  false
                ],
                "referer": [
                  "boolean",
                  false
                ],
                "track_redirects": [
                  "boolean",
                  false
                ]
              }
            ],
            "http_errors": [
              "boolean",
              true
            ],
            "decode_content": [
              "boolean",
              true
            ],
            "verify": [
              "boolean",
              true
            ],
            "cookies": [
              "boolean",
              false
            ]
          }
        ]
      ]
    },
    {
      "namespace": "GuzzleHttp",
      "short_class": "Client",
      "class": "GuzzleHttp\\Client",
      "type": "->",
      "function": "requestAsync",
      "file": "/srv/api/vendor/guzzlehttp/guzzle/src/Client.php",
      "line": 131,
      "args": [
        [
          "string",
          "BAN"
        ],
        [
          "object",
          "GuzzleHttp\\Psr7\\Uri"
        ],
        [
          "array",
          {
            "synchronous": [
              "boolean",
              true
            ],
            "base_uri": [
              "object",
              "GuzzleHttp\\Psr7\\Uri"
            ],
            "handler": [
              "object",
              "GuzzleHttp\\HandlerStack"
            ],
            "allow_redirects": [
              "array",
              {
                "max": [
                  "integer",
                  5
                ],
                "protocols": [
                  "array",
                  [
                    [
                      "string",
                      "http"
                    ],
                    [
                      "string",
                      "https"
                    ]
                  ]
                ],
                "strict": [
                  "boolean",
                  false
                ],
                "referer": [
                  "boolean",
                  false
                ],
                "track_redirects": [
                  "boolean",
                  false
                ]
              }
            ],
            "http_errors": [
              "boolean",
              true
            ],
            "decode_content": [
              "boolean",
              true
            ],
            "verify": [
              "boolean",
              true
            ],
            "cookies": [
              "boolean",
              false
            ],
            "_conditional": [
              "array",
              {
                "User-Agent": [
                  "string",
                  "GuzzleHttp/6.3.3 curl/7.64.0 PHP/7.3.4"
                ]
              }
            ]
          }
        ]
      ]
    },
    {
      "namespace": "GuzzleHttp",
      "short_class": "Client",
      "class": "GuzzleHttp\\Client",
      "type": "->",
      "function": "request",
      "file": "/srv/api/vendor/api-platform/core/src/HttpCache/VarnishPurger.php",
      "line": 54,
      "args": [
        [
          "string",
          "BAN"
        ],
        [
          "string",
          ""
        ],
        [
          "array",
          {
            "headers": [
              "array",
              {
                "ApiPlatform-Ban-Regex": [
                  "string",
                  "(^|\\,)/greetings($|\\,)"
                ]
              }
            ],
            "synchronous": [
              "boolean",
              true
            ]
          }
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\Core\\HttpCache",
      "short_class": "VarnishPurger",
      "class": "ApiPlatform\\Core\\HttpCache\\VarnishPurger",
      "type": "->",
      "function": "purge",
      "file": "/srv/api/vendor/api-platform/core/src/Bridge/Doctrine/EventListener/PurgeHttpCacheListener.php",
      "line": 102,
      "args": [
        [
          "array",
          {
            "/greetings": [
              "string",
              "/greetings"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\Core\\Bridge\\Doctrine\\EventListener",
      "short_class": "PurgeHttpCacheListener",
      "class": "ApiPlatform\\Core\\Bridge\\Doctrine\\EventListener\\PurgeHttpCacheListener",
      "type": "->",
      "function": "postFlush",
      "file": "/srv/api/vendor/symfony/doctrine-bridge/ContainerAwareEventManager.php",
      "line": 61,
      "args": [
        [
          "object",
          "Doctrine\\ORM\\Event\\PostFlushEventArgs"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Bridge\\Doctrine",
      "short_class": "ContainerAwareEventManager",
      "class": "Symfony\\Bridge\\Doctrine\\ContainerAwareEventManager",
      "type": "->",
      "function": "dispatchEvent",
      "file": "/srv/api/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php",
      "line": 3395,
      "args": [
        [
          "string",
          "postFlush"
        ],
        [
          "object",
          "Doctrine\\ORM\\Event\\PostFlushEventArgs"
        ]
      ]
    },
    {
      "namespace": "Doctrine\\ORM",
      "short_class": "UnitOfWork",
      "class": "Doctrine\\ORM\\UnitOfWork",
      "type": "->",
      "function": "dispatchPostFlushEvent",
      "file": "/srv/api/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php",
      "line": 430,
      "args": []
    },
    {
      "namespace": "Doctrine\\ORM",
      "short_class": "UnitOfWork",
      "class": "Doctrine\\ORM\\UnitOfWork",
      "type": "->",
      "function": "commit",
      "file": "/srv/api/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php",
      "line": 359,
      "args": [
        [
          "null",
          null
        ]
      ]
    },
    {
      "namespace": "Doctrine\\ORM",
      "short_class": "EntityManager",
      "class": "Doctrine\\ORM\\EntityManager",
      "type": "->",
      "function": "flush",
      "file": "/srv/api/vendor/api-platform/core/src/Bridge/Doctrine/Common/DataPersister.php",
      "line": 59,
      "args": []
    },
    {
      "namespace": "ApiPlatform\\Core\\Bridge\\Doctrine\\Common",
      "short_class": "DataPersister",
      "class": "ApiPlatform\\Core\\Bridge\\Doctrine\\Common\\DataPersister",
      "type": "->",
      "function": "persist",
      "file": "/srv/api/vendor/api-platform/core/src/Bridge/Symfony/Bundle/DataPersister/TraceableChainDataPersister.php",
      "line": 56,
      "args": [
        [
          "object",
          "App\\Entity\\Greeting"
        ],
        [
          "array",
          {
            "resource_class": [
              "string",
              "App\\Entity\\Greeting"
            ],
            "collection_operation_name": [
              "string",
              "post"
            ],
            "receive": [
              "boolean",
              true
            ],
            "respond": [
              "boolean",
              true
            ],
            "persist": [
              "boolean",
              true
            ]
          }
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\Core\\Bridge\\Symfony\\Bundle\\DataPersister",
      "short_class": "TraceableChainDataPersister",
      "class": "ApiPlatform\\Core\\Bridge\\Symfony\\Bundle\\DataPersister\\TraceableChainDataPersister",
      "type": "->",
      "function": "persist",
      "file": "/srv/api/vendor/api-platform/core/src/EventListener/WriteListener.php",
      "line": 60,
      "args": [
        [
          "object",
          "App\\Entity\\Greeting"
        ],
        [
          "array",
          {
            "resource_class": [
              "string",
              "App\\Entity\\Greeting"
            ],
            "collection_operation_name": [
              "string",
              "post"
            ],
            "receive": [
              "boolean",
              true
            ],
            "respond": [
              "boolean",
              true
            ],
            "persist": [
              "boolean",
              true
            ]
          }
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\Core\\EventListener",
      "short_class": "WriteListener",
      "class": "ApiPlatform\\Core\\EventListener\\WriteListener",
      "type": "->",
      "function": "onKernelView",
      "file": "/srv/api/vendor/symfony/event-dispatcher/Debug/WrappedListener.php",
      "line": 115,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent"
        ],
        [
          "string",
          "kernel.view"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "WrappedListener",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener",
      "type": "->",
      "function": "__invoke",
      "file": "/srv/api/vendor/symfony/event-dispatcher/EventDispatcher.php",
      "line": 212,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent"
        ],
        [
          "string",
          "kernel.view"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "doDispatch",
      "file": "/srv/api/vendor/symfony/event-dispatcher/EventDispatcher.php",
      "line": 44,
      "args": [
        [
          "array",
          [
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ]
          ]
        ],
        [
          "string",
          "kernel.view"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/srv/api/vendor/symfony/event-dispatcher/Debug/TraceableEventDispatcher.php",
      "line": 145,
      "args": [
        [
          "string",
          "kernel.view"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "TraceableEventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/srv/api/vendor/symfony/http-kernel/HttpKernel.php",
      "line": 155,
      "args": [
        [
          "string",
          "kernel.view"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseForControllerResultEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handleRaw",
      "file": "/srv/api/vendor/symfony/http-kernel/HttpKernel.php",
      "line": 67,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ],
        [
          "integer",
          1
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handle",
      "file": "/srv/api/vendor/symfony/http-kernel/Kernel.php",
      "line": 198,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ],
        [
          "integer",
          1
        ],
        [
          "boolean",
          true
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "Kernel",
      "class": "Symfony\\Component\\HttpKernel\\Kernel",
      "type": "->",
      "function": "handle",
      "file": "/srv/api/public/index.php",
      "line": 25,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ]
      ]
    }
  ]
}

**Comment by dunglas** [comment]
It's an error related to Docker. Could you paste the output of `docker-compose pull && docker-compose up --build --force-recreate`?
It looks like the Varnish Docker is not starting correctly. If you removed it on purpose, you must turn off the Varnish integration by removing these lines in the config: https://github.com/api-platform/api-platform/blob/master/api/config/packages/api_platform.yaml#L14-L21

**Comment by Rmy5** [comment]
End of the output of `docker-compose pull && docker-compose up --build --force-recreate` was:

> Successfully built 9ab099c4d1f0
Successfully tagged api-platform-242_h2-proxy:latest
Creating api-platform-242_client_1      ... done
Creating api-platform-242_db_1      ... done
Creating api-platform-242_mercure_1 ... done
Creating api-platform-242_admin_1       ... done
Creating api-platform-242_php_1     ... done
Creating api-platform-242_api_1     ... done
Creating api-platform-242_cache-proxy_1 ... done
Creating api-platform-242_h2-proxy_1    ... done
Attaching to api-platform-242_db_1, api-platform-242_mercure_1, api-platform-242_php_1, api-platform-242_api_1, api-platform-242_cache-proxy_1, api-platform-242_admin_1, api-platform-242_client_1, api-platform-242_h2-proxy_1
db_1           | 2019-04-28 09:42:22.496 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db_1           | 2019-04-28 09:42:22.496 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db_1           | 2019-04-28 09:42:22.501 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
mercure_1      | time="2019-04-28T09:42:22Z" level=info msg="Mercure started" protocol=http
php_1          | Loading composer repositories with package information
db_1           | 2019-04-28 09:42:22.520 UTC [18] LOG:  database system was interrupted; last known up at 2019-04-27 23:30:04 UTC
php_1          | Installing dependencies (including require-dev) from lock file
cache-proxy_1  | Debug: Version: varnish-6.0.3 revision 7d1ded3aa033a018317dbafc61587026ea2ef8a3
cache-proxy_1  | Debug: Platform: Linux,4.9.125-linuxkit,x86_64,-junix,-sdefault,-sdefault,-hcritbit
db_1           | 2019-04-28 09:42:22.865 UTC [18] LOG:  database system was not properly shut down; automatic recovery in progress
admin_1        | yarn run v1.12.3
php_1          | Nothing to install or update
client_1       | yarn run v1.12.3
cache-proxy_1  | Debug: Child (17) Started
cache-proxy_1  | Info: Child (17) said Child starts
db_1           | 2019-04-28 09:42:22.867 UTC [18] LOG:  redo starts at 0/1656738
db_1           | 2019-04-28 09:42:22.868 UTC [18] LOG:  invalid record length at 0/16568D8: wanted 24, got 0
db_1           | 2019-04-28 09:42:22.868 UTC [18] LOG:  redo done at 0/16568A0
db_1           | 2019-04-28 09:42:22.868 UTC [18] LOG:  last completed transaction was at log time 2019-04-27 23:33:05.106996+00
admin_1        | $ react-scripts start
db_1           | 2019-04-28 09:42:22.883 UTC [1] LOG:  database system is ready to accept connections
php_1          | Generating autoload files
client_1       | $ react-scripts start
php_1          | Executing script cache:clear [OK]
php_1          | Executing script assets:install public [OK]
php_1          | 
php_1          | Waiting for db to be ready...
php_1          | 
php_1          |  [OK] Nothing to update - your database is already in sync with the current     
php_1          |       entity metadata.                                                          
php_1          | 
php_1          | [28-Apr-2019 09:42:32] NOTICE: fpm is running, pid 1
php_1          | [28-Apr-2019 09:42:32] NOTICE: ready to handle connections
admin_1        | Starting the development server...
admin_1        | 
client_1       | Starting the development server...
client_1       | 
client_1       | Compiled successfully!
client_1       | 
client_1       | You can now view client in the browser.
client_1       | 
client_1       |   Local:            http://localhost:3000/
client_1       |   On Your Network:  http://172.18.0.8:3000/
client_1       | 
client_1       | Note that the development build is not optimized.
client_1       | To create a production build, use yarn build.
client_1       | 
admin_1        | Compiled successfully!
admin_1        | 
admin_1        | You can now view admin in the browser.
admin_1        | 
admin_1        |   Local:            http://localhost:3000/
admin_1        |   On Your Network:  http://172.18.0.7:3000/
admin_1        | 
admin_1        | Note that the development build is not optimized.
admin_1        | To create a production build, use yarn build.
admin_1        | 

> 

It solved the problem. I hadn't removed the Varnish Docker, but not used to Docker either.
Tx. :+1
