### ISSUE TITLE
Mercure JWT incompatible with LexikJWTAuthenticationBundle?

### ISSUE THREAD

**Issue by dvc** [api-platform/api-platform#1123]
Hello, everybody!

Current documentation covers case for manual creating mercure publisher jwt via jwt.io (HS256 with secret-key).

If i want to protect pubs for subscribers (mercure targets), i need separate jwt (also HS256)  for subscriber. Because LexikJWTAuthenticationBundle generates RS256 token (with keypair).

And we need to share mercure secret for that, not only precreated token.

It is discouraging!

**Comment by dunglas** [comment]
I'm not sure to understand the issue. Of course to sign the token you need the secret key.

**Comment by teohhanhui** [comment]
@dunglas If I understand correctly, the default implementation of Mercure uses HS256 algorithm (symmetric key) whereas it's better to use RS256 algorithm (asymmetric key).

@dvc But I don't see why you'd need to share the secret to the subscribers / publishers. The JWT is signed (and verified) by the Mercure hub only, right? If I understand https://github.com/dunglas/mercure/blob/master/spec/mercure.md#authorization correctly...

**Comment by dunglas** [comment]
For Mercure's use case, using symmetric keys is perfectly OK, and simpler. The client (the web browser) must never modify the token. But I'll be glad to merge RS256 if someone want to work on this (it's supported by the JWT lib used by Mercure).

**Comment by dvc** [comment]
Hello everybody! Thank you for comments.
Let me try to describe:

I use api platform with RS256 JWT keys. And i want to add mercure key in this user jwt via listener. I want to restrict subscribe abilities for user by provide his id, roles or something else (like his chats ids). It's too dynamic options and different for any user.
After that i can publish messages with targets and avoid too wide clients subscriptions.

So i need shared mercure secret in api platform for separate subscribers jwt-s generation. Or Mercure should support RS256 tokens and public key for tokens validation.
I'm not sure about golang. May be it will simple... I can't guarantee, but i will try :)

**Comment by dvc** [comment]
I try to say that Mercure don't have to generate tokens. And don't have to share any secrets. It's just proxy. All tokens generates outside. Only public key in mercure configuration for remote tokens validation is more secure and more flexible. IMHO.

**Comment by ghanbari** [comment]
is implemented this feature?

**Comment by dvc** [comment]
hello, @ghanbari 
Future is implemented in v0.8, but i can't use it. Always 401 error with RS256 subscribers JWT.

Mercure has not too verbose output to debug... I have no idea, what's wrong in my case.

**Comment by Viktor-Bredihin** [comment]
@dvc 
I have the same problem, have u found a solution?

**Comment by dvc** [comment]
no. I don't use Mercure for long time :(

**Comment by syntaxgirl** [comment]
> no. I don't use Mercure for long time :(

Searching now for the same answer. What did you ended up using (if mercure turns out to not work with jwt generated on via lexik bundle)

**Comment by dunglas** [comment]
Mercure now supports tokens generated by LexikJWTBundle. Use the `subscriber_jwt` and `publisher_jwt` directives to specify the algorithm and the key to use: https://mercure.rocks/docs/hub/config#directives

There is now also a dedicated guide explaining how to use RSA keys: https://mercure.rocks/docs/hub/config#jwt-verification

**Comment by jonesie100** [comment]
Does support for subscriber_jwt and publisher_jwt affect v0.10?  Or is this only for v0.11
