### ISSUE TITLE
unable to access Admin on fresh 2.4.2 local installation on Mac

### ISSUE THREAD

**Issue by StephanePate** [api-platform/api-platform#1136]
"Unable to retrieve API documentation"

When trying to reach "http://localhost:81"  ... Blocage d’une requête multiorigines (Cross-Origin Request) : la politique « Same Origin » ne permet pas de consulter la ressource distante située sur http://api/docs.jsonld. Raison : échec de la requête CORS.

When trying to reach ""https://localhost:444" ...  Blocage du chargement du contenu mixte actif (mixed active content) « http://api/docs.jsonld »

Is-it linked to .env CORS_ALLOW_ORIGIN=^https?://localhost(:[0-9]+)?$ ?

**Comment by dunglas** [comment]
Are you using the latest tagged version of the distribution? This bug should have been fixed by https://github.com/api-platform/api-platform/pull/1067

**Comment by StephanePate** [comment]
Yes, but I also launched the "update-deps.sh" script in which the command "cd api && composer sync-recipes --force" overwrites the .env file without the bug fix ...

**Comment by dunglas** [comment]
Yes, this script is only for the maintainers and contributors. It requires to make some manual tweaks after its use, it’s why it is not included in the official archives. I’ll make it bold in a comment.

**Comment by StephanePate** [comment]
Thanks very much ! I'm really fan of what you're doing, it's great.
