### ISSUE TITLE
User authentication using JWT

### ISSUE THREAD

**Issue by Rmy5** [api-platform/api-platform#1137]
I'm trying to follow the documentation for an example on how to set up an authentication system in API-platform, but I'm not using Docker (I seem to often stumble on examples for docker in the documentation), so I'm not sure on how to achieve this using a plain Symfony / API-platform install ?
![Capture d’écran 2019-05-12 à 01 36 37](https://user-images.githubusercontent.com/30668074/57576053-c655cf80-7457-11e9-8610-763de352d64e.png)

**Comment by teohhanhui** [comment]
@Rmy5 For the next time when you face any issue, please provide a proper description and the relevant details. :smile:
