### ISSUE TITLE
Authentication JWT

### ISSUE THREAD

**Issue by MaximeBrl** [api-platform/api-platform#1140]
Hello,

It's my first time that I try to create an API. 
First of all, I just want to make jwt authentication using **LexikJWTAuthenticationBundle**. I read some links to understand the goal of JWT. 
After,  I have read the doc of **api-platform** to set up to my project. 
Unfortunately, all of my attemps were a failure. 
Indeed, when I try to retrieve the token for user, with 
`curl -X POST -H "Content-Type: application/json" http://localhost:8080/authentication_token -d '{"email":"email","password":"pwd"}'`
I have : 
`{"code":401,"message":"Bad credentials"}`

But the user exists... 

I try to look for similar topic on the web to resolve my problem, but I haven't found a solution yet. 

I put my code in a pastebin because I had some troubles when inserting codes.

Here's my security.yaml : 
https://pastebin.com/FtLEQbzm

My routes.yaml : 
https://pastebin.com/fNKQvsbw

My entity Account : 

https://pastebin.com/wtNeRupD

And a screenshot of the data in db account : 
![image](https://user-images.githubusercontent.com/16270786/57715190-6b4df380-7676-11e9-84a8-b8c16d41e5f7.png)

Thank you for those who will help me
Sorry about my English

**Comment by antograssiot** [comment]
Your password should be encoded in db using argon2i as that's the encoder that you've specified in security.yaml

**Comment by MaximeBrl** [comment]
I will try this this evening. I thought that JWT work even if the password is not encoded. If it's worked, I will put close the issue. Thank for your response.

**Comment by MaximeBrl** [comment]
![image](https://user-images.githubusercontent.com/16270786/57776059-db17b900-771e-11e9-94e8-2358b949ce06.png)

Thank you ! I lost a lot of time... if only I'd thought of that.
