### ISSUE TITLE
GraphQL cannot filter subresources

### ISSUE THREAD

**Issue by Vilx2** [api-platform/api-platform#1141]
Let's say I have 3 levels of entities - sellers, categories and products. Each seller has multiple categores, each category has multiple products. Furthermore, products can be active or inactive (boolean field "active"). Now, suppose I want to write a GraphQL query such that it returns a specified seller, all categories in that seller, and for each category ONLY the active products in that category. The query would look something similar to this:

```
{
  sellers(id: 5) {
    edges { node {
        categories {
          edges { node {
              products (active: true) {
                totalCount
                edges { node {
                  name
}}}}}}}}}
```

Unfortunately, as far as I can tell, this is currently impossible with API Platform (which was also confirmed to me in the appropriate Slack channel). No matter where I put my `@ApiFilter()` annotation, I can only filter the root level collection (e.g. sellers) at best.

This was confirmed using API Platform 2.4.2 and Doctrine 2.6.3.

**Comment by alanpoulain** [comment]
Should be fixed in 2.4 by https://github.com/api-platform/core/commit/f1802ea2f75f489bd781967cacd1e8e4797824a5
