### ISSUE TITLE
force_eager config is ignored - relations always fetched

### ISSUE THREAD

**Issue by Gradius30** [api-platform/api-platform#1145]
Hello guys. How do you setup entities to not automatically fetch relations? 
The following code always returns relations loaded..

Cache cleared, symfony debug shows correct `force_eager: false`

api_platform.yaml:
```
api_platform:
    eager_loading:
        force_eager: false
```

Entity\State:
```
/**
 * Class State
 *
 * @ApiResource(
 *     attributes={
 *          "force_eager"=false
 *     }
 * )
 *
 * @ORM\Entity()
 * @ORM\Table(name="list__states")
 */
class State extends BaseEntity implements StateInterface {

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=191, unique=true)
     */
    protected $name;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=3, unique=true)
     */
    protected $code;

    /**
     * @var CountryInterface
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Country\Country", inversedBy="states", fetch="EAGER")
     */
    protected $country;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="App\Entity\County\County", mappedBy="state", cascade={"persist"})
     */
    protected $counties;
}
```

Api response:
![image](https://user-images.githubusercontent.com/36446808/57921275-45eefe80-789d-11e9-8b14-dbcdf298b506.png)

**Comment by Gradius30** [comment]
Solved using serialization groups https://api-platform.com/docs/v2.2/core/serialization/#using-serialization-groups

**Comment by fyrye** [comment]
For clarification `fetch_eager` changes the way Doctrine retrieves the records, not how api-platform displays them. `EAGER` retrieves the associated records immediately, where Doctrine defaults to `LAZY` which fetches the associations `uninitialized` and Doctrine retrieves the values on first call. 

So it looks like

EAGER:
```
SELECT State.id, Country.id FROM State 
LEFT JOIN County ON County.state_id = state.id;
$serializer->normalize($state);
```

LAZY:
```
SELECT State.id FROM State;
$serializer->normalize($state);
     $state->getCounties();

SELECT County.id FROM County WHERE state_id = id;
```
