### ISSUE TITLE
How can I configure page based pagination for GraphQL?

### ISSUE THREAD

**Issue by okaufmann** [api-platform/api-platform#1152]
Hi,

We're using a frontend that reads data from a Symfony Backend via GraphQL. 

After a really long session on Google I only can find Cursor Based Pagination. Is there any way to setup api-platform to use limit/offset properties to paginate the data?

The Frontend was built with Angular so I plan to use https://material.angular.io/components/paginator/api where the user can click on a given page of x pages.

Would really appreciate any tips!

**Comment by alanpoulain** [comment]
We follow the Relay Cursor Connections Specification which is a cursor-based pagination.
I don't plan to add another pagination system yet but you could try to implement it if you want.

**Comment by jeromelebleu26** [comment]
Hello, 

How can we implement it ? (which file)

**Comment by CharlyPoppins** [comment]
Hello, there is an example on our fork : https://github.com/wayatech/core/tree/2.4-waya
Look at this specific commit : https://github.com/wayatech/core/commit/84267d08d71dbc956f64872d594ae92a23c1d580

**Comment by alanpoulain** [comment]
@CharlyPoppins it would be great if you could make a PR with this (and add a configuration flag to enable it) :slightly_smiling_face:

**Comment by jeromelebleu26** [comment]
@CharlyPoppins great thank's !

**Comment by CharlyPoppins** [comment]
@alanpoulain I'll keep that in mind, and i will propose a PR when i'll be back on this project.

@jeromelebleu26 You're welcome :)

**Comment by alanpoulain** [comment]
Merged in master.
