### ISSUE TITLE
Docker: how to make node_modules visible?

### ISSUE THREAD

**Issue by darthf1** [api-platform/api-platform#1155]
Breaking my head on this for a while now.

When I download release 2.4.3 and run the docker instance, the `/client/node_modules` and `/admin/node_modules folder` on the host are empty folders (owned by root). In the containers, both folders are populated with their packages.
```
    volumes:
      - ./admin:/usr/src/admin:rw,cached
      - /usr/src/admin/node_modules
```

The issue i'm having is that this the IDE cannot see the packages, which obviously gives me all kinds of errors.

What i would like to achieve is to have the node_modules folder from the container visibile in the host, so when i add a package in the container, this is visible in the host folder as well. I do not need to make changes in the host node_modules folder.

I tried changing the above lines to the below:
```
    volumes:
      - ./admin:/usr/src/admin:rw,cached
      - ./admin/node_modules:/usr/src/admin/node_modules
```
But this results in `/bin/sh: react-scripts: not found`

I also tried the solution in [this](https://stackoverflow.com/questions/51097652/install-node-modules-inside-docker-container-and-synchronize-them-with-host) link, but this only results on errors on my side.

What should be the preferred way to handle this? Maybe I could add a PR for the docs if there is one.

**Comment by teohhanhui** [comment]
Are you on Linux?

**Comment by darthf1** [comment]
Yes, Ubuntu 19.04.

Op di 28 mei 2019 11:56 schreef Teoh Han Hui <notifications@github.com>:

**Comment by shvlv** [comment]
@teohhanhui What do you think about this [workaround](https://stackoverflow.com/a/52092711)?
I test next code for client (admin same).
### Dockerfile:
```# "development" stage
FROM node:${NODE_VERSION}-alpine AS api_platform_client_development

WORKDIR /usr/src/cache

RUN yarn global add @api-platform/client-generator

# prevent the reinstallation of node modules at every changes in the source code
COPY package.json yarn.lock ./
RUN set -eux; \
	yarn install

VOLUME /usr/src/cache

WORKDIR /usr/src/client

COPY . ./

ENTRYPOINT ["./entrypoint.sh"]
CMD ["yarn", "start"]
```

### entrypoint.sh

```
#!/bin/sh
rsync -arv /usr/src/cache/node_modules/. /usr/src/client/node_modules/
chown -R node:node /usr/src/client/node_modules/
exec "$@"
```

node_modules was installed and cached at images volume but expose after mounting and can inspect by IDE.

**Comment by teohhanhui** [comment]
@shvlv No, that's not the way to go.

**Comment by grimzy** [comment]
I managed to make it work on my MacOS using the solution in the [StackOverflow link](https://stackoverflow.com/questions/51097652/install-node-modules-inside-docker-container-and-synchronize-them-with-host) @darthf1 shared.

Easier to communicate the changes with a PR: https://github.com/api-platform/api-platform/pull/1614
