### ISSUE TITLE
Question: 404 not found on assets

### ISSUE THREAD

**Issue by ajaunasse** [api-platform/api-platform#1163]
Hello,

I've an issue for loading the assets, my browser retrieve 404 not found:

![image](https://user-images.githubusercontent.com/6407911/59261966-a411c600-8c3e-11e9-8b07-68be4401c12c.png)

Yet the files are in the public folder

![image](https://user-images.githubusercontent.com/6407911/59262108-e6d39e00-8c3e-11e9-8617-05d482aad773.png)

I'm working on a docker-compose stack with php-fpm and nginx, there is my nginx conf for the app:

![image](https://user-images.githubusercontent.com/6407911/59262309-416cfa00-8c3f-11e9-8db0-ae023cb35621.png)

I'm stuck on it since 2 hours. it worked perfectly few weeks ago.

Any idea ?

**Comment by Rafarel** [comment]
I have the exact same issue, did you find the solution ? 
I'm using Nginx on docker
Thanks !

**Comment by soyuka** [comment]
are you sure that the swaggerui has been copied as well?

**Comment by Rafarel** [comment]
I found why and this is exactly this !
The docker run composer install after copying the files to the nginx container so all bundle assets were missing.
I ended up by sharing a volume for public ressources

**Comment by nicomagnani3** [comment]
Hola tengo el mismo problema. al levantarlo con PHP levanta bien pero con docker me sucede lo mismo. Cual fue tu solucion?
