### ISSUE TITLE
SimpleObjectHydrator error after upgrading to V2 beta

### ISSUE THREAD

**Issue by napalm33700** [api-platform/api-platform#117]
>                 $results['products'] = $this->em->getRepository('AppBundle:Catalog\Product')->findBy(
                    ['id' => $ids],
                    null,
                    $this->maxItems,
                    $this->maxItems * ($this->page - 1)

after upgrading to V2 i have this error 

> Cannot use SimpleObjectHydrator with a ResultSetMapping that contains scalar mappings.

It worked fine with V2alpha and if I clear doctrine cache there is no error after first reload.

**Comment by napalm33700** [comment]
Something it definitely broken with SimpleObjectHydrator in beta 

same action that worked fine before upgrading now behave like this 

> MappingException in MappingException.php line 565:
Duplicate definition of column 'code' on entity 'AppBundle\Entity\Erp\SaleForce' in a field or discriminator column mapping.
> ReflectionException in RuntimeReflectionService.php line 80:
Property AppBundle\Entity\Web\AccountOption::$code does not exist

if I clear doctrine meta-data cache => no error

I try the same request 

> RuntimeException in SimpleObjectHydrator.php line 40:
Cannot use SimpleObjectHydrator with a ResultSetMapping that contains more than one object result.
ContextErrorException in ClassMetadataInfo.php line 1861:
Notice: Undefined index: wishlist

Again clear meta-data cache no error...

**Comment by teohhanhui** [comment]
I don't see how it has anything to do with this project. Please file a Doctrine bug if relevant...

**Comment by napalm33700** [comment]
Sorry... Next time I will investigate a little lounger...
I just found out that it was related to redis... It's strange because I have no problem in alpha.
Again sorry for polluting your issues.

**Comment by Simperfit** [comment]
@napalm33700 No problem, you are not. 
If it is unlink to api-platform we will tell you like @teohhanhui did ;).
