### ISSUE TITLE
GraphQl nested params on a query

### ISSUE THREAD

**Issue by olup** [api-platform/api-platform#1170]
Hi. I am wondering if it is possible to organise query parameters into sub input types, in order to group parameters concern and use types to manage dynamic parameters query more easily on the clients.

Basicaly, be able to do `user(first:10, filters:{name:"arandomname"})`

In this query the filters belongs to a filter input type (could be named UserFilters), and are separated from the pagination logic. This is pretty much standard graphql good practices. Can api platform let me generate such query parameters structure ?

Cheers

**Comment by alanpoulain** [comment]
Theoretically you could but it would be a little hard.
In master, you would need to decorate the `FieldsBuilder` and the `ReadStage` and change their filters management.

**Comment by olup** [comment]
Tanks. We ended up implementing our own api directly with graphql-php anyway.
