### ISSUE TITLE
API-Platform.com website has broken images

### ISSUE THREAD

**Issue by farazive** [api-platform/api-platform#1178]
Images on the website are broken and result in a 404. 

Visit https://api-platform.com/docs/core/serialization/ and look at the image underneath it. It is not showing correctly. And points to https://api-platform.com/static/f5bf57af8c8a3275d8ba1c9ced6e890d/664bf/SerializerWorkflow.png which results in a 404. Could you please fix the website images. Thanks.

**Comment by toofff** [comment]
thank's @farazive

We will restore this as soon as possible ;)

**Comment by alanpoulain** [comment]
Should be fixed now, thanks.
