### ISSUE TITLE
PHP TypeError (or parent Error) exception are not managed by content negociation

### ISSUE THREAD

**Issue by Rebolon** [api-platform/api-platform#1179]
Hi,
i'm maybe wrong in my implementation but when my API return a TypeError (when someone doesn't fill the body with correct value, then PHP throw a TypeError), then ApiPlatform return an HTTP 500 Internal Server Error with an HTML body (the classic symfony error page).

I expect the API to return a content based on the Header Accept, so json or ld+json for my API.
I try to add the TypeError and Error in api_platform.exception_to_status but it seems not used coz i still get HTML.

Any help or clue is welcome, thanks !

**Comment by gries** [comment]
are you using prod or dev mode?

**Comment by Rebolon** [comment]
This is in preprod and dev environment

**Comment by gries** [comment]
can you try in prod? because for dev it's standard to show symfony error page

**Comment by Rebolon** [comment]
yes i did it and i get html response:

```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <title>An Error Occurred: Unauthorized</title>
        <style>
            body { background-color: #fff; color: #222; font: 16px/1.5 -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; margin: 0; }
            .container { margin: 30px; max-width: 600px; }
            h1 { color: #dc3545; font-size: 24px; }
            h2 { font-size: 18px; }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>Oops! An Error Occurred</h1>
            <h2>The server returned a "401 Unauthorized".</h2>
            <p>
                Something is broken. Please let us know what you were doing when this error occurred.
                We will fix it as soon as possible. Sorry for any inconvenience caused.
            </p>
        </div>
    </body>
</html>
```

Your answer is strange coz when i have an exception, even in dev i have a json response.

**Comment by gries** [comment]
Hi,
The error you have posted is a 401 error not a TypeError.
I have checked out a fresh project and created a TypeError and I'm getting JSON responses as expected.
`curl -X POST "http://localhost:8080/greetings" -H "accept: application/ld+json" -H "Content-Type: application/ld+json" -d "{ \"name\": \"test\"}"`
Procudes:
```
{
  "@context": "/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Argument 1 passed to App\\Entity\\Greeting::testTypeError() must be of the type int, string given, called in /srv/api/src/Entity/Greeting.php on line 53",
...
```
without any modification to the standard distribution.

Can you give more specifics on your project and on how to reproduce the error?

**Comment by Rebolon** [comment]
Sorry to be slow to answer. But i have certainly missed something at a moment.
It works in production.
```
{
    "@context": "\/api\/contexts\/ConstraintViolationList",
    "@type": "ConstraintViolationList",
    "hydra:title": "An error occurred",
    "hydra:description": "patient: This value should not be blank.",
    "violations": [
        {
            "propertyPath": "patient",
            "message": "This value should not be blank."
        }
    ]
}
```
