### ISSUE TITLE
return graphQL Response without edges and nodes

### ISSUE THREAD

**Issue by darkcattz** [api-platform/api-platform#1181]
Hello, 

Just one question. Is it possible to get graphQL Response without edges and nodes for collections (as standard JSON REST response ?)

Thanks

**Comment by alanpoulain** [comment]
This is not supported yet.

**Comment by darkcattz** [comment]
Ok thanks

**Comment by alanpoulain** [comment]
You can disable the pagination though.

**Comment by darkcattz** [comment]
> You can disable the pagination though.

How can I disable it? I had to miss it in the doc
Thanks ;)

**Comment by alanpoulain** [comment]
https://api-platform.com/docs/core/pagination/#disabling-the-pagination

**Comment by darkcattz** [comment]
Thanks. 
There is a way to target only GraphQL without disable pagination for REST ?

**Comment by alanpoulain** [comment]
No but maybe we should :thinking:

**Comment by darkcattz** [comment]
oh shame, I need the pagination for REST.
Thanks again.

**Comment by darkcattz** [comment]
Hello, 

I tried to disable pagination for an entity : 

```
/**
 * @ApiResource(attributes={"pagination_enabled"=false})
 */
class Preferences {
...
}
```

And for GraphQL request : 

```
query {
preferences {
        currency
        defaultVat
    }
}
```

Same Error message. It returns a preferencesConnection : 
```
{"errors":[{"message":"Cannot query field \u0022currency\u0022 on type \u0022PreferencesConnection\u0022.","extensions":{"category":"graphql"},"locations":[{"line":1,"column":186}]},{"message":"Cannot query field \u0022defaultVat\u0022 on type \u0022PreferencesConnection\u0022.","extensions":{"category":"graphql"},"locations":[{"line":1,"column":195}]}]}
```

Thanks.

**Comment by alanpoulain** [comment]
The feature will be in 2.5.

**Comment by darkcattz** [comment]
Great job. Thanks !

**Comment by jannes-io** [comment]
@alanpoulain , we are on 2.6.x-dev at the moment and still require edges/nodes. Is there something we need to enable to have this behavior? I also can't find anything in the documentation that mentions it for Collections.

**Comment by alanpoulain** [comment]
Have you read: https://api-platform.com/docs/core/graphql/#disabling-the-pagination?

**Comment by jannes-io** [comment]
@alanpoulain that only references the pagination.

> The feature will be in 2.5.

I thought this referred to no longer having to use edges/nodes on Collections. Is this planned for somewhere in the near future?

**Comment by alanpoulain** [comment]
Edges/nodes and pagination are related. It follows the Relay spec: https://facebook.github.io/relay/graphql/connections.htm.
If you disable pagination, you will not have edges/nodes anymore because there is no pagination anymore.
If you want to keep pagination but don't like the Relay specification, you can use page-based pagination (https://api-platform.com/docs/master/core/graphql/#using-the-page-based-pagination) but I wouldn't recommend it.

**Comment by jannes-io** [comment]
@alanpoulain thanks a bunch! We are however experiencing an internal server error when we disable pagination.
`
errors": [
    {
      "debugMessage": "\"Doctrine\\ORM\\Query::setFirstResult()\" or/and \"Doctrine\\ORM\\Query::setMaxResults()\" was/were not applied to the query.",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "trace": [
        {
          "file": "/var/www/html/vendor/api-platform/core/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php",
          "line": 182,
          "call": "ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\AbstractPaginator::__construct(instance of Doctrine\\ORM\\Tools\\Pagination\\Paginator(100))"
        },
       ...
    ]}]
`
Any idea?

**Comment by alanpoulain** [comment]
Make sure the cache is cleared (sometimes it needs to be cleared twice).
