### ISSUE TITLE
Error on classes with inheritance 

### ISSUE THREAD

**Issue by wimme002** [api-platform/api-platform#1184]
After upgrading api-platform core from 2.4.3, there seems to be an error introduced when inheritance is used.

Example code:
https://github.com/wimme002/api-platform-abstract-class/tree/master/src/Entity

creating a new tire on an existing Bus throws an error:

`curl -X POST "http://127.0.0.1:8000/api/tires" -H "accept: application/ld+json" -H "Content-Type: application/ld+json" -d "{ \"vehicle\": \"/api/buses/1\"}"`

This code works perfectly on 2.4.3 but throws the following exception now:

> {"@context":"\/api\/contexts\/Error","@type":"hydra:Error","hydra:title":"An error occurred","hydra:description":"Cannot instantiate abstract class App\\Entity\\Vehicle","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"\/vagrant\/api-platform\/vendor\/symfony\/serializer\/Normalizer\/AbstractNormalizer.php","line":527,"args":[]},{"namespace":"Symfony\\Component\\Serializer\\Normalizer","short_class":"AbstractNormalizer","class":"Symfony\\Component\\Serializer\\Normalizer\\AbstractNormalizer","type":"-\u003E","function":"instantiateObject","file":"\/vagrant\/api-platform\/vendor\/symfony\/serializer\/Normalizer\/AbstractObjectNormalizer.php","line":231,"args":[["array",[["string","\/api\/buses\/1"]]],["string","App\\Entity\\Vehicle"],["array",{"operation_type":["string","collection"],"collection_operation_name":["string","post"],"api_allow_update":["boolean",false],"input":["null",null],"output":["nul......

[This is the commit that breaks the code:](https://github.com/api-platform/core/commit/717b90956a54379e33db1a08a55978b8d5ac5496)

**Comment by nik-lampe** [comment]
Having the same issue.

Thanks! You saved me many hours of searching for the cause. I thought it was related to symfony/serializer (it might be)

Downgrading to 2.4.3 works for me for now

**Comment by soyuka** [comment]
I think that @teohhanhui fixed it but it's not released yet!

**Comment by wimme002** [comment]
This one seems fixed, I can't reproduce te error any more.

Thanks!
