### ISSUE TITLE
CQRS and Custom Operation

### ISSUE THREAD

**Issue by FabienSalles** [api-platform/api-platform#1186]
Hi,

I initiated a project with Api Plateform and Api Admin. I tried to use the CQRS Pattern in order to manage my first resource (corresponding to the user management of my app) but this was not working very well.

**My observation** :

1. [The example in the documentation](https://api-platform.com/docs/core/messenger/#dispatching-a-resource-through-the-message-bus)  indicate to create a new resource for the Command but that causes some problems : 
    * It would be logic to have a "POST" or "PUT" operation like the example but this seems to break API Admin because the resource does not have "GET" operation. I found this conclusion [here](https://github.com/api-platform/admin/issues/73#issuecomment-388828449) and [here](https://github.com/api-platform/admin/issues/73#issuecomment-436509343) 
   * Independently of the previous bug, I break my swagger documentation when I override the `shortName` into `User` in order to group all my resources link to the `User` resource : the resource used for the whole documentation is always the first one

2. I tried to work around these problems by using `input` data transformers on additional operations in my main resource but it comes into conflcts with the activation of the messenger component : Data transformers are called before the Data Persister and the resource is sent to messenger with a Data Persister. So the object that is recovered by the Message Handler is not the Command but the transformed Entity and that does not respect the CQRS pattern.

**What I have done** :

I override the `SerializerContextBuilder` class in order to check if the messenger is activated and check if I have an input specified on my operation. If it is true I changed the context of my operation by using my `input` class into the `resource_class` of the operation. By doing that, Data transformers aren't used, the DeserializeListener use the correct class and the Swagger documentation use the correct resource but this seems to be a dirty fix and do not follow your resource declaration...

In my opining we should be able to use the CQRS pattern with additional operations and the Command should not be sent to the MessengerBus by a Data Persister.

What do you thinking about this ?

**Comment by soyuka** [comment]
> It would be logic to have a "POST" or "PUT" operation like the example but this seems to break API Admin because the resource does not have "GET" operation. I found this conclusion here and here

There are some workarounds for this.

> I tried to work around these problems by using input data transformers on additional operations in my main resource but it comes into conflcts with the activation of the messenger component : Data transformers are called before the Data Persister and the resource is sent to messenger with a Data Persister. So the object that is recovered by the Message Handler is not the Command but the transformed Entity and that does not respect the CQRS pattern.

Just use `input="messenger"` and it'll send the Input instead of the tranformed entity.

**Comment by teohhanhui** [comment]
You should not expose commands through a RESTful API. Using CQRS should not mean exposing the internal architecture to the client.

**Comment by FabienSalles** [comment]
Thanks for your replies. 

Independently of the API Admin I try to understand how to fix all my use cases but I continue to find new problems to solve.

What I would like to have :

1.  group all my endpoints relative to a resource in one section in the swagger documentation
2.  create specifics operations/actions with the CQRS pattern and messenger component link to a same resource
3. configure the serialization of my command/operation/action : I have some properties to hide for the documentation
4. configure the serialization of my resource : I have some properties to hide and I would like to flat some information like my embedded value objects.


> You should not expose commands through a RESTful API. Using CQRS should not mean exposing the internal architecture to the client.

**Have you an example in order to achieve this by fulfilling all my previously listed criteria ?**

My commands aim to stay simple and be valid. That's why I started by exposing them not like the documentation but like custom operation in order to group them in one section in the swagger documentaiton.

For the point 1 and 2,  I change my fix exposed in my first message :  I delete the overriding of the SerializerContextBuilder class, disable the deserialization of the operation and create a new listener in order to deserialize my command independently of my resource. Like this,  I feel that I do not change the way API platform works, I just add a new feature in order to group my endpoints.

For the point 3 I find 2 solution : 
1. use serialization group like the documentation. This seems to be logic when we have multiple operations for the same class/resource but by my side, I only have one operation for my "command" so I find that it loses its meaning.
2. I saw that if I declare a new resource that use the same class of my command (use as input in a custom operation of my resource) the configuration of my properties is used but this solution exposed my internal properties in the model of the documentation : 
 
![Capture d’écran de 2019-07-31 15-13-46](https://user-images.githubusercontent.com/937901/62214703-e1284800-b3a5-11e9-8e98-d4ee2e763b07.png)
![Capture d’écran de 2019-07-31 15-13-25](https://user-images.githubusercontent.com/937901/62214704-e1c0de80-b3a5-11e9-8044-38fe8b3f922a.png)

So i don't know what is the better solution.

For the point 4, I also find 2 solutions that I have not started to implement but I do not like them : 
1. create a custom normalizer for the symfony serialization but this seems to not be read by the swagger documentation so I have to configure it manually
2. create a new DTO and use the output feature of the resource but this create a new way to handle the serialization process of my resource and I think I will have also to configure the swagger documentation when I will have complex relations between objects that I want to expose in one endpoint (like product objects with generic models and specific attributes/values depending of the product that I want to retrieve).

**I would like to find the better solution for all my use cases.** I am interested in any track if you have one. Thanks in advance.

**Comment by FabienSalles** [comment]
I close this issue.

If anyone is interested I reproduced the solution that I found in the past in a small project for a [technical test ](https://github.com/FabienSalles/smartengo-apip) last month.

I created 2 operations for [read](https://github.com/FabienSalles/smartengo-apip/blob/master/apps/api/src/Infrastructure/ApiPlatform/EventSubscriber/ReadQuerySubscriber.php) and [write](https://github.com/FabienSalles/smartengo-apip/blob/master/apps/api/src/Infrastructure/ApiPlatform/EventSubscriber/WriteCommandSubscriber.php) operation and be able to use my commands and queries in my handlers.

My resources declaration are more verbose.
Last year I abandoned the swagger documentation in favor of postman. I seem to have heard that it was better now.
For React admin, I ended up not using it too, so I don't know if my problems still exist
