### ISSUE TITLE
GraphQL allows mutations using GET requests

### ISSUE THREAD

**Issue by ddelbondio** [api-platform/api-platform#1188]
When sending a GraphQL mutation, api platform does not check whether the mutation was sent in a HTTP POST request. 

For example simply sending a request like `curl -X GET http://example.com/graphql?query=mutation...` successfully runs the mutation. 

While the spec doesn't seem to forbid that, I think it's generally a good idea to prevent this by default.

**Comment by alanpoulain** [comment]
It would mean parsing the query to know if it's a mutation or not (where it should not be done here) to prevent it in the case of a GET.
GraphQL has not been thought like this, and I think it's the responsibility of the user to choose the right way to implement it.

**Comment by ddelbondio** [comment]
This is actually a security problem on different levels:
- It completely circumvents any browser security for CORS requests as the browser will only block the client from reading a get response, but not the actual request
- depending on the setup it circumvents CSRF protections
- it violates the HTTP spec

In my opinion this gives the users a pretty big gun to shoot themselves in the foot. Someone not acutely aware of the workings of graphql might not even be aware that there is the possibility of get requests suddenly doing modification.
