### ISSUE TITLE
Documentation: Serialization terminology seems a bit confusing

### ISSUE THREAD

**Issue by slavo2** [api-platform/api-platform#1199]
According to picture at https://api-platform.com/docs/core/serialization/
the **serialization** process contains two steps:
**serialize** = _*normalize*_ -> _*encode*_
similarly **deserialization** process contains two steps:
**deserialize** = _*decode*_ -> _*denormalize*_

However, under [Available **Serializers** ❗️ ](https://api-platform.com/docs/core/serialization/#available-serializers) there are listed things, which seems to take care of exporting / importing from different outer formats: JSON-LD, HAL, JSON, XML, CVS, YAML.
I understand that process is actually an _**encoding**_ / _**decoding**_.

In the same time the services are marked as 
api_platform.jsonld.**normalizer**❗️.item, 
api_platform.hal.**normalizer**❗️.item 
api_platform.**serializer**❗️.**normalizer**❗️.item

😕 

Shouldn't they by called and tagged as '**encoders**' or '**decoders**'?
Or are they complex ones, and then they are all 'serializers' with different 'encoders' set?

**Comment by dunglas** [comment]
No it's correct:

The JSON-LD/HAL/JSON:API/... normalizers have the responsibility to create the PHP array respecting the data structures and key names for the selected format (normalization).
Then the JSON encoder will transform these PHP arrays in JSON.

If you think that we can make it more clear in the docs, a PR is very welcome!

**Comment by slavo2** [comment]
Ah, thanks for explanation, @dunglas .
