### ISSUE TITLE
Handling file upload

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/api-platform#12]
I'm trying to integrate with [VichUploaderBundle](https://github.com/dustin10/VichUploaderBundle) but DunglasApiBundle doesn't support `multipart/form-data`

Is that intended?

**Comment by teohhanhui** [comment]
More generally, how'd you handle file uploads in a REST API?

**Comment by dunglas** [comment]
There is nothing built in API Platform to handle file upload but VinchUploaderBundle should work as expected. I never tried but if it doesn't work can you give more details about the error.

For REST API in general I usually create a special endpoint accepting from/multipart data. An alternative is to add a special field to the posted JSON document containing the file encoded in base64 (less performant but easier to handle especially when dealing with mobile apps and browsers).

It would be nice to have native file upload handling in API platform. Any work on this topic is welcome (doc on how to use Symfony features or code to ease

**Comment by teohhanhui** [comment]
The way [PostCollectionAction](https://github.com/dunglas/DunglasApiBundle/blob/6e21fdb447d9dadbefc5d8fcdc46fe4669315627/Action/PostCollectionAction.php#L51) works:

```php
        return $this->serializer->deserialize(
            $request->getContent(),
            ...
        );
```

It bypasses PHP / Symfony's processing of request body, instead relying on the Symfony Serializer...
At first I thought of implementing an encoder for `multipart/form-data`, but history tells us it shall not be done: symfony/symfony#10381

So no, `multipart/form-data` seems to be out of the question.

**Comment by teohhanhui** [comment]
Another overarching issue is that DunglasApiBundle does not work with `application/x-www-form-urlencoded` and `multipart/form-data` `Content-Type`s

**Comment by dunglas** [comment]
Did you try with a controller not handled at all by ApiBundle (a plain old Symfony controller)? You can always access to API Platform services if necessary.

**Comment by dunglas** [comment]
It's not an issue IMO. You can register specific actions supporting such formats.

**Comment by teohhanhui** [comment]
Considering DunglasApiBundle is built around the Symfony Serializer workflow (normalizers), I imagine it wouldn't be straightforward to subvert that while still making full use of the services...

I'll just go with base64 encoded string for now...

**Comment by dunglas** [comment]
Personnaly I've created a controller dealing directly with the Symfony request to get the data from the multipart post request and using the serializer (but not the deserializer) to generate the JSON-LD response content. But base 64 works too.

**Comment by dunglas** [comment]
Related Symfony PR: symfony/symfony#16164

**Comment by npotier** [comment]
Hi @dunglas thank you for your amazing work. Do you thing that you could provide an example of your controller ?

**Comment by AlexandreHagen** [comment]
Now that Symfony 3.1 is released. Do we have some docs or explanations to upload files with Api-platform V2 alpha ?

**Comment by dunglas** [comment]
No, the doc is the missing part and any help on this is very welcome. There is something like a doc for the SF feature however: https://github.com/symfony/symfony/pull/16164

**Comment by AlexandreHagen** [comment]
Ok thanks ! I will try with that. For doc, I will see when my upload system will be finished.

**Comment by AlexandreHagen** [comment]
So if I understand well. We can't upload files through Api-platform 2 ? We still have to create our own controller or use base 64 to do that ? And Symfony 3.1 just provide new tools to handle files thanks to DataUriNormalizer ? I think I do not understand something, but I don't know what !

**Comment by AlexandreHagen** [comment]
Anyone ? A short response please.

**Comment by dunglas** [comment]
> So if I understand well. We can't upload files through Api-platform 2 ? We still have to create our own controller or use base 64 to do that ? And Symfony 3.1 just provide new tools to handle files thanks to DataUriNormalizer ? I think I don't understand something, but I don't know what !

Yes and it will be always like that. base64 works out of the box with API Platform 2. Multipart however isn't JSON-based and require to write a custom controller.

**Comment by AlexandreHagen** [comment]
@dunglas Thanks a lot !

**Comment by teohhanhui** [comment]
I suspect the `DataUriNormalizer` in Symfony Serializer is only good for a tiny amount of data (I have not tried it). Going by thephpleague/uri#11, I'd expect a 1MB file to fail to upload due to `pcre.backrack_limit` being exceeded...

Also see https://github.com/symfony/symfony/pull/16164#discussion_r52104290 and https://github.com/symfony/symfony/pull/16164#discussion_r52104421, which I don't think have been addressed yet.

**Comment by dunglas** [comment]
@teohhanhui exactly.

**Comment by Simperfit** [comment]
I think this can be closed
