### ISSUE TITLE
Rate limit feature

### ISSUE THREAD

**Issue by cve** [api-platform/api-platform#120]
Hi,

I have a question is this platform has a rate limit feature or it can works with https://github.com/jaytaph/RateLimitBundle? If so, how can I integrate it? It seems that the RateLimitBundle secures controllers with annotations, but api-platform does not expose controllers explicitly...

**Comment by teohhanhui** [comment]
You can still create custom controller actions if you choose to: https://github.com/api-platform/docs/blob/master/core/operations.md#creating-custom-operations-and-controllers

**Comment by Simperfit** [comment]
@cve You could made a bridge between ApiPlatform and the RateLimitBundle ;)
