### ISSUE TITLE
Doc update request : "No identifiers defined for resource of type" got when trying the sample in the documentation for MongoDB support 

### ISSUE THREAD

**Issue by ellioh-thoto** [api-platform/api-platform#1206]
Hello, 

I would suggestion a correction/improvement of the doc "MongoDB Support" https://api-platform.com/docs/core/mongodb/.

A sample below is provided for the document declaration. 

```
<?php
// api/src/Document/Offer.php

namespace App\Document;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ODM\MongoDB\Mapping\Annotations as ODM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ApiResource(iri="http://schema.org/Offer")
 *
 * @ODM\Document
 */
class Offer
{
    /**
     * @ODM\Id(strategy="INCREMENT", type="integer")
     */
    private $id;

    /**
     * @ODM\Field
     */
    public $description;

    /**
     * @ODM\Field(type="float")
     * @Assert\NotBlank
     * @Assert\Range(min=0, minMessage="The price must be superior to 0.")
     * @Assert\Type(type="float")
     */
    public $price;

    /**
     * @ODM\ReferenceOne(targetDocument=Product::class, inversedBy="offers", storeAs="id")
     */
    public $product;
}
```

When using this code like it is, it generate the following error during the build : 

`No identifiers defined for resource of type [...]`

The fix consist in adding the getter to the class declaration as it is done for the Product Document. 

```
[...]
public function getId(): ?int
{
    return $this->id;
}
```

Suggestion : to add the code above in the documentation. 

B. R.

**Comment by alanpoulain** [comment]
Thank you for your report.
The PR is here: https://github.com/api-platform/docs/pull/853
Don't hesitate to do the PR directly the next time :wink:
You can even do it automatically by using the pencil when going here: https://github.com/api-platform/docs/blob/2.4/core/mongodb.md
![image](https://user-images.githubusercontent.com/10920253/62282384-c0b4c800-b44f-11e9-9fcf-94d4f681f1c7.png)
