### ISSUE TITLE
Question about Restangular

### ISSUE THREAD

**Issue by OCoulonAckwa** [api-platform/api-platform#121]
Hi
You use restangular in your demo code.
Restangular seems to be dead.
Is there an alternative ? or an active fork ?

Thank's

**Comment by Simperfit** [comment]
I'm using ng-admin or hm-admin (still in progress) for generated backend.

For the front you could use restAngular, angular 1.5 / Angular2 (Maybe wait for the stable version since it's changing alot between RC's) / React. It depends on what you want to achieve.

**Comment by dunglas** [comment]
@OCoulonAckwa for my newer projects I simply use React/Redux with [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch).

**Comment by dunglas** [comment]
Btw are you sure that Restangular is dead? The last commit is from June (no very old).
