### ISSUE TITLE
Serialization groups not respecting security?

### ISSUE THREAD

**Issue by abeal-hottomali** [api-platform/api-platform#1214]
I'm seeing a possible issue with security and serialization groups.  It appears that the groups do not respect security declaration on subresources.

Below is the definition for two entities, "Foo" and "Bar", with a 1:1 relationship between them (starting from Foo).  I've added a security declaration to Bar, indicating that it should only be accessible to admin users.:

```php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiSubresource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ApiResource(
 *     normalizationContext={"groups"={"read"}},
 *     denormalizationContext={"groups"={"write"}}
 * )
 * @ORM\Entity()
 */
class Foo
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"read", "write"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"read", "write"})
     */
    private $foo;

    /**
     * @ORM\OneToOne(targetEntity="App\Entity\Bar", cascade={"persist", "remove"})
     * @ORM\JoinColumn(nullable=false)
     * @Groups({"read", "write"})
     * @ApiSubresource()
     */
    private $bar;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFoo(): ?string
    {
        return $this->foo;
    }

    public function setFoo(?string $foo): self
    {
        $this->foo = $foo;

        return $this;
    }

    public function getBar(): ?Bar
    {
        return $this->bar;
    }

    public function setBar(Bar $bar): self
    {
        $this->bar = $bar;

        return $this;
    }
}
```
```php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ApiResource(
 *     normalizationContext={"groups"={"read"}},
 *     denormalizationContext={"groups"={"write"}},
 *     itemOperations={
 *       "get"={
 *         "access_control"="is_granted('ROLE_ADMIN')"
 *       }
 *     }
 * )
 * @ORM\Entity()
 */
class Bar
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"read", "write"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Groups({"read", "write"})
     */
    private $bar;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBar(): ?string
    {
        return $this->bar;
    }

    public function setBar(?string $bar): self
    {
        $this->bar = $bar;

        return $this;
    }
}
```
I also created a couple instances as fixtures:

```php
//In \App\DataFixtures\TestFixtures:
// ...
        $foo = new Foo();
        $foo->setFoo('foo');
        $bar = new Bar();
        $bar->setBar('bar');
        $foo->setBar($bar);
        $this->manager->persist($foo);
        $this->manager->flush();
// ...
```
This presumes JWT-based authentication, and two roles, `ROLE_ADMIN` and `ROLE_USER`.

When I log in as `ROLE_USER`, and hit the endpoint `/bars/1`, I get the expected response:

```json
{
    "@context": "\/contexts\/Error",
    "@type": "hydra:Error",
    "hydra:title": "An error occurred",
    "hydra:description": "Access Denied.",
    "trace": ...
}
```

However, when I request `foos/1`, I get back:

```json
{
    "id": 1,
    "foo": "foo",
    "bar": {
        "id": 1,
        "bar": "bar"
    }
}
```

Am I misunderstanding something here about the role of serialization groups?  I wouldn't expect them to supersede access control declarations.  Can anyone reproduce this?

**Comment by abeal-hottomali** [comment]
Note: I've created a new repository [here](https://github.com/abeal-hottomali/api-platform-test/tree/serialization_security_issue_test) that demonstrates this issue.  Build against most recent api-platform [official distribution](https://github.com/api-platform/api-platform/releases/tag/v2.4.5) (cloned from repo template initially).

**Comment by teohhanhui** [comment]
You're misunderstanding what the `access_control` attribute does. It checks authorization for the resource. If you do want to restrict access to `Foo` based on its `bar` property, you have to add `access_control` (which checks the `bar` property) on the `Foo` resource.

**Comment by abeal-hottomali** [comment]
> "It checks authorization for the resource"

That is what I thought it did - I guess I don't understand.  I'm trying to restrict access to Bar for *all* requests that are not admin. The access control does restrict access to Bar when requested directly, as expected.  It does not restrict it in conjunction with Foo requests, however.

What I would expect to happen is that Bar is not shown, because (as you say) Bar has an access control restriction on it, and the user is not authorized to see Bar.  So when I request Foo, Foo should be shown, but without Bar content, e.g.:

```json
{
    "id": 1,
    "foo": "foo"
}
```

or 

```json
{
    "id": 1,
    "foo": "foo",
    "bar": {}
}
```

**Comment by teohhanhui** [comment]
Yes, that's a misunderstanding. `access_control` doesn't do that. It works at the API operation level.

**Comment by abeal-hottomali** [comment]
I see, thank you.

For this comment, then: 
> If you do want to restrict access to Foo based on its bar property, you have to add `access_control` (which checks the bar property) on the Foo resource.

I would then ask if this can be done on a per-property basis, but I see that has already been asked [here](https://github.com/api-platform/api-platform/issues/789).  Still at a bit of a loss as to the best way to lock this stuff down, but that's not the same as a platform bug, so I'll close this issue.  Thanks!

**Comment by teohhanhui** [comment]
You can restrict access to `Foo` based on the value of its `bar` property. This is achievable with `access_control` on `Foo`.

Alternatively, if you want to hide the `bar` property based on its value, you can use dynamic serializer groups: https://api-platform.com/docs/core/serialization/#changing-the-serialization-context-dynamically
