### ISSUE TITLE
Question about exporting json schema

### ISSUE THREAD

**Issue by domhaas** [api-platform/api-platform#1222]
Hi,

I couldn't find anything about creating json-schema for forms inside api platform. I'm currently evaluating this project: [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form) and I got it working together with this Lib [LiipImagineBundle](https://github.com/liip/LiipImagineBundle). But it depends on a symfony form.

Has anybody an idea how to get a json schema in api platform, maybe with some workaround via swagger?
Thank you in advance.

Dom

**Comment by dunglas** [comment]
It's a work in progress, see https://github.com/api-platform/core/pull/2983.

**Comment by domhaas** [comment]
> It's a work in progress, see [api-platform/core#2983](https://github.com/api-platform/core/pull/2983).

thanks @dunglas 
I think this would be a "mighty" feature for api platform, because I think we all hate forms. So hoping this is getting soon implemented.
Thank you in this way for the great work - did my first journey with api platform and was quite impressed.
