### ISSUE TITLE
Embedded property is mapped as `string` instead of `object` in custom POST request

### ISSUE THREAD

**Issue by s1k3s** [api-platform/api-platform#1227]
I am trying to create a custom POST action with that needs to have the following body:

```
# post /custom-greeting
{
    "name": "string",
    "comment": {
          "name": "string",
          "number": 1
     }
}
```

But api-platform is generating the following request in swagger:

```
{
  "name": "string",
  "comment": "string"
}
```

These are my entities:

```
// src/Entity/Greeting.php

<?php

declare(strict_types=1);

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ApiResource(
 *     itemOperations={},
 *     collectionOperations={
 *          "custom-greeting"={
 *              "method"="POST",
 *              "path"="/custom-greeting",
 *              "controller"=CustomGreetingAction::class,
 *              "denormalization_context"={"groups"={"write"}}
 *          }
 *     },
 * )
 */
class Greeting
{
    /**
     * @var string
     * @Groups({"write"})
     */
    public $name = '';

    /**
     * @var Comment
     * @Groups({"write"})
     */
    public $comment;
}
```

```
// src/Entity/Comment.php

<?php

declare(strict_types=1);

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ApiResource(
 *     itemOperations={},
 *     collectionOperations={},
 *     denormalizationContext={"groups"={"write"}}
 * )
 */
class Comment
{
    /**
     * @var string
     * @Groups({"write"})
     */
    public $name;

    /**
     * @var int
     * @Groups({"write"})
     */
    public $number;
}
```

I have set the denormalization groups properly for both my entities. I have set the proper `@var` annotations on the properties. 

Can someone tell me why it doesn't map the relation properly and it maps it as `string`?

**Comment by remoteclient** [comment]
After a short chat on slack, we found out that all is serialized perfectly. Only issue is that it is not shown correctly on swagger.
My guess is, that the Comment entity is not mapped to the database which leads to the behaviour I described [here](https://github.com/api-platform/core/issues/2868).
Solution should come with [this](https://github.com/api-platform/api-platform/issues/1197)

**Comment by dunglas** [comment]
The new infrastructure regarding JSON Schema and OpenAPI I introduced in #2983 should help. Could you try if it works with master? If not, this class should be patched: https://github.com/api-platform/core/blob/master/src/JsonSchema/SchemaFactory.php

**Comment by s1k3s** [comment]
@remoteclient @dunglas Thanks, I see there have been multiple requests for such features. I tested it today with v2.4.6 and it works fine. Closing.
