### ISSUE TITLE
[Question] Specification for API filters parameters

### ISSUE THREAD

**Issue by wRLSS** [api-platform/api-platform#1229]
Currently API Platform uses a layer of conversion between GET parameters syntax and actually applied filters. 
https://api-platform.com/docs/core/filters/

We are currently looking for a way to use similar approach for applications which are not using API platform, and even PHP. Is there some sort of specification document for filter syntax, or it's home-cooked?

**Comment by dunglas** [comment]
Unfortunately now. OData contains a (complex) specification for filter. Loopback (a framework similar to API Platform written in Node) also has its own convention.
