### ISSUE TITLE
Varnish doesn't cache request with Authorization header

### ISSUE THREAD

**Issue by Brewal** [api-platform/api-platform#1233]
I'm trying to implement Varnish cache to my API with authentification. 
While testing from the API Platform distribution (2.4.6), if I do this request on the API without cache : 

```bash
curl -sSL -D - -H "Authorization: atoken" http://localhost:8080/greetings -o /dev/null
```

I get these headers : 

```
HTTP/1.1 200 OK
Server: nginx/1.17.3
Content-Type: application/ld+json; charset=utf-8Transfer-Encoding: chunked
Connection: keep-alive
X-Powered-By: PHP/7.3.6
Vary: Accept
Vary: Content-Type
Vary: Authorization
X-Content-Type-Options: nosniff
X-Frame-Options: deny
Cache-Control: max-age=0, public, s-maxage=3600
Date: Mon, 26 Aug 2019 10:14:35 GMT
Link: <http://localhost:8080/docs.jsonld>; rel="http://www.w3.org/ns/hydra/core#apiDocumentation"
ETag: "deb94667cc031e94935546c727fbb298"
Cache-Tags: /greetings
X-Debug-Token: 2d4fd3
X-Debug-Token-Link: http://localhost:8080/_profiler/2d4fd3
X-Robots-Tag: noindex
```

But if I do several requests on the cache API : 

```bash
curl -sSL -D - -H "Authorization: atoken" http://localhost:8081/greetings -o /dev/null
```

I get these headers, with `Age` always at `0` : 

```
HTTP/1.1 200 OK
Server: nginx/1.17.3
Content-Type: application/ld+json; charset=utf-8
X-Powered-By: PHP/7.3.6
Vary: Accept, Content-Type, Authorization
X-Content-Type-Options: nosniff
X-Frame-Options: deny
Cache-Control: max-age=0, public, s-maxage=3600
Date: Mon, 26 Aug 2019 10:17:50 GMT
Link: <http://localhost:8081/docs.jsonld>; rel="http://www.w3.org/ns/hydra/core#apiDocumentation"
ETag: "deb94667cc031e94935546c727fbb298"
X-Debug-Token: 0942ed
X-Debug-Token-Link: http://localhost:8081/_profiler/0942ed
X-Robots-Tag: noindex
X-Varnish: 25
Age: 0
Via: 1.1 varnish (Varnish/6.2)
Accept-Ranges: bytes
Content-Length: 121
Connection: keep-alive
```

Looking at the `/api/docker/varnish/conf/default.vcl` file, it does not seems that Varnish should pass requests with Authorization headers. 

Maybe this is a desired behavior ? How can I cache those requests ?

**Comment by dunglas** [comment]
You have to unset the header `Authorization` header in the VCL if you want to cache such requests. See https://varnish-cache.org/docs/trunk/users-guide/increasing-your-hitrate.html#authorization

**Comment by mRoca** [comment]
For the record, if you need to keep the Authorization header, you can override the [buildin.vcl](https://github.com/varnishcache/varnish-cache/blob/master/bin/varnishd/builtin.vcl) Varnish default rules by returning something in the `vcl_recv` part of your `default.vcl` file.

```vcl
sub vcl_recv {
  # ...
  # Default rules of docker/varnish/conf/default.vcl
  # ...

  if (req.method != "GET" && req.method != "HEAD") {
    /* We only deal with GET and HEAD by default */
    return (pass);
  }

  ## This is the part you must remove or update
  #if (req.http.Authorization || req.http.Cookie) {
  #  /* Not cacheable by default */
  #  return (pass);
  #}

  return (hash);
}
```

**Comment by Brewal** [comment]
Thanks for the help ! I understand. As caching authenticated requests with Varnish doesn't sounds quite safe (I need to validate tokens before), I think I will try to improve caching on the lower levels

**Comment by mRoca** [comment]
Indeed. If you still need cache for your authenticated requests and if you are using JWTs, you can also check the [JWT validity in the Varnish `vcl_recv` vcl](https://github.com/opositatest/varnish-jwt/blob/master/varnish/default.vcl).
