### ISSUE TITLE
Is it neccessary to define "0.0.0" as default version ?

### ISSUE THREAD

**Issue by zorn-v** [api-platform/api-platform#1235]
Or maybe some parameter to not show version in docs ? (`[ Base URL: / ]` also does not sence usually)

Imagine I have some service and want to share docs to others. Just for "you can look at here". Maybe share for all. And I dont want another "version control" because all in docs. 
Api not public, just for client app. Proper security is assigned.

Imagine fastidious customer.

**Comment by dunglas** [comment]
The `info.version` is required by the OpenAPI specification, it cannot be omitted: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#infoVersion
