### ISSUE TITLE
"ApiProperty(identifier=true)" works in YAML file but not in annotation

### ISSUE THREAD

**Issue by Moranbzh** [api-platform/api-platform#1238]
Hi,

I try to define the ID field in an entity class, it works when I define my field in the yaml conf file (resources.yaml) but it doesn't work when I set it in annotation in my entity class. 

I work with Symfony 4.2 and I have installed the Api platform core module.

**My entity class :** 

```
class Article
{
    /**
     * @ApiProperty(identifier=true)
     * @ORM\Column(type="integer")
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Groups({"article_get"})
     */
    private $id_article;

[...]

```

**Error message :** 
```
"type": "https:\/\/tools.ietf.org\/html\/rfc2616#section-10",
  "title": "An error occurred",
  "detail": "Not found, because of an invalid identifier configuration",
  "trace": [{
    "namespace": "",
    "short_class": "",
    "class": "",
    "type": "",
    "function": "",
    "file": "\/var\/www\/***\/vendor\/api-platform\/core\/src\/EventListener\/ReadListener.php",
    "line": 110,
    "args": []
```

**Comment by d0niek** [comment]
It is not that `@ApiProperty(identifier=true)` means your entity is not any more Doctrine entity ([link](https://api-platform.com/docs/core/serialization/#entity-identifier-case))? So maybe you should delete `@ORM` annotations?
In my case every think works with annotation `@ApiProperty(identifier=true)`, I can GET entity collections.

**Comment by teohhanhui** [comment]
Hi, please provide more information to help us help you.

In fact, there's no need to manually set `identifier=true` when you use `@ORM\Id` as there's already a `PropertyMetadataFactory` for that.

**Comment by soyuka** [comment]
Feel free to give a feedback if needed, closing this as answered.
