### ISSUE TITLE
[Question] ApiFilter BooleanFilter::class, properties={"posts.enabled"} with only 1 item who's enabled property is false results in parent item not being returned.

### ISSUE THREAD

**Issue by NickDuBois** [api-platform/api-platform#1241]
I have an entity with a ManyToMany property "posts" that I am trying to apply an API Filter to.

```
* @ORM\ManyToMany(targetEntity="App\Entity\Posts")
* @ORM\JoinTable(
*     name="posts",
*     joinColumns={@ORM\JoinColumn(name="parent_post_id", referencedColumnName="id")},
*     inverseJoinColumns={@ORM\JoinColumn(name="child_post_id", referencedColumnName="id")}
* )
* @Groups({"read"})
* @ApiFilter(BooleanFilter::class, properties={"posts.enabled"})
*/
private $posts;
```

and if that collection is length 1, and that 1 item has enabled=false,  when I hit the api_route.com?posts.enabled=true

the parent item doesn't come through at all.

```
id: 0
Title: "Post 1"
Enabled: true
Post: 
	1: Post 2

id: 1
Title: "Post 2"
Enabled: true
Post: 
	2: Post 3   <- because this post is not enabled, post with id 1 "Post 2" would not come through the api

id: 2
Title: "Post 3"
Enabled: false
Post: 
```

What can I do to get Post with id 1 to come through regardless of status of its post parameter?

**Comment by NickDuBois** [comment]
I'm not certain yet, but I think adding [exists] fixed my issue:

api_route.com?posts.enabled[exists]=true

I'll have to do some testing.

Sorry for the false alarm.

**Comment by teohhanhui** [comment]
Hi, the behaviour of `BooleanFilter` as you've described is 100% as intended. Please note that filters are used to filter the top-level resource items. We don't support filtering children, but filtering *by* children.

**Comment by soyuka** [comment]
If you need a custom behavior that we don't support by default please implement your own filter by following the documentation: https://api-platform.com/docs/core/filters/. I hope that this may be of some help.
