### ISSUE TITLE
[Question] How to automatically set the relationship between an embedded entity and its parent upon creation?

### ISSUE THREAD

**Issue by pierre-le** [api-platform/api-platform#1244]
Hi folks,

The title may be somewhat hard to understand, so here's an example below.

```php
class Person
{
  /**
   * @ORM\OneToMany(targetEntity="Asset", mappedBy="person", cascade={"all"})
   * @ApiProperty(writableLink=true)
   */
  protected $assets;

  /**
   * (ORM blah blah)
   */
  protected $foo;
}
class Asset {
  /**
   * @ORM\ManyToOne(targetEntity="Person", inversedBy="assets")
   * @ORM\JoinColumn(nullable=false, referencedColumnName="id")
   */
  protected $person;

  /**
   * (ORM blah blah)
   */
  protected $bar;
}
```

Now, when I'm trying to create a new Person through the API, with one or several embedded Assets to be created along with the Person:

`POST /persons`
```json
{
  "foo": 123,
  "assets": [
    { "bar": "fish" },
    { "bar": "elephant" }
  ]
}
```

This request raises an exception:
```
An exception occurred while executing 'INSERT INTO asset (bar, person_id) VALUES (?, ?)' with params ["fish", null]:\n\nSQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "person_id" violates not-null constraint"
```

Which seems to indicate that API Platform did create the new embedded Asset object with the right values, but failed to associate it with the parent Person.
One way to circumvent is to edit the `setAssets($assets)` function to manually set the association (i.e. `for ($assets as $asset) { $asset->setPerson($this); }`). But it's kind of a hack.

Any idea on how to do that properly?

**Comment by ismail1432** [comment]
can you add `groups` in the snippet ?

**Comment by dunglas** [comment]
@ismail1432 thanks for answering!
