### ISSUE TITLE
Missing packages: to use the make:crud command

### ISSUE THREAD

**Issue by psirus0588** [api-platform/api-platform#1248]
`./api/bin/console make:crud`
or
`docker-compose exec php bin/console make:crud`

> [ERROR] Missing packages: to use the make:crud command, run:
> composer require form annotations

add to require in composer.json
```
"sensio/framework-extra-bundle": "^5.4",
"symfony/form": "4.3.*"

```

**Comment by soyuka** [comment]
This looks like a documentation issue, would you mind updating it?

**Comment by psirus0588** [comment]
aslo i find dependencies for `"symfony/form"` in `api/symfony.lock`

```
require-dev:

api-platform/core_v2.4.6		"symfony/form": "^3.4 || ^4.0",
symfony/doctrine-bridge_v4.3.3		"symfony/form": "~4.3",
symfony/framework-bundle_v4.3.3		"symfony/form": "^4.3",
symfony/security-bundle_v4.3.3		"symfony/form": "~3.4|~4.0",
symfony/twig-bridge_v4.3.3		"symfony/form": "<4.3",
symfony/twig-bundle_v4.3.3		"symfony/form": "~3.4|~4.0",


conflict:

symfony/doctrine-bridge_v4.3.3		"symfony/form": "<4.3",
symfony/framework-bundle_v4.3.3		"symfony/form": "<4.3",
symfony/twig-bridge_v4.3.3		"symfony/form": "<4.3",
symfony/web-profiler-bundle_v4.3.3	"symfony/form": "<4.3"
```


may be update packages in composer.json: 
```
	symfony/console
	symfony/dotenv
	symfony/framework-bundle
	symfony/yaml
```
from` "4.3.*" to "4.4.*"` can resolve this dependency issue for `symfony/form`
and for `api/composer.json` add only `"sensio/framework-extra-bundle": "^5.4"`

**Comment by dunglas** [comment]
`make:crud` isn't related to API Platform at all. It doesn't use API Platform. We recommend to use our own client generator instead: https://api-platform.com/docs/client-generator/
