### ISSUE TITLE
Number of pages for a pagination

### ISSUE THREAD

**Issue by seb-jean** [api-platform/api-platform#1251]
Hi,
Is it possible to get the number of pages when there is a pagination?
Thanks :)

**Comment by luca-simonetti** [comment]
you can read the totalCount and make the math on client side I guess (ex. first:10, totalCount = 95, pages = ceil(95/10) )

**Comment by seb-jean** [comment]
There is not a possibility to get it directly via the JSON for example for the totalItems it's hydra: totalItems ": 50 ?
