### ISSUE TITLE
MySQL syntax error when using GET method

### ISSUE THREAD

**Issue by Rmy5** [api-platform/api-platform#1254]
I have an entity called "Character" (generated through Symfony maker). 
The Symfony Migrations bundle migrated the entity.
When I try to retrieve the entities through the API's GET method I get a MySQL "syntax error" because "charcacter" seems to be a protected MySQL keyword and not escaped by API Platform. 

This is the generated SQL: 
SELECT c0_.id AS id_0, c0_.name AS name_1 FROM character c0_ ORDER BY c0_.id ASC LIMIT 30

This would be working:
SELECT c0_.id AS id_0, c0_.name AS name_1 FROM \`character\` c0_ ORDER BY c0_.id ASC LIMIT 30

**Comment by dunglas** [comment]
It's not related to API Platform but to Doctrine ORM.
Doctrine doesn't escape special keywords by default, see https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/basic-mapping.html#quoting-reserved-words and https://github.com/doctrine/orm/issues/2409.

**Comment by pcinvent** [comment]
I made this "API-Platform-Mysql" Github Project that made API platform works with MySQL 8, please fork, star, contribute to it, you may create an issue or ask questions there in my Repository:
https://github.com/pcinvent/api-platform-mysql
