### ISSUE TITLE
ERROR an upstream response is buffered to a temporary file

### ISSUE THREAD

**Issue by wuestkamp** [api-platform/api-platform#1255]
On some requests (like 1 in 500) I get a 500 exception from the Symfony API:

**getDoctrine_Orm_DefaultListeners_AttachEntityListenersService**
```
{
    "class": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "message": "Compile Error: require(): Failed opening required '\/srv\/api\/var\/cache\/prod\/ContainerWKxhZGH\/getDoctrine_Orm_DefaultListeners_AttachEntityListenersService.php' (include_path='.:\/usr\/local\/lib\/php')",
    "code": 0,
    "file": "\/srv\/api\/var\/cache\/prod\/ContainerWKxhZGH\/srcApp_KernelProdContainer.php:532"
}
```

**getSession_Storage_NativeService**
```
{
    "class": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "message": "Compile Error: require(): Failed opening required '\/srv\/api\/var\/cache\/prod\/ContainerAPB4itV\/getSession_Storage_NativeService.php' (include_path='.:\/usr\/local\/lib\/php')",
    "code": 0,
    "file": "\/srv\/api\/var\/cache\/prod\/ContainerAPB4itV\/srcApp_KernelProdContainer.php:532"
}
```

**getApiPlatform_Listener_View_RespondService**
```
{
    "class": "Symfony\\Component\\Debug\\Exception\\FatalErrorException",
    "message": "Compile Error: require(): Failed opening required '\/srv\/api\/var\/cache\/prod\/Container8GRzllw\/getApiPlatform_Listener_View_RespondService.php' (include_path='.:\/usr\/local\/lib\/php')",
    "code": 0,
    "file": "\/srv\/api\/var\/cache\/prod\/Container8GRzllw\/srcApp_KernelProdContainer.php:532"
}
```

Always about different files from the cache. The cache is warmed up and the application did already run 2-3 hrs in production.

The nginx throws this error at the same time:

```
2019/09/21 10:32:37 [warn] 6#6: *562 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/1/00/0000000001 while reading upstream, client: 1.1.1.1, server: _, request: "GET /url HTTP/1.1", upstream: "fastcgi://2.2.2.2:9000", host: "api.killer.sh", referrer: "https://domain.com/url2"
```

Anyone got an idea?

**Comment by dunglas** [comment]
Are you using Docker? Kubernetes?

**Comment by wuestkamp** [comment]
yes, dockerized and on kubernetes. I solved the nginx error by adding this to the nginx config:

```
fastcgi_buffer_size 128k;
fastcgi_buffers 4 256k;
fastcgi_busy_buffers_size 256k;
```

but the actual symfony errors still persist.

I'm running 2 pods of nginx and 2 of php. the pods did not restart, if that would be the case it could've explained the missing cache.

**Comment by teohhanhui** [comment]
Do you start with a new container and a fresh (Symfony) cache each time (i.e. no reused volumes)? If so, it might be a Symfony bug. Otherwise, it might just be a cache pollution problem.

**Comment by wuestkamp** [comment]
Yes, every container has a fresh own Symfony cache, no shared volumes for cache.

**Comment by teohhanhui** [comment]
Did you manage to confirm if the file is actually there?

**Comment by wuestkamp** [comment]
Can confirm the file was actually not there. The issue was caused by a wrongly configured Kubernetes readinessProbe which resulted in the cache being cleared and warmed up again, hence the missing references sometimes.

Thanks for your help here!
