### ISSUE TITLE
Google Structured Data - React

### ISSUE THREAD

**Issue by seb-jean** [api-platform/api-platform#1257]
Hi,
How to make structured data work for google in app React?
If I do axios.get('https://demo.api-platform.com/books/02f93821-b174-4b1e-9156-91c9e71e36ba.jsonld'), will the structured data work?
Is calling a URL a problem?

Or I have to create script and fill in the values manually ? :
```javascript
<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Organization",
  "url": "http://www.example.com",
  "name": "Unlimited Ball Bearings Corp.",
  "contactPoint": {
    "@type": "ContactPoint",
    "telephone": "+1-401-555-1212",
    "contactType": "Customer service"
  }
}
</script>
```

Thanks :)

**Comment by dunglas** [comment]
You can just inject the result of your API in a the DOM (in a `<script type="application/ld+json">` element). Google will be able to parse it. Using a framework with SSR support (such as NextJS) will improve the SEO.
