### ISSUE TITLE
An error occurred while executing

### ISSUE THREAD

**Issue by henno** [api-platform/api-platform#126]
Steps to reproduce the problem
1. Go to [tutorial](https://api-platform.com/doc/1.0/getting-started/api).
2. Open Terminal and issue the first command in the tutorial `create-project api-platform/api-platform blog-api`

Expected result:
I get back the prompt without any errors

What happens instead:
<img width="906" alt="screen shot 2016-09-01 at 22 43 51" src="https://cloud.githubusercontent.com/assets/92807/18182091/0ffdab52-7097-11e6-90e9-5fc06e699548.png">

Googling the error message yields this solution: http://stackoverflow.com/a/14953911/584750 but implementing it does not work:

<img width="906" alt="screen shot 2016-09-01 at 22 59 27" src="https://cloud.githubusercontent.com/assets/92807/18182238/c65407b6-7097-11e6-83f7-9f81234b6662.png">

**Comment by henno** [comment]
Referred page  [https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors](https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors) talks about getting Xdebug commented out in `php.ini` but in my case I did not find `xdebug` from `php -i | grep -i xdebug`

Since my loaded `php.ini` had `memory_limit=128MB` and not `1073741824` (1G) as in the error message, it got me thinking that maybe composer uses some other php.ini. Injecting printing out used php ini path to composer yielded information that composer did not use any php ini at all. My composer is installed globally and I have an alias named `php` in my ~/.bash_profile, linking it to my MAMP's version of php (7.0.8). I thought maybe composer does not use this alias and uses some other version of php, so I downloaded composer.phar and ran it as `blog-api henno$ php composer.phar update` and got green :)

<img width="997" alt="screen shot 2016-09-01 at 23 24 55" src="https://cloud.githubusercontent.com/assets/92807/18183054/50b0c68a-709b-11e6-918a-63b257c0e44d.png">

**Comment by henno** [comment]
Nevertheless it would be appropriate to do something about this issue. Not every newbie would have been able to solve this issue.

**Comment by Simperfit** [comment]
@henno This is not directly related to api-platform but either to composer.

What would you suggest to do ?

a Know issue part ?

**Comment by Simperfit** [comment]
Please create an issue on the docs repository if you want to add a know issue part
