### ISSUE TITLE
Custom item operation & @id 

### ISSUE THREAD

**Issue by ehibes** [api-platform/api-platform#1262]
Hi,

I'm trying to create a new item operation to get an entity by its property (instead of its id).
So I made a new controller and its route : 
```
    /**
     * @Route(
     *     name="api_challenger_phone",
     *     path="/api/challengers/phone/{id}",
     *     requirements={"id"=".+"},
     *     methods={"GET"},
     *     defaults={
     *         "_api_resource_class"=Challenger::class,
     *         "_api_item_operation_name"="challenger_phone"
     *     }
     * )
     */
    public function __invoke(Challenger $data): Challenger
    {
        return $data;
    }
```
Two problems here : 
First, the id of challenger entity is now "@id": "/api/challengers/phone/1" instead of "/api/challengers/1".
Then, if my phone number starts with a 0, the number is transformed to an int so the first 0 is removed. I made a hack on my dataProvider but I think it's not the best solution.

```
    public function getItem(string $resourceClass, $id, string $operationName = null, array $context = [])
    {
        if ('challenger_phone' === $operationName) {
            // String is transform to int...
            return $this->repository->findOneByPhone($this->requestStack->getCurrentRequest()->get('id'));
        }

        return $this->repository->find($id); // Retrieves User normally for other actions
    }
```
Is there a better solution to solve my use case ?

Thanks in advance

**Comment by soyuka** [comment]
this could be of some interest: https://github.com/api-platform/core/pull/2126
