### ISSUE TITLE
Upgrade client/ and admin/ to react-scripts 3

### ISSUE THREAD

**Issue by dunglas** [api-platform/api-platform#1263]
A new version of Create React App is there.

**Comment by deepansh946** [comment]
@dunglas I would like to work on this issue.

**Comment by aviral243** [comment]
I've upgraded both to react-scripts 3. It shows certain warnings about react version being incorrect. Were they always present? The solution would require degrading react to 16.4.

**Comment by dunglas** [comment]
They were, it's "intended".

**Comment by umar2323** [comment]
good

**Comment by dsuarezlogans** [comment]
Hello! is this issue still? can I work on it?

**Comment by umar2323** [comment]
thank you sir I am a student from Indonesia who wants to learn from you as a senior programmer, thank you

**Comment by umar2323** [comment]
thanks
 sir

Pada tanggal Rab, 2 Okt 2019 pukul 05.30 Danny Suarez <
notifications@github.com> menulis:
