### ISSUE TITLE
Non existent service dependency after upgrade to 2.5

### ISSUE THREAD

**Issue by reypm** [api-platform/api-platform#1265]
I have upgrade to the new 2.5 release and I am running into the following issue:

```
Executing script php bin/console cache:clear [KO]
 [KO]
Script php bin/console cache:clear returned with error code 1
!!
!!  In CheckExceptionOnInvalidReferenceBehaviorPass.php line 86:
!!
!!    The service "api_platform.graphql.fields_builder" has a dependency on a non
!!    -existent service "api_platform.security.resource_access_checker".
!!
!!
!!
Script @auto-scripts was called via post-update-cmd
```
Not sure if now I have a bundle dependency or I am missing a configuration though (if I am then is not in the docs https://api-platform.com/docs/core/graphql/)

**Comment by alanpoulain** [comment]
Could you try to remove the cache? Because the service should exist.

**Comment by reypm** [comment]
@alanpoulain I did it ... twice before post this and by removing I mean `rm -rf var/` but still not working not sure if I am missing a configuration or a package

**Comment by soyuka** [comment]
https://github.com/api-platform/core/issues/3115 related?

**Comment by teohhanhui** [comment]
> api-platform/core#3115 related?

No...

**Comment by teohhanhui** [comment]
But it seems like a bug:

It's normal that the `api_platform.security.resource_access_checker` service might not exist, if `SecurityBundle` is not installed:

https://github.com/api-platform/core/blob/81d276c33c871ee45605222d474181a503cdf1bd/src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php#L601-L603

So, we need to add `on-invalid="ignore"` here:

https://github.com/api-platform/core/blob/81d276c33c871ee45605222d474181a503cdf1bd/src/Bridge/Symfony/Bundle/Resources/config/graphql.xml#L56

and here:

https://github.com/api-platform/core/blob/81d276c33c871ee45605222d474181a503cdf1bd/src/Bridge/Symfony/Bundle/Resources/config/graphql.xml#L61

**Comment by rperezmira** [comment]
@teohhanhui let me see if I can get some free time and make a little fix for this :) no promises though

**Comment by reypm** [comment]
@teohhanhui let me see if I can get some free time and make a little fix for this :)

**Comment by reypm** [comment]
@alanpoulain this can be closed now, right?
