### ISSUE TITLE
Why is the Person Entity called "people" on API Endpoint?

### ISSUE THREAD

**Issue by fxkopp** [api-platform/api-platform#127]
Hi!

Sorry for asking, but why is the Person Entity out of the Demo application called "/people" in the Rest Endpoint?

Made a search over all the files but can't find anything defining Person as People 🤔

Thank you very much!

Best. Felix.

**Comment by dunglas** [comment]
It uses the Doctrine Inflector library to do so: https://github.com/doctrine/inflector

**Comment by fxkopp** [comment]
Good too know. Thank you very much 👍
