### ISSUE TITLE
how to limit the number of fields to retrieve according to the request (collection or item)

### ISSUE THREAD

**Issue by johan-Rm** [api-platform/api-platform#1274]
I would like to know if it is possible on API Platform to **limit the number of fields (properties of the entity) according to the query request (collection or item)**

for this request "/ api / accommodations" I would like **all the fields**
and for this request "/ api / accommodations / 1" I would like **only 3 fields** (title, image, url)

thanks in advance

**Comment by maxhelias** [comment]
Of course, you can play with the Symfony Serializer groups to get this result.
Take a look at this https://api-platform.com/docs/core/serialization/#using-serialization-groups-per-operation 😉

**Comment by johan-Rm** [comment]
thank you very much I passed by in the documentation with my average English: D
