### ISSUE TITLE
Performances in "prod" are >2 times worse than in "dev"

### ISSUE THREAD

**Issue by krismas** [api-platform/api-platform#1279]
We use api-platform 2.4.5 with docker (PHP 7.2, APCu 5.1.2) and we are experiencing an unusual behaviour on some of our requests. The performances in "prod" are >2 times worse than in "dev". After some tests via blackfire, it turns out that APCu seems to be involved (ie apcu_fetch() cost is more 30%) and indeed by disabling it (apc.enabled = 0), the performances in "prod" are better although still lower than those in "dev" !? Do you have any idea what can caused this problem?

**Comment by soyuka** [comment]
Please follow https://github.com/api-platform/core/issues/2593. 

Would you be able to use some other cache then APCu? If you could give us the source of apcu calls maybe that I could give you more leads.

**Comment by teohhanhui** [comment]
Hi, I think you'd need to provide more details. It's an unusual claim to say that performance in `prod` is worse than in `dev`.

Are you using our Docker setup?

**Comment by krismas** [comment]
We use a Docker configuration from 2.1.6 (varnish, nginx, php, mysql). Our "request" use `pagination=false` mode and returns 240 "members". With APCu the processing time is about 2x longer than without APCu. In our context `apcu_fetch()` is invoked 23269 times :

![Capture d’écran 2019-10-13 à 22 28 18](https://user-images.githubusercontent.com/1462821/66722029-4918f700-ee09-11e9-8467-89d6fc19633c.png)

**Comment by teohhanhui** [comment]
Correct me if I'm wrong, but it sounds like your items have more embedded relations that causes this combinatorial explosion? I'm not sure that's a good idea...

Anyway, it sounds like you'd benefit from https://github.com/symfony/symfony/blob/v4.3.5/src/Symfony/Component/PropertyInfo/PropertyInfoCacheExtractor.php (If you're not already on Symfony 4.3)
