### ISSUE TITLE
Make default referenceType configurable

### ISSUE THREAD

**Issue by maechler** [api-platform/api-platform#128]
The parameter "referenceType" is used in various parts of the framework and its default is always UrlGeneratorInterface::ABS_PATH. We feel like that absolute URLs are more user friendly because they allow for an easy API browsing. We also think that absolute URLs are more aligned with the Hydra concepts and Linked Data in general. 

Do you think there is the possibility to change the default to UrlGeneratorInterface::ABS_URL? Or maybe make the default easily configurable?

At the moment we would have to decorate or copy paste a lot of code to get the desired output.

Thanks already in advance!

**Comment by dunglas** [comment]
I would be to add an option to configure the default.

Using paths instead of URLs have some advantages too:

* It's easier to deal with path than full URLs client side (and especially when using not intended to deal with hypermedia APIs like Restangular or ng-admin).
* It reduces the size of responses (performances)
* It's easier to read for developers (especially those not used to hypermedia APIs).

Adding a config flag can be done easily in the Configuration class.

**Comment by maechler** [comment]
And how would you implement this? 
Add a constant UrlGeneratorInterface::CONFIG = -1 and change the interface and all the method calls to default to CONFIG. And then pass the configuration to your router and set the reference type to the value in the configuration if necessary?

**Comment by maechler** [comment]
I have just created a pull request, if you had something different in mind, please let me know.
I am also not quite sure about the naming of the configuration.

https://github.com/api-platform/core/pull/751

**Comment by teohhanhui** [comment]
I suggest we do this instead: https://www.w3.org/TR/json-ld/#base-iri

This should also allow us to remove the path prefix (e.g. `/app_dev.php` or `/api/app_dev.php`) from the IRI. Much more cleaner and portable.

**Comment by teohhanhui** [comment]
And the wording in the JSON-LD spec seems to suggest that absolute URLs are undesirable. Of course, we should still allow to change that via configuration.

**Comment by teohhanhui** [comment]
> remove the path prefix (e.g. /app_dev.php or /api/app_dev.php) from the IRI

I'm not sure how (cleanly) doable this is with Symfony.

**Comment by Simperfit** [comment]
app_dev does not exist anymore with flex, is this still something ?

**Comment by maechler** [comment]
Moved to https://github.com/api-platform/core/pull/2708
