### ISSUE TITLE
Force the serializer to dump empty JSON object instead of array for empty arrays

### ISSUE THREAD

**Issue by s1k3s** [api-platform/api-platform#1280]
When serializing an array, the serializer behaves as follows:

- if the array is numerically indexed (0, 1, 2... etc), it's converted in a JSON array
- if the array uses strings as keys ('a' => .., 'b' =>... etc), it's converted in a JSON object
- if the array is empty, it's converted in a (empty) JSON array.

This issue has already been reported and fixed in https://github.com/symfony/symfony/pull/28363. However it will only come with the next Symfony release.

Is there any way to fix this in my project, until the next SF & Api-platform version is released?

**Comment by soyuka** [comment]
you should bump the serializer component on your project, mb that overriding the json encoder could also work
