### ISSUE TITLE
react-scripts start after docker compose up

### ISSUE THREAD

**Issue by vasilvestre** [api-platform/api-platform#1285]
After a fresh fork of the repository then a docker-compose up -d
```
yarn run v1.12.3
react-scripts start
/bin/sh: react-scripts: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by dunglas** [comment]
It looks like #1268 doesn't work properly. Could you take a look @dsuarezlogans?

**Comment by FabienSalles** [comment]
I had the same error but after rebuild my containers, everything went back to normal :

```
docker-compose build admin
docker-compose build client
docker-compose up
```

**Comment by soyuka** [comment]
thanks @FabienSalles let us know if this issue is persistent.

**Comment by hernandezrivera** [comment]
Same problem here on Windows 10 and using Docker for Windows.

**Comment by raphael-gauthier** [comment]
I confirm the problem still persists (using Docker for Windows on W10 too).

Same errors on both client and admin containers (even after a rebuild).

> yarn run v1.21.1
> $ react-scripts start
> /bin/sh: react-scripts: not found
> error Command failed with exit code 127.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by vasilvestre** [comment]
I also confirm that on Windows and Linux it didn't work two weeks ago

**Comment by link365dev** [comment]
What was the solution?

**Comment by Brewal** [comment]
Same issue on fresh v2.5.5 on W10 with the client container. Fixed by running `docker-compose build client` once after the first `docker-compose up -d`

**Comment by chandanpuggal** [comment]
I am still getting this error while running it on kube cluster 
`yarn run v1.22.10
$ react-scripts start
/bin/sh: react-scripts: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`
