### ISSUE TITLE
http://cache-proxy still present in api/.env

### ISSUE THREAD

**Issue by abeal-hottomali** [api-platform/api-platform#1294]
Hi all, hopefully quick question: Current Master branch `api/.env` lists the `VARNISH_URL` value as being [equal to `http://cache-proxy`](https://github.com/api-platform/api-platform/blob/master/api/.env), but it looks like that service [was removed](https://github.com/api-platform/api-platform/blob/master/docker-compose.yml).  Is this a bug?  What value should this be for local development?  Leave blank?

**Comment by dunglas** [comment]
Hi! It's intended, the service hasn't been removed but moved: https://api-platform.com/docs/deployment/docker-compose/#installing-the-docker-compose-setup-for-production

**Comment by abeal-hottomali** [comment]
Closing issue, as it's not a bug.
