### ISSUE TITLE
Warning "<link rel=preload> must have a valid `as` value"

### ISSUE THREAD

**Issue by jorgeluisacostaalonso** [api-platform/api-platform#1303]
Hello, 

I've entities Book and Review copied from Api-Platform example

I've configured the relationship "reviews" from Book as 

 /**
     * @var Review[] Available reviews for this book.
     * @ApiProperty(push=true)
     * @ORM\OneToMany(targetEntity="Review", mappedBy="book", cascade={"persist", "remove"})
     */
    public $reviews;

And in the client side I got \<link rel=preload> must have a valid `as` value. And Proxy doesn't PUSH the resource "/rewiews/xxxx"

 having this below in the h2-proxy

    listen 8443 ssl http2;
    listen [::]:8443 ssl http2;
    
    ssl_certificate /etc/nginx/ssl/cert.crt;
    ssl_certificate_key /etc/nginx/ssl/cert.key;
   
    location / {
        proxy_pass http://api;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Port 8443;
        http2_push_preload on; <= New line
    }

We should add another configuration to h2-proxy or it's something to add to @ApiProperty ?

**Comment by electricBonfire** [comment]
I am having the same issue

**Comment by dunglas** [comment]
Fixed in the version I just tagged!
