### ISSUE TITLE
@UniqueEntity for "email" doesn't work

### ISSUE THREAD

**Issue by tomasyhy** [api-platform/api-platform#1306]
**API Platform version(s) affected**: 2.5.0

**Description**  
I created User entity which implements Symfony\Component\Security\Core\User\UserInterface.
@UniqueEntity doesn't work for field "email". For other fields working correctly.

Entity:

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Lexik\Bundle\JWTAuthenticationBundle\Security\User\JWTUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use ApiPlatform\Core\Annotation\ApiResource;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use App\Validator\Constraints\DuplicateUser;

/**
 * @ApiResource(collectionOperations={
 *     "get",
 *     "register"={
 *         "method"="POST",
 *         "path"="/auth/register",
 *         "controller"=App\Controller\Register::class,
 *     }
 * })
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @UniqueEntity("email")
 * @ORM\Table(name="user_account")
 */
class User implements UserInterface
{
    const ROLE_USER = 'ROLE_USER';
    const ROLE_ADMIN = 'ROLE_ADMIN';

    /**
     * Hook timestampable behavior
     * updates createdAt, updatedAt fields
     */
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50, unique=true)
     * @Assert\Email
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=15)
     * @Assert\NotBlank()
     * @Assert\NotNull()
     * @Assert\Length(
     *      min = 2,
     *      max = 14
     * )
     */
    private $name;
...

Scenaroius:
1. POST with existing email: {
    "email": "email@gmail.com",
    "password": "password",
    "name": "name",
    "surname": "surname"
}
Result:
HTTP 500
hydra:description: "An exception occurred while executing 'INSERT INTO user_account ... key value violates unique constraint \"uniq_253b48aee7927c74\"\nDETAIL:  Key (email)=(email@gmail.com) already exists.

2. Set @UniqueEntity("name"), POST with existing name:
{
    "email": "email@gmail.com",
    "password": "password",
    "name": "name",
    "surname": "surname"
}
Result:
HTTP 400
"hydra:description": "name: This value is already used."

**Comment by dunglas** [comment]
It looks related to the Symfony Serializer, not to API Platform directly.

**Comment by hous04** [comment]
Hi
I have the same error, did you found a solution ?

**Comment by hous04** [comment]
Hi
I have the same error, did you found a solution ?

**Comment by tomasyhy** [comment]
In my case problem wasn't related with "UniqueEntity" validator but with saving entity logic. My entity was saving two times, so for the second save attempt, symfony returns exception.

**Comment by hous04** [comment]
And in my case it was related to validation groups
