### ISSUE TITLE
Error while reading the API schema

### ISSUE THREAD

**Issue by msmaromi** [api-platform/api-platform#1307]
**API Platform version(s) affected**: 
2.5.0

**Description**  

I ran api platform using `docker-compose`. It works perfectly except for admin, which display this text `Error while reading the API schema`.

**How to reproduce**  

1. Run `docker-compose up -d`
2. Open admin `http://localhost:81`

**Comment by levansonqs** [comment]
Enter this code to the chrome search box.
`chrome://flags/#allow-insecure-localhost`
enable this flag

![image](https://user-images.githubusercontent.com/11365381/68265320-4747f980-007e-11ea-8d01-68ef252c67f3.png)
Hope this help!

**Comment by msmaromi** [comment]
Btw I able to make it works by changed the `@api-platform/admin` to version `1.0.1`. Make sure to rebuild the image without cache.
