### ISSUE TITLE
Compatibility issue when using composer require with symfony 3.1.4

### ISSUE THREAD

**Issue by rudidev08** [api-platform/api-platform#131]
With latest (3.1.4) vanilla symfony, if i use

`composer require dunglas/api-bundle`

(from https://api-platform.com/doc/1.0/api-bundle/getting-started)

I get the following errors:

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - dunglas/api-bundle v1.1.0 requires phpdocumentor/reflection ^1.0.7 -> satisfiable by phpdocumentor/reflection[1.0.7].
    - Installation request for dunglas/api-bundle ^1.1 -> satisfiable by dunglas/api-bundle[v1.1.0].
    - Conclusion: remove symfony/symfony v3.1.4
    - Conclusion: don't install symfony/symfony v3.1.4
    - phpdocumentor/reflection 1.0.7 requires phpdocumentor/reflection-docblock ~2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
    - phpdocumentor/reflection-docblock 2.0.0 conflicts with symfony/symfony[v3.1.4].
    - phpdocumentor/reflection-docblock 2.0.1 conflicts with symfony/symfony[v3.1.4].
    - phpdocumentor/reflection-docblock 2.0.2 conflicts with symfony/symfony[v3.1.4].
    - phpdocumentor/reflection-docblock 2.0.3 conflicts with symfony/symfony[v3.1.4].
    - phpdocumentor/reflection-docblock 2.0.4 conflicts with symfony/symfony[v3.1.4].
    - Installation request for symfony/symfony (locked at v3.1.4, required as 3.1.*) -> satisfiable by symfony/symfony[v3.1.4].


Installation failed, reverting ./composer.json to its original content.
```

I've tried removing symfony from requirements, but no luck. In composer.json, symfony/symfony version is set to 3.1.*, which sounds like it should work based on last message. What am I missing?

**Comment by teohhanhui** [comment]
You should use API Platform v2 :smile:

**Comment by rudidev08** [comment]
Success! Documenting steps below in case someone else needs them.

Using docs at:

`https://github.com/api-platform/docs/blob/master/core/getting-started.md#installing-api-platform-core`

I've called this after installing latest symfony (3.1.4)

`composer require api-platform/core`

```
Using version ^1.1 for api-platform/core

  Problem 1
    - api-platform/core v1.1.0 requires phpdocumentor/reflection ^1.0.7 -> satisfiable by phpdocumentor/reflection[1.0.7].
    - api-platform/core v1.1.1 requires phpdocumentor/reflection ^1.0.7 -> satisfiable by phpdocumentor/reflection[1.0.7].
    - Conclusion: don't install phpdocumentor/reflection 1.0.7
    - Installation request for api-platform/core ^1.1 -> satisfiable by api-platform/core[v1.1.0, v1.1.1].
```

Next i've tried to request ^2.0

`composer require api-platform/core ^2.0`

```
  Problem 1
    - The requested package api-platform/core 2.* is satisfiable by api-platform/core[2.0.x-dev, v2.0.0-alpha.1, v2.0.0-alpha.2, v2.0.0-beta.1, v2.0.0-beta.2, v2.0.0-beta.3] but these conflict with your requirements or minimum-stability.
```

Finally adding this to composer.json fixed it:

`"minimum-stability": "beta"`

Note that since I'm using MAMP with OS X, i've also needed to install PHP 7 from http://php-osx.liip.ch and set default path to it in .bash_profile, otherwise composer will complain that PHP 7 is not present.

**Comment by teohhanhui** [comment]
`composer require api-platform/core:^2.0.0@beta`

Also see #119

**Comment by martijn80** [comment]
I managed to workaround the PHP 7 requirement with  
composer require api-platform/core ^2.0 --ignore-platform-reqs

And installing 
composer require symfony/polyfill-php70

**Comment by teohhanhui** [comment]
@martijn80 There is simply no working around the PHP 7 requirement. We use PHP 7 language features in the API Platform code. No amount of polyfill can change that. But I think you already know, because you'd have run into errors soon enough...
