### ISSUE TITLE
Query parameter validation not running

### ISSUE THREAD

**Issue by ghostika** [api-platform/api-platform#1314]
I'm not sure if this is a feature or a bug. 

In the `QueryParameterValidateListener` there is a check against the `collection_operation_name` value and it always has to be `get`. I have a custom `get` operation with a custom name and the base `get` operation with the `get` name for the same entity and I have a defined filter with a required query parameter.
If I call the base `get` url, the validation kicks in and notifies me of the missing parameter but for the custom `get` operation it doesn't.

**Comment by winzza** [comment]
https://stackoverflow.com/questions/59533789/validation-in-custom-operation-controller

Maybe this will help you?

**Comment by ghostika** [comment]
Nope sadly, it has nothing to do with input validation in that sense. If you have like a `user_id` filter than in a normal get operation you specify that it is required and if it's a get request and is not set, then a 400 error response is returned automatically, but if I use the same filter for a custom named get operation, the validation doesn't.

**Comment by ghostika** [comment]
Oh, actually I see that this was added in this commit:

https://github.com/api-platform/core/commit/3ec427e85ccaeff23aca620335bdd0b7c5da3ded#diff-8ca4abfe354f5592ea6b86ce6f94726f

Perfect, then I can close this issue!
