### ISSUE TITLE
[MERCURE] Add a way to have a public mercure url and a private

### ISSUE THREAD

**Issue by Richard87** [api-platform/api-platform#1315]
**Description**  
Hi! Thanks for this awesome component btw!

I need to have a private Mercure Hub URL for use in Kubernetes and Docker-Compose... For example, on kubernetes, the public url is https://mercure.example.com, while the private/internal url is http://mercure.example.svc.default-cluster. 

In development, in docker-compose, I have a public url http://localhost:8088 and a private url http://mercure.

**Example**  
- To solve the issue, I tried to modify the messenger bus, and have a new `Update` handler, but mercure's own Publisher always cought the event and the event was sent twice...
- I tried to decorate the Publisher server, but since it's final that failed...
- I tried to create a factory service to create the Publisher with a custom hub url, but then nothing worked :/ (I probably have to modify the container at build time to override your configuration)
- I tried to add a EventSubscriber to modify the Link header, but since you didn't set `priority` on the `AddLinkHeaderListener` I can't run my listener in between yours and mine LinkHeader handler (atleast before WebLink writes the updates to the headers, and I'm afraid there might be a bug here in the feature since they all run with the same priority 0).

Right now I'm duplicating your code to add the correct mercure link, and serializing the links and setting the correct header, but this feels bad...

I think you (I could send a pull request if wanted!) need to modify a few things:
- Fix priorities for all eventlisteners to make sure there isn't a bug where mercure link is added after _link is serialized and added to the headers
- Make it easier to modify the urls, either remove the `final`property on the `Publisher` class or the `AddLinkHeaderListener` class, or add interfaces so I can decorate them...

Thansk again for the awesome work all of you are doing!! :fire:

**Comment by Richard87** [comment]
My hack to fix it was modifying the container:

```php
class OverridePublisherUrl implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $internalUrl = $container->getParameter("mercure_internal_url");

        $definition = $container->getDefinition('mercure.hub.default.publisher');
        $definition->setArgument(0,$internalUrl);
        $container->setDefinition('mercure.hub.default.publisher', $definition);
    }
}
```

**Comment by Darkweak** [comment]
What's going wrong using http://mercure on the code to dispatch events ?

**Comment by Richard87** [comment]
Its not accessable from the outside of the private network, therefore the Link header in the response is invalid...

**Comment by Darkweak** [comment]
If I understand your problem that's normal, your `MERCURE_SUBSCRIBE_URL` should be a reachable url on the internet and your `MERCURE_PUBLISH_URL` can be on the same network. But if you want to allow to publish on same network (as internal) you should allow PUBLISH_ALLOWED_ORIGINS to accept http://yourservice (worked for me but didn't updated since a while)

**Comment by Richard87** [comment]
No, the problem is the information sent out, everything works when I have the urls

But internally, mercure-bundle publishes it's updates to http://mercure/hub, but then *also* sends this url in the `Link` header... That's wrong since that url is not accessable from the outside, for the client to connect to the hub they need to connect to http://mercure.example.com/hub

Again, the problem is not CORS :) It's about the headers sent out.
Also the problem is not in Mercure Hub, it's in the Api-Platform Mercure integration...

**Comment by Darkweak** [comment]
Oh my bad.. Open a PR with your hack, it could be great to merge it then

**Comment by dunglas** [comment]
We now have a dedicated environment variable for both the public and the private URL to address this use case: https://github.com/api-platform/api-platform/blob/main/api/.env#L19
