### ISSUE TITLE
Difference between POST with @id and PUT

### ISSUE THREAD

**Issue by amenophis** [api-platform/api-platform#132]
Hi,
It seems these 2 request does the same thing:

```POST /companies { "@id": "/companies/123", "name": "My Company" }```
and
```PUT /companies/123 { "name": "My Company" }```

The first request result in a 201 in all case, which is bad for update.
If @id is not found, the error is ```Item not found for \"\/companies\/123\".```

The second request result in 200. Works only wiith @id in url.

Is it the expected result ?

**Comment by teohhanhui** [comment]
`POST` is for creating the resource, and `PUT` for updating it. If you can update with `POST`, or create with `PUT`, that's a bug and we should fix it.

**Comment by amenophis** [comment]
I confirm I can update with `POST.` But can't create with `PUT`

**Comment by soyuka** [comment]
> I confirm I can update with POST

You have `http_method_override: true`?

**Comment by amenophis** [comment]
I use the api-platform disctribution without modifications, so yes !

**Comment by dunglas** [comment]
It's indeed a weird behavior, thanks for reporting it.

We have 2 possible fixes for this case:

* throw an error in this specific case
* ignore the `@id` key and create a new resource

I in favor of the first one

**Comment by teohhanhui** [comment]
Yes, I think it should result in a HTTP 400.
