### ISSUE TITLE
API Resource not expand object property - its a string to resource only

### ISSUE THREAD

**Issue by patrickbussmann** [api-platform/api-platform#1326]
**API Platform version(s) affected**: 2.5.0 / (api-platform/api-pack: 1.2.6)

**Description**  
I have simple entity with two `ManyToMany` entities.
The first one called `Service` is mapped correct.
The second one called `File` and is mapped to a `string`.

How to directly get the field within the main entity?
And not having a second API call?

**How to reproduce**  
https://github.com/patrickbussmann/api-platform-bug-001

But the funny thing is that I cant reproduce it there.

So on my development environment.

You can see the object `service` there expanded.
In the schema it's known as a Service.
![image](https://user-images.githubusercontent.com/15617021/68255064-7b92ca00-002c-11ea-98e2-a88e8b26b66a.png)

And now its the demo repository in the top.
![image](https://user-images.githubusercontent.com/15617021/68255149-c876a080-002c-11ea-9d5a-d4b8d8268a13.png)

There everything is a `string`.
Its an string to the resource like `/api/files/363`.
But its not an object. Its an string (to the object).

This is an example in my local environment when I call:
`/api/greetings/1`
```json
{
    "@context": "/api/contexts/Greeting",
    "@id": "/api/greetings/1",
    "@type": "Greeting",
    "id": 42,
    "service": {
        "@id": "/api/services/1",
        "@type": "Service",
        "id": 1
    },
    "title": "Test",
    "image": "/api/files/1"
}
```

And I expect that the `image` is an expanded object like the `service`.

Thanks in Advance for ideas.

**Comment by fgamess** [comment]
You should define serialization groups (https://api-platform.com/docs/core/serialization/).
In your case, define serialization groups inside `normalizationContext` on your Resource. Then add the serialization group to the `image` property located inside your `Service` resource. Then inside your `File` resource add the same serialization group on the fields you need. In the json response, it will display `image` body instead of the IRI.

**Comment by teohhanhui** [comment]
Please use the proper channels for support questions. Thanks!
