### ISSUE TITLE
graphql pagination last/before/startCursor not enabled

### ISSUE THREAD

**Issue by BernardA** [api-platform/api-platform#1327]
**API Platform version(s) affected**: `"api-platform/api-pack": "^1.2",`

**Description**  
Pagination with `first/after` works but `last/before` throws error.
This is a simple pagination with `previous/current/next` pages. 
The `NEXT` query equivalent to one provided below works, while the query with  `last/before` throws error:

`"Unknown argument \"last\" on field \"ads\" of type \"Query\"."`

Also attempting to ask for the field `startCursor` in the `first/after` query will throw error.

Additionally, the `last/before/startCursor` combination is not available on `graphiql`. 

**How to reproduce**  

This is the query:

      const queryQl = `query($last: Int, $before: String){
        ads(last: $last, before: $before) {
            totalCount
            pageInfo {
                endCursor
                hasNextPage
            }
            edges {
                cursor
                node {
                    id
                    _id
                    description
                    user {
                        id
                        username
                        image{
                            filename
                        }
                        address{
                            city
                        }
                    }
                    category {
                        id
                        title
                        parent{
                            title
                        }
                    }
                    budget
                }
            }
    }}`;
    const variables = {
        last: 10,
        before: action.cursor,
    };

These are the annotation in Ad Entity:

     /**
    * @ORM\Entity(repositoryClass="App\Repository\AdRepository")
     * @ApiFilter(
     *     SearchFilter::class,
     *     properties={
     *         "description": "exact",
     *         "user": "exact",
     *         "user.email": "partial",
     *         "user.address": "exact",
     *         "category": "exact"
    *     }
    * )
     * @ApiFilter(
     *     DateFilter::class,
     *     properties={
    *         "createdAt"
     *     }
    * )
     * @ApiFilter(RangeFilter::class, properties={"createdAt"})
     * @ApiFilter(
     *     OrderFilter::class,
    *     properties={
    *         "createdAt",
    *     },
     *     arguments={"orderParameterName"="_order"}
     * )
     * @ApiFilter(PropertyFilter::class, arguments={
     *     "parameterName": "properties",
     *     "overrideDefaultProperties": false,
     *     "whitelist": {"id", "rentTime", "description", "user", "category"}
     * })
    * @ApiResource(
     *      attributes={
     *         "order"={"createdAt": "DESC"},
     *         "pagination_via_cursor"={"field"="createdAt", "direction"="DESC"}
    *      },
    *      itemOperations={
     *         "get"={
     *             "normalization_context"={
     *                 "groups"={"get-ad-with-user"}
    *             }
    *          },
    *          "put"={
     *              "access_control"="is_granted('ROLE_USER') or (is_granted('ROLE_EDITOR') and object.getUser() == user)"
     *          },
     *          "put-user-to-ad"={
     *              "access_control"="is_granted('ROLE_USER') and object.getUser() == user",
     *              "method"="PUT",
     *              "path"="/ads/{id}/put-user",
     *          }
     *      },
     *      collectionOperations={
     *          "get",
     *          "post"={
     *              "access_control"="is_granted('ROLE_USER')"
     *          },
     *          "post-before-signup"={
     *             "method"="POST",
     *             "path"="/ads/unsigned",
     *             "denormalization_context"={
     *                 "groups"={"post-before-signup"}
     *             },
     *             "validation_groups"={"post-before-signup"}
     *          }
     *      },
     *      denormalizationContext={
     *          "groups"={"post"}
     *      }
     * )
     */

**Possible Solution**  

**Additional Context**

**Comment by alanpoulain** [comment]
Which version of API Platform (not `api-pack`) do you use?

**Comment by BernardA** [comment]
Did you mean this one
`api-platform/core                   v2.4.6`

**Comment by alanpoulain** [comment]
Yes. You need API Platform 2.5.0: https://github.com/api-platform/core/releases/tag/v2.5.0.

**Comment by BernardA** [comment]
Thanks, it works now. 
Just a quick question if you allow me: I set this up as  very simple pagination with only previous/next buttons as it seems to me that the ` cursor` pagination does not allow for a more complete pagination where the user can jump to specific pages. Am I correct?

I understand that the REST api would allow that, but I am attempting to stick to `graphql` as much as I can.
Thanks again

**Comment by alanpoulain** [comment]
There is an ongoing PR related to this: https://github.com/api-platform/core/pull/3175

**Comment by BernardA** [comment]
Great, thanks!

**Comment by BernardA** [comment]
I am facing all kind of issues now, which I believe may be related to some mismatch in-between the `"api-platform/api-pack": "^1.2"` and the separately installed `"api-platform/core": "2.5.0"` as per above. 

When I attempt to reach graphql at `127.0.0.1:8001` it will throw error in console:

     TypeError: document.getElementById(...) is null         init-graphiql.js:49:36
    onload http://127.0.0.1:8001/bundles/apiplatform/init-graphiql.js:49

All my queries from the client side ( Gatsby ) are also failing.

Previously I attempted to install an update to `api-platform/api-pack` but none seems to exist, so I installed `"api-platform/core": "2.5.0"` separately. 

So in my compser.json I now have:

         "api-platform/api-pack": "^1.2",
        "api-platform/core": "2.5.0",

**Comment by BernardA** [comment]
I did manage to access `http://127.0.0.1:8001/api/graphql` only to find out that some of my entities that were marked as resource no longer appear on the `docs` tab as a Connection. 

A query like below, that worked fine before this change now throws error as below:

      query{
                categories {
                    edges {
                        node {
                            id
                            title
                            parent {
                                id
                                title
                            }
                            root {
                                id
                                title
                            }
                        }
                    }
                    totalCount
                }
       }

Error throw: `"Cannot query field \"edges\" on type \"Category\".",`

For the entity Ad, the query below works fine:

                          ads{
                       edges {
                           node {
                               id
                               _id
                               description
                               user {
                                   id
                                   username
                                   image{
                                       filename
                                   }
                                   address{
                                       city
                                   }
                               }
                               category {
                                   id
                                   title
                                   parent{
                                       title
                                   }
                               }
                               budget
                           }
                       }
                       totalCount
                   }

Looking the annotations I could not find what could explain the different behavior. 

This is for the Category entity:

        /**
     * @Gedmo\Tree(type="nested")
     * @ORM\Table(
     *      uniqueConstraints={@ORM\UniqueConstraint(name="partitle", columns={"parent_id", "title"})}
     * )
     * @UniqueEntity(
      *      fields={"title","parent"},
     *      errorPath="title",
     *      repositoryMethod="checkDuplicateTitle",
     *      message="Sub-category already exists for this category "
     * )
     * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
     * @ApiFilter(
     *     SearchFilter::class,
     *     properties={
     *         "title": "partial",
     *         "root": "exact",
     *         "parent": "exact",
     *     }
     * )
     * @ApiFilter(
     *     OrderFilter::class,
     *     properties={
     *         "parent",
     *         "title",
     *     },
     *     arguments={"orderParameterName"="_order"}
     * )
     * @ApiResource(
     *     attributes={"pagination_enabled"=false},
     *     itemOperations={
     *          "get"={
     *             "normalization_context"={
     *                 "groups"={"get-cats"}
     *             }
     *          },
     *          "put"={
     *              "access_control"="is_granted('ROLE_ADMIN')"
     *          }
     *      },
     *      collectionOperations={
     *          "get",
     *          "post"={
     *              "access_control"="is_granted('ROLE_ADMIN')"
     *          }
     *      },
     *      denormalizationContext={
     *          "groups"={"post"}
     *      }
    * )
    */

For the Ad entity the annotation are on the original post.

In the case of the User entity it simply disappeared from the 'Docs' tab. No Collection nor individual items are available.

**Comment by BernardA** [comment]
Full code at [this repository. ](https://github.com/BernardA/quiamo-api)

**Comment by BernardA** [comment]
I moved this to the a new issue as above.
