### ISSUE TITLE
CORS issue due to upgrade in api-pack

### ISSUE THREAD

**Issue by jspizziri** [api-platform/api-platform#1332]
**API Platform version(s) affected**: 2.5.1

**Description**  
The upgrade of `nelmio/cors-bundle` in the `api-pack` [here](https://github.com/api-platform/api-pack/commit/cab95501cb6f7d1dc1942d5df65d41a51155b755) broke CORS requests.

**How to reproduce**  

```
cd api
composer update
cd ..
docker-compose build api
docker-compose up -d api
```
Then attempt to access a resource via admin, and you'll see a `405` on the `OPTIONS` request.

**Possible Solution**  

Lock down the version of `api-pack` to require a version that depends on `nelmio/cors-bundle:^1.5`.

**Additional Context**  

I ran `composer update` as part of upgrading a `v2.4.5` installation to a `v2.5.1`. I went through [the diff](https://github.com/api-platform/api-platform/compare/v2.4.5..v2.5.1) and couldn't identify any additional configuration that resolved this issue. I resolved the issue locally by forcing lower version of `nelmio/cors-bundle`. Ex:

```
cd api
composer require "nelmio/cors-bundle:^1.5"
cd ..
docker-compose build api
docker-compose up -d api
```

**Comment by jspizziri** [comment]
@dunglas I'd be happy to submit a PR on this if someone told me if you want the version lick in `api-pack` or in `api-platform`.

**Comment by soyuka** [comment]
We fixed that issue normally https://github.com/api-platform/core/pull/3265

**Comment by jspizziri** [comment]
I've confirmed that `api-platform/core >= 2.5.2` and above PR resolves the issue.
