### ISSUE TITLE
API PLATFORM custom identifier in custom action

### ISSUE THREAD

**Issue by AbbesBendaoud10** [api-platform/api-platform#1334]
I want to use custom identifier in a custom action without using {id} like this .
     
      @ApiResource(
         itemOperations={
            "FORGOT-PASSWORD"={
                 "method"="PUT",
                 "path"="/users/{forgotPasswordToken}/forgot-password",
                 "controller"="App\Controller\ForgotPasswordController",
              }
          }
      )

But i still have the same error with "Invalid identifier value or configuration" .

Any issue please ?

**Comment by rached-bch** [comment]
Have you tried to set ApiProprety annotations to correct fields ? see example below : 

```
/**
 * @ORM\Id()
 * @ORM\GeneratedValue()
 * @ORM\Column(type="integer")
 * @ApiProperty(identifier=false)
 */
private $id;

```
```
/**
 * @ORM\Column(type="string", length=120)
 * @ApiProperty(identifier=true)
 */
private $forgotPasswordToken;
```

**Comment by soyuka** [comment]
This feature is not available in api platform, I've made a proposal in https://github.com/api-platform/core/pull/2126 but it's not merged yet.

**Comment by AbbesBendaoud10** [comment]
Ok thank you, @soyuka  waiting for it ...

**Comment by andrei115** [comment]
> Have you tried to set ApiProprety annotations to correct fields ? see example below :
> 
> ```
> /**
>  * @ORM\Id()
>  * @ORM\GeneratedValue()
>  * @ORM\Column(type="integer")
>  * @ApiProperty(identifier=false)
>  */
> private $id;
> ```
> 
> ```
> /**
>  * @ORM\Column(type="string", length=120)
>  * @ApiProperty(identifier=true)
>  */
> private $forgotPasswordToken;
> ```

This really helped me. Besides setting  @ApiProperty(identifier=true) on the desired field, it is also important to set  * @ApiProperty(identifier=false) to the id field
