### ISSUE TITLE
GraphQL pagination

### ISSUE THREAD

**Issue by KingAdapting** [api-platform/api-platform#1339]
Hi guys! I face with problem using GraphQL pagination in Api Platform.
I have a query like this:
```
query getItems($first: Int, $last: Int, $after: String, $before: String) {
        items(first: $first, last: $last, before: $before, after: $after) {
            totalCount
            edges {
                node {
                    _id
                    message
                    user {
                        firstName
                        lastName
                    }
                }
            }
            pageInfo {
                endCursor
                hasNextPage
                hasPreviousPage
            }
        }
    }
```
This example has 60 items, but after 40 hasNextPage returns false and my pagination seems not to work anymore.
Example
```
"endCursor": "Mzk=",
 "hasNextPage": false,
 "hasPreviousPage": true
```
And if I try to use endCursor to get next page - it works and I receive next items, but hasNextPage = false.
Thanks for help!

**Comment by alanpoulain** [comment]
Which version of API Platform are you using?

**Comment by KingAdapting** [comment]
> Which version of API Platform are you using?

v2.5.0

**Comment by alanpoulain** [comment]
It's tricky. Could you add this dump in `vendor/api-platform/core/src/GraphQl/Resolver/Stage/SerializeStage.php` in `serializeCursorBasedPaginatedCollection` and before `$data['pageInfo']['hasNextPage']...`:
```php
dump($offset, $collection->getItemsPerPage(), $collection->getCurrentPage(), $totalItems);
```

**Comment by KingAdapting** [comment]
> It's tricky. Could you add this dump in `vendor/api-platform/core/src/GraphQl/Resolver/Stage/SerializeStage.php` in `serializeCursorBasedPaginatedCollection` and before `$data['pageInfo']['hasNextPage']...`:
> 
> ```
> dump($offset, $collection->getItemsPerPage(), $collection->getCurrentPage(), $totalItems);
> ```

<img width="622" alt="Снимок экрана 2019-11-21 в 13 15 55" src="https://user-images.githubusercontent.com/45668301/69333355-275d2c00-0c61-11ea-8c5f-c05735617983.png">

**Comment by alanpoulain** [comment]
Could you try this change within your code https://github.com/api-platform/core/pull/3281?
It should solve the issue.

**Comment by KingAdapting** [comment]
> Could you try this change within your code [api-platform/core#3281](https://github.com/api-platform/core/pull/3281)?
> It should solve the issue.

**Comment by alanpoulain** [comment]
You should wait for the next minor version to update to solve this then.
