### ISSUE TITLE
Optionally remove google fonts dependency 

### ISSUE THREAD

**Issue by jvigneron** [api-platform/api-platform#1346]
**Description**  
Remove any google fonts dependency from api-platform.

**Example**  
Remove the google font stylesheet in line 8 of _api-platform\core\src\Bridge\Symfony\Bundle\Resources\views\SwaggerUi\index.html.twig_ depending on a configuration variable?

**Context**
I'm working on an intranet application for a big company where any call to the fonts.googleapi.com CDN takes 30 seconds to respond.

**Comment by dunglas** [comment]
Anyway I would like to remove the dependency Google's server. Maybe can we embed the font in the distribution? cc @ginifizz

**Comment by shivambhatia5432** [comment]
Is this issue still open?

**Comment by dunglas** [comment]
Yes it is

**Comment by tripleee** [comment]
This is prominently displayed on https://github.com/topics/hacktoberfest and the sloppy typing isn't exactly reflecting well on this project. Somebody with the privileges please edit the ticket into shape?

**Comment by jvigneron** [comment]
> 
> 
> This is prominently displayed on https://github.com/topics/hacktoberfest and the sloppy typing isn't exactly reflecting well on this project. Somebody with the privileges please edit the ticket into shape?

Well, I tried to make it less 'sloppy' but the ticket seems to be cached on https://github.com/topics/hacktoberfest ...

**Comment by tripleee** [comment]
"Optionaly" in the title is still misspelled. Thanks for fixing; I'm sure it will eventually be updated on the roster page too.

**Comment by rahil1304** [comment]
Hey, I'd like to work on this issue if nobody has already taken it up?

**Comment by jpic** [comment]
Would it be acceptable to use that module? 

https://github.com/beyonk-adventures/google-fonts-webpack-plugin#usage

**Comment by dunglas** [comment]
It's not necessary. This issue has been fixed now.
