### ISSUE TITLE
Using GraphQL file url is always null

### ISSUE THREAD

**Issue by laurinium** [api-platform/api-platform#1347]
**API Platform version(s) affected**: 2.5.3

**Description**  
I'm uploading files, via GraphQL multipart request spec like in https://api-platform.com/docs/core/graphql/#handling-file-upload. The file is uploading just fine and correct database entry is made. But the URL in the response is always null. 

I've debugged a bit and the ResolveMediaObjectContentUrlSubscriber is never called when using GraphQL. 

**How to reproduce**  
Create a File Entity class like this:
```php 
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiProperty;
use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Serializer\Annotation\Groups;
use Vich\UploaderBundle\Mapping\Annotation\Uploadable;
use Vich\UploaderBundle\Mapping\Annotation\UploadableField;
use Symfony\Component\Validator\Constraints as Assert;
use App\Resolver\CreateMediaObjectResolver;
/**
 * @ApiResource(
 * normalizationContext={
 *      "groups"={"list","one"},
 *     },
 * graphql={
 *     "collection_query",
 *     "item_query",
 *     "update",
 *     "delete",
 *      "upload"={
 *             "mutation"=CreateMediaObjectResolver::class,
 *             "deserialize"=false,
 *             "args"={
 *                 "file"={"type"="Upload!", "description"="The file to upload"}
 *             }
 *         }
 *     }
 * )
 * @Uploadable
 * @ORM\Entity(repositoryClass="App\Repository\FileRepository")
 */
class File
{
    /**
     * @ORM\Id()
     * @Groups({"list","one"})
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;


    /**
     * @Groups({"list","one"})
     * @ORM\Column(name="file_key",type="string", length=255)
     */
    private $fileKey;

    /**
     * @var string|null
     * @ApiProperty(iri="http://schema.org/contentUrl")
     * @Groups({"list","one"})
     */
    public $url;

    /**
     * @var UploadedFile|null
     *
     * @Assert\NotNull()
     * @UploadableField(mapping="media_object", fileNameProperty="fileKey")
     */
    public $file;


  
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFileKey(): ?string
    {
        return $this->fileKey;
    }

    public function setFileKey(string $file_key): self
    {
        $this->fileKey = $file_key;

        return $this;
    }
}

 ```

Upload a file:
```bash
curl -X POST https://localhost:8000/graphql
  -F operations='{ "query": "mutation ($file: Upload!) { uploadFile(input: {file:$file}) { file{id url} } }", "variables": { "file": null } }' \
-F map='{ "0": ["variables.file"] }' \
-F 0=@a.txt
```

The result will be:

```json
{"data":{"uploadFile":{"file":{"id":"\/files\/30","url":null}}}}
```

**Comment by alanpoulain** [comment]
It's because the `ResolveMediaObjectContentUrlSubscriber` is for REST, not for GraphQL. You need to set the URL in the `CreateMediaObjectResolver`. Maybe it needs a documentation entry.

**Comment by laurinium** [comment]
Hi @alanpoulain,
thanks for your quick response. 
I totally forgot about the `CreateMediaObjectResolver`. :sweat_smile: 
I've now set the URL in the `CreateMediaObjectResolver` and it works when uploading a file now. 
But not when I try to query with an `item_query` or a`collection_query`. To get the URL in the `item_query` and `collection_query` operations I added 2 custom resolvers, which add the URL when querying.
```php
/**
 * @ApiResource(
 * graphql={
*      "collection_query"={"collection_query"=GetMediaObjectCollectionResolver::class},
 *     "item_query"={"item_query"=GetMediaObjectResolver::class},
 *     "update",
 *     "delete",
 *      "upload"={
 *             "mutation"=CreateMediaObjectResolver::class,
 *             "deserialize"=false,
 *             "args"={
 *                 "file"={"type"="Upload!", "description"="The file to upload"},
 *
 *             }
 *         }
 *     }
 * )
 * @Uploadable
 * @ORM\Entity(repositoryClass="App\Repository\FileRepository")
 */
class File
{
...
```
```php
<?php

namespace App\Resolver;

use ApiPlatform\Core\GraphQl\Resolver\QueryCollectionResolverInterface;
use App\Entity\File;
use Vich\UploaderBundle\Storage\StorageInterface;

final class GetMediaObjectCollectionResolver implements QueryCollectionResolverInterface
{

    /**
     * @var StorageInterface
     */
    private $storage;

    public function __construct(StorageInterface $storage)
    {

        $this->storage = $storage;
    }

    /**
     * @param iterable<File> $collection
     * @param array $context
     * @return iterable<File>
     */
    public function __invoke(iterable $collection, array $context): iterable
    {
        foreach ($collection as $file) {
            // resolve url for each item
            $file->url = $this->storage->resolveUri($file);
        }
        return $collection;
    }
}
``` 
```php
<?php

namespace App\Resolver;

use ApiPlatform\Core\GraphQl\Resolver\QueryItemResolverInterface;
use App\Entity\File;
use Vich\UploaderBundle\Storage\StorageInterface;

final class GetMediaObjectResolver implements QueryItemResolverInterface
{

    /**
     * @var StorageInterface
     */
    private $storage;

    public function __construct(StorageInterface $storage)
    {

        $this->storage = $storage;
    }

    /**
     * @param File $file
     * @param array $context
     * @return File
     */
    public function __invoke($file, array $context): File
    {
        //resolve url for file
        $file->url = $this->storage->resolveUri($file);
        return $file;
    }
}
```
It now returns the URL when creating/uploading a file and when querying. 
I don't know if this is the recommended solution, but it works good enough for me.

Regarding the documentation entry, I'd volunteer to write it. 

Thanks again for the quick response and impulse.

**Comment by alanpoulain** [comment]
You're right, it should have in the `item_query` or `collection_query` as well. It should be doable by decorating the `SerializeStage`. I think it's a better alternative than adding it in the resolver.

**Comment by m0rtis** [comment]
Hi @alanpoulain,
I've got the same problem and you approach does not work when you are querying some entity which has `MediaObject` as related object. `SerializeStage` isn't be invoked for `MediaObject` in such case. Working solution I've found is to decorate `ItemSerializer`:

    /**
     * @param mixed $data
     * @param string|null $format
     * @return bool
     */
    public function supportsNormalization($data, $format = null): bool
    {
        return $data instanceof MediaObject || $this->decorated->supportsNormalization($data,$format);
    }

    /**
     * @param mixed $object
     * @param string|null $format
     * @param array $context
     * @return array|ArrayObject|bool|float|int|mixed|string|null
     * @throws ExceptionInterface
     */
    public function normalize($object, $format = null, array $context = [])
    {
        if ($object instanceof MediaObject) {
            $object->setUri($this->vich->resolveUri($object));
        }
        return $this->decorated->normalize($object, $format, $context);
    }

What do you think about it? If this is proper solution I will send pull request to add this into docs.

**Comment by alanpoulain** [comment]
I don't see why the `SerializeStage` wouldn't be invoked.
I think decorating the stage would work.

Your solution seems OK too but it's not exactly the same approach as REST. I don't know why the REST part has chosen to use an event subscriber and not a normalizer like you do.

**Comment by m0rtis** [comment]
> I don't see why the SerializeStage wouldn't be invoked.
I think decorating the stage would work.

Yes, you right. `SerializeStage` is invoking for every field. This was my mistake in implementing the stage  decorator. But decorating the Normalizer is a more universal approach. And I even glad I made that mistake:)

> I don't know why the REST part has chosen to use an event subscriber and not a normalizer like you do.

Hm... Maybe it makes sense to place my approach in the documentation in the common section about uploading files?

**Comment by alanpoulain** [comment]
Yes, documenting it would be nice.
Could you make sure it works with REST too though?

**Comment by m0rtis** [comment]
I will check. My project does not support REST, only GraphQL. So it will take some time. I will report the result.
