### ISSUE TITLE
Best way to extend an Entity?

### ISSUE THREAD

**Issue by fxkopp** [api-platform/api-platform#135]
Hey guys,

I have an Entity called _Activity_ and I'm guessing the best way to only show the **best 5 activities** for example. So there is a script with an algorithm that has to be called and returns the top 5 activities.

What is the best way to extend the API?
1. I've already tried to make a Custom Operation, but this only works for Item Operations and not for Collection Operations unfortunately.
2. Using a filter: The standard filters won't work as the algorithm has to do some calculation and not only ordering or something similar. May writing a custom filter but this looks quite difficult / is not that good documented yet.

Any other solutions? What would be best practice ?

Thank you very much.

**Comment by soyuka** [comment]
In your case you should use a ResultExtension. You can find some examples [here](https://github.com/api-platform/docs/pull/107/files) (not merged yet). Interfaces are available [here](https://github.com/api-platform/core/tree/master/src/Bridge/Doctrine/Orm/Extension). 
This allows you to do some custom operations before you return results. By settings the priority after the `PaginationExtension` (for example [10](https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml#L105)) you'll be able to return results before it reaches this one.

**Comment by teohhanhui** [comment]
Since you're talking about "top 5", use a custom `OrderFilter` together with `itemsPerPage=5` (where `itemsPerPage` is the page parameter name).

For example:

`GET /activities?order[popularity]=desc&itemsPerPage=5`

**Comment by teohhanhui** [comment]
Assuming your calculation can be done at the database level...

**Comment by teohhanhui** [comment]
> I've already tried to make a Custom Operation, but this only works for Item Operations and not for Collection Operations unfortunately.

Please let us know what is the problem you are facing when trying to add a custom collection operation.

**Comment by Simperfit** [comment]
Is it still an issue ? @fxkopp

**Comment by fxkopp** [comment]
@Simperfit don't really know - sorry had no time to test this, so maybe i will have some questions when trying :)

**Comment by Simperfit** [comment]
@fxkopp In case please open a new issue ;).
