### ISSUE TITLE
dev-tls saying address in use

### ISSUE THREAD

**Issue by tpharaoh** [api-platform/api-platform#1357]
**API Platform version(s) affected**: 2.5.3

**Description**  
ERROR: for project_dev-tls_1  Cannot start service dev-tls: driver failed programming external connectivity on endpoint project_dev-tls_1 (c29d35fc95e0f3d4abc0dbe287b6294492ca3804785f3dfcb4c7f07546bffcfd): Error starting userland proxy: listen tcp 0.0.0.0:80: bind: address already in use

I tried docker ps and killed the nginx on port 80 and tried again. Same result.

**How to reproduce**  
it happens simply with docker-compose up

**Comment by stepotronic** [comment]
Why did you close it? With the version 2.5.3 it is an issue when you simply do a docker-compose up.

**Comment by tpharaoh** [comment]
Not sure about you but I had same issue, but after reporting issue I closed
it noticing in my case was caused by another app not stopping when calling
stop.

I searched the command to see which program listening on which port and
then found the culprit.

**Comment by haroldmodesto** [comment]
Recently faced this issue. When using a mac the local httpd server is usually running. `sudo apachectl stop` should do the trick. Thanks for the hint @tpharaoh  .
