### ISSUE TITLE
Trait support

### ISSUE THREAD

**Issue by Gabb1995** [api-platform/api-platform#1358]
**Description**  

I use the Gedmo Timestampeable trait in my entities, and would love to expose the createdAt and updatedAt fields by the normalizationContext.

**Example**  

```php
/**
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ApiResource(
 *     collectionOperations={"get", "post"},
 *     itemOperations={"get", "put"},
 *     normalizationContext={"groups"={"user:read"}},
 *     denormalizationContext={"groups"={"user:write"}}
 * )
 * @UniqueEntity(fields={"nickname"})
 * @UniqueEntity(fields={"email"})
 */
class User implements UserInterface
{
    /**
     * @Groups({"user:read"})
     */
    use TimestampableEntity;
```
```php
/**
 * Timestampable Trait, usable with PHP >= 5.4
 *
 * @author Gediminas Morkevicius <gediminas.morkevicius@gmail.com>
 * @license MIT License (http://www.opensource.org/licenses/mit-license.php)
 */
trait TimestampableEntity
{
    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     */
    protected $createdAt;

    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     */
    protected $updatedAt;
```

**Comment by crowincage** [comment]
You need to set groups inside Trait on createdAt and updatedAt properties. Remove Groups on use trait statement. That's the way I use it :-)

**Comment by Gabb1995** [comment]
Yeah after I posted this and was trying to sleep I thought about this, but wasn't sure if it could access groups outside of the same class, guess it can, let me try!

**Comment by kanoamoana** [comment]
Or you could add this to your entity:

    /**
     * @Groups({"user:read"})
     * Returns createdAt.
     * @SerializedName("createdAt")
     * @return \DateTime
     */
    // createdAT provided by trait TimestampableEntity
    public function getCreatedAtTimestampable(): string

    {
        return $this->createdAt;
    }
