### ISSUE TITLE
Adding custom data to Entities

### ISSUE THREAD

**Issue by petervdbroek** [api-platform/api-platform#136]
Hi,

Just playing around with the API Platform and it looks really good. At the moment I can't figure out how to do the following use case. I have an Order entity with Orderproduct associated. In the GET /orders (collection) API call I want to return some calculated values about the Order. Such as totalValue, numProducts etc. These values can be calculated. I have to calculate discounts based on an order policy for the total value for example. I also want to add these values for the GET /orders/{id} API call. 

How can I implement this so that API Platform will expose this in my API?

I'm thinking of a few possible solutions:
1. Using Doctrine aggregated fields as described here: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/aggregate-fields.html
2. Is it possible to do it with a custom EntityRepository? Will API Platform pickup for example getTotalValue() from the EntityRepository?
3. Using custom operations / controllers

Am I missing another way to add custom data to an Entity? What is the best practice?

Thanks in advance.

**Comment by teohhanhui** [comment]
#1 is the way to go.

> 2. Is it possible to do it with a custom EntityRepository? Will API Platform pickup for example getTotalValue() from the EntityRepository?

The way you achieve it does not matter, as long as the getter is there on the entity and it's exposed through the correct serializer groups used in the normalization context.

**Comment by carlespibernatcreus** [comment]
Hi,

So the best option is to add it as a new column into database? And if, for example, its value it's taken from another api? Then it has no sense to store any value into database.

Thanks!

**Comment by srosato** [comment]
I was wondering too, but no, as @teohhanhui suggested, as long as you have the correct serializer groups. You can add it on an accessor. For example,

```yaml
AppBundle\Entity\AnEntity:
    collectionOperations:
        get:
            method: GET
    itemOperations:
        get:
            method: GET
    attributes:
        normalization_context:
            groups:
                - get
```
Note that we could also use the `@ApiResource` annotation, I just took from my own project.

And the `AnEntity` class:
```php
namespace AppBundle\Entity\AnEntity;

class AnEntity
{
    /**
     * @var string
     *
     * @ORM\Column(name="tag", type="string", length=3, nullable=false)
     * @Groups({"get"})
     */
    private $tag;

    public function getTag(): string
    {
        return $this->tag;
    }

    /**
     * @Groups({"get"})
     */
    public function getFoo(): string
    {
        return $this->getTag();
    }
```

Will automatically expose "foo" and have the value of the `getTag()` function in this case.

**Comment by carlespibernat** [comment]
Thanks! Works like a charm

**Comment by plamenh** [comment]
Any idea how we can make this work for GraphQL, we get a 'Cannot query field \"foo\" on type \"Bar\"'. With a regular query it works fine, of course.

**Comment by srosato** [comment]
I have only set it up for a REST endpoints, so I do not know for GraphQL unfortunately I would assume it works the same. I do not have much context from your error so it's hard to tell what is wrong.

**Comment by plamenh** [comment]
I figured it out, so for anyone who's having trouble: It was not working in GraphQL, because we hadn't set '@return' type annotation. Once this is set, it works like a charm.
