### ISSUE TITLE
Can't use hautelook/alice-bundle due to "doctrine/doctrine-migrations-bundle": "^2.0"

### ISSUE THREAD

**Issue by sareiodata** [api-platform/api-platform#1361]
**API Platform version(s) affected**: 1.1

**Description**  

Trying to follow this tutorial: https://api-platform.com/docs/distribution/testing/ 
I can't install alice due to requirements in composer.json file related to doctrine version.

**How to reproduce**  

Run: docker-compose exec php composer require --dev  hautelook/alice-bundle 
I'm getting: 
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install hautelook/alice-bundle v2.5.1
    - Conclusion: remove doctrine/doctrine-bundle 2.0.0
    - Installation request for hautelook/alice-bundle ^2.5 -> satisfiable by hautelook/alice-bundle[2.5.0, v2.5.1].
    - Conclusion: don't install doctrine/doctrine-bundle 2.0.0
    - hautelook/alice-bundle 2.5.0 requires doctrine/doctrine-bundle ^1.8 -> satisfiable by doctrine/doctrine-bundle[1.10.0, 1.10.1, 1.10.2, 1.10.3, 1.11.0, 1.11.1, 1.11.2, 1.12.0, 1.12.1, 1.12.2, 1.8.0, 1.8.1, 1.9.0, 1.9.1].

**Additional Context**  

There is an open issue over at the alice-bundle repo: 
https://github.com/hautelook/AliceBundle/pull/485

**Comment by antograssiot** [comment]
just downgrade doctrine-bundle and you'll be good, that not an issue with the distribution nor the doc I think

**Comment by dunglas** [comment]
There is nothing we can do on our side except what @antograssiot described. This must be fixed in AliceBundle. Closing here.
