### ISSUE TITLE
Allowing NULL value in json with API-Platform

### ISSUE THREAD

**Issue by coolfarmer** [api-platform/api-platform#1364]
**API Platform version(s) affected**: v2.5.3 (core)

https://api-platform.com/docs/core/filters/#managing-null-values

**Description**  
I want to allow null value inside my json result but even with the good date filter I can't have it.
My class have been generated with make:entity.

```
/**
 * @ApiResource(normalizationContext={"groups"={"employee"}})
 * @ApiFilter(DateFilter::class, properties={"dateProperty": DateFilter::INCLUDE_NULL_BEFORE_AND_AFTER})
 * @ORM\Table(name="employee")
 */
class Employee
{
    // ...

    /**
     * @ORM\Column(type="datetime", nullable=true)
     * @Groups({"employee"})
     */
    private $firedDate;

    public function getFiredDate(): ?\DateTimeInterface
    {
        return $this->firedDate;
    }

    // ...
}
```

If I go to my route I get all the values but not the firedDate.
If I set a date in my database for firedDate I can get it without problem.

So is this a bug with DateFilter? Why I can't get null value?

Thanks.

**Comment by cenemoi** [comment]
Morning,

Try with "itemOperations={"get"},"

```
* @ApiResource(
 *      itemOperations={"get"},
 * )
```

**Comment by coolfarmer** [comment]
> 
> 
> Morning,
> 
> Try with "itemOperations={"get"},"
> 
> ```
> * @ApiResource(
>  *      itemOperations={"get"},
>  * )
> ```

Wow! It work!!! My god thanks you are my hero!!!

**Comment by winzza** [comment]
it's don't work for me.

**Comment by winzza** [comment]
I found the right solution:
https://stackoverflow.com/questions/59314728/allowing-null-value-in-json-with-api-platform#59856013

**Comment by lebadapetru** [comment]
> I found the right solution:
> https://stackoverflow.com/questions/59314728/allowing-null-value-in-json-with-api-platform#59856013

Im using apiplatform 2.6.3 and to me it doesn't work. Anyone else facing this issue?
