### ISSUE TITLE
Symfony 4.4 is not there

### ISSUE THREAD

**Issue by razbakov** [api-platform/api-platform#1368]
**API Platform version(s) affected**: 2.5.3

**Description**  

In release notes states `Upgrade to Symfony 4.4` but it's not possible to update to 4.4 and actual version is 4.3

**How to reproduce**  

```
$ docker-compose exec php composer info | grep symfony/frame

symfony/framework-bundle            v4.3.9  Symfony FrameworkBundle

$ cat api/composer.json:

    "extra": {
        "symfony": {
            "allow-contrib": false,
            "require": "4.3.*"
        }
    }
```

**Comment by teohhanhui** [comment]
This looks like a mistake indeed. /cc @dunglas

**Comment by mickaelandrieu** [comment]
Hello @teohhanhui,

can we expect a support of Symfony 5.0.x for the next release ?

If it's working for 4.4, the chances are good that it will also works for Symfony 5.0 🤞 

Regards
