### ISSUE TITLE
Create a new subscription with a user that already exists in database

### ISSUE THREAD

**Issue by foolskill** [api-platform/api-platform#137]
Hi Team,

I would like to optimize my queries on Doctrine and I face a scenario that I can not manage and I would like to get your help.

Script: create a new subscription with a user that already exists in database

If the information in the existing user have changed (eg phone), we first updates the user data before creating a new subscription

- phone: 04235698745 (The new user phone)
- @id: / users / 160

`{"date":"2016-09-12","type":"politique","message":"j'aimerai particip\u00e9 \u00e0 ce meeting","user":{"firstName":"PHY","lastName":"NUHIO","gender":1,"phone":"04235698745","@id":"\/users\/160"}}`

Is there a configuration that can manage this case?

Meanwhile, we can do
PUT request to update the user
POST request to create a new subscription

But it is less efficient.

thank you.

I like your project, it makes my developments very easy.

**Comment by teohhanhui** [comment]
If you set the correct serializer groups for denormalization in the `User` entity, you can embed the user and it'll be updated.

**Comment by teohhanhui** [comment]
See https://github.com/api-platform/docs/blob/master/core/serialization-groups-and-relations.md

**Comment by foolskill** [comment]
Thank's
