### ISSUE TITLE
Denormalization of a Datetime object with Elasticsearch

### ISSUE THREAD

**Issue by Cocray** [api-platform/api-platform#1370]
**API Platform version(s) affected**: 2.5.2

**Description**  
Hi APIP team,
My project use API Platform and Elasticsearch. It works perfectly, I can read my documents. But when I add a Datetime field, I have this issue when I try to GET a document:
Failed to denormalize attribute \"created_at\" value for class \"App\\Entity\\File\": Expected argument of type \"DateTime\", \"string\" given at property path \"created_at\"

Here is my mapping:
```
{
  "mapping": {
    "properties": {
      "created_at": {
        "type": "date",
        "format": "yyyy-MM-dd HH:mm:ss"
      },
      "id": {
        "type": "keyword"
      },
      "path": {
        "type": "keyword"
      },
      "path_source": {
        "type": "keyword"
      },
      "reference": {
        "type": "keyword"
      }
    }
  }
}

```

I can't find in the code where date fields are changed from a string in ES to a DateTime object in API Platform. So when the denormalize function in api-platform/core/src/Bridge/Elasticsearch/Serializer/ItemNormalizer is called, created_at field is still a string instead of a Datetime object and the function setCreatedAt(Datetime $createdAt) will fail.

Thanks

**Comment by soyuka** [comment]
I remember having this bug. Make sure that the date format matches an ISO format that the datetime API support. I think that there's an issue with the Elasticsearch normalizer but we'd need some unit test to be sure. A workaround is to change the type of the `createdAt` argument to a string and transform the string there :|.

**Comment by Cocray** [comment]
Hello @soyuka,

Thanks a lot for your answer. I use Gedmo Timestampable, and I override the setter in your way :)
```
public function setCreatedAt($createdAt): File
{
    if (is_string($createdAt)) {
        $createdAt = \DateTime::createFromFormat('Y-m-d H:i:s', $createdAt);
    }
    $this->createdAt = $createdAt;

    return $this;
}
```

Thanks
