### ISSUE TITLE
[Doctrine ORM Extension] Where clause on join

### ISSUE THREAD

**Issue by mpiot** [api-platform/api-platform#1392]
**API Platform version(s) affected**: 2.5.4

**Description**  
When you have an Entity like a `Group` with a collection of `Users`, and when you GET the `Group item` with only the current user, it works well if you get IRI.

You only have something like:
```json
{
  "@id": "/api/group/1",
  "members": {
    "/api/users/1"
  }
}
```

But if you use GraphQL, or normalizationContext, to get more infos on the member in the list, then it totally fail, it return:
```json
{
	"@id": "/api/groups/1",
	"members": [{
			"@id": "/api/users/1",
			"...": ""
		},
		{
			"@id": "/api/users/2",
			"...": ""
		},
		{
			"@id": "/api/users/3",
			"...": ""
		}
	]
}
```

The extension contains it:
```php
$rootAlias = $queryBuilder->getRootAliases()[0];
$queryBuilder
    ->leftJoin(sprintf('%s.members', $rootAlias), 'members')->addSelect('members')
    ->andWhere('members = :current_user')
    ->setParameter('current_user', $user);
```

**Possible Solution**  
Not really a solution but the problem is in the way the query is build, because we need extra info it add a Join of User on Group, but to get the filter we already have a Join and a Where clause. Then we retrieve the current user twice, with all others. (Double join and select)

**Comment by AbbesBendaoud10** [comment]
You need to do something like : 

    $rootAlias = $queryBuilder->getRootAliases()[0];
    $queryBuilder
         ->leftJoin(sprintf('%s.members', $rootAlias), 'members')->addSelect('members')
         ->andWhere(':current_user MEMBER OF members')
         ->setParameter('current_user', $user);

**Comment by mpiot** [comment]
@AbbesBendaoud10 thanks for your answer, I've just try it, but it does the same thing.

To give me the complementary data it done a second request with a SELECT IN SELECT, and do not care on the previous request.

```sql
SELECT 
  a0_.id AS id_0, 
  a0_.username AS username_1, 
  a0_.password AS password_2, 
  a0_.enabled AS enabled_3, 
  a0_.roles AS roles_4, 
  a0_.last_name AS last_name_5, 
  a0_.first_name AS first_name_6, 
  a0_.email AS email_7, 
  a0_.phone_number AS phone_number_8 
FROM 
  app_user a0_ 
WHERE 
  a0_.id IN (
    SELECT 
      a1_.id 
    FROM 
      european_project e2_ 
      INNER JOIN european_project_user e3_ ON e2_.id = e3_.european_project_id 
      INNER JOIN app_user a1_ ON a1_.id = e3_.user_id 
    WHERE 
      e2_.id = ?
  ) 
ORDER BY 
  a0_.last_name ASC, 
  a0_.first_name ASC, 
  a0_.id ASC
```

**Comment by soyuka** [comment]
When queries become that complex it's hard to make them work automatically. Would you be able to write the query by hand for this case?

**Comment by mpiot** [comment]
@soyuka, in fact the query is not really complex, but it's a Doctrine interpretation problem, not api-platform finally (at first, wh'en I've opend the issue, the error only appeared on GraphQL and not in Rest. But finally I've the same problem with Rest if I use normalizationContext to add more infos.

It's more a Doctrine way to retrieve data problem, in place of join on or done the request by select only filtered data, it done a second request that ignore the filter.

I've a problem near to that when trying to filter on nullable relation throught a ManyToMany relation, because of the third table, it always not null if the user is in one group.

Group => GroupUser => User

But thanks for your help :)
