### ISSUE TITLE
How to enable schema discoveries while securing graphql endpoint

### ISSUE THREAD

**Issue by jav974** [api-platform/api-platform#1397]
Hello,

i'm willing to allow others to discover the schema via introspection queries, but the endpoint /api/graphql is secured in my config.

Is there a way to achieve this ? Even more important, is this a desired behaviour or should i stick with authentication first before schema discovery ?

I'm asking this because i really enjoy the autocompletion features provided by GraphQL plugins inside IDEs, that is not working if the endpoint is secured..

Thank's a lot !

**Comment by soyuka** [comment]
Yes IMO having the introspection query without security might be a security hole. Still, why don't you allow this in development mode while you disable it in production? Closing as there's no good solution here.
