### ISSUE TITLE
Is there any way to integrate KNPDoctrineBehaviors with api-platform?

### ISSUE THREAD

**Issue by dvalverdeGF** [api-platform/api-platform#1399]
I'm using KNPDoctrineBehaviors for translate database content. When I create a resource the I'm getting this error:

> Class App\Entity\TranslationInterface does not exist

Someone got the same issue ? :)

Thanks for your work @api-platform !

**Comment by akira28** [comment]
Wow, I literally just published this issue https://github.com/api-platform/api-platform/issues/1400 , after trying to make it work for a couple days. It seems to be an issue with the ReflectionClass

**Comment by dvalverdeGF** [comment]
> Wow, I literally just published this issue #1400 , after trying to make it work for a couple days. It seems to be an issue with the ReflectionClass

It’s really a curious coincidence!

I've found the problem appears trying to render de api doc. The api works when I make calls with Postman.

Right now I can see the API doc, but really I don't know what I have done for solve the problem.
I have read some articles about I18n.

Please, try using the normalizationContext y your API definition.

```
/**
 * @ORM\Entity()
 * @ApiResource(
 *     normalizationContext={"groups"={"opcion", "opcion:read"}},
 *     collectionOperations={
 *         "get",
 *         "post" = {
 *           "denormalization_context" = {"groups"={"opcion", "opcion:write"}}
 *          }
 *     },
 *     itemOperations={
 *         "get",
 *         "put"={
 *              "denormalization_context" = {"groups"={"opcion"}}
 *          },
 *         "delete"
 *     }
 * )
 */
```

**Comment by jenyak** [comment]
to get rid of the error just add
`use Knp\DoctrineBehaviors\Contract\Entity\TranslationInterface;`
to translatable entity

**Comment by soyuka** [comment]
Yeah there's a bug with these imported classes see https://github.com/api-platform/core/issues/3349

**Comment by tamert** [comment]
how solved this problem?

**Comment by GPMathieu** [comment]
@soyuka Did you have some news about this bug ?

**Comment by bettinz** [comment]
Solved by adding
`use Knp\DoctrineBehaviors\Contract\Entity\TranslationInterface;`
at the beginning of translatable entity. Thanks @jenyak

**Comment by akira28** [comment]
@bettinz sorry for the offtopic, but I'm adding right now a translatable entity, and my question is how do you manage to choose the translation to return to the client? Some kind of listener of a query param o header?

**Comment by bettinz** [comment]
@akira28 Check here: https://github.com/KnpLabs/DoctrineBehaviors/blob/master/docs/translatable.md
I accept a virtual property called "language" with, for example, "en" and then I return this
`$category->translate($entity->getLanguage())->getName();`

**Comment by akira28** [comment]
@bettinz nice! Anyway I'm trying this now: https://packagist.org/packages/locastic/api-platform-translation-bundle
it has the behavior I need with the `locale` query param, and as it uses doctrine relations I can decide the column names

**Comment by bettinz** [comment]
Thank you for the advice, I'll check it 😎

**Comment by tamert** [comment]
if you didn't set "collectionOperations > post" the same issue happened. 
Why unset and default POST call **TranslationInterface** problem ... 
I solved but but the issue is an annoying situation

**Comment by DanidCH** [comment]
> Solved by adding
> 
> `use Knp\DoctrineBehaviors\Contract\Entity\TranslationInterface;`
> 
> at the beginning of translatable entity. Thanks @jenyak 

@bettinz any example of how you sober your problem? I've tried as you said to add the `use Knp\DoctrineBehaviors\ Contract\Entity\TranslationInterface;` at the beginning but the error remains…

**Comment by bettinz** [comment]
Hello @DanidCH this is how I use in in my entity
```php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Knp\DoctrineBehaviors\Contract\Entity\TranslationInterface;
use Knp\DoctrineBehaviors\Model\Translatable\TranslationTrait;
use App\Repository\LabelTranslationRepository;
use Ramsey\Uuid\UuidInterface;

/**
 * @ORM\Entity(repositoryClass=TextTranslationRepository::class)
 */
class TextTranslation implements TranslationInterface
```

**Comment by muhammadtashfeen** [comment]
Hello all,
I am unable to perform PUT or PATCH request for my endpoint and it throws following error:
`"Duplicate entry '1-de' for key 'category_translation_unique_translation'"`

I have two very simple classes Category and CategoryTranslation from the DoctrineBehaviors example code [here](https://github.com/KnpLabs/DoctrineBehaviors/blob/master/docs/translatable.md)

```
/**
 * @ORM\Entity
 */
class CategoryTranslation implements TranslationInterface
{
    use TranslationTrait;

    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    protected $name;
    
   ...SETTERS and GETTERS...
```

```
/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass=CategoryRepository::class)
 */
class Category implements TranslatableInterface
{
    use TranslatableTrait;
    
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
    
    public function getId(): ?int
    {
        return $this->id;
    }
}
```

Any help would be appreciated. Thank you :)

**Comment by amir-souissi** [comment]
@dvalverdeGF

you saved me ! thank you... In fact I added **denormalizationContext: ["groups" => "promotion:write"],** and next I have to clear cache ... and then the /api/docs works fine.... Hope it can help some others

**Comment by cmarsaudon687** [comment]
@muhammadtashfeen  I have same problem, did you find a solution ?

**Comment by dvalverdeGF** [comment]
> @muhammadtashfeen I have same problem, did you find a solution ?

Try using the normalizationContext in your API definition.

https://github.com/api-platform/api-platform/issues/1399#issuecomment-578540784
https://github.com/api-platform/api-platform/issues/1399#issuecomment-1274777560

**Comment by TPantelConventus** [comment]
I got rid of the Exception my replacing 

~~~php
use  TranslatableTrait;
~~~

 in the translatable Entities with:

~~~php
use TranslatableMethodsTrait;
  use TranslatablePropertiesTrait;
~~~

 The TranslatableTrait does nothing else than using those two Traits. But using them directly instead of using the Wrapper made the exception disappear.

**Comment by quentinRogeret34** [comment]
I have the same issue, have you found a solution?
