### ISSUE TITLE
Help Wanted : Serialization

### ISSUE THREAD

**Issue by Miniplop** [api-platform/api-platform#1402]
Hello, 

I have an issue with the serialization process. 

**Context**

I have two entities Layer & Assets linked by a ManyToOne bidirectional

```
/**
 * @ApiResource(
 *   denormalizationContext={
 *     "groups"={"write-component"},
 *     "enable_max_depth"=true
 *   }
 *)
 * @ORM\Entity
 */
class Layer {
     /**
     * @var Collection
     * @Groups({"write-component"})
     * @ORM\OneToMany(targetEntity="Asset", mappedBy="layer", cascade={"persist"})
     * @MaxDepth(1)
     **/
    private $assets;
}
```

```
/** @ApiResource(
 * denormalizationContext={
 *     "enable_max_depth"=true
 *   },
 * )
 * @ORM\Entity
 */
class Assets {
 /**
     * @var Layer
     * @Groups({"write-component"})
     * @ORM\ManyToOne(targetEntity="Layer", inversedBy="assets")
     * @ORM\JoinColumn(name="layer_id", referencedColumnName="id")
     * @MaxDepth(1)
     */
    private $layer;
}
```

when I make this request `POST /layer`

```
{
  "assets": [
     "/api/assets/132",
     "/api/assets/133"
  ]
}
```

I have this error message : `The total number of joined relations has exceeded the specified maximum. Raise the limit if necessary, or use the \"max_depth\" option of the Symfony serializer."`

**Questions** : 

My goal is to a create a Layer entity and linked existing Asset entity to it, I try MaxDepth (see above), but it's not working as expected :) Is it the good way to do this ? I don't understand how api platform serialize my assets entities :/ I'm probably doing a wrong things here :) 

Thank you for your help :)

**Comment by Miniplop** [comment]
solved 

I close the issue

**Comment by MedKayed** [comment]
@Miniplop how did you solve it, i have the same issue
