### ISSUE TITLE
Q: PUT should be doing INSERT or UPDATE; right now it only UPDATEs

### ISSUE THREAD

**Issue by MihailoJoksimovic** [api-platform/api-platform#1404]
**Description**  

First of all, I'm not honestly sure if this is a FEATURE REQUEST or a BUG. Namely, the way that PUT operation works now is that **it expects that object EXISTS prior to being updated**. However, that seems to be against the PUT's specification:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PUT
https://tools.ietf.org/html/rfc7231#section-4.3.4

The specification states:

> The PUT method requests that the state of the target resource be created or replaced with the state defined by the representation enclosed in the request message payload.

Hence, as I said, I'm not sure if the current behavior is buggy or not.

**Comment by Episch** [comment]
Maybe I'm not the right one for the job, but I haven't noticed any additions on MDN yet.

"The common use case is to return 204 as a result of a PUT request, updating a resource, without changing the current content of the page displayed to the user. If the resource is created, 201 Created is returned instead. If the page should be changed to the newly updated page, the 200 should be used instead. " **https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204**

-> The common use case is to return 204 as a result of a PUT request, updating a resource, without changing the current content of the page displayed to the user

Sounds like it is possible to send a call with put and if there is nothing to change, a 204 status code is returned. However, it also says that when an object is created, a status code 201 comes back and when an update works a 200 comes back. But how is it differentiated between there is nothing to update so status code 204 and status code 201 with object is created.

So it must be possible between;

Default:
Object existing / and can be updated -> PUT response 200

Case A:
Object is missing / and cant be updated -> PUT response 204
Case B:
Object is missing / and can be created -> PUT response 201



But how can it be made possible to indicate the behavior, to differentiate between case A and case B?

**Comment by MihailoJoksimovic** [comment]
Hi @Episch and thanks a lot for your response!

To be honest, I didn't even get that far with the 204 and 201 statuses, but indeed it'd probably make sense to consider it.

However, the problem that API Platform is having right now is that **if object DOES NOT exist, it will NOT be created, but the 404 will be returned instead**. And that's really the source of the issue that I mentioned here.

**Comment by soyuka** [comment]
I think that this has been a choice here. Anyway, it'd not be very hard to implement, even on your side. @api-platform/core-team any thoughts?

**Comment by teohhanhui** [comment]
>    Proper interpretation of a PUT request presumes that the user agent
>    knows which target resource is desired.  A service that selects a
>    proper URI on behalf of the client, after receiving a state-changing
>    request, SHOULD be implemented using the POST method rather than PUT.

To me, this implies that this "upsert" behaviour can only be implemented when the client decides the identifier.

**Comment by dunglas** [comment]
> To me, this implies that this "upsert" behaviour can only be implemented when the client decides the identifier.

Exactly. Doing this is currently not supported in API Platform (it's a known limitation). We'll be glad to accept a patch that gets rid of this limitation by to allowing to create the object at the requested URL if it doesn't exist yet by using `PUT`.

**Comment by dunglas** [comment]
Note that this feature will be useless if the resource is identified by a server-side-generated, non-predictable ID (sequence, auto-increment, and even UUID). It's only useful when resource IDs are predictable, which isn't very common these days.

**Comment by jarkt** [comment]
> Note that this feature will be useless if the resource is identified by a server-side-generated, non-predictable ID (sequence, auto-increment, and even UUID). It's only useful when resource IDs are predictable, which isn't very common these days.

But an UUID could be client generated, which isn't completely uncommon. I will create a custom controller for this one entity where I have the issue now.

**Comment by nnikolay** [comment]
> > To me, this implies that this "upsert" behaviour can only be implemented when the client decides the identifier.
> 
> Exactly. Doing this is currently not supported in API Platform (it's a known limitation). We'll be glad to accept a patch that gets rid of this limitation by to allowing to create the object at the requested URL if it doesn't exist yet by using `PUT`.

Hi @dunglas, is this limitation already solved?

**Comment by dunglas** [comment]
Yes, this has been solved in API Platform 3!
