### ISSUE TITLE
Symfony 5 support

### ISSUE THREAD

**Issue by tomadimitrie** [api-platform/api-platform#1409]
Are there any plans on supporting Symfony 5?

**Comment by wow-apps** [comment]
@tomadimitrie 
It work's well on Symfony 5!

https://packagist.org/packages/api-platform/api-pack

<img width="248" alt="image" src="https://user-images.githubusercontent.com/2779949/74169165-8f555a00-4c33-11ea-9f9d-02bf36e3bce3.png">


And here's my `composer.json` file screenshoot of developing project:

<img width="440" alt="image" src="https://user-images.githubusercontent.com/2779949/74169269-b9a71780-4c33-11ea-9ded-de3c4a82acd8.png">

just run: `composer require api` ;)

**Comment by tomadimitrie** [comment]
Oh, thank you, it worked!! Tried like a week ago to update but got a lot of dependencies conflicts, but now it's all good
