### ISSUE TITLE
/certs/localhost.crt: no such file or directiry

### ISSUE THREAD

**Issue by oleksandr-dubrovskyi-codetiburon** [api-platform/api-platform#1410]
After docker-compose pull and docker-compose up -d I have the same error in logs for mercure and vulcain containers: level=fatal msg="open /certs/localhost.crt: no such file or directory

![image](https://user-images.githubusercontent.com/56152742/74107483-6e303300-4b79-11ea-8c0e-66938138eca4.png)
![image](https://user-images.githubusercontent.com/56152742/74107516-aa639380-4b79-11ea-9719-ec701bac93e1.png)

Maybe someone has encountered such a problem and resolve this?

**Comment by GregoireHebert** [comment]
hi @oleksandr-dubrovskyi-codetiburon !

I referenced your issue because it target the same lines of code, but it seems a little different. On some occasion the generation of the certificates might fail. The #1414 might fix it for you, anyway you can try to rebuild the dev-tls container, or run the mkcerts lines manually inside the container.
You should also check that your volumes are correctly mounted.

**Comment by teohhanhui** [comment]
Actually perhaps we could just distribute a pre-generated dev cert? Lol...

**Comment by GregoireHebert** [comment]
These certificates must never be used in production anyway, so IMO not that much a security concern, at least not worse than it already is.

**Comment by Spomky** [comment]
Hi,

I have the same problem.
It occures when I stop the containers (e.g. `docker stop $(docker ps -a -q)`) and restart them (`docker-compose up -d`).

To solve that, I had the completely remove the images and volumes and rebuild everything… but that’s not a really convenient way to solve that issue.
During the builds, the certificate is correctly generated (I can see it in the log)

**Comment by soyuka** [comment]
https://github.com/api-platform/api-platform/pull/1415 should fix this

**Comment by teohhanhui** [comment]
> #1415 should fix this

Not sure about that...

**Comment by dunglas** [comment]
> Actually perhaps we could just distribute a pre-generated dev cert? Lol...

It's not a good idea: https://medium.com/@mikenorth/webpack-preact-cli-vulnerability-961572624c54 (especially the last paragraph).

**Comment by dunglas** [comment]
I confirm that the problem still occurs. The current workaround is to remove the volumes (`docker-compose down -v`) and restart the containers again (`docker-compose up`). But it's far from being ideal. We need to fix this.

**Comment by dunglas** [comment]
Fixed by switching to Caddy server.
