### ISSUE TITLE
Prevent POST operations ignoring data that is not part of the de-normalization context

### ISSUE THREAD

**Issue by tomsykes** [api-platform/api-platform#1417]
**API Platform version(s) affected**: all?

**Description**  
Any data that is part of the request body, but not referenced in the de-normalization context for POST, PUT and PATCH operations is simply ignored. It would be good to be able to run a strict API which throws a 400 bad request error when unexpected fields are added to the body. It's essentially the equivalent of "allow_extra_fields" on symfony forms.

**How to reproduce**  
Example entity "Book" has a single field in the de-normalization context - "title".
Sending a POST request to /api/books with the data
```json
{
    "title": "The Hitchhiker's Guide to the Galaxy",
    "extraData": 42
}
```
I would like this to return a 400

**Possible Solution**  
Have a configurable option for strict de-normalization contexts

**Additional Context**  
I have searched far and wide, but cannot find any discussion on this topic relating directly to API platform. Am I missing an obvious fix to this, or even existing config options?

There is a good discussion on the general subject relating to RESTful APIs here's
https://stackoverflow.com/questions/20526784/restful-api-correct-behaviour-when-spurious-not-requested-parameters-are-passe

**Comment by j-schumann** [comment]
This should already be possible: https://github.com/api-platform/core/issues/1217#issuecomment-488662805

**Comment by soyuka** [comment]
Thanks @j-schumann lmk if this doesn't help @tomsykes
