### ISSUE TITLE
Tag with openapi_context in subresource

### ISSUE THREAD

**Issue by bettinz** [api-platform/api-platform#1419]
**API Platform version(s) affected**: 2.5.4

**Description**  
The subresource is not tagged like property in an Entity.

**How to reproduce**  
Create an Entity Service, with many-to-many Lenghts.

\App\Entity\Length.php
```
/**
     * @ORM\ManyToMany(targetEntity="App\Entity\FinancingService", mappedBy="serviceLengths")
     * @ApiProperty(
     *     attributes={
     *          "openapi_context"={
     *              "tags" = {"PublicWizard"}
     *          }
     *     })
     */
    private $services;
```

\App\Entity\Service.php
```
 /**
     * @ORM\ManyToMany(targetEntity="App\Entity\FinancingLength", inversedBy="services")
     * @ApiSubresource()
     * @ApiProperty(
     *     attributes={
     *          "openapi_context"={
     *              "tags" = {"PublicWizard"}
     *          }
     *     })
     * @var FinancingLength
     */
    private $serviceLengths;
```

I'm expecting that
/api/services/{id}/lengths
and
/api/services/{id}/lengths

are under "PublicWizard" group. But they are alone.
Instead, the classes Service and Length with

```
 *      itemOperations={
 *          "get" = {
 *              "openapi_context"={
 *                  "summary" = "Retrieve the list of all services. STEP 1",
 *                  "description" = "The supported method is only GET and it's available for anonymous queries. The step is the 1st",
 *                  "tags" = {"PublicWizard"}
 *              }
 *          }
 *      },
```
are correctly under "PublicWizard" group.

Thanks

**Comment by soyuka** [comment]
You need to declare the context in the subresource operation.

**Comment by bettinz** [comment]
Thank you for the reply. 
As suggested at https://api-platform.com/docs/core/subresources/ I've ran
bin/console debug:router
and found the correct route name.
So I've added

```
 * @ApiResource(
 *      subresourceOperations={
 *          "api_service_lengths_get_subresource"={
 *              "path"="/api/services/{id}/lengths",
 *              "tags" = {"PublicWizard"}
 *          },
 *      }
```
but it doesn't move the route under "PublicWizard". Is it a known error? Thanks

**Comment by soyuka** [comment]
Yes it's how the subresources are built, there's an issue about that and it's still under improvement.

**Comment by bettinz** [comment]
Thank you for the kind reply :-)

**Comment by sudent** [comment]
Hi. Any progress on this? Or any pointer where I should look how the tags are set for subresources? Thanks

**Comment by egorzot** [comment]
Hi everyone! 
I'm stuck with defining `openapi_context` in subresource operation.
Can everyone explain how to do that?  
This code doesn't work:
```
#[ApiResource(
    subresourceOperations: [
        'api_tests_links_get_subresource' => [
            'security' => "is_granted('ROLE_ADMIN') or is_granted('ROLE_MANAGER')",
            'method' => 'GET',
            'path' => '/tests/{id}/links',
            'openapi_context' => [
                'summary'=>'Summary',
                'description'=>'Description'
            ]
        ]
)]
```

**Comment by Snowbaha** [comment]
Hello @egorzot , did you find the solution? I have the same issue :(

**Comment by egorzot** [comment]
> Hello @egorzot , did you find the solution? I have the same issue :(

It doesn't work. 
You should set it up with decorator or with event handler.
