### ISSUE TITLE
nproc not found in php:7.2-fmp-alpine

### ISSUE THREAD

**Issue by toby-griffiths** [api-platform/api-platform#1420]
**API Platform version(s) affected**: 2.4.5 (& maybe affect others)
PHP version: 7.2

**Description**  
Recently attempted to rebuild my containers on a new laptop, and build failed due to `nprocm not found` error.
I fixed this by including `coreutils` in the `.build-deps`, before installing the PHP extensions.

**How to reproduce**  
Setup a project using the skeleton, & attempt to build the containers (although I've not tried this on the most recent version).

**Possible Solution**  
Install `coreutils` using `apk add --no-cache coreutils`

**Additional Context**  
I believe this is because the latest `php:7.2-fpm-alpine` container no longer includes this command by default.  I've checked the 7.4 version of the file, and it appears to be included, so raising this ticket to raise awareness that others might get caught out by this.

I suspect this ticket can be instantly closed, but will allow other uses to find this issue, and it's fix.

**Comment by soyuka** [comment]
thanks for the heads up @toby-griffiths !
