### ISSUE TITLE
docker compose : error getting response : Connection reset by peer

### ISSUE THREAD

**Issue by ElNelyo** [api-platform/api-platform#1426]
**API Platform version(s) affected**:  latest

**Description**  
I followed the documentation from API platform
- git fork 

```
$ docker-compose pull # Download the latest versions of the pre-built images
$ docker-compose up -d # Running in detached mode
```
![image](https://user-images.githubusercontent.com/17676307/75017755-04bff680-548e-11ea-8564-f3068a52b117.png)

**Comment by dunglas** [comment]
It looks like a network issue on your side. Docker isn't able to connect to github.com to build the container, and it's mandatory.

Closing, feel free to reopen if it's not related to your network configuration (but it's very unlikely).
