### ISSUE TITLE
 "Attempted to load trait "HttpClientTrait" from namespace "Symfony\Component\HttpClient"

### ISSUE THREAD

**Issue by Whiterid** [api-platform/api-platform#1437]
Hi!

I got an issue with my new project in symfony 4.4 and api-plateform.
When i POST a new Object, i got a error message from a file in test directory in api plateform.

**API Platform version(s) affected**: 2.5.4

**Description**  
[2020-02-28 09:39:29] request.CRITICAL: Uncaught PHP Exception Symfony\Component\ErrorHandler\Error\ClassNotFoundError: "Attempted to load trait "HttpClientTrait" from namespace "Symfony\Component\HttpClient"
[response_1582882770218.json.log](https://github.com/api-platform/api-platform/files/4266405/response_1582882770218.json.log)

. Did you forget a "use" statement for another namespace?" at [...]/vendor/api-platform/core/src/Bridge/Symfony/Bundle/Test/Client.php line 34 {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\ClassNotFoundError(code: 0): Attempted to load trait \"HttpClientTrait\" from namespace \"Symfony\\Component\\HttpClient\".\nDid you forget a \"use\" statement for another namespace? at [...]/vendor/api-platform/core/src/Bridge/Symfony/Bundle/Test/Client.php:34)"} []
`

Ty a lot for your answer and your work. :)

**Comment by soyuka** [comment]
Install symfony http client?

**Comment by Romain** [comment]
That fixed it for me.

**Comment by soyuka** [comment]
this happend when you were using the TestClient right? Closing as fixed.
