### ISSUE TITLE
An exception has been thrown during the rendering of a template. Unexpected collection operator "<", class name is missing. Make sure there is a loader supporting the "api_platform" type.

### ISSUE THREAD

**Issue by mikaelit** [api-platform/api-platform#1440]
I can not find directly the culprit, though in my opinion it is the swagger issue. The message of the exception point in to api platform, so I start reporting this issue from here.

Full message:

> An exception has been thrown during the rendering of a template ("Unexpected collection operator "<", class name is missing in . (which is being imported from "/app/config/routes/api_platform.yaml"). Make sure there is a loader supporting the "api_platform" type.").

This exception throw after add any entity, even on default settings.
After `composer require api` everythings is ok. But when I set annotation `@ApiResource()` or register entity in other `yml, xml` file, FileLoader throw this exception.

I use `symfony: "4.2.*", api-pack: "^1.2"`

**Comment by mikaelit** [comment]
For posterity.
Do not use char "<" or " >" in annotations tag. Swagger do not handle with it!

For example:
`/**
     * @return <\Doctrine\Common\Collections\Collection, multitype:\App\Entity\User >
     */`

**Comment by saniyar-dev** [comment]
Hi can you share the solution you found for this problem?
As you closed the issue I think you've solved it
