### ISSUE TITLE
[Elasticsearch] How to define username and password security params set with xpack?

### ISSUE THREAD

**Issue by Cocray** [api-platform/api-platform#1443]
**API Platform version(s) affected**: 2.5.4

**Description**  
In the doc, it is very clear how we must define the host param in order to connect to the Elasticsearch instance (https://api-platform.com/docs/core/elasticsearch/#enabling-reading-support), but it seems there is no way to define the username and password set with xpack.

**How to reproduce**  
Protect your ES instance with xpack (https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html).
Try to make a GET (note that it does not matter if the index exists yet or not, it fails when the CollectionDataProvider checks if the index related to the entity exists).

Here is what I had to create my ES Client to write docs in my index before settings xpack security:
```
return ClientBuilder::create()->setHosts([$this->elasticsearchHost])->build();
```
And with xpack security:
```
$client = ClientBuilder::create();
$client->setHosts([$this->elasticsearchHost]);
if (isset($this->elasticsearchUser['username']) && isset($this->elasticsearchUser['password'])) {
    $client->setBasicAuthentication($this->elasticsearchUser['username'], $this->elasticsearchUser['password']);
}

return $client->build();
```

**Comment by WilliamPeralta** [comment]
how resolve this ? i have same problem :/
