### ISSUE TITLE
Filter on entities with inheritance

### ISSUE THREAD

**Issue by sta2m** [api-platform/api-platform#1459]
Hi,

For your information: https://api-platform.com/support => 404.
I don't know if a new feature is needed or not.

I have 2 entities (ProductX and ProductY), herited from Product (inheritance type: JOINED).
I need to add a condition on ProductX or productY field in a filter. But the query builder doesn't show this entities. Joins are added after (by edge ​​loading ?).

How can I filter on this entities?

**Comment by soyuka** [comment]
Create a custom filter see https://api-platform.com/docs/core/filters/#filters
