### ISSUE TITLE
CustomDataProvider vs CustomOperation vs ADR

### ISSUE THREAD

**Issue by valentin74** [api-platform/api-platform#1465]
Hi Team,

Thanks for your wonderfull work on APIPlatform,!
To be sure that I understand the philosophy and the "How to" of apiplatform
I have a User entity, with a referent user attribute (only one so this is a ManyToOne relation)
I want to create an endpoint GET /referent/{id}/users to get all referents of a user
My question is, do I have to:
- Create a DataProvider on User
- Create a CustomOperation
- Create a POST_RESPOND subscriber and erase normal GET users by my own.

What is the best practice?
Thanks a lot for reading

**Comment by soyuka** [comment]
You can use subresources on that property: https://api-platform.com/docs/core/subresources/. There are some DX issues with subresources, we will work to fix it asap see https://github.com/api-platform/core/issues/3458.
