### ISSUE TITLE
Configuring Entity Mapping

### ISSUE THREAD

**Issue by ppounder** [api-platform/api-platform#147]
Apologies, but this may be a really simple question. I'm using v2 RC, and I have installed and mapped all my entities correctly.

I am trying to understand how I can reconfigure the ID mapping of a specific entity. For example a Blog entity. If I wanted to GET a specific Blog it automatically configures the routes to be GET /blog/{id}. But what happens if I have a {slug} field and I want the same route to now be GET blog/{slug}.

I still have the Id field, but I want to be able to use the slug field to retrieve my blog item. A bit like ParamConverter in Symfony where you use options and mapping to link the {slug} in the route as the identifier in the findOneBy.

I have found the [Entity Identifier Case](https://github.com/api-platform/docs/blob/master/core/serialization-groups-and-relations.md) in the documentation (for both v1 and v2), but I wasn't clear on how this worked, and if this was how it is supposed to be done.

Hope you can help.

**Comment by teohhanhui** [comment]
@ppounder I do not believe slugs add any any value when used in the IRI for an API. That said, if you really want to do it, you can add your own decorator for the `PropertyMetadataFactory`:

* `->withIdentifier(false)` for the `id` property
* `->withIdentifier(true)` for the `slug` property

Hopefully that's all the changes necessary. (But let us know if there were more things that you needed to change to make it work.)

**Comment by soyuka** [comment]
As this seem to be a common request, maybe we can consider an annotation/specific metadata for this purpose?

**Comment by dunglas** [comment]
There already is an annotation for that: `@ApiPorperty(identifier=true)`

**Comment by ppounder** [comment]
Hi @dunglas Hope you are well, I was at the Symfony London Workshop with you. 
Final question, would I need to add ````@ApiProperty(identifier=false)```` to the $id field?

**Comment by ppounder** [comment]
Ignore that final question, I added the ````@ApiProperty(identifier=false)```` to the $id field and it now works. Many thanks

**Comment by dunglas** [comment]
Yes @ppounder the annotation loader has a higher priority.
I hope you're doing well.

**Comment by teohhanhui** [comment]
@dunglas Oops, I thought it'd be overridden by the `DoctrineOrmMetadataFactory`, but apparently there's a check.
