### ISSUE TITLE
What about symfony 3 on php 5.6

### ISSUE THREAD

**Issue by rouflak** [api-platform/api-platform#148]
Hi!
I hope I'm not asking a previously answered question.

I've been disappointed when I tried to install the api-platform on a project running in symfony3 and targeting a Debian 8 server with the version 5.6 of PHP installed.

I could not find any version of the platform corresponding to this combination of versions. I'm pretty sure Debian will not come up with the version 7 of PHP for a while.

Is it a conscientious choice? Do you plan to support symfony 3 on PHP 5.6 as most of the servers will come with this version for some time to come?

**Comment by theofidry** [comment]
Hi @rouflak!

The version 1.x should work on PHP 5.6 (it did come out before PHP7 after all). Otherwise 2.x bumps it to PHP7 as it was making a lot of things easier for us.

Debian won't come with php 7 as a *default* installation before some time, but you can install PHP7 on a debian distrib still :)

>Do you plan to support symfony 3 on PHP 5.6 as most of the servers will come with this version for some time to come?

Well I hope people will try to upgrade to PHP7 which should not be too hard unless you've been using PHP functions that have been deprecated for a while already.

**Comment by rouflak** [comment]
Hi @theofidry!
Thanks for answering. 

The version 1.x-dev is limited to symfony/symfony:2.8.*

My aim is to use the api platform on different projects, each on different servers. I won't be able to install PHP 7 on each server. Moreover, the company I'm working for is not ready to upgrade to PHP 7 (you know how many time companies need to upgrade to a major version of PHP ;) ).

I'd really like to have PHP 7 on our servers (my own computer is on it since some time as well) but I really think many companies will hesitate to upgrade to PHP 7 until Debian comes up with this version.

However the API Platform is still a great library! I look forwrad to use it!

**Comment by theofidry** [comment]
>Moreover, the company I'm working for is not ready to upgrade to PHP 7 (you know how many time companies need to upgrade to a major version of PHP ;) ).

Tell them they'll get a 20-40% boost and consume much less resources (so can reduce the number of servers?) 😝 

I believe we could make 1.x compatible with Symfony 3.x, it shouldn't require much work but @api-platform/core-team may prove me wrong.

**Comment by teohhanhui** [comment]
@rouflak TL;DR: Use Docker.

**Comment by Simperfit** [comment]
@teohhanhui If you have someone in the team who can monitor docker in prod, than ok, tell the adminsys to change directly how they are working for years can be hard.

@rouflak You should anyway try to upgrade the maximum of the servers, since php7 is faster.
Anyway, maybe you can try to bump symfony with api-platform v1 and run the tests 👍

**Comment by rouflak** [comment]
@Simperfit 
Thx. I won't be able to upgrade the servers, I don't have permissions on them (that's the work of one my colleague).

I hope we will be able to upgrade to PHP7 soon.

Thx for the advice.

**Comment by teohhanhui** [comment]
I personally wouldn't recommend using v1.

**Comment by Simperfit** [comment]
@rouflak if you can, it will be better to have another server with PHP7 and use V2 since it's better.

**Comment by rouflak** [comment]
Thx all for answering. I still don't have the choice of the php version. It looks like it's much more complicated to have the version of API Platform for both symfony 3 and php 5.6 than I thought.

Using v1 means using symfony 2.8, and we've been using symfony 3 for many monthes now, and we won't get back on symfony 2.8.

**Comment by theofidry** [comment]
@rouflak it's worth checking if making 1.x compatible with 3.x is not just a matter of updating the composer.json, if it's just that, we can definitely release a patch for it

**Comment by Aerendir** [comment]
Maybe this is the right time to update to PHP 7: this is the case for me. Just discovered this app and just today I updated my environment to PHP 7.

It was time to do it, also because it is not so complex and the BC are really few... Also, if you are using Symfony 3... But I understand these may be complex things when working in a team, with the "bureaucracy" :(

**Comment by jayesbe** [comment]
Symfony 2.8 is an LTS. It wont lose support until 2018. Why not make API Platform V2 compatible with the current LTS ?

**Comment by theofidry** [comment]
The idea was not to put to much burden on the team regarding compatibility: PHP 5.6 stills hasn't reached EOL either, neither does Symfony 2.7 or even 2.3 for that matter.

However in your case @jayesbe this may be issue on our end. The core does not require `symfony/symfony`, but only a few components. If you are on Symfony 2.7 or even 2.3, you may use ApiPlatform as long as you upgraded the required components (which doesn't necessarily require to upgrade the whole framework and all its deps).

Also As you can see [here](https://github.com/api-platform/core/blob/master/composer.json#L20-L21), we did lower some deps. Maybe the serializer or property info can be lowered as well.

However, supporting PHP5.6 at this point is out of question for now unless we are given a very good reason to re-consider that point.

**Comment by jayesbe** [comment]
@theofidry Thanks I missed the point of supporting 5.6 since my projects have been upgraded to 7.0.  Though 2.8 LTS itself does support 5.3 by default, which kind of implies that you need to support PHP 5.3 if you are to support 2.8 LTS.  I guess I could make a separate 2.8 Compatibility ticket.

**Comment by dunglas** [comment]
@jayesbe it doesn't imply that. We don't have to support the lower version supported by all our dependencies. PHP 5.3 isn't officially supported anymore by the PHP maintainers (in fact, only PHP 5.6 is still supported: http://php.net/supported-versions.php), we never supported 5.3 and will not do that.

It's time to upgrade to PHP 7. The end of life of PHP 5 is planned for December 31.

**Comment by jayesbe** [comment]
@dunglas I agree completely. If we can't support 5.6 nor am I saying we should.. can we support 2.8 LTS with 7.0?

**Comment by dunglas** [comment]
@jayesbe yes, patches are welcome to add support to PHP 7 to the 1.1 branch (it should not be a difficult work IMO).

**Comment by dunglas** [comment]
However, using API Platform 1 for new projects is strongly discouraged.

**Comment by jayesbe** [comment]
Im working on a 2.8 project and I had to downgrade 2 dependencies.. will create a pull request once I believe there are no issues. Thanks

**Comment by Simperfit** [comment]
@jayesbe Pull Request is welcomed.
