### ISSUE TITLE
Validation failed but entity persisted

### ISSUE THREAD

**Issue by danielchodusov** [api-platform/api-platform#1482]
**API Platform version(s) affected**: 2.5.4

**Description**  
Hi!

I'm having a strange issue with the validation. Let's say I have a entity which is exposed to API with this property:

```
   /**
     * @var string|null
     *
     * @ORM\Column(type="bigint", nullable=true, name="order_number")
     *
     * @Groups({"invoice:read", "invoice:write"})
     *
     * @Assert\Length(max="10")
     */
    protected $orderNumber;
```

I send the PUT request to update the entity with the order number, which longer then max number in the constraint.

```
{"...orderNumber":"10101010101001010" ...}
```

which gives me correct

```
{
    "@context": "/api/contexts/ConstraintViolationList",
    "@type": "ConstraintViolationList",
    "hydra:title": "An error occurred",
    "hydra:description": "orderNumber: This value is too long. It should have 10 characters or less.",
    "violations": [
        {
            "propertyPath": "orderNumber",
            "message": "This value is too long. It should have 10 characters or less."
        }
    ]
}
```

but the entity is updated and persisted into the database with the 10101010101001010 value even though I got the validation error. 

Is it a bug or am I missing something maybe? Thank you.

**Comment by adrientiburce** [comment]
According to symfony doc  the `Length Validator`
> validates that a given string length is between some minimum and maximum value.
I'm not sure but have you tried with an `orderNumber` as a `string`  and not `bigint `

**Comment by danielchodusov** [comment]
To me it seems more like the issue when the validator is fired. I tried another example:

```
    /**
     * @var \DateTime|null
     *
     * @ORM\Column(type="datetime", nullable=true, name="issued_at")
     *
     * @Groups({"invoice:read", "invoice:write"})
     *
     * @Assert\DateTime()
     */
    protected $issuedAt;
```

I send the date in ISO 2020-04-03T00:00:00.000+02:00

And I got this error: This value should be of type string.

But still, the date is persisted into the database, even the error is fired. To me it seems the validator is executed after entity manager is flushed and not before .. or the validation is executed but even though there are some errors doctrine continue to persist the entity.

**Comment by adrientiburce** [comment]
@danielchodusov can you show your entity and your error output, are you sure it comes from the validator and not the date denormalizer ?
Plus I don't understand what do you mean by 
> I send the date in ISO 2020-04-03T00:00:00.000+02:00
you don't send a string ? what is you request ?

**Comment by danielchodusov** [comment]
Sorry for the delay. I find out that the problem was caused by the incorrect priority order of my event listeners. But thank you very much for your effort to help!
