### ISSUE TITLE
Subresources does not work as documented, security does not work at all in subresources

### ISSUE THREAD

**Issue by nightio** [api-platform/api-platform#1485]
**API Platform version(s) affected**: 2.5.4

**Description**  

Cannot change attributes of subresource (e.g. path) using example from documentation.
https://api-platform.com/docs/core/subresources/#using-custom-paths

 e.g. operation name "api_greetings_comments_get_subresource" does not work, but "comments_get_subresource" does. In not sure it is intended (but not well documented) or not.

Security is not invoked at all.
https://api-platform.com/docs/core/subresources/#access-control-of-subresources
e.g. If security is set to "security"="has_role('ROLE_NOT_EXISTING')" I can still access to the endpoint even as anonymous.
A have tested various scenarios with debugs and security was never invoked.

**How to reproduce** 
    Clean distribution of 2.5.4 with following entities:
```
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass="App\Repository\CommentRepository")
 */
class Comment
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $body;

    /**
     * @var Greeting
     * @ORM\ManyToOne(targetEntity="Greeting", inversedBy="comments")
     */
    private $greeting;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(string $body): self
    {
        $this->body = $body;

        return $this;
    }
}
```

```
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiSubresource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * This is a dummy entity. Remove it!
 *
 * @see "api_greetings_comments_get_subresource" does not work at all as subresource operation name
 * @ApiResource(
 *     subresourceOperations={
 *          "comments_get_subresource"={ 
 *              "path"="/greetings/{id}/test_comments",
 *              "security"="has_role('ROLE_NOT_EXISTING')"
 *          }
 *     }
 * )
 * @ORM\Entity
 */
class Greeting
{
    /**
     * @var int The entity Id
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string A nice person
     *
     * @ORM\Column
     * @Assert\NotBlank
     */
    public $name = '';

    /**
     * @var Comment[]
     * @ORM\OneToMany(targetEntity="Comment", mappedBy="greeting")
     * @ApiSubresource()
     */
    public $comments;

    public function getId(): int
    {
        return $this->id;
    }
}

```

**Comment by vincentchalamon** [comment]
Hi @nightio,

Could you try the following configuration?:
```php
/**
 * @ApiResource(
 *     subresourceOperations={
 *          "comments_get_subresource"={ 
 *              "path"="/greetings/{id}/test_comments",
 *              "security"="has_role('ROLE_NOT_EXISTING')"
 *          }
 *     }
 * )
 */
class Greeting
{
    /**
     * @var Comment[]
     *
     * @ApiSubresource()
     */
    public $comments;
}
```
```php
/**
 * @ApiResource(
 *     subresourceOperations={
 *         "api_greetings_comments_get_subresource"={
 *             "access_control"="has_role('ROLE_NOT_EXISTING')"
 *         }
 *     }
 * )
 */
class Comment
```

I managed to configure them properly in an old project: https://github.com/vincentchalamon/zero-dechet/blob/master/api/. Check the configuration between User & Weighing entities:
https://github.com/vincentchalamon/zero-dechet/blob/28f8a253b0894af90cafd75d1d382a09fa8b2855/api/src/Entity/User.php#L80-L82
https://github.com/vincentchalamon/zero-dechet/blob/28f8a253b0894af90cafd75d1d382a09fa8b2855/api/src/Entity/Weighing.php#L34-L36

ApiSubresources may be difficult to use sometimes. There is an RFC proposal to optimize them, but sadly we don't find so much time to work on it: https://github.com/api-platform/core/issues/2706

**Comment by nightio** [comment]
@vincentchalamon 

It's a bit messy but it works, thanks!

**Comment by qdequippe** [comment]
Hi @nightio do you think documentation should be updated related to your issue?
