### ISSUE TITLE
Get all items of an user custom operation

### ISSUE THREAD

**Issue by DBuit** [api-platform/api-platform#149]
Hello,

I got an user entity which has an relation with orders.
I can get my user with: /app_dev.php/users/1

but i want an custom operation to get all orders for a specific user like this:
/app_dev.php/users/1/orders

I made an custom operation action with the following annotations.

```
/**
 * @Route(
 *     name="get_user_orders",
 *     path="/users/{id}/orders",
 *     defaults={"_api_resource_class"=User::class, "_api_item_operation_name"="get_user_orders"}
 * )
 * @Method("GET")
 */
```

In my function i return my users orders but the context is still users so it says it got no items. Is it possible to change the context so i know im returning orders and not users?

Thanks!

**Comment by teohhanhui** [comment]
Perhaps someone else who has used this kind of custom operations can help you better, but what is the exact issues that you're having?

**Comment by soyuka** [comment]
What about doing this on the orders instead if you want orders? 

For example with a filter on the `user` property:
```
/orders?user=x
```

With correct serialization groups, you'd get what you want no?

**Comment by Simperfit** [comment]
@DBuit Do you still have an issue ?
