### ISSUE TITLE
Use API Platform Distribution,can't run.

### ISSUE THREAD

**Issue by sdlyingyong** [api-platform/api-platform#1509]
I use API Platform Distribution. tar. gzfile in docker on centos7 of the virtual machine, but access discovery 444 does not have admin. 

When I try to use GitClone https://github.com/api-platform/api-platform.git
docker-compose build
docker-compose up -d
At that time, the home page can be accessed, 8443 can be accessed, but admin's 444 returns some error messages.

[object Object]

in AdminGuesser (created by AdminGuesserWithError)
in ErrorBoundary (created by AdminGuesserWithError)
in TranslationProvider (created by AdminGuesserWithError)
in AdminGuesserWithError (created by HydraAdmin)
in HydraAdmin (at App.js:4)
in Unknown (at src/index.js:6)

**Comment by thomasmoreaumaster** [comment]
Hi @sdlyingyong,

What do you see if you do : docker-compose logs ?

Thanks,
Thomas.

**Comment by sdlyingyong** [comment]
Thank you for your reply.

There are the following logs about admin:
```
[36madmin_1    |[0m [2K[1G[1myarn run v1.22.4[22m
[36madmin_1    |[0m [2K[1G[2m$ react-scripts start[22m
[36madmin_1    |[0m [34m���[39m [90m���wds���[39m: Project is running at https://172.19.0.9/
[36madmin_1    |[0m [34m���[39m [90m���wds���[39m: webpack output is served from 
[36madmin_1    |[0m [34m���[39m [90m���wds���[39m: Content not from webpack is served from /usr/src/admin/public
[36madmin_1    |[0m [34m���[39m [90m���wds���[39m: 404s will fallback to /
[36madmin_1    |[0m [2J[3J[H[36mStarting the development server...[39m
[36madmin_1    |[0m [36m[39m
[36madmin_1    |[0m [2J[3J[H[32mCompiled successfully![39m
[36madmin_1    |[0m 
[36madmin_1    |[0m You can now view [1madmin[22m in the browser.
[36madmin_1    |[0m 
[36madmin_1    |[0m   [1mLocal:[22m            https://localhost:[1m3000[22m
[36madmin_1    |[0m   [1mOn Your Network:[22m  https://172.19.0.9:[1m3000[22m
[36madmin_1    |[0m 
[36madmin_1    |[0m Note that the development build is not optimized.
[36madmin_1    |[0m To create a production build, use [36myarn build[39m.
[36madmin_1    |[0m 
```


All logs are here.
[docker-compose-log.log](https://github.com/api-platform/api-platform/files/4519870/docker-compose-log.log)

**Comment by sdlyingyong** [comment]
When I installed github version on ubuntu on the virtual machine, I found that port 444 can be accessed locally and admin works correctly. 
However, when I access from the physical computer through ip address, admin displays the above information.
Is there any configuration that needs to be modified ?

**Comment by J3m5** [comment]
I'm facing the same issue.

**Comment by Taark** [comment]
> I'm facing the same issue.
> 
> [UPDATE]
> 
> It seems to be related to issue #1410.
> I spotted the cert error in the logs and running
> 
> ```
> docker-compose down -v
> docker-compose up -d
> ```
> 
> solved the issue.

it work to me too

**Comment by dunglas** [comment]
Fixed by switching to Caddy server.
