### ISSUE TITLE
Demo on official page is broken https://demo.api-platform.com/

### ISSUE THREAD

**Issue by Mausino** [api-platform/api-platform#1516]
**Description**  

If you go on official page for front end demo.. you will see that is broken
See the screenshot.. tested on chrome, edge, mozilla

![Snímka obrazovky z 2020-04-28 11-24-21](https://user-images.githubusercontent.com/5773777/80471193-5cbe2200-8943-11ea-84aa-15134cae4534.png)

**Comment by GRUXXKi** [comment]
Working really fine for me.
