### ISSUE TITLE
When the version 2 is going to be out?

### ISSUE THREAD

**Issue by samusenkoiv** [api-platform/api-platform#153]
When the version two is going to be out?

**Comment by dunglas** [comment]
Probably this week.

**Comment by bpolaszek** [comment]
Is there a changelog somewhere about what happened between v1 and v2?

**Comment by dunglas** [comment]
Take a look at https://github.com/api-platform/core/blob/master/CHANGELOG.md and https://dunglas.fr/2016/05/the-first-alpha-of-api-platform-2-0-is-available/.

**Comment by bpolaszek** [comment]
Perfect!

**Comment by andreas-glaser** [comment]
It's been two weeks since the question was raised. Any news on the release date?
Also where can I find the beta documentation for v2?

**Comment by andreas-glaser** [comment]
Found the docs.. sorry for the hasty question ;)
https://github.com/api-platform/docs/blob/master/distribution/index.md

**Comment by Simperfit** [comment]
@andreas-glaser We deployed the docs on https://api-platform.com

**Comment by Simperfit** [comment]
RC4 is out, if there are no blocking bug, it will be the stable release !

**Comment by magnus-eriksson** [comment]
Now RC7 is out on packagist. Any more ETA on a stable release?

**Comment by soyuka** [comment]
We made a few last-minute breaking changes but it's really close now ;).

**Comment by teohhanhui** [comment]
Sounds alright to me.

**Comment by Simperfit** [comment]
Is it ! ;)
