### ISSUE TITLE
Iconv fails to transform UTF-8 to ASCII/TRANSLIT

### ISSUE THREAD

**Issue by amari-at4** [api-platform/api-platform#1532]
**API Platform version(s) affected**: 2.5.5

**Description**  
When try to use the transliteration with iconv throw this notice "php Notice: iconv(): Wrong charset, conversion from `UTF-8' to `ASCII//TRANSLIT' is not allowed" and Api Platform throws an Exception

**How to reproduce**  
```
$text="Texto en español"
$new_text = iconv('UTF-8', 'ASCII//TRANSLIT', $text);
```
**Possible Solution**  
As commented [here](https://github.com/nunomaduro/phpinsights/issues/43#issuecomment-498108857) it's an Alpine bug. to fix this it's necessary to add to the Dokerfile this lines:

```
RUN apk add --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/community/ --allow-untrusted gnu-libiconv
ENV LD_PRELOAD /usr/lib/preloadable_libiconv.so
```

**Comment by dunglas** [comment]
Thanks for the report and the workaround! I suggest to wait for this package to be marked as stable by Alpine before we change this.
