### ISSUE TITLE
Fix: Varnish in Helm/Kubernetes requires fixed name for nginx/api

### ISSUE THREAD

**Issue by silverbackdan** [api-platform/api-platform#1534]
**Description**  
In the current setup, the API service name must be fixed in order for the Varnish configuration to work. With some minor adjustments we can make the varnish configuration based on environment variables.

**Example** 

Updated Dockerfile (sorry for some other differences in the CMD and paths) 
```dockerfile
FROM varnish:${VARNISH_VERSION} AS api_platform_varnish

RUN \
  apt-get update \
  && apt-get -y install gettext-base \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY _docker/varnish/conf/default.vcl /tmp/varnish/conf/default.vcl
COPY _docker/varnish/persist-environment.sh /usr/local/bin/persist-environment

RUN chmod +x /usr/local/bin/persist-environment
ENTRYPOINT ["persist-environment", "docker-varnish-entrypoint"]

CMD ["varnishd", "-F", "-f", "/etc/varnish/default.vcl", "-p", "http_resp_hdr_len=65536", "-p", "http_resp_size=98304", "-p", "workspace_backend=512K"]
```

persist-environment.sh
```sh
#!/bin/sh
set -e
mkdir -p /usr/local/etc/varnish
envsubst '${UPSTREAM},${UPSTREAM_PORT},${PHP_SERVICE}' < /tmp/varnish/conf/default.vcl > /etc/varnish/default.vcl
exec "$@"
```

default.vcl
```vcl
vcl 4.0;

import std;

backend default {
  .host = "${UPSTREAM}";
  .port = "${UPSTREAM_PORT}";
  # Health check
  #.probe = {
  #  .url = "/";
  #  .timeout = 5s;
  #  .interval = 30s;
  #  .window = 5;
  #  .threshold = 3;
  #}
}

# Hosts allowed to send BAN requests
acl invalidators {
  "localhost";
  "${PHP_SERVICE}";
  # local Kubernetes network
  "10.0.0.0"/8;
  "172.16.0.0"/12;
  "192.168.0.0"/16;
}

... etc.
```

Once that's done it's jus a case of adjusting the docker-compose yaml and then passing the environment variables in the Helm chart.

As a side note, it'd be nice if the Helm charts were updated to include Vulcain too.

I have a template project where I am implementing all of this so once it is all working I can create a PR if it's something you'd like to have in this template as well.

**Comment by dunglas** [comment]
Nice! PR very welcome :).

**Comment by silverbackdan** [comment]
Great, I'll get on it as soon as poss. It's all working in my repo now so should be OK. I'll do another PR to put Vulcain in the helm charts too while I'm there.

**Comment by silverbackdan** [comment]
No longer relevant with current build. If Varnish is reintroduced (which I have done in my API Platform implementation with Caddy), we could do this.
