### ISSUE TITLE
Serialization Groups

### ISSUE THREAD

**Issue by ppounder** [api-platform/api-platform#155]
Hi there,

Quick question, I've tried looking through the documentation (including 2.0) but struggling to find the answer.

I have serialization groups set up on my Entity. This displays the required fields I want to see on my ````GET```` request, however I want to be able to display different fields on a custom ````GET```` Action that I've set up.

For example in the case of a Book entity that has a OneToMany to a Review Entity. In my out of the box ````GET```` request I have the serialization groups so that I don't return any of the Reviews. 

But I want to set up a Custom Action with say a route of ````book/1/reviews```` that brings back a few of the Book fields (name, isbn) and all the reviews linked. I know I can setup Groups per method type, but wondered if there was a way of setting a serialization group per GET request (such as one for the standard CRUD method and one for a Custom Action).

Hope that makes sense.

Kind regards
Paul

**Comment by teohhanhui** [comment]
The custom normalization / denormalization context is per-operation. So you can specify different serializer groups to use for each custom operation.

**Comment by teohhanhui** [comment]
See https://github.com/api-platform/docs/blob/master/core/serialization-groups-and-relations.md#using-different-serialization-groups-per-operation

**Comment by ppounder** [comment]
Many thanks,

In that example though it's on a per itemOperation, so how would I distinguish a normalization context between my standard GET itemOperation and a GET custom operation that I have created in an Action? 

Can I apply ````"normalization_context"={"groups"={"custom"}}```` against where I set my custom operation? For example:

````"special"={"route_name"="book_special", "normalization_context"={"groups"={"custom"}}}````

**Comment by soyuka** [comment]
yes, see [here](https://api-platform.com/docs/core/serialization-groups-and-relations#using-different-serialization-groups-per-operation)

```
/**
 * @ApiResource(
 *     attributes={"normalization_context"={"groups"={"get"}}},
 *     itemOperations={
 *          "get"={"method"="GET"},
 *          "put"={"method"="PUT", "normalization_context"={"groups"={"put"}}}
 *     }
 * )
 */
```

**Comment by ppounder** [comment]
Thanks @soyuka @teohhanhui
