### ISSUE TITLE
Problem with 'docker-compose up'

### ISSUE THREAD

**Issue by sh4ka** [api-platform/api-platform#156]
After doing:
`composer create-project api-platform/api-platform bookshop-api`
I try to do:
`docker-compose up`
And I get:
`ERROR: The Compose file './docker-compose.yaml' is invalid because:
mysql.environment.MYSQL_ALLOW_EMPTY_PASSWORD contains true, which is an invalid type, it should be a string, number, or a null`
Using docker-compose v1.8.1.
I am pretty new to docker-compose so I dont know how to fix this yet.

**Comment by sh4ka** [comment]
Using the latest configuration provided in the 'master' branch seems to solve this problem.
database:
    image: mysql
    environment:
        MYSQL_ROOT_PASSWORD: changeme
        MYSQL_DATABASE: api_platform
        MYSQL_USER: api_platform
        MYSQL_PASSWORD: api_platform

**Comment by sh4ka** [comment]
The next command describe in the docs, docker-compose run web composer install --no-interaction:
`ERROR: Cannot start service web: oci runtime error: exec: "composer": executable file not found in $PATH`
Where is the composer binary installed?

**Comment by dunglas** [comment]
Maybe not clear enough in the doc, but you must not use `composer create-project` directly if you want to use Docker. Download the zip and run `docker-compose up` OR use `composer create-project`.

**Comment by sh4ka** [comment]
I'll try again this evening, but this certainly sounds like a big case of pebkac.

**Comment by sh4ka** [comment]
Pebcak.
