### ISSUE TITLE
Attributes "Order" ignored

### ISSUE THREAD

**Issue by bettinz** [api-platform/api-platform#1563]
**API Platform version(s) affected**: 2.5.6

**Description**  
If I add ``attributes={"order"={"name": "ASC"}},`` in `@Apiresource` this is totally ignored and the entity is still ordered by `ID`

**How to reproduce**  
Add ``attributes={"order"={"name": "ASC"}},`` in your entity and check the entity with a GET on the collections with swagger

**Comment by wmfelipe** [comment]
I have the same issue, but I'm trying to use the YAML format exacly how it is described here:
https://api-platform.com/docs/core/default-order/#overriding-default-order 

Any idea?

**Comment by oliveiraev** [comment]
> **API Platform version(s) affected**: 2.5.6
> 
> **Description** If I add `attributes={"order"={"name": "ASC"}},` in `@Apiresource` this is totally ignored and the entity is still ordered by `ID`
> 
> **How to reproduce** Add `attributes={"order"={"name": "ASC"}},` in your entity and check the entity with a GET on the collections with swagger

I'm facing the exact same issue.
How did you fix it?
