### ISSUE TITLE
Error in first step of GraphQL setup

### ISSUE THREAD

**Issue by solariox** [api-platform/api-platform#1572]
**API Platform version(s) affected**: 
api-platform/api-pack v1.2.2       
api-platform/core v5.6 
webonyx/graphql-php v14.0.0 

**Description**  
I've tried to install API platform + graphQL support. 
I followed every steps from the documentation: 
`
composer req api &&  composer req webonyx/graphql-php && bin/console cache:clear
`
When i'm going on localhost/api/graphql, it end to a 500 error:
`Attempted to load class "Debug" from namespace "GraphQL\Error"`
in `vendor/api-platform/core/src/GraphQl/Action/EntrypointAction.php (line 49) `
We are calling class 'GraphQL\Error\Debug;' which doesn't exist : 
![Capture d’écran de 2020-06-25 10-42-57](https://user-images.githubusercontent.com/27417057/85686983-bedf9d00-b6d0-11ea-80f3-4680379116d0.png)

**How to reproduce**  
Just follow basic installation steps 

**Possible Solution**  
After looking on webonyx last release : 

> Renamed `GraphQL\Error\Debug` to `GraphQL\Error\DebugFlag`. 

cf : https://github.com/api-platform/api-platform/issues/new?template=1_Bug_report.md
I guess rename apiplatform's calls to  webonyx/graphql-php library would fix it, but it looks like last release insert more breaking changes

**Comment by alanpoulain** [comment]
Hello.
It's already fixed here: https://github.com/api-platform/core/pull/3621.
Not released yet.
