### ISSUE TITLE
normalization context don't work on symfony v5.1.99

### ISSUE THREAD

**Issue by redha-ax2lan** [api-platform/api-platform#1576]
**API Platform version(s) affected**: x.y.z

**Description**  

when i make my normalization context on symfony 5.1.99 in api ressource like that : 
normalizationContext={"groups"={"read:question"}}
my model disapear in the api documentation and the api return 200 code but don't return element from database, only context from hydra

**How to reproduce**  

normalizationContext={"groups"={"read:question"}} in api ressource and @Groups in a entity.
and  serializer: { enable_annotations: true } in config/package/framework.yamls

**Possible Solution**  

i think it's cause it's a newest version.
**Additional Context**  

this is worked on symfony 4.4
my php version is 7.3.14
![api-platform-bug](https://user-images.githubusercontent.com/54364242/86580238-badc3680-bf7e-11ea-9d5e-d6c9ccccd924.PNG)

**Comment by kelvin2200** [comment]
did you add the same normalization group to every property in your entity?

**Comment by redha-ax2lan** [comment]
I tested in both cases and it doesn't work, with all property in the same group and with 2 propertie in the group and here is only one group in this entity.

**Comment by kelvin2200** [comment]
from the little you provided, the route seems to be returning the expected result. Can you post the entire entity here? I think you are messing up somewhere with the denormalization groups.

**Comment by redha-ax2lan** [comment]
I do not have denormalization groups just a normalization, it is not necessary to create a group. my code worked on symfony 5.0 and 4.4

**Comment by kelvin2200** [comment]
well, if you don't want to post your entity, I don't know how to help. I'm running 5.1 and I have no issues. Do you have custom normalizers defined?

**Comment by redha-ax2lan** [comment]
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\QuestionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ApiResource(normalizationContext={"groups"={"read:quest"}}, collectionOperations={"get"}, itemOperations={"get"})
 * @ORM\Entity(repositoryClass="App\Repository\QuestionRepository")
 */
class Question
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"read:quest"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"read:quest"})
     */
    private $libelle;

    /**
     * @ORM\OneToMany(targetEntity=Reponse::class, mappedBy="idQuestion", orphanRemoval=true)
     * @Groups({"read:quest"})
     */
    private $reponses;

    public function __construct()
    {
        $this->reponses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    /**
     * @return Collection|Reponse[]
     */
    public function getReponses(): Collection
    {
        return $this->reponses;
    }

    public function addReponse(Reponse $reponse): self
    {
        if (!$this->reponses->contains($reponse)) {
            $this->reponses[] = $reponse;
            $reponse->setIdQuestion($this);
        }

        return $this;
    }

    public function removeReponse(Reponse $reponse): self
    {
        if ($this->reponses->contains($reponse)) {
            $this->reponses->removeElement($reponse);
            // set the owning side to null (unless already changed)
            if ($reponse->getIdQuestion() === $this) {
                $reponse->setIdQuestion(null);
            }
        }

        return $this;
    }
}
this is my entity, and don't have custom the normalizers

**Comment by redha-ax2lan** [comment]
`<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\QuestionRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ApiResource(normalizationContext={"groups"={"read:quest"}}, collectionOperations={"get"}, itemOperations={"get"})
 * @ORM\Entity(repositoryClass="App\Repository\QuestionRepository")
 */
class Question
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     * @Groups({"read:quest"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Groups({"read:quest"})
     */
    private $libelle;

    /**
     * @ORM\OneToMany(targetEntity=Reponse::class, mappedBy="idQuestion", orphanRemoval=true)
     * @Groups({"read:quest"})
     */
    private $reponses;

    public function __construct()
    {
        $this->reponses = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getLibelle(): ?string
    {
        return $this->libelle;
    }

    public function setLibelle(string $libelle): self
    {
        $this->libelle = $libelle;

        return $this;
    }

    /**
     * @return Collection|Reponse[]
     */
    public function getReponses(): Collection
    {
        return $this->reponses;
    }

    public function addReponse(Reponse $reponse): self
    {
        if (!$this->reponses->contains($reponse)) {
            $this->reponses[] = $reponse;
            $reponse->setIdQuestion($this);
        }

        return $this;
    }

    public function removeReponse(Reponse $reponse): self
    {
        if ($this->reponses->contains($reponse)) {
            $this->reponses->removeElement($reponse);
            // set the owning side to null (unless already changed)
            if ($reponse->getIdQuestion() === $this) {
                $reponse->setIdQuestion(null);
            }
        }

        return $this;
    }
}
`

**Comment by redha-ax2lan** [comment]
this is my entity i don't have custom normalizer

**Comment by romainderocle** [comment]
did you find a solution ?

**Comment by redha-ax2lan** [comment]
not really, I downgraded symfony to 5.0 and it works, I haven't tried again since

**Comment by dParadiz** [comment]
Try to run `./bin/console cache:clear`

**Comment by redha-ax2lan** [comment]
there is no cache that does not fix the bug

**Comment by TadjerouniMohamedAdel** [comment]
for me cache:clear solved the issue
symfony :5.1

**Comment by redha-ax2lan** [comment]
after trying it works! thanks for the help !

**Comment by Tchekda** [comment]
Worked also for me !!
Is there a way to disable this cache in dev environment ?
Thanks

**Comment by angelomelonas** [comment]
@dParadiz clearing the cache solved my problem after 3 hours of wondering why a simple `get` was not returning the entity data!

**Comment by gediminasnn** [comment]
Same problem but with post operation, cache clearing does not fix it...

**Comment by gediminasnn** [comment]
> Same problem but with post operation, cache clearing does not fix it...

Bus somewhy if I add write group to setter method it magically works...

```
    /**
     * The description of the cheese as raw text.
     * @Groups({"write"})
     */
    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

```

**Comment by NouraToukabriACF** [comment]
> > Same problem but with post operation, cache clearing does not fix it...
> 
> Bus somewhy if I add write group to setter method it magically works...
> 
> ```
>     /**
>      * The description of the cheese as raw text.
>      * @Groups({"write"})
>      */
>     public function setFirstName(string $first_name): self
>     {
>         $this->first_name = $first_name;
> 
>         return $this;
>     }
> ```

Worked for me!! thank youu

**Comment by abdojulari** [comment]
> did you add the same normalization group to every property in your entity?

In my own case, I did, out of 5, only two appeared in the api documentation.
