### ISSUE TITLE
PHP7: behatch/contexts dev-master requires php ~5.4 -> your PHP version (7.1.0RC3) does not satisfy that requirement.

### ISSUE THREAD

**Issue by Aerendir** [api-platform/api-platform#158]
I've simply run

```
MacBook-Pro-di-Aerendir:_Tests Aerendir$ composer create-project api-platform/api-platform api-platform
Installing api-platform/api-platform (v1.0.0)
  - Installing api-platform/api-platform (v1.0.0)
    Downloading: 100%         

Created project in api-platform
Class SymfonyStandard\Composer is not autoloadable, can not call post-root-package-install script
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for behatch/contexts dev-master -> satisfiable by behatch/contexts[dev-master].
    - behatch/contexts dev-master requires php ~5.4 -> your PHP version (7.1.0RC3) does not satisfy that requirement.
```

I've tried the Docker version and all worked well, but, as I have never used Docker before and as I had some issue (for example, configuring the right PHP version in PHPStorm - too complex for the moment for me) I opted for the pure `composer` installation.

But this is the error I receive. Are you aware of this? How can I solve the problem without touching the source code yet before I start?

**Comment by dunglas** [comment]
You need to install the v2 for PHP7:

composer create-project api-platform/api-platform=v2.0.0-rc.4 api-platform

**Comment by Aerendir** [comment]
Ok, perfect, is also a RC, so, it is sufficient stable? I'm experimenting with the platform: I like it a lot!!

**Comment by dunglas** [comment]
Yes we're in the process of releasing the v2.0.0 stable. And thanks for your feedback!

**Comment by Aerendir** [comment]
Ok, just installed... I'll play with it... I hope will very deep play with it!!! And from what I've seen so far, this is a really great application and it will save me a lot of time, give me a direction on the APIs and provide me with very strong guidance about standards! Many thanks to all the team!
