### ISSUE TITLE
Custom subresource path doesn't work

### ISSUE THREAD

**Issue by bastoune** [api-platform/api-platform#1581]
**API Platform version(s) affected**: 2.5.6
**Description**  
Following this documentation: `https://api-platform.com/docs/core/subresources/#using-custom-paths`
I try to override the path (and security, and requirements) of a subresource.
It works for the security, but not for path (and so requirements).

**How to reproduce**  
https://github.com/bastoune/api-platform-issue-1581

Having this route with `debug:router` :
`api_organizations_users_get_subresource   GET      ANY      ANY    /v2/organizations/{id}/users.{_format}`
and this annotation :
```
 *      subresourceOperations={
 *          "api_organizations_users_get_subresource"={
 *              "method"="GET",
 *              "path"="/BLABLABLA/organizations/{organization_id}/users",
 *              "requirements"={"organization_id": StringHelper::UUIDv4Regex},
 *              "security"="is_granted('readOrganization', organization_id)"
 *          }
 *      }
```
I can put this annotation in the `User` or the `Organization` entity, I have the same result.

The security works but not the rest.

If I remove the security, it doesn't work anyway.

**Comment by bastoune** [comment]
Here is a very small project to reproduce the code :
https://github.com/bastoune/api-platform-issue-1581

You will find that the path isn't changed, the is even a Web Server to see the SwaggerUi to check.

**Comment by vipulwairagade** [comment]
Try adding `@ApiSubresource` annotation to `$organisations` property

**Comment by bastoune** [comment]
> 
> 
> Try adding `@ApiSubresource` annotation to `$organisations` property

The subresource is users of the organization, not the contrary.

**Comment by plfort** [comment]
Try with "users_get_subresource" as operation name (instead of "api_organizations_users_get_subresource").
https://github.com/api-platform/docs/issues/1109

This PR was merge https://github.com/api-platform/docs/pull/370 but this commit revert the changes https://github.com/api-platform/docs/commit/b8304bc4a32ac16d6e71997a8b0682187caaa473

**Comment by bastoune** [comment]
Thanks, I won't use this feature since it seems not to be stable.
Maybe the doc shall be changed ?

**Comment by p5yk0** [comment]
For those looking for information, I managed to make it work on my projet.

**You need to declare the custom path on the parent entity, in your case it's Organisation.**
Exemple using yaml :
```
subresourceOperations:
   users_get_subresource:
      path: "/BLABLABLA/organizations/{organization_id}/users"
```
_Notice that you need to remove the prefix "api_organizations_" from the operation name.


**Then you add your security and normalization configuration on the child entity, in your case it's User.**
Still using yaml : 
```
subresourceOperations:
   api_organizations_users_get_subresource:
      security: "is_granted('readOrganization', organization_id)"
      normalization_context: { groups: [ 'my-group' ] }
```
