### ISSUE TITLE
GraphQL

### ISSUE THREAD

**Issue by ngrdanjski** [api-platform/api-platform#1589]
After enable Graphql

Attempted to load class "Debug" from namespace "GraphQL\Error".
Did you forget a "use" statement for e.g. "Symfony\Component\ErrorHandler\Debug" or "Doctrine\Common\Util\Debug"?

in class EntrypointAction

**Comment by alanpoulain** [comment]
Fixed by https://github.com/api-platform/core/pull/3621.
You need to either:
- wait for a new version to be released
- use the dev version of the `2.5` branch
- downgrade webonyx/graphql-php to a previous version (`0.13`)
