### ISSUE TITLE
[QUESTION] Support MongoDB ODM

### ISSUE THREAD

**Issue by ad3n** [api-platform/api-platform#159]
It is support for ODM?

**Comment by theofidry** [comment]
MongoDB is supported if you are using Doctrine ODM eventually combined with https://github.com/dunglas/doctrine-json-odm. @dunglas can you confirm?

**Comment by dunglas** [comment]
There is a pending PR for MongoDB support: https://github.com/api-platform/core/pull/461

The implementation works but it needs review and more tests. Any help welcome! /cc @samvdb @Simperfit

**Comment by ad3n** [comment]
@dunglas : :+1: ok i will waiting to merge

**Comment by Aerendir** [comment]
@ad3n maybe a test of the PR is better before merging... if you use mongo it may be helpful your opinion about eventual bugs or issues...
