### ISSUE TITLE
can not install messenger component with symfony 4.2

### ISSUE THREAD

**Issue by nourheine** [api-platform/api-platform#1591]
I wanted to install messenger component with symfony 4.2 , i got this error:
 Could not find package symfony/messenger in a version matching 4.2.

after doing my research , i have seen a previous issue    https://github.com/api-platform/api-platform/issues/1169  .
i tried this solution provided by teohhanhui:
" Yes, you need to add "symfony/messenger": "^4.2" to the composer.json manually and do composer update symfony/* (I think)
composer require is only appropriate for simple cases."

now i get this error:
"The requested package symfony/messenger ^4.2 exists as symfony/messenger[4.1.x-dev, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9] but these are rejected by your constraint.
"
i will appreciate any help guys.

**Comment by rugolinifr** [comment]
I'm not the best with composer's version management, but following the error message, i assume there is no package symfony/messenger >=4.2 and <5 ([which is equivalent to "^4.2"](https://getcomposer.org/doc/articles/versions.md#caret-version-range-)). 

Try to use "^4.1"  instead and run composer update once more ?

**Comment by nourheine** [comment]
I tried with messenger version  "^4.1" , it worked for me, thank you

**Comment by rugolinifr** [comment]
great, can you close the issue please ?
