### ISSUE TITLE
Custom itemOperation with provider

### ISSUE THREAD

**Issue by lamb0tiana** [api-platform/api-platform#1593]
**API Platform version(s) affected**: 2.5.6

**Description**  
I want to get an item by accessing with some url like **/api/user/account** and I'm get some error like
 **"Invalid identifier value or configuration."**, it seems that the id is a mandatory [here](https://github.com/api-platform/core/blob/master/src/DataProvider/OperationDataProviderTrait.php#L89) for an item operation but isn't there anyway to override this. ? So I implemented an service with **api_platform.item_data_provider** but the error still there.
Is there a way to do that efficiently ? thank you.

**Possible Solution**  
Define the operation into collection operation but I think it shouldn't be like that cause it's about an item. so

**Comment by rugolinifr** [comment]
I'm not sure i get it.

Do you want to create an item operation with a custom data provider without supplying an ID within the url (**/api/user/account** instead of  **/api/user/account/{id}** ?) ? 

I think it's not possible... As you can see [here](https://api-platform.com/docs/core/data-providers/#custom-item-data-provider), the public method getItem() is called with a $id argument. You define this ID using the **@ApiProperty(identifier=true)** within your entity.

As you workaround, i suggest you to use a collection operation instead, which returns a collection of one and only one element.

Or you can still use an item operation, and implementing an useless id, so **/api/user/account/1** == **/api/user/account/2** and so on.

Or worst, use a Symfony controller, but it is highly discouraged.

**Comment by lamb0tiana** [comment]
thanks for your quick reply,
yeah you got it,


``` 
 *         "user_account"={
 *              "method"="get",
 *              "path"="/user_account/",
 *              "controller"="UserAccountApi::class",
 *              "normalization_context"={"groups"={"user:account"}},
 *              "openapi_context"={
 *                 "summary" = "Compte d'utilisateur",
 *                      "tags" ={"UserAccount"},
 *                      "parameters" = false,
 *                  "responses"={
 *                      "200"={
 *                              "content" = { "application/json" = { "schema"={ "$ref"= "#/components/schemas/User-user::account"} }
 *                      }
 *                  }
 *              }
 *               },
 *              "pagination_enabled" = false
 *          }
```

and  dd("here i am") in my __invoke controller

so it returns
```
"type": "https:\/\/tools.ietf.org\/html\/rfc2616#section-10",
  "title": "An error occurred",
  "detail": "Invalid identifier value or configuration.",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "\/var\/www\/api\/vendor\/api-platform\/core\/src\/EventListener\/ReadListener.php",
      "line": 112,
      "args": []
    },
```

It from [here](https://github.com/api-platform/core/blob/master/src/DataProvider/OperationDataProviderTrait.php#L89)


so I try to debug by setting id value, and strangely my customerprovider runs, 

so apparently, the OperationDataProvider take over the others defined customProvider,


```
  App\Provider\UserAccountProvider:
    tags:
      - { name: 'api_platform.doctrine.orm.item_data_provider', priority: 1}
```

**Comment by rugolinifr** [comment]
So, it is ok to you ?

i've found another way to to do it.

Within you User entity : 
```
 * @ApiResource(
 *      itemOperations={
 *          "my_account" = {
 *              "method" = "get",
 *              "read" = false,
 *              "path" = "/user/account",
 *              "controller" = MyAccountController::class,
 *              "security" = "is_granted('ROLE_USER')"
 *          }
 * }
```

And now the controller :
```
<?php


namespace App\Controller;


use Symfony\Component\Security\Core\Security;

class MyAccountController
{
    /** @var Security */
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }

    public function __invoke()
    {
       // or whatever you want, in fact
        return $this->security->getUser();
    }
}
```
With that code, and if i understand weel xhat you want to do, you no longer need custom data provider.

The trick is that the **read** attribute allow you to skip your data provider, so nothing is retrievied from.
So the **invoke()** method take no parameter.

Note that inside the swagger view, you still need to provide an id in order to "try it out", but check the curl command and you will see that there is no ID within the URL.

**Comment by lamb0tiana** [comment]
@rugolinifr, no it's not ok,
as I said, the id param is a mandatory in item operation,but in my case, I don't want that id params,

**Comment by lamb0tiana** [comment]
same case as #337 but unfortunately, with latest version, it's won't works :)

**Comment by rugolinifr** [comment]
then my previous answer should solve your problem https://github.com/api-platform/api-platform/issues/1593#issuecomment-660490475

**Comment by lamb0tiana** [comment]
@rugolinifr , unfortunately, nope,
I compare your purpose with what I [did](https://github.com/api-platform/api-platform/issues/1593#issuecomment-660488111) and put the missed params , but it returns the same error.

**Comment by rugolinifr** [comment]
i don't know what to say.

i just tried it with a 2 years old project and a newly created one, and it works fine.
your error said that the ReadListener is called, and that should not happened with **read = false**.

try to remove yours additional  annotations and send some screenshots of your code ?

**Comment by lamb0tiana** [comment]
Sorry for lat response, so here is the screenshots
![a](https://user-images.githubusercontent.com/12131782/87861010-d0703980-c94a-11ea-92ff-28eb4cfcd43f.png)
![b](https://user-images.githubusercontent.com/12131782/87861014-d5cd8400-c94a-11ea-9675-483df6f26762.png)

for now, I think it's about how doctrine could convert that item, ? so how do you suggest please, thanks.

**Comment by rugolinifr** [comment]
May i see the UserAccount::__invoke() method ?

**Comment by lamb0tiana** [comment]
@rugolinifr , here is it, I just put a dd. 

![a](https://user-images.githubusercontent.com/12131782/87866909-fbc94780-c98f-11ea-8739-b708813683fd.png)

**Comment by rugolinifr** [comment]
[As i said before](https://github.com/api-platform/api-platform/issues/1593#issuecomment-660490475), the method should take no parameter

**Comment by lamb0tiana** [comment]
> [As i said before](https://github.com/api-platform/api-platform/issues/1593#issuecomment-660490475), the method should take no parameter

ah yeah, sorry, 
thank you very much, I close this.
