### ISSUE TITLE
Improve Support for Custom Voter Security by passing the subject from graphql context

### ISSUE THREAD

**Issue by nicomuschert** [api-platform/api-platform#1596]
**Description**  
"object" Support for "@ApiResource -> graphql -> .. -> is_granted(.., object)"

Another guy hit the same problem:
https://stackoverflow.com/questions/58610094/api-platform-symfony-security-voter-subject-null-when-entity-implements-interfac

**Example**  

> @ApiResource(graphql={
>   "create"={"security"="is_granted('USER_CREATE', object)"}
> }))

** Relatet Docs **
https://api-platform.com/docs/core/graphql/#security
https://api-platform.com/docs/core/security/#hooking-custom-permission-checks-using-voters

**Comment by rugolinifr** [comment]
I'm not sure this is because of graphQL, but because of api-platform lifecycle instead.

Can you try **"security_post_denormalize"** instead of **"security"** ?

**Comment by nicomuschert** [comment]
Works!
Thank you. :)

Does ist make sense to mention it at the graphql security documentation?

**Comment by rugolinifr** [comment]
Let say that it is implicitly mentioned [here](https://api-platform.com/docs/core/graphql/#security):

> To add a security layer to your queries and mutations, follow the security documentation.

Then, **security_post_denormalize** is explained [here](https://api-platform.com/docs/core/security/#executing-access-control-rules-after-denormalization).

I don't know. Having an example on the graphql page is fair, but perhaps it is redundant. Not my job to decide anyway :p

**Comment by nicomuschert** [comment]
Totally okay from my side. Now it is documented at the issues. :-D
Thanks. Have a good Time!
