### ISSUE TITLE
Throwing GraphQL validation exceptions always result in an internal server error

### ISSUE THREAD

**Issue by tk-za** [api-platform/api-platform#1598]
If I throw a ValidationException in a GraphQL resolver or data persister, my response is always an internal server error.

Given the following sample mutation:

    mutation {
      updateUser(input: {
        id:"/api/users/22",
        plainPassword: "polly",
        clientMutationId:"dufiafghiuhft9qyf9g"
      }) {
        clientMutationId,
      }
    }

Using a simple @Assert in my User entity results in the following response:

    {
      "errors": [
        {
          "message": "plainPassword: This value is too short. It should have 6 characters or more.",
          "extensions": {
            "category": "graphql"
          },
          "locations": [
            {
              "line": 33,
              "column": 3
            }
          ],
          "path": [
            "updateUser"
          ]
        }
      ],
      "data": {
        "updateUser": null
      }
    }

But if I throw a ValidationException in either my resolver or data persister, I get the following response:

    {
      "errors": [
        {
          "debugMessage": "plainPassword: This value is too short. It should have 6 characters or more.",
          "message": "Internal server error",
          "extensions": {
            "category": "internal"
          },
          "locations": [
            {
              "line": 33,
              "column": 3
            }
          ],
          "path": [
            "updatePasswordUser"
          ],
          "trace": [
          	...
          ]
      }
    }

Is this the correct/expected behaviour? And if so, what is the mechanism one should use to throw a set of validation exceptions that will result in the expected output (as per the first case) rather than receiving an "Internal server error".

**Comment by alanpoulain** [comment]
Please use the `master` version and read https://api-platform.com/docs/master/core/graphql/#formatting-exceptions-and-errors.

**Comment by tk-za** [comment]
Thank you. That additional documentation is very useful.

**Comment by tk-za** [comment]
The revised documentation is interesting, but it doesn't work as described:

> For some specific exceptions, built-in custom exception normalizers are also used to add more information. It's the case for a HttpException for which the status entry will be added under extensions and for a ValidationException for which status (always 400) and violations entries will be added.

This is not the case at all. All of the above scenarios result in an Internal Server Error with no status codes or violations added.

Also, any exceptions thrown in resolvers or data-persisters completely bypass the custom normaliser. This is true for all exceptions, including those defined by php-graphql, api-platfom, symfony or PHP. The only time the custom normaliser is called is when no exceptions are thrown. So this being the case, how does one throw and format exceptions correctly?

**Comment by alanpoulain** [comment]
Are you using the `master` version?

**Comment by tk-za** [comment]
Yes. I have copied the MyExceptionNormalizer code as-is from the documentation and have registered it in services.yaml.
I am using Symfony 5.1 and API-Platform 2.5.6

**Comment by alanpoulain** [comment]
You should use the `dev-master` version of API Platform, not the `2.5`.

**Comment by tk-za** [comment]
Sorry. I misread your initial post and assumed that you were only referring to updated documentation. Moving to the dev-master version of API Platform now works as advertised - and it is a huge improvement. 

Thank you once again.
