### ISSUE TITLE
Spelling correction in routes

### ISSUE THREAD

**Issue by enielrodriguez** [api-platform/api-platform#1599]
**API Platform version(s) affected**: 1.2.2

**Description**  
Somehow the routes are suffering from a spelling correction.

**How to reproduce**  
```
/**
 *
 * @ORM\Entity
 *
 * @ApiResource()
 */
class Analisis
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="NONE")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nombre", type="string", length=100, nullable=false)
     */
    private $nombre;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }
}
```

This results in the following (note the change from analisis to analises in the routes):

GET /api​/analises Retrieves the collection of Analisis resources.
POST ​/api​/analises Creates a Analisis resource.
GET ​/api​/analises​/{id} Retrieves a Analisis resource.
DELETE ​/api​/analises​/{id} Removes the Analisis resource.
PUT ​/api​/analises​/{id} Replaces the Analisis resource.
PATCH ​/api​/analises​/{id} Updates the Analisis resource.

**Possible Solution**  

**Additional Context**

**Comment by dunglas** [comment]
We use Doctrine Inflector under the hood to handle pluralization. To fix this you have 3 solutions:

1. Use the `path` attribute to specify explicitly the route to use
2. Use the Doctrine Inflector API to add custom pluralization rules
3. Of it's a bug in Doctrine Inflector, send a Pull Request to this projet to fix it

Best regards

**Comment by carlospauluk** [comment]
@dunglas , I'm trying to change the language of Doctrine Inflector API to `Language::PORTUGUESE`, but it seems to be hardcoded in Doctrine\Inflector\InflectorFactory to english:

```
    public static function create() : LanguageInflectorFactory
    {
        return self::createForLanguage(Language::ENGLISH);
    }
```
Is there some configuration inside API Platform to change that? Can't find anything in the docs.
Otherwise my API Resources will be with wrong names when pluralized.

Thanks
