### ISSUE TITLE
Mobile version: hamburger menu should retract when scrolling

### ISSUE THREAD

**Issue by CecileAmrl** [api-platform/api-platform#160]
<img width="394" alt="capture d ecran 2016-10-25 a 13 59 15" src="https://cloud.githubusercontent.com/assets/8024246/19685179/79aa83b0-9abb-11e6-889e-e25b02ef94af.png">

(ios 10.0.1)

**Comment by Aerendir** [comment]
You have to click the menu icon again to close it... I'm not sure is a useful behavior if it is closed by a scrolling o.O

**Comment by CecileAmrl** [comment]
Yes but that's not intuitive.

**Comment by Simperfit** [comment]
I agree with @CecileAmrl. It use alot of space, so when scrolling it should close by itself.

**Comment by Aerendir** [comment]
Maybe...

**Comment by Aerendir** [comment]
Ah ah ah, it's a play in house... Ok, as you like :)

**Comment by meyerbaptiste** [comment]
@CecileAmrl You should move your issue to https://github.com/api-platform/website.

**Comment by meyerbaptiste** [comment]
IMO menu should be a slideout navigation menu. But I'm not an UI expert! 😛

**Comment by Simperfit** [comment]
closing in favor of api-platform/website#6
