### ISSUE TITLE
Authentication lost, because of PUT request on user resource [PHP 7.4, Symfony 5.1]

### ISSUE THREAD

**Issue by RomanZberg** [api-platform/api-platform#1600]
**API Platform version(s) affected**: 2.5.6

**Description**  
Whenever I make a PUT Request to update the username of the current logged in user to a username of a existing user I get a response with a 400 status code, caused because of a validation error.

Nothing is wrong with that, because I have added a UniqueEntity annotation to the userentity, which causes this error.

Wrong is, that when I submit the same PUT request again, I get a 401 statuscode.
The first PUT request must have logged me out in some way. I get a 401 statuscode, because only fully authenticated users can use this route.

Instead of being logged out I should again get a 400 error.
**Note**: This only happens if the entity implements Symfony's Userinterface.

Im using API Platform with PHP 7.4 and Symfony 5.1

**How to reproduce**  

**My project:** [api-php.zip](https://github.com/api-platform/api-platform/files/4981329/api-php.zip)

1. Download my project
2. Install dependencys
    ```$ composer install```
3. Edit .env to adjust the database credentials
4. Create database
    ```$ php bin/console doctrine:database.create```
5. Execute Migrations
    ```$ php bin/console doctrine:migrations:migrate```
5. Load Fixtures
    ```$ php bin/console doctrine:fixtures:load```
6. Through the Swagger UI, use the login route to authenticate using the following credentials:
    **username:** user1
    **password:** 123456
    Remember the id returned from the login response (property user)
7. Submit a PUT request on the user resource with the userid from the login as request parameter and the following body:
   ```{"username": "user2"}```
8. A request with the status code 400 is retured. Submit the same request again.
9. A 401 status code is returned and you have been logged out

**Comment by dunglas** [comment]
Do you have a `security` attribute set? If it's not the case, you should consider adding a security rule. It prevents such errors related to how the Symfony Security Component handles authentication states. We already had this kind of issues reported, and it wasn't related to API Platform directly, but more about side effects triggered by the Security Component when an entity also managed by Doctrine where used.

**Comment by RomanZberg** [comment]
The user entity starts as follows:

/**
 * @ApiResource(
 *  normalizationContext={"groups"={"read"}},
 *  denormalizationContext={"groups"={"write"}},
 *     itemOperations={
 *     "get",
 *     "put" = { "security" = "is_granted('ROLE_USER')"},
 *     "delete"= { "security" = "is_granted('ROLE_USER')"}
 *     }
 * )
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @UniqueEntity(fields={"username"})
 */
class User implements UserInterface

**Comment by RomanZberg** [comment]
Reopened Issue on api-platform / core branch:
https://github.com/api-platform/core/issues/3661
