### ISSUE TITLE
Patch and Put returns good data but doesn't update in database

### ISSUE THREAD

**Issue by bastoune** [api-platform/api-platform#1605]
Versions:
- Api Platform `2.5.6`
- Symfony `4.4.11`

I have an entity called `Organization` and another one called `User`.
Both have Rest request managed by ApiPlatform.

The issue:
- For the entity user, it works perfectly.
- For Organization, I can do a `PATCH` or a `PUT` on the route `organizations/{id}`, **I get a 200 with the organization name well modified** BUT, in database it hasn't been stored as if it was persisted but not flushed.
- So If i get it later, the name is the older one.

The Serialization Context is dynamic (I followed this documentation): 
https://api-platform.com/docs/core/serialization/#changing-the-serialization-context-dynamically

I debugged and the `Organization:rw` group is well stored in the context thanks to this function:

**EntityRestContextBuilder.php**

    /**
     * @param Request $request
     * @param bool $normalization
     * @param array|null $extractedAttributes
     * @return array
     */
    public function createFromRequest(Request $request, bool $normalization, array $extractedAttributes = null): array
    {
        $context = $this->decorated->createFromRequest($request, $normalization, $extractedAttributes);
        $resourceClass = $context['resource_class'] ?? null;
    
        if (is_null($resourceClass))
            return $context;
    
        $context['groups'] = $context['groups'] ?? [];
    
        $entityName = StringHelper::splitAndGetLastElement("\\", $resourceClass);
        $operationType = $context['operation_type'];
    
        $context['groups'][] = "$entityName:rw";
        if ($normalization === true) {
            $context['groups'][] = "$entityName:read";
            $context['groups'][] = "$entityName:read:$operationType";
        } else {
            $context['groups'][] = "$entityName:write";
        }
    
        $context['groups'] = array_unique($context['groups']);
    
        return $context;
    }

Here are my config files :

**organization.yml**

    App\Entity\Organization:
      normalizationContext:
        enable_max_depth: true
      itemOperations:
        get:
          security: 'is_granted("read", object)'
        put:
          security: 'is_granted("update", object)'
        patch:
          security: 'is_granted("update", object)'
      collectionOperations:
        get:

**Organization.php**

    <?php
    namespace App\Entity;
    
    use Doctrine\Common\Collections\ArrayCollection;
    use Doctrine\Common\Collections\Collection;
    use Doctrine\ORM\Mapping as ORM;
    use Symfony\Component\Serializer\Annotation\Groups;
    use Symfony\Component\Serializer\Annotation\MaxDepth;
    
    /**
     * @ORM\Entity(repositoryClass="App\Repository\OrganizationRepository")
     * @ORM\HasLifecycleCallbacks
     */
    class Organization extends BaseEntity
    {
        /**
         * @ORM\Id()
         * @Groups({"Organization:read"})
         * @ORM\GeneratedValue(strategy="UUID")
         * @ORM\Column(name="id", type="guid", unique=true)
         */
        private $id;
    
        /**
         * @Groups({"Organization:rw", "User:read:item"})
         * @ORM\Column(type="string", length=255, unique=true)
         */
        private $name;
    
        /**
         * @var Collection $groups
         * @Groups({"Organization:read:item"})
         * @ORM\OneToMany(targetEntity="Group", mappedBy="organization")
         */
        private $groups;
    
        /**
         * @var Collection $users
         * @Groups({"Organization:read:item"})
         * @ORM\OneToMany(targetEntity="User", mappedBy="organization")
         */
        private $users;
    
        /**
         * @var Collection $children
         * @MaxDepth(1)
         *
         * @Groups({"Organization:read"})
         * @ORM\OneToMany(targetEntity="Organization", mappedBy="parent")
         */
        private $children;
    
        /**
         * @Groups({"Organization:read:item"})
         * @MaxDepth(1)
         *
         * @ORM\ManyToOne(targetEntity="Organization", inversedBy="children")
         * @ORM\JoinColumn(name="parent_id", referencedColumnName="id", nullable=true)
         */
        private $parent;
    
        /**
         * Organization constructor.
         */
        public function __construct()
        {
            $this->children = new ArrayCollection();
            $this->users = new ArrayCollection();
            $this->groups = new ArrayCollection();
        }
    
        public function getId(): string
        {
            return $this->id;
        }
    
        public function getName(): string
        {
            return $this->name;
        }
    
        public function setName(string $name): self
        {
            $this->name = $name;
    
            return $this;
        }
    
        public function getGroups(): Collection
        {
            return $this->groups;
        }
    
        public function getChildren(): Collection
        {
            return $this->children;
        }
    
        public function addChild(Organization $child): self
        {
            // @TODO If Orga has parent, throw Exception => https://sprints.zoho.eu/team/heyliot#itemdetails/P2/I91
    
            if (!$this->children->contains($child)) {
                $this->children->add($child);
                $child->setParent($this);
            }
    
            return $this;
        }
    
        public function removeChild(Organization $child): self
        {
            if ($this->children->contains($child)) {
                $this->children->removeElement($child);
                $child->setParent(null);
            }
    
            return $this;
        }
    
        public function getParent(): ?Organization
        {
            return $this->parent;
        }
    
        public function setParent(?Organization $parent): self
        {
            // @TODO If Orga has children, throw Exception => https://sprints.zoho.eu/team/heyliot#itemdetails/P2/I91
            $this->parent = $parent;
    
            return $this;
        }
    
        public function getUsers(): Collection
        {
            return $this->users;
        }
    
        public function addUser(Organization $organization): self
        {
            if (!$this->users->contains($organization)) {
                $this->users->add($organization);
            }
    
            return $this;
        }
    
        public function removeUser(Organization $organization): self
        {
            if ($this->users->contains($organization)) {
                $this->users->removeElement($organization);
            }
    
            return $this;
        }
    }

**Comment by Muspi** [comment]
Hi, do you use a custom DataPersister in your project?

**Comment by bastoune** [comment]
Yes @Muspi , and it was the problem, it wasn't well configured.
Sorry I forgot to close this issue.
