### ISSUE TITLE
Authenticator

### ISSUE THREAD

**Issue by damienmillet** [api-platform/api-platform#1620]
Hi, 

In my app, I get a token authenticator from an other services, I only save the username in database.
How can I use it with ur framework for be authenticated ?

ty,

Damien Millet

**Comment by rugolinifr** [comment]
I guess your token provider uses JWT and signs its token with an RSA private key.

As the [documentation says](https://api-platform.com/docs/core/jwt/#installing-lexikjwtauthenticationbundle), you should use the lexik bundle to authenticate through JWT your users.

Just put your token provider's RSA public key [inside your project](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#configuration) and configure your app to read the proper [`user_identity_field`](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/1-configuration-reference.md#full-default-configuration) value stored within the JWT.

The lexik guard authenticator will do the rest.

**Comment by damienmillet** [comment]
Ty, finally my auth isn't with token but with cookie, so i can close these.
