### ISSUE TITLE
he server returned a "500 Internal Server Error".

### ISSUE THREAD

**Issue by Osub** [api-platform/api-platform#163]
Oops! An Error Occurred

The server returned a "500 Internal Server Error".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by dunglas** [comment]
Can you try http://localhost/app_dev.php?
If it works, clear the cache: `bin/console c:c -e=prod`

**Comment by Osub** [comment]
ok,it works.  thanks!!!
