### ISSUE TITLE
[Bug] doctrine backward compatibility

### ISSUE THREAD

**Issue by rugolinifr** [api-platform/api-platform#1631]
**API Platform version(s) affected**: 1.2.2 on [Symfony flex](https://packagist.org/packages/api-platform/api-pack#v1.2.2)

**Description**  
This [issue](https://github.com/symfony/symfony/issues/37935) appreared on Symfony today. It is fixed now, but i'm still unable to run `composer require api`. I wonder if there is something to do on api-platform side ?

**How to reproduce**  
Create a new Symfony project with composer and add Api-Platform to it:
```bash
composer create-project symfony/skeleton new-project
cd new-project
composer require api
```
The last command should fail with the same error message as the Symfony linked issue.

**Comment by fabian-laine** [comment]
+1

**Comment by lyova** [comment]
same

**Comment by alanpoulain** [comment]
A release to fix it in the Doctrine bundle has been made 3 hours ago: https://github.com/doctrine/DoctrineBundle/releases/tag/2.1.2.

**Comment by walva** [comment]
+1 ! I'm torn about what to do 🌊

**Comment by alanpoulain** [comment]
You just have to update the Doctrine bundle to fix the issue.

**Comment by walva** [comment]
thanks @alanpoulain for your answer.

Creating a new symfony project `symfony new dummy` and then `composer require api` is not working because of 
```
 Argument 1 passed to ApiPlatform\Core\Bridge\Doctrine\Orm\Metadata\Property\DoctrineOrmPropertyMetadataFactory::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry, instance of Doctrine\Bundle\DoctrineBundle\Registry given, called in /home/ben/projects/gaa/dummy/var/cache/dev/ContainerWgxzW6R/App_KernelDevDebugContainer.php on line 1040
```

But  `symfony new dummy` then `compose require require orm-pack`  does work.

**Comment by Wenuz** [comment]
I always get it wrong, impossible to install API Platform...

`Argument 1 passed to ApiPlatform\Core\Bridge\Doctrine\Orm\Metadata\Property\DoctrineOrmPropertyMetadataFactory::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry, instance of Doctrine\Bundle\DoctrineBundle\Registry given, called in /Applications/MAMP/htdocs/my_events/App/var/cache/dev/Container6HxB1KB/App_KernelDevDebugContainer.php on line 1048`

**Comment by fabian-laine** [comment]
@alanpoulain, tks for your help but always the same issue on `symfony new xxxx` and `composer require api`

> Argument 1 passed to ApiPlatform\Core\Bridge\Doctrine\Orm\Metadata\Property\DoctrineOrmPropertyMetadataFactory::__construct() must be an instance of Doctrine\Common\Persistence\ManagerRegistry, instance of Doctrine\Bundle\DoctrineBundle\Registry given

**Comment by gponty** [comment]
same here after a fresh install

**Comment by alanpoulain** [comment]
Closing this issue in favor of the duplicated https://github.com/api-platform/core/issues/3683. Please use the other issue instead.
