### ISSUE TITLE
docker-compose up and windows : error no such file or directory

### ISSUE THREAD

**Issue by Dannebicque** [api-platform/api-platform#164]
Hello,

I try to use Api-platform (which seems very ambitious :) ). I use Windows 7, 64 bits (not the choice).
I try to install api-platform with docker. I foolow the instruction : 

- download docker-toolbox
- install, and run the terminal. OK
- download the api-platform zip.
- I put the terminal in this directory
- I run : docker-compose up
- Docker download durong few minutes many files, Symfony, API-platform

and, after that I have an error message : 

Error: for web Cannot start service web: invalid header field value "oci runtime error: container_linux.go:247: starting container process caused \"exec: \\\"/app/docker/apache/run.sh\\\": stat /app/docker/apache/run.sh: no such file or directory\"\n"
Encountered errors while bringing up the project.

I cannot exectue the other command from the "getting starting page". I have others errors.

Thanls for your help.

David

**Comment by Simperfit** [comment]
Are the files in synchro with the VM ?
This error means that either there are no synchro, either it's in the wrong place ?
Does it have the right to be executed ?

**Comment by Dannebicque** [comment]
I think yes.

I am new with docker. I just follow the installation guide. I think it works.

**Comment by teohhanhui** [comment]
You should try using Docker for Windows (new), not Docker Toolbox (old).

Few tips for Windows compatibility:
- Make sure you set `git` to not do EOL conversion - always use LF.
- Make sure you do `chmod +x ...` in the container for the scripts that you want to execute.
- (More problems that you might run into...)

**Comment by Simperfit** [comment]
@Dannebicque Did you find the solution ?

**Comment by Dannebicque** [comment]
Hi,

No, impossible to use Docker.  I uninstalled. I passed by the Git Repository.

**Comment by Simperfit** [comment]
@Dannebicque Did you try what @teohhanhui said ?

**Comment by teohhanhui** [comment]
It'd be good if someone could test on Windows and make it work out of the box.

**Comment by Dannebicque** [comment]
I cannot try the solution of teohhanhui, because the new docker does not work on windows 7, that's why I use Docker Toolbox.

**Comment by jonag** [comment]
Where are located your files? By default, with Docker Toolbox, only the files under your user directory (C:\Users\....) are accessible. This may explain your issue with Docker...

**Comment by dunglas** [comment]
I do not use Windows either. It would be nice if someone using Windows can confirm that our Docker setup is working out of the box.
If some extra steps are needed, we should add them to our docs or try to add out of the box support if possible.

**Comment by priyanka1110** [comment]
@dunglas I tried the steps suggested by @teohhanhui But still I am facing the same issue

`no such file or directory\"\n"`

I am using windows 10 Home, with docker toolbox.

**Comment by priyanka1110** [comment]
The issue was fixed since I had the code in `E:`. I checked out in `C:` and it works.

**Comment by Simperfit** [comment]
@priyanka1110 Could you please post a PR on the documentation to explain what to do on windows ?
