### ISSUE TITLE
[docs] Image is not readable in dark mode

### ISSUE THREAD

**Issue by alexislefebvre** [api-platform/api-platform#1647]
**API Platform version(s) affected**: possibly all versions

**Description**  
Some text and borders in image are not visible in dark mode, see below.

**How to reproduce**  
Go here and enable dark mode: https://api-platform.com/docs/core/dto/#specifying-an-input-or-an-output-data-representation

**Possible Solution**  
Workaround: click on image to zoom it, it enable a white background.

Add a background to image in dark mode, use different colors in images, etc.

**Additional Context** 

Dark mode:

> ![image](https://user-images.githubusercontent.com/2071331/92914640-1669eb00-f42c-11ea-9a65-06c632267a50.png)

Light mode:

> ![image](https://user-images.githubusercontent.com/2071331/92914837-4913e380-f42c-11ea-8654-e074b3468062.png)

**Comment by alanpoulain** [comment]
To solve this issue, a white background should be added to the SVG image.

**Comment by rugolinifr** [comment]
open your issue [here](https://github.com/api-platform/docs/issues) instead and fell free to fix it yourself !

**Comment by dunglas** [comment]
Maybe could we add some sort of CSS filter instead of changing the SVG?

**Comment by alexislefebvre** [comment]
Thanks @rugolinifr, I moved it in the corresponding repository: https://github.com/api-platform/docs/issues/1162
