### ISSUE TITLE
Upgrade docs?

### ISSUE THREAD

**Issue by djoos** [api-platform/api-platform#166]
Hi there,

I'm aware api-platform 2.0 is a RC-version, but: we'd like to get on 2.x as soon as possible. Are there any (rough) upgrade docs available for people migrating from 1.x?
Obviously there's no need to repeat the actual Symfony 2.8.x > 3.1.x upgrade, but a heads up on changes specific to api-platform would be very handy!

Thanks in advance for your feedback, have a great weekend!
David

**Comment by Simperfit** [comment]
Hey, @djoos 

We are discussing it in here api-platform/docs#67, we will be in the process of written it, if you can help ;)

Closing in favor of the issue in the docs.
