### ISSUE TITLE
No controller required to create custom operations.

### ISSUE THREAD

**Issue by imsheng** [api-platform/api-platform#1663]
**Description**  
```
/**
 * @ApiResource(
 *     itemOperations={
 *      "test"={"method"="POST","path"="/test" }
 *     },
 *     collectionOperations={
 *     }
 * )
 */
```
error: There is no builtin action for the item POST operation. You need to define the controller yourself in . (which is being imported from "C:\www\xiaoming\backend\app\config/routes/api_platform.yaml"). Make sure there is a loader supporting the "api_platform" type.

Sometimes the api simply submits the data, but it needs a controller, I feel cumbersome.

**Comment by rugolinifr** [comment]
`POST` operation are Collection operations, not item operations.
