### ISSUE TITLE
Error at the end of install

### ISSUE THREAD

**Issue by webspin** [api-platform/api-platform#1665]
Commands executed (empty project):
```
# Create a new Symfony Flex project
$ composer create-project symfony/skeleton synapi
# Enter the project folder
$ cd synapi
# Install the API Platform's server component in this skeleton
$ composer req api
```

Result:
PHP Fatal error:  Uncaught Error: Call to a member function getPrettyString() on string in /media/data/html/synapi/vendor/symfony/flex/src/Unpacker.php:153
Stack trace:
#0 /media/data/html/synapi/vendor/symfony/flex/src/Command/UnpackCommand.php(79): Symfony\Flex\Unpacker->unpack(Object(Symfony\Flex\Unpack\Operation))
#1 /media/data/html/synapi/vendor/symfony/flex/src/Command/RequireCommand.php(63): Symfony\Flex\Command\UnpackCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php(245): Symfony\Flex\Command\RequireCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 phar:///usr/local/bin/composer/vendor/symfony/console/Application.php(835): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///usr/local in /media/data/html/synapi/vendor/symfony/flex/src/Unpacker.php on line 153

PHP 7.2.24-0ubuntu0.18.04.6 (cli) (built: May 26 2020 13:09:11) ( NTS )

**Comment by dunglas** [comment]
This has been fixed by https://github.com/symfony/flex/pull/685
