### ISSUE TITLE
Error on step 9

### ISSUE THREAD

**Issue by toinouu** [api-platform/api-platform#167]
Hi
I try to install API platform and got the following error

> ERROR: Service 'web' failed to build: The command '/bin/sh -c php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"     && php -r "if (hash_file('SHA384', 'composer-setup.php') === 'e115a8dc7871f15d853148a7fbac7da27d6c0030b848d9b3dc09e2a0388afed865e6a3d6b3c0fad45c48e2b5fc1196ae') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"     && php composer-setup.php     && php -r "unlink('composer-setup.php');"     && mv composer.phar /usr/bin/composer     && composer global require "hirak/prestissimo:^0.3"' returned a non-zero code: 1

if anyone can help me

thx

**Comment by Simperfit** [comment]
You have to change the signature in the Dockerfile of composer by this one `aa96f26c2b67226a324c27919f1eb05f21c248b987e6195cad9690d5c1ff713d53020a02ac8c217dbf90a7eacc9d141d `

**Comment by Simperfit** [comment]
Fixed by #168

**Comment by toinouu** [comment]
thx @Simperfit 

but now => #169

**Comment by Simperfit** [comment]
now fixed
