### ISSUE TITLE
Item custom operation using DELETE

### ISSUE THREAD

**Issue by ivanmunozruiz** [api-platform/api-platform#1672]
is there a way to make a custom operation using method delete without delete all the entity? 
for example:
  ```
"delete_password"={
      "method"="DELETE",
      "path"="{id}/password",
      "controller"=PasswordDelete::class,
 },
```
In that controller I only want to do something like this:

`$entity->setPassword(null)...`

because I am trying and the code in PasswordDelete is executed, but after that execution my entity is deleted from database

thanks

**Comment by rugolinifr** [comment]
This is the job of a `PUT` operation.

Anyway you can return a `Response` object from your controller to skip the rest of the lifecycle.

Or you may [disable](https://api-platform.com/docs/core/events/#built-in-event-listeners) the `WriteListener` by adding a `write=false` to your operation:
```php
"delete_password"={
    "method"="DELETE",
    "path"="{id}/password",
    "controller"=PasswordDelete::class,
    "write"=false
},
```

**Comment by rugolinifr** [comment]
This is the job of a `PUT` operation.

Anyway, you can return a `Response` object from your controller after calling manualy `$entityManager->flush()`, it will skip the rest of the lifecycle.

Or you may [disable](https://api-platform.com/docs/core/events/#built-in-event-listeners) the `WriteListener`:
```php
"delete_password"={
    "method"="DELETE",
    "path"="{id}/password",
    "controller"=PasswordDelete::class,
    "write"=false
},
```

**Comment by rugolinifr** [comment]
@ivanmunozruiz don't forget to close if this solves your issue !
