### ISSUE TITLE
Creating api-platform from Use this template is broken for production due to admin component changes

### ISSUE THREAD

**Issue by vemonet** [api-platform/api-platform#1687]
**API Platform version(s) affected**: `master` branch

**Description**  

It seems like there has been work on `master` branch to merge admin in the Client

But in the meanwhile the docker deployments are not updated for this new infrastructure

This means that if I follow the instructions to deploy for production I will face issues due to the `admin` folder being deleted in the master branch

Unfortunately GitHub does not propose to start the template from a specific version/tag/commit 

**How to reproduce**  

1. Create repo from **Use this template** at https://github.com/api-platform/api-platform
2. Follow instruction to `docker build` API platform: https://api-platform.com/docs/deployment/docker-compose/#installing-the-docker-compose-setup-for-production

**Possible Solution**  

Only push releases to the `master` so that the **Use this template** will provide the latest stable and working version

**Additional Context**  

Hoping to see this new development soon in a release, thanks!

**Comment by dunglas** [comment]
Fixed in API Platform 2.6 alpha. We still need to update the docs.
