### ISSUE TITLE
Failed to write cache file

### ISSUE THREAD

**Issue by toinouu** [api-platform/api-platform#169]
Hi

I installed api platform but now when I want to access the dev environment (app_dev.php) I get an error related to the cache

> RuntimeException in ClassCollectionLoader.php line 272: Failed to write cache file "/app/var/cache/dev/classes.php".

thx for help

**Comment by Simperfit** [comment]
Can you please show me the rights of your app ?

**Comment by toinouu** [comment]
the rights of cache directory 
drwxr-xr-x 4 root root /api-platform/var/cache

**Comment by Simperfit** [comment]
This is on the host right ? Why is it root ?

**Comment by toinouu** [comment]
I think it puts the root because when I want to run a command I do this

sudo docker-compose run web bin/console cache:clear

**Comment by dunglas** [comment]
you shouldn't be running docker-compose as root.

**Comment by toinouu** [comment]
ok but when i dont use root  i have this error 

> ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

**Comment by Simperfit** [comment]
What environment are you using ?


Could you please tell me if you run all :

### On Linux

1) Run install script

    curl -fsSL https://get.docker.com/ | sh


2) Add the current in user in the Docker group and restart your machine

    sudo usermod -aG docker `whoami`

You have to reboot

3) Start your docker service

    sudo service docker start


4) Run docker test

    docker run hello-world

**Comment by toinouu** [comment]
I forgot to reboot my bad

thx
