### ISSUE TITLE
NormalizationContext group fields not returned in api test

### ISSUE THREAD

**Issue by FrankHouwelingCastor** [api-platform/api-platform#1699]
**API Platform version(s) affected**:v2.5.7

**Description**  
Properties of resources which use normalizationContext / [serialisation groups](https://api-platform.com/docs/core/serialization/#the-serialization-context-groups-and-relations) are not returned in functional tests using the ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase methods for retrieving data. The properties áre returned when using the "real" API endpoint.

**How to reproduce**  
Create some resource while using a normalizationContext. For example:

```
<?php

/**
 * @ApiResource(
 *     normalizationContext={"groups"={"study:read"}},
 * )
 */
class Study
{
   ....

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Groups({"study:read"})
     */
    private string $name;

   ....
```

Now create a test that tries to retrieve this information:

```
<?php

use ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase;

class StudyTest extends ApiTestCase
{
    public function testGetStudyCollection(): void
    {
        static::createClient()->request('GET', '/studies');
        self::assertResponseIsSuccessful();

        $data = $singleResponse->toArray();
        self::assertArrayHasKey('name', $data);
    }
}
```

The test will fail, since the 'name' property is not returned.

Calling the API directly for the same endpoint will return the 'name' property.

**Comment by rugolinifr** [comment]
Where is instanciated `$singleResponse` ?

**Comment by merigold** [comment]
I have the same behavior:

`   $client = static::createClient();

        $iriObject = $this->findIriBy(Objects::class, ['name' => 'objects_test']);
        $response =$client->request('GET', $iriObject);
$object = $response->toArray()
        print_r($object);
`

Fields with nested entity is null. In normal api call eg. from swager  are filled

**Comment by FrankHouwelingCastor** [comment]
Looks to be resolved by explicitly adding a use statement for the entity.
