### ISSUE TITLE
Any way without docker installation ?

### ISSUE THREAD

**Issue by SerkanDayicik** [api-platform/api-platform#170]
Hey, i m trouble with docker because my os a windows 10 32 bit cannot run docker any way can install api-platform on vagrant or lika a xampp ?

**Comment by Simperfit** [comment]
@SerkanDayicik Docker is way of running the project, you can totally run api-platform with a local mysql server and one `bin/console server:run` or be using apache or nginx.

**Comment by theofidry** [comment]
As @Simperfit, this is a regular PHP application. Docker is here just to help a bit but you can do without :)

**Comment by alex88** [comment]
@Simperfit latest update seems to have removed the `bin/console server:run` command, there is nothing under the `server` namespace anymore, was it intentional?

**Comment by Simperfit** [comment]
IIRC You now need to install the webserver [by your own](https://github.com/symfony/web-server-bundle)

**Comment by alex88** [comment]
@Simperfit you mean nginx-apache etc or a component that replaces that command?

**Comment by meyerbaptiste** [comment]
The Symfony WebServerBundle which provides the `server:run` command since Symfony 3.3: http://symfony.com/blog/new-in-symfony-3-3-webserverbundle

**Comment by alex88** [comment]
Oh sorry, haven't seen that, I've searched only through api platform changes... Thank you!
