### ISSUE TITLE
php8 add new library in api/composer.json

### ISSUE THREAD

**Issue by nicotec** [api-platform/api-platform#1705]
**API Platform version(s) affected**: dev-master as 2.6.0

**Description**  
installation of ^ 7.x php library which was added in composer :
 xxx requires php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.

**How to reproduce**  
add in api/composer.json
    "require": {
        "api-platform/core": "dev-master as 2.6.0",
        "backup-manager/symfony": "3.*",

**Possible Solution**  
add : "--ignore-platform-req=php" in api/docker/php/docker-entrypoint.sh (l.26)
composer install --ignore-platform-req=php --prefer-dist --no-progress --no-suggest --no-interaction

After install is okey !

**Additional Context**

**Comment by dunglas** [comment]
Thanks for reporting. This has been fixed yesterday: https://github.com/api-platform/api-platform/blob/master/api/docker/php/docker-entrypoint.sh#L21
