### ISSUE TITLE
Schema test wrong since v2.5.8: tested working on 2.5.7

### ISSUE THREAD

**Issue by FrankHouwelingCastor** [api-platform/api-platform#1713]
v2.5.8

**Description**  
The json schema in the test is different from the json schema in documentation and from the json schema of the API response.

**How to reproduce**  
![image](https://user-images.githubusercontent.com/69353572/101617741-4f0c6700-3a11-11eb-9181-7a7885c3d647.png)

```
static::createClient()->request('GET', '/studies');
        self::assertResponseIsSuccessful();
        self::assertResponseHeaderSame('content-type', 'application/ld+json; charset=utf-8');

        self::assertMatchesResourceCollectionJsonSchema(Study::class);
```

Will return:
hydra:member[0].roles[0].user: Object value found, but a string is required

If I var_dump the schema that is being generated by the ApiTestAssertionsTrait::assertMatchesResourceCollectionJsonSchema function it indeed expects a string. This is different from the output of the API docs, and also from what the API returns.

This functionality is broken because of the api-platform/core update (v2.5.7 => v2.5.8). Tested to be working before the update of these packages, with the same code.

**Comment by yakobe** [comment]
Hi @FrankHouwelingCastor 
I am having a similar problem. Did you close this because you found a solution?

**Comment by theyough** [comment]
Hi @FrankHouwelingCastor , 

did you find the solution ? I have the same problem ?

**Comment by FrankHouwelingCastor** [comment]
@yakobe Sorry for not responding to your question, I completely missed the notification.

@theyough Thanks for reminding me!

For us, the issue was that API Platform did (for some reason) not use the correct schema. We have a custom function in a trait that receives the correct schema (by asking it explicitely).

```
trait GetSchema
{
    /**
     * @param string[] $normalizerGroups
     *
     * @return Schema<Entity>
     */
    public function getSchema(string $className, array $normalizerGroups, string $operationType): Schema
    {
        $schemaFactory = static::$container->get('api_platform.json_schema.schema_factory');
        assert($schemaFactory instanceof SchemaFactoryInterface);

        return $schemaFactory->buildSchema(
            $className,
            'jsonld',
            Schema::TYPE_OUTPUT,
            $operationType,
            null,
            null,
            [
                AbstractNormalizer::GROUPS => $normalizerGroups,
                AbstractNormalizer::ALLOW_EXTRA_ATTRIBUTES => false,
            ]
        );
    }
}
```

This is then implemented in our test with this code:

```
$response = static::createClient()->request('GET', '/some_endpoint');
self::assertResponseIsSuccessful();
self::assertResponseHeaderSame('content-type', 'application/ld+json; charset=utf-8');
$schema = $this->getSchema(SomeEndpoint::class, ['some_endpoint:read'], OperationType::COLLECTION);
static::assertMatchesJsonSchema($schema->getArrayCopy());
```

**Comment by yakobe** [comment]
See here for the cause of the problem: https://github.com/api-platform/core/issues/3896

Unfortunately i have not found the time to have a crack at the PR yet. It's on my list of things to do tho because I cannot upgrade without it 😄.
