### ISSUE TITLE
GraphQL not logging

### ISSUE THREAD

**Issue by djpremier** [api-platform/api-platform#1715]
**API Platform version(s) affected**: x.y.z
api-platform/api-pack > v1.3.0

**Description**  

My GraphQL does not send errors to the log, it appears in the request "Internal server error", but nothing is stored. Does any configuration need to be done to store it?

**How to reproduce**  

**Possible Solution**  

**Additional Context**

**Comment by alanpoulain** [comment]
You need to configure it. See https://api-platform.com/docs/master/core/graphql/#handling-exceptions-and-errors-logging-filtering-.
