### ISSUE TITLE
Property metadata and normalization context for custom resource

### ISSUE THREAD

**Issue by mykbas** [api-platform/api-platform#1718]
**API Platform version(s) affected**: 2.6.0-alpha.1 + Symfony 5.2

**Description**  
Following [this tutorial](https://symfonycasts.com/screencast/api-platform-extending/property-metadata#play) with Symfony5.2 and latest APIPlatform 2.6.0-alpha.1 setting normalization context with custom data provider returns empty data for the fields marked with appropriate groups.

UPD: clearing cache didn't help

UPD 2
Somehow it does not react to manual setting `normalizationContext` groups either in camelcase "dailyStats:read" or with dash "daily-stats:read", or "dummystats:read". 
But the data is displayed correctly only with default groups `"dailystats:read"``

```
For class defined like below I see only `totalVisitors`

/**
* @ApiResource(
*     normalizationContext={"groups"={"dummystats:read"}},
*     itemOperations={"get"},
*     collectionOperations={"get"}
* )
*/
class DailyStats
{
    /**
    * @Groups({"dummystats:read"})
    */
    public $date;
    
    /**
    * @Groups({"dailystats:read"})
    */
    public $totalVisitors;
}
```

**Comment by tpharaoh** [comment]
I literally just had the same issue. Found a post on github where someone
said clearing cache solves it. I didn't believe it, but I tried. Worked for
me

bin/console cache:clear

**Comment by mykbas** [comment]
found my mistake
