### ISSUE TITLE
Why do I have to indicate addSeries() and not addSerie()?

### ISSUE THREAD

**Issue by GaylordP** [api-platform/api-platform#1721]
**API Platform version(s) affected**: 2.5

**Description**  
With Symfony, Doctrine and API Platform, I just solved a problem which caused a lot of nervousness and weariness for 8 hours.

For one of my entities, I had a lot of problem with an ArrayCollection attribute :

    /**
     * TrainingSession
     *
     * @ORM\Entity(repositoryClass="App\Repository\TrainingSessionRepository")
     * @ApiResource(
     *     collectionOperations={"get", "post"},
     *     itemOperations={"get", "delete"},
     *     normalizationContext={
     *         "skip_null_values"=false,
     *         "groups"={"training_sessions_read"}
     *     },
     *     denormalizationContext={
     *         "groups"={"training_sessions_write"}
     *     }
     * )
     */
    class TrainingSession
    {
        ...

        /**
         * @ORM\OneToMany(
         *     targetEntity="App\Entity\TrainingSerie",
         *     mappedBy="training",
         *     cascade={"persist"},
         * )
         * @Groups({
         *     "training_sessions_read",
         *     "training_sessions_write",
         * })
         */
        private $series;

        public function getSeries(): Collection
        {
            return $this->series;
        }

        public function addSerie(TrainingaSerie $serie): void
        {
            // don't work
            ...
        }

It is not possible to add series in `Post` request.

`/api`, I can see that no data is expected for the `POST` operation for this entity :

[![enter image description here][1]][1]

After 8 hours of research, I understand that I must indicate `addSeries()` and not `addSerie()`.

Now, I can `POST` séries : 

[![enter image description here][2]][2]

How to explain this and the use of the plural ? I have a lot of other `ArrayCollection` attributes that work normally (`$measurements` / `addMeasurement()` ; `$posts` / `addPost()`).

  [1]: https://i.stack.imgur.com/qdybj.png
  [2]: https://i.ibb.co/5nbbf3r/capture.png

**Comment by dunglas** [comment]
Thanks for reporting! This looks like a bug in the Symfony Inflector component (which in turn is used by the PropertyInfo component, which is used by API Platform). This must be directly reported to Symfony. There is nothing we can do about it here.
