### ISSUE TITLE
next/link not works

### ISSUE THREAD

**Issue by nicotec** [api-platform/api-platform#1726]
**API Platform version(s) affected**: 2.6.beta (wsl2)

**Description**  
If we add a link with next / link. An error always occurs. The code is the original one.

**How to reproduce**  
import Head from "next/head";
import Link from "next/link";

const Welcome = () => (
  <>
    <Head>
      <title>Welcome to API Platform!</title>
    </Head>

    <div className="welcome">
      <Link href="/"><a>test link</a></Link>
      <header className="welcome__top">

**Possible Solution**  
https://github.com/vercel/next.js/issues/16874

**Additional Context**  
![image](https://user-images.githubusercontent.com/10002262/102797861-8cc5a400-43b0-11eb-8441-938068686241.png)

**Comment by LeoBenoist** [comment]
Hello. same problem for me.

It is related to the caddy Caddyfile.

Next json request are forwarded to Symfony instead of Next due to:

api/docker/caddy/Caddyfile

`@pwa {
    # Pass the request to the API for typical API media types.
    # `application/xml` is not in the list on purpose:
    # it is part of the default Accept header sent by browsers.
    not header_regexp Accept (?i)(?:\bjson\b|^text/(?:csv|xml)$|^application/x-yaml$)

    # Explicitly list routes always handled by the API as well as
    # URLs with an extension corresponding to common formats supported by the API.
    not path_regexp (?i)(?:^/docs|^/graphql|^/bundles/|^/_profiler|^/_wdt|.+\.(?:json|html$|csv$|ya?ml$|xml$))
}`

**Comment by dunglas** [comment]
Good catch. We must add an exception for the `/_next` prefix in the regex.

**Comment by LeoBenoist** [comment]
Also manifest.json is missing if have next pwa

**Comment by LeoBenoist** [comment]
For now I have fixed my project like that: (probably some better ways to it but I don't know caddy

```
{
    # Debug
    {$DEBUG}
    # HTTP/3 support
    servers {
        protocol {
            experimental_http3
        }
    }
}

{$SERVER_NAME}

log

@pwaNext {
    path /_next/*
    path /manifest.json
}

@pwa {
    # Pass the request to the API for typical API media types.
    # `application/xml` is not in the list on purpose:
    # it is part of the default Accept header sent by browsers.
    not header_regexp Accept (?i)(?:\bjson\b|^text/(?:csv|xml)$|^application/x-yaml$)

    # Explicitly list routes always handled by the API as well as
    # URLs with an extension corresponding to common formats supported by the API.
    not path_regexp (?i)(?:^/docs|^/graphql|^/bundles/|^/_profiler|^/_wdt|.+\.(?:json|html$|csv$|ya?ml$|xml$))
}

route {
    root * /srv/api/public
    push

    # Comment the following line if you don't want Next.js to catch requests for HTML documents.
    # In this case, they will be handled by the PHP app.
    reverse_proxy @pwaNext http://{$PWA_UPSTREAM}
    reverse_proxy @pwa http://{$PWA_UPSTREAM}
    php_fastcgi unix//var/run/php/php-fpm.sock
    encode zstd gzip
    file_server
}
```

**Comment by dunglas** [comment]
@LeoBenoist thanks for your research, it helped me a lot! I opened a PR fixing this problem: https://github.com/api-platform/api-platform/pull/1741
Could you test if it works for you?

**Comment by LeoBenoist** [comment]
> @LeoBenoist thanks for your research, it helped me a lot! I opened a PR fixing this problem: #1741
> Could you test if it works for you?

Sure on it :)
