### ISSUE TITLE
2.6.0 beta 1 graphQL support

### ISSUE THREAD

**Issue by MasterHarem** [api-platform/api-platform#1727]
**API Platform version(s) affected**: 2.6.0 beta 1

**Description**  
Cannot install GraphQL

**How to reproduce**  
Clean install api-platform
Try install graphQL with `docker-compose exec php composer req webonyx/graphql-php && docker-compose exec php bin/console cache:clear`
```
Using version ^14.4 for webonyx/graphql-php
./composer.json has been updated
Running composer update webonyx/graphql-php
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/doctrine-migrations-bundle is locked to version 3.0.1 and an update of this package was not requested.
    - doctrine/doctrine-migrations-bundle 3.0.1 requires php ^7.2 -> your php version (8.0.0) does not satisfy that requirement.


Installation failed, reverting ./composer.json and ./composer.lock to their original content
```

**Possible Solution**  
Upgrade dependencies

**Comment by dunglas** [comment]
Add the `--ignore-platform-req=php` option. Doctrine Migrations is not yet officially compatible with PHP 8, but it works fine for most use cases.
