### ISSUE TITLE
Change parameter and data type

### ISSUE THREAD

**Issue by CesarCarrazana** [api-platform/api-platform#173]
Hello 

I'm customize operations and I like change type and name of parameter in GET, POST p. e. "slug" - "string". Default is "id" type "integer". Thanks!

**Comment by Simperfit** [comment]
@CesarCarrazana Do you mean on the URL ?

**Comment by CesarCarrazana** [comment]
@Simperfit  on the parameters in POST

Thanks

**Comment by Simperfit** [comment]
You can do that by [overriding the operation](https://api-platform.com/docs/core/operations#configuring-operations)
