### ISSUE TITLE
Attempted to load class "DebugFlag" from namespace "GraphQL\Error".

### ISSUE THREAD

**Issue by evgeniyphp** [api-platform/api-platform#1734]
**API Platform version(s) affected**: x.y.z
Hello everyone!
**Description**  

Today I decided to create a new symfony project and installed api_platform on it. Activated graphql. I go to / api / graphql and get this error. How to solve it? Someone came across?

**How to reproduce**  

Just create new symfony project and activate graphql. Go to url api/grpahql

1.  composer create-project symfony/skeleton my_project_name
2.  composer req api
3.  Activate grpahql in config/packages/api_platform.yaml
4.  Go to api/graphql

**Possible Solution**  

**Additional Context**  

![Screenshot from 2020-12-30 17-37-52](https://user-images.githubusercontent.com/60447632/103365732-6b0f9f80-4ac9-11eb-8566-359e2a65362b.png)

**Comment by alanpoulain** [comment]
Are you using the latest version (2.5.9)?

**Comment by evgeniyphp** [comment]
Yes, i am using this version
![Screenshot from 2020-12-30 20-17-11](https://user-images.githubusercontent.com/60447632/103372902-04e04800-4adc-11eb-8cc8-097820a8713f.png)

**Comment by alanpoulain** [comment]
What is your graphql-php version?

**Comment by alanpoulain** [comment]
Did you follow https://api-platform.com/docs/core/graphql/#enabling-graphql?

**Comment by evgeniyphp** [comment]
This?
![Screenshot from 2020-12-30 20-32-56](https://user-images.githubusercontent.com/60447632/103373680-407c1180-4ade-11eb-9670-491f6d528be8.png)

**Comment by alanpoulain** [comment]
Yes. Have you cleared your cache?

**Comment by evgeniyphp** [comment]
Yes

**Comment by alanpoulain** [comment]
It should work then. The `DebugFlag` is here: https://github.com/webonyx/graphql-php/blob/master/src/Error/DebugFlag.php.

**Comment by evgeniyphp** [comment]
> Did you follow https://api-platform.com/docs/core/graphql/#enabling-graphql?

No, i did not follow this. But, now i am trying and it work. Thanks!
