### ISSUE TITLE
Can't install the framework because of repositories

### ISSUE THREAD

**Issue by AndreMaz** [api-platform/api-platform#175]
Hello

So I'm trying to install the API Platform but during the installation (`sudo docker-compose up`) getting the following error:

```
Starting apiplatformmaster_database_1
Building web
Step 1 : FROM php:7.0-apache
 ---> 7dea5b089190
Step 2 : ENV APCU_VERSION 5.1.5
 ---> Using cache
 ---> e5bb56e77724
Step 3 : RUN buildDeps="         libicu-dev         zlib1g-dev     "     && apt-get update     && apt-get install -y --no-install-recommends         $buildDeps         libicu52         zlib1g     && rm -rf /var/lib/apt/lists/*     && docker-php-ext-install         intl         mbstring         pdo_mysql         zip     && apt-get purge -y --auto-remove $buildDeps
 ---> Running in 0a54787f47cf
Err http://security.debian.org jessie/updates InRelease
  
Err http://security.debian.org jessie/updates Release.gpg
  Could not resolve 'security.debian.org'
Err http://deb.debian.org jessie InRelease
  
Err http://deb.debian.org jessie-updates InRelease
  
Err http://deb.debian.org jessie Release.gpg
  Could not resolve 'deb.debian.org'
Err http://deb.debian.org jessie-updates Release.gpg
  Could not resolve 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  
                                                                                                                                     
W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease                                                         
                                                                                                                                     
W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Could not resolve 'security.debian.org'              
                                                                                                                                     
W: Failed to fetch http://deb.debian.org/debian/dists/jessie/Release.gpg  Could not resolve 'deb.debian.org'                         
                                                                                                                                     
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/Release.gpg  Could not resolve 'deb.debian.org'                 
                                                                                                                                     
W: Some index files failed to download. They have been ignored, or old ones used instead.                                            
Reading package lists...                                                                                                             
Building dependency tree...                                                                                                          
Reading state information...                                                                                                         
E: Unable to locate package libicu-dev                                                                                               
E: Unable to locate package zlib1g-dev                                                                                               
E: Unable to locate package libicu52                                                                                                 
ERROR: Service 'web' failed to build: The command '/bin/sh -c buildDeps="         libicu-dev         zlib1g-dev     "     && apt-get update     && apt-get install -y --no-install-recommends         $buildDeps         libicu52         zlib1g     && rm -rf /var/lib/apt/lists/*     && docker-php-ext-install         intl         mbstring         pdo_mysql         zip     && apt-get purge -y --auto-remove $buildDeps' returned a non-zero code: 100
```

Docker seems to be running OK. After running the `sudo docker run hello-world` getting the following message:

```
latest: Pulling from library/hello-world

c04b14da8d14: Pull complete 
Digest: sha256:0256e8a36e2070f7bf2d0b0763dbabdd67798512411de4cdcf9431a1feb60fd9
Status: Downloaded newer image for hello-world:latest

Hello from Docker!
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/engine/userguide/
```

Any solution?

PS: I'm using Ubuntu 16.04.1 LTS

**Comment by Simperfit** [comment]
Hey @AndreMaz thank you for using ApiPlatform, 

Firstly why are you running docker as root ?

Secondly can you do `docker pull php:7.0-apache` then `docker-compose up -d` ?

**Comment by AndreMaz** [comment]
Hey @Simperfit thanks for quick answer

1. I was running as a root because I've just done a fresh installation of Docker and didn't add my account to the docker group (https://docs.docker.com/engine/installation/linux/ubuntulinux/#/create-a-docker-group)

2.
Input
`docker pull php:7.0-apache`
Output:
` 
7.0-apache: Pulling from library/php
Digest: sha256:635651170bb227a1586c392d529704d74c74ba48226491850e78392b36b47f94
Status: Image is up to date for php:7.0-apache
`


Input:
`docker-compose up -d`
Output:
`apiplatformapiplatformab17f42_database_1 is up-to-date
Building web
Step 1 : FROM php:7.0-apache
 ---> 7dea5b089190
Step 2 : ENV APCU_VERSION 5.1.5
 ---> Using cache
 ---> e5bb56e77724
Step 3 : RUN buildDeps="         libicu-dev         zlib1g-dev     "     && apt-get update     && apt-get install -y --no-install-recommends         $buildDeps         libicu52         zlib1g     && rm -rf /var/lib/apt/lists/*     && docker-php-ext-install         intl         mbstring         pdo_mysql         zip     && apt-get purge -y --auto-remove $buildDeps
 ---> Running in 18937467dbe0
Err http://security.debian.org jessie/updates InRelease
  
Err http://security.debian.org jessie/updates Release.gpg
  Could not resolve 'security.debian.org'
Err http://deb.debian.org jessie InRelease
  
Err http://deb.debian.org jessie-updates InRelease
  
Err http://deb.debian.org jessie Release.gpg
  Could not resolve 'deb.debian.org'
Err http://deb.debian.org jessie-updates Release.gpg
  Could not resolve 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/jessie/InRelease  

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/InRelease  

W: Failed to fetch http://security.debian.org/dists/jessie/updates/Release.gpg  Could not resolve 'security.debian.org'

W: Failed to fetch http://deb.debian.org/debian/dists/jessie/Release.gpg  Could not resolve 'deb.debian.org'

W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/Release.gpg  Could not resolve 'deb.debian.org'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libicu-dev
E: Unable to locate package zlib1g-dev
E: Unable to locate package libicu52
ERROR: Service 'web' failed to build: The command '/bin/sh -c buildDeps="         libicu-dev         zlib1g-dev     "     && apt-get update     && apt-get install -y --no-install-recommends         $buildDeps         libicu52         zlib1g     && rm -rf /var/lib/apt/lists/*     && docker-php-ext-install         intl         mbstring         pdo_mysql         zip     && apt-get purge -y --auto-remove $buildDeps' returned a non-zero code: 100
`

**Comment by Simperfit** [comment]
Do you have a proxy that would disable the access to the repository ? I can't reproduce this error using the same steps.
Maybe you could try `docker-compose build --no-cache`

**Comment by dunglas** [comment]
It's not an error related to API Platform. It's obviously a network issue on your side (a firewall is probably blocking access to `debian.org`'s subdomain from your network).

Can you retry from a connection without firewall or proxy?

**Comment by AndreMaz** [comment]
Thanks @Simperfit and @dunglas :) you were right. For some reason my university is blocking the access to `debian.org` subdomains.
VPN solved the issue
