### ISSUE TITLE
Denormalization_context groups doesnt work on Entity variables

### ISSUE THREAD

**Issue by gediminasnn** [api-platform/api-platform#1759]
**API Platform version(s) affected**: x.y.z

**Description**  
My simple ApiResource entity denormalization group doesnt work

This is my entity

```
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\SerializedName;


  /**
   * @ApiResource(
   *     attributes={
   *     "normalization_context"={"groups"={"read"}},
   *     "denormalization_context"={"groups"={"write"}},
   * }
   * )
   * @ORM\Entity(repositoryClass=UserRepository::class)
   */

class User
  {
      /**
       * @ORM\Id
       * @ORM\GeneratedValue
       * @ORM\Column(type="integer")
       */
      private $id;
  
      /**
       * @ORM\Column(type="string", length=255)
       * @Groups("write")
       */
      private $first_name;
  
      /**
       * @Groups("write")
       * @ORM\Column(type="string", length=255, nullable=true)
       */
      private $last_name;
  
      /**
       * @ORM\Column(type="string", length=255)
       * @Groups("write")
       */
      private $api_key;
  
      /**
       * @Groups("read")
       * @ORM\Column(type="string", length=255, nullable=true)
       */
      private $full_name;
  
      public function getId(): ?int
      {
          return $this->id;
      }
  
      public function getFirstName(): ?string
      {
          return $this->first_name;
      }
  
      public function setFirstName(string $first_name): self
      {
          $this->first_name = $first_name;
  
          return $this;
      }
  
      public function getLastName(): ?string
      {
          return $this->last_name;
      }
  
      public function setLastName(?string $last_name): self
      {
          $this->last_name = $last_name;
  
          return $this;
      }
  
      public function getApiKey(): ?string
      {
          return $this->api_key;
      }
  
      public function setApiKey(string $api_key): self
      {
          $this->api_key = $api_key;
  
          return $this;
      }
  
      public function getFullName(): ?string
      {
          return $this->full_name;
      }
  
      public function setFullName(?string $full_name): self
      {
          $this->full_name = $full_name;
  
          return $this;
      }
  }
```

This is what I get
![Screenshot 2021-01-14 155337](https://user-images.githubusercontent.com/70708109/104599824-ed2ec500-5680-11eb-81b2-e299b4c236e3.png)

**Possible Solution**  
There is a way to go around this issue just use denormalization groups on setter methods :
  ```

    /**
       * @param string $first_name
       * @Groups("write")
       * @return $this
       */
      public function setFirstName(string $first_name): self
      {
          $this->first_name = $first_name;
  
          return $this;
      }
  
     /**
       * @param string|null $last_name
       * @return $this
       * @Groups("write")
       */
      public function setLastName(?string $last_name): self
      {
          $this->last_name = $last_name;
  
          return $this;
      }
  
      /**
       * @param string $api_key
       * @return $this
       * @Groups("write")
       */
      public function setApiKey(string $api_key): self
      {
          $this->api_key = $api_key;
  
          return $this;
      }

```

Then it works just fine - 
![image](https://user-images.githubusercontent.com/70708109/104599787-e30cc680-5680-11eb-9839-3f38ea9cbc0c.png)

Also in this https://github.com/api-platform/api-platform/issues/1576 issue which is same problem but only with normalization_context not denormalization it suggest to clear cache with `php bin/console cache:clear`, i've tried it and it didn't work.

**Comment by silverbackdan** [comment]
Your normalization context is `read` so the returned object will only look to include those fields. Does the object populate correctly in the database?

**Comment by gediminasnn** [comment]
> Your normalization context is `read` so the returned object will only look to include those fields with that group. It will exclude null variables by default. Does the object populate correctly in the database?

Yes, it does have values, not nulls and is named correctly

**Comment by silverbackdan** [comment]
Sorry, I may be wrong but what I'm saying is this is the only property you should expect to see returned from the API as your object as it has the `read` group but in your successful response, this field is not there either, so perhaps you aren't submitting it?
```
      /**
       * @Groups("read")
       * @ORM\Column(type="string", length=255, nullable=true)
       */
      private $full_name;
```

Whereas the fields you get in your successful version, when using the annotation `@Groups("write")` will not be included in the response because of `"normalization_context"={"groups"={"read"}}`. If you want those returned as well, use `@Groups({"write","read"})` on the fields perhaps?

**Comment by gediminasnn** [comment]
> Sorry, I may be wrong but what I'm saying is this is the only property you should expect to see returned from the API as your object as it has the `read` group but in your successful response, this field is not there either, so perhaps you aren't submitting it and is not included because it is null?
> 
> ```
>       /**
>        * @Groups("read")
>        * @ORM\Column(type="string", length=255, nullable=true)
>        */
>       private $full_name;
> ```
> 
> Whereas the fields you get in your successful version, when using the annotation `@Groups("write")` will not be included in the response because of `"normalization_context"={"groups"={"read"}}`. If you want those returned as well, use `@Groups({"write","read"})` on the fields perhaps?

here I made write and read groups to the properties

```
 /**
     * @ApiProperty(identifier=true)
     * @Groups({"write","read"})
     * @SerializedName("first_name")
     */
    private $first_name;

    /**
     * @Groups({"write","read"})
     */
    private $last_name;

    /**
     * @Groups("read")
     */
    private $full_name;
```

And i still got this 
![image](https://user-images.githubusercontent.com/70708109/104627540-d21f7d80-569f-11eb-842a-a54f87d99e0f.png)

Its like some weird bug

**Comment by gediminasnn** [comment]
Welp,
![image](https://user-images.githubusercontent.com/70708109/104627714-0eeb7480-56a0-11eb-9da1-612f067bbfa0.png)

So in the schemas it does show that write have those properties, but it doesnt suggest in request body

**Comment by silverbackdan** [comment]
After changing the groups did you clear your cache? I know I'm not a maintainer, just trying to help - but I use API Platform a lot including the groups and it is a well tested library.

That schema shows when it is taking your input object to write to the database it'll use `first_name` and `last_name` fields, and then with that object it'll serialize the fields `full_name` for the user output (i.e. what you see in the response area of OpenAPI)

**Comment by silverbackdan** [comment]
I'm very sorry for my misunderstanding of your issue - I realise now when you say "doesn't work" I thought it was not working in the API. I see now you're referring to the API documentation example input. I thought the screenshot was the output you had after making a POST request.

**Comment by rugolinifr** [comment]
Declare your properties with camel case instead of snake case. The serializer expects camelcase to match your properties with getters/setters.

**Comment by andrekutianski** [comment]
Did you try the new Annotation? 

```php
#[ApiResource(
    mercure: true,
    normalizationContext: ['groups' => ['read']],
    denormalizationContext: ['groups' => ['write']],
)]
class Myclass ...
```

Worked for me on v2.6

![image](https://user-images.githubusercontent.com/5316107/108612333-83fc4900-73c6-11eb-8c5c-e5af7f105b16.png)

**Comment by andrekutianski** [comment]
My case is a little stranger than yours (I think). When I use _normalizationContext_ and _denormalizationContext_ Swagger generates two different schemas. For example (my real case):

```php
...
#[ApiResource(
    mercure: true,
    normalizationContext: ['groups' => ['read']],
    denormalizationContext: ['groups' => ['write']],
)]
Class Denuncia {
  
     /**
     * @var \Ramsey\Uuid\UuidInterface
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="CUSTOM")
     * @ORM\CustomIdGenerator(class=UuidGenerator::class)
     * @ORM\Column(type="uuid", unique=true)
     *
     * @ApiProperty(identifier=false)
     *
     */
    public $id;

    /**
     * Protocolo da denúncia
     *
     * @ORM\Column(type="string", length=255)
     *
     * @ApiProperty(identifier=true)
     *
     * @Groups("read")
     */
    public $protocol;

...
}
```

I get two schemas from Swagger:

![image](https://user-images.githubusercontent.com/5316107/108612544-8b245680-73c8-11eb-90b6-ce59f337573b.png)

Schema is showing or hidden variables as _Groups()_ says but my Hydra Admin dos did not know which to use, and eventually, Murphy's law wins and Hydra tries to use the _Denuncia.jsonld-write_ that don't have the _$protocol_ var available and as a result property is not available on API Schema.

![image](https://user-images.githubusercontent.com/5316107/108612674-9c219780-73c9-11eb-991c-294888b7fddc.png)

**Comment by andrekutianski** [comment]
I believe I understand what is happening in my case. When a property is out of the _denormalizationContext_  the `"@context"` of `hydra:Collection`.

**Whit** _denormalizationContext_:
```json
{
    "@context": {
        "@vocab": "https://api.test/docs.jsonld#",
        "hydra": "http://www.w3.org/ns/hydra/core#",
        "id": "Denuncia/id",
        "cidadao": "Denuncia/cidadao",
        "protocol": "Denuncia/protocol",
        "status": "https://schema.org/status",
        "message": "Denuncia/message",
        "anonymous": "Denuncia/anonymous",
        "streetAddress": "https://schema.org/streetAddress",
        "addressNumber": "Denuncia/addressNumber",
        "district": "Denuncia/district",
        "addressLocality": "https://schema.org/addressLocality",
        "addressRegion": "https://schema.org/addressRegion",
        "addressComplement": "Denuncia/addressComplement",
        "postalCode": "https://schema.org/postalCode",
        "addressCountry": "https://schema.org/addressCountry",
        "createdAt": "Denuncia/createdAt",
        "updatedAt": "Denuncia/updatedAt"
    }
}
```
 I have `"protocol": "Denuncia/protocol"`

**Whitout** _denormalizationContext_

```json
{
    "@context": {
        "@vocab": "https://api.test/docs.jsonld#",
        "hydra": "http://www.w3.org/ns/hydra/core#",
        "id": "Denuncia/id",
        "cidadao": "Denuncia/cidadao",
        "status": "https://schema.org/status",
        "message": "Denuncia/message",
        "anonymous": "Denuncia/anonymous",
        "streetAddress": "https://schema.org/streetAddress",
        "addressNumber": "Denuncia/addressNumber",
        "district": "Denuncia/district",
        "addressLocality": "https://schema.org/addressLocality",
        "addressRegion": "https://schema.org/addressRegion",
        "addressComplement": "Denuncia/addressComplement",
        "postalCode": "https://schema.org/postalCode",
        "addressCountry": "https://schema.org/addressCountry",
        "createdAt": "Denuncia/createdAt",
        "updatedAt": "Denuncia/updatedAt"
    }
}
```

**Comment by andrekutianski** [comment]
I believe that I resolve. In my case a moved the normalization_context to the operation:

```php
#[ApiResource(
    mercure: true,
    normalizationContext: ['groups' => ['read']],
    collectionOperations: [
        'get',
        'post' => [
            'normalization_context' => ['groups' => ['write']],
        ],
    ],
)]
```
Now the `@context` has the property and Hydra understudy which schema use.

**Comment by soyuka** [comment]
looks like this was the correct answer: 

Declare your properties with camel case instead of snake case. The serializer expects camelcase to match your properties with getters/setters.

@andrekutianski  may you open a new issue with your case? Thanks.

**Comment by MedKayed** [comment]
Mine was solved by declaring properties in in camelCase format (foundation_date didn't work , but foundationDate worked as charm)
