### ISSUE TITLE
Action without entity

### ISSUE THREAD

**Issue by cve** [api-platform/api-platform#176]
Hi,

I want to make post action which receives uploaded file for further processing, but when I set up custom collectionOperations and try to send JSON with encoded (base64) content of the file, then I receive "entity not found exception" in result. Is it possible to have an entity without "id" (persistance) or action without entity at all?

#### Import.php (POPO without @Entity annotation and without id)
````php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * A import.
 */
class Import
{
    /**
     * @var File
     *
     * @Assert\File
     */
    private $file;

    /**
     * @return File
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @param File $file
     */
    public function setFile($file)
    {
        $this->file = $file;
    }
}

````

#### resources.yml
````yaml
import:
    class: 'AppBundle\Entity\Import'
    itemOperations: ~
    collectionOperations:
        import:
            route_name: 'import'
````

#### ImportAction.php
````php
<?php

namespace AppBundle\Action;

use AppBundle\Entity\Import;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\Routing\Annotation\Route;

class ImportAction
{
    /**
     * @Route(
     *     name="import",
     *     path="/import",
     *     defaults={"_api_resource_class"=Import::class, "_api_collection_operation_name"="import"}
     * )
     * @Method("POST")
     */
    public function __invoke($data)
    {
        // I want have $data->file (decoded) as uploaded file here
        var_dump($data);
    }
}
````

**Comment by cve** [comment]
sorry I made a mistake... yaml file should be named api_resources.yml not resources.yml..., now it works :) thanks.

**Comment by abysKri** [comment]
I'm testing this code, but how to format the json uploaded file ?
AP throw an error: Cannot validate values of type \"NULL\" automatically. Please provide a constraint.
Thanks


In swagger ui, the import json format:
{
  "file": "string"
}

**Comment by dunglas** [comment]
@abysKri Please open a new issue if you're sure that it's a bug as it doesn't look related with this one, and paste the detailed stack trace. Also, if you're not sure that's a bug and want help, please try [StackOverflow](https://stackoverflow.com/questions/tagged/api-platform.com) or [the Slack channel first](https://api-platform.com/support).
