### ISSUE TITLE
Out of the box install. Warning for easyrdf/easyrdf/lib/EasyRdf

### ISSUE THREAD

**Issue by art-cg** [api-platform/api-platform#1762]
**API Platform version(s) affected**: 2.5.9

**Description**  
The actual Distro-Bundle does not work out of the box.
I can not edit an entity correct in the Admin-Tool. The enity update is saved, but the UI has an error.
Composer is sending the following error.

> _Generating optimized autoload files_
> Class EasyRdf_Parser_JsonLd located in ./vendor/easyrdf/easyrdf/lib/EasyRdf/Parser/JsonLdImplementation.php does not comply with psr-0 autoloading standard. Skipping.
> Class EasyRdf_Serialiser_JsonLd located in ./vendor/easyrdf/easyrdf/lib/EasyRdf/Serialiser/JsonLd_real.php does not comply with psr-0 autoloading standard. Skipping.
> 

**How to reproduce**  
Fresh install the distro and try to edit an entity with Admin-Tool.

**Possible Solution**  
A solution could be a new version of "api-platform/schema-generator" with the newer Version of "easyrdf/easyrdf" like in master-Branch. In the actual v.2.2.2 the requirement for easyrdf/easyrdf is still on v0.9.3

I fixed it for me by adding these line to composer.json. But that ist just a temporary fix.
"minimum-stability": "dev",
"prefer-stable": true

Than install newest easyrdf/easyrdf. I am not sure if it should used with "-dev"
docker-compose exec php composer req easyrdf/easyrdf "dev-master"

I updated symfony to 5.2,* as well.

**Comment by dunglas** [comment]
This will be fixed by https://github.com/api-platform/schema-generator/pull/204
