### ISSUE TITLE
GraphQL / API Platform problem with nested objects for create/update mutation

### ISSUE THREAD

**Issue by marcinmkot** [api-platform/api-platform#1771]
**API Platform version(s) affected**: 2.5

**Description**  

I have a problem with API Platform. I cant correctly generate GraphQL Schema. I have two Entities: Post and PostContent as you can see in the code attached.
 
There is a One To One relation between these objects, but my schema is not working correctly.
 
Instead of a nested object I am getting a foreign key (String) for create/update mutations.
 
I want to have a nested object of the PostInput type, not a String.
 
Pleease help :) 
 
I am getting sth like below: 
 

    type createPostInput {
      postContent: String!
      clientMutationId: String
    }

 
but I want to get:
 

    type createPostInput {
      postContent: postContentInput!
      clientMutationId: String
    }

 
so that I can send a json like below:
 

    {
      "post": {
        "postContent": { "content": "sample content" }
      }
    }

 

**How to reproduce**  

Here are my classes Post.php, PostContent.php and PostInput.php: https://stackblitz.com/edit/typescript-gzwwwx

Post.php:

    <?php
    /**
     * Class Post
     * @package App\Entity
     * @ApiResource(
     *     input=PostInput::class,
     *     normalizationContext={"groups"={"user:read"}},
     *     denormalizationContext={"groups"={"user:write"}},
     * )
     * @ORM\Entity
     * @ORM\Table(name="post")
     */
    class Post
    {
    
        /**
         * @ORM\Id()
         * @ORM\GeneratedValue
         * @ORM\Column(type="integer", name="id")
         */
        private $id;
    
        /**
         * @var PostContent|null
         * @ORM\OneToOne(targetEntity="PostContent", cascade={"persist"})
         * @Groups({"user:read", "user:write"})
         * @ORM\JoinColumn(name="post_content_id", referencedColumnName="id", nullable=true)
         */
        public ?PostContent $postContent;
    
            /**
         * @return PostContent
         */
        public function getPostContent(): PostContent
        {
            return $this->postContent;
        }
    
        /**
         * @param PostContent|null $postContent
         * @return $this
         */
        public function setPostContent(?PostContent $postContent): self
        {
            $this->postContent = $postContent;
            return $this;
        }
    
        public function getId()
        {
            return $this->id;
        }
    }

PostContent.php: 

    <?php
    
    /**
     * Class PostContent
     * @package App\Entity
     * @ApiResource(
     *     normalizationContext={"groups"={"user:read"}},
     *     denormalizationContext={"groups"={"user:write"}},
     * )
     * @ORM\Entity
     * @ORM\Table(name="post_content")
     */
    class PostContent
    {
        /**
         * @ORM\Id()
         * @ORM\GeneratedValue
         * @ORM\Column(type="integer", name="id")
         */
        public $id;
    
    
        public Post $post;
    
        /**
         * @param Post $post
         * @return $this
         */
        public function setPost(Post $post): self
        {
            $this->post = $post;
            $post->setPostContent($this);
    
            return $this;
        }
    
        /**
         * @return Post
         */
        public function getPost(): Post
        {
            return $this->post;
        }
    
    }

PostInput.php:

    <?php
    
    /**
     * Class PostInput
     * @package App\Entity
     */
    class PostInput
    {
        /**
         * @var PostContent
         * @Groups({"user:read", "user:write"})
         */
        public PostContent $postContent;
    
        public function getPostContent(): PostContent
        {
            return $this->postContent;
        }
    
        public function setPostContent(PostContent $postContent): self
        {
            $this->postContent = $postContent;
            return $this;
        }
    }

**Possible Solution**  

-

**Additional Context**  

-

**Comment by alanpoulain** [comment]
Hello. Duplicated issue. See https://github.com/api-platform/core/issues/3258.
