### ISSUE TITLE
Limit Depth of Many to Many is not working

### ISSUE THREAD

**Issue by ZED-Magdy** [api-platform/api-platform#1778]
**API Platform version(s) affected**: x.y.z

**Description**  
Trying to make a subresource for many to many related entities with max depth = 1 doesnt remove the nested route

**How to reproduce**  
### I have 3 Entities
- Motherboard
- Processor
- Ram
```php
@ApiResource
class Motherboard
{
     /**
     * @ORM\ManyToMany(targetEntity=Processor::class, mappedBy="motherboards")
     * @ApiSubresource(maxDepth=1)
     */
    private $processors;

    /**
     * @ORM\ManyToMany(targetEntity=Ram::class, inversedBy="motherboards")
     * @ApiSubresource(maxDepth=1)
     */
    private $rams;
}
```
```php
@ApiResource
class Processor
{
   /**
     * @ORM\ManyToMany(targetEntity=Motherboard::class, inversedBy="processors")
     * @ApiSubresource(maxDepth=1)
     */
    private $motherboards;
}
```
```php
@ApiResource
class Ram
{
    /**
     * @ORM\ManyToMany(targetEntity=Motherboard::class, mappedBy="rams")
     * @ApiSubresource(maxDepth=1)
     */
    private $motherboards;
}
```
The error
```
Route pattern "/api/rams/{id}/motherboards/{motherboards}/processors/{processors}/motherboards/{processors}/rams.{_format}" cannot reference variable name "processors" more than once.
```
I`ve been searching google/documentation for 4hrs and didnt find any solution

**Comment by ZED-Magdy** [comment]
does anyone even look at issues?

**Comment by silverbackdan** [comment]
Hi Zed, just another API Platform user here but it may be worth raising this in the core repository instead of the template. The maintainers are very active and always working through issues. https://github.com/api-platform/core

**Comment by soyuka** [comment]
related to https://github.com/api-platform/core/pull/3616 or https://github.com/api-platform/core/issues/3982 which were both fixed pending release
