### ISSUE TITLE
Why RequestAttributesExtractor class is mark as internal

### ISSUE THREAD

**Issue by piotrbrzezina** [api-platform/api-platform#178]
Hi 

Why RequestAttributesExtractor class is marked as internal? I would like to use it in my listeners but and I'm not sure if I can use it. 

Can the Internal annotation be removed from this class?

Thanks

**Comment by tsurowiec** [comment]
The same here - since RequestAttributesExtractor is marked as @internal - what is the proper way to extract the Resource from Request in our Listeners.

**Comment by dunglas** [comment]
We marked this class as internal because its API may still change. There is no BC promise for this class for now.

You can either:

* Use it but be aware that it can change in future versions
* Copy its logic in your own listener (or create your own utility class)

**Comment by piotrbrzezina** [comment]
thanks
Now everything is clear
