### ISSUE TITLE
 disable_type_enforcement: issue

### ISSUE THREAD

**Issue by Cenarius-io** [api-platform/api-platform#1786]
**API Platform version(s) affected**: "api-platform/api-pack": "^1.2"

**Description**  
Hi!
I use the following setup (yaml config) to avoid the unnecessary storing of null values:

```
denormalization_context:
    disable_type_enforcement: true
```

It works for the "simple fields", but not for the references (mongoDB).
Is it a bug or the expected result?

**Comment by lucasgranberg** [comment]
What kind of data do you pass in and what does your model look like?

**Comment by Kenariosz** [comment]
Yaml config:

    shortName: 'attribute'

    attributes:
        route_prefix: '/catalog'

    collectionOperations:
        post:
            method: 'POST'
            security_post_denormalize: 'is_granted("attribute:collection:post", object)'
            denormalization_context:
                disable_type_enforcement: true

Part of a model:
```
/**
 * @ODM\Document(collection="catalog.attributes")
 * @ODM\InheritanceType("SINGLE_COLLECTION")
 * @ODM\DiscriminatorField("type")
 * @ODM\DiscriminatorMap(AbstractAttribute::DISCRIMINATOR_MAP)
 * @DiscriminatorMap(typeProperty="type", mapping=AbstractAttribute::DISCRIMINATOR_MAP)
 * @NotUsedAsVariationAttribute()
 */
abstract class AbstractAttribute implements MerchantRelatedBaseInterface
{
    public const TYPE = '?';

    public const DISCRIMINATOR_MAP = [
        BooleanValue::TYPE           => BooleanValue::class,
        TextValue::TYPE              => TextValue::class,
        IntegerValue::TYPE           => IntegerValue::class,
        FloatValue::TYPE             => FloatValue::class,
    ];

    /**
     * @var string
     * @ODM\Id()
     */
    private $id;

    /**
     * @var array
     * @ODM\Field(type="hash")
     * @Assert\NotNull()
     * @Assert\NotBlank()
     */
    private $label = [];

    /**
     * @var string
     * @ODM\Field(type="string")
     * @Assert\NotBlank()
     * @Assert\Type(type="string")
     */
    private $name;

    /**
     * @var AttributeRole|null
     * @ODM\ReferenceOne(targetDocument=AttributeRole::class, inversedBy="attributes", storeAs="id", nullable=true)
     */
    private $role;
...
public function getRole(): ?AttributeRole
    {
        return $this->role;
    }

    public function setRole(?AttributeRole $role): self
    {
        $this->role = $role;

        return $this;
    }
...
```

As you can see i enabled the null value on the getter and setter as well, but i had to use the nullable=true on the role field. Otherwise i got an error (400): it cannot be null. So ican't turn off the ODM metadata validation.

**Comment by felipyamorim** [comment]
I have a similar problem, the option "disable_type_enforcement" does not work for relationship fields. any workaround ?

**Comment by Kenariosz** [comment]
@felipyamorim unfortunately i haven't got any workaround. Currently i use the nullable=true flag on the relation fields.
If i have a little bit more time, i'd like to take a deeper dive to resolve this issue.
