### ISSUE TITLE
Error when mapped entity is not a resource

### ISSUE THREAD

**Issue by napalm33700** [api-platform/api-platform#179]
Do you change something recently about mapped entity ?

After updating composer there are errors when mapped entities are not resource 

Ex:
`{
  "@context": "/contexts/Error",
  "@type": "Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Resource \"AppBundle\\Entity\\Catalog\\Asset\" not found."
}`

Mapping
`    /**
     * @ORM\ManyToMany(targetEntity="Asset", fetch="EAGER")
     * @ORM\JoinTable(name="article_asset",
     *      joinColumns={@ORM\JoinColumn(name="article_code", referencedColumnName="code")},
     *      inverseJoinColumns={@ORM\JoinColumn(name="asset_id", referencedColumnName="id")}
     *      )
     * @Groups({"product", "article", "operation_detail", "cart", "wish_list_detail"})
     */
    private $articleAssets;`

**Comment by dunglas** [comment]
Do you use the YAML mapping format?

**Comment by soyuka** [comment]
`targetEntity="Asset"` why not the full namespace (saying this because `AppBundle\Entity\Catalog\\Asset` looks weird)? Is the `use` statement included? Is it an actual resource which is declared as `@ApiResource`?

In YAML the `class` property has been removed:

Before:
```
resources:
    product:
       class: 'Product\ProductBundle\Entity\Product'
```

Today:
```
resources:
    'Product\ProductBundle\Entity\Product': ~
```

**Comment by napalm33700** [comment]
There is a use and i use ApiResource Annotation
Entity Asset is not a declared  resource.  
As I mention before everything work fine since v2 alpha. I will post the resource annotation as soon i  can.

**Comment by soyuka** [comment]
This is the problem IMO:

> Entity Asset is not a declared resource.

**Comment by napalm33700** [comment]
is it mandatory now that every entity  has to be e resource ?
If yes since when and what is the purpose  ?  I don't want my entities to be exposed

**Comment by dunglas** [comment]
No, it's not. Can you post enough code and config to reproduce the bug?

**Comment by napalm33700** [comment]
'all my entities' ...

**Comment by napalm33700** [comment]
I will post it tomorrow morning i'm not a work now

**Comment by soyuka** [comment]
> No, it's not. Can you post enough code and config to reproduce the bug?

Though this error is caused by a `ResourceClassNotFoundException` right? I'd assume that it's because of a `$resourceMetadata->create()` that does not catch this exception. Hence the `fetch="EAGER"` I'd (again assume) [this one](https://github.com/api-platform/core/blob/202aabcc67b925bbc94596b50970073ca21dbbf6/src/Bridge/Doctrine/Orm/Extension/EagerLoadingExtension.php#L110).

**Comment by dunglas** [comment]
@soyuka we should join only if Doctrine knows `$resourceClass` (in the other case, it can be a VO or anything else). Can you provide a hotfix before the stable release?

**Comment by soyuka** [comment]
Ofc
