### ISSUE TITLE
name_converter in snake case remove the parameters in swagger

### ISSUE THREAD

**Issue by aratinau** [api-platform/api-platform#1791]
**API Platform version(s) affected**: 2.6

**Description**  
I change the name converter as the documentation says it on this page: https://api-platform.com/docs/core/serialization/#name-conversion

But when I go back to the swagger page and go to POST the Request body disappeared. And if I remove my changes the Request body go back as:

```json
{
  "email": "user@example.com",
  "isExecutive": true
}
```

Thank you for your help

**Comment by soyuka** [comment]
https://github.com/api-platform/core/issues/3997 duplicate
