### ISSUE TITLE
api:swagger:export doesn't generate v2 specs

### ISSUE THREAD

**Issue by mlr-it** [api-platform/api-platform#1792]
**API Platform version(s) affected**: v2.5.7

**Description**  

the command `php bin\console api:swagger:export` generates version 3 json file
```{
    "openapi": "3.0.2",
    "info": {
        "title": "Api Platform",
        "version": "1.0.0"
    } ...
```
**How to reproduce**  

php bin\console api:swagger:export 

**Additional Context**  

i used also this command:
`php bin\console api:openapi:export --output=swagger_docs2.json --spec-version 2`
but it shows this error :
`This tool only supports versions 3 of the OpenAPI specification ("2" given)`

thanks

**Comment by soyuka** [comment]
1) make sure you configured the `swagger_version` to `[2]` or `[2,3]` in the `api_platform.yaml` file
2) use bin/console api:swagger:export --spec-version=2

**Comment by mlr-it** [comment]
Thank you very much! it works like a charm
