### ISSUE TITLE
ArrayObject unknown in JwtDecorator documentation

### ISSUE THREAD

**Issue by GuiReco** [api-platform/api-platform#1794]
**API Platform version(s) affected**: 2.6.1

**Description**  
I'm creating the decorator according to [the documentation](https://api-platform.com/docs/core/jwt/#adding-endpoint-to-swaggerui-to-retrieve-a-jwt-token)

**How to reproduce**  
By accessing to the https://localhost/docs page, I encounter a unrecognized ArrayObject error.

**Possible Solution**  
Add a `use ArrayObject;` on top of the code.

**Additional Context**  
<img width="1070" alt="Capture d’écran 2021-02-04 à 17 47 37" src="https://user-images.githubusercontent.com/11681755/106926706-a7aa6880-6711-11eb-80da-48590ecaa561.png">

**Comment by wb-all** [comment]
`use ArrayObject;` or used new \ArrayObject([]);
