### ISSUE TITLE
Node_modules are empty in project files side but populated in container that produce autocompletion issues in IDE

### ISSUE THREAD

**Issue by ksom** [api-platform/api-platform#1798]
**API Platform version(s) affected**: 2.6.1

**Description**  
Node_modules are populated only in container but empty in my project folder this produce autocompletion issues on my Jetbrains IDE.

**How to reproduce**  
1: Download last Api-Platform version
2: run `docker-compose pull`
3: run `docker-compose up -d`

**Additional Context**  
OS: MacOS BigSur 11.0.1

I also tried to empty my node_modules in container and re-run `yarn install --check-files`. I also tried to run `docker-compose stop` followed by `docker-compose up -d`. Still doesn't work.

**Comment by alanpoulain** [comment]
That's because a volume is used for performance reasons: https://github.com/api-platform/api-platform/blob/41d1214eadaf2e46a4284cb1852f17594a88d8d2/pwa/Dockerfile#L23.
You can share the volume with the host if you want but I don't think it's a good idea with Mac.

**Comment by ksom** [comment]
@alanpoulain I'd like to keep that volume for performance issue. Do you recommend to install dependencies OS side too for having autocompletion ?

**Comment by alanpoulain** [comment]
Sure I don't see the harm in doing that.

**Comment by ksom** [comment]
@alanpoulain Thank you very much for your responsiveness !
