### ISSUE TITLE
Custom data provider + filtering

### ISSUE THREAD

**Issue by djoos** [api-platform/api-platform#180]
Hi there,

anyone got a (rough and ready) gist/heads up on how to handle filtering in v2 in a custom data provider?

In v1 we would check and filter out data in the getCollection()-method, but the request is no longer available in that method.
```
            foreach ($resource->getFilters() as $filter) {
                if ($filter instanceof FilterInterface) {
                    if(!empty($request->query->all()))
                    {
                        foreach ($request->query->all() as $k => $v) {
...
```

Thanks in advance!

Kind regards,
David

P.S. This task is related to #118 (Migration from v1 to v2).

**Comment by dunglas** [comment]
You can inject the `request_stack` service in your data provider class.

**Comment by djoos** [comment]
Perfect - got it, thanks!
