### ISSUE TITLE
Change client from react (Next.js) to vue (Nuxt.js)

### ISSUE THREAD

**Issue by d0niek** [api-platform/api-platform#1803]
Hi!
I want to change ReactJS to VueJS. My steps:

- Download api-platform ver. 2.6.2,
- Build images,
- Delete all files from **./pwa** (Dockerfile, and .* files left),
- Follow https://api-platform.com/docs/client-generator/nuxtjs/ with command prefix `docker-compose run --rm pwa ...`,
- Command `... yarn create nuxt-app your-app-name` creates **./pwa/your-app-name** directory so I move all files to **./pwa**,
- Once more build pwa images `docker-compose build pwa`,
- Run stack `docker-compose up`.

All request from localhost are going to `api` instead of `pwa` !? o0

Am I miss something from docs? I shouldn't delete files from **./pwa** (I don't want to mess with old React files, I want fresh install of Vue)?

**Comment by d0niek** [comment]
To fix an issue remember to update [caddyfile](https://github.com/api-platform/api-platform/blob/main/api/docker/caddy/Caddyfile#L18). Read paths from browser network logs and add them here.

**Comment by HugoFerrant** [comment]
Hello @d0niek 
I've run into the exact same issue, then I saw your issue x)
I guess the documentation is not quite up-to-date with the 2.6 version and the revamping of the Distribution.
Anyway, I tried with no success to "Read paths from browser network logs and add them here." could you please be more specific and/or give your caddyfile as an example ?
Thx for the clue !

**Comment by d0niek** [comment]
Hi! I'm not in front of my computer so I can't share with you my caddyfile now.

You should check browser network logs and look for requests which got 404 response code and response was created by symfony. If you are sure that symfony shouldn't handles that request add that path to caddyfile.

If didn't help, later I can share my caddyfile

**Comment by HugoFerrant** [comment]
@d0niek  Now I think I don't have the exact same problem : I have WSOD when trying to access my app in my browsers (but /docs is still OK) caused by a 502 error ( in docker logs I have "dial tcp 172.26.0.4:3000: connect: connection refused" printed by Caddy)

**Comment by d0niek** [comment]
My changes in **caddyfile**:

```
-    || {path}.startsWith("/_next")
+    || {path} == "/v.png"
+    || {path} == "/vuetify-logo.svg"
+    || {path}.startsWith("/_loading")
+    || {path}.startsWith("/_nuxt")
+    || {path}.startsWith("/__webpack_hmr")
```

**Comment by plaub** [comment]
hi, i had the same problem as @HugoFerrant and solved it by adding: 

ENV NUXT_HOST=0.0.0.0
ENV NUXT_PORT=3000

to the pwa Dockerfile.

**Comment by d0niek** [comment]
I didn't change **Dockerfile** but my **package.json** has `scripts/dev: "nuxt-ts -H 0.0.0.0"`

**Comment by HugoFerrant** [comment]
So much new leads to try 😮 thanks a lot you two, I'll keep you posted!

**Comment by HugoFerrant** [comment]
OK so after some testing I needed indeed @plaub the env vars in my Dockerfile.
I also needed something that none of us have mention atm : changing my `pwa/config/entrypoint.js`, from `export const ENTRYPOINT = "http://caddy";` to `export const ENTRYPOINT = typeof window === "undefined" ? "http://caddy" : window.origin;` (I've take that from the default react client)
