### ISSUE TITLE
caddy ssl block some countries

### ISSUE THREAD

**Issue by ahbaqdadi** [api-platform/api-platform#1810]
**Description**  
caddy ssl block some country

**Example**  
for example i want to request from iran country but ssl block my ip

**Comment by dunglas** [comment]
Is it related to Caddy? Caddy uses Let's Encrypt by default. Is Let's Encrypt blocked in Iran?

As a workaround, you can use any other certification authority providing an ACME endpoint, or custom certificates: https://caddyserver.com/docs/caddyfile/directives/tls

**Comment by ahbaqdadi** [comment]
Yes related to caddy when i  using `traefik` with ssl i don't have problem, but if i want to use default docker-compose and docker file configuration related to api platform i get that issue

**Comment by ahbaqdadi** [comment]
I'm using Let's Encrypt

**Comment by francislavoie** [comment]
Could you be more specific? What are in your logs?

**Comment by ahbaqdadi** [comment]
I got nothing from logs

**Comment by francislavoie** [comment]
You must get _something_. Caddy outputs plenty of logs at startup. Check the container logs.
