### ISSUE TITLE
Problem with OpenApi api-platform 2.6

### ISSUE THREAD

**Issue by john-dufrene-dev** [api-platform/api-platform#1815]
Hi,

I'm using api-platform 2.5 with old version of the Swagger. I have some custom route defined with this doc : https://api-platform.com/docs/v2.5/core/jwt/ . Since I upgrade to 2.6 version of Api-platform I need to change my route to OpenApi.

- Possible to keep the old version and use SwaggerDecorator or I'm oblige to switch to new version with OpenApi ?
- I don't arrive to reproduce properly example in https://api-platform.com/docs/core/jwt/ without errors, I think it's my php 7.4 version (not using php 8), someone have an example in php 7.4 ?

Thanks for your help !

**Comment by dominiquefournier** [comment]
The example use the new PHP8 syntax : https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments
Of course, every body is already in PHP8 :-( !
I try to do a working example but it is awful. Is it possible to add the setters ? We can in this case use ->setPost(), ->setGet() and al to define cleanly the content ?

Here a working version :
[JwtDecorator.php.zip](https://github.com/api-platform/api-platform/files/5988779/JwtDecorator.php.zip)

**Comment by john-dufrene-dev** [comment]
@dominiquefournier Thanks a lot ! Its working perfectly

**Comment by Thibault-OC** [comment]
@dominiquefournier  Thanks !

**Comment by byhaskell** [comment]
@dominiquefournier I helped out, last times I spent hours on this, and today I immediately found your comment. Thank you very much.
