### ISSUE TITLE
Unable to generate IRI for an entity with an url prefix containing a placeholder

### ISSUE THREAD

**Issue by KaporalK** [api-platform/api-platform#1818]
**API Platform version(s) affected**: 2.6.2 (did not test this on other version)

**Description**  
I have an orm+api-ressource entity and if i set up an url prefix with a placeholder inside, api-platform give me this error
`Unable to generate an IRI for App\Entity\MyEntity`

**How to reproduce**  
Call get/post for an entity with this anotation set up
````php
/**
 *@ApiResource(
 *     routePrefix="/somePerfix/{variablePlaceHolder}"
 * )
 */
 ````

**Possible Solution**  
I can fix this issue by decorating this service `api_platform.iri_converter` but i did not find a nice way to fix the issue.
I did not find an access to the configured urlPrefix for the entity inside the IriGenerator. So the fix is kinda static and i don't like that

Is there any way to acces the urlPrefix config inside this service so that my fix looks better ? 

edit: And the bug is fixed also if i delete the `{placeholder}` from the prefix, of course i need it

**Comment by soyuka** [comment]
Using a placeholder in the prefix is not supported. I suggest that you decorate our ApiLoader which loads the routes using your own route generation. If sufficient take a look at the OperationPathResolverInterface that may help you do so.
