### ISSUE TITLE
GithubAction: PHPUnit call fails

### ISSUE THREAD

**Issue by art-cg** [api-platform/api-platform#1819]
**API Platform version(s) affected**: 2.6.2

**Description**
GithubActions "CI" fails.
- name: PHPUnit
  run: docker-compose exec -T php bin/phpunit

Eror-message:
Run docker-compose exec -T php bin/phpunit
docker-compose exec -T php bin/phpunit
shell: /bin/bash -e {0}
OCI runtime exec failed: exec failed: container_linux.go:370: starting container process caused: exec: "bin/phpunit": permission denied: unknow

**How to reproduce**  
push code to github and check Github Actions

**Possible Solution**  
Maybe
run: docker-compose exec -T php php bin/phpunit

**Additional Context**  
Anyone else getting this error?

**Comment by soyuka** [comment]
```
✗)❯ docker-compose exec -T php bin/phpunit
```

Works to me.

**Comment by cesar-sebastian** [comment]
I have same error
![Error](https://user-images.githubusercontent.com/1793704/115482470-2436e880-a225-11eb-97ec-8d15efd1205f.PNG)

**Comment by art-cg** [comment]
Can you check my solution? I changed ci.yaml for other reasons. So i can not test it directly.
Do you have this problem under windows or other os? I had it under windows.

I changed this file.
/api/docker/php/docker-entrypoint.sh

Add the following lines after this Line (should be 14.)
`ln -sf "$PHP_INI_RECOMMENDED" "$PHP_INI_DIR/php.ini"`


```
# Fix START
if [ "$APP_ENV" != 'prod' ]; then
   # https://github.com/api-platform/api-platform/issues/1819
   chmod +x bin/phpunit
fi
# FIX END
```

**Comment by cesar-sebastian** [comment]
Cool, that working. 

Thanks
