### ISSUE TITLE
shortName on annotated ApiResource

### ISSUE THREAD

**Issue by djoos** [api-platform/api-platform#182]
Hi there,

the expected behaviour of the following annotation setting the shortName attribute would be that I should be able to spot "foo_bar" in the entrypoint ("fooBar": "/foo_bar"), rather than "blurb", however that doesn't seem to work as all I can see is "blurb": "/blurb"...

Is the idea behind shortName still the same as it was in v1?

```
/**
 * @ApiResource(attributes={"shortName"="FooBar"})
 * @ORM\Entity
 * @ORM\Table(name="doesntreallymatter")
 */
class Blurb {
	...
}
```

Thanks in advance for your advice!

Kind regards,
David

**Comment by dunglas** [comment]
Can you try this:

```php
/**
 * @ApiResource(shortName="FooBar")
 * @ORM\Entity
 * @ORM\Table(name="doesntreallymatter")
 */
class Blurb
{
    // ...
}
```

**Comment by djoos** [comment]
Unfortunately that throws the following exception: `Couldn't find constant shortName, class Path\\To\\Entity\\Blurb.`

FYI: 2.0.0-rc.6

**Comment by djoos** [comment]
Sorry, scrap my previous reply... #facepalm

Using `* @ApiResource(shortName="FooBar")` results in having "fooBar": "/foo_bar" when checking the entrypoint - thanks for your quick feedback!
David

**Comment by mrtnzagustin** [comment]
is there a way to change just the shortname and not the endpoint? 
My example: i have a class named "Accion". By default api-platform create:
- "@context": "/api/contexts/Accion"
- "@id": "/api/accions"

If i change shortName to "Acciones" (spanish) i get:
- "@context": "/api/contexts/Acciones"
- "@id": "/api/acciones"

What i want (just change the endpoint):
- "@context": "/api/contexts/Accion"
- **"@id": "/api/acciones"**

Is there another property to do that?

**Comment by mrtnzagustin** [comment]
@dunglas is there a apiresource options doc reference?

**Comment by mrtnzagustin** [comment]
Quick fix. Please let me know if there is a way to change the endpoint prefix globally for al item and collection operations. Regards.

```php
/**
 * Accion
 * @ORM\Table(name="portal_accion", indexes={@ORM\Index(name="fk_estado_actual", columns={"id_estado_actual"}), @ORM\Index(name="fk_estado_siguiente", columns={"id_estado_siguiente"})})
 * @ORM\Entity
 * @ApiResource(
 *      normalizationContext={"groups"={"getCollectionAccion"}},
 *      collectionOperations={
 *          "get"={
 * 				"path"="acciones"
 * 			}
 *      },
 *      itemOperations={
 *          "get"={
 * 				"path"="acciones/{id}"
 * 			}
 *      }
 * )
 * @ApiFilter(SearchFilter::class , properties={"tipoTramite.id":"exact","estadoActual.id":"exact"})
 * @ApiFilter(AccionUserFilter::class , properties={"null"})
 */
class Accion
{
```
