### ISSUE TITLE
Having 50 entities cause the docs to only display the last one

### ISSUE THREAD

**Issue by HugoFerrant** [api-platform/api-platform#1820]
**API Platform version(s) affected**: `2.6.2`

**Description**
Having 50 (or more) entities cause the docs to only display the last one (or more) and hides the 49 first, with no way to use them.

**How to reproduce**
Add the 50+ entities (handmade copy-pasted) [linked here](https://github.com/api-platform/api-platform/files/6022343/Entity.zip), and access the usual https://localhost/docs . You'll see only a few ones among the many you added.

**Possible Solution**
Once seeing only the last entities (sorted by name) are displayed, I presume it is a weird pagination bug, and what we are seeing is like a 2nd page.

**Additional Context**
My admin (fresh & clean too) seems to be broken too, but I'll have to investigate more to be sure it's linked.

PS: Maybe this should be in Swagger issues ? I'me kind of new to contributing 😇

**Comment by soyuka** [comment]
these are resources? it's weird to me you need to have an ApiResource attribute to make them show as resources.

**Comment by HugoFerrant** [comment]
@soyuka yes these are resources sorry for misleading

**Comment by HugoFerrant** [comment]
@soyuka all of these have the ApiResource attribute. Should I edit the issue ?

**Comment by soyuka** [comment]
I'm really confused it can not be possible that 50 resources are up and just a few are documented. Provide a reproducer so that I can take a look?

**Comment by HugoFerrant** [comment]
I did provide the reproduce process with a zip containing 50+ resources php classes. Did I miss something ?

**Comment by HugoFerrant** [comment]
I assume that since the issue is closed you might not receive notifications, so just in case : @soyuka ⤴️

**Comment by HugoFerrant** [comment]
Cause/Solution found, in case anyony faces this someday :
The issue is due to the very slow protocol used by WSL (used by Docker for Windows).
To fix this kind of issues, instead of storing your project files in the windows side (and accessing it with `/mnt/c/...` in wsl), you should store them on the linux wsl side (in \\wsl from windows).
