### ISSUE TITLE
Argument 4 passed to ApiPlatform\Core\OpenApi\Model\Parameter::__construct() must be of the type bool, string given, called in /srv/api/vendor/api-platform/core/src/OpenApi/Factory/OpenApiFactory.php

### ISSUE THREAD

**Issue by Lenny4** [api-platform/api-platform#1822]
**API Platform version(s) affected**: 2.6.2

**Description** 
The error:
```
Argument 4 passed to ApiPlatform\Core\OpenApi\Model\Parameter::__construct() must be of the type bool, string given, called in /srv/api/vendor/api-platform/core/src/OpenApi/Factory/OpenApiFactory.php on line 167
```
Where it happens:
As you can see in `ApiPlatform\Core\OpenApi\Model\Parameter` the 4th argument of the constructor is:
```php
bool $required = false
```
In `ApiPlatform\Core\OpenApi\Factory\OpenApiFactory` line `167`, we got this:
```php
$parameters[] = new Model\Parameter($parameter['name'], $parameter['in'], $parameter['description'] ?? '', $parameter['required'] ?? false, $parameter['deprecated'] ?? false, $parameter['allowEmptyValue'] ?? false, $parameter['schema'] ?? []);
```
![Api-platform-error](https://user-images.githubusercontent.com/25544892/108722866-e4ed6380-7523-11eb-9e94-e5e276f45475.png)
`$parameter['required']` is a string.

**How to reproduce**  
I don't have a clear way to reproduce this bug. It happens on every page of my symfony application where api platform is used.

**Possible Solution**  
- When the `$parameter['required']` is set, ensure that the value is a boolean
- Or
- Instead of `$parameter['required'] ?? false` => `isset($parameter['required']) ? $parameter['required'] === 'true' : false`

**Additional Context**  
Once fix, need to check if the others boolean parameters of the constructors are boolean and not string as for the `$required` parameter
```php
public function __construct(... bool $required = false, bool $deprecated = false, bool $allowEmptyValue = false, ..., bool $explode = false, bool $allowReserved = false ...)
```

**Comment by soyuka** [comment]
How did you configure this requirement ? It should be a boolean.

**Comment by Lenny4** [comment]
Hi @soyuka it was my bad, in my config I wrote:
```
 * "parameters" ={
 *                      {
 *                          "name" = "search",
 *                          "in" = "query",
 *                          "description" = "searched text",
 *                          "required" = "true",
 *                          "type" : "string",
 *                      },
```
Instead of:
```
 * "parameters" ={
 *                      {
 *                          "name" = "search",
 *                          "in" = "query",
 *                          "description" = "searched text",
 *                          "required" = true,
 *                          "type" : "string",
 *                      },
```
