### ISSUE TITLE
Service "PHP" failed to start. How can I solve it?

### ISSUE THREAD

**Issue by EricTrinh153** [api-platform/api-platform#1824]
**API Platform version(s) affected**: 2.6.2

**Description**  
Hi guys, I start to work on the getting started document of api platform but when I execute the command 
docker-compose up -d I received the error as below
![Screenshot from 2021-02-25 20-55-05](https://user-images.githubusercontent.com/58277362/109136015-c9948980-77ab-11eb-9dff-15afb3edba3e.png)
Could you please help me to figure it out?
Thank you so much!

**Comment by adham-hajji** [comment]
I have the same problem as @EricTrinh153, although dotenv appears to be correctly mapped into `autoload_classmap.php`. Can this problem be related to this recent commit: https://github.com/symfony/flex/commit/e472606b4b3173564f0edbca8f5d32b52fc4f2c9?

**Comment by adham-hajji** [comment]
It happens this commit do fix the issue (see https://github.com/composer/composer/issues/9722). `composer.json` and `composer.lock` files need to be updated.

**Comment by zmilan** [comment]
Hi, I'm totally new to the api-platform and I run into this same issue when I wish to give it a try and follow the "Getting Started" guide from the site. I have found this thread and I have solved it by forcing the composer to **update** dependencies inside `api/Dockerfile` file on line 81. I hope this could help someone :)
