### ISSUE TITLE
[Edited title] React admin unusable, unable to load and blocking other requests for platform, probably something with redirect to pwa

### ISSUE THREAD

**Issue by Antarian** [api-platform/api-platform#1825]
**API Platform version(s) affected**: 2.6.0-2.6.2

**Description**  
Docs and admin page is hanging without errors after any change and Chrome browser is loading \docs and \admin indefinitely.

**How to reproduce**  
Just change something in PWA react app part or ApiResource and refresh browser.

**Possible Solution**
- restarting Docker every change done to ApiResources or PWA?
- don't use \docs and \admin and only use Postman.
- wait if this will be somehow resolved for Caddy/Go lang? Issue: https://github.com/caddyserver/caddy/issues/3896

**Additional Context**  
Possibly related errors from Docker:
`{"level":"error","ts":1614298653.2000477,"logger":"http.log.access","msg":"handled request","request":{"remote_addr":"172.21.0.1:54626","proto":"HTTP/2.0","method":"GET","host":"localhost","uri":"/.well-known/mercure","headers":{"Caddy-Push":["1"],"Accept-Encoding":["gzip, deflate, br"],"Accept-Language":["en,sk-SK;q=0.9,sk;q=0.8,en-US;q=0.7"],"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9"],"Cache-Control":["max-age=0"],"User-Agent":["Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.96 Safari/537.36"]},"tls":{"resumed":false,"version":772,"cipher_suite":4865,"proto":"h2","proto_mutual":true,"server_name":"localhost"}},"common_log":"172.21.0.1 - - [26/Feb/2021:00:17:33 +0000] \"GET /.well-known/mercure HTTP/2.0\" 400 27","duration":0.001080793,"size":27,"status":400,"resp_headers":{"Server":["Caddy"],"Alt-Svc":["h3-32=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"],"X-Frame-Options":["DENY"],"X-Content-Type-Options":["nosniff"],"X-Xss-Protection":["1; mode=block"],"Content-Security-Policy":["default-src 'self' mercure.rocks cdn.jsdelivr.net"],"Content-Type":["text/plain; charset=utf-8"]}}
`
and
`{"level":"error","ts":1614298653.862272,"logger":"http.handlers.reverse_proxy","msg":"aborting with incomplete response","error":"http2: stream closed"}`

**Comment by jdutheil** [comment]
Same problem here, and is really annoying 'cause 9 times out of 10 I get stuck with the admin / docs pending indefinitely. Sometimes happens with the PWA too

Is there a fix somewhere ?

**Comment by Antarian** [comment]
@jdutheil if you kill admin in browser and refresh docs, they will work. Admin is a blocking whole server/docker when this happens.
I am not using admin for now.

**Comment by Autsider666** [comment]
I'm having the same issue. It also seems to make the page to page navigation in next.js VERY slow.

**Comment by senorLobito** [comment]
Confirming. Not only ReactAdmin. Also jumping between pages in NextJS sometimes hangs forever. I noticed there is combination of `"msg":"aborting with incomplete response","error":"http2: stream closed"` in caddy mentioned above and `_next/webpack-hmr` request in devtools which hangs forever. No idea whether and how it is connected.

**Comment by Autsider666** [comment]
You can fix it for now by disabling push in your Caddyfile (if your app isn't using it ofc)

**Comment by viviengenet** [comment]
Hi, still no fix if we want to use push in the Caddyfile? :/

**Comment by Soetens** [comment]
There does not seem to be a fix in place :-(
