### ISSUE TITLE
PhpPgAdmin support

### ISSUE THREAD

**Issue by shristov-iMeniu** [api-platform/api-platform#1829]
Hi,

I'm new to Docker and PostgreSQL, so I don't know how can I add a panel for database administration just like PhpMyAdmin for MySQL.

I think many people would appreciate this feature and I would do it, if I could or someone help me.

Thank you!

**Comment by djpremier** [comment]
A more complete alternative is pgAdmin (https://www.pgadmin.org/). Regarding the implementation is for your part, just put an image of the docker in the docker-compose and you will have the service available, or else export the database port to a secure network (preferably internal IP) and then connect. These are management tools that do not need to change the system.

**Comment by alanpoulain** [comment]
Thanks for the answer @djpremier.
However we don't use the issues anymore for support, I'm closing the issue.
