### ISSUE TITLE
Get resource's pagination attributes in custom data provider?

### ISSUE THREAD

**Issue by djoos** [api-platform/api-platform#183]
Hi there,

would it be possible to give me a heads up on the best way to retrieve a specific resource's pagination attributes (whether to paginate or not, the pagination items per page number,...) in a custom data provider? (specifically for getCollection-method usage obviously)

Thanks in advance for your feedback!
David

**Comment by dunglas** [comment]
You can inject the `api_platform.metadata.resource.metadata_factory` service in your provider and copy take inspiration from this method: https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php#L112-L122

**Comment by djoos** [comment]
Perfect, works like a treat; additionally also injecting the `api_platform.collection.pagination.items_per_page`-parameter so to use as a default when not set on the resource.

Thanks, have a great day!
David

**Comment by mvigneron** [comment]
Hi @djoos ,

Like you, I would like to have pagination in my custom data provider (get results from ElasticSearch) but I don't know what is the best way to do it. Do you can tell me how you did it ? if you have a code example, it would be very great ;-)

Thanks

**Comment by djoos** [comment]
Hi @mvigneron,

sure! Here a are some snippets...

The custom DataProvider's getCollection method:
```php
use Escape\PaginatorBundle\Lib\Pagerfanta; // see below
use Pagerfanta\Adapter\DoctrineCollectionAdapter;

public function getCollection(string $resourceClass, string $operationName = null)
{
    if(!$this->supports($resourceClass)) {
        throw new ResourceClassNotSupportedException();
    }

    $request = $this->requestStack->getCurrentRequest();

    $ac = new ArrayCollection();

    if(!empty($this->data)) {
        foreach($this->data as $element) {
            $ac->add($element);
        }

        if(!empty($request->query->all()))
        {
            foreach ($request->query->all() as $k => $v) {
                $ac = $this->filter($k, $v, $ac);
            }
        }
    }

    $adapter = new DoctrineCollectionAdapter($ac);
    $pagerfanta = new Pagerfanta($adapter);

    $resourceMetadata = $this->resourceMetadataFactory->create($resourceClass);

    $pagerfanta->setMaxPerPage(
        (int) $request->get(
            $this->itemsPerPageParameter,
            $resourceMetadata->getCollectionOperationAttribute(
                $operationName,
                'pagination_items_per_page',
                $this->globalItemsPerPage,
                true
            )
        )
    );

    $pagerfanta->setCurrentPage((int) $request->get($this->pageParameter, 1));

    return $pagerfanta;
}
```

So, the actual pagination logic is handled by [Pagerfanta](https://github.com/whiteoctober/Pagerfanta), which we've slightly tweaked to work with the ApiPlatform's PaginatorInterface:
```php
namespace Escape\PaginatorBundle\Lib;

use ApiPlatform\Core\DataProvider\PaginatorInterface;
use Pagerfanta\Pagerfanta as BasePagerfanta;

class Pagerfanta extends BasePagerfanta implements PaginatorInterface
{
    /**
     * Gets the current page number
     *
     * @return float
     */
    public function getCurrentPage(): float {
        return parent::getCurrentPage();
    }

    /**
     * Gets the last page
     *
     * @return float
     */
    public function getLastPage(): float {
        return parent::getNbPages();
    }

    /**
     * Gets the number of items by page
     *
     * @return float
     */
    public function getItemsPerPage(): float {
        return parent::getMaxPerPage();
    }

    /**
     * Gets the number of items in the whole collection
     *
     * @return float
     */
    public function getTotalItems(): float {
        return parent::getNbResults();
    }
}
```

And the pagination_items_per_page is set in config.yml as follows:
```yml
api_platform:
    collection:
        pagination:
            items_per_page: 20
```

Hope this helps!

Please do give me a shout if you have any further questions or remarks! (it's always great to have someone else read through and improve the code :-) )

Have a great day!
David

**Comment by mvigneron** [comment]
Hi @djoos 

Thanks for your help !

My case in a bit different of you because I want to search with elasticSearch, not with doctrine but your example had help me a lot.

custom Data provider : 

```
namespace AppBundle\DataProvider;


use ApiPlatform\Core\DataProvider\CollectionDataProviderInterface;
use ApiPlatform\Core\Exception\ResourceClassNotSupportedException;
use ApiPlatform\Core\Metadata\Resource\Factory\ResourceMetadataFactoryInterface;
use AppBundle\Entity\Offer;
use AppBundle\Entity\Shop;
use AppBundle\Service\SearcherService;
use Symfony\Component\HttpFoundation\RequestStack;

class ElasticsearchCollectionDataProvider implements CollectionDataProviderInterface
{
    private $searcherService;
    private $requestStack;
    private $resourceMetadataFactory;
    private $itemsPerPageParameter;
    private $globalItemsPerPage;
    private $pageParameter;

    public function __construct(SearcherService $searcherService,RequestStack $requestStack,ResourceMetadataFactoryInterface $resourceMetadataFactory,int $itemsPerPage = 30,int $globalItemsPerPage = 30)
    {
        $this->searcherService = $searcherService;
        $this->requestStack = $requestStack;
        $this->resourceMetadataFactory = $resourceMetadataFactory;
        $this->itemsPerPageParameter = $itemsPerPage;
        $this->globalItemsPerPage = $globalItemsPerPage;
        $this->pageParameter = "page";
    }

    /**
     * Retrieves a collection.
     *
     * @param string $resourceClass
     * @param string|null $operationName
     *
     * @throws ResourceClassNotSupportedException
     *
     * @return array|\Traversable
     */
    public function getCollection(string $resourceClass, string $operationName = null)
    {
        // Add here all entities that's you want to query with ElasticSearch
        if (!in_array($resourceClass, [Shop::class,Offer::class])) {
            throw new ResourceClassNotSupportedException();
        }
        $request = $this->requestStack->getCurrentRequest();

        $index = explode('\\', $resourceClass);
        $index = strtolower(end($index));

        $filters = $request->query->all();

        // Results is a PagerFanta
        $results = $this->searcherService->search($index,$filters);

        $resourceMetadata = $this->resourceMetadataFactory->create($resourceClass);

        $results->setMaxPerPage(
            (int) $request->get(
                $this->itemsPerPageParameter,
                $resourceMetadata->getCollectionOperationAttribute(
                    $operationName,
                    'pagination_items_per_page',
                    $this->globalItemsPerPage,
                    true
                )
            )
        );

        $results->setCurrentPage((int) $request->get($this->pageParameter, 1));

        return $results;
    }
}
```

Searcher Service : 

```
namespace AppBundle\Service;


use AppBundle\Bridge\ElasticSearch\PagerFanta;
use FOS\ElasticaBundle\Manager\RepositoryManager;

class SearcherService
{
    public $respositoryManager;

    public function __construct(RepositoryManager $repositoryManager)
    {
        $this->respositoryManager = $repositoryManager;
    }

    public function search($entityName,$filters) : PagerFanta {
        $repository = $this->getRepository($entityName);

        $results = $repository->findWithCustomQuery($filters);
        return $results;
    }

    /**
     * @param $entityName
     * @return \FOS\ElasticaBundle\Repository
     *
     * TODO REFACTORING
     */
    private function getRepository($entityName){
        $repositoryName = "api_".$entityName."s/".$entityName;
        return $this->respositoryManager->getRepository($repositoryName);
    }

}
```

Example ShopRepository : 

```
namespace AppBundle\SearchRepository;


use ApiPlatform\Core\Exception\InvalidArgumentException;
use Doctrine\Common\Collections\ArrayCollection;
use Elastica\Query;
use Elastica\Query\BoolQuery;
use Elastica\Query\GeoDistance;
use Elastica\Query\MatchAll;
use Elastica\Query\MultiMatch;
use Elastica\Query\Nested;
use Elastica\Query\Terms;
use Elastica\Script\Script;
use Elastica\Script\ScriptFields;
use FOS\ElasticaBundle\Repository;
use Pagerfanta\Adapter\DoctrineCollectionAdapter;

class ShopRepository extends Repository
{
    public function findWithCustomQuery($filters)
    {

		//Construct elastic query with filters
        .....
		
		
        $finalQuery = new Query($query);

        $hybridResults = $this->findHybrid($finalQuery,100);
        $shops = new ArrayCollection();

        foreach ($hybridResults as $hybridResult) {
            $shop = $hybridResult->getTransformed();
            $result = $hybridResult->getResult();
            foreach($result->getFields() as $key=>$field) {
                $shop->$key = count($field) == 1 ? $field[0] : $field;
            }
            $shops->add($shop);
        }
        $dca = new DoctrineCollectionAdapter($shops);
        return new \AppBundle\Bridge\ElasticSearch\PagerFanta($dca);
    }
} 
```

Thanks

Have a great Day
Mikael

**Comment by djoos** [comment]
Hi Mikael,

I'm glad it was useful for you to get going!

Have a great day!
David

**Comment by nckenn** [comment]
> Hi @mvigneron,
> 
> sure! Here are some snippets to get you on the way...
> FYI: we're still on v2.0.11 of api-platform/core.
> 
> The custom DataProvider's getCollection method:
> 
> ```
> use Escape\PaginatorBundle\Lib\Pagerfanta; // see below
> use Pagerfanta\Adapter\DoctrineCollectionAdapter;
> 
> public function getCollection(string $resourceClass, string $operationName = null)
> {
>     if(!$this->supports($resourceClass)) {
>         throw new ResourceClassNotSupportedException();
>     }
> 
>     $request = $this->requestStack->getCurrentRequest();
> 
>     $ac = new ArrayCollection();
> 
>     if(!empty($this->data)) {
>         foreach($this->data as $element) {
>             $ac->add($element);
>         }
> 
>         if(!empty($request->query->all()))
>         {
>             foreach ($request->query->all() as $k => $v) {
>                 $ac = $this->filter($k, $v, $ac);
>             }
>         }
>     }
> 
>     $adapter = new DoctrineCollectionAdapter($ac);
>     $pagerfanta = new Pagerfanta($adapter);
> 
>     $resourceMetadata = $this->resourceMetadataFactory->create($resourceClass);
> 
>     $pagerfanta->setMaxPerPage(
>         (int) $request->get(
>             $this->itemsPerPageParameter,
>             $resourceMetadata->getCollectionOperationAttribute(
>                 $operationName,
>                 'pagination_items_per_page',
>                 $this->globalItemsPerPage,
>                 true
>             )
>         )
>     );
> 
>     $pagerfanta->setCurrentPage((int) $request->get($this->pageParameter, 1));
> 
>     return $pagerfanta;
> }
> ```
> 
> So, the actual pagination logic is handled by [Pagerfanta](https://github.com/whiteoctober/Pagerfanta), which we've slightly tweaked to work with the ApiPlatform's PaginatorInterface:
> 
> ```
> namespace Escape\PaginatorBundle\Lib;
> 
> use ApiPlatform\Core\DataProvider\PaginatorInterface;
> use Pagerfanta\Pagerfanta as BasePagerfanta;
> 
> class Pagerfanta extends BasePagerfanta implements PaginatorInterface
> {
>     /**
>      * Gets the current page number
>      *
>      * @return float
>      */
>     public function getCurrentPage(): float {
>         return parent::getCurrentPage();
>     }
> 
>     /**
>      * Gets the last page
>      *
>      * @return float
>      */
>     public function getLastPage(): float {
>         return parent::getNbPages();
>     }
> 
>     /**
>      * Gets the number of items by page
>      *
>      * @return float
>      */
>     public function getItemsPerPage(): float {
>         return parent::getMaxPerPage();
>     }
> 
>     /**
>      * Gets the number of items in the whole collection
>      *
>      * @return float
>      */
>     public function getTotalItems(): float {
>         return parent::getNbResults();
>     }
> }
> ```
> 
> And the pagination_items_per_page is set in config.yml as follows:
> 
> ```yaml
> api_platform:
>     collection:
>         pagination:
>             items_per_page: 20
> ```
> 
> Hope this helps!
> 
> Please do give me a shout if you have any further questions or remarks! (it's always great to have someone else read through and improve the code :-) )
> 
> Have a great day!
> David

May i see the filter function?
