### ISSUE TITLE
docker-compose up fails suggesting require symfony/dotenv but package is already in composer.json

### ISSUE THREAD

**Issue by ksom** [api-platform/api-platform#1833]
**API Platform version(s) affected**: 2.6.2

**Description**  
When I run `docker-compose pull` and `docker-compose up -d` I have the following error :

![image](https://user-images.githubusercontent.com/4030561/109697566-ae03f700-7b8e-11eb-9964-c28a1f96eb0d.png)

I don't understand why it suggests me to install `symfony/dotenv` because it is already in the composer.json.

**How to reproduce**  
1: Download api-platform zip
2: run `docker-compose pull`
3: run `docker-compose up -d`

**Comment by rugolinifr** [comment]
https://stackoverflow.com/questions/66387155/api-platform-demo-project-installation-problem

**Comment by dunglas** [comment]
Fixed by the last release.
