### ISSUE TITLE
Custom documentation

### ISSUE THREAD

**Issue by piotrbrzezina** [api-platform/api-platform#185]
Hi 

Is there any better way to do custom documentation than I suggested in issue  https://github.com/api-platform/docs/issues/143 ?

This approach does work but it takes a lot of space. In my Entity I created five custom actions and if I write documentation that way it takes more lines then the php object.

**Comment by dunglas** [comment]
One solution can be to use XML or YAML mapping file instead of annotations.
Another solution is to decorate the `api_platform.swagger.normalizer.documentation` service to modify the array directly in PHP.

**Comment by Simperfit** [comment]
@piotrbrzezina Does it answer your needs ?

**Comment by piotrbrzezina** [comment]
yes thank
