### ISSUE TITLE
Deploy api-platform 2.6 with docker

### ISSUE THREAD

**Issue by d0niek** [api-platform/api-platform#1859]
Hi!

Deploy with docker to version **2.5** was easy with https://github.com/api-platform/docker-compose-prod

On local:

```
vim .env
docker-compose -f docker-compose.build.yml build --pull
docker-compose -f docker-compose.build.yml push
```

On server:

```
vim .env
docker-compose pull
docker-compose up -d
docker-compose exec php bin/console cache:clear && docker-compose restart php
```

How should I do it with version **2.6**? Which **docker-compose\*** file(s) use for build/push, which **docker-compose\*** file(s) use for pull/up?

For example file **docker-compose.override.yml** expose caddy ports so it looks good for `docker-compose up -d` but it uses build target **dev** for pwa and bind local directory for php.

**Comment by d0niek** [comment]
Ok, I see there was an update in **2.6.3** version and now I think it should looks like:

On local:

```
docker-compose -f docker-compose.yml -f docker-compose.prod.yml build --pull
docker-compose -f docker-compose.yml -f docker-compose.prod.yml push
```

On server:

```
docker-compose -f docker-compose.yml -f docker-compose.prod.yml pull
docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d
```

Am I correct? :-)

**Comment by jlagneau** [comment]
Yes, that's the correct way to deploy.

Although, you don't need to specify docker-compose.override.yml for development, you can just use docker-compose normally, read docker-compose docs.

https://docs.docker.com/compose/production/
https://docs.docker.com/compose/extends/

> By default, Compose reads two files, a `docker-compose.yml` and an optional `docker-compose.override.yml` file. By convention, the `docker-compose.yml` contains your base configuration. The override file, as its name implies, can contain configuration overrides for existing services or entirely new services.

In this case, the override file contains the development configuration.

The process for deploying in production in 2.5 was slightly more complicated than that, there was an external repository for production [api-platform/docker-compose-prod](https://github.com/api-platform/docker-compose-prod) but it was archived and is no longer relevant.
