### ISSUE TITLE
_api_persist=false or write=false does not seem to disable PRE_WRITE/POST_WRITE event dispatch

### ISSUE THREAD

**Issue by Leo450** [api-platform/api-platform#1869]
**API Platform version(s) affected**: 2.6

**Description**
I have a custom operation with this configuration
```php
/**
 *  "dataset_delete_form_for_establishment_and_team"={
 *    "method"="DELETE",
 *    "path"="/establishments/{establishment_id}/teams/{team_id}/forms/{id}",
 *    "controller"="App\Domain\Dataset\Operation\CRUDOperations::deleteForEstablishmentAndTeam",
 *    "write"=false,
 *    "defaults"={"_api_persist"=false}
 *  }
```
As said in the documentation, i'm expecting the ``WriteListener`` to be disabled because of the ``"write"=false`` and/or ``"defaults"={"_api_persist"=false}`` annotations.
So, i would expect any Subscriber registered to ``kernel.view`` event on ``PRE_WRITE`` and ``POST_WRITE`` hooks not to be triggered, and they are.

It might be an intended behavior, i just wanted to ask if that's the case, and report if that is not.
Or maybe i misunderstood something, i'm quite new to API Platform.

**How to reproduce**  
Add the ``"write"=false`` annotation to any of your ``POST``, ``DELETE``, ``PUT`` or ``PATCH`` custom route.
Create a Subscriber subscribed to ``kernel.view`` event on ``PRE_WRITE`` and/or ``POST_WRITE``.
Call your endpoint and watch the Subscriber getting triggered.

**Additional Context**  
Here is my Subscriber code for you too check i didn't badly write anything.
```php
<?php

namespace App\Domain\Dataset\Event\Subscriber;

use ApiPlatform\Core\EventListener\EventPriorities;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\ViewEvent;
use Symfony\Component\HttpKernel\KernelEvents;

class DatasetTestSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
            KernelEvents::VIEW => [
                ['testA', EventPriorities::PRE_WRITE],
                ['testB', EventPriorities::POST_WRITE]
            ],
        ];
    }

    public function testA(ViewEvent $event)
    {
        // Xdebug breakpoint here
    }

    public function testB(ViewEvent $event)
    {
        // Xdebug breakpoint here
    }
}
```

Thank you for your time.

**Comment by soyuka** [comment]
We don't hook on the symfony's event system you should check this value yourself see https://github.com/api-platform/core/blob/main/src/EventListener/WriteListener.php#L62.

**Comment by Leo450** [comment]
Oh yeah, thank you very much, i see it now.

It's just a bad comprehension of how those Events works from me.
I had in mind that the ``WriteListener`` would at some point dispatch two more Events, one before and one after persistence and that those Events would not be dispatched if persistence is disabled.
But there are no such Events, because of course the ``WriteListener`` is just a listener subscribed to the ``kernel.view`` Event which will be dispatched no matters what and PRE_WRITE and POST_WRITE are not Events but priorities.

You can close and even delete this one. Thanks.
