### ISSUE TITLE
Unrecognized option "absolute_url" under "api_platform"

### ISSUE THREAD

**Issue by tsdevelopment** [api-platform/api-platform#1870]
**API Platform version(s) affected**: 2.6.3

**Description**  
Set the following configuration:

```
# api/config/packages/api_platform.yaml
api_platform:

    # Return IRIs as Absolute URLs.
    # ex: http://example.com/authors/1
    absolute_url: true
```

**How to reproduce**  
Create a fresh symfony project (or use an existing one) with api-platform 2.6.3 installed and use the configuration from above.

**Additional Context**  
![image](https://user-images.githubusercontent.com/4952908/113879336-b4534780-97ba-11eb-9b28-8e549d66cf6a.png)

**Comment by roman-huliak** [comment]
Changes in https://github.com/api-platform/core/pull/3198 but not documented

**Comment by alanpoulain** [comment]
It is now documented: https://api-platform.com/docs/core/url-generation-strategy/
