### ISSUE TITLE
Empty mapped collection

### ISSUE THREAD

**Issue by Jarablus** [api-platform/api-platform#188]
Is it possible to empty a mapped collection with denormalization  ?

If yes then this does not work
Ex:
> {
  "@context": "/contexts/Cart",
  "@id": "/carts/30867",
  "@type": "Cart",
  "updatedAt": "2016-11-28T07:52:02+01:00",
  "articles": []
}

**Comment by Simperfit** [comment]
Could you please explain what you want to achieve ?

**Comment by napalm33700** [comment]
Cart "articles"  is an ArrayCollection I want to clear it on a Cart PUT

**Comment by napalm33700** [comment]
If it is not possible you can close the issue I have made a "dirty" workaround...

**Comment by soyuka** [comment]
I think that this works as I've a similar route working. What's your dirty workaroud? You should not need one. Can you show us entities?

**Comment by napalm33700** [comment]
> /**

   *   @ApiResource(
   *      collectionOperations={
   *        "get"={"method"="GET"},
   *      },
   *      itemOperations={
   *        "get"={"method"="GET",   "normalization_context"={"groups"={"cart"}},   "denormalization_context"={"groups"={"cart"}}},
   *        "put"={"method"="PUT",   "normalization_context"={"groups"={"cart"}},   "denormalization_context"={"groups"={"cart"}}},
   *      }
   *   )
   *   @ORM\Entity
   *   @ORM\HasLifecycleCallbacks
   *   @ORM\Table(name="cart")
*/
class   Cart

/**
  *   @ORM\OneToMany(targetEntity="CartArticle",   mappedBy="cart",      cascade={"persist",   "remove"})
  *   @ORM\OrderBy({"createdAt"   =   "DESC"})
  *   @Groups({"cart"})
*/
private   $articles;
____________________________
My workaround, don't judge me :D ... Is a kernel request listener if articles is empty manualy remove all articles and flush.

The thing I don't understand is that in my listener articles is empty but without my ugly fix nothing is actually deleted in database.

**Comment by Simperfit** [comment]
Is that workaround still in place ?
Because like @soyuka said you should not need one.

**Comment by Jarablus** [comment]
Yes,  I will try without it and with latest apiplatform version

**Comment by teohhanhui** [comment]
Make sure you're not doing it wrong: http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/unitofwork-associations.html#important-concepts

**Comment by Jarablus** [comment]
It's the first thing I've checked.

**Comment by teohhanhui** [comment]
We'll need more information then...

**Comment by Simperfit** [comment]
@Jarablus is it ok for you ?

**Comment by Jarablus** [comment]
@Simperfit Yes After starting with a "fresh" api-plaform install. I think the problem was my migration from V1 to V2 (it was a little "messy").
