### ISSUE TITLE
Schema generator fail because of purl certificate problem

### ISSUE THREAD

**Issue by florent-andre** [api-platform/api-platform#1897]
**API Platform version(s) affected**: 2.6.4

**Description**  
From the 23 avril, the purl https certifcate is exprired, thus invalid and raise this exception in the schema generator : 
```
PHP Warning:  SimpleXMLElement::__construct(): SSL operation failed with code 1. OpenSSL Error messages:
error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed in /srv/api/vendor/api-platform/schema-generator/src/Command/GenerateCommand.php on line 157
```

**How to reproduce**  
`docker-compose exec php vendor/bin/schema`

**Possible Solution**  
* As a quick fix, this can be added in the `*-schema.yaml` conf : 
``` yaml
relations:
    - http://www.heppnetz.de/ontologies/goodrelations/v1.owl
```

* As a long term fix, the purl default config may be changed to the de-referenced uri (http://www.heppnetz.de/ontologies/goodrelations/v1.owl)

**Additional Context**  
Seriously, who manage the purl certificates ?

**Comment by alanpoulain** [comment]
Another option would be to use `https://archive.org/services/purl/` instead.

**Comment by dunglas** [comment]
PR welcome!

**Comment by florent-andre** [comment]
Here you are : https://github.com/api-platform/schema-generator/pull/326 !
