### ISSUE TITLE
How to test Graphql ?

### ISSUE THREAD

**Issue by Fizzy-59** [api-platform/api-platform#1905]
Hello,

I want to test my API-Graphql created by API-platform.

I read the doc :
https://api-platform.com/docs/distribution/testing/

But, I can't find in the documentation how to test a route served by graphql ...

Could you help me please ?

Thanks you ! 

I would like something like this, but for the Graphql:
![Capture d’écran 2021-05-06 à 18 20 47](https://user-images.githubusercontent.com/49993311/117332170-c8f92d00-ae97-11eb-916d-2fd71c61b9a6.png)

I want to test this call:
![Capture d’écran 2021-05-06 à 18 20 26](https://user-images.githubusercontent.com/49993311/117332129-bda60180-ae97-11eb-94a4-d1d2d679690d.png)

**Comment by Chris53897** [comment]
Did you found a solution?

**Comment by soyuka** [comment]
should be `POST /graphql`
