### ISSUE TITLE
problem with persisting password

### ISSUE THREAD

**Issue by hurcle** [api-platform/api-platform#1913]
Hi,

I am trying to create a user, it was working well but suddenly I don't get why it's stuck expecting my password which I give actually...

`"hydra:description": "An exception occurred while executing 'INSERT INTO user (email, name, roles, password, temporary_password, birthdate, end_subscription, auto_subscription, gender, id_subscription, created_at, image_id, language_default_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"test21@gmail.com\", \"test21\", \"[\\\"ROLE_USER\\\",\\\"ROLE_PRO\\\"]\", null, null, \"1989-01-20\", \"2021-08-14\", 1, 0, null, \"2021-05-14 12:20:00\", null, null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Le champ 'password' ne peut être vide (null)",`

I have tried many different things but the most akward thing is that it even doesn't appear in my own documentation.
I don't get why my password can't go through POST method. I don't get any problem at all make everything else work by GET methode or others entity.

Here is part of my code concerned :
`
@ApiResource(
 *     normalizationContext={"groups"={"user:read"}},
 *     denormalizationContext={"groups"={"user:write"}}
`

`
/**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;
`
`
/**
     * @Groups("user:write")
     * @SerializedName("password")
     */
    private $plainPassword;
` 

Here is my doc concerned, password doesn't even appear :

![user_doc](https://user-images.githubusercontent.com/29728603/118271100-26f1ca00-b4c1-11eb-8443-441cc5f73edd.png)

In my UserDataPersister it does take my password anyway but validation fail until that :

![persist](https://user-images.githubusercontent.com/29728603/118271981-40dfdc80-b4c2-11eb-96b8-95047d2af723.png)

Any help would be appreciate, thanks :)

**Comment by Chris53897** [comment]
I am not sure if @SerializedName("password") is overwriting the name "password".

Maybe another problem:
Are you using a mysql-Database? Password look like a reserved word.
https://dev.mysql.com/doc/refman/8.0/en/keywords.html

/** @Column(type="string", name="pwd") */
private $password;

Maybe backticks work too
/** @Column(type="string", name="`password`") */
private $password;

I had a smiliar Problem with "group".

**Comment by ES-Six** [comment]
I think the @SerializedName("password") is overwriting the name "password" because I use it a similar way to hash the password with a DataPersister :

The tricks here is to store temporarly the password into an other property then hash he password using a DataPersister

#### The 2 properties in the User.php Entity
```php
    /**
     * @ORM\Column(type="string")
     */
    private ?string $password;

    #[Assert\NotBlank(groups: ["public:write"])]
    #[Assert\Length(min: 8, groups: ["public:write"])]
    #[SerializedName("password")]
    #[Groups(["public:write"])]
    #[ApiProperty(["attributes" => [
        "openapi_context" => [
            "type" => "string",
            "example"=> "apassword"
        ]
    ]])]
    protected ?string $plainPassword = null;
```

#### The User Datapersister
```php
<?php
// in file src/DataPersister/UserDataPersister.php
namespace App\DataPersister;

use ApiPlatform\Core\DataPersister\DataPersisterInterface;
use App\Entity\User;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

class UserDataPersister implements DataPersisterInterface
{
    private UserPasswordHasherInterface $userPasswordHasher;
    private EntityManagerInterface $entityManager;

    public function __construct(EntityManagerInterface $entityManager, UserPasswordHasherInterface $userPasswordHasher)
    {
        $this->userPasswordHasher = $userPasswordHasher;
        $this->entityManager = $entityManager;
    }

    public function supports($data): bool
    {
        return $data instanceof User;
    }

    public function persist($data)
    {
        if ($data->getPlainPassword()) {
            $data->setPassword($this->userPasswordHasher->hashPassword($data, $data->getPlainPassword()));
            $data->eraseCredentials();
        }
        $this->entityManager->persist($data);
        $this->entityManager->flush();
    }

    public function remove($data)
    {
        $this->entityManager->remove($data);
        $this->entityManager->flush();
    }
}
```
