### ISSUE TITLE
Snake/Camel case generator error

### ISSUE THREAD

**Issue by seregaperm** [api-platform/api-platform#1915]
**API Platform version(s) affected**: 2.6.4

**Description**  
Invalid generation and read properties with symbol "_"

**How to reproduce**  
Symfony entity generator makes method "getMegaField" for field "mega_field", but api platform translate **two** properties **together**: megaField and mega_field (in GET method for example)

I should fix it and rename method getMegaField to getMega_field, but this fixing is not working 100% (sometimes a field is hidden together)

For example: when I add **created_at** property, symfony creates property **created_at**, and method **getCreatedAt**, **setCreatedAt**, but api_platform shows **created_at** and **createdAt** together.
```
{
"created_at": ...,
"createdAt": ...,
}
```

I should rename **getCreatedAt** method to **getCreated_at** to fix it.

I have a problem with api_platform when I need to use properties consists of two parts.

**Possible Solution**  
Internal problem in generator.

**Additional Context**  
Nothing

**Comment by Chris53897** [comment]
That problem is reported more than once.
The best way ist to name Attributes like **$myAttribute** **$megaField** **$createdAt**

Btw, you can configure how doctrine orm maps attributes to names.
/api/config/packages/doctrine.yaml

doctrine:
    orm:
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware

**Comment by soyuka** [comment]
please provide a reproduction on api-platform/core we have tests for this and the feature should be documented
