### ISSUE TITLE
Format \u0022png\u0022 is not supported

### ISSUE THREAD

**Issue by arnaudbagnis** [api-platform/api-platform#1919]
Hello, I follow this tutorial for support file type in my Api. 
But I have a error in production. 
`{"type":"https:\/\/tools.ietf.org\/html\/rfc2616#section-10","title":"An error occurred","detail":"Format \u0022png\u0022 is not supported"}` in body and this log 
`NOTICE: PHP message: [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "Format "png" is not supported" at /srv/app/vendor/api-platform/core/src/EventListener/AddFormatListener.php line 104`

In development I manage to display my image. The only difference between the environments is that I go through a caddy web server

I wanted to know if it came from api platform or just bad configuration

version of api-platform : 2.5.9

thank you 🙂

**Comment by Chris53897** [comment]
Did you tried different file-types like jpg or pdf for testing?

**Comment by soyuka** [comment]
It's weird why do you want to use API Platform for pictures? I think that you need to avoid going through our FormatListener for this to work so you have multiple solutions:
- allow the format in API Platform configuration (see docs)
- skip the format listener (_api_respond in the defaults to false, may have other impact)

Or use a symfony route for this not API Platform
