### ISSUE TITLE
Can't access localhost/app_dev.php (similar to #169) (docker install, Ubuntu 16.04)

### ISSUE THREAD

**Issue by Gormador** [api-platform/api-platform#192]
Hi,

Currently banging my head against a wall of incomprehension at this stage of the [tutorial](https://api-platform.com/docs/distribution/):
![appdevfails](https://cloud.githubusercontent.com/assets/6118753/21233871/1c266fac-c2f1-11e6-9c22-54a58beadc95.png)

What I did:
- corrected my mistake of not having used `docker-compose` as a user instead of root by adding my user to the docker group, rebooted, deleted the already built docker images, deleted the skeleton-project including the root-owned folders;
- ran `docker-compose up -d` again, as a user this time, in a freshly copy pasted skeleton-project and followed the tutorial up to the same point;
- same error. `var/cache/dev` is still root-owned.

No idea what I did wrong. Any clue as to what it might be?
Thanks in advance for any input you may have, and thank you for this great looking project :-)

ps: May be worth noting that I'm a docker noob.

**Comment by Simperfit** [comment]
the /var/cache is root locally too ?

Could you please try to remove the whole folders content give the permission to the current user ?

**Comment by Gormador** [comment]
Yes, sorry, didn't mention it. I'm speaking about the `var/cache/dev` folder in the skeleton-project directory.

Trying out your suggestion now...

Ok, performed `sudo chown -R $USER var/cache/dev` after deleting its content. Refreshing the page gives me an Error 500. But applying the same to `var/cache/logs/dev.log` fixed it and allowed me to access the dev env.

I have no idea why this behaved like it did though. Why did root took ownership of those files when the command I was using wasn't executed as root?

Anyway, I can at least continue with the tutorial now.

Thanks!

**Comment by Simperfit** [comment]
I think something has been executing as root at the first time

**Comment by renan-taranto** [comment]
I'm also having this problem.

- I didn't run docker-compose as root

**Comment by renan-taranto** [comment]
I'm also having this problem.

- I didn't run `docker-compose` as root;
- I had to `sudo chown -R $USER var/logs/` and `sudo chown -R $USER var/cache/` to access the dev env.

IMHO this issue should not be closed since it wasn't fixed.

**Comment by teohhanhui** [comment]
The user in the container which executed the commands is `root`, so that might be the problem... (I haven't looked into it.)

**Comment by Linkinou** [comment]
By default, Docker containers are executed as root.
So if you execute a command through a docker container, it will be executed by the root User.

A workaround for me is a simple alias : 

``
project-chown='docker-compose exec web chown -R www-data:www-data var/logs/ var/cache/'
``

But the best thing to do IMHO would be to change the User in the Dockerfile.

**Comment by teohhanhui** [comment]
This will be fixed by #162

**Comment by dunglas** [comment]
But #162 will be only for 2.1. We need to fix the Apache for 2.0 anyway.

**Comment by teohhanhui** [comment]
That is why I do not recommend having a 2.0 branch... :disappointed:

**Comment by dunglas** [comment]
@teohhanhui this is not an option, we should release bug (like this one) and security fixes before the release of 2.1.

**Comment by teohhanhui** [comment]
> we must release bug (like this one) and security fixes before the release of 2.1

I still disagree, but this is not the place to discuss this.

**Comment by Stoakes** [comment]
Hello,

I had the same issue.
It comes from `composer install` executed as root in docker/start.sh

To solve that, I added after composer call in start.sh

```
#get apache user : second word of the first line (from docker/apache/start_safe_perms)
apache_user=$(head -n 1 /etc/apache2/apache2.conf| cut -d " " -f 2)

#get apache group : second word of the second line
apache_group=$(head -n 2 /etc/apache2/apache2.conf| tail -1 |  cut -d " " -f 2)

chown -R $apache_user:$apache_group var
```

Are you interested on a PR ?

**Comment by dunglas** [comment]
Yes we are.

**Comment by renan-taranto** [comment]
I believe this is solved by #162 :)
Great job on the docker updates.

**Comment by Simperfit** [comment]
@Gormador Could you confirm please ?

**Comment by Gormador** [comment]
As stated in #162 , I am not in a position to test this anymore... My apologies.
Don't wait on me to close this issue :-)
Thanks again for you help.
