### ISSUE TITLE
ArrayInput with ManyToOne relation doesn't show values on Edit form

### ISSUE THREAD

**Issue by htaoufikallah** [api-platform/api-platform#1921]
**API Platform version(s) affected**: 2.6.0

**Description**  
ArrayInput with ManyToOne relation doesn't show values on Edit form although it render the correct form inputs according to the relation items count
check this [screenshot](https://ibb.co/R7FxnxQ)

**How to reproduce**  
My code is very simple by following [react admin doc](https://marmelab.com/react-admin/Inputs.html#arrayinput)
```
export const QuizQuestionCreate = props => (
  <CreateGuesser {...props}>
    <InputGuesser source="question" validate={[required()]}/>

    <ArrayInput source="choices">
      <SimpleFormIterator>
        <TextInput label="choice" source="choice"/>
        <BooleanInput label="Correct" source="correct"/>
      </SimpleFormIterator>
    </ArrayInput>
  </CreateGuesser>
);

export const QuizQuestionEdit = props => {
  return (
    <Edit {...props}>
      <SimpleForm>
        <TextInput source="question"/>

        <ArrayInput source="choices">
          <SimpleFormIterator>
            <TextInput label="choice" source="choice"/>
            <BooleanInput label="Correct" source="correct"/>
          </SimpleFormIterator>
        </ArrayInput>
      </SimpleForm>
    </Edit>
  )
};
```
Api Question Get response
```
{
   "@context":"\/contexts\/QuizQuestion",
   "@id":"\/quiz_questions\/34",
   "@type":"QuizQuestion",
   "id":34,
   "question":"question test",
   "project":"\/projects\/5",
   "choices":[
      {
         "@id":"\/quiz_choices\/64",
         "@type":"QuizChoice",
         "id":64,
         "choice":"choice 1",
         "project":"\/projects\/5",
         "correct":false
      },
      {
         "@id":"\/quiz_choices\/65",
         "@type":"QuizChoice",
         "id":65,
         "choice":"choice 2",
         "project":"\/projects\/5",
         "correct":true
      }
   ]
}
```

**Comment by denisvmedia** [comment]
Hi, I'm struggling with the same issue. Were you able to work around the issue?

**Comment by htaoufikallah** [comment]
Hi @denisvmedia no solution for the moment I think about implementing this solution [https://marmelab.com/blog/2020/09/16/react-admin-tutorials-form-for-related-records.html)](https://marmelab.com/blog/2020/09/16/react-admin-tutorials-form-for-related-records.html)

**Comment by denisvmedia** [comment]
@htaoufikallah thanks. I actually, solved it in my case by embedding the relation to the main entity response and then following [this](https://api-platform.com/docs/admin/handling-relations/). Not sure if it can work for your case, but it worked for me fine.
