### ISSUE TITLE
Unable to generate an IRI with ORM php 8 annotations

### ISSUE THREAD

**Issue by oschwartz** [api-platform/api-platform#1923]
Hi,
i started to migrate the entities to php8 annotations. I am having this problem with my first entity

```
#[ORM\Id, ORM\GeneratedValue(strategy: 'UUID'), ORM\Column(type: 'guid')]
private ?string $id = null;
```

error: No identifier/primary key specified for Entity "App\Entity\Test". Every Entity must have an identifier/primary key.

**Comment by simivar** [comment]
From what I see API Platform is based on doctrine/doctrine-bundle which hasn't been released yet with support for `Attribute Driver`. See doctrine/DoctrineBundle#1354

**Comment by Chris53897** [comment]
DoctrineBundle now supports AttributDriver

You need at least these versions
"doctrine/doctrine-bundle": "^2.4",
"doctrine/orm": "^2.9",

You can change the doctrine orm type in /api/config/packages/doctrine.yaml
But all of your entities need the "attribute"-Format.

doctrine:
    orm:
            App:
                #type: annotation
                type: attribute

Testet with API-Platform Distro 2.6.4

**Comment by soyuka** [comment]
Not an API Platform issue.
