### ISSUE TITLE
[question] How to implement ?fields=name,email filter?

### ISSUE THREAD

**Issue by rogamoore** [api-platform/api-platform#193]
Hello everyone and thanks for this great bundle!

I'm currently trying to find a way to limit the returned fields on a GET request dynamically by using a `fields` list on the query string.

**Standard:**
`GET /books`
```
[
  {
    "id": 19,
    "isbn": null,
    "title": "test",
    "description": "test",
    "author": "test",
    "publicationDate": "2016-11-28T14:47:44+00:00",
  },
  {
    "id": 25,
    "isbn": "9788811810148",
    "title": "Odissea",
    "description": "Grande classico ellenico",
    "author": "Omero",
    "publicationDate": "2016-11-11T18:14:58+00:00",
  }
]
```

**With filter:**
`GET /books?fields=id,title`
```
[
  {
    "id": 19,
    "title": "test",
  },
  {
    "id": 25,
    "title": "Odissea",
  }
]
```

What would be the recommended way to solve this?

**Comment by teohhanhui** [comment]
I don't think this can be implemented as a custom filter. And serializer groups seem ill-suited for this...

**Comment by soyuka** [comment]
Indeed, you can do this by using serialization groups.

**Comment by dunglas** [comment]
I've started to add this feature in the Symfony Serializer but it's not finished yet (see comments): https://github.com/symfony/symfony/pull/18834

Any help welcome :)

**Comment by dunglas** [comment]
By the way, it can be also be easily added by decorating the `api_platform.jsonld.normalizer.item` service and `unset`ting fields you don't want. You can directly inject the `request_stack` service to access your data but it's not clean, I recommend to set a new parameter in the serialization context to that: https://api-platform.com/docs/core/serialization-groups-and-relations#changing-the-serialization-context-dynamically.

**Comment by rogamoore** [comment]
Thanks Kévin, for the feedback. I've used dynamic serialization groups for now (not as dynamic as I wanted above) but I will try your suggestion asap. :)
I'll also have a look if I can provide any help with the Symfony Serializer as this would be probably the cleanest solution :)

**Comment by alborq** [comment]
It's may impleaments into DataProvider too. It's not really usefull to fetch unused data. 
@dunglas some news for symfony/symfony#18834 ?

**Comment by teohhanhui** [comment]
symfony/symfony#18834 has been merged. :tada:

**Comment by BallisticPain** [comment]
Looking forward to this.

**Comment by Simperfit** [comment]
This has been implemented in core !
