### ISSUE TITLE
[ASK] How to create json-ld manually using api platform?

### ISSUE THREAD

**Issue by ad3n** [api-platform/api-platform#194]
How to create json-ld from unmanage resource, such as a static collection?

**Comment by Simperfit** [comment]
What do you mean ?

I think you can use a [DataProvider](https://api-platform.com/docs/core/data-providers)

**Comment by ad3n** [comment]
@Simperfit : Thanks for your reply,

I have a collection, imagine an enum with data (A, B, C), in my case, i save that enum in parameters and want to expose that use an api endpoint.

How to handle it using Api Platform?

Sorry for my bad english and i hope you can understand about my question :-)

**Comment by dunglas** [comment]
@ad3n, @Simperfit is right, you should use custom data providers to do that. It can return an array of static data.

**Comment by Simperfit** [comment]
@ad3n Did you find out how to use the custom data provider ?

**Comment by ad3n** [comment]
@dunglas n @Simperfit : :+1: thank you so much... it work properly :+1: api platform is very awesome
