### ISSUE TITLE
Error when swagger is disabled

### ISSUE THREAD

**Issue by napalm33700** [api-platform/api-platform#195]
When swagger is disabled all my services are down wih this error 
=> Serialization for the format html is not supported.
html is enabled in config.yml

**Comment by napalm33700** [comment]
I think its not related to swagger but to request header **Accept,** If it's not **application/ld+json**
there is this error if swagger is disabled and redirection to swagger doc if it is enabled.

**Comment by Simperfit** [comment]
You can change the route or [disable swagger directly](https://github.com/api-platform/core/pull/841)

```
swagger_ui:
    path:       /swaggerui
    defaults:  { _controller: api_platform.swagger.action.ui }
```

**Comment by napalm33700** [comment]
I fixed it by forcing **Accept:application/ld+json** in a listener, don't think it's the best id but I'm in a hurry

**Comment by Simperfit** [comment]
@napalm33700 but you can disable swagger ui and don't be using a listener

**Comment by napalm33700** [comment]
as I said the error is when it is disabled. And I need it in dev env.

**Comment by napalm33700** [comment]
@Simperfit I will investigate more and test something less ugly tomorrow

**Comment by gerfigna** [comment]
same problem
