### ISSUE TITLE
[Context] application/ld+json exposing sensitive fields

### ISSUE THREAD

**Issue by RSalo** [api-platform/api-platform#1953]
**API Platform version(s) affected**: 2.6.5

**Description**  
I found that application/ld+json exposing all fields in a related entity.
For example output in application/json format:
```JSON
{
  "id": 1,
  "uuid": "7c1e0dcd-6d0e-4f8d-9839-fbf95b604a7b",
  "title": "string1",
  "slug": null,
  "fullArticle": "string3",
  "author": {
    "username": "admin"
  },
  "createdAt": "2021-06-22T13:17:43+00:00"
}
```
And the same response in application/ld+json format:
```JSON
{
  "id": 1,
  "uuid": "7c1e0dcd-6d0e-4f8d-9839-fbf95b604a7b",
  "title": "string1",
  "slug": null,
  "fullArticle": "string3",
  "author": {
    "@context": {
      "@vocab": "http://api.localhost:8000/api/docs.jsonld#",
      "hydra": "http://www.w3.org/ns/hydra/core#",
      "uuid": "User/uuid",
      "email": "User/email",
      "username": "User/username",
      "roles": "User/roles",
      "password": "User/password",
      "articles": "User/articles",
      "userIdentifier": "User/userIdentifier",
      "salt": "User/salt"
    },
    "@type": "User",
    "@id": "_:802",
    "username": "admin"
  },
  "createdAt": "2021-06-22T13:17:43+00:00"
}
```

**How to reproduce**  
~

**Possible Solution**  
~

**Additional Context**  
~

**Comment by Chris53897** [comment]
Hi. What behaviour do you expect? The hydra-conteyxt only shows the schemata, not the data.

**Comment by RSalo** [comment]
> Hi. What behaviour do you expect? The hydra-conteyxt only shows the schemata, not the data.

But it exposes additional information about application structure, isn't it? What about security?

**Comment by dunglas** [comment]
What do you mean by application infrastructure? The domain name? It's not the default behavior, and it's the expected behavior, not a security issue to me.

**Comment by RSalo** [comment]
Expected behavior.
