### ISSUE TITLE
Property security : variable "request" is not valid

### ISSUE THREAD

**Issue by bpiwowar** [api-platform/api-platform#1962]
**API Platform version(s) affected**: 2.6.5

**Description**  

Contrarily to what is said in the documentation https://api-platform.com/docs/core/security/ the variable `request` is not available at the property level, i.e. modifying the example like below does not work

```
class Book
{
    //...

    /**
     * @var string Property viewable and writable only by users with ROLE_ADMIN
     *
     * @ApiProperty(security="is_granted('ROLE_ADMIN') or request.method='GET'")
     */
    private $adminWriteOnlyProperty;
}
```

**Possible Solution**  

Either change the documentation, or better - add the request object when checking security at the property level and/or a way to know if we are normalizing or denormalizing the entity.

**Context**

I am trying to restrict the access to the property depending on the request. Another option would be to have different security checks when normalizing or denormalizing the entity. 

I am aware of the possibility of using a dynamic context, but then the OpenAPI generation is broken (the field is not included anymore in the OpenAPI documentation), requiring to create an `OpenApiFactory`. I was looking for much simpler solutions by using the `@ApiProperty(security="")` annotation but then I am blocked because there is no way to distinguish between normalization and denormalization.

**Comment by bpiwowar** [comment]
By the way, the documentation is again inaccurate

> Access control checks in the security attribute are always executed before the denormalization step. It means than for PUT or PATCH requests, object doesn't contain the value submitted by the user, but values currently stored in the persistence layer.

Actually, the `object` is only a string contain the entity name

**Comment by alanpoulain** [comment]
Please read the documentation for the `2.7` version, some changes have been done and it's clearer now: https://api-platform.com/docs/main/core/security/.

**Comment by r-martins** [comment]
It still innacutate and says we can use the `request` variable.
But got the same error as @bpiwowar
