### ISSUE TITLE
PUT operation does PATCH

### ISSUE THREAD

**Issue by CedricYii** [api-platform/api-platform#1964]
**API Platform version(s) affected**: 2.6.5

**Description**  
When sending PUT with only some partial fields of one element, the element is partially updated with those fields.
But documentation says:
PUT Replace an element
PATCH Apply a partial modification to an element

**How to reproduce**  
Update one field of any element with several fields

**Possible Solution**  
Update the behavior (more common Api practice is to replace) or, if it is intended, state it clearly in the documentation

**Comment by alanpoulain** [comment]
It is intended do not cause BC for users using `PUT` like a `PATCH`.
It can be clarified in the documentation, but the new behavior (only replacing) will be enforced for API Platform 3.

**Comment by CedricYii** [comment]
Good to know, thanks.
Then yes, the documentation should say exactly that. And deprecate the current behavior.

**Comment by dunglas** [comment]
Thanks for reporting @CedricYii, closing as duplicate of https://github.com/api-platform/core/issues/4344.
