### ISSUE TITLE
Error on first build of fresh install

### ISSUE THREAD

**Issue by brendanlawton** [api-platform/api-platform#1979]
Hi all,

I downloaded V2.6.5 just now and ran `docker-compose build --pull --no-cache` as per the docs but the build fails and I get 

the following error: `ERROR: Service 'php' failed to build`

along with: `executor failed running [/bin/sh -c set -eux; 	apk add --no-cache --virtual .build-deps`

and further up: `#7 40.08 make: /bin/sh: Operation not permitted` `#7 40.08 make: *** [Makefile:209: php_intl.lo] Error 127`

Is this something to do with the permissions in my code directory where this install lives, maybe?

<img width="1440" alt="Screenshot 2021-07-27 at 19 37 26" src="https://user-images.githubusercontent.com/10241756/127209762-87039b96-71dc-4297-acad-17af0409bc67.png">

**Comment by zspine** [comment]
Hi @brendanlawton 

Change the PHP version to  PHP_VERSION=8.0 to PHP_VERSION=8.0.5 in Dockerfile and try to rebuild

Reference: https://github.com/api-platform/api-platform/issues/1975#issuecomment-884030886

**Comment by brendanlawton** [comment]
Thanks @zspine that did it 👍
