### ISSUE TITLE
Entity not found in relationship returns 500 HTTP error

### ISSUE THREAD

**Issue by renan-taranto** [api-platform/api-platform#198]
I'm getting the same error described in #88 which was closed but still persists.

Providing a non existing resource id to an association when using PUT or POST returns a 500 error instead of a 400 one.

Eg.: Sending a POST request to a '/product/' with a non existing '/category/'
``` json
 {
   "category": "/categories/0"
 }
```
will return a 500 status code response with the content:
```
{
  "@context": "/contexts/Error",
  "@type": "Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Entity of type 'AppBundle\\Entity\\Category' for IDs id(0) was not found"
}
```

**Comment by teohhanhui** [comment]
You're using 2.0, right? Can you add a failing test?

**Comment by teohhanhui** [comment]
It was supposed to have been fixed by api-platform/core#599

**Comment by renan-taranto** [comment]
@teohhanhui This project reproduces the error https://github.com/renan-taranto/api_platform_issue_198.
Note that the mentioned error happens if the "Valid" constraint is added to the field that represents the relation. Otherwise we get a DBAL exception. Both 500 errors.

**Comment by dunglas** [comment]
ping @Simperfit

**Comment by Simperfit** [comment]
This has been fixed long time ago ;)
