### ISSUE TITLE
Connection refused error: Docker Compose v2.0.0 bug

### ISSUE THREAD

**Issue by Rme2001** [api-platform/api-platform#1986]
**API Platform version(s) affected**: 2.6.5 (main)

**Description**  
Getting "Connection Refused" errors on https://localhost with a clean install of version 2.6.5. (Chrome 92)
The `docker-compose.yml` contains published port 443 for both TCP (HTTPS) and UDP (HTTP/3). 
This results in docker only publishing UDP 443 as seen in the following screenshot: 
Output of `docker ps`:
![image](https://user-images.githubusercontent.com/2506544/128498413-9713a9cf-f7c2-4be7-a962-ea72483e10b2.png)

Output of `docker ps` after commenting out UDP 443 port:
![image](https://user-images.githubusercontent.com/2506544/128499516-67735ab0-e690-408a-9fbf-e21ed5ed6796.png)

**How to reproduce**  
- Docker Desktop (Windows 10) 3.5.2
- Docker Engine: 20.10.7
- Docker Compose: v2.0.0-beta.6
Docker containers running in WSL2

**Possible Solution**  
Downgrade to Docker Compose 1.29, see the [Compose V2 documentation](https://docs.docker.com/compose/cli-command/) on how to accomplish this.

**Additional Context**  
This is an upstream issue related to Docker Compose v2 beta in combination with this specific config, but at the very least i wanted to raise this issue to indicate that out of the box release 2.6.5 does not allow you to visit https://localhost when using Docker Composer v2.0.0-beta.6, which i.i.r.c. was automatically turned on with a recent update of Docker Desktop.

**Comment by Rme2001** [comment]
Created an issue upstream: https://github.com/docker/compose-cli/issues/1996

**Comment by Chris53897** [comment]
I have the same issue with Mac M1

**Comment by dunglas** [comment]
The issue has been fixed upstream. https://github.com/compose-spec/compose-go/pull/179
