### ISSUE TITLE
Composer install - Update installation docs

### ISSUE THREAD

**Issue by randycasburn** [api-platform/api-platform#200]
Requires composer update after composer install.

Please add this step to the composer install workflow.

**Comment by dunglas** [comment]
`composer update` is not required. Can you elaborate a bit more? Why do you need to run this command?

**Comment by randycasburn** [comment]
OK.

Followed composer method install instructions
Started server per instructions - server runs
UI was FUBAR

Instinct: composer update

Result: composer update identifies 1 install and 2 version updates required by dependencies. Composer installs/updates

Restart server: UI looks just like Swagger UI

Conclusion: My platform required an install and updates based upon your dependency list. Maybe someone else's will too. Can't explain why, because now that I've updated composer's dependencies, I cannot reproduce the problem.

**Unrelated - but continuing with Book tutorial:** When I run:
`docker-compose exec web bin/console doctrine:generate:entities AppBundle`
to generate new entities, I receive and error:
`ERROR: No container found for web_1`

Feel free to close this. Didn't mean to waste your time.

**Comment by randycasburn** [comment]
disregard the prior **Unrelated** comment. Didn't dawn on me to replace:
`docker-compose exec web `
with:
`php bin/console`

All good - unless one tends to not use Docker.

**Comment by shaisachs** [comment]
I didn't need to do a composer update, but I definitely needed to do a composer install. I tried this:

```
docker-compose up -d
docker-compose exec php bin/console doctrine:schema:create
```

And got:

```
Fatal error: require(): Failed opening required '/srv/api-platform/app/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /srv/api-platform/app/autoload.php on line 7
```

So then I ran:

```
docker-compose exec php composer install
```

.. and was able to run doctrine:schema:create properly after that.

**Comment by teohhanhui** [comment]
@shaisachs But `composer install` is already in the container startup script: https://github.com/api-platform/api-platform/blob/8d7bedda15ab130a8d373dd401b1caf855492ad5/docker/php/start.sh#L10

Did you override the cmd?

**Comment by teohhanhui** [comment]
Or, more likely, I suspect you did not wait for the startup script to run to completion. We should mention this in the docs. :smile:

**Comment by shaisachs** [comment]
What do you mean by the startup script? Admittedly I may be doing the wrong thing, but here is my entire process:

1. Download https://api.github.com/repos/api-platform/api-platform/zipball
2. cd /path/to/api-platform
3. docker-compose up -d 
4. docker-compose exec php bin/console doctrine:schema:create

It's step 4 where things go pear-shaped as described above. I've seen this happen on a couple different machines. Could be I'm missing a step!

Even so - it may be worth refactoring the docs a little bit to give a clearer step-by-step set of instructions for the docker install path, since as it is there's a bit of exposition that muddies things up a little. I'd certainly be happy to give that a crack if y'all are amenable.

**Comment by teohhanhui** [comment]
After `docker-compose up -d`, do `docker-compose logs -f php` to see the
progress. When you see a message that fpm is ready, that's the time when
you'll be able to continue.

**Comment by shaisachs** [comment]
Oh! I see. I didn't realize that was a necessary step - I thought it was just informational. Mind if I touch up the docs to clarify?

**Comment by teohhanhui** [comment]
Sure, please help us make it better. We might want to look into the
healthcheck feature, but I'm not sure it will help in this case...

**Comment by Simperfit** [comment]
The documentation has been updated and the docker setup too :).
