### ISSUE TITLE
API doc ReDoc in cyrillic

### ISSUE THREAD

**Issue by babeuloula** [api-platform/api-platform#2009]
**API Platform version(s) affected**: 2.6.5

**Description**  
I've recently updated my app to APIP 2.6.5 and when I display my API documentation with ReDoc and I've got some of my properties are in cyrillic.

![image](https://user-images.githubusercontent.com/4849233/132004872-a5b694e4-c598-44ea-82b6-e86255544763.png)

Did you have any ideas to solve this ?

**Comment by dunglas** [comment]
This has been fixed in the dev branch.

**Comment by babeuloula** [comment]
Great, and you have a release date ?
