### ISSUE TITLE
Docker - PWA Image size

### ISSUE THREAD

**Issue by BeyerJC** [api-platform/api-platform#2013]
Hi !

I noticed that the size of the PWA docker image is very high. I did not find the cause yet but when build it is ~770 MB.
It is build from alpine image and just copies a few files and does a yarn install.

Does anyone know what the problem could be ?

**Comment by dunglas** [comment]
The usual suspect is the `node_modules` directory...

**Comment by WhiteRabbitDE** [comment]
Node_modules is 350 MB,  .next is 165 MB.  So i guess there is no way to reduce the size ... 350 MB looks wild to me for JS dependencies.

**Comment by WhiteRabbitDE** [comment]
I did some googling on how to reduce the size but did not find anything that really helped. You if you @dunglas  have no idea or hint for me investigate we can just close the issue.

**Comment by J3m5** [comment]
What I did is generate static files with Next and serve them with nginx but it could be done with caddy I guess.
The image is now 10 Mb.

**Comment by WhiteRabbitDE** [comment]
That sounds like a good idea for the pwa prod Image ! Thanks @J3m5 !
