### ISSUE TITLE
[idea] Voters/ACL & Data Transformer Support

### ISSUE THREAD

**Issue by pierre-H** [api-platform/api-platform#202]
Hi,
First thank you for your great work : Api-Platform is awesome !!!

I'm asking if Api-Platform supports : 

1. Symfony's voter/acl : for example, with a Comment entity, I'd like to get only comments which the user can see. For example

2. Data Transformer (in my case, i've got fields which are in rtf and I'd like to transform them in html and I've got already a Data Transformer for that but I'd like to apply it to Api Platform entity definition)

The first solution I've got is to use a Custom Data Provider but this is in my opinion heavy.

It would be so easy to have something like this : 
1. Voter/ACL :
```
@ApiPlatform(attributes={"isGranted": ".."})
class Comment {
...
}
```

2. DataTransformer :
```
/**
 * @ApiPlatform\DataTransformer({"nameOfDataTransformer"})
 */
private $field;
```

I know that this is possible with Custom Data Provider, but I think these features could be useful...

Again, thank you for your great work !

**Comment by pierre-H** [comment]
For Data Transformer, it's possible to integrate [serializer callback](https://symfony.com/doc/current/components/serializer.html#using-callbacks-to-serialize-properties-with-object-instances).

For ACL/Voter, if it's only for one/few fields (not the entity), it's possible to [change the serialization context dynamically](https://api-platform.com/docs/core/serialization-groups-and-relations#changing-the-serialization-context-dynamically). But it's still a heavy solution, especially if you have (like me) dozens of entity.

**Comment by pierre-H** [comment]
With Api-Platform 2.1, the ACL issue will be easy [see here](https://github.com/api-platform/core/pull/938)

But I can't figure it out how to use serializer callback...

**Comment by dunglas** [comment]
Closing now that api-platform/core#938 is merged, we also have a doc regarding the serializer callback: https://api-platform.com/docs/core/serialization-groups-and-relations#changing-the-serialization-context-dynamically
