### ISSUE TITLE
update docker wsl2 : ERR_CONNECTION_REFUSED localhost

### ISSUE THREAD

**Issue by nicotec** [api-platform/api-platform#2023]
Since the update of docker on windows 10, the browser indicates ERR_CONNECTION_REFUSED with WSL2.

So, I tried to install again with the latest version of apiplatform and the result is the same, I get the same error.

In the Caddy v2.4.5 console:
`
caddy_1     | {"level":"warn","ts":1631795654.224746,"msg":"input is not formatted with 'caddy fmt'","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":2}
`
`
caddy_1     | 2021/09/16 12:34:14 failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/lucas-clemente/quic-go/wiki/UDP-Receive-Buffer-Size for details.
`
`
caddy_1     | {"level":"warn","ts":1631795654.4342203,"logger":"tls","msg":"stapling OCSP","error":"no OCSP stapling for [localhost]: no OCSP server specified in certificate"}
`
`
caddy_1     | 2021/09/16 12:34:14 Warning: "certutil" is not available, install "certutil" with "apt install libnss3-tools" or "yum install nss-tools" and try again
`

**Comment by Chris53897** [comment]
Can you please check if "docker compose 2 RC" is activated in your options? 
https://github.com/api-platform/api-platform/issues/1986#event-5287801959

**Comment by nicotec** [comment]
![image](https://user-images.githubusercontent.com/10002262/133770203-7ebf374b-603f-4369-97b6-9fb57a5caef1.png)

Thank you,

**but unchecking the box is not enough on some computer.**

in this case, execute the command:
`docker-compose disable-v2`
