### ISSUE TITLE
How to disable  and remove PWA Feature

### ISSUE THREAD

**Issue by WA-WilliamKrieg** [api-platform/api-platform#2046]
Hello,

I want install API Platform with docker but I want disable PWA container, compilation and generation.
I did not find how to do it in the documentation.

Can you help me ?

Thanks

**Comment by WhiteRabbitDE** [comment]
How are you starting it ? If you use compose, you can just comment it in the docker-compose.yaml.

You should also remove it from the caddyfile then.
