### ISSUE TITLE
ViolationList normalizer override  : how to change error output format ?

### ISSUE THREAD

**Issue by CaptainFalcon92** [api-platform/api-platform#2060]
Hello to the community ! 

I have a quick question, not a problem but rather a simple "is it known to be possible ?".

I'm making a front app with i18n and i want to deal with translating errors in frontend only.

For this reason, i want to respond with a list of violations having a key (untranslated) but also having the parameters accessible for translation (i.e. using Nuxt3, i18n and Vuelidate2).

By default ApiPlatform sends me back a translated violation list as so :
```json
"violations": [
    {
      "propertyPath": "password",
      "message": "password.weak",
      "code": ""
    }
  ]
```

I manage to find the normalizer responsible for ViolationList at `AbstractConstraintViolationListNormalizer::getMessagesAndViolations` and added a temporary line for test purposes :
```php
// src/Serializer/AbstractConstraintViolationListNormalizer.php

$violationData = [
  'propertyPath' => $this->nameConverter ? $this->nameConverter->normalize($violation->getPropertyPath(), $class, static::FORMAT) : $violation->getPropertyPath(),
  'message' => $violation->getMessage(),
  'code' => $violation->getCode(),
  'params' => $violation->getParameters(), // <-- added this line
];
```

The result is as expected :
```json
"violations": [
    {
      "propertyPath": "password",
      "message": "password.weak",
      "code": "",
      "params": {
        "current": 1,
        "minimum": 3
      }
    }
  ]
```

Is there an official way or mode to enable that give access to violations parameters ?

or

Is there a good way you would recommend me for overriding the ViolationList normalization ?

Thanks ! Have a good day 🌻

**Comment by norkunas** [comment]
@CaptainFalcon92 you can use payload parameter of constraints for this, you'll just need to configure api-platform to expose it:
```
api_platform:
    validator:
        serialize_payload_fields: ~
```

**Comment by CaptainFalcon92** [comment]
Hello @norkunas 👋 

Thank you for givin me a hint. 👍  I did not know i could add payload to constraint.
Although it is not exactly what i was looking for, it appears to solve my problem in a similar fashion.

After some research using the "payload" keyword, in case anyone happen to also wonder how to enrich violation response with some params, here how :

This SF article shows one use-case of payload for severity purpose :
- https://symfony.com/doc/current/validation/severity.html

This AP article shows how to whitelist payloads :
- https://api-platform.com/docs/core/validation/#error-levels-and-payload-serialization


One can add payload on constraint definition - but that means only having static params in payload.
```php
$metadata->addPropertyConstraint('password', new PasswordStrength([
    'payload' => ['test' => 'value']
]));
```

So instead - where i was building my violations - i also added my params to the constraint payload.
```php
$params = [
    'current' => $report['score'],
    'minimum' => $constraint->min,
];

$constraint->payload = $params;
$this->context->buildViolation($constraint->message, $params)->addViolation();
```

Adding the provided line in configuration enables payload :
```yaml
api_platform:
    validator:
        serialize_payload_fields: ~
```

It works fine as is. Thanks again @norkunas ✌️
