### ISSUE TITLE
Composer call in update-deps.sh

### ISSUE THREAD

**Issue by NanneHuiges** [api-platform/api-platform#2072]
**API Platform version(s) affected**: 2.6.6 (probably more, also master branch)

**Description**  
The update-deps.sh file has a "local" call to composer which means composer needs to be installed on the host machine. This does not seem needed, see the `composer update` call some lines higher that uses the docker image. I also suspect that if you do have composer installed it is still not what you would want as this could be a wrong version or a different version of PHP that it runs against.

**How to reproduce**  
Run `update-deps.sh` on a machine that has no composer installed and see:
```
$ ./update-deps.sh 
[...]
./update-deps.sh: 13: ./update-deps.sh: composer: not found
```

**Possible Solution**  
Replace these lines https://github.com/api-platform/api-platform/blob/v2.6.6/update-deps.sh#L11 and beyond:

```
# Update the Symfony skeleton
cd api
composer sync-recipes --force
```
with
```
# Update the Symfony skeleton
docker-compose run php composer sync-recipes --force
```

**Additional Context**  
I'm not familiar enough with the `update-deps` process itself to fully test this, that's why I haven't made PR that might imply that I oversee all effects of this, but this seems to me the right way to call this composer command.

**Comment by dunglas** [comment]
This will not work because Flex needs to access the Git repository, which is outside the container. This tool is intended to be used (mostly) by the maintainers. Except if someone finds an easy hack, we won't introduce much complexity to handle edge cases.

(It should be possible run composer in the container by mounting the whole directory as a volume).

**Comment by NanneHuiges** [comment]
Yeah, I understood it is a maintainer-thing, I was looking into doing the update process myself  to see how complicated that would be in a situation where code starts to drift too far apart etc. Indeed I was afraid it might not be so easy, that's why it wasn't a PR.
I do think this should be run in a container (maybe introduce a 'maintain' container with that specific mount/volume), but I can understand that this would not be a priority. Thanks for you response!
