### ISSUE TITLE
Ability to configure filter arguments per operation

### ISSUE THREAD

**Issue by alexdruhet** [api-platform/api-platform#2075]
Hi,

I need to configure filter arguments for a specific operation. While it's possible and documentate using `ApiFilter` annotation, I don't find any correct syntax to do so for just a single operation where it's only accepted the filter class name.

Is there a way to do so or just this feature does not exists?

Thanks

**Comment by alexdruhet** [comment]
Well, it's funny how opening a ticket prompts you to help yourself...
I solved my problem by declaring 2 service aliases with different arguments and then using these aliases as the filters name, which is the native Symfony method.

**Comment by tezrik** [comment]
I'm find how connect filter for alone operaion ))) https://api-platform.com/docs/core/filters/#basic-knowledge
