### ISSUE TITLE
[Question] about order filter

### ISSUE THREAD

**Issue by xleliberty** [api-platform/api-platform#208]
Hi all, and thanks for this awesome bundle.

after reading the filters doc, i still have a question about order.

Is there a way to provide a default order filter to api collection operations without providing any parameter ? 

for exemple, i want to call:   /api/tracks?state=open

along pages, the order is not always maintained, and i need to do: /api/tracks?state=open&order[id]=asc

Is there an option to force all collections to be ordered by id asc ?

Thanks in advance

**Comment by teohhanhui** [comment]
There is the [OrderExtension](https://github.com/api-platform/core/blob/3fe7ceb0a725f6fada9fb5c398249f800cebb5fd/src/Bridge/Doctrine/Orm/Extension/OrderExtension.php).

To use it:

```yaml
api_platform:
    collection:
        order: 'ASC'
```

Relevant docs: https://github.com/api-platform/docs/blob/79ff981212f9410fd04b5acdf3b0e1a8fb5cab20/core/configuration.md#L48-L49
