### ISSUE TITLE
BUG: swagger_ui specyfication problem

### ISSUE THREAD

**Issue by Suvres** [api-platform/api-platform#2081]
**Description**  
Your swager ui specyfication has to more 'paths' -> 
![obraz](https://user-images.githubusercontent.com/67355511/143415137-43f0cb0e-30c0-4b33-b37f-2393cb9349db.png)

**How to reproduce**  
![obraz](https://user-images.githubusercontent.com/67355511/143415257-d5f94389-d3fb-495d-94a8-a255f047763b.png)

**Possible Solution**  
Change type of fields 'paths' to array

**Comment by Suvres** [comment]
@dunglas

**Comment by Suvres** [comment]
or You can add this->

**Comment by Suvres** [comment]
![obraz](https://user-images.githubusercontent.com/67355511/143415620-6d49a316-96ac-4ad3-af22-8b6bb78f8774.png)
 to SwaggerUiAction

**Comment by Suvres** [comment]
Ehh
You must repair this like in my first photo, because swagger js not working with this bug

**Comment by Suvres** [comment]
@fabpot @dunglas @pborreli @coudenysj

**Comment by alanpoulain** [comment]
Please do not duplicate the issue and ping all the PHP earth...
https://github.com/api-platform/core/issues/4574
