### ISSUE TITLE
Allow Authenticate Button in swagger UI

### ISSUE THREAD

**Issue by sebheitzmann** [api-platform/api-platform#209]
The Authenticate button in the swagger UI is not present. 

After some research it appear that this button require some info in the swagger specification.

like this one.
```json
"securityDefinitions":` {
    "Bearer": {
      "in": "header",
      "type": "accessToken",
      "name": "Authorization"
    }
  },

```

Is there a way to add this in the ui ?

**Comment by Simperfit** [comment]
I think this is fixed with swaggerui v3
