### ISSUE TITLE
AtLeastOneOf - Attempted to call an undefined method named "getNestedContraints"

### ISSUE THREAD

**Issue by lgeorgiev** [api-platform/api-platform#2093]
**API Platform version(s) affected**: 2.6.6 / Symfony 5.4.0

**Description**  
Attempted to call an undefined method named "getNestedContraints" of class "Symfony\Component\Validator\Constraints\AtLeastOneOf".
Did you mean to call "getNestedConstraints"?

**Additional Context**  

![AtLeastOneOf-Did-you-mean-to-call-getNestedConstraints](https://user-images.githubusercontent.com/1999598/145728735-4911f66d-a09b-47b1-ab57-d123c33952ff.png)

**Comment by dunglas** [comment]
This has been fixed in the dev version. We'll tag a new release as soon as we support Symfony 6.
