### ISSUE TITLE
 Did you mean to call "getNestedConstraints"? after update

### ISSUE THREAD

**Issue by kedzier93** [api-platform/api-platform#2094]
**API Platform version(s) affected**: 2.6.6
**Symfony version**: 5.4.1

**Description**  
Symfony start showing error 500, due to incorrect method name. It is used by api platform to check entity by assert, atleastoneof.

**How to reproduce**  
Update symfony by composer to 5.4.1, composer.json in attachment.

**Possible Solution**  
In my opinion there is a typo in two files:

api-platform/core/src/Bridge/Symfony/Validator/Metadata/Property/ValidatorPropertyMetadataFactory.php 
api-platform/core/src/Bridge/Symfony/Validator/Metadata/Property/Restriction/PropertySchemaOneOfRestriction.php

when i change it manually to _getNestedConstraints_ (missing s) everything works good.

**Additional Context**  
[Error message](https://www.dropbox.com/s/qa73og3lx7e9iys/Zrzut%20ekranu%202021-12-14%20o%2000.10.08.png?dl=0)
[composer.txt](https://github.com/api-platform/api-platform/files/7707518/composer.txt)

**Comment by alanpoulain** [comment]
See https://github.com/api-platform/api-platform/issues/2093.
