### ISSUE TITLE
How to update nested entity with api platform?

### ISSUE THREAD

**Issue by Lenny4** [api-platform/api-platform#2096]
I have 2 entities:

Parent:
```php
<?php
#[ApiResource(
    collectionOperations: [
        'get',
        'post',
    ],
    itemOperations: [
        'get',
        'put',
    ],
    attributes: [
        'validation_groups' => ['edition'],
        'normalization_context' => ['groups' => ['r-parent']],
        'denormalization_context' => ['allow_extra_attributes' => false, 'groups' => ['w-parent']],
    ],
    routePrefix: '/api',
)]
#[ORM\Entity(repositoryClass: ParentRepository::class)]
class Parent
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    #[Groups(['r-parent'])]
    private ?int $id = null;

    #[ORM\OneToMany(mappedBy: 'parent', targetEntity: Child::class, cascade: ['persist', 'remove'], orphanRemoval: true)]
    #[Assert\Valid(groups: ['edition'])]
    #[Groups(['r-parent', 'w-parent'])]
    private array|PersistentCollection|ArrayCollection $children;

    public function __construct()
    {
        $this->children = new ArrayCollection();
    }
}
```
Child:
```php
<?php
#[ApiResource(
    collectionOperations: [
        'get',
        'post',
    ],
    itemOperations: [
        'get',
        'put',
    ],
    attributes: [
        'validation_groups' => ['edition'],
        'normalization_context' => ['groups' => ['r-child']],
        'denormalization_context' => ['allow_extra_attributes' => false, 'groups' => ['w-child']],
    ],
    routePrefix: '/api',
)]
#[ORM\Entity(repositoryClass: ChildRepository::class)]
class Child
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(type: Types::INTEGER)]
    #[Groups(['r-parent'])]
    private ?int $id = null;

    #[ORM\Column(type: Types::STRING, length: 1)]
    #[Groups(['r-parent', 'w-parent'])]
    private ?string $name = null;

    #[ORM\ManyToOne(targetEntity: Parent::class, inversedBy: 'children')]
    #[Groups(['r-child'])]
    private ?Establishment $establishment = null;
}
```
# POST

I can create a `Parent` with his child:

`POST` `/api/parents`
```json
{
  "children": [
    {
      "name": "Child 1"
    },
    {
      "name": "Child 2"
    }
  ]
}
```
Result:
```json
{
  "@id": "/api/parents/1",
  "children": [
    {
      "@id": "/api/children/1",
      "name": "Child 1"
    },
    {
      "@id": "/api/children/2",
      "name": "Child 2"
    }
  ]
}
```

# PUT

Now I want to be able to update the names of my children using the `PUT` endpoint of my `Parent`, something like:

`PUT` `/api/parents/1`
```json
{
  "children": [
    {
      "@id": "/api/children/1",
      "name": "Child 1.2"
    },
    {
      "@id": "/api/children/2",
      "name": "Child 2.2"
    }
  ]
}
```
Expected Result:
```json
{
  "@id": "/api/parents/1",
  "children": [
    {
      "@id": "/api/children/1",
      "name": "Child 1.2"
    },
    {
      "@id": "/api/children/2",
      "name": "Child 2.2"
    }
  ]
}
```

But I got:
```json
{
  "@context": "/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Extra attributes are not allowed (\"@id\" is unknown).",
  "trace": [
//    ...
  ]
}
```

Is there a way to do this ?

**Comment by mcanepa** [comment]
@Lenny4 how did you solve it?

**Comment by Lenny4** [comment]
@mcanepa I have created this pacakage https://packagist.org/packages/lenny4/doctrine-merge-persistent-collection-bundle

**Comment by gremo** [comment]
I have the same problem with cart and items resources relation (very similar to your example):

```json
{
   "name":"foo",
   "items":[
      {
         "@id": 1,
         "product": "/api/products/1",
         "quantity": 10
      }
   ]
}
```

Even if cart item with identifier `1` exists, this payload always remove and recreate the item with a new id. That is, is impossible to `PUT` or `PATCH` referecing an existing item.

I've tested it with multiple keys like `"id": 1`, `"@id": 1` and even `"@id": "/api/cart-items/1"`

This is a major problem IMHO, working with nested resource is somehow always needed.

This should be reopened waiting for an official answer.

**Comment by mcanepa** [comment]
@gremo can you post the complete source for your entities? (at least the relevant parts)

I have the same problem and don't know how to solve it

**Comment by gremo** [comment]
@mcanepa ok but this is a WIP pay attention, in this case I think there is a check to add (I'm working with subresources) in order to not update cart items not beloning to the right cart. In order words, I didn't tested what happens when you put an id as a nested resource when that id is not related to the parent that you are updating.

I'll try to strip all not needed properties, let me know if this works for you:

`Cart` class:

```php
namespace App\Entity;

#[ORM\Entity]

#[ApiResource]
#[Get(
    normalizationContext: ['groups' => 'cart:read'],
)]
#[Put(
    denormalizationContext: ['groups' => 'cart:update'],
    validationContext: ['groups' => ['Default', 'cart:update']],
    normalizationContext: ['groups' => 'cart:read'],
)]
class Cart
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Serializer\Groups(['cart:read'])]
    private ?int $id = null;

    #[ORM\OneToMany(
        mappedBy: 'cart',
        targetEntity: CartItem::class,
        fetch: 'EAGER',
        cascade: ['persist'],
        orphanRemoval: true
    )]
    #[Serializer\Groups(['cart:read', 'cart:create', 'cart:update'])]
    private Collection $items;

    public function __construct()
    {
        $this->items = new ArrayCollection();
    }

    public function addItem(CartItem $item): self
    {
        if (!$this->items->contains($item)) {
            $this->items->add($item);
            $item->setCart($this);
        }

        return $this;
    }

    public function removeItem(CartItem $item): self
    {
        if ($this->items->removeElement($item)) {
            if ($item->getCart() === $this) {
                $item->setCart(null);
            }
        }

        return $this;
    }

    /**
     * @return array<int, CartItem>
     */
    #[Assert\Valid]
    public function getItems(): array
    {
        return $this->items->toArray();
    }
}
```

`CartItem` class:

```php
namespace App\Entity;

#[ORM\Entity]

#[ApiResource]
#[Get]
class CartItem
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Serializer\Groups(['cart:read'])]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'items')]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    #[Serializer\Ignore]
    private ?Cart $cart = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getCart(): ?Cart
    {
        return $this->cart;
    }

    public function setCart(?Cart $cart): self
    {
        $this->cart = $cart;

        return $this;
    }
}

```

Example payload of `PUT /api/carts/1` given that cart has a child with id 1, the second one will be created instead:

```json
{
   "items":[
      { "id": 1, "property": "foo" },
      { "property": "bar" }
   ]
}
```

**Comment by mcanepa** [comment]
it worked!!

I leaved my code wihout modifications, but removed the @ in the body of the request

I was doing this for `PUT /api/products/1`

```
{
    "name": "product updated",
    "offers": [
        {
            "@id": "/offers/1",
            "description": "offer updated"
        }
    ]
}
```

Changed to

```
{
    "name": "product updated",
    "offers": [
        {
            "id": "/offers/1",
            "description": "offer updated"
        }
    ]
}
```

**Comment by gremo** [comment]
@mcanepa happy for you! Have you tested PUT/PATCH?

**Comment by mcanepa** [comment]
I've tested only `PUT`

**Comment by mcanepa** [comment]
I don't know if this is an api platorm issue or not, but I think this simple example should be in the docs somewhere...

That `@` in the ID key is misleading

@dunglas

**Comment by 7system7** [comment]
### This bug is still present! 

I scr*wed up net 8 hours to figure out what is goin' on...

The **[docs](https://api-platform.com/docs/core/serialization/#denormalization)** says:
> The following rules apply when denormalizing embedded relations:
> - If an @id key is present in the embedded resource, then the object corresponding to the given URI will be retrieved through the state provider. Any changes in the embedded relation will also be applied to that object.
>  - If no @id key exists, a new object will be created containing state provided in the embedded JSON document.

(And btw, the documentation suggests to use the [Vulcain](https://github.com/dunglas/vulcain) what is actually not working too in todays browsers. The Vulcain's **partly** alternative is the **[103 Early Hints](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/103)**. But it is actually, very poorly supported yet.)

### Example

I have a `Git` parent and a `CryptoKey` child entity w/ one-to-one relation.

However if I send an update like this:

```jsonld
{
	"@context": "\/api\/contexts\/Git",
	"@id": "\/api\/gits\/25",
	"@type": "Git",
	"repo": "git@github.com:yxz/yxz.git",
	"cryptoKey": {
		"@id": "\/api\/crypto_keys\/50"
	}
}
```

**Then it won't work and it creates a new CryptoKey entity in database.** If you send it w/o the `@` as @mcanepa figured out too, then it will work... (and you still have to send an iri in this property) So sad. The "correct" jsonld is like this:

```jsonld
{
	"@context": "\/api\/contexts\/Git",
	"@id": "\/api\/gits\/25",
	"@type": "Git",
	"repo": "git@github.com:yxz/yxz.git",
	"cryptoKey": {
	---->>	"id": "\/api\/crypto_keys\/50"  
	}
}
```

This will update the existing `CryptoKey` entity in this example.

**Comment by Lenny4** [comment]
@7system7 did you try to add the `@context` and `@type` ?

 Like this:

```json
{
  "@context": "\/api\/contexts\/Git",
  "@id": "\/api\/gits\/25",
  "@type": "Git",
  "repo": "git@github.com:yxz/yxz.git",
  "cryptoKey": {
    "@id": "\/api\/crypto_keys\/50",
    "@context": "\/api\/crypto_keys\/MyType",
    "@type": "MyType"
  }
}
```

**Comment by 7system7** [comment]
Yes I did and it did not work.

**Comment by Lenny4** [comment]
@7system7 I suggest you to open a new issue

**Comment by 7system7** [comment]
I was wrong. As I said later, it was a long day. I sent my requests w/ these headers because another investigation to find another bug. And **I forgot to change them later**. 

```http
Content-type: application/json
Accept: application/ld+json
```

If I send w/ these

```http
Content-type: application/ld+json  <---
Accept: application/ld+json
```

then obviously the function working as the documentation says.

**Comment by SylvainNConnect** [comment]
FYI it does't works with PATCH requests now (API Platform 3.1.13), only with PUT request.
