### ISSUE TITLE
Install on Windows 7 using docker toolbox

### ISSUE THREAD

**Issue by silverarm** [api-platform/api-platform#213]
File: Dockerfile
Add in 
RUN chmod +x ./docker/composer.sh
under
 Install composer
and before 
RUN ./docker/composer.sh \

Need to figure out path permissions still

**Comment by Simperfit** [comment]
Is this something related to how you have to do it ?

**Comment by silverarm** [comment]
Create a .env file in same folder as docker-compose.yml
and put in 
COMPOSE_CONVERT_WINDOWS_PATHS=1

**Comment by dunglas** [comment]
Can you review #215?

About `COMPOSE_CONVERT_WINDOWS_PATHS`, I'm not fond of versioning a `.env` file (especially because Symfony will also use `.env` files starting to 3.3). Do you know an alternative solution? Maybe mentioning this in the documentation will be enough?

**Comment by teohhanhui** [comment]
The `.env` file is standard for Docker Compose. Perhaps we can include a `.env.windows.dist`.

**Comment by teohhanhui** [comment]
Oh, I see now. You're using Docker Toolbox which is not the recommended method. I think we should only mention this in the documentation.

**Comment by dunglas** [comment]
Doc PR opened: https://github.com/api-platform/docs/pull/172

**Comment by Simperfit** [comment]
@silverarm could you please review #215  and see if api-platform/docs#172 is ok for you ?
