### ISSUE TITLE
database_driver parameter on fresh install

### ISSUE THREAD

**Issue by thedigital** [api-platform/api-platform#214]
By default, database_driver is hardcoded with pdo_mysql.

In app/config/config.yml, this is hardcoded this way :
doctrine:
    dbal:
        driver:   "pdo_mysql"

I feel like it should be :
doctrine:
    dbal:
        driver:   "%database_driver%"

database_driver should be asked at installation time with default pdo_mysql if you prefer this database but please dont let it be hardcoded.

I lose 20min searching why doctrine couldnt find database_driver: pdo_pgsql driver that i set in app/config/parameters.yml 

Otherwise, install is great

**Comment by dunglas** [comment]
We want to keep as close as possible of the Symfony Standard Edition (and we'll probably switch to Symfony Flex when it will be out) and Symfony hardcode the driver to use: https://github.com/symfony/symfony-standard/blob/master/app/config/config.yml#L45

**Comment by dunglas** [comment]
Take a look at this discussion to understand why `database_driver` isn't in `parameters.yml` anymore: https://github.com/symfony/symfony-standard/pull/776#discussion-diff-23593282
