### ISSUE TITLE
I18n

### ISSUE THREAD

**Issue by nlefebvre1410** [api-platform/api-platform#216]
hi 
Is provided an i18n layer ?

**Comment by dunglas** [comment]
What do you mean by i18n layer?

You can easily integrates solution like Atlantic18/DoctrineExtensions in API Platform to manage different versions of data. There is also the Symfony Translation component included to translate texts / errors and so on.

**Comment by soyuka** [comment]
+1 it's out of scope here

**Comment by nlefebvre1410** [comment]
sorry,
But I do not find much I use for the first time api-platform and it's a bit confusing

**Comment by Simperfit** [comment]
Did you found out what you wanted to achieve, what do you think is confusing ?

**Comment by Simperfit** [comment]
Feel free to ping me if you still have an issue.

**Comment by Renjyy** [comment]
@nlefebvre1410 I wonder if you have succeed to translate your entity ?
