### ISSUE TITLE
custom POST

### ISSUE THREAD

**Issue by nlefebvre1410** [api-platform/api-platform#217]
Hi 
I try to personalize the post in an action but it asks me an id?
```php
namespace AppBundle\Action;

use AppBundle\Entity\Book;
use Doctrine\Common\Persistence\ManagerRegistry;
use GuzzleHttp\Psr7\Request;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\Config\Definition\Exception\Exception;
use Symfony\Component\DependencyInjection\Container;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Authorization\AuthorizationChecker;

class BookSpecial
{
    private $myService;
    /**
     * @var Container
     */
    private $container;

    public function __construct(MyService $myService,Container $container, AuthorizationChecker $checker)
    {
        $this->myService = $myService;
        $this->container = $container;
        $this->authorizationChecker = $checker;
    }

    /**
     * @Route(
     *     name="book_special",
     *     path="api/books/special",
     *     defaults={"_api_resource_class"=Book::class, "_api_item_operation_name"="special"},
     *     options={"i18n" = false }
     * )
     * @Method("POST")
     */
    public function __invoke($data)
    {

        if (!$this->authorizationChecker->isGranted('ROLE_ADMIN')) {
            $data =  array('error'=>410);
            return new JsonResponse($data, 400);
    }
        $this->myService->doSomething($data);


        return $data; // API Platform will automatically validate, persist (if you use Doctrine) and serialize an entity
        // for you. If you prefer to do it yourself, return an instance of Symfony\Component\HttpFoundation\Response
    }
}
```

**Comment by Simperfit** [comment]
What do you mean ? could you please post the error and the entity ?

**Comment by nlefebvre1410** [comment]
`{
  "@context": "/app_dev.php/fr/api/contexts/Error",
  "@type": "Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Invalid identifier \"\", \"id\" has not been found.",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/Applications/MAMP/htdocs/catella-core/vendor/api-platform/core/src/Bridge/Doctrine/Orm/ItemDataProvider.php",
      "line": 159,
      "args": []
    },
    {
      "namespace": "ApiPlatform\\Core\\Bridge\\Doctrine\\Orm",
      "short_class": "ItemDataProvider",
      "class": "ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\ItemDataProvider",
      "type": "->",
      "function": "normalizeIdentifiers",
      "file": "/Applications/MAMP/htdocs/catella-core/vendor/api-platform/core/src/Bridge/Doctrine/Orm/ItemDataProvider.php",
      "line": 69,
      "args": [
        [
          "null",
          null
        ],
        [
          "object",
          "Doctrine\\ORM\\EntityManager"
        ],
        [
          "string",
          "AppBundle\\Entity\\Book"
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\Core\\Bridge\\Doctrine\\Orm",
      "short_class": "ItemDataProvider",
      "class": "ApiPlatform\\Core\\Bridge\\Doctrine\\Orm\\ItemDataProvider",
      "type": "->",
      "function": "getItem",
      "file": "/Applications/MAMP/htdocs/catella-core/vendor/api-platform/core/src/DataProvider/ChainItemDataProvider.php",
      "line": 40,
      "args": [
        [
          "string",
          "AppBundle\\Entity\\Book"
        ],
        [
          "null",
          null
        ],
        [
          "string",
          "special"
        ],
        [
          "array",
          []
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\Core\\DataProvider",
      "short_class": "ChainItemDataProvider",
      "class": "ApiPlatform\\Core\\DataProvider\\ChainItemDataProvider",
      "type": "->",
      "function": "getItem",
      "file": "/Applications/MAMP/htdocs/catella-core/vendor/api-platform/core/src/EventListener/ReadListener.php",
      "line": 94,
      "args": [
        [
          "string",
          "AppBundle\\Entity\\Book"
        ],
        [
          "null",
          null
        ],
        [
          "string",
          "special"
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\Core\\EventListener",
      "short_class": "ReadListener",
      "class": "ApiPlatform\\Core\\EventListener\\ReadListener",
      "type": "->",
      "function": "getItemData",
      "file": "/Applications/MAMP/htdocs/catella-core/vendor/api-platform/core/src/EventListener/ReadListener.php",
      "line": 58,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ],
        [
          "array",
          {
            "resource_class": [
              "string",
              "AppBundle\\Entity\\Book"
            ],
            "item_operation_name": [
              "string",
              "special"
            ]
          }
        ]
      ]
    },
    {
      "namespace": "ApiPlatform\\Core\\EventListener",
      "short_class": "ReadListener",
      "class": "ApiPlatform\\Core\\EventListener\\ReadListener",
      "type": "->",
      "function": "onKernelRequest",
      "file": null,
      "line": null,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "call_user_func",
      "file": "/Applications/MAMP/htdocs/catella-core/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/WrappedListener.php",
      "line": 61,
      "args": [
        [
          "array",
          [
            [
              "object",
              "ApiPlatform\\Core\\EventListener\\ReadListener"
            ],
            [
              "string",
              "onKernelRequest"
            ]
          ]
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "WrappedListener",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener",
      "type": "->",
      "function": "__invoke",
      "file": null,
      "line": null,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "call_user_func",
      "file": "/Applications/MAMP/htdocs/catella-core/var/cache/dev/classes.php",
      "line": 2167,
      "args": [
        [
          "object",
          "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\EventDispatcher\\ContainerAwareEventDispatcher"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "doDispatch",
      "file": "/Applications/MAMP/htdocs/catella-core/var/cache/dev/classes.php",
      "line": 2082,
      "args": [
        [
          "array",
          [
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ],
            [
              "object",
              "Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"
            ]
          ]
        ],
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher",
      "short_class": "EventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\EventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/Applications/MAMP/htdocs/catella-core/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/Debug/TraceableEventDispatcher.php",
      "line": 136,
      "args": [
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\EventDispatcher\\Debug",
      "short_class": "TraceableEventDispatcher",
      "class": "Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher",
      "type": "->",
      "function": "dispatch",
      "file": "/Applications/MAMP/htdocs/catella-core/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php",
      "line": 129,
      "args": [
        [
          "string",
          "kernel.request"
        ],
        [
          "object",
          "Symfony\\Component\\HttpKernel\\Event\\GetResponseEvent"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handleRaw",
      "file": "/Applications/MAMP/htdocs/catella-core/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php",
      "line": 68,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ],
        [
          "string",
          "1"
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "HttpKernel",
      "class": "Symfony\\Component\\HttpKernel\\HttpKernel",
      "type": "->",
      "function": "handle",
      "file": "/Applications/MAMP/htdocs/catella-core/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php",
      "line": 169,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ],
        [
          "string",
          "1"
        ],
        [
          "boolean",
          true
        ]
      ]
    },
    {
      "namespace": "Symfony\\Component\\HttpKernel",
      "short_class": "Kernel",
      "class": "Symfony\\Component\\HttpKernel\\Kernel",
      "type": "->",
      "function": "handle",
      "file": "/Applications/MAMP/htdocs/catella-core/web/app_dev.php",
      "line": 33,
      "args": [
        [
          "object",
          "Symfony\\Component\\HttpFoundation\\Request"
        ]
      ]
    }
  ]
}`

**Comment by nlefebvre1410** [comment]
How to recover you post ?

**Comment by dunglas** [comment]
If you are registering an item operation, you need to add `{id}` in the route name. Then you can retrieve the current data using `$request->attributes->get('data')`.

**Comment by nlefebvre1410** [comment]
Why add an id to a post ?

**Comment by dunglas** [comment]
Because if you are working an item, you need to tell API Platform how to retrieve the data.
It's not mandatory if you use collection operations.

**Comment by nlefebvre1410** [comment]
Do you have an implantation of post a me mount please ?

**Comment by dunglas** [comment]
Can you explain what you try to achieve? Why do you want to create a custom operation instead of using [events](https://api-platform.com/docs/core/events)?

**Comment by oxnel88** [comment]
@nlefebvre1410 try changing the parameter of the route defaults key to: "_api_collection_operation_name"

**Comment by ramzes13** [comment]
To fix this error you need to use annotation for identifier field, ex:

```
    /**
     * @ApiProperty(identifier=true)
     *
     * @var int|null
     */
    protected $entityId;
```

**Comment by Simperfit** [comment]
Feel free to ping me if you still have an issue.

**Comment by julestruong** [comment]
@oxnel88 THANK YOU
