### ISSUE TITLE
Return JSON-LD from ordinary symfony controller

### ISSUE THREAD

**Issue by helios-ag** [api-platform/api-platform#219]
How/is it possible to return json-ld object from ordinal symfony controller?

**Comment by helios-ag** [comment]
Its enough to return JsonResponse from controller which returns, serialized api resource prepared by symfony seriliazer with 'jsonld' param.
i.e 
```php
return new JsonResponse($serializer->serialize($apiResourceObject, 'jsonld'), 201, [], true);
```

**Comment by teohhanhui** [comment]
You are expected to pass in some serialization context. One way is to use the `SerializerContextBuilder`. (Not sure of your exact needs / what you're trying to achieve.)

**Comment by giacono-mcn** [comment]
@helios-ag How do you get $serilizer variable?

**Comment by helios-ag** [comment]
@giacono-mcn inject Serializer into your controller action (i.e. https://symfony.com/doc/current/serializer.html#using-the-serializer-service)).
