### ISSUE TITLE
Caddy does not build

### ISSUE THREAD

**Issue by icfmp** [api-platform/api-platform#2199]
**API Platform version(s) affected**: 2.6.8

**Description**  
Caddy does not build

```console
2022/06/07 08:14:29 [FATAL] exit status 2
[568] Service 'caddy' failed to build : The command '/bin/sh -c xcaddy build     --with github.com/dunglas/mercure     --with github.com/dunglas/mercure/caddy     --with github.com/dunglas/vulcain     --with github.com/dunglas/vulcain/caddy' returned a non-zero code: 1

[569]
Cleaning up project directory and file based variables
00:01
[570] ERROR: Job failed: exit status 1
```

**How to reproduce**  
Build API platform

**Additional Context**  
Gitlab CI/CD

**Comment by icfmp** [comment]
It started this morning for me. It was working properly 3 days ago.

**Comment by icfmp** [comment]
Then what could it be ?
Can I provide some logs ?

**Comment by icfmp** [comment]
Am I the only one with this problem ?

**Comment by icfmp** [comment]
I found a workaround for those who does not use Vulcain.

In your Dockerfiile, comment the Vulcain lines

```Dockerfile
FROM caddy:${CADDY_VERSION}-builder-alpine AS api_platform_caddy_builder

RUN xcaddy build \
	--with github.com/dunglas/mercure \
	--with github.com/dunglas/mercure/caddy 
	# --with github.com/dunglas/vulcain \
	# --with github.com/dunglas/vulcain/caddy
```

**Comment by icfmp** [comment]
Since this problems seems to be related to Vulcain, i'll open an issue there

**Comment by icfmp** [comment]
I think i found why.

The caddy:2-builder-alpine image used by API Platform builds github.com/caddyserver/caddy/v2 **v2.4.3** and go.uber.org/zap **1.17**
![build fail](https://user-images.githubusercontent.com/71736258/172579000-5c693a18-9c28-4ddd-b9a2-caea4e56e104.png)


But two days ago Vulcain had a commit to update requirements :
![Capture d’écran du 2022-06-08 11-11-01](https://user-images.githubusercontent.com/71736258/172579031-3dcd0e9d-927b-4c78-b3d6-842daa6ab1c6.png)

Forcing CADDY_VERSION to 2.5. in the Dockerfile 1 solves the problem.
![Capture d’écran du 2022-06-08 11-18-38](https://user-images.githubusercontent.com/71736258/172580819-8a31f5e7-3cc9-41b6-878c-018bb30fe7cd.png)

**Comment by icfmp** [comment]
It seems that docker did not download the last version, even with a --no-cache.

Don't know why though ...

**Comment by icfmp** [comment]
Same today but with mercure instead

![Capture d’écran du 2022-09-07 09-32-25](https://user-images.githubusercontent.com/71736258/188817106-aa6ed822-fac1-45ea-94ca-543a753ee7c4.png)

I had to change CADDY_VERSION to 2.5.2 in place of 2.5.1. CADDY_VERSION=2 didn't work for me.

**Comment by KojoEnch** [comment]
Same today with a fresh clone, while building with --no-cache. 
Updating caddy version as suggested by @icfmp did the trick: 
```
diff --git a/api/Dockerfile b/api/Dockerfile
index 49452a7..4b8cc49 100644
--- a/api/Dockerfile
+++ b/api/Dockerfile
@@ -121,7 +121,7 @@ RUN set -eux; \
 RUN rm -f .env.local.php
 
 # Build Caddy with the Mercure and Vulcain modules
-FROM caddy:2-builder-alpine AS app_caddy_builder
+FROM caddy:2.5.2-builder-alpine AS app_caddy_builder
 
 RUN xcaddy build \
        --with github.com/dunglas/mercure \
@@ -130,7 +130,7 @@ RUN xcaddy build \
        --with github.com/dunglas/vulcain/caddy
 
 # Caddy image
-FROM caddy:2-alpine AS app_caddy
+FROM caddy:2.5.2-alpine AS app_caddy
 
 WORKDIR /srv/app

**Comment by AlanCrevon** [comment]
Just had the same problem with a fresh install.
```
docker pull caddy:2-builder-alpine 
docker pull caddy:2-alpine 
```
before `docker compose build --pull --no-cache` worked for me without changing any code.

I don't understand why the `--pull --no-cache` had no effect on inherited images, though.

**Comment by dunglas** [comment]
Unfortunately `docker compose build --pull` doesn't update the images used in `FROM` clauses. They must be updated manually. Alternatively, running `docker system prune -a` will remove all currently downloaded images and the next call to `docker compose build` will use the latest versions of all dependencies.

**Comment by janklan** [comment]
In my case, nothing of the following helped:

- `docker system prune -a`
- build without cache
- pull all the latest images manually
- pin a specific version of Caddy
- add `@main` to the Mercure & Vulcain modules
- switch to another internet connection. 
- restart docker

I'm getting `make: *** [build] Error 17` caused by `#0 64.76 2023/06/05 00:41:52 [INFO] exec (timeout=-2562047h47m16.854775808s): /usr/local/go/bin/go get -d -v github.com/dunglas/mercure/caddy@main github.com/caddyserver/caddy/v2@v2.6.4` - this timeout showed up for all plugins I was trying to build:

```
FROM caddy:${CADDY_VERSION}-builder-alpine AS symfony_caddy_builder

RUN xcaddy build \
    --with github.com/caddy-dns/route53 \
    --with github.com/silinternational/certmagic-storage-dynamodb/v3 \
    --with github.com/dunglas/mercure@main \
    --with github.com/dunglas/mercure/caddy@main \
    --with github.com/dunglas/vulcain@main \
    --with github.com/dunglas/vulcain/caddy@main
```

My GitHub token expired since the last time I started the computer, so as a last resort attempt, I'll try to turn the damn thing off and on again, like in the old days. Maybe it's cached somewhere.

**Comment by dunglas** [comment]
@janklan can you try this workaround? https://github.com/dunglas/mercure/issues/770#issuecomment-1558154310

**Comment by janklan** [comment]
> @janklan can you try this workaround? [dunglas/mercure#770 (comment)](https://github.com/dunglas/mercure/issues/770#issuecomment-1558154310)

Yeah that worked. Thanks.
