### ISSUE TITLE
Invalid postgresql chart version used by helm

### ISSUE THREAD

**Issue by SharkEzz** [api-platform/api-platform#2204]
**Description**  
I've got an issue with the API Platform helm chart while doing `helm dependency update` :
```
Getting updates for unmanaged Helm repositories...
...Successfully got an update from the "https://charts.bitnami.com/bitnami/" chart repository
Error: can't get a valid version for repositories postgresql. Try changing the version constraint in Chart.yaml
```

The issue come from the version of the postgresql chart used in the API Platform helm chart who does not exist anymore (`~10.1.4`).
You can see it here : https://artifacthub.io/packages/helm/bitnami/postgresql

**How to reproduce**  

- Clone this repo
- Try to deploy with Helm
- You will get the error message mentioned above

**Possible Solution**  
We can use the `~10.16.2` postgresql chart version instead of the `~10.1.4`, which is still available.
I've tested it locally and it works perfectly well.

If you need any more infos, just ask :+1: 
I can also make a PR directly.

**Comment by dunglas** [comment]
Good catch, can you make the PR and upgrade Postgres to the latest version? Thanks!
