### ISSUE TITLE
Dependency Injection (Autowiring) into a PHPUnit Test-Case

### ISSUE THREAD

**Issue by Mauriceu** [api-platform/api-platform#2206]
Hello!

I have a BaseClass that extends the **ApiTestCase** of PHPUnit. Now in order to generate my Entity Endpoint-URLs, I would like to be able to get the IRI of a given Entity, so, naive as I am, I tried to **autowire** the IriConverter into the BaseClass by trying the following:

This throws an error, because autowiring does not detect the first argument to be an injected service. Also tried to manually define the **$conv** argument to be the **api_platform.iri_converter** in the services.yaml.
```    
public function __construct(IriConverter $conv, ?string $name = null, array $data = [], $dataName = '')
{
        parent::__construct($name, $data, $dataName);
        $this->iriConverter = $conv;
}
```

I do not know if Api Platform has a faulty Setter-Injection integration, but this is not working either. I also tried manually calling that function by declaring the "call" property of that Service in services.yaml, but no luck.
```
/** @required */
public function setConverter(IriConverter $conv): void
{
        $this->iriConverter = $conv;
}
```
Here $container is null
```
public function setUp(): void
{
      $this->iriConverter = self::$container->get('api_platform.iri_converter');
}
```
This throws a ServiceNotFoundException - "The "kernel" service is synthetic, it needs to be set at boot time before it can be used."
```
public function setUp(): void
{
      self::bootKernel();
      $this->iriConverter = self::$container->get('api_platform.iri_converter');
}
```

And this throws another ServiceNotFoundException "The "ApiPlatform\Core\Api\IriConverterInterface" service or alias has been removed or inlined when the container was compiled. You should either make it public, or stop using the container directly and use dependency injection instead".
```
public function setUp(): void
{
        $this->iriConverter = self::$kernel->getContainer()->get('api_platform.iri_converter');
}
```

I am pretty sure I did not fully grasp kernel and container lifecycle, but I also am at my wits end...How do I inject the IriConverter correctly?

Thank you for reading this far.

**Comment by Ledalys** [comment]
Hi,

In my project to get Doctrine I'm doing:
```php
use ApiPlatform\Core\Bridge\Symfony\Bundle\Test\ApiTestCase as TestApiTestCase;

abstract class ApiTestCase extends TestApiTestCase
{
    //...

    protected function getDoctrine(): ManagerRegistry
    {
        if (!static::$booted) {
            throw new \RuntimeException(sprintf('The container is not available. You must call "bootKernel()" or "createClient()" before calling "%s".', __METHOD__));
        }

        $container = static::getContainer();

        return $container->get('doctrine');
    }
}
```
It should work with `api_platform.iri_converter` too.

**Comment by Mauriceu** [comment]
@Ledalys Thank you greatly for your answer! You just lit up a bulb, because now I understand my problem. The setUp()-function is called **before or while** the kernel is booting, so of course I can not fetch the IriConverter. The function used for fetching an IRI now looks like this:
```
protected function getEntityIri(): string {
        if (!$this->iriConverter) {
            $this->iriConverter = self::$container->get(IriConverterInterface::class);
        }
        return $this->iriConverter->getIriFromResourceClass($this->getEntityClass());
}
```
This function is called when a Test-Function is being executed, meaning after setUp(), so the kernel and container should be up and running.If no IriConverter exists, it is fetched from the container.

However, I do feel like this solution is kind of obscure, because dependency injection on instantiation or by setter-injection is usually hailed as the correct way to use Core-Services, but maybe that is just my perception...

Anyway, thank you very much :)
