### ISSUE TITLE
Installing 3.0 beta fails

### ISSUE THREAD

**Issue by tacman** [api-platform/api-platform#2214]
**API Platform version(s) affected**: 3.0 beta 1

**Description**  

```bash
symfony new --webapp api3 && cd api3 
composer config minimum-stability beta
composer req api-platform/core:^3.0

Script cache:clear returned with error code 255
!!  Symfony\Component\ErrorHandler\Error\ClassNotFoundError {#64
!!    #message: """
!!      Attempted to load class "ApiPlatformBundle" from namespace "ApiPlatform\Core\Bridge\Symfony\Bundle".\n
!!      Did you forget a "use" statement for "ApiPlatform\Symfony\Bundle\ApiPlatformBundle"?
!!      """
!!    #code: 0
!!    #file: "./vendor/symfony/framework-bundle/Kernel/MicroKernelTrait.php"
!!    #line: 135
!!    trace: {

```

**Comment by tacman** [comment]
Perhaps the problem is with the recipe, bundles.php shouldn't use the bridge, but this:

    ApiPlatform\Symfony\Bundle\ApiPlatformBundle::class => ['all' => true],

**Comment by vincentchalamon** [comment]
Hello @tacman,

Thanks for opening this issue. This distribution has been updated to API Platform 3.0.0-rc.1. It should be fixed now.

**Comment by thomas-l** [comment]
The recipe update from 2.7.0-rc2 to 3.0.0 did not remove the old line `ApiPlatform\Core\Bridge\Symfony\Bundle\ApiPlatformBundle::class => ['all' => true],` 
so just remove it by hand
