### ISSUE TITLE
Doctrine entity APIResourcce with `messenger=true` does not dispatch messages

### ISSUE THREAD

**Issue by DurandA** [api-platform/api-platform#2240]
**API Platform version(s) affected**: v2.6.8

**Description**  
When using `messenger=true` ApiResource attribute in a Doctrine entity, resources are not dispatched and the Doctrine DataPersister is called. This behavior is in contradiction with [_Symfony Messenger Integration_ documentation](https://api-platform.com/docs/core/messenger/#dispatching-a-resource-through-the-message-bus):

> Note: when using `messenger=true` ApiResource attribute in a Doctrine entity, the Doctrine DataPersister is not called. If you want the Doctrine DataPersister to be called, you should implement a `ResumableDataPersisterInterface` [documented here](https://api-platform.com/docs/core/data-persisters/).

**How to reproduce**  
```php
namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Action\NotFoundAction;
use Doctrine\ORM\Mapping as ORM;

#[ApiResource(collectionOperations: [
        "post" => ["messenger" => true, "output" => false, "status" => 202]
    ], itemOperations: [
        "get" => ["controller" => NotFoundAction::class, "read" => false, "status" => 404]
    ]
)]
#[ORM\Entity]
class Person
{
    #[ORM\Id, ORM\Column, ORM\GeneratedValue]
    private ?int $id = null;

    #[ORM\Column(type: 'string')]
    public string $name;
}
```

```php
namespace App\Messenger\Handler;

use App\Entity\Person;
use Psr\Log\LoggerInterface;
use Symfony\Component\Messenger\Handler\MessageHandlerInterface;
use Symfony\Component\Messenger\Attribute\AsMessageHandler;

#[AsMessageHandler]
class PersonHandler implements MessageHandlerInterface
{
    public function __construct(
        private LoggerInterface $logger
    ) {
    }

    public function __invoke(Person $person)
    {
        $this->logger->info("Person handler called");
    }
}
```

**Comment by predyke** [comment]
Hi!

if you run `bin/console debug:config api_platform` is messenger enabled for you?

If not, add messenger: true in your api_platform configuration.

**Comment by DurandA** [comment]
Yes, messenger is enabled (`debug:config api_platform`) have the following entry:
```
    messenger:
        enabled: true
```

Note that the handler (`PersonHandler`) is called if I remove the Doctrine annotations.

As a side note, should this issue be transferred to https://github.com/api-platform/core/issues?

**Comment by DurandA** [comment]
I created a clean project from scratch to demonstrate the issue and the creation of the Doctrine entity triggers the handler... There is something going wrong with my project.

**Comment by DurandA** [comment]
I found the cause and opened https://github.com/api-platform/core/issues/4902.
