### ISSUE TITLE
Fatal error with  KernelTestCase

### ISSUE THREAD

**Issue by nlefebvre1410** [api-platform/api-platform#225]
`<?php
namespace AppBundle\Tests\Core;

use GuzzleHttp\Client;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Doctrine\Common\DataFixtures\Purger\ORMPurger;

class ApiTestCase  extends KernelTestCase
{

    private static $staticClient;
    /**
     * @var ContainerInterface
     */
    protected $container;

    /**
     * @var string
     */
    protected $authorizationHeaderPrefix = 'Bearer';

    /**
     * @var string
     */
    protected $queryParameterName = 'bearer';

    protected $client;

    public static function setUpBeforeClass()
    {
        self::bootKernel();
        self::$staticClient = new Client(['base_uri' => 'http://catella:8888/', array(
            'request.options' => array(
                'exceptions' => false,
            )
        )]);
    }

    protected function setUp()
    {

        $this->client = self::$staticClient;
    }

    protected function getService($id)
    {
        return self::$kernel->getContainer()
            ->get($id);
    }

    protected function getUrl($route, $params = array(), $absolute = false)
    {
        return $this->getService('router')->generate($route, $params, $absolute);
    }
    protected  function herdear($debug = false,$data =null){
        return array(
            'headers' => array('Content-Type'=> 'application/json','Accept'=> 'application/json','Cache-Control'=> 'no-cache'),
            'body' => json_encode($data),
            'debug' => $debug
        );
    }

    protected function createAuthenticatedClient($username = 'user', $password = 'password')
    {
        $client = static::createClient();
        $client->request(
            'POST',
            $this->getUrl('login_check'),
            array(
                'username' => $username,
                'password' => $password,
            )
        );

        $response = $client->getResponse();
        $data     = json_decode($response->getContent(), true);

        return static::createClient(
            array(),
            array('HTTP_Authorization' => sprintf('%s %s', $this->authorizationHeaderPrefix, $data['token']))
        );
    }

    protected function assertJsonResponse(Response $response, $statusCode = 200, $checkValidJson = true)
    {
        $this->assertEquals($statusCode, $response->getStatusCode(), $response->getContent());
        $this->assertTrue($response->headers->contains('Content-Type', 'application/json'), $response->headers);

        if ($checkValidJson) {
            $decode = json_decode($response->getContent(), true);
            $this->assertTrue(
                ($decode !== null && $decode !== false),
                'is response valid json: [' . $response->getContent() . ']'
            );
        }
    }
    protected function createUser($username, $plainPassword = 'foo')
    {
        $user = new User();
        $user->setUsername($username);
        $user->setEmail($username.'@foo.com');
        $password = $this->getService('security.password_encoder')
            ->encodePassword($user, $plainPassword);
        $user->setPassword($password);
    }
    protected function tearDown()
    {
        parent::tearDown();

    }
}`

hello,
My pb if   self::bootKernel();
error: 
Parse error: parse error, expecting `';'' or `'{'' in /Applications/MAMP/htdocs/catella-core/vendor/api-platform/core/src/Bridge/Symfony/Bundle/DependencyInjection/ApiPlatformExtension.php on line 310

**Comment by dunglas** [comment]
Do you use PHP 7+?

**Comment by nlefebvre1410** [comment]
yes

**Comment by Simperfit** [comment]
Do you still have the bug ?

**Comment by Simperfit** [comment]
Feel free to ping me if you still have an issue.
