### ISSUE TITLE
Search on api-platform.com does not find content

### ISSUE THREAD

**Issue by wazum** [api-platform/api-platform#2257]
**Description**  

I searched for e.g. "subresource" and there are no results. The same for "provider", etc.

<img width="788" alt="Screenshot 2022-09-15 at 16 42 44" src="https://user-images.githubusercontent.com/146727/190434900-e079a101-1e62-4cb5-b177-bd1acd7f9f0e.png">

**Comment by digitaltim-de** [comment]
The same for itemoperations...

**Comment by soyuka** [comment]
should be working now

**Comment by soyuka** [comment]
> The same for itemoperations...

item operations doesn't exist anymore take a look here: https://api-platform.com/docs/core/upgrade-guide/#upgrade-guide
