### ISSUE TITLE
php bin/console make:entity --api-resource - broken, does not work

### ISSUE THREAD

**Issue by bwnek** [api-platform/api-platform#2262]
**API Platform version(s) affected**: 3.0

**Description**  
After cloning a clean 3.0 release, and bringing up the docker containers, I wanted to create new api-resource. To do so, I've been always using given command - `php bin/console make:entity --api-resource`. But executing this command gives an error message: `[ERROR] Missing package: to use the make:entity command, run: composer require api` - just like on plain symfony project. This command works fine when cloning & running some older releases.

**How to reproduce**  
1.) Clone clean 3.0 release
2.) Bring docker containers up
3.) Execute: `php bin/console make:entity --api-resource` on php container

**Possible Solution**  

**Additional Context**  
Running `composer require api` command does not change anything.

**Comment by yobrx** [comment]
Hi,

It's a symfony/maker-bundle issue, not directly API Platform.

An issue has been created here : 

https://github.com/symfony/maker-bundle/issues/1198

**Comment by yobrx** [comment]
This issue has beed fixed with v1.46.0 of symfony/maker-bundle

https://github.com/symfony/maker-bundle/blob/v1.46.0/CHANGELOG.md
