### ISSUE TITLE
Datetime Timezone is persisted incorrectly

### ISSUE THREAD

**Issue by justpilot** [api-platform/api-platform#2267]
**API Platform version(s) affected**: 3.0.0

**Description**  

**datetime** timezone is written incorrect into the database.

**How to reproduce**  

POST JSON data:
```
{
    dateExample: '2022-09-22T17:16:45.133Z'
}
```
RESPONSE Body (TimeZone is correct):
```
{
    dateExample: '2022-09-22T17:16:45+00:00'
}
```
Now using the GET method:
```
{
    dateExample: '2022-09-22T17:16:45+02:00'
}
```
Now the TimeZone is incorrect.

**Possible Solution**  

**Additional Context**  

```
    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    #[Groups(['timer'])]
    private ?\DateTimeInterface $startDate = null;
```
`DATABASE_URL="mysql://app:!ChangeMe!@127.0.0.1:3306/app?serverVersion=mariadb-10.5.16&charset=utf8mb4"`

**Comment by yobrx** [comment]
Hi,

MySQL don't support TimeZone.

Two solutions :
- Convert your datetime in your default timezone before persisting,
- Save timezone in an another column (more complex)

For the first solution, I wrote this class :

```php
<?php

namespace App\Doctrine\Types;

use DateTimeInterface;
use DateTimeZone;
use Doctrine\DBAL\Platforms\AbstractPlatform;
use Doctrine\DBAL\Platforms\MySQLPlatform;
use Doctrine\DBAL\Types\DateTimeType as Base;

/**
 * Fix timezone before save datetime into database.
 */
class DateTimeType extends Base
{
    public function convertToDatabaseValue($value, AbstractPlatform $platform): mixed
    {
        if ($value instanceof DateTimeInterface && $platform instanceof MySQLPlatform) {
            $timezone = new DateTimeZone(date_default_timezone_get());
            if ($value instanceof \DateTimeImmutable) {
                $value = \DateTimeImmutable::createFromInterface($value)->setTimezone($timezone);
            } else {
                $value = $value->setTimeZone($timezone);
            }
        }

        return parent::convertToDatabaseValue($value, $platform);
    }
}
```
And add this in your `doctrine.yaml` :

```yaml
doctrine:
    dbal:
        types:
            datetime: App\Doctrine\Types\DateTimeType
```

**Comment by justpilot** [comment]
Thank you very much!

More official information can be found at:

Doctrine-Project: Projects > ORM > Documentation > Working with DateTime Instances 

[Working with DateTime Instances](https://www.doctrine-project.org/projects/doctrine-orm/en/latest/cookbook/working-with-datetime.html)
