### ISSUE TITLE
Prefix route

### ISSUE THREAD

**Issue by tfournier** [api-platform/api-platform#227]
Hi, I'm using API plaform for my development and I have some problem when i use prefix in routing.yml and custom Action.

My routing.yml : 
```
api:
    resource: '.'
    type:     'api_platform'
    prefix: '/api'

app:
    resource: '@AppBundle/Action/'
    type:     'annotation'
    prefix: '/api'
```

I wrote a custom Action : 

```
class ApiCustomersPost
{
    /**
     * @Route(
     *     name="API_Customers_post",
     *     path="/customers",
     *     defaults={"_api_resource_class"=Customers::class, "_api_collection_operation_name"="post"}
     * )
     * @Method("POST")
     */
    public function __invoke($data) 
    {
        return $data;
    }
}
```

When a I go to the doc I can see my route prefixed by "/api"

![capture d ecran 2017-01-30 a 12 53 15](https://cloud.githubusercontent.com/assets/9422685/22422137/2159840a-e6eb-11e6-841a-bec62bbcf8fc.png)

And the base URL in documentation is : 
![capture d ecran 2017-01-30 a 12 56 32](https://cloud.githubusercontent.com/assets/9422685/22422226/9a80d23e-e6eb-11e6-818e-c4fa6377f08c.png)

I this case, when I want to test my route, the documentation try to call "/api/api/customers"
![capture d ecran 2017-01-30 a 12 59 20](https://cloud.githubusercontent.com/assets/9422685/22422310/f5b60390-e6eb-11e6-9aae-b30aaad3564f.png)

But my routing is ok : with `php bin/console router:debug` I get : 
`API_Customers_post                  POST     ANY      ANY    /api/customers `

And It work when I call the route `/api/customers`with postman.

How can I handle this ?

Regards,

TF

**Comment by dunglas** [comment]
It looks like a bug in the Swagger generator. Ping @Simperfit

**Comment by headonkeyboard** [comment]
@dunglas I've also experienced some problem with route prefixing and custom collection operation.

Here is my routing configuration :

```
api_action:
   resource: '@AppBundle/Action/'
   type:     'annotation'
   prefix: '/api'

api:
    resource: '.'
    type:     'api_platform'
    prefix:   '/api' # Optional
```

And my resource configuration

```
resources:
    AppBundle\Entity\Site:
        collectionOperations:
            last_updates:
                route_name: 'api_sites_last_updates'
            get:
                method: 'GET'
            post:
                method: 'POST'
```

Then, how my routing looks like :

```
api_sites_last_updates                      GET      ANY      ANY    /api/sites/last_updates              
api_sites_get_collection                    GET      ANY      ANY    /api/sites.{_format}                 
api_sites_post_collection                   POST     ANY      ANY    /api/sites.{_format}                 
api_sites_get_item                          GET      ANY      ANY    /api/sites/{id}.{_format}            
api_sites_put_item                          PUT      ANY      ANY    /api/sites/{id}.{_format}            
api_sites_delete_item                       DELETE   ANY      ANY    /api/sites/{id}.{_format}      
```
And in Swagger :

![swagger](https://cloud.githubusercontent.com/assets/837567/23456204/c030dc1a-fe72-11e6-8c8b-b0062c20f444.png)

And when I try to request the route `api_sites_last_updates`

![swagger_response](https://cloud.githubusercontent.com/assets/837567/23456136/7d68cc30-fe72-11e6-89cd-7c09e22cdbb1.PNG)

To solve my problem, I had to remove all the api prefixes. Then, my custom operation `last_updates`  was working.

**Comment by madarco** [comment]
I hade the same issue,

in the meantime I fixed this by overriding the [SwaggerUI/index.html.twig](https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/Resources/views/SwaggerUi/index.html.twig) template by copying it in `app/Resources/views/SwaggerUI/index.html.twig`.

And changing the start of the javascript in the page so that I manually remove the spec.basePath from the start of my paths:

    <script>
        $(function () {
            var spec = {{ spec|replace({'<': '\u003c'})|raw }};
            if(spec.basePath) {
                for (var path in spec.paths) {
                    if (path.indexOf(spec.basePath) == 0) {
                        var newPath = path.substr(spec.basePath.length);
                        spec.paths[newPath] = spec.paths[path];
                        delete spec.paths[path];
                    }
                }
            }

            window.swaggerUi = new SwaggerUi({
                url: '{{ path('api_doc', {'_format': 'json'} ) }}',
                spec: spec,
                dom_id: 'swagger-ui-container',
        // ... rest is the same

**Comment by santiagosemhan** [comment]
+1

**Comment by lvillarino** [comment]
Hi @madarco ,

I copy the file SwaggerUI/index.html.twig template to app/Resources/views/SwaggerUi/index.html.twig and made some modifications but the system is still using the default template.

Do you have any suggestion to find out what happen ?

Thanks

**Comment by madarco** [comment]
Try:
`app/Resources/ApiPlatformBundle/views/SwaggerUI/index.html.twig`

**Comment by lvillarino** [comment]
Thanks @madarco

**Comment by Simperfit** [comment]
This has been fixed in core by @meyerbaptiste

**Comment by jbeurel** [comment]
hi @Simperfit 
In which PR/version ?

**Comment by meyerbaptiste** [comment]
This one: https://github.com/api-platform/core/pull/1192
