### ISSUE TITLE
The service "ApiPlatform\State\CreateProvider" has a dependency on a non-existent service "api_platform.state.item_provider".

### ISSUE THREAD

**Issue by Aerendir** [api-platform/api-platform#2270]
**API Platform version(s) affected**: 3.0.0

**Description**  
When installing ApiPlatform on a fresh SF6 app, this error appears:

> The service "ApiPlatform\State\CreateProvider" has a dependency on a non-existent service "api_platform.state.item_provider".

**How to reproduce**  

```console
symfony new my_project_directory && cd my_project_directory && composer req api-platform/core
```

**Possible Solution**  
I don't know.

**Additional Context**  
Nothing more to say

**Comment by alanpoulain** [comment]
Already fixed here https://github.com/api-platform/core/pull/4954.
