### ISSUE TITLE
Error setting API key in value field

### ISSUE THREAD

**Issue by royalphp** [api-platform/api-platform#2283]
**API Platform version(s) affected**: 3.0.0

**Description**  

I followed the [JWT Authentication](https://api-platform.com/docs/core/jwt) setup and when I configured an endpoint to [SwaggerUI](https://api-platform.com/docs/core/jwt/#documenting-the-authentication-mechanism-with-swaggeropen-api) to conveniently retrieve the token, then the header is sent on requests: `Authorization: Bearer [object Object]`

**How to reproduce**  

After deploying docker, follow the above guide.

**Possible Solution**  

I found exactly the same problem and it's already [solved](https://github.com/swagger-api/swagger-ui/issues/7926). But as far as I know, the SwaggerUI is "standalone" integrated into the ApiPlatform, and you can't fix it with a regular update.

**Additional Context**  

I would be grateful if you tell me how to solve this problem, if this is not an error.

**Comment by alanpoulain** [comment]
Please use `api-platform/core` 3.0.1.

**Comment by royalphp** [comment]
It still doesn't fix this bug!
<img width="289" alt="Знімок екрана 2022-09-30 о 15 57 15" src="https://user-images.githubusercontent.com/6890594/193274773-c2c7558d-4dce-475d-ab8e-037edf3ce473.png">
<img width="336" alt="Знімок екрана 2022-09-30 о 15 54 14" src="https://user-images.githubusercontent.com/6890594/193274837-bf5ae348-a78f-4101-83e9-94c596fc9948.png">

**Comment by soyuka** [comment]
There's an issue on `core` for that lets follow that in https://github.com/api-platform/core/issues/5044
