### ISSUE TITLE
Provide an example of using the api-platform without an ORM

### ISSUE THREAD

**Issue by paolomainardi** [api-platform/api-platform#229]
Firstable, let me thank you for this impressive work!

As written in the subject, would be nice to have an example which makes use of external services wirhout relying to Doctrine, for example the case of a middleware/broker API.

Thanks!

**Comment by dunglas** [comment]
There are some minimal examples here: https://api-platform.com/docs/core/data-providers

Enhancing this doc would be very appreciated 🙂: https://github.com/api-platform/docs

**Comment by paolomainardi** [comment]
Thanks a lot @dunglas that is what exactly i was looking for, i hope to contribute back to the doc very soon.

**Comment by paolomainardi** [comment]
Ok the documentation is quite clear about implementing the data provider, but not how to use it in a entity bundle.

**Comment by dunglas** [comment]
Not sure to get what you mean.

**Comment by paolomainardi** [comment]
For example, let's take the provided example entity:

```
<?php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * This is a dummy entity. Remove it!
 *
 * @ApiResource
 * @ORM\Entity
 */
class Foo
{
    /**
     * @var int The entity Id
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string Something else
     *
     * @ORM\Column
     * @Assert\NotBlank
     */
    private $bar = '';

    public function getId()
    {
        return $this->id;
    }

    public function getBar() : string
    {
        return $this->bar;
    }

    public function setBar(string $bar)
    {
        $this->bar = $bar;
    }
}
```

How can be used the custom data provider instead of Doctrine, keeping the same framework functionalities like docs generations, filter etc ?

**Comment by dunglas** [comment]
Built-in filters are a Doctrine feature.

However docs generation (including custom filter) and all other features will work as long as the PHPDoc is present.

**Comment by paolomainardi** [comment]
@dunglas thanks for the quick reply!
And we come back to the initial question, how the custom data provider should be used/included instaed of the standard one ? An example file like the one below would be gold :)

**Comment by dunglas** [comment]
Just remove all `ORM` annotations from the `Foo` entity, and return instances of this class form you custom data providers as explained in the doc.
It's now the responsibility of your providers to return instances of `Foo`. API Platform will still be able to deal with them thanks to the `@ApiResource` annotation.

**Comment by insekticid** [comment]
There is no mention about referenced objects and how to deal with it

**Comment by devrck** [comment]
@dunglas How can you apply a custom filter to a custom data provider how are they linked together?

**Comment by soyuka** [comment]
@devrck it's just a service that you inject in your data provider.

**Comment by devrck** [comment]
@soyuka I saw the previous [answer](https://github.com/api-platform/api-platform/issues/262#issuecomment-325905346) but I was wondering if there is a guideline on how to do it better.

**Comment by soyuka** [comment]
What do you mean? You can also do your filtering directly in the data provider ;).

**Comment by Simperfit** [comment]
@devrck @soyuka is right, you can do what you want in the custom data provider ;)

**Comment by dunglas** [comment]
Can we close this one?

**Comment by globalglug** [comment]
Hello! I've got the item and collection providers working (my understanding being that these are for GETs) but how do you deal with custom persisters? i.e. deal with a POST so instead of using Doctrine it knows to fire off a web service call elsewhere. I can see how you can do this with an action, but in light of the ability to have custom data providers, can you have custom data persisters? My thinking - I want to avoid having an action for every POST (unless you can advise me how you can create a generic action for all POSTS perhaps).

**Comment by dunglas** [comment]
Just register a kernel event like we do for Doctrine!

* The Doctrine event (just create a new class containing your own persistence logic): https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/EventListener/WriteListener.php
* The service definition: https://github.com/api-platform/core/blob/f21b1658d11bbca432ca0a6a8c995262064b382c/src/Bridge/Symfony/Bundle/Resources/config/doctrine_orm.xml#L100-L104

**Comment by globalglug** [comment]
There is a complaint about generating the IRI:
`Unable to generate an IRI for the item of type \"AppBundle\\Entity\\Example\""`

This complaint seems to occur before getting to either the built-in write listener or the new one I've created.

I do have `@ApiProperty(identifier=true)` above the `private $id` property of the example entity.

**Comment by insekticid** [comment]
@globalglug it should be protected

**Comment by globalglug** [comment]
Thanks, @insekticid but that doesn't seem to fix it - the same error response about not being able to generate the IRI occurs.

**Comment by globalglug** [comment]
@dunglas OK I've registered my bespoke `WriteListener` as follows in `app\config\services.yml`:

`    api_platform.doctrine.listener.view.write:
        id: api_platform.doctrine.listener.view.write
        class: AppBundle\DataPersister\EventListener\WriteListener
        arguments:
            - '@?doctrine'
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 32 }`

This new class is handling the event. However, I noticed it replaces the default `WriteListener` and that I have to include the persistence logic for Doctrine entities.

Is there no way to have your listener deal with Doctrine entities as normal, but let mine deal with the non-Doctrine entities?

**Comment by mab05k** [comment]
@globalglug Have you found a way to work around that error? I'm getting the same.

```Unable to generate an IRI for the item of type \"AppBundle\\Entity\\CustomData\"```

**Comment by Simperfit** [comment]
@globalglug Maybe is to add a call to the decorated listener when a doctrine entity is found (you can test this with doctrine).

**Comment by Simperfit** [comment]
@globalglug And if you still have question,  think it's just better to open a new issue.

**Comment by gries** [comment]
Hi,
for anybody else that stumbles upon this thread, the easiest solution that I found was to register a new DataPersister using a Tagged Service like so:

**Create your own DataPersister and implement the interface**

```php
<?php
namespace App\DataPersister;

use ApiPlatform\Core\DataPersister\DataPersisterInterface;

class ArrayPersister implements DataPersisterInterface
{

    /**
     * Is the data supported by the persister?
     *
     * @param mixed $data
     *
     * @return bool
     */
    public function supports($data): bool
    {
        if (/* Check if you want to handle the persistence of this data*/) {
            return true;
        }

        return false;
    }

    /**
     * Persists the data.
     *
     * @param mixed $data
     */
    public function persist($data)
    {
        // do your storage
    }

    /**
     * Removes the data.
     *
     * @param mixed $data
     */
    public function remove($data)
    {
        // remove from storage
    }
}
```
**Register the persister as a service**
```yaml
    array_persister:
      class: App\DataPersister\ArrayPersister
      tags:
        - { name: api_platform.data_persister }
```

That's it, no need to wrap the handle doctrine entities as long as your **support** method indicates to ignore them.
