### ISSUE TITLE
API Platform V3 - GraphQL - DeleteMutation does not delete data from database

### ISSUE THREAD

**Issue by kreativwolke** [api-platform/api-platform#2292]
**Hello people,**

I have upgraded from version 2.7 to 3.0. Unfortunately I cannot delete records via GraphQL. Attached you can see my entity, my query. But the record is not deleted from the database.

Do you have any idea what the problem is?

**My entity**
`<?php

namespace App\Entity\Shop;

use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GraphQl\Mutation;
use ApiPlatform\Metadata\GraphQl\QueryCollection;
use ApiPlatform\Metadata\GraphQl\Query;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Doctrine\Orm\Filter\OrderFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\Post;
use App\ApiPlatform\ShopCategorySearchFilter;
use App\Entity\User;
use App\Repository\Shop\CategoryRepository;
use App\State\SetOwnerProcessor;
use Carbon\Carbon;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Ramsey\Uuid\Doctrine\UuidGenerator;
use Ramsey\Uuid\UuidInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Serializer\Annotation\SerializedName;

#[ORM\Entity(repositoryClass: CategoryRepository::class)]
#[ORM\Table(name: "shop_category")]

#[ApiResource(
    graphQlOperations: [
        new Query(
            normalizationContext: ['groups' => ['shop:category:read']],
            name: 'item_query'
        ),
        new QueryCollection(
            normalizationContext: ['groups' => ['shop:category:read']],
            name: 'collection_query'
        ),
        new Mutation(
            normalizationContext: ['groups' => ['shop:category:read']],
            denormalizationContext: ['groups' => ['shop:category:write']],
            security: 'is_granted("ROLE_ADMIN")',
            securityMessage: 'Sorry, only the admin can add a resource',
            name: 'create',
            processor: SetOwnerProcessor::class,
        ),
        new Mutation(
            normalizationContext: ['groups' => ['shop:category:read']],
            denormalizationContext: ['groups' => ['shop:category:write']],
            security: "is_granted('EDIT', object)",
            securityMessage: 'Sorry, only the owner can edit this resource',
            name: 'update'
        ),
        new Mutation(
            security: "is_granted('EDIT', object)",
            securityMessage: 'Only the creator or the admin can delete this resource',
            name: 'delete'
        )
     ]
)]

#[ApiFilter(ShopCategorySearchFilter::class)]
#[ApiFilter(OrderFilter::class, properties: ['createdAt', 'title', 'isPublished'])]

class Category
{
    #[ORM\Id, ORM\GeneratedValue(strategy: 'CUSTOM'), ORM\CustomIdGenerator(class: UuidGenerator::class)]
    #[ORM\Column(type: 'uuid', unique: true)]
    private ?UuidInterface $id = null;

    #[ORM\Column(length: 150)]
    #[Groups(["shop:product:read", "shop:category:read", "shop:category:write"])]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Groups(["shop:category:read", "shop:category:write"])]
    private ?string $description = null;

    #[ORM\OneToMany(mappedBy: 'category', targetEntity: Product::class, cascade: ['persist', 'remove'])]
    #[Groups(["shop:category:read"])]
    private Collection $products;

    #[ORM\Column]
    #[Groups(["shop:category:read", "shop:category:write"])]
    private ?bool $isPublished = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'categories')]
    #[Groups(["shop:category:read", "shop:category:write"])]
    private ?User $owner = null;

    public function __construct()
    {
        $this->products = new ArrayCollection();
        $this->createdAt = new \DateTimeImmutable();
    }
    public function getId() : ?UuidInterface
    {
        return $this->id;
    }
    public function getTitle() : ?string
    {
        return $this->title;
    }
    public function setTitle(string $title) : self
    {
        $this->title = $title;
        return $this;
    }
    public function getDescription() : ?string
    {
        return $this->description;
    }
    public function setDescription(string $description) : self
    {
        $this->description = $description;
        return $this;
    }
    /**
     * @return Collection<int, Product>
     */
    public function getProducts() : Collection
    {
        return $this->products;
    }
    public function addProduct(Product $product) : self
    {
        if (!$this->products->contains($product)) {
            $this->products->add($product);
            $product->setCategory($this);
        }
        return $this;
    }
    public function removeProduct(Product $product) : self
    {
        if ($this->products->removeElement($product)) {
            // set the owning side to null (unless already changed)
            if ($product->getCategory() === $this) {
                $product->setCategory(null);
            }
        }
        return $this;
    }
    public function isIsPublished() : ?bool
    {
        return $this->isPublished;
    }
    public function setIsPublished(bool $isPublished) : self
    {
        $this->isPublished = $isPublished;
        return $this;
    }
    public function getCreatedAt() : ?\DateTimeImmutable
    {
        return $this->createdAt;
    }
    #[Groups(["shop:category:read"]), SerializedName('createdAtAgo')]
    public function getCreatedAtAgo() : string
    {
        return Carbon::instance($this->getCreatedAt())->locale('de_DE')->diffForHumans();
    }

    public function getOwner(): ?User
    {
        return $this->owner;
    }

    public function setOwner(?User $owner): self
    {
        $this->owner = $owner;

        return $this;
    }
}
`
**My query**

`mutation DeleteShopCategory($id: ID!) {
  deleteCategory(input: {id: $id}) {
   category {
      id
    }
  }
}`

**The result - however, the data still exist in the database**
`{
  "data": {
    "deleteCategory": {
      "category": {
        "id": "/categories/4ac7e5b6-21a8-4b22-9f66-517c73ea2817"
      }
    }
  }
}`

Thank you!

**Comment by remyber** [comment]
I had the same problem. It seems that the documentation is not yet up to date.

You have to use **new DeleteMutation** instead of **new Mutation**.
