### ISSUE TITLE
Why aren't hydra and open api3 generating the same components

### ISSUE THREAD

**Issue by aymaneabssi** [api-platform/api-platform#2297]
**Description**  
here I am testing the client generator and I am noticing that the hydra generates only this
`Interface for the "Book" resource type has been generated!

Interface for the "Review" resource type has been generated!

Interface for the "TopBook" resource type has been generated!`

and the openapi3 generate this:
`Interface for the "Book" resource type has been generated!;

Interface for the "Parchment" resource type has been generated!;

Interface for the "Review" resource type has been generated!;

Interface for the "TopBook" resource type has been generated!;
`

and when i looked at the endpoints on the api https://demo.api-platform.com/
i saw that there are 5 
/books*
/parchments*
/reviews*
/stats*
/top_books*

**How to reproduce**  
I lunched the test-gen and test-gen-openapi3 commands

**Comment by alanpoulain** [comment]
Please do not open an issue twice.
