### ISSUE TITLE
Inconsistent ID with PUT operation in API Platform 2.7

### ISSUE THREAD

**Issue by fabienlem** [api-platform/api-platform#2319]
**API Platform version(s) affected**: 2.7 / 3.0

**Description**  
With custom PUT operation, the ID of the resourse is altered in the endpoint response.

My use case is the following:
I have many PUT endpoints on the same API resource with different paths and denormalization contexts.

```
        new Put(
            uriTemplate: '/my_resource/{uuid}/aaa',
            denormalizationContext: [
                'groups' => [
                    'edit_aaa',
                ],
            ],
            ...
        ),
        new Put(
            uriTemplate: '/my_resource/{uuid}/bbb',
            denormalizationContext: [
                'groups' => [
                    'edit_bbb',
                ],
            ],
            ...
        ),
        ...
```

**How to reproduce**  
In Mathias' repository, replace the POST operation line 50 by a PUT operation.
https://github.com/mtarld/apip-ddd/blob/main/src/BookStore/Infrastructure/ApiPlatform/Resource/BookResource.php#L50

In the API response, the @id is then inconsistent:
![image](https://user-images.githubusercontent.com/19775001/199926642-8a1b4bee-7d1f-402c-ab00-cbad4656fa57.png)

Thank you!

**Comment by xavierrr1** [comment]
I had the same problem. Have you tried to set output: Booking::class in your put operation?

**Comment by FACHINA** [comment]
I got the same issue using API Platform 4.3

**Comment by FACHINA** [comment]
<img width="1044" height="587" alt="Image" src="https://github.com/user-attachments/assets/26d94a88-fb40-4d97-8e54-9264129b818e" />
id referenced in violation is not the same as in the request but the given id doesn't exist
