### ISSUE TITLE
[idea] Adding DMS/Filter support

### ISSUE THREAD

**Issue by diegograssato** [api-platform/api-platform#232]
I have an idea to improve ApiPlatform, by adding DMS/Filter support to allow users to implement input filtering in entities using Annotations.

In the physical world, a filter is typically used for removing unwanted portions of input, and the desired portion of the input passes through as filter output (e.g., coffee). In such scenarios, a filter is an operator that produces a subset of the input. This type of filtering is useful for web applications - removing illegal input, trimming unnecessary white space, etc.

It would be so easy to have something like this :

```php
    /**
    * @Filter\StripTags()
    * @Filter\Trim()
    * @Filter\StripNewlines()
    *
    * @var string
    */
    public $name;

    /**
    * @Filter\StripTags()
    * @Filter\Trim()
    * @Filter\StripNewlines()
    *
    * @var string
    */
    public $email;
```

Use this library based zend filter implementation, see repository for more information about implementation:
 - [dms-filter-bundle](https://github.com/rdohms/dms-filter-bundle)

Thank you for your great work!
You can count on my help.

**Comment by Simperfit** [comment]
WDYT @api-platform/core-team ?

For me it could be in a bundle that has a bridge with api-platform and not in core directly.

**Comment by dunglas** [comment]
I agree with @Simperfit, however we can promote this bundle on the website and in the doc (we should do it for Rollerworks Search and the rate limiting bundle too).

**Comment by Simperfit** [comment]
@diegograssato Like @dunglas said, if you are willing to write a bridge or if it's already working, tell us, we could promote that bundle.
