### ISSUE TITLE
PHPUnit tests

### ISSUE THREAD

**Issue by lpitteloud** [api-platform/api-platform#233]
Hello everyone !

I come up with a big problem into my tests suite using `phpunit` and `LiipFunctionalTestBundle`
Each of my tests whose expected a collection returned a response with the documentation page : 

> 2) [...]ArticleControllerTest::testGetSingleArticle
Cache-Control: no-cache, private
Content-Type:  text/html; charset=UTF-8
Link:          <http://localhost/1.0/api/docs.jsonld>; rel="http://www.w3.org/ns/hydra/core#apiDocumentation"
Failed asserting that false is true.

I don't understand why... When I run `debug:router --env=test` command, it listed the correct routes.

Did anyone ever have this problem ?

**Comment by dunglas** [comment]
Can you provide the full stack trace. I don't get the exact problem (the `Link` HTTP header is expected).

**Comment by lpitteloud** [comment]
Thank you for your answer.
I'll try to explain the problem correctly : 

**ArticleControllerTest.php**
```
public function testGetSingleArticle()
{
        $this->client->request('GET', $this->getRouter()->generate('api_articles_get_item', array('id' => $this->fixtures->getReference('article1')->getId())));
        $response = $this->client->getResponse();

        $this->assertEquals(Response::HTTP_OK, $response->getStatusCode());
        $this->assertIsItemOperationResponse($response, Article::class);
}
```

**CustomWebTestCase.php**
```
public function assertIsLDJsonResponse(Response $response)
{
        $this->assertTrue(
            $response->headers->contains('Content-Type', 'application/ld+json'),
            $response->headers
        );
}

public function assertIsItemOperationResponse(Response $response, $type = null)
{
        $this->assertIsLDJsonResponse($response);
        $jsonData = json_decode($response->getContent(), true);

        $this->assertArrayHasKey('@context', $jsonData);
        $this->assertArrayHasKey('@id', $jsonData);
        $this->assertArrayHasKey('@type', $jsonData);

        if (null !== $type) {
            $this->assertEquals($type, $jsonData['@type']);
        }
}
```

Do you need more details ?

**Comment by Simperfit** [comment]
@lpitteloud Yes, could you please post the full error stack trace ?

**Comment by lpitteloud** [comment]
I only have following lines : 

```
vendor/bin/phpunit tests

PHPUnit 5.7.13 by Sebastian Bergmann and contributors.
F.                                                                  2 / 2 (100%)

Time: 2.31 seconds, Memory: 28.00MB

There was 1 failure:

1) Tests\AppBundle\Controller\ArticleControllerTest::testGetSingleArticle
Cache-Control: no-cache, private
Content-Type:  text/html; charset=UTF-8
Link:          <http://localhost/1.0/api/docs.jsonld>; rel="http://www.w3.org/ns/hydra/core#apiDocumentation"

Failed asserting that false is true.

tests/AppBundle/Controller/CustomWebTestCase.php:121
tests/AppBundle/Controller/CustomWebTestCase.php:88
tests/AppBundle/Controller/ArticleControllerTest.php:68

FAILURES!
Tests: 2, Assertions: 3, Failures: 1.
```

**Comment by dunglas** [comment]
```
public function assertIsLDJsonResponse(Response $response)
{
        $this->assertTrue(
            $response->headers->contains('Content-Type', 'application/ld+json'),
            $response->headers
        );
}
```

This assertion is weird. It should be something like `$this->assertEquals('application/ld+json', $response->headers->get('Content-Type'));`

**Comment by lpitteloud** [comment]
True. But the main problem is that I'm testing content-type header of a route I'm not trying tout validate...

**Comment by teohhanhui** [comment]
You've been bitten by the Swagger documentation magic. Ouch!

**Comment by lpitteloud** [comment]
Additional information : 

If I disable api documentation, I got this : `Failed asserting that 500 matches expected 200.`. It seems logical because this is the documentation route which is tested every time. 

Now I'm trying to find why all the routes are redirected to documentation...

**Comment by dunglas** [comment]
Ok got it. You have forgotten to set the proper `Accept: application/ld+json` header and your testing tool set automatically this header if it isn't present to `test/html`, then you get the docs.

Setting the `Accept` header explicitly should fix the problem.

**Comment by lpitteloud** [comment]
Ok, it was that ! Why default format set into configuration file is not applied ?

Thank you for your time anyway :)

**Comment by dunglas** [comment]
It is. But if you (or the testing tool) send a header, it is used in priority (it's the normal behavior). The problem is: the testing tool should not set the `Accept` header implicitly like that.

**Comment by lpitteloud** [comment]
Ok great. Thank you !
