### ISSUE TITLE
OpenAPI responses not overwriting defaults

### ISSUE THREAD

**Issue by Nathanael-Shermett** [api-platform/api-platform#2333]
**API Platform version(s) affected**: 3.0.0

**Description**

When setting the `openapiContext` for some operation, it is possible to set the expected responses, using the `responses` key, like so:

```php
#[ApiResource(operations: [
  new Post(
    uriTemplate: '/some/path',
    controller: SomeAction::class,
    openapiContext: [
      'responses' => [
        '201' => [
          'description' => 'Resource created',
        ],
      ],
    ],
  )],
)]
```

The above correctly updates the 201 response. However, because I am setting `responses` to an array that only contains the 201 response, I would expect that to be the only response that is shown. However, the defaults still remain.

**Expected result**

![expected](https://user-images.githubusercontent.com/33186878/204401333-10715394-4cc7-44f9-bb52-ba2ccbfcfa24.png)

**Actual result**

![actual](https://user-images.githubusercontent.com/33186878/204401330-af873014-7475-4388-bcb8-6d9c817d60c9.png)

**How to reproduce**  

1. Create a custom API operation using the above code snippet.
2. Open the Swagger documentation.
3. Notice that default responses still exist.

**Possible solution**

The challenge here is that the actual solution probably isn't simple. If we change the OpenAPI context handling from "merge" to "set", then that would cascade to all OpenAPI settings, effectively requiring everything to be rebuilt manually each time even a trivial change needs to be made.

I think the best solution would be to allow settings to be manually removed by setting them to `null`. A quick glance over the [OpenAPI Specification](https://swagger.io/specification) seems to suggest that `null` is not something that Swagger handles any particular way, and even if it did, we could still pass this value by using "null" as a string. This change would arguably also not introduce a BC break.

An alternative solution would be to replace "merge" with "set", and then also add some magical `'_inherit' => true` option for each array, or something to that effect. But that seems weird and isn't better than the previous solution.

**Additional context**

One thing I find confusing is that an [issue from 2020](https://github.com/api-platform/api-platform/issues/1498) seems to suggest that the behavior used to be different. I'm not sure what changed since then.

**Comment by grizzlylab** [comment]
Hi @Nathanael-Shermett, I confirm I have the same issue.

**Comment by soyuka** [comment]
will be fixed by https://github.com/api-platform/core/pull/5393
