### ISSUE TITLE
Missing linux headers package during docker build

### ISSUE THREAD

**Issue by jibla** [api-platform/api-platform#2339]
**API Platform version(s) affected**: 3.0.3

**Description**  
When building the source locally with `docker compose build --pull --no-cache` I get the following error:
```
"configure: error: rtnetlink.h is required, install the linux-headers package: apk add --update linux-headers"
```

**How to reproduce**  
Host operating system is the following:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

docker and docker-compose versions are the following:
```
Docker version 20.10.17, build 100c70180f
```

```
docker-compose version 1.29.2, build unknown
```

To reproduce the bug, you need to clone the repo and run the docker compose build command quoted above (following the installation guide in docs).

**Possible Solution**  
Solution should be to add `apk add --update linux-headers` in `api/Dockerfile` (checked and worked for me).

**Comment by foxou33** [comment]
Same issue, same fix worked for me too.

**Comment by mvillarmmem** [comment]
Hi! I am also experiencing this on my Docker, I am using Windows OS, what possible solution needed please?

**Comment by dunglas** [comment]
Can you try with the `main` version of the distribution please?
