### ISSUE TITLE
[Question] Remove _format parameter

### ISSUE THREAD

**Issue by paullla** [api-platform/api-platform#234]
Hi, Is there a way to set default api format and remove parameter _format from all routes?

**Comment by dunglas** [comment]
Yes: https://api-platform.com/docs/core/content-negotiation#enabling-several-formats

This first format will be the default one.

**Comment by teohhanhui** [comment]
> remove parameter _format from all routes

That's not currently possible because it's hardcoded in all routes. Unless you generate all the routes yourself... :disappointed:

**Comment by dunglas** [comment]
Closing as won't fix.

**Comment by greg0ire** [comment]
This means you can't use dots in the value for a route parameter

**Comment by dunglas** [comment]
It can still be done by implementing a custom path resolver: https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Routing/ApiLoader.php#L190

**Comment by greg0ire** [comment]
Thanks for the hint, I will probably need that!

**Comment by jerome2710** [comment]
@dunglas your link now throws a 404. I am having the same issue as @greg0ire, a dot in my route parameter causes issues. How can I use a custom path resolver in the current version?
