### ISSUE TITLE
PWA container fails to start because pnpm is unable to install @api-platform/admin

### ISSUE THREAD

**Issue by HazemKaroui** [api-platform/api-platform#2352]
**API Platform version(s) affected**:3.0.8

**Description**  
On a fresh instance of the Api-platform distribution, the PWA container fails to start because pnpm can't install the admin package

**How to reproduce**  
1. Download and extract the release .tar.gz
2. run `docker compose build --pull --no-cache`
3. run `docker compose up`
4. pwa container throws an error and shuts down

**Additional Context**  
PWA container shows the following log
```bash
2022-12-28 23:34:19 Lockfile is up to date, resolution step is skipped
2022-12-28 23:34:19 Progress: resolved 1, reused 0, downloaded 0, added 0
2022-12-28 23:34:19 .                                        | +458 ++++++++++++++++++++++++++++++++
2022-12-28 23:34:19 undefined
2022-12-28 23:34:19  ERR_PNPM_NO_OFFLINE_TARBALL  A package is missing from the store but cannot download it in offline mode. The missing package may be downloaded from https://registry.npmjs.org/@api-platform/admin/-/admin-3.4.3.tgz.
2022-12-28 23:34:19 
2022-12-28 23:34:19 > pwa@0.1.0 dev /srv/app
2022-12-28 23:34:19 > next dev
2022-12-28 23:34:19 
2022-12-28 23:34:19 sh: next: not found
2022-12-28 23:34:19  ELIFECYCLE  Command failed.
```

**Comment by 0x539** [comment]
I found this comment:

https://github.com/api-platform/api-platform/issues/2351#issuecomment-1366511047

after running:

`docker compose run pwa pnpm install`

then restart the pwa container:

`docker compose restart pwa`

It does seem to load at that point. 

Im assuming that the local pnpm packages in the container doesnt have "admin-3.4.3.tgz." or something and the --offline part of the command is failing.

**Comment by HazemKaroui** [comment]
> I found this comment:
> 
> [#2351 (comment)](https://github.com/api-platform/api-platform/issues/2351#issuecomment-1366511047)
> 
> after running:
> 
> `docker compose run pwa pnpm install`
> 
> then restart the pwa container:
> 
> `docker compose restart pwa`
> 
> It does seem to load at that point.
> 
> Im assuming that the local pnpm packages in the container doesnt have "admin-3.4.3.tgz." or something and the --offline part of the command is failing.

That fixes it!
I'm not sure exactly what the origin of the problem is but I suppose this is not an isolated incident.
Does there need to be a change made in the Dockerfile to avoid this?

**Comment by dunglas** [comment]
Definitely, PR very welcome, or I'll take a look ASAP.

**Comment by dcatipon** [comment]
Seems like dev image is not using or locating the correct `.pnpm-store`.

Setting `store-dir=/.pnpm-store` in an `.npmrc` file fixes the issue for me.

Alternatively, including `pnpm config set store-dir /.pnpm-store` in `CMD` for dev image in the Dockerfile also fixes the issue I think.

**Comment by dunglas** [comment]
Good catch! Thanks @dcatipon. Creating a global `.npmrc` directly in the parent `Docerfile` looks like the best fix to ensure the same store is always used.

Do you want to open a PR?

**Comment by dunglas** [comment]
https://github.com/api-platform/api-platform/pull/2354 fixes the issue on my side, could you test this patch please?
