### ISSUE TITLE
GraphQl ManyToMany relation search filter Semantical Error.

### ISSUE THREAD

**Issue by durimjusaj** [api-platform/api-platform#2369]
Just upgraded to 3.0.10 and after that I got an error only on many to many relations search filter.

eg.
```
#[ORM\ManyToMany(targetEntity: AccessGroup::class, inversedBy: "users")]
#[ORM\JoinTable(name: "user_access_group")]
#[ORM\JoinColumn(name: "user_id", referencedColumnName: "user_id")]
#[ORM\InverseJoinColumn(name: "access_group", referencedColumnName: "name")]
private Collection $accessGroups;
```

And in other side:
```
#[ORM\ManyToMany(targetEntity: User::class, inversedBy: "accessGroups")]
#[ORM\JoinTable(name: "user_access_group")]
#[ORM\JoinColumn(name: "access_group", referencedColumnName: "name")]
#[ORM\InverseJoinColumn(name: "user_id", referencedColumnName: "user_id")]
protected Collection $users;
```

graphql query:

```
query {
  accessGroups(
	page: 1,
	itemsPerPage: 300, 
	users: "/api/users/1"
) {
    collection {
      name
      users {
        collection {
          id
        }
      }
    }
  }
}
```
error:
```
"[Semantical Error] line 0, col 82 near 'name = :name_p1': Error: Class App\\Entity\\User has no field or association named name"
```

This happens in other cases as well, the issue is the same only entities and fields are different. In the Link metadata, looks like toClass and fromClass identifiers are not filled properly when you search for ManyToMany relations, cause the name is the field in JoinTable and not in `user` in this case.

Querying without ManyToMany search property it will work fine and returns related data as it should.

```
query {
  accessGroups(
	page: 1,
	itemsPerPage: 300
) {
    collection {
      name
      users {
        collection {
          id
        }
      }
    }
  }
}
```

**Comment by alanpoulain** [comment]
Could you use 3.1.0? It should solve your issue.

**Comment by durimjusaj** [comment]
@alanpoulain the reason why I updated to 3.0.10 was I had other issues with previous versions which blocked the whole system, like subresource depth or we had some other issues where subresource was returning all table records, but with this version those issues are fixed except this ManyToMany search filter part.

**Comment by durimjusaj** [comment]
@alanpoulain I tried version 3.1.0, same issue for ManyToMany search filter.

**Comment by alanpoulain** [comment]
I cannot reproduce your issue.
Please provide a failing Behat test in a new PR.

**Comment by durimjusaj** [comment]
@alanpoulain the issue was entities without field named id, I had 3 entities without any field named id,  we used `name` field as identifier, I have renamed it to id and everything is working fine now. I think this is by design in api platform which I didn't know. Thank you for your support, appreciate it.
