### ISSUE TITLE
Remove item from collection on an existing entity

### ISSUE THREAD

**Issue by morgane-luminous** [api-platform/api-platform#2373]
Hi, I have a Video entity containing a ManyToMany relationship with a Category entity.
I would like to remove a Category item from its collection, by a PATCH on Video route.

example:
I have a Video entity containing 
```
#[Entity]
#[ApiResource(
    operations: [
        ...
        new Patch(security: "is_granted('ROLE_ADMIN') and object.getAddedBy() == user"),
    ],
)]
class Video {
    #[ORM\ManyToMany(targetEntity: Category::class, mappedBy: 'videos')]
    private Collection $categories;  // currently containing ["/categories/1", "/categories/2"]
}
```

- I've tried to request PATCH `/videos/1` passing the following body:

```
{
    "categories": ["/categories/1"] // consciously removing "/categories/2" to deleting it from collection
}
```

but it does not work. I can only add new categories with this way.
- I've then tried with PUT method, but it worked exactly the same
- I've tried with Subresource, setting my Category entity like the following:
```
#[ApiResource(
    uriTemplate: '/videos/{videoId}/categories/{categoryId}',
    operations: [ new Delete() ],
    uriVariables: [
        'videoId' => new Link(toProperty: 'videos', fromClass: Video::class),
        'categoryId' => new Link(fromClass: Category::class),
    ]
)]
class Category {
    #[ORM\ManyToMany(
        targetEntity: Video::class,
        inversedBy: 'categories'
    )]
    private Collection $videos;
}
```
but it completely delete the category in database.

So how can I do to remove Category item from collection through Video route?

Thanks

**Comment by soyuka** [comment]
The specification doesn't work like this on collection see https://www.rfc-editor.org/rfc/rfc7386#section-3. Handle this yourself in a Processor. A Subresource is a good idea.
