### ISSUE TITLE
[Question] Error after add application/x-www-form-urlencoded Form Data

### ISSUE THREAD

**Issue by ThomAille** [api-platform/api-platform#239]
Hi Guys, 

Since I created the DeserializeListener decorator, I have this error when I make a POST call
I have followed all the steps of this page : https://api-platform.com/docs/core/form-data

Here is the error : 	Uncaught PHP Exception Symfony\Component\Validator\Exception\RuntimeException: "Cannot validate values of type "NULL" automatically. Please provide a constraint." at /Users/Thomas/Project/apiEngine/vendor/symfony/symfony/src/Symfony/Component/Validator/Validator/RecursiveContextualValidator.php line 187

If I remove the decorator I no longer have the error

Do you have an idea ?

Best Regards 
Thomas

**Comment by renan-taranto** [comment]
Hy @ThomAille,
It may not be related to your issue but I had the same error while creating a custom operation and not returning a response (or the $data object) in the __invoke() method like suggested here https://api-platform.com/docs/core/operations#creating-custom-operations-and-controllers.

**Comment by Simperfit** [comment]
@ThomAille Do you still have an issue ? if it's the case could you please provide more information ?
(if you can write a little reproducer it could help us alot :))
