### ISSUE TITLE
Unable to generate an IRI when using foreign key as composite primary key

### ISSUE THREAD

**Issue by rubobaquero** [api-platform/api-platform#2397]
**API Platform version(s) affected**: 3.1.3

**Description**  
I have two entities (Bundle and Price) that are related by a ManyToOne relationship. One Bundle can have multiple Price.

For the entity Price, the primary key is a composite key of bundle and tax. But the problem happens also if the primary key is just the foreign key to bundle.

When trying to get one Price or a Collection of Prices, I receive a 400 error:
`Unable to generate an IRI for the item of type \"App\\Entity\\Price\`

I think I have followed the steps that appear [in the Doctrine docs for composite primary keys](https://www.doctrine-project.org/projects/doctrine-orm/en/current/tutorials/composite-primary-keys.html). My case should be an example of the Use case 1.

I have added the #[ORM\Id] attribute to both columns (bundle and tax) and specified the relationship in both entities.

This is my actual code:

**Entity Bundle**

```
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\BundleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: BundleRepository::class)]
#[ApiResource]
class Bundle
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\OneToMany(mappedBy: 'bundle', targetEntity: Price::class, orphanRemoval: true)]
    private Collection $prices;

    public function __construct()
    {
        $this->prices = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * @return Collection<int, Price>
     */
    public function getPrices(): Collection
    {
        return $this->prices;
    }

    public function addPrice(Price $price): self
    {
        if (!$this->prices->contains($price)) {
            $this->prices->add($price);
            $price->setBundle($this);
        }

        return $this;
    }

    public function removePrice(Price $price): self
    {
        if ($this->prices->removeElement($price)) {
            // set the owning side to null (unless already changed)
            if ($price->getBundle() === $this) {
                $price->setBundle(null);
            }
        }

        return $this;
    }
}

```

**Entity Price**
```
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\PriceRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PriceRepository::class)]
#[ApiResource]
class Price
{
    #[ORM\Id]
    #[ORM\ManyToOne(targetEntity: Bundle::class, inversedBy: 'prices')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Bundle $bundle = null;

    #[ORM\Id]
    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $tax = null;

    #[ORM\Column]
    private ?float $base = null;

    public function __construct(Bundle $bundle, int $tax)
    {
        $this->bundle = $bundle;
        $this->tax = $tax;
    }

    public function getBundle(): ?Bundle
    {
        return $this->bundle;
    }

    public function setBundle(?Bundle $bundle): self
    {
        $this->bundle = $bundle;

        return $this;
    }

    public function getBase(): ?float
    {
        return $this->base;
    }

    public function setBase(float $base): self
    {
        $this->base = $base;

        return $this;
    }

    public function getTax(): ?int
    {
        return $this->tax;
    }

    public function setTax(int $tax): self
    {
        $this->tax = $tax;

        return $this;
    }

}

```

Probably I am missing something stupid, but I have looked through all the Google results, Stackoverflow and Issues here without being able to find the solution.

Thanks in advance!

**Comment by rubobaquero** [comment]
I activated de debugger and went through the error log to try to find the error before the Exception. That lead me to this issue:

[Compose identifiers don't work](https://github.com/api-platform/core/issues/282#issuecomment-1244778653)

Apparently according to that one, all I have to do is add a __toString() method to the Bundle entity:

```
    public function __toString()
    {
        return (string) $this->id;
    }
```

After doing that ... it works!

I think it would be good to add some details [to the docs](https://api-platform.com/docs/core/identifiers/#supported-identifiers) about this particular case of using objects as identifiers, as it's unclear if they could be used or not.

**Comment by j-corral** [comment]
Hi,

Same problem here.
Doctrine ManyToOne Composite keys worked correctly in 2.x.
With the new changes in `ApiPlatform\Api\IdentifiersExtractor.resolveIdentifierValue()`, we must specify `Stringable`identifiers (ManyToOne aren't).

The workaround given here works, but it feels a bit hacky. What if we want to override __toString() with something else ?
The solution given in the other issue (setting the identifier as a method which returns the formated composite key as string) requires a lot of code and is prone to errors.

It would be great to have the old behavior back : if the identifier(s) is a resource, The `IdentifiersExtractor` extracts this resource identifier value.

**Comment by j-corral** [comment]
Thanks for the quick reply @soyuka 

So, what is the best way to implement this common case ? [Use-Case 3: Join-Table with Metadata](https://www.doctrine-project.org/projects/doctrine-orm/en/2.14/tutorials/composite-primary-keys.html#use-case-3-join-table-with-metadata)

**Comment by soyuka** [comment]
it should work: https://github.com/api-platform/core/blob/main/tests/Fixtures/TestBundle/Entity/CompositeRelation.php or please write me a reproducer if there's a bug (example of fixtures: https://github.com/api-platform/core/pull/5447/commits/dd9499ec7a58ac058b52c8258904c2cc6c812c79)

**Comment by wetakflex** [comment]
Open? what was the solution?

**Comment by kkcscheduling** [comment]
please post the solution

**Comment by rkeet** [comment]
Going to add a comment for a solution of how to use Composite keys in URI, fixing the "Unable to generate an IRI when using foreign key as composite primary key" exception. 

As I understand it, it is by design that it does not work out of the box. The below works with OtM - MtO and OtM - OtO. 

Setup: `EntityA - EntityJoin - EntityB`. Entities A and B have a relation to EntityJoin. 

In `EntityJoin` resource configuration (`./config/api_platform/entity-join.yaml`), you need to define the URI Template and the URI Variables to use. It would look something like this (also possible as PHP Attributes): 

```yaml
properties:
  App\EntityJoin:
    entityA:
      identifier: true
    entityB:
      identifier: true

resources:
  App\EntityJoin:
    operations:
      ApiPlatform\Metadata\GetCollection: ~
      ApiPlatform\Metadata\Get:
        uriTemplate: /entity-joins/{entityAId}/{entityBId}{._format}
        uriVariables:
          entityAId:
            fromClass: App\EntityA    # FQCN
            fromProperty: entityA     # Property name on join entity
            identifiers: [ id ]       # Identier property on joined entity - Can be something else, like 'uuid'
          entityBId:
            fromClass: App\EntityB
            fromProperty: entityB
            identifiers: [ id ]
```

Running a `GET /entity-joins/` should give a result like: 

```json
{
    "@context": "/api/contexts/EntityJoin",
    "@id": "/api/entity_joins",
    "@type": "Collection",
    "totalItems": 1,
    "member": [
        {
            "@id": "/api/entity_joins/123e4567-e89b-12d3-a456-000000000000/123e4567-e89b-12d3-a456-111111111111",
            "@type": "EntityJoin",
            "entityA": "/api/entity-a/123e4567-e89b-12d3-a456-000000000000",
            "entityB": "/api/entity-b/123e4567-e89b-12d3-a456-111111111111",
            "updatedAt": "2025-11-09T18:40:50+00:00",
            "createdAt": "2025-11-09T18:40:50+00:00"
        }
    ]
}
```

Hope that helps :)

**Comment by soyuka** [comment]
Hi ! Now with the links hanlder (https://api-platform.com/docs/guides/handle-links/) it should be even easier, don't hesitate to decorate the IRI Converter its a great extension point!
