### ISSUE TITLE
Missing step on getting started documentation (Symfony cache clear)

### ISSUE THREAD

**Issue by nachomozo** [api-platform/api-platform#24]
In "Creating your first API with API Platform" documentation, there is a missing step.
After exposing the API, you must clean Symfony cache.

```
php app/console cache:clear
```

If this step is not performed, the server does not find the new API routes.
I know it's silly, but can save you a few minutes of confusion.

**Comment by maciekpaprocki** [comment]
+1

**Comment by Simperfit** [comment]
You won't need to in the first place since it's done in Docker.
