### ISSUE TITLE
Error on PUT a circular relation on inherited class

### ISSUE THREAD

**Issue by ZeBigDuck** [api-platform/api-platform#240]
Hi all!

That's a really specific issue, here are the things you need to reproduce (given some concrete stuff for easier understanding) :

Item class with discriminator column "type" and inheritance type "JOINED"
Activity class extends Item
Activity.suggestions m2m Activity

From here, when you `PUT` an existing activity as a suggestion to an activity, you'll have the following error :

```
"The discriminator column "type" is missing for "AppBundle\Entity\Activity" using the DQL alias "suggestions_a4"."
```

This is due to the following part of `ItemDataProvider`, when trying to get the activity I wanna add as a suggestion :

```php
        foreach ($this->itemExtensions as $extension) {
            $extension->applyToItem($queryBuilder, $queryNameGenerator, $resourceClass, $identifiers, $operationName, $context);

            if ($extension instanceof QueryResultItemExtensionInterface && $extension->supportsResult($resourceClass, $operationName)) {
                return $extension->getResult($queryBuilder);
            }
        }
```

$extensions contains only one extension in my case, which is `EagerLoadingExtension`.
It seems this class tries to force fetching all data of Activity relations with left join. Result is that because my activity.suggestions is empty, then relations fields are all `null`. But with doctrine discriminator column, the  `type` column is not allowed to be null, and it then results with the error reported above.

For now, I made my own ItemDataProvider that do not pass in extensions loop if I'm on an inherited class and if operationName is null (which is the case when retrieving the "suggested" Activity). But I'm not sure at all that this will not have side effects.

What is this eager extension used for ? May I have side issues with the bypass I made ?

I can't search deeper in here because I don't know what these extensions are being used for. And I don't even know if the problem is because ApiPlatform shouldn't call this extension in such case, or if this doctrine extension doesn't correctly handle this use case.

I hope I made clear by now, and for sure this is a very specific issue, but I think it deserves some interest.

Thank you for reading.

**Comment by soyuka** [comment]
You can disable Eager loading by using:

```
 * @ApiResource(attributes={"force_eager"=false})
```

One of the side-effects is Lazy Loading. If you remove every extension you'll lose filter and pagination extensions, I'd recommend to disable it through the configuration instead.

Read more about this extension [here](https://api-platform.com/docs/core/performance#doctrine-queries-and-indexes).

**Comment by soyuka** [comment]
@ZeBigDuck  Would it be possible to have a subtract of your entites and the HTTP query issued? I'd like to reproduce this to see where there might be an issue!

Thanks!

**Comment by soyuka** [comment]
This works fine to me, just add a getter for `id` on your abstract class:

```php
    public function getId() {
        return $this->id;
    }
```

![postman](https://cloud.githubusercontent.com/assets/1321971/23297679/b1a82a28-fa7a-11e6-8208-44166e199c70.png)

**Comment by Simperfit** [comment]
Any update on this ?
