### ISSUE TITLE
Element operations have a 500 error — access denied.

### ISSUE THREAD

**Issue by royalphp** [api-platform/api-platform#2400]
Hello everybody)

I have several resources that work as expected, but there are two resources that have strange behavior, for example, there are two resources `Image` and `Video` that have standard crud operations, where the `GetCollection` and `Post` collection operations work fine, but the `Get`, `Put`, and `Delete` element operations have a 500 error — access denied.

I've debugged these requests and indeed the authenticated user data is empty (I'm using a jwt token) and as I understand it, the problem occurs specifically in requests with an identifier (I'm using a uuid identifier). And here is the strangest thing, when I changed the names of my resources from `Image & Video` to `Picture & Movie`, this problem disappears and everything works perfectly!

I can't understand what is the problem? Is this an error of the expression parser not being able to correctly map the resource to its security, or are there some keywords that can't be used in the names of their resources?

**Comment by soyuka** [comment]
no idea without a reproducer for support please use other channels
