### ISSUE TITLE
Use an interface as Output in apiResource operation

### ISSUE THREAD

**Issue by ivanmunozruiz** [api-platform/api-platform#2409]
Hello! is there a way to use an interface as output in items operations in api platform 3? that was working in 2.6

`output=SomeOutputInterface::class,
`

Thank You!

**Comment by ivanmunozruiz** [comment]
I have found how to solve it, I can send an array in output like this:

`output: [SomeOutput::class, SomeOtherOutput::class],`

**Comment by ivanmunozruiz** [comment]
Sorry but sending an array doesn't work  because it need a class and a name, is there a way to use an interface? thank you!

**Comment by soyuka** [comment]
You should probably declare your operation on the interface itself

**Comment by soyuka** [comment]
we couldn't reproduce
