### ISSUE TITLE
Custom action documentation

### ISSUE THREAD

**Issue by komik966** [api-platform/api-platform#241]
I prefer using built-in api-platform documentation than NelmioApiDoc (which is also good, but api-platform's is more friendly).
I need to implement custom authentication actions, which requires username and password as a request and returns api token as a response.
Is there any solution to document such actions in api-platform's documentation? Maybe through annotations?
I've been looking for solution in the source, but with no results.
Thanks in advance

**Comment by alborq** [comment]
You can look my post on  #246

**Comment by komik966** [comment]
Resolved in #246, thanks @alborq
