### ISSUE TITLE
[3.1] DTO @id not generating when identifier different that id

### ISSUE THREAD

**Issue by aurogroup** [api-platform/api-platform#2411]
**API Platform version(s) affected**: 3.1

**Description**  
When working with DTO, and setting force_resource_class under normalizationContext, it generates the following error "Can't get a way to read the property \"id\" in class \"App\\Dto\\Output\\UserOutput\".",

After debugging in the source code, i found that the problem is that i'm using uuid as the identifier and not the default id.

If i replace the identifier by the id or in the IdentifiersExtractor class, getIdentifiersFromItem method, i replace the hard coded id by uuid it works as well

if (!$this->isResourceClass($this->getObjectClass($item))) {
    return ['id' => $this->propertyAccessor->getValue($item, 'id')];
}

**Possible Solution**  
In the IriConverter class, generateSymfonyRoute method only extract identifiers if the uri_variables is empty

`
        $identifiers = $context['uri_variables'] ?? [];

        if (\is_object($resource) && !$identifiers) {
            try {
                $identifiers = $this->identifiersExtractor->getIdentifiersFromItem($resource, $identifiersExtractorOperation, $context);
            } catch (InvalidArgumentException|RuntimeException $e) {
                // We can try using context uri variables if any
                if (!$identifiers) {
                    throw new InvalidArgumentException(sprintf('Unable to generate an IRI for the item of type "%s"', $operation->getClass()), $e->getCode(), $e);
                }
            }
        }
`

**Comment by soyuka** [comment]
you're doing something wrong, use your dot as resource.

**Comment by CesarScur** [comment]
I read your exchange with @weaverryan. It looks like a sound observation.

https://symfonycasts.com/screencast/api-platform/serialization-groups#comment-29006
