### ISSUE TITLE
PNPM 8 new release breaking change in lock file definition prevent building docker container

### ISSUE THREAD

**Issue by ravalum** [api-platform/api-platform#2417]
**API Platform version(s) affected**: 3.0.9 (and probably all previous versions using pnpm 7)

**Description**  

This error show up when building container
`ERR_PNPM_FROZEN_LOCKFILE_WITH_OUTDATED_LOCKFILE  Cannot perform a frozen installation because the version of the lockfile is incompatible with this version of pnpm`

**How to reproduce**  

Download latest api platform release
Launch `docker compose up -d`

**Possible Solution**  

In PWA Dockerfile fix pnpm version to 7 by replacing 
`pnpm@latest` by `pnpm@latest-7`

**Additional Context**  

<img width="962" alt="image" src="https://user-images.githubusercontent.com/1615956/229547175-ff93758b-523f-4602-8ab3-c0589aac93d9.png">

**Comment by JeremyPasco** [comment]
Worked for me too, thanks!

**Comment by regisnew** [comment]
Worked for me too.
Tks!

**Comment by Renrhaf** [comment]
+1 - Thanks !
