### ISSUE TITLE
FilterInterface for Get operation

### ISSUE THREAD

**Issue by avinesse** [api-platform/api-platform#2420]
Hello,

I have created a custom ApiFilter  implementing FilterInterface and added it to my ApiResource like so : `#[ApiFilter(DatamartFilter::class)]`.
This works perfectly for the GetCollection operation and I can see my filter parameters in the docs, but I have a use case where I also need these filters for a simple Get operation.   
Basically I have a route `/totalAmount?filter1=X&filter2=Y` : it does not return a collection so I have made it a Get operation but then the filters don't show up in the docs, I can't make them required, etc.   
Is there a way to apply my filter to a Get operation ?

Thank you

**Comment by mxmp210** [comment]
If you're using default providers, i.e., Doctrine Provider, it only impmements a certain amount of default operations. Filters are essentially collection operarions.

For customising providers, you need to decorate providers or write your own providers. The url parameters in the operation seem like anti-patten, when we are talking about true RESTful api, and you can always add new resources with custom DTOs and feed them from custom providers. 

You use utilize custom state providers as stated in docs : [State Providers](https://api-platform.com/docs/core/state-providers/)

You can extract `uriVariables` and provide the hydrated object from the database according to parameters.

**Comment by soyuka** [comment]
https://github.com/api-platform/core/issues/5527
