### ISSUE TITLE
Non entity based response

### ISSUE THREAD

**Issue by anisolankure** [api-platform/api-platform#243]
Hi,

I am looking to get some response back without using any entities/entity. I know the DataProvider is there but that also needs to be called from action as service and every action is based on entity. 
**OR** 
In other words I am looking a way to use api_platform actions to get response back without interacting with entity. 
Any help will be appreciated.
Thank you in advance.

**Comment by remoteclient** [comment]
Hi @anisolankure,
Did you manage to get it working?
