### ISSUE TITLE
Api platform 3.1 [Semantical Error] line 0, col 40 near 'dice_id IN (SELECT': Error: Invalid PathExpression. StateFieldPathExpression or SingleValuedAssociationField expected.

### ISSUE THREAD

**Issue by djo57** [api-platform/api-platform#2430]
**API Platform version(s) affected**: 3.1

**Description**  
Hi,

I have the following error : [Semantical Error] line 0, col 40 near 'dice_id IN (SELECT': Error: Invalid PathExpression. StateFieldPathExpression or SingleValuedAssociationField expected.

I have 2 entities with a ManyToMany relation : Dice & Face
I created a collection to retrieve all dices related to a Face and an other to retrieve all faces related to a Dice
The first one works great but not the second whereas the code is the same

**How to reproduce**  
`#[ApiResource(
    uriTemplate: '/faces/{id}/related_dices',
    uriVariables: [
        'id' => new Link(
            fromClass: Face::class, 
            fromProperty: 'dice_id'
        )
    ], 
    requirements: ['id' => '\d+'],
    operations: [new GetCollection()]
)]`

The getSQL from Doctrine QueryBuilder :
`SELECT d0_.id AS id_0, d0_.name AS name_1, d0_.faces AS faces_2 FROM `dice` d0_ 
WHERE d0_.id IN (
    SELECT d1_.id FROM face f2_ 
    INNER JOIN face_dice f3_ ON f2_.id = f3_.face_id 
    INNER JOIN `dice` d1_ ON d1_.id = f3_.dice_id 
    WHERE f2_.id = 1
) 
ORDER BY d0_.id ASC LIMIT 5`

This one works, dice_id is the link between Face & Dice, but

`#[ApiResource(
    uriTemplate: '/dices/{id}/related_faces',
    uriVariables: [
        'id' => new Link(
            fromClass: Dice::class,
            fromProperty: 'faces_obj'
        ),
    ], 
    requirements: ['id' => '\d+'],
    operations: [new GetCollection()]
)]`

I cannot get the SQL

This one doesn't work. faces_obj is the link between Dice & Face

The 2 entities are the same
Dice : id, name, faces_obj (collection of Face)
Face : id, name, dice_id (collection of Dice)

I have no idea why that doesn't go in both ways :/

Thx for your help

**Comment by soyuka** [comment]
https://github.com/api-platform/api-platform/issues/2286

**Comment by djo57** [comment]
The solution is : 
`#[ApiResource(
    uriTemplate: '/dices/{id}/related_sets',
    uriVariables: [
        'id' => new Link(
            fromClass: Dice::class, 
            toClass: self::class,
            toProperty: 'dice'
        )
    ],
    requirements: ['id' => '\d+'],
    operations: [new GetCollection()]
)]`
