### ISSUE TITLE
Api platform 3.1 There is no builtin action for the operation. You need to define the controller yourself in . (which is being imported from "/apiplatform/config/routes/api_platform.yaml"). Make sure there is a loader supporting the "api_platform" type.

### ISSUE THREAD

**Issue by djo57** [api-platform/api-platform#2431]
**API Platform version(s) affected**: 3.1

**Description**  
Hello,

I created a custom operation which works, the operation return an array with all the results :
`#[ApiResource(
    description: "Roll the dices",
    operations: [
        new Get(
            name: 'setrolldices',
            uriTemplate: '/sets/{id}/roll',
            uriVariables:[
                'id' => new Link(
                    fromClass: Set::class
                )
            ],
            requirements: ['id' => '\d+'],
            controller: SetRollDicesController::class,
            openapi: new Model\Operation(
                summary: 'Roll the dices !!!', 
                description: 'Get a random value of each dice', 
                responses: [
                    '200!!!' => new Model\Response(
                        description: "Dices value",
                        content: new \ArrayObject([
                            'application/json' => [
                                'schema' => [
                                    'type' => 'array',
                                    'description' => 'The value each dice'
                                ],
                                'example' => [
                                    1,2,3,4
                                ]
                            ]
                        ])
                    )
                ]
            )
        ),
    ]
)]` 

and I would like to create more operation but if I add the following operation I have a fatal error : There is no builtin action for the "setbestdices" operation. You need to define the controller yourself in . (which is being imported from "/apiplatform/config/routes/api_platform.yaml"). Make sure there is a loader supporting the "api_platform" type.

`#[ApiResource(
    operations: [
        new Get(
            name: 'setbestdices',
            uriTemplate: '/sets/{id}/best/{x}',
            uriVariables:[
                'id' => new Link(
                    fromClass: Set::class
                )
            ],
            requirements: ['id' => '\d+', 'x' => '\d+'],
            controller: SetBestDicesController::class,
            openapi: new Model\Operation(
                summary: 'Get the x best dices', 
                description: 'Get a random value of each best dice', 
                responses: [
                    '200!!!' => new Model\Response(
                        description: "Dices value",
                        content: new \ArrayObject([
                            'application/json' => [
                                'schema' => [
                                    'type' => 'array',
                                    'description' => 'The value each best dice'
                                ],
                                'example' => [
                                    6,3,1
                                ]
                            ]
                        ])
                    )
                ]
            )
        )
    ]
)]`

With php bin/console debug:container --tag=roll I have : 
 --------------------------------------- --------------------------------------- 
  Service ID                              Class name                             
 --------------------------------------- --------------------------------------- 
  kernel                                  App\Kernel                             
  App\Controller\RollController           App\Controller\RollController          
  **App\Controller\SetBestDicesController   App\Controller\SetBestDicesController  
  App\Controller\SetRollDicesController   App\Controller\SetRollDicesController**

Why the first case is ok and not the second ? Can I create multiple get operation in the same entity ?

And another little problem is that I can't override the 200 response.

Thx for your help

**Comment by soyuka** [comment]
this is not a support channel
