### ISSUE TITLE
After updating to latest version 3.1.10 and switching from phpdocumentor/reflection-docblock to phpstan/phpdoc-parser SchemaFactory is not working as excepted.

### ISSUE THREAD

**Issue by peter-benicky** [api-platform/api-platform#2442]
**API Platform version(s) affected**:  3.1.10

**Description**  
After updating to latest version and switching from phpdocumentor/reflection-docblock to phpstan/phpdoc-parser SchemaFactory is not working as excepted. My test are failing on assertMatchesResourceItemJsonSchema. This mainly because that arrays are not longer expanded. If I define array of object (dots) which is not persisted. Schema factory will generate array of strings  ["string"] and not array of objects.

```
Is:
"placeholders": ["string"]

Should be:
"placeholders": [
    {
      "@context": "string",
      "@id": "string",
      "@type": "string",
      "name": "string",
      "description": "string"
    }
  ]
```
 I tried to add readablelink but it does not change. This behaviour is not happening for arrays or collection which are persisted ( toMany relations) this collection are expand when I use readablelink. Am I missing dot or this is a bug?

**How to reproduce**  
See above

**Comment by peter-benicky** [comment]
@soyuka So should I use  phpdocumentor/reflection-docblock until this is fixed?

**Comment by Romaixn** [comment]
Hello @peter-benicky! How is your array of `placeholders` defined within your object? Is it well-documented, with a `@var` for example?

**Comment by pauljura** [comment]
Hi folks,

I'm seeing a similar problem in my project.

I have a custom POST operation for a `Redemption` with a property `$items` that is an array of `RedemptionItem`. The schema looks like this:
```
{
  "account": "string",
  "items": [
    {
      "reward": "string",
      "quantity": 0,
      "fulfilmentData": [
        "string"
      ]
    }
  ]
}
```

but after switching from `phpdocumentor/reflection-docblock` to `phpstan/phpdoc-parser` the schema looks like this:

```
{
  "account": "string",
  "items": [
    "string"
  ]
}
```

and after denormalization `$items` is an array of arrays, instead of an array of `RedemptionItem` objects.

The `$items` property is commented with `/** @var RedemptionItem[] */`

**Comment by pauljura** [comment]
After some further investigation I discovered the problem, so I just wanted to post here for others to see.

The solution was to create missing methods for `addItem` and `removeItem` for my array.

I got a hint from here: https://symfony.com/doc/current/components/property_access.html#writing-to-array-properties

> The PropertyAccess component checks for methods called add{SingularOfThePropertyName}() and remove{SingularOfThePropertyName}(). Both methods must be defined.
