### ISSUE TITLE
[3.0.10] `caddy` build failed : package crypto/ecdh is not in GOROOT

### ISSUE THREAD

**Issue by CugeDe** [api-platform/api-platform#2452]
**API Platform version(s) affected**: 3.0.10

**Description**  
Unable to use the provided Dockerfile to build `caddy` service.

During the `caddy` image build (builder), an error occurs and seems to be linked to the latest stable version of caddy.

`crypto/ecdh: Package crypto/ecdh is not in GOROOT`

**How to reproduce**  
Just get the 3.0.10 release of API-Platform and `docker compose build`.

**Possible Solution**  
As a workaround, I just used the `2.7-builder-alpine` tag for `caddy`  build and `2.7-alpine` for `caddy` runner.

**Comment by toby-griffiths** [comment]
I've also just experienced this issue.  Thanks for the workaround, @CugeDe.  This worked for me.

**Comment by dunglas** [comment]
Fixed by https://github.com/api-platform/api-platform/pull/2453.

You'll have to apply this patch manually in your projet as long a long term solution hasn't been found (see https://github.com/caddyserver/caddy-docker/pull/298).

**Comment by dunglas** [comment]
We now have a better fix. Please si https://github.com/dunglas/symfony-docker/issues/434#issuecomment-1664103478 and https://dunglas.dev/2023/08/6x-faster-docker-builds-for-symfony-and-api-platform-projects/
