### ISSUE TITLE
Custom Operation to show all Offers of a LocalBusiness

### ISSUE THREAD

**Issue by fxkopp** [api-platform/api-platform#247]
Is there a way to create a custom operation that uses the id of a LocalBusiness (Entity) but returns entities of type Offer (resourceClass). Because currently i'm only able to retrieve the id/data for the resource class.

Example:

/author/{id}/books
should show all books of author id 1

**Comment by Simperfit** [comment]
I think this is now possible in master with the work of @soyuka
