### ISSUE TITLE
Use plain IDs

### ISSUE THREAD

**Issue by gouxlord** [api-platform/api-platform#249]
I would like to use API PLATFORM without IRI but old ID references, is there an easy way to do that?

Thank you for attention.

**Comment by dunglas** [comment]
You can easily use API Platform in plain JSON. It's even enabled by default (just append .json to URLs or send application/json in the Accept header).

Regarding plain old ids, it is possible by replacing the item normalizer but it's not supported by default.

**Comment by gouxlord** [comment]
@dunglas yes my problem was related to plain ids, we finally replaced the normalizer. Thx for your support!
Btw, using plain ids by configuration could be a very nice feature!

**Comment by rouflak** [comment]
@dunglas I'm in the same situation and I have replaced the  `ItemNormalizer`.

It's been pretty hard to replace it. The `AbstractItemNormalizer` has private methods that must be overridden to get plain IDs. I've had to copy paste a large amount of line of codes to get it work well.

I think plain IDs will be used for many years to come. As @gouxlord said it would be very nice to have it configurable or at least more easily overrideable.

Thanks!

**Comment by teohhanhui** [comment]
It already works with plain IDs: api-platform/core#877

**Comment by friendsofdevs** [comment]
@teohhanhui does it works with plain IDS out of the box? Trying to send request but still getting "detail": "Expected IRI or nested document for attribute \"contact\", \"integer\" given." (Accept and Content-Type headers are 'application/json')

**Comment by teohhanhui** [comment]
Can we have a test case? :)

**Comment by friendsofdevs** [comment]
Sure

Company entity is https://gist.github.com/friendsofdevs/8588f55598639e820421730628a3eda2 and Contact entity is https://gist.github.com/friendsofdevs/4b5384aacac1fc55cfa4f214c5d212ec

**Comment by friendsofdevs** [comment]
Moreover, even if I set `Accept` to `application/json' I get  response like `[
  {
    "id": 1,
    "contactName": "Surname",
    "contactCompany": "/api/v1/companies/1"
  }
]` (Numerical Ids have been expected instead of string)

**Comment by teohhanhui** [comment]
Yeah, this seems to be a bug.

I can see that it's not covered by this scenario: https://github.com/api-platform/core/blob/master/features/main/content_negotiation.feature#L45-L70

Can you help us add one? :smile:

**Comment by Simperfit** [comment]
It's not the same thing, the id is supported but the relation are using IRIs. should we return numerical value (or string if uuid) when there is a relation and we are using JSON ? @api-platform/core-team

**Comment by soyuka** [comment]
IMO yes, IRI's are part of the jsonld format. When using plain json we should return `{id: 12}`.

**Comment by JarJak** [comment]
@api-platform/core-team do you plan to make this request format working?

**Comment by Simperfit** [comment]
I will do it

**Comment by Simperfit** [comment]
It seems that #1365 has been merged, so this should be fixed.

Could you confirm @gouxlord

**Comment by ELepolt** [comment]
Is there any documentation for this? I'm not sure if I'm missing something but adding `allow_plain_identifiers: true` to my config file isn't accomplishing anything.

**Comment by ELepolt** [comment]
I noticed this line https://github.com/soyuka/core/commit/808b5d3efb529e49adc68b0099c259c62ace7c19#diff-3e45e8e6ce08f8a7cbbbda1601d5ff29R308

`if (true === $this->allowPlainIdentifiers && $this->itemDataProvider) `

Should I be setting `itemDataProvider` somewhere also?

**Comment by gonzalovilaseca** [comment]
@ELepolt Did you find a solution? I'm having the same issue

**Comment by J4VMC** [comment]
@dunglas could you please provide some clarity about this? @ELepolt, @gonzalovilaseca and I are having the same issue, but the documentation is non-existent on the api-platform website.

**Comment by dunglas** [comment]
@J4VMC see https://github.com/api-platform/core/pull/2022#issuecomment-398851861 for the current status. Help on this topic will be very welcome.

**Comment by J4VMC** [comment]
> @J4VMC see [api-platform/core#2022 (comment)](https://github.com/api-platform/core/pull/2022#issuecomment-398851861) for the current status. Help on this topic will be very welcome.

Thanks @dunglas
