### ISSUE TITLE
Github repository generator might be deprecated

### ISSUE THREAD

**Issue by clifflo** [api-platform/api-platform#2490]
**API Platform version(s) affected**: 3.4

I have tried the Github repository generator for a new Api-platform project. Afterwards I have tried to use `docker compose pull --include-deps` but it said that the image for Caddy, Php are wrong then. Then I downloaded the Tar files and successfully run the project. Is the Github repository generated version deprecated? But in the docker-compose.yml the version should be 3.4.

**Comment by beejaz** [comment]
I think this is caused (might be) because of a typo in this commit, https://github.com/api-platform/api-platform/pull/2480/files#diff-e45e45baeda1c1e73482975a664062aa56f20c03dd9d64a827aba57775bed0d3R5 

I dont recognize those images names. Waiting for @dunglas response here https://github.com/api-platform/api-platform/issues/2480#issuecomment-1656721241_

**Comment by dunglas** [comment]
The generator isn't deprecated. The doc is just updated. These images will be built locally. Just run: `docker compose up --wait`, this should be enough

**Comment by dunglas** [comment]
I updated the doc to prevent this warning: https://github.com/api-platform/docs/pull/1789

**Comment by beejaz** [comment]
@dunglas Hm, I just tried it and still got error, where is the image name app-php coming from?

```
❯ docker compose build --no-cache --pull                                                                                                                                  Sun Jul 30 09:23:16 2023
[+] Building 10.2s (2/3)                                                                                                                                                                          
[+] Building 64.5s (3/3)                                                                                                                                                                          
 => [php internal] load .dockerignore                                                                                                                                                        0.0s
 => => transferring context: 493B                                                                                                                                                            0.0s
 => [php internal] load build definition from Dockerfile                                                                                                                                     0.0s
 => => transferring dockerfile: 3.44kB                                                                                                                                                       0.0s
 => ERROR [php] resolve image config for docker.io/docker/dockerfile:1.4                                                                                                                    10.3
 ```

**Comment by dunglas** [comment]
It's just a name for the image that is built locally. What version of Docker and Docker Compose do you use?

**Comment by dunglas** [comment]
Do you use a proxy? https://github.com/microsoft/vscode-remote-release/issues/7291

**Comment by beejaz** [comment]
```
❯ docker -v
Docker version 24.0.2, build cb74dfc

❯ docker compose version
Docker Compose version v2.18.1
```

Win 11, WSL2, Docker Desktop 4.20.1 (110738)

**Comment by beejaz** [comment]
> Do you use a proxy? [microsoft/vscode-remote-release#7291](https://github.com/microsoft/vscode-remote-release/issues/7291)

Uh, I don´t use a proxy per my known configuration atleast but I will read trough these issues to see if I can find the issue because it sounds similar to my environment/setup!
