### ISSUE TITLE
Duplicated SELECT WHERE on query using filter + serialized subressource

### ISSUE THREAD

**Issue by brunonic** [api-platform/api-platform#2503]
Hi,

For an unknown reason, when a filter is applied on a route using a subressource in serialization, a WHERE is used twice.

Exemple : 

1 - I'm looking for Pizzas without any subressource requested and with a date filter : 

#### Query generated :
```
SELECT
  c0_.id AS id_26
FROM
  pizza c0_
WHERE
  c0_.created_at >= ?
ORDER BY
  c0_.created_at DESC
LIMIT
  30
```

2 - I'm looking for Pizzas with subressource (ingredients) and with a date filter : 

#### Queries generated :
```
SELECT
  DISTINCT c0_.id AS id_0
FROM
  pizza c0_
  LEFT JOIN pizzas_ingredients c2_ ON c0_.id = c2_.pizza_id
  LEFT JOIN ingredient c1_ ON c1_.id = c2_.ingredient_id
WHERE
  c0_.id IN (
    SELECT
      c3_.id
    FROM
      pizza c3_
      LEFT JOIN pizzas_ingredients c5_ ON c3_.id = c5_.pizza_id
      LEFT JOIN ingredient c4_ ON c4_.id = c5_.ingredient_id
    WHERE
      c3_.created_at >= ?
  )
ORDER BY
  c0_.created_at DESC
LIMIT
  30

______

SELECT   …
  c0_.id AS id_26   …
FROM
  pizza c0_
  LEFT JOIN pizzas_ingredients c2_ ON c0_.id = c2_.pizza_id
  LEFT JOIN ingredient c1_ ON c1_.id = c2_.ingredient_id
WHERE
  c0_.id IN (
    SELECT
      c3_.id
    FROM
      pizza c3_
      LEFT JOIN pizzas_ingredients c5_ ON c3_.id = c5_.pizza_id
      LEFT JOIN ingredient c4_ ON c4_.id = c5_.ingredient_id
    WHERE
      c3_.start_at >= ?
  )
  AND c0_.id IN (?)
ORDER BY
  c0_.created_at DESC
```

Why a `c0_.id IN (SELECT...` is generated for the second query when a `AND c0_.id IN (?)` is applied right after ? 

I'm working on a old project using api-platform 2.6 and I can't currently upgrade to a recent version.

**Comment by soyuka** [comment]
we try to do something that works everywhere but it comes with tradeoffs... I'd suggest to create your own provider to query the subresource and to apply api platform filters using our doctrine extensions (see our doctrine providers).

**Comment by brunonic** [comment]
@soyuka I'm ok with that, but there is no logic in a usage of `c0_.id IN ... AND c0_.id IN ...`...
