### ISSUE TITLE
Impossible to disable all collectionOperations when using XML

### ISSUE THREAD

**Issue by sawmurai** [api-platform/api-platform#252]
I want to disable all collectionOperations via resources.xml. Unfortunately I cannot specify an empty tag (i.e. `<collectionOperations />` (analog to yml or annotations where collectionOperations encloses the list of all allowed operations) because in xml `<collectionOperation>` is used. 

If I provide one `<collectionOperation>` only the provided operation is allowed.
If I provide no `<collectionOperation>` all operations are allowed (which is the default).

So there is no way to disable all operations using xml.

**Comment by soyuka** [comment]
I'm not sure what would be the proper way to do this in xml. Should we add a `node` for disallowing operations?

ping @dunglas @teohhanhui

**Comment by sawmurai** [comment]
I think the proper way would be to have an optional `<collectionOperations>` tag (not provided -> all operations enabled) that contains 0-n `<collectionOperation>` tags. But that would break existing configurations

**Comment by soyuka** [comment]
This would indeed make sense, like:

No-op:

```xml
<collectionOperations />
```

Custom
```xml
<collectionOperations>
    <collectionOperation method="GET" />
</collectionOperations>
```

Without the node, everything operation is enabled.

@sawmurai would you be able to submit a pull request for this? I'm not sure that we can find a cleaner fix without breaking current xml implementations and we have some pending pull requests that are breaking things anyway (ie new release soon? I hope :p).

**Comment by sawmurai** [comment]
I will give it a try tonight :)

**Comment by sawmurai** [comment]
There you go. I also submitted a PR to update the documentation.

**Comment by meyerbaptiste** [comment]
This issue can be closed now 😉
