### ISSUE TITLE
Custom operation route "Not Found" error

### ISSUE THREAD

**Issue by mitalcoi** [api-platform/api-platform#253]
My API Resource:
```php
namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ApiResource(
 *     collectionOperations={
 *        "list"={"route_name"="campaign_list"}
 *     }
 * )
 * @ORM\Entity
 */
class Campaign {
...
}
```

My custom action:

```php
namespace AppBundle\Action;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\JsonResponse;
use AppBundle\Entity\Campaign;
class CampaignList
{
    /**
     * @Route(
     *     name="campaign_list",
     *     path="/list",
     *     defaults={
     *          "_api_resource_class"=Campaign::class,
     *          "_api_collection_operation_name"="list"
     *     },
     *
     * )
     * @Method("GET")
     */
    public function __invoke()
    {
       return new JsonResponse(['test'=>'test']);
    }
}
```

My routing:
```
api:
    resource: 'api'
    prefix: /api
    type:     'api_platform'
```

Then I try to send request, and got 404 error:

<img width="1253" alt="2017-03-14 12 30 37" src="https://cloud.githubusercontent.com/assets/3224226/23894152/14c7def6-08b2-11e7-87b9-d8f2c597583d.png">

**Comment by soyuka** [comment]
Did you enable route annotations?
Did you clear the cache?
May we have an output subtract of `bin/console debug:router`?

**Comment by mitalcoi** [comment]
1)
<img width="406" alt="2017-03-14 19 49 13" src="https://cloud.githubusercontent.com/assets/3224226/23911978/7fe4bd5c-08ef-11e7-9bea-428e75b44192.png">
2)
Yes, every time
3)
<img width="875" alt="2017-03-14 19 48 31" src="https://cloud.githubusercontent.com/assets/3224226/23911985/832da9f6-08ef-11e7-8db9-5384c6f85311.png">

**Comment by soyuka** [comment]
The match is wrong apparently. I'm not sure your route is actually registered, can you execute:

```
bin/console router:debug | grep campaigns
```

**Comment by mitalcoi** [comment]
Unfortunately, I can't debug route this way (at symfony 3.2 ``` router:debug``` deprecated):
<img width="564" alt="2017-03-14 20 00 58" src="https://cloud.githubusercontent.com/assets/3224226/23912528/f8a89e88-08f0-11e7-88a6-7396b3b4182c.png">
But I steel can debug through ```router:match```:
<img width="862" alt="2017-03-14 20 03 14" src="https://cloud.githubusercontent.com/assets/3224226/23912612/47576b5e-08f1-11e7-9bc5-cf1b3a3c03c5.png">

My ApiResource config:
<img width="363" alt="2017-03-14 20 04 28" src="https://cloud.githubusercontent.com/assets/3224226/23912663/7258b4b6-08f1-11e7-9ab3-c4105f7cdcc6.png">
My action config:
<img width="474" alt="2017-03-14 20 04 54" src="https://cloud.githubusercontent.com/assets/3224226/23912681/82095f64-08f1-11e7-8a6b-47f5d09639b1.png">

**Comment by soyuka** [comment]
`debug:router` then sorry

**Comment by mitalcoi** [comment]
Maybe the problem is in regular expression that treats route after "/api/campaigns/" path as id (```| Path Regex   | #^/api/campaigns(?:\.(?P<_format>[^/]++))?$#s           |```)

**Comment by soyuka** [comment]
if it doesn't show up in `bin/console debug:router` there's a misconfiguration somewhere.

**Comment by mitalcoi** [comment]
I mean that this rule overrides my route, so it doesn't shown up. Also I have provided all related configuration - rest part is taken from standard edition

**Comment by soyuka** [comment]
So, based on the standard edition (master, this repository):

```diff
diff --git a/src/AppBundle/Action/FooCustom.php b/src/AppBundle/Action/FooCustom.php
new file mode 100644
index 0000000..75cc28e
--- /dev/null
+++ b/src/AppBundle/Action/FooCustom.php
@@ -0,0 +1,22 @@
+<?php
+namespace AppBundle\Action;
+
+use AppBundle\Entity\Foo;
+use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
+use Symfony\Component\Routing\Annotation\Route;
+
+class FooCustom
+{
+    /**
+     * @Route(
+     *   name="foo_custom",
+     *   path="/foos/custom",
+     *   defaults={"_api_resource_class"=Foo::class, "_api_item_operation_name"="custom"}
+     * )
+     * @Method("GET")
+     */
+    public function __invoke()
+    {
+
+    }
+}
diff --git a/src/AppBundle/Entity/Foo.php b/src/AppBundle/Entity/Foo.php
index 3d0e31d..605d1fc 100644
--- a/src/AppBundle/Entity/Foo.php
+++ b/src/AppBundle/Entity/Foo.php
@@ -9,7 +9,11 @@ use Symfony\Component\Validator\Constraints as Assert;
 /**
  * This is a dummy entity. Remove it!
  *
- * @ApiResource
+ * @ApiResource(collectionOperations={
+ *   "get"={"method"="GET"},
+ *   "post"={"method"="POST"},
+ *   "custom"={"route_name"="foo_custom"},
+ * })
  * @ORM\Entity
  */
 class Foo
```

You can apply this patch in the main repository by: 
1. clone the repository
2. `curl https://gist.githubusercontent.com/soyuka/36c01a56404bdfb323010e013b3d11f7/raw/950bd1dc6ab90d872efef07f8cef534a802f35cf/custom.patch | patch -p1`

`bin/console debug:router` output (extract):

```
  api_foos_get_collection    GET      ANY      ANY    /foos.{_format}
  api_foos_post_collection   POST     ANY      ANY    /foos.{_format}
  api_foos_get_item          GET      ANY      ANY    /foos/{id}.{_format}
  api_foos_put_item          PUT      ANY      ANY    /foos/{id}.{_format}
  api_foos_delete_item       DELETE   ANY      ANY    /foos/{id}.{_format}
  foo_custom                 GET      ANY      ANY    /foos/custom
```

**Comment by mitalcoi** [comment]
I've just applied you PATCH to fresh instance of api-platform, and routes are rendered OK (only difference is that I used ```_api_collection_operation_name``` instead of ```_api_item_operation_name``` from your PATCH) until I try to send smth to this route:

<img width="979" alt="2017-03-15 13 14 59" src="https://cloud.githubusercontent.com/assets/3224226/23943732/811f47c2-0981-11e7-9819-63ea0c92ab45.png">

**Comment by soyuka** [comment]
Yeah indeed, it's not matched because of the itemOperation regex match. I'm not sure if this is a bug or not (ping @teohhanhui).

**Comment by mychalvlcek** [comment]
@mitalcoi yes, route isnt matched correctly because of itemOperation regex.. 

quick solution: move "app" routing configuration before "api_platform" routing cfg so your custom routes will be matched before the generated (from api_platform) ones

```
app:
    resource: '@AppBundle/Action/'
    type: 'annotation'

api:
    resource: 'api'
    prefix: /api
    type: 'api_platform'
```

**Comment by abysKri** [comment]
Change your route, because regular expression think your route is for an api_platform_item_collection and not the route of your custom action:
your path route:  /list
try to chage to : /get/all/list
for example.

**Comment by soyuka** [comment]
closing as old, feel free to ping or open a new one
