### ISSUE TITLE
Route prefix duplicates in custom operations

### ISSUE THREAD

**Issue by mitalcoi** [api-platform/api-platform#254]
I already faced with routing problem in custom operations (#253) , but I found another more obvious problem.
I have global "/api" prefix, and it breaks custom operations routing.
routing.xml:
<img width="300" alt="2017-03-15 13 46 23" src="https://cloud.githubusercontent.com/assets/3224226/23944993/e0251720-0985-11e7-8c5f-c16b7cbefecf.png">
Api Resource and Action:
<img width="693" alt="2017-03-15 13 48 20" src="https://cloud.githubusercontent.com/assets/3224226/23945072/2283e66e-0986-11e7-8074-d46ccf458955.png">
<img width="470" alt="2017-03-15 13 48 30" src="https://cloud.githubusercontent.com/assets/3224226/23945073/22b45a6a-0986-11e7-84b5-94470ae3f07c.png">

Then if I call ```curl -X GET "http://127.0.0.1:8000/api/foos-custom"```, server return 404
OK, I've tried to prefix route different ways:
<img width="302" alt="2017-03-15 15 24 31" src="https://cloud.githubusercontent.com/assets/3224226/23948315/851aba66-0993-11e7-82ec-e6ffe864162d.png">
And (or)
<img width="705" alt="2017-03-15 15 24 57" src="https://cloud.githubusercontent.com/assets/3224226/23948323/931b6570-0993-11e7-975d-6800013a1b49.png">

But I didn't get a working endpoint with the correct swagger docs

**Comment by ArnaudBan** [comment]
I have the exact same problem. Did you find a solution ?

**Comment by mitalcoi** [comment]
problem still exists :(
@soyuka do you have any idea about it?

**Comment by soyuka** [comment]
I don't use swagger and I do add `/api` to my custom operation's path for it to be correct.

**Comment by ArnaudBan** [comment]
Yes the problem is only with Swagger. 
If you prefix your route with `/api` it works. That's what a did for the moment.

**Comment by Simperfit** [comment]
Could you please implement this in a api-platform/api-platform fork ?

**Comment by MarsArt** [comment]
![_001](https://cloud.githubusercontent.com/assets/9011844/25190556/3d25a398-2535-11e7-89a3-bf54eb6d13d8.png)

on custom operation identifying global routing prefix dublicates in route.  

https://github.com/MarsArt/api-platform - link on project where this error occures

**Comment by eps90** [comment]
Any news on that? Same problem here, makes SwaggerUI completely unusable since most of my routes are mapped custom operations.

**Comment by meyerbaptiste** [comment]
I'm on it.

**Comment by meyerbaptiste** [comment]
Can you please test this PR? https://github.com/api-platform/core/pull/1192

**Comment by meyerbaptiste** [comment]
Can be closed @Simperfit.
