### ISSUE TITLE
Store array in database

### ISSUE THREAD

**Issue by alborq** [api-platform/api-platform#255]
Hi,

i try to define this ressource:  
```json
{
	"user": "/users/1",
	"name": "Test",
	"definition": {
		"enable": {
			"type": "Boolean",
			"nullable": true,
			"default": true
		},
		"locked": {
			"type": "Boolean",
			"default": false
		},
		"username": {
			"type": "Text",
			"length": 50,
			"unique": true
		}
	}
}
```
But, I want store Definiton has json/array in DB
If i try some of : 

```php 
     * @ORM\Column(name="definition", type="array")
     * @ORM\Column(name="definition", type="json_array")
```

api platform espected array of sting : 
```json
{
  "id": 0,
  "user": "string",
  "name": "string",
  "definition": [
    "string"
  ]
}
```
Why, where it come from ?
How did it, change it ?

**Comment by cve** [comment]
@alborq I suggest to use 

````php
* @ORM\Column(name="definition", type="json")
````

http://docs.doctrine-project.org/projects/doctrine-dbal/en/latest/reference/types.html#json

**Comment by alborq** [comment]
@cve JSON type not available on MySql

**Comment by amenophis** [comment]
hi @alborq ,
You could use https://github.com/dunglas/doctrine-json-odm made by @dunglas :)

**Comment by alborq** [comment]
hi @amenophis 
like response to @cve, Json ODM is not available actually on Mysql 

> Currently only PostgreSQL is supported. MySQL (>= 5.7.8) will be supported when the Pull Request doctrine/dbal#2266 will be merged.

**Comment by teohhanhui** [comment]
Doctrine `json` type is only available in `master` (v2.6; unreleased). But it's actually the same as `json_array`. There should be nothing stopping you from using the `json_array` type. *If* (I'm not sure about this) API Platform expects a flat array of strings, that's a wrong expectation on our end.

**Comment by alborq** [comment]
Ping @dunglas. We speak together on SymfonyLive about that. This may as a same bug on symfony components (duplicate code). Why array of string is excpect and not just an array. Allan

**Comment by dunglas** [comment]
It's actually intended for `simple_array` (it's an array of string: a CSV) but it should work for `json_array` according to https://github.com/symfony/symfony/blob/master/src/Symfony/Bridge/Doctrine/PropertyInfo/DoctrineExtractor.php#L126-L127

Can you post the code of your entities (or publish a sample repository)?

**Comment by alborq** [comment]
I have try to reproduce my bug, it seen to be a mistake of myself. All work with json_array,

documentation just say 'string[]' change '@var' to "@var bool[]" let the same, but, this not concerne my initial problem. 

 this issue is solved. 
Thanks.

**Comment by codedmonkey** [comment]
@teohhanhui Yes this is unfortunately the case. When using the `json` type the model shows as `[string]` while it should be a key/value storage. Correct?

**Comment by teohhanhui** [comment]
I think we should support a flat array of any homogeneous scalar type.
