### ISSUE TITLE
Use other identifier than the IRI for relation

### ISSUE THREAD

**Issue by matthieu-delisle** [api-platform/api-platform#2553]
Is it possible to use another identifier for a relation in a POST?

Let's say I have a country Entity with : 

- Id = 1, Code = CA, Desc = Canada
- Id = 2, Code = US, Desc = United States

Then I want to POST a sale for a country.

### Actual
```
{
  "saleDate": "2023-10-19T04:00:00.000Z",
  "country": "/api/country/1"
}
```

### Wanted
```
{
  "saleDate": "2023-10-19T04:00:00.000Z",
  "country": "CA"
}
```

For now, this would give me an Invalid IRI.

Thanks

**Comment by soyuka** [comment]
Use a custom normalizer note that this is quite wrong in json-ld, you could probably use the country slug as identifier though

**Comment by matthieu-delisle** [comment]
@soyuka Thank you for the suggestion. We can close this, I will try it and think about your quote `this is quite wrong in json-ld` if it is something I finally want to do.
