### ISSUE TITLE
State Provider is not always properly called 

### ISSUE THREAD

**Issue by Ideneal** [api-platform/api-platform#2555]
**API Platform version(s) affected**: 3.2.1

**Description**  
The state provider is not called when there are no URI variables and the request does not have a safe method.

**How to reproduce**  
Given the user entity:
```php
#[ApiResource(
  operations: [
    new Patch(
      uriTemplate: '/users/me',
      provider: CurrentUserProvider::class,
    ),
  ]
)]
#[ORM\Entity(repositoryClass: UserRepository::class)]
class User //...
```

and given the related state provider:
```php
final readonly class CurrentUserProvider implements ProviderInterface
{
    public function __construct(private TokenStorageInterface $tokenStorage) {}

    public function provide(Operation $operation, array $uriVariables = [], array $context = []): null|User|UserInterface
    {
        return $this->tokenStorage->getToken()?->getUser();
    }
}
```

The CurrentUserProvider is never called when I do a PATCH request on the `/api/users/me` endpoint.

**Possible Solution**  
Remove the following check in the line [ReadListener.php#L72](https://github.com/api-platform/core/blob/main/src/Symfony/EventListener/ReadListener.php#L72) or update the documentation.

```php
(!$operation->getUriVariables() && !$request->isMethodSafe())
```

**Comment by soyuka** [comment]
Hi, we fixed this with https://github.com/api-platform/core/pull/5657 just use the `event_listeners_backward_compatibility_layer: false` configuration
