### ISSUE TITLE
POST error without Item GET method

### ISSUE THREAD

**Issue by alborq** [api-platform/api-platform#256]
Hi, 
Little feedback,

If GET item method is not set, POST method throw an error. 
Maybe return nothing in this case ?

**Comment by amenophis** [comment]
hi @alborq,
The error is api-platform use the GET item route to generate IRI, the @id field in JSON

**Comment by Simperfit** [comment]
Like @amenophis said we need the `GET` to generate an IRI, it's [mandatory](https://api-platform.com/docs/core/operations#operations).

**Comment by dunglas** [comment]
However you can use event listeners to only return a "No content" response for this URI.
