### ISSUE TITLE
Post without body fails

### ISSUE THREAD

**Issue by lukey78** [api-platform/api-platform#2574]
**API Platform version(s) affected**:  3.2

**Description**  

I want to use a POST route without having to send json data. Usecase: Invalidating a JWT token that is delivered inside the Authorization header.

```
#[Post(processor: AppLogoutHandler::class, uriTemplate: '/app-logout')]
class AppLogout
{
}
```

My AppLogoutHandler just has a process($data, ...) method as needed.

Testing it:

```
$client->request(
            'POST',
            '/api/app-logout',
            [],
            [],
            ['CONTENT_TYPE' => 'application/json']
        );
```

This produces a "Syntax error" I'm not aware where it may come from. 
The "process" method is never called.

When I change this to include some arbitrary test data, the request works as expected:

```
$client->request(
            'POST',
            '/api/app-logout',
            [],
            [],
            ['CONTENT_TYPE' => 'application/json'],
            json_encode(['test' => 'testcontent'])
        );
```

I tried different combinations of the "read", "write", "input" and "output" properties on the Post annotation, but didn't find a way to make it work.

When I use "input: false" it actually producec the error: Could not resolve argument $data of "api_platform.action.placeholder::__invoke()", maybe you forgot to register the controller as a service or missed tagging it with the "controller.service_arguments"

How should this usecase (using a DTO without properties and without output) actually be handled?

**Comment by soyuka** [comment]
decorate or replace the json encoder with yours that allows empty bodies.

**Comment by lukey78** [comment]
Isn't a POST without a body a valid usecase? It seems odd not to handle it with a simple condition.

**Comment by soyuka** [comment]
doesn't `input: false` work?

**Comment by lukey78** [comment]
As stated in my original issue, with `input: false` the problem is this:

Could not resolve argument $data of "api_platform.action.placeholder::__invoke()", maybe you forgot to register the controller as a service or missed tagging it with the "controller.service_arguments"?

Maybe the $data attribute on the processor interface has to be nullable to support empty inputs?

**Comment by soyuka** [comment]
you're not giving all the informations... do you need event listeners? Is your configuration up to date for 3.2? `composer update:receipes` may help. What I read should work with `event_listeners_backward_compatibility_layer: false`

**Comment by lukey78** [comment]
Ok, I tried. Can confirm that `input: false` works with `event_listeners_backward_compatibility_layer: false`. 

Ist there any documentation page for the extra properties on resources like `read`, `write`, `input`, `output`? If that page exists, maybe that place would be good for documenting that some properties only work without the compatibility layer.

**Comment by soyuka** [comment]
they will work with event listeners but to avoid breaking lots of code we needed a few minor versions, https://github.com/api-platform/core/pull/6102 fixes this without the flag

**Comment by langziyang** [comment]
same error
![image](https://github.com/api-platform/api-platform/assets/2345387/f56b3d90-5b74-418a-87de-cf2bcf08a93d)

api-platform/core v3.3.3
event_listeners_backward_compatibility_layer: false

![image](https://github.com/api-platform/api-platform/assets/2345387/f1a41cea-06b6-4811-8431-3322875a60b6)
