### ISSUE TITLE
KernelEvents::VIEW is no longer called

### ISSUE THREAD

**Issue by gassan** [api-platform/api-platform#2578]
**API Platform version(s) affected**: 3.2.*

**Description**  
Controller returns since 3.2 a Response, so KernelEvents::VIEW is no called.

Maybe [The Event System page](https://api-platform.com/docs/main/core/events/) should be adapted

**Comment by arvydasjankauskas** [comment]
This is why I'm struggling for a few hours trying to understand, why subscribers stopped working.

**Comment by MalekWahada** [comment]
Hey @arvydasjankauskas, I encountered a comparable situation using `Symfony@6.3` + `API-Platform@3.2` until I came across information in the Symfony documentation stating that "Lifecycle subscribers are deprecated starting from Symfony 6.3."

Nevertheless, they do recommend exploring alternative solutions:

https://symfony.com/doc/current/doctrine/events.html#doctrine-lifecycle-subscribers

**Comment by soyuka** [comment]
hi, use `event_listeners_backward_compatibility_layer: true`
