### ISSUE TITLE
Bug with normalization/denormalization groups and inheritance (only when cache is built)

### ISSUE THREAD

**Issue by Stnaire** [api-platform/api-platform#263]
Hi,

I experience a strange bug only occurring **after the cache has been built**. If I do a `rm -rf var/cache/*` I got one working run. Then never again.

I have the following entities (simplified as much as I can to still show the problem):

A base `User` class
```php
/**
 * @ORM\Entity
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ApiResource(
 *  itemOperations={
 *     "update"={
 *          "method"="PUT",
 *          "path"="/user/update/{id}",
*           "normalization_context"={
 *              "groups"={"always-r", "public-r1", "public-r2"}
 *          },
 *          "denormalization_context"={
 *              "groups"={"always-w", "public-w1", "public-w2"}
 *          }
 *      }
 *  }
 * @UniqueEntity(fields="username", message = "entity.user.username.already-used")
 *
 * @ORM\DiscriminatorColumn(name="discr", type="string")
 * @ORM\DiscriminatorMap({"a" = "UserTypeA", "b" = "UserTypeB", "c" = "UserTypeC"})
 */
abstract class User extends AbstractEntity implements UserInterface
{
    /**
     * Users types.
     *
     * @var string
     */
    const TYPE_A = 'a';
    const TYPE_B = 'b';
    const TYPE_C = 'c';

    /**
     * @ORM\Column(type="file", nullable=true)
     *
     * @Groups({"public-r1", "user-public-r1", "public-w1", "user-public-w1"})
     */
    protected $avatar;

    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Assert\NotBlank(message="entity.user.email.blank")
     * @Assert\Email(message="entity.user.email.invalid")
     *
     * @Groups({"public-r1", "user-public-r1", "public-w1", "user-public-w1"})
     */
    protected $email;

    [etc..]
}
```

A subclass for `companies`:

```php
abstract class UserTypeCompany extends User
{
    /**
     * @ORM\Column(type="string", length=255)
     *
     * @Groups({"public-r1", "user-public-r1", "public-w1", "user-public-w1"})
     */
    protected $companyName;

    [etc...]
}
```

And then another subclass for each type of company:
```php
/**
 * @ORM\Entity
 * @ApiResource(
 *     collectionOperations={},
 *     itemOperations={
 *         "get"={"method"="GET"}
 *     }
 * )
 */
class UserTypeA extends UserTypeCompany
{
    public function __construct()
    {
        parent::__construct();
        $this->type = self::TYPE_A;
        $this->addRoles('ROLE_A');
    }
}
```

**_Optionally_**, if you're interested, here's the logic of my groups:

* `always-r`: any action will define it in its normalization groups (always readable)
* `always-w`: same for denormalization groups (always writable)
* `public-r[n]`: publicly readable level N. The more you increase the level, the more details you get.
* `public-w[n]`: publicly writable level N. The more you increase the level, the more details you can write.
* `public` can be replaced by `admin` or anything. Just a way to separate by role.
* `[entityName]-public-r[n]`: same as `public-r[n]` but specific to this entity. All entities will define the `public-r[n]` groups and their specific groups.

# The bug

The bug occurs when I try to update a user model. I can't update fields on the subclass once the cache is built.

If I do the following request : 

```
curl -X PUT --header 'Content-Type: application/ld+json' --header 'Accept: application/ld+json' -d '{"companyName": "New name"}' 'http://api.dev/user/update/PCBY'
```

It works once after the cache is cleared, then never again.
By inspecting into the code I've found the following problem (screenshots):

[http://imgur.com/a/Z0wy1](http://imgur.com/a/Z0wy1)

The `$allowedAttributes` variable contains very strange values after the cache is built (nothing else changed between the two captures).

It contains 7 elements when it should contain 16 elements. But more than that, **it contains invalid elements**.

In the second capture, you can see `$allowedAttributes` contains a `firstName` and `lastName` property. **_These properties are not defined in the classes described above_** but in another child class of the `User` base class : 

```php
/**
 * @ORM\Entity
 * @ApiResource(
 *     collectionOperations={},
 *     itemOperations={
 *         "get"={"method"="GET"}
 *     }
 * )
 */
class UserTypeB extends User
{
    /**
     * @ORM\Column(type="string", length=50)
     *
     * @Assert\NotBlank(message="entity.user.firstName.blank")
     * @Assert\Length(min=2, max=100, minMessage="entity.user.firstName.short", maxMessage="entity.user.firstName.long")
     *
     * @Groups({"public-r1", "user-public-r1", "public-w1", "user-public-w1"})
     */
    protected $firstName;

    /**
     * @ORM\Column(type="string", length=50)
     *
     * @Assert\NotBlank(message="entity.user.lastName.blank")
     * @Assert\Length(min=2, max=100, minMessage="entity.user.lastName.short", maxMessage="entity.user.lastName.long")
     *
     * @Groups({"public-r1", "user-public-r1", "public-w1", "user-public-w1"})
     */
    protected $lastName;
}
```

It's very strange as the object given to the deserializer is an instance of `UserTypeA`, I've seen it when debugging the code step by step.

I've experienced the same thing with the normalization. I have no example to show here but when I try to get a single user entity, all fields the groups ask for are not present and fields of `UserTypeB` are extracted instead.

When there is no inheritance, it works fine.

Thanks for your help!

**Comment by nik-lampe** [comment]
I am experiencing an similar issue, I have documented it in #266

**Comment by soyuka** [comment]
https://github.com/api-platform/core/issues/1025

**Comment by Simperfit** [comment]
Does it fix this issue @soyuka ?

**Comment by soyuka** [comment]
Closing, feel free to ping if it's not working.
