### ISSUE TITLE
could not translate host name

### ISSUE THREAD

**Issue by Zer0NimO-web** [api-platform/api-platform#2643]
Hello,

I'm encountering an issue while using the official API platform repository. I'm uncertain whether it's a bug, which is why I'm reaching out through this channel to explain my problem.

After cloning the repository onto my computer, I executed the following commands:

```
docker compose build --no-cache
docker compose up --wait
```
as per the documentation's suggestion.

Everything seems to be working fine, and I have three containers up and running: app-php, ap-pwa, and postgre.
However, the problem arises when attempting to perform a migration outside of the container (at the root of my api folder). Running the command:

`symfony console make:migration`

results in the following error:

`An exception occurred in the driver: SQLSTATE[08006] [7] could not translate host name "database" to address: nodename nor servname provided, or not known`

Do you have any insights on how to resolve this? Is it necessary to execute Symfony commands within the container?

Just in case here is the DATABASE_URL : 
`DATABASE_URL="postgresql://app:!ChangeMe!@database:5432/app?serverVersion=15&charset=utf8"`

**Comment by 1MarONE** [comment]
i have the same problem
