### ISSUE TITLE
[CRITICAL] Admin Page Not Working on Fresh Install

### ISSUE THREAD

**Issue by TheDevick** [api-platform/api-platform#2646]
### API Platform version(s) affected: 3.2.15 (Latest)

# Description  

So, the admin page isn't working. While this problem may be from the [Admin](https://github.com/api-platform/admin) package, I think there something related to the docker files. I was debugging a little bit and it appears that symfony is handling a next js request, but i'm not sure. Check the first image - isn't that route supposed to be handled by Next.js?
![image](https://github.com/api-platform/api-platform/assets/71853418/f9b6f434-0dd9-4390-ac3a-034e1189d69a)
---
![image](https://github.com/api-platform/api-platform/assets/71853418/2ad192ab-0e4f-4cdc-b9b4-b33e6dfe5423)
![image](https://github.com/api-platform/api-platform/assets/71853418/4738e436-e0dd-42af-9b83-1a833de81267)
![image](https://github.com/api-platform/api-platform/assets/71853418/d6e59f9a-1a07-4680-9d10-541631e532c1)
![image](https://github.com/api-platform/api-platform/assets/71853418/f83d0150-d734-46bf-8da7-f87d023ca993)

**How to reproduce**  

Clone the Api Platform repo, `cd` to the folder, run `docker compose build` and `docker compose up`, just like in documentation. After that, simply open the Admin page and the errors appears.

```bash
git clone git@github.com:api-platform/api-platform.git
cd api-platform
docker compose build --no-cache
docker compose up --wait
open https://localhost/admin
```

**Comment by TheDevick** [comment]
Update: The newest version of the package (v3.2.15) still have the same error.

**Comment by beejaz** [comment]
Im not a NextJS user so Im not sure how it works, but it seems v14.1 added/changed from using `/_nextjs` to `/__nextjs` so if we add `/__next*` here https://github.com/api-platform/api-platform/blob/main/api/frankenphp/Caddyfile#L79 it will prevent the error request from reaching Symfony but it still seems to produce some errors related to NextJS after that (image 2,3,4,5).

**Comment by vinceAmstoutz** [comment]
Same issue after a fresh install
![image](https://github.com/api-platform/api-platform/assets/46444652/c4fb483d-72f8-442c-9b3b-e952944d2bc1)

**Comment by zairigimad** [comment]
we had some issues in the few month related, I did install a fresh pwa with app directory and it works just fine, did you try this ?

**Comment by vinceAmstoutz** [comment]
> we had some issues in the few month related, I did install a fresh pwa with app directory and it works just fine, did you try this ?

Do you have a tutorial or explanations for this please?

**Comment by kaceman** [comment]
I have the same issue here. Has anyone found a solution?

**Comment by zairigimad** [comment]
> > we had some issues in the few month related, I did install a fresh pwa with app directory and it works just fine, did you try this ?
> 
> Do you have a tutorial or explanations for this please?

you need to remove the pwa folder, then install new nextjs with configuration you want, we did choose app directory instead of pages directory provided by APIP. then you need to do a small change in your caddy file to 

add the '_rcs': '*'

`	@pwa expression `(
			header({'Accept': '*text/html*'})
			&& !path(
				'/docs*', '/audit*', '/graphql*', '/bundles*', '/contexts*', '/_profiler*', '/_wdt*',
				'*.json*', '*.html', '*.csv', '*.yml', '*.yaml', '*.xml'
			)
		)
		|| path('/favicon.ico', '/manifest.json', '/robots.txt', '/_next*', '/sitemap*')
		|| query({'_rsc': '*'})
		`
` 
the next js part should work , then if you need the code generated by API PLatform  for the admin pages, you can copy it from the distribution or from the doc.

**Comment by dunglas** [comment]
I cannot reproduce the issue on a fresh install of the distribution, but I also get the `[TypeError: palette.theme undefined](https://stackoverflow.com/questions/70120053/material-ui-typeerror-palette-theme-undefined)` when upgrading the JS deps.

I opened https://github.com/api-platform/api-platform/pull/2656 for a partial config fix. I'm still investigating the MUI error.
