### ISSUE TITLE
Docker schema command doesn't work from 5 min tutorial

### ISSUE THREAD

**Issue by mmuruev** [api-platform/api-platform#265]
`/api-platform$ docker-compose exec web bin/console doctrine:schema:create
ERROR: No such service: web
`
Seems like manual is bit outdated.

**Comment by Newan** [comment]
docker-compose exec php bin/console doctrine:schema:create

**Comment by dunglas** [comment]
This is because of a GitHub bug: the link to download the latest release is broken. It downloads `master` instead of the latest tag. I've just updated the website to use the new link.

You probably have the master version instead of a 2.0.x. Sorry about that, you should downgrade to the laster v2.

**Comment by Newan** [comment]
Website linked to core?
https://github.com/api-platform/core/releases/tag/v2.0.6

I think you mean?:
https://github.com/api-platform/api-platform/releases/tag/v2.0.6

But if i try to downlaod and docker-compose up -d:

```
Removing intermediate container 833b77853e7b
Successfully built e9fa41984cb7
WARNING: Image for service web was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating apiplattform_database_1
Creating apiplattform_web_1
```
I become some errors:

```
docker-compose exec web bin/console doctrine:schema:create
Warning: require(/app/app/../vendor/autoload.php): failed to open stream: No such file or directory in /app/app/autoload.php on line 7
Fatal error: require(): Failed opening required '/app/app/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /app/app/autoload.php on line 7
```

**Comment by dunglas** [comment]
Oops I used the bad link...
Can you start from a fresh download? The error is weird.

**Comment by Newan** [comment]
1. Yes fresh download 
2. `docker-compose up -d`
But in log I see that the composer failed:
```
web_1       |   - Installing symfony/symfony (v3.2.6): Loading from cache    Failed to download symfony/symfony from dist: Could not delete /app/vendor/symfony/symfony/src/Symfony/Component/Translation/Tests/fixtures/resources.ts:
web_1       |     Now trying to download from source
web_1       |   - Installing symfony/symfony (v3.2.6):
web_1       |
web_1       |   [RuntimeException]
web_1       |   Could not delete /app/vendor/symfony/symfony/src/Symfony/Component/Translation/Tests/fixtures/resources.ts:
web_1       |
web_1       |
web_1       | install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoload
er] [--ignore-platform-reqs] [--] [<packages>]...
web_1       |
apiplatform206_web_1 exited with code 1
```

**Comment by dunglas** [comment]
I've just tried with the latest version and I'm not able to reproduce. Do you have a slow network? It looks like a network issue.

What OS and Docker version do you use?

**Comment by Newan** [comment]
Docker Version 17.03.0-ce, build 60ccb22
Windwos 10  Pro

Delete all Images in Docker recreate all, same issues

**Comment by Newan** [comment]
on an fresh installed windows with nothing installed:

1. install docker
2. enable hyper-V and shared c:
3. download api-Plattform
4. unzip
5. change to root from api-Plattform
6. run docker-composer up -d
7. run docker-compose logs web

```
web_1       | /usr/local/bin/docker-php-entrypoint: 9: exec: 
/app/docker/start.sh: not found
```

8. run docker-compose PS

```
PS C:\Users\EDV\Downloads\api-platform-2.0.6> docker-compose ps
           Name                         Command                State      
Ports
--------------------------------------------------------------------------------
apiplatform206_database_1   docker-entrypoint.sh mysqld      Up         
3306/tcp
apiplatform206_web_1        docker-php-entrypoint /app ...   Exit 127
```

The start.sh is in the container.  an Windows issues, but no idea to fix it

**Comment by dunglas** [comment]
I've no Windows box with me... I'll not be able to help. @jockos, @api-platform/core-team any idea?

**Comment by jockos** [comment]
Can you check the line-ending of your .sh files ? They need to be set to LF.

**Comment by Newan** [comment]
PHPStorm says LF

**Comment by Newan** [comment]
Update, after x install all new an try try try then:

```
web_1       |  [OK] Cache for the "dev" environment (debug=true) was successfully cleared.
web_1       |
web_1       | > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
web_1       |
web_1       |  Trying to install assets as relative symbolic links.
web_1       |
web_1       |  --- ------------------- ------------------
web_1       |       Bundle              Method / Error
web_1       |  --- ------------------- ------------------
web_1       |   Ô£ö   ApiPlatformBundle   relative symlink
web_1       |  --- ------------------- ------------------
web_1       |
web_1       |  [OK] All assets were successfully installed.
web_1       |
web_1       | > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
web_1       | > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
web_1       | + rm -f /var/run/apache2/apache2.pid
web_1       | + exec docker/apache/start_safe_perms -DFOREGROUND
web_1       | AH00526: Syntax error on line 1 of /etc/apache2/apache2.conf:
web_1       | Error:\tApache has not been designed to serve pages while\n\trunning as root.  There are known race conditions that\n\twill allow any local user to read any file on the system.\n\tIf you still desire to serve pages as root then\n\tadd -DBIG_SECURITY_HOLE to
 the CFLAGS env variable\n\tand then rebuild the server.\n\tIt is strongly suggested that you instead modify the User\n\tdirective in your httpd.conf file to list a non-root\n\tuser.\n
web_1       | Action '-DFOREGROUND' failed.
web_1       | The Apache error log may have more information.
```

**Comment by Newan** [comment]
I used the latest Release.  dunglas wrote it for downgrade on this issues.  I will wait for the next Release

**Comment by soyuka** [comment]
Can you try [master](https://github.com/api-platform/api-platform/archive/master.zip) ?

**Comment by Newan** [comment]
Works, very good!


But first Post:

>   Seems like manual is bit outdated.

**Comment by dunglas** [comment]
The new setup in master is not released yet, it's why the doc hasn't been updated. But glad to here that the new one works on Windows too :)

**Comment by dunglas** [comment]
Btw, you can use the new setup while just downgrading to stable `api-platform/core`.

**Comment by Simperfit** [comment]
Hey @Newan,

Thanks for using Api-Platform,

We will update the doc if it's still outdated, feel free to open a PR if you need to :).

**Comment by garbus** [comment]
Oh in fact in the manual "app" is outdated, changing to web solved the problem.
Then it appeared "the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'", so writing _winpty docker-compose exec app bin/console doctrine:schema:create_ made the job.
