### ISSUE TITLE
[ask] resource class saved as doctrine proxy class not the original one

### ISSUE THREAD

**Issue by pitraadytia** [api-platform/api-platform#267]
hey,
i'm using https://github.com/dunglas/doctrine-json-odm to save jsonb document in postgre sql field table.

Given class with json_document type : 
```
     /**
     *
     * @var MedicalNote[]
     *
     * @ORM\Column(type="json_document", options={"jsonb": true}, nullable=true)
     * 
     * @Groups({"dept_detail"})
     *
     * @Gedmo\Versioned()
     *
     * @Assert\Valid()
     *
     */
    protected $medicalNoteParameters;
```
MedicalNote defined as resource class.  When insert new record in table, MedicalNote serialized as proxy class (#type:Proxies\\__CG__\\AppBundle\Entity\MedicalNote) and caused error entity not found. 

Any chance i can save as the real class (#type:AppBundle\Entity\MedicalNote) ?

**Comment by dunglas** [comment]
Can you try if https://github.com/dunglas/doctrine-json-odm/pull/16 fix your issue please?

Anyway, closing this issue because it's not related at all with API Platform.
