### ISSUE TITLE
Cannot Start Environment with Docker-Compose on MacBook M1 Sonoma

### ISSUE THREAD

**Issue by LucianoVandi** [api-platform/api-platform#2670]
**API Platform version(s) affected**: 3.2.x

**Description**  
Cloning a new project on a Macbook M1 Sonoma (14.3), it is not possible to start the environment with docker-compose.

```sh
php-1       | Waiting for database to be ready...
php-1       | The database is now ready and reachable
php-1       |
php-1       |
php-1       |  [OK] Already at the latest version ("DoctrineMigrations\Version20210930074739")
php-1       |
php-1       |
php-1 exited with code 139
```
I have a project that was started a couple of months ago which has suddenly stopped working with the same error after a rebuild. 

**How to reproduce**  
Clone the project and just update the compose.yml file to add the platform emulation, required by M1 architecture.
```yaml
services:
  php:
    image: ${IMAGES_PREFIX:-}app-php
    platform: linux/x86_64
    ...

```
Everything else remains the same as the newly cloned project.

**Possible Solution**  

**Additional Context**

**Comment by LucianoVandi** [comment]
I've realized that this problem starts to manifest with the tag `1.1.1-php8.2-alpine`. If I downgrade to the tag `1.1.0-php8.2-alpine`, it works correctly.

In the known issues of FrankenPHP, there is this note: [XDebug may crash, or hang on PHP 8.3. A workaround is to downgrade to PHP 8.2](https://github.com/dunglas/frankenphp/issues/563). However, I am actually trying with a PHP 8.2 image, and the problem persists, even when disabling the installation of Xdebug.

```dockerfile
FROM dunglas/frankenphp:1.1.1-php8.2-alpine AS frankenphp_upstream
...
# Dev FrankenPHP image
FROM frankenphp_base AS frankenphp_dev

ENV APP_ENV=dev XDEBUG_MODE=off
VOLUME /app/var/

RUN mv "$PHP_INI_DIR/php.ini-development" "$PHP_INI_DIR/php.ini"

#RUN set -eux; \
#	install-php-extensions \
#    xdebug \
#    ;

COPY --link frankenphp/conf.d/app.dev.ini $PHP_INI_DIR/conf.d/

CMD [ "frankenphp", "run", "--config", "/etc/caddy/Caddyfile", "--watch" ]
```

**Comment by dunglas** [comment]
Closed by https://github.com/xdebug/xdebug/pull/958.
