### ISSUE TITLE
No route found for "GET /books.json"

### ISSUE THREAD

**Issue by fizdalf** [api-platform/api-platform#268]
I'm following the 5 min tutorial at [https://api-platform.com/docs/distribution/#creating-your-first-api-with-api-platform-in-5-minutes]( https://api-platform.com/docs/distribution/#creating-your-first-api-with-api-platform-in-5-minutes)  

I'm running a windows 10 pro, and I tried to follow the tutorial with Docker..but I was getting an error regarding Apache complaining about running as root..so I tried the Composer version..

Generated the Book and Review classes, and created the schema etc..all of that works..and now at localhost:8000/ I have the list of resources including /books and /reviews, but, the routes don't exist..I cannot post nor get from any of those two resources.

What am I doing wrong? 

the /foos routes work correctly ..but it seems API-Platform is not generating new routes for the resources

**Comment by dunglas** [comment]
Can you try to clear the cache ?

**Comment by fizdalf** [comment]
A few seconds before you suggested it ..that's what I did ..and viola! ..maybe that should be added to the guide cause there's no mention of it.

Thanks for your assistance anyways!!
