### ISSUE TITLE
Impossible to use vite/vue3 with supplied Caddyfile

### ISSUE THREAD

**Issue by rishta** [api-platform/api-platform#2697]
**API Platform version(s) affected**: 3.x/HEAD
The problem seems specific to Caddy configuration. 

**Description**  
`.ts`, `.css`, `.vue`, practically any static file goes to PHP instead of @pwa reverse proxy
The only container that is modified is the PWA. Changed to vue3/vite. The screenshot shows the error.

**How to reproduce** 
Use vue3/vite app instead of next.

**Possible Solution**  
Go back to nginx

**Additional Context**  
![Screenshot at 2024-04-28 23-25-23](https://github.com/api-platform/api-platform/assets/296382/fb9e5cb3-8445-4e4d-adc9-96cd4cfce574)

**Additional comments**
This here, making funny names, like "frankenphp", inserting funny servers into the backend framework code, forcing those servers on people is counterproductive. It stops people from being able to smoothly upgrade the codebase OR use the frontend framework of their choice. Consequently people start to choose trash like Laravel, which doesn't carry those risks.

I personally am tired of fighting those "novelties" to make them work. Test them better, or refrain from making unnecessary, unwelcome changes to deployment. You are damaging the developer experience.

**Comment by dunglas** [comment]
As stated in the documentation, the default distribution only supports Next.js. If you want to use Vue, you have to adapt the web server configuration to handle Vue's specificities.

You would have also have to do that with NGINX btw.

A documentation entry explaining how to use Vue is welcome, but we'll not add default support for Vue to not bloat the default distribution.

**Comment by rishta** [comment]
> This has nothing to do with Caddy/FrankenPHP (actually it will be easier to adapt for Vue with Caddy) and you would also have to update the NGINX config.

LOL easier than this?
```
    location / {
        proxy_pass http://pwa:3000;
    }

    location ~ ^/index\.php(/|$) {
        # config  ....
    }
```
I don't think so. Please stop lying on top of making breaking changes.

**Comment by dunglas** [comment]
You don't know what you're talking about, and you haven't read the article I linked to. You can follow this strategy with Caddy too, and you'll have problems (like with NGINX).

If you're not happy with our project, don't use it. I'm not going to waste my time with people who are as aggressive and unconstructive as you are.
