### ISSUE TITLE
"Invalid identifier value or configuration."

### ISSUE THREAD

**Issue by facundososalopez** [api-platform/api-platform#2702]
**API Platform version(s) affected**: 3.3.2

**Description**  
I have this endpoint:

new Get(
    uriTemplate: '/fex/documentacions/{hash}/archivo',
    controller: FileGet::class,
    read: false
)

and I get this error when I run it: "Invalid identifier value or configuration."

Hash is not the identifier but the read : false setting should prevent the error, or at least before version 3.3 it did not have problems.

The previous endpoint was just an example, I have also received the error on other endpoints with similar characteristics.

**Comment by soyuka** [comment]
https://github.com/api-platform/core/issues/6355 will be fixed soon
