### ISSUE TITLE
How active oauth authenfification?

### ISSUE THREAD

**Issue by angelzeke** [api-platform/api-platform#271]
Hi everybody
It seems that the authentication oauth is natively implement on the new version 2.X.
I would like to have some precision for activate it.

Thank a lot for your help

**Comment by soyuka** [comment]
Hmm, nope. @iCodr8 has implemented oauth for swagger only see 
https://github.com/api-platform/core/pull/982

Ref: https://github.com/api-platform/core/pull/982#issuecomment-288992744

**Comment by angelzeke** [comment]
thank you for your reply.
Is it planned to set up on client_credentials? 
Participate in the development of this evolution?

**Comment by dunglas** [comment]
OAuth support is available tru FosOAuthServer and is being documented here: https://github.com/api-platform/docs/pull/182

Any help on this in very welcome!

**Comment by iCodr8** [comment]
The "client_credentials" grant type is currently not supported by swagger ui.

**Comment by angelzeke** [comment]
I use this tutorial to implement Oauth https://causeyourestuck.io/2016/07/19/oauth2-explained-part-2-setting-up-oauth2-with-symfony2-using-fosoauthserverbundle/
Now i can generate token_access 

In security.yml i change 
`        api:
            pattern:    ^/api/[A-Za-z0-9]
            fos_oauth:  true
            stateless:  true`

Like this i can access to swagger UI and method like 'http://192.168.56.2/app_dev.php/api/books' need Oauth.

- How i can add a field to give my access_token like Raw Headers
- change class for accept this access_token

**Comment by novakma2** [comment]
@angelzeke Hey, can you please write short and brief tutorial about implementation of OAuth2? Cant get this running. Thanks
