### ISSUE TITLE
Strange Api-platform activity. It looks like ApiProperty Attribute doesn't work with json format. Looks like a security issue.

### ISSUE THREAD

**Issue by mantaszv** [api-platform/api-platform#2711]
API Platform version 3.2, PHP 8.2, Symfony 7

Folowed security vulnerability process, but got response that all good, and no response to consecutive email.
So writing here.

I have simple ApiResource example
```
#[ApiResource()]
class UserApi
{
  public ?int $id = null;
  
  public ?string $firstName = null;  
  
  #[ApiProperty(readable: false)]
  public ?string $doNotShow = null;
}
```
If i request jsonld format http://localhost/api/users/1.jsonldi get:
```
{
  "@context": "/api/contexts/User",
  "@id": "/api/users/1",
  "@type": "User",
  "id": 1,
  "firstName": "john",
}
```
'doNotShow' is not visible

If i request json format http://localhost/api/users/1.json, i get:
```
{
  "id": 1,
  "firstName": "john",
  "doNotShow": "secret",
}
```
'doNotShow' is visible

config file: api_platform.yaml

```
api_platform:
    mapping:
        paths: [ 
           '%kernel.project_dir%/src/Entity',
        ]
    formats:
        json: [ 'application/json' ]
        jsonld: ['application/ld+json']
```

**Comment by dunglas** [comment]
Hi `readable` is just a hint for the generated Hydra docs and must not be used for security.

For security-related settings, use the dedicated `security` property of the `ApiProperty` attribute instead.

**Comment by mantaszv** [comment]
> Hi,
> 
> `readable` is just a hint for the generated Hydra docs and must not be used for security.
> 
> For security-related settings, use the dedicated `security` property of the `ApiProperty` attribute instead.

Still it doesn't act as suposed.

**Comment by soyuka** [comment]
Hi, I don't understand why you'd need this ApiResource is designed to be used on a class wich properties represent your resource, if a field isn't needed in the response it should not even be in the class. Also, there's no mention of this field of `ApiProperty` anywhere in the documentation: what are you trying to do? what is "as suposed"? 

Last but not least, got your email, tested the functionality and it does work, sorry I did not take the time to answer but as it was not a security issue I just discarded.

```php
<?php

namespace ApiPlatform\Tests\Fixtures\TestBundle\ApiResource\Issue2711;

use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Operation;

#[ApiResource(provider: [self::class, 'provide'])]
class Readable
{
    public function __construct(public int $id, public string $name, #[ApiProperty(readable: false)] public string $secret) {}

    public static function provide(Operation $operation, array $uriVariables = [], array $context = []): object|array|null
    {
        return new self(1, 'test', 'secret');
    }
}
```

```console
❯ curl -k -X 'GET' -H 'Accept: application/json' 'https://localhost:8000/readables'
{"id":1,"name":"test"}%
❯ curl -k -X 'GET' -H 'Accept: application/json' 'https://localhost:8000/readables.json'
{"id":1,"name":"test"}%
❯ curl -k -X 'GET' 'https://localhost:8000/readables.json'
{"id":1,"name":"test"}%
```

**Comment by mantaszv** [comment]
Hi, Soyuka,
> if a field isn't needed in the response it should not even be in the class. Also, there's no mention of this field of `ApiProperty` anywhere in the documentation: what are you trying to do? what is "as suposed"?

The issue here, is that ApiProperty  attribute doesn't work with json format for me.
Field may be writable, bot not readable. I simplified an example to present the problem. 

I did run your 'Readable' class example (exact, no changes) and got different results:
 in json format 'secret' exist and in 'ld+json' it is not.
```
>curl -k -X 'GET' -H 'Accept: application/json' 'http://localhost/api/readables'
{"id":1,"name":"test","secret":"secret"}%
>curl -k -X 'GET' -H 'Accept: application/ld+json' 'http://localhost/api/readables'
{"@context":"\/api\/contexts\/Readable","@id":"\/api\/readables","@type":"Readable","id":1,"name":"test"}%


```
