### ISSUE TITLE
Handling File Upload Error

### ISSUE THREAD

**Issue by sta2m** [api-platform/api-platform#2713]
**API Platform version(s) affected**: 3.3.3

**Description**  

I have an issue when doing a POST request to upload a file, using the example from the [docs](https://api-platform.com/docs/core/file-upload/)

Error : Could not resolve argument $data of \"api_platform.action.placeholder::__invoke()\", maybe you forgot to register the controller as a service or missed tagging it with the \"controller.service_arguments\"?"

Same as : https://github.com/api-platform/api-platform/issues/2539#issuecomment-2098595585

**How to reproduce**  

See [docs](https://api-platform.com/docs/core/file-upload/)

**Possible Solution**  

This workaround work for me : https://github.com/api-platform/api-platform/issues/2539#issuecomment-1790341634

**Additional Context**  

My conf : 
```api_platform:
    title: Hello API Platform
    version: 1.0.0
    # Mercure integration, remove if unwanted
    mercure:
        enabled: false
        include_type: true
    formats:
        jsonld: ['application/ld+json']
        multipart: [ 'multipart/form-data' ]
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
    # Good defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
            rfc_7807_compliant_errors: true
    # change this to true if you use controllers
    use_symfony_listeners: true
    keep_legacy_inflector: false
    swagger:
        api_keys:
            JWT:
                name: Authorization
                type: header

```

**Comment by dynalouis** [comment]
Same issue here !

**Comment by asalisaf** [comment]
Try to specify input format in operation level instead of specifying in global config.

**Comment by sta2m** [comment]
My POST config : 

```
new Post(
            inputFormats: ['multipart' => ['multipart/form-data']],
            processor: UploadOnFile::class,
            deserialize: false,
            openapi: new Model\Operation(
                requestBody: new Model\RequestBody(
                    content: new \ArrayObject([
                        'multipart/form-data' => [
                            'schema' => [
                                'type' => 'object',
                                'properties' => [
                                    'file' => [
                                        'type' => 'string',
                                        'format' => 'binary'
                                    ]
                                ]
                            ]
                        ]
                    ])
                )
            )
        ),```

**Comment by asalisaf** [comment]
try removing multipart in format section in global config(api_platform.yml)

**Comment by d0niek** [comment]
My error is:

```
Deserialization for the format \"multipart\" is not supported.
```

I've follow the docs from up to this [point](https://api-platform.com/docs/core/file-upload/#making-a-request-to-the-media_objects-endpoint) and after ` POST /media_objects` I got an error.

[Here](https://github.com/api-platform/docs/commit/39655fc3d7778b97320d24e74b5f0a30bc2599d2) I see "new" change which doesn't work. 

| Vich **doesn't** manage the file creation and set the filePath.

It looks like custom process is needed. Is it true?

**Comment by d0niek** [comment]
@sta2m do you have any progress in this issue?

**Comment by fvozar** [comment]
I had the same issue and I had to solve it with custom provider. Here is my implementation

```php
public function provide(Operation $operation, array $uriVariables = [], array $context = []): object|array|null
	{
		$uploadedFile = $context['request']->files->get('file');
		if (!$uploadedFile) {
			throw new BadRequestHttpException('"file" is required');
		}
		$mediaObject = new MediaObject();
		$mediaObject->file = $uploadedFile;

		return $mediaObject;
	}
```

MediaObject is my entity with Vich Uploadable attribute.

**Comment by soyuka** [comment]
We successfully handle file upload in many of our projects, closing as non-issue

**Comment by d0niek** [comment]
In my case the problem was that docs aren't in good order.

After section **Resolving the File URL** should be a **Handling the Multipart Deserialization** (!)
