### ISSUE TITLE
Implementing getSupportedTypes() in a Denormalizer causes a Fatal Error Allowed Memory size exhausted

### ISSUE THREAD

**Issue by algorun77** [api-platform/api-platform#2737]
**API Platform version(s) affected**: 3.3.7 and Symfony 6.4

**Description**  
I'm trying to implement a custom Denormalizer by following the example given in the doc : [https://api-platform.com/docs/core/serialization/#plain-identifiers](https://api-platform.com/docs/core/serialization/#plain-identifiers). However, each time I'm trying to implement the `getSupportedTypes()` method, my requests fails with a "Fatal error: Allowed memory size of X bytes exhausted" as you can see in the screenshot attached. If I remove the method, it works fine but I'm left with a deprecation notice. What's strange is that I just adapted the inner code of the official example, so I don't understand what's wrong. And since it's a fatal error, I don't have the Profiler to help me.

**How to reproduce**  
I setup a little project [here](https://github.com/algorun77/api-platform-denormalizers). I hope the README fil will be enough, I'm not used to this.

Follow the steps and you should get a "Error: Maximum execution time of 30 seconds exceeded". It's not exactly the same error than on my work project (which I cannot share for obvious reasons) but it seems that the error lays at the same place.

After getting the error, open the file `Serializer/DummyDenormalizer`, and remove the method `getSupportedTypes()` and try the request again. Now, you get a validation error, which is what's expected from the beginning.

**Additional Context**  
On my work project, this is what my Denormalizer looks like :
```php
<?php

namespace App\Serializer;

use App\Entity\Employee;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;

class EmployeeDenormalizer implements DenormalizerInterface, DenormalizerAwareInterface
{
    use DenormalizerAwareTrait;

    public function __construct(private readonly Security $security)
    {
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        $data = $this->denormalizer->denormalize($data, $class, $format, $context + [__CLASS__ => true]);

        if (!$this->security->isGranted('ROLE_SUPERVISOR')) {
            $currentUser = $this->security->getUser();
            if ($currentUser instanceof Employee && count($currentUser->getCompanies()) === 1) {
                foreach ($data->getCompanies() as $company) {
                    $data->removeCompany($company);
                }

                $data->addCompany($currentUser->getCompanies()->toArray()[0]);
            }
        }

        return $data;
    }

    public function supportsDenormalization($data, $type, $format = null, array $context = []): bool
    {
        return (
            \in_array($format, ['json', 'jsonld'], true) &&
            is_a($type, Employee::class, true) &&
            !isset($context[__CLASS__])
        );
    }

    public function getSupportedTypes(?string $format): array
    {
        return [
            'object' => null,
            '*' => false,
            Employee::class => true
        ];
    }
}
```
The error on Postman:

![image](https://github.com/api-platform/api-platform/assets/24519881/f6c00f8c-3ac0-4534-8198-7843fcd3d760)

The line 21 is the call to the denormalizer `$data = $this->denormalizer->denormalize($data, $class, $format, $context + [__CLASS__ => true]);`

Am I missing something or is this really a bug? Since I did not found any mention on this elsewhere.
Thanks 😃

**Comment by GHuygen** [comment]
I think that your getSupportedTypes function is the problem.
It looks like it's copied from the docs. [Here](https://symfony.com/doc/current/serializer/custom_normalizer.html#performance-of-normalizers-denormalizers).
All these values are examples.

'object' => null means that the normalizer doesn't support objects.
'*' => false means that it supports everything but it can't be cached.
Employee::class => true means that it supports that object and it's cacheable.

I would just use Employee::class => false to see if that resolves your issue.

**Comment by algorun77** [comment]
Hello,

Yes ! Using only
```php
public function getSupportedTypes(?string $format): array
{
    return [
        Employee::class => false
    ];
}
```
works fine ! After re-reading the docs, I think I misunderstood what the value true/false were used for. I can't believe I missed that after spending that much time on it...
And I guess trying to cache a deserialized Doctrine entity is a bit too much to handled given the complexity of those objects.

Thanks a lot for your help!

**Comment by jdreesen** [comment]
I suppose it was built after reading [these API platfom docs](https://api-platform.com/docs/core/serialization/#plain-identifiers-for-symfony) and I think they're broken and should be changed.
