### ISSUE TITLE
composer install --no-dev

### ISSUE THREAD

**Issue by matthieu-delisle** [api-platform/api-platform#2755]
I don't see in the Dockerfile or the entrypoint if you set the --no-dev flag for composer install. Does this mean that you deploy require-dev package to all your environment?

**Comment by dunglas** [comment]
It's here: https://github.com/api-platform/api-platform/blob/main/api/Dockerfile#L88

**Comment by matthieu-delisle** [comment]
Oups sorry, I was looking at my Dockerfile that I modified month ago. Thank you for the fast response!
