### ISSUE TITLE
entrypoint normalization question

### ISSUE THREAD

**Issue by cr3a7ure** [api-platform/api-platform#278]
I'm curious why the first letter is lower case in entrypoint and in '#Entrypoint' of docs.jsonld.
My main concern is that I can not see direct connection to the class description without transforming it back to match other hydra fields. 
  "civicStructure": "/civic_structures" vs  "CivicStructure": "/civic_structures",

`{
  "@context": "/contexts/Entrypoint",
  "@id": "/",
  "@type": "Entrypoint",
  "thing": "/things",
  "place": "/places",
  "civicStructure": "/civic_structures",
  "postalAddress": "/postal_addresses",
  "offer": "/offers",
  "airport": "/airports",
  "intangible": "/intangibles",
  "flight": "/flights"
}`

`"@id": "#Entrypoint",
      "@type": "hydra:Class",
      "hydra:title": "The API entrypoint",
      "hydra:supportedProperty": [
        {
          "@type": "hydra:SupportedProperty",
          "hydra:property": {
            "@id": "#Entrypoint/thing",
            "@type": "hydra:Link",
            "domain": "#Entrypoint",
            "rdfs:label": "The collection of Thing resources",
            "range": "hydra:PagedCollection",
            "hydra:supportedOperation": []`

**Comment by dunglas** [comment]
Because it maps the name of the property generated in `/`, and by convention it should be lowerCamelCased.
