### ISSUE TITLE
What is the best way to sort all items in response?

### ISSUE THREAD

**Issue by indapublic** [api-platform/api-platform#279]
I have this response 

```
[
  {
    "id": "1",
    "name": "Dddd-item",
    "subitems": [
      {
        "id": "1",
        "name": "Cccc-subitem"
      },
      {
        "id": "2",
        "name": "Bbbb-subitem"
      },
      {
        "id": "3",
        "name": "Aaaaa-subitem"
      }
    ]   
  },
  {
    "id": "2",
    "name": "Aaaa-item",
    "subitems": [
      {
        "id": "4",
        "name": "Ffff-subitem"
      },
      {
        "id": "3",
        "name": "Aaaaa-subitem"
      },
      {
        "id": "5",
        "name": "Zzzzz-subitem"
      }
    ]   
  }
]
```

I should to sort all items and all subitems ascending on name. What is the best way to realize it?
Order Filter is not suitable for this, isn't it?

**Comment by cr3a7ure** [comment]
If you are fetching from a database(Doctrine) you should have a look at this section [filters#creating-custom-doctrine-orm-filters](https://api-platform.com/docs/core/filters#creating-custom-doctrine-orm-filters).
I have not implement anything similar myself though.
