### ISSUE TITLE
Will there be future support for HATEOAS?

### ISSUE THREAD

**Issue by leroy0211** [api-platform/api-platform#28]
It is not necessarily an issue, but  more something to discuss about. 
Will there be any support for HATEOAS in the future? Or is there already a way to implement this in the api-platform project?

**Comment by dunglas** [comment]
In fact HATEOAS is supported out of the box by API Platform. By default, all APIs are compliant with JSON-LD and Hydra (W3C recommandations about Linked Data/HATEOAS).

Adding support for other HATEOAS formats such as HAL or SIREN should be really easy in the `dev-master` version thanks to Content Negotiation: https://github.com/api-platform/doc/blob/master/api-bundle/content-negotiation.md

If someone start to work on supporting such formats, I'll be pleased to merge it upstream.

**Comment by renan-taranto** [comment]
I wonder how to proceed in order to add something like this to a resource using api-platform:
 "ref" : "http://foo.org/bar/3" 
Could you give me some hints or maybe an example?

**Comment by leroy0211** [comment]
A few weeks ago I've seen a symfony bundle that can add linked data to entities by using only annotations.

For example to publish a blog post. The `/publish` or `/unpublish` links could be added as a Relation with specific expressions like only add the `/publish` link if the `isPublished()` method returns `false`. And only if the requested user has the `ADMIN` role.

I've just found the related bundle:  https://github.com/willdurand/BazingaHateoasBundle

I think this can be usefull, but might not be the best solution to integrate these links/actions.

**Comment by renan-taranto** [comment]
Thank you very much leroy0211.  I'm just learning, so for now I will use FOSRest, JSMSerializer and BazingaHateoas until I find a way to do that with API Platform.

**Comment by dunglas** [comment]
@renan-taranto You want HAL support right? You can do it (yourself) with the dev-master version. You need to implement a Symfony Normalizer implementing HAL support like we've done for JSON-LD: https://github.com/dunglas/DunglasApiBundle/blob/master/JsonLd/Serializer/ItemNormalizer.php

**Comment by renan-taranto** [comment]
@dunglas I am new to JSON-LD and after some researches on the web I believe that what I want is not supported by it. I will read about the Symfony Normalizer and try to implement HAL. Thanks for the great framework man.

**Comment by Simperfit** [comment]
@renan-taranto HAL is now implemented in V2.

**Comment by renan-taranto** [comment]
Thank you @Simperfit
