### ISSUE TITLE
OAuth and Entrypoint

### ISSUE THREAD

**Issue by quentinus95** [api-platform/api-platform#280]
Hello,

I've successfully added and configured oAuth to work with my ApiPlatform instance.

However, is there a way to customize the default entrypoint to only list resources that can be accessed by current user ?

Or maybe this is against Hydra specification?

Many thanks for your work.

**Comment by dunglas** [comment]
You can use [service decoration](http://symfony.com/doc/current/service_container/service_decoration.html) to decorate the `api_platform.hydra.normalizer.entrypoint` service and change the output.

But I think it's better to document available resources and throw a 401/403 status code if the user must authenticate.

**Comment by quentinus95** [comment]
Ok, thanks for the advice.

I keep it as is, so.
