### ISSUE TITLE
methods is{a_number} are not supported

### ISSUE THREAD

**Issue by jocel1** [api-platform/api-platform#282]
Hi,

Easily repeatable:

Just replace in Foo.php example file the method getBar() by is169(), the application will issue an exception:

Type error: Argument 2 passed to ApiPlatform\Core\Metadata\Property\Factory\CachedPropertyMetadataFactory::create() must be of the type string, integer given, called in /Users/jocelynfournier/Documents/workspace/php-api-ingestion/vendor/api-platform/core/src/Swagger/Serializer/DocumentationNormalizer.php on line 386

Thanks,

**Comment by dunglas** [comment]
Can you post the code? I didn't get it.

**Comment by jocel1** [comment]
Sure!

```php
<?php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * This is a dummy entity. Remove it!
 *
 * @ApiResource
 * @ORM\Entity
 */
class Foo
{
    /**
     * @var int The entity Id
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string Something else
     *
     * @ORM\Column
     * @Assert\NotBlank
     */
    private $bar = '';

    public function getId()
    {
        return $this->id;
    }

    public function is169() : string
    {
        return $this->bar;
    }

    public function setBar(string $bar)
    {
        $this->bar = $bar;
    }
}
```

**Comment by jocel1** [comment]
Basically it happens because in InheritedPropertyNameCollectionFactory / ExtractorPropertyNameCollectionFactory, the propertyName is stored as a key of the array $propertyNames, which is automagically converted by PHP into an int if it's a number.

**Comment by dunglas** [comment]
Ok got it. Definitely a bug.

**Comment by teohhanhui** [comment]
`declare(strict_types=1);` is helping us catch these. Yay! But the price to pay is that things not caught by our test suite would be broken for a while. Sorry...

**Comment by jocel1** [comment]
FYI, I'm currently working on a PR to fix the issue

**Comment by jocel1** [comment]
Just pushed the PR. However, I fail to modify the tests to cover this issue (I try playing with the Dummy entity, but it was not failing)
