### ISSUE TITLE
Question (normalization) : dynamically embed relations?

### ISSUE THREAD

**Issue by cookingfox** [api-platform/api-platform#284]
Hi,

__Short version:__

I am looking for a way to dynamically control which entity relations are embedded (full object instead of IRI), for example by including a request (query) parameter, e.g.: `/projects?embedLevels=2`.

__Long version:__

I have a question regarding the embedding of relations. I work on a project with entity relations that look like this:

- User
  - App
    - Project
      - Location
        - Page
          - Block

For every relation going down, the relationship is One-To-Many. So one User has many Apps, one App has many Projects, etcetera.

Now we have identified different types of scenarios in regards to how we would like entity relations to be embedded. For example:

- The "project overview" scenario starts at one App and expects Project entities to be fully embedded, but Location entities to be represented by IRIs - and so nothing from Location would be embedded.
- The "project details" scenario starts at one Project and expects *all* subsequent relations to be fully embedded.

After reading the docs, I understand I can use normalization contexts and (dynamic) serialization groups. For example, I could add groups with the names of the two scenarios above (e.g. "project_overview" and "project_details") to the relations that I want to be embedded. I could then pass a request parameter to influence which scenario I would want to apply. The default would be no embedded relations (just IRIs).

However, I'd prefer to choose a solution that is as dynamic as possible, so that there's more room to scale, and the API code remains free of usage scenarios (which is what it should be, of course).

Let's say I want to request all Project entities, with the subsequent two entities (Location and Page) embedded. These are some options that *could* work for me:

A. Provide a request parameter to indicate *how many* relations I want to be embedded. For example, `/projects?embedLevels=2`.
B. Provide a request parameter to indicate *up to which* entity I want the relations to be embedded. For example, `projects?embedUpTo=Page`.

So my questions:

1. How would I implement these options?
2. Are there any better alternatives?

I have the feeling that this is a pretty common desire / request, so I hope other people can benefit from your answer.

Thanks for taking the time with this question! :)

Abel
Cooking Fox

**Comment by cookingfox** [comment]
***BUMP***: It would be great if someone could help me with this!

**Comment by soyuka** [comment]
Hi!

You need to use a dynamic serialization context. I think that @bwegrzyn is doing just what you're looking for [see here](https://github.com/api-platform/core/pull/1041#issuecomment-292944026).

**Comment by bwegrzyn** [comment]
Hi @cookingfox. Check out https://github.com/api-platform/core/issues/1062. I've added a feature request to implement something similar to this directly in api-platform/core. 

My implementation has some short comings that would need to be addresses in order to provide a full solution, but its working for me for the moment. There is some working being done in https://github.com/symfony/symfony/pull/18834 & https://github.com/api-platform/core/pull/1036 that should help in that regard.

**Comment by cookingfox** [comment]
That looks promising, thanks @soyuka & @bwegrzyn ! I'll try it out later today.

**Comment by Simperfit** [comment]
This seems merged, I think this can be closed ;).
