### ISSUE TITLE
Swagger entities

### ISSUE THREAD

**Issue by jhonatanTeixeira** [api-platform/api-platform#285]
hello guys.

i've got the following entity

```php

/**
 * @ApiResource(
 *      attributes={
 *          "normalization_context"={"groups"={"read"}},
 *          "denormalization_context"={"groups"={"write"}}
 *      },
 *      itemOperations={
 *          "get"={"method"="GET"},
 *          "put"={"method"="PUT"},
 *          "cancel"={"route_name"="order_cancel"}
 *      }
 * )
 * @ORM\Entity()
 * @ORM\Table(name="order")
 * @ORM\EntityListeners({"\AppBundle\Entity\Listener\OrderListener"})
 */
class Order
{
    ...

    /**
     * @ORM\Embedded(class="AppBundle\Entity\Embeddable\OrderPayment", columnPrefix = "payment_")
     * @Groups({"read", "write"})
     *
     * @var \AppBundle\Entity\Embeddable\OrderPayment
     */
    private $payment;

    /**
     * @ORM\OneToMany(targetEntity="OrderItem", mappedBy="order", cascade={"persist"}, orphanRemoval=true, fetch="EAGER")
     * @Groups({"read", "write"})
     * 
     * @var OrderItem[]
     */
    private $orderItems;

    ...
}
```

however i get this on swagger:

```js
{
  ...

  "payment": "string",
  "orderItems": [
    "string"
  ]

  ...
}
```

OrderItem entity is not an api resource.

I've searched entire documentation and can't find anything on it, is there a way of my swagger show correctly?

Thanks

**Comment by cocciagialla** [comment]
@jhonatanTeixeira I have the same problem. Did you find any solution?

**Comment by Dragonqos** [comment]
Any solution found?

**Comment by dunglas** [comment]
You can use a Swagger decorator: https://api-platform.com/docs/core/swagger#override-swagger-documentation

**Comment by Simperfit** [comment]
Is the swagger decorator what you need ?

**Comment by jhonatanTeixeira** [comment]
I now understand that this is due to the way apiplatform expose the relationships by using the iri converter. Therefore its a string, you cannot send an entire entity on this json. You have to customize the entire thing if you want to work with nested objects
