### ISSUE TITLE
Problem in docker-compose commands in the documentation

### ISSUE THREAD

**Issue by ypereirareis** [api-platform/api-platform#288]
Hi !

There is a mistake in docker compose commands in the [documentation](https://api-platform.com/docs/distribution/).

```
docker-compose exec web ...
```

should be

```
docker-compose exec php ...
```

**web => php**

Thx !

**Comment by dunglas** [comment]
The doc on the website is about the current stable version (2.0). The container has been renamed php only in the dev version (the upcoming 2.1 version).
