### ISSUE TITLE
[documentation] Missing SocialMediaPosting in schema.yml

### ISSUE THREAD

**Issue by mheki** [api-platform/api-platform#29]
Hi,
the official documentation "Creating your first API with API Platform" is missing `SocialMediaPosting: ~` under `types` key in `schema.yml`.
This leads to the error message while generating entities:
```
$ bin/schema generate-types src/ app/config/schema.yml 
[error] The type "SocialMediaPosting" (parent of "BlogPosting") doesn't exist
```

**Comment by dunglas** [comment]
Thanks for the report and the fix @mheki
