### ISSUE TITLE
Override DELETE operation: update `status` property instead

### ISSUE THREAD

**Issue by cookingfox** [api-platform/api-platform#291]
Hi!

I want to override all entities' DELETE operation with a custom implementation that sets a new value to a custom `status` property instead. For example, when I do `DELETE /api/projects/3` I want it to set the `status` property of the Project entity with ID 3 to value `disabled`, and NOT remove the record from the database. I want to apply this to all my entities - they all implement a base `EntityInterface` that contains the getter + setter for this `status` property.

I spent some time trying the options I could think of, with the following results:

1. [Create a custom operation](https://api-platform.com/docs/core/operations#creating-custom-operations-and-controllers)

The problem I ran into is routing: I want to use this for all my entities, but could not figure out how to have a dynamic route in the action, e.g.:

```php
class SafeDeleteEntity
{
    /**
     * @Route(
     *     name="safe_delete_entity",
     *     path="/{entity}/{id}",
     *     defaults={"_api_resource_class"=EntityInterface::class, "_api_item_operation_name"="safe_delete_entity"}
     * )
     * @Method("DELETE")
     */
    public function __invoke($data) { ... }
}
```

Usage in entity:

```php
/**
 * @ORM\Entity
 * @ApiResource(
 *     itemOperations={
 *          "delete"={"method"="DELETE", "route_name"="safe_delete_entity"}
 *     }
 * )
 */
class MyEntity implements EntityInterface { ... }
```

This would result in a 405 error: method `DELETE` not allowed.

2. [Hook into the event system](https://api-platform.com/docs/core/events)

I was able to hook into the `PRE_WRITE` kernel event and check the entity and operation. I understand this is where I can update the entity `status` property, but I could not figure out how to prevent the `DELETE` operation. Is this even possible this way?

3. [Create a custom extension](https://api-platform.com/docs/core/extensions#custom-extension)

When printing the query builder, it was for the `SELECT` operation, not `DELETE`. It sounds logical that we first want to check whether there is an entity with the requested ID to provide the user with a 404 error when it does not. However, if this is not the `DELETE` operation, then it appears I am not able to override it this way...

Can you please advise me on the correct way to implement this?

Thanks!

Abel
Cooking Fox

**Comment by cookingfox** [comment]
***BUMP***: It would be great if someone could help me with this!

**Comment by soyuka** [comment]
Hmm, why are you not using a Doctrine subscriber for this? It looks like you need something like the [`SoftDeletable` extension](https://github.com/Atlantic18/DoctrineExtensions/blob/master/lib/Gedmo/SoftDeleteable/SoftDeleteableListener.php).

**Comment by Simperfit** [comment]
I agree with @soyuka @cookingfox why not using directly a doctrine event

**Comment by cookingfox** [comment]
Sounds good, I'll try this.

**Comment by Simperfit** [comment]
@cookingfox Can we close this ?

**Comment by toulemol** [comment]
Would it not be easier to use PUT as a method since you only want to modify a property ?

**Comment by soyuka** [comment]
@toulemol Not really because on the API side you want to DELETE. The thing is that sometimes `DELETE` on the API doesn't mean `DELETE` data but instead "flag this data as deleted", especially if you need to keep relations.

Closing as old, feel free to open a new one.

**Comment by DarkChyper** [comment]
Hello,
@soyuka @cookingfox 

I would like to complete this ticket without re-opening it.

I have exactly the same problem with version 2.7. I found another way to solve the problem than by using Doctrine events, in the Processor:

```
<?php

namespace App\State\Processor;

use ApiPlatform\Metadata\DeleteOperationInterface;
use ApiPlatform\Metadata\DeleteOperationInterface;
use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProcessorInterface;
use App\Entity\MyObject;

class ObjectProcessor implements ProcessorInterface
{
    /**
     * @var ProcessorInterface
     * Declaring and binding this interface is enough to block the standard DELETE, 
     * the system expects you to trigger the delete process only when you want it in this class. 
     * But if we never do it or without the data of our resources, we do not DELETE
     */
    private $removeProcessor;

    public function __construct(
        ProcessorInterface $removeProcessor
    ) {
        $this->removeProcessor = $removeProcessor;
    }

    /**
     * @return mixed
     */
    public function process($data, Operation $operation, array $uriVariables = [], array $context = [])
    {
        if (MyObject::class === $operation->getClass()) {
            if ($operation instanceof DeleteOperationInterface) {
                // it works without this line, but my IDE did not like an unused property
                $this->removeProcessor->process(null, $operation, $uriVariables, $context);
                return $this->remove($data);
            }
        }

        return $data;
    }

    private function remove($data)
    {
        // My Stuff which trigger a $em->flush() if needed

        return $data;
    }
}
```
