### ISSUE TITLE
Form request

### ISSUE THREAD

**Issue by castroCrea** [api-platform/api-platform#292]
I have a request but I don't know where to ask.
Did you plan to make a request for each entity where we can get all the needed field.
For example : 
I have a relation oneToMany between book and type of book and another one with book and editor. Will be nice to do one request where we can get all type of book and all the editor inside of two request.

I hope you get what I means.
Have a good day
Paolo

**Comment by hectorh30** [comment]
I guess #1602 relates to what you're looking for

**Comment by Simperfit** [comment]
@castroCrea Could you please add an technical exemple ?

Do you mean embeddable resources ?

**Comment by castroCrea** [comment]
Hello,
Sorry for the late answer

There is what i means

For exemple i have the entity : 

`<?php

// src/AppBundle/Entity/Product.php

namespace AppBundle\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ApiResource
 * @ORM\Entity
 */
class Product // The class name will be used to name exposed resources
{
    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    public $id;

    /**
     * @param string $name A name property - this description will be avaliable in the API documentation too.
     *
     * @ORM\Column
     * @Assert\NotBlank
     */
    public $name;

    /**
     * @ORM\ManyToOne(targetEntity="Category")
     */
    public $category;

    /**
     * @ORM\ManyToOne(targetEntity="Country")
     */
    public $country;
}`

And i want to generate the CRUD

For the form i have to make a request to get all the category and one to get all the country
Despite to do 2 request I think it will be nice to have one request to get all the dependency of the form.
There it's just 2 but we can imagine that it can be more, for exemple i'm working on a project right know where i have 5 dependency so 5 requests api.

So it will be faster to do just one.
Maybe it can be a nice feature for the next release

Have good day
Paolo

**Comment by Simperfit** [comment]
I think what you need is [this](https://api-platform.com/docs/core/serialization-groups-and-relations#embedding-relations), you will then do ` GET /products` and get products, and category and country in the response

**Comment by castroCrea** [comment]
I want to get all the category and the country to make a post form actually, with this i get the country and the-catgeroy of the product no?

**Comment by Simperfit** [comment]
Now I understand ^^.

I don't think it's a good idea to have a endpoint that returns you 2 resources, but what you can do is to maybe add a customDataProviders or  a custom action that will fetch everything for you and put them into two json arrays ?

**Comment by Simperfit** [comment]
Closing as we got no feedback.
