### ISSUE TITLE
[QUESTION] How to create multiple resources

### ISSUE THREAD

**Issue by cocciagialla** [api-platform/api-platform#294]
Hi,
I am quite new to api-platform so excuse me if it is a newbie question.

I need to expose an api endpoint to create (or even update) multiple instances of a single resource type. 

Something like a POST to `/teams_multiple` which accepts a json like:
```
[
{
  "name": "Team 1",
  "teamLogo": "logo1.png"
},
{
  "name": "Team 2",
  "teamLogo": "logo2.png"
},
...
]
```
Which is the best practice in this case?

**Comment by Simperfit** [comment]
By default this is not possible, but what you could do to achieve that is to use a [custom post / put](https://api-platform.com/docs/core/operations#creating-custom-operations-and-controllers) and parse what you send.

**Comment by cocciagialla** [comment]
Thanks @Simperfit I will follow your suggestion.

**Comment by sunviwo** [comment]
@Simperfit would you have any idea have to do this ? A snippet would be highly appreciated.

**Comment by pashak09** [comment]
You can use
https://api-platform.com/docs/core/dto/
If an example is needed, let me know. I will help you.

**Comment by armin-crosslend** [comment]
@pashak09 I would be interested in an example.

**Comment by ayoob-faraji** [comment]
@pashak09 I would be interested in an example too.

**Comment by sfi-fgarnier** [comment]
@pashak09  I would be interested in an example plz.

**Comment by lsdch** [comment]
@Renrhaf thank you for this example, I tried to reproduce it but get an error : 
```
App\\Controller\\API\\ImportCSVAction::__invoke(): 
Argument #1 ($data) must be of type App\\DTO\\CsvRecordsRequest, App\\Entity\\Dna given
```
How did you manage to by-pass it so that your controller receives an InvitationMultipleRequest instead of an Invitation ? 
Is the `@ApiResource` annotation that you show set on your `Invitation` entity, or some other custom entity ? 

I'd love to understand what's going on here, hope you can help. Cheers !

---
**Some context :** 

I created my DTOs and DataTransformers in the same way as in your example code (only changing class names). 

The controller is currently doing nothing special : 
```php
/**
 * @param CsvRecordsRequest $data
 */
class ImportCSVAction {
	public function __invoke(CsvRecordsRequest $data): CsvRecordsResponse {
		return new CsvRecordsResponse();
	}
}
```
And here is my resource configuration on class `Dna`
```php
 * @ApiResource(
 *     //...
 *     collectionOperations={
 *      //...
 * 	  "import": {
 * 		"method": "POST",
 * 		"path": "/dnas/import",
 * 		"controller": ImportCSVAction::class,
 * 		"input": CsvRecordsRequest::class,
 * 		"output": CsvRecordsResponse::class,
 * 		"normalization_context": {"groups": {"dna:item"}},
 * 		"denormalization_context": {"groups": {"csv:import"}},
 * 	}
 *   //...
 * )
 class Dna {
   //...
}
 ```

**Comment by drennvinn** [comment]
@Renrhaf is it possible to have an update with state processor/provider of api platform ^3.0 ? 
Because of the deletion of Data transformers to be replaced by state I would like to have an opinion on good practices now for bulk post because there really aren't many resources online on this topic 😅

**Comment by Renrhaf** [comment]
@lsdch @drennvinn sorry I got quite busy on other projects but I have a new one with API Platform 3 so I'll try to update the example if I can in the next weeks. In the meantime if anyone has the answer, feel free to post :)

**Comment by rubobaquero** [comment]
@Renrhaf Don't want to put pressure on you, but if you find some time it would be amazing if you can share that example with API Platform 3. Thanks in advance!!

**Comment by timdreier** [comment]
Hi, I‘m trying to get this working in the latest Version. What exactly is the mailManager in your example? I cannot find something similar in my instance.

**Comment by Renrhaf** [comment]
Hi @timdreier, I did not put the code of the `MailManager` as it is just a service which is processing an email. You can refer to the documentation to create your own service to send emails : https://symfony.com/doc/current/mailer.html

**Comment by timdreier** [comment]
Thanks for clarification @Renrhaf! Got an error and thought this part could be needed. So this should be the MailMultipleProcessor if it should just persist the Entites:

```
<?php

namespace App\State\Mail;

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProcessorInterface;
use App\Dto\Mail\MailMultipleDto;
use App\Dto\Mail\MailMultipleResponseDto;
use App\Service\Mail\MailManager;
use App\Entity\Mail\Mail as MailEntity;

final class MailMultipleProcessor implements ProcessorInterface
{
    public function __construct(
        #[Autowire(service: 'api_platform.doctrine.orm.state.persist_processor')]
        private ProcessorInterface $persistProcessor,
    ) {}

    /**
     * @param MailMultipleDto $data
     */
    public function process($data, Operation $operation, array $uriVariables = [], array $context = []): MailMultipleResponseDto
    {
        $result = new MailMultipleResponseDto();
        $mails = $data->getMails();
        if (empty($mails)) {
            return $result;
        }

        foreach ($mails as $mail) {
            $this->persistProcessor->process($mail, $operation, $uriVariables, $context)
        }

        return $result;
    }
}
```

Just one more question: while the above example works it generates an invalid openapi.yml for me. Is this also fixable?

<img width="532" alt="image" src="https://github.com/api-platform/api-platform/assets/10117610/f80e98bd-ee8b-43da-89cd-aa83a3a0629b">
