### ISSUE TITLE
[QUESTION] Exceptions : Hydra + error payload

### ISSUE THREAD

**Issue by amaccis** [api-platform/api-platform#295]
Hi.

My APIs use a few data providers that return (after parsing) the result of external APIs and I'm handling all the errors by raising customized exceptions, so, in case of error, I always get something like that:
```
{
  "@context": "/api/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Search Error"
}
```
My purpose, by adding an error payload, would be to get something like this:
```
{
  "@context": "/api/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Search Error",
  "errors": [
    {
      "field1": "compulsory"
      "field2": "wrong"
    }
  ]
}
```
I don't know if the event listeners are the best way to address my problem and what hydra property I am supposed to use.

Any advice? 

Thank you very much!

A.

**Comment by Metisse** [comment]
up

**Comment by BonnieDoug** [comment]
Have you tried using the assert validation functions in your entities?

https://symfony.com/doc/current/validation.html

When setup, these provide pretty errors in Hydra format.

**Comment by Simperfit** [comment]
@amaccis Is this still an issue for you ?

**Comment by amaccis** [comment]
@Simperfit I abandoned the idea to add the error detail, since it turned that it was not essential.
So the issue can be closed. Thanks.
