### ISSUE TITLE
have handle on GET/POST/DELETE/PUT method 

### ISSUE THREAD

**Issue by angelzeke** [api-platform/api-platform#296]
For a specific project i would like not use CRUD but keep handing on differents methods.
```php
# In src/AppBundle/Entity/Book.php
<?php

  @ORM\Entity
  @ApiResource(
  itemOperations={
      "get"={"method"="GET"},
      "put"={"method"="PUT"},
      "delete"={"method"="DELETE"},
      "special"={"route_name"="book_special"},
      "specialget"={"route_name"="book_special"},
  }
  )
```
```php
# In src/AppBundle/Action/BookSpecial.php
<?php
    
     @Route(
          name="book_special",
          path="/books/{id}/special",
          defaults={"_api_resource_class"=Book::class, "_api_item_operation_name"="special"}
      )
      @Method({"GET", "PUT"})
```     
I must create a file for each method (GET,PUT,DELETE,...) and change route_name or can use controller and define each method?

**Comment by soyuka** [comment]
What do you mean by `keep handing on differents methods`. I think that there is a better way of doing what you want but I need more informations.

**Comment by angelzeke** [comment]
For example, 
GET /books ==> host/app_dev.php/#!/Book/getBookCollection

I want overwritte CRUD and use my own method

**Comment by angelzeke** [comment]
I think best way is using In src/AppBundle/Entity/Book.php

  @ApiResource(
      shortName="Books method",
      collectionOperations={
          "get"={
               "method"="GET",
               "controller"="AppBundle:Book:get",
           },
          "post"={"method"="POST" },
          "search"={
             "path"="/books/search",
             "method"="GET",
             "controller"="AppBundle:Book:search",
             "hydra_context"={
                   "type"="hydra:Operation",
                   "hydra:title"="Recherche de books",
                   "returns"="jsonld"
               }
          }
      },
      iri="http://schema.org/Book"
 )

and associate a controller src/AppBundle/Controller/BookController.php

namespace AppBundle\Controller;

use AppBundle\Entity\Book;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\RequestStack;

class BookController extends Controller
{

    public function searchAction()
    {

        return array();
    }

    public function getAction()
    {
        $em = $this->getDoctrine()->getManager();
        return $em->getRepository('AppBundle:Book')->findAll();
    }
}

**Comment by soyuka** [comment]
Just implement a DataProvider if you want to do custom queries. There are really a few use cases where a Controller is valid with ApiPlatform. Most of the use cases can be dealt with by implementing one of those:
- Filter (soon will also be possible without doctrine)
- DataProvider (don't need to be doctrine specific)
- QueryExtension

**Comment by angelzeke** [comment]
Thank you for the answer, would you have an idea or I could find an example

**Comment by insekticid** [comment]
@soyuka You are developping custom Filters without doctrine? I am working on it too in my project. Could you send me more info or link about this planned feature?

**Comment by soyuka** [comment]
@insekticid we need https://github.com/api-platform/core/pull/1099 for filters to be able to work without doctrine. Then, you can check https://github.com/api-platform/core/pull/1111 which works as a filter. We'll then also work on https://github.com/api-platform/core/issues/1083 for example.

**Comment by insekticid** [comment]
Today I have finished custom filters Number,string and datetime which are
working through my service classes - mappers  to soap service. It reads
filter parameters from required parameters from service method and apply
them via Php Di Invoker

**Comment by insekticid** [comment]
Today I have finished custom filters Number,string and datetime which are
working through my service classes - mappers  to soap service. It reads
filter parameters from required parameters from service method and apply
them via Php Di Invoker

example:

```php

//entity class
/**
 * @ApiResource(
 *     collectionOperations={"get"={"method"="GET", "invoker"={"AppBundle\Service\SoapService", "getEntries"} }},
 *     itemOperations={}
 *     )
 */

//service
final class SoapService
{
    public function getEntries(int $projectId, \DateTime $from, \DateTime $to, $phoneNumber = null) {}

//DateFilter
class DateFilter extends AbstractFilter
{
    public function getDescription(string $resourceClass): array
    {
//reads parameters from SoapService::getEntries via Reflection
....
            $description += $this->getFilterDescription($property);
....
            return $description;
    }

    protected function getFilterDescription(string $property): array
    {
        $default = new \DateTime('YESTERDAY', new \DateTimeZone('Europe/Prague'));

        return [
            sprintf('%s', $property) => [
                'property' => $property,
                'type' => \DateTimeInterface::class,
                'required' => true,
                'swagger' => ['default'=> $default->format(\DateTime::ISO8601), 'description' => 'ISO8601[' . \DateTime::ISO8601.']'],
            ],
        ];
    }
```

**Comment by insekticid** [comment]
my reply is here #301

**Comment by Simperfit** [comment]
It seems that all the linked PRs have been merged. This can be closed.
