### ISSUE TITLE
robots.txt and icons in /web folder

### ISSUE THREAD

**Issue by sadovnik** [api-platform/api-platform#3]
Hi

Why do the framework stores these resources? They must be stored in the frontend.
By the way there is no point to have this `web` folder anymore.

**Comment by theofidry** [comment]
It's still useful since the front controller is in `web`. Besides if you're shipping an SPA with it, you may as well put all your front-end files in web instead of having two separate repository. If you don't need it it can always delete it :)

**Comment by dunglas** [comment]
Hi,

This is a rest of the the Symfony standard edition. 

The `web` folder is necessary for storing front controllers.
We can discuss about removing `robots.txt` and `favicon.ico` (this one must at least be replaced with the API Platform logo) but as crawlers will always request them, your logs will be full of 404 if they aren't present. It's considered best practice to always have those files.

Solution proposed by @theofidry can be useful for prototype and small apps but the recommended way of using API Platform is having separate git repositories (and servers) for the API and the frontend app.

**Comment by codeskull** [comment]
@dunglas 404 logging of these files can be easily prevented by your web server:
```nginx
location ~* \/(favicon\.ico|robots\.txt) {
	log_not_found off;
	access_log off;
}
```
They don't make a problem.

What's the purpose of requesting these files in terms of an API? I haven't found any references about this topic, could you please share some?

**Comment by theofidry** [comment]
@codeskull they both don't have any use for the API. As @dunglas said crawlers will always request them, and even if you can disable logging for these files, it is not done by default. That's way it is considered good practice to keep them, at least for "distributed products". If you have your API installed, there is nothing preventing you to remove them and disable the logging for that.
