### ISSUE TITLE
Left join with fields not needed in result?

### ISSUE THREAD

**Issue by antonioperic** [api-platform/api-platform#304]
I have question, I have situation where I have virtual property $cover, and two variables $coverValue and $coverType. with event (doctrine event) I am setting value of $cover. Issue is that when I reach my entity from relation of some other entity I need to put value and type in response to get it, otherwise I cannot get value as it is not selected from DB (left join). Can I select this two fields in some way and remove them from response, so only $cover is in response.

**Comment by antonioperic** [comment]
@Simperfit cover is virtual property generated on fly.

**Comment by Simperfit** [comment]
Does the serialization groups help you on that ? I think it's the best way to do it.

**Comment by antonioperic** [comment]
@Simperfit yes if i adde serilization then i have it in respone, i dont want it in response just to get it for calucation

**Comment by Simperfit** [comment]
If you still have an issue please feel free to ping me.
