### ISSUE TITLE
Error on demo page

### ISSUE THREAD

**Issue by tacman** [api-platform/api-platform#307]
The demo page is showing a validation error:

![image](https://cloud.githubusercontent.com/assets/619585/26351889/536e18da-3f87-11e7-8ed3-042eedd835a5.png)

https://online.swagger.io/validator/debug?url=https://demo.api-platform.com/docs.json

**Comment by dunglas** [comment]
It's a known issue with the online Swagger validator... But the generated Swagger file is valid.

**Comment by Simperfit** [comment]
As in the spec, we use the http://swagger.io/specification/#externalDocumentationObject.

The issue in with the validator.
