### ISSUE TITLE
Retreiving user by its username or its email.

### ISSUE THREAD

**Issue by DylanFayant** [api-platform/api-platform#312]
Hello the community !

I'm using Api Platform for a mobile application project. I've created an Account entity which works properly. When I click on the mobile register button it sends a post request to the API containing my registering user informations and it saves properly the Account to the database. 

The problem here is that IDK how i can, thanks to Api Platform, discover if there is already an user using the email address used to the registration. 

I've tried to create an action "AccountExists" which returns an account by sending it an email address, but I haven't found how to get an email post param in a custom action.

Thank you !
Have a nice day ;)

Dylan Fayant

**Comment by soyuka** [comment]
You should be able to use symfony validation for this. See [UniqueEntity](http://symfony.com/doc/current/reference/constraints/UniqueEntity.html) for example.

**Comment by DylanFayant** [comment]
Thank you for your reply. 
UniqueEntity is used to make sure that a field is unique in the database. 
Here the thing is that I want to get an user through the API, by its email, to check in my mobile app if there is already an user in the database with the same email.
Thank you again for your time =)

**Comment by dunglas** [comment]
So you may just use the standard `search` filter: https://api-platform.com/docs/core/filters#search-filter

**Comment by Simperfit** [comment]
You don't need to check that the the mobile app if the api returns you an error when sending the email.

Or what you can do is to use our filters to do that?

**Comment by DylanFayant** [comment]
Thank you, filtering works perfectly. I saw this page into the doc but I thought it couldn't solve my problem, sorry for the disturbing ^^ !
Have a nice day and thank you again.
