### ISSUE TITLE
[question]: How to catch exceptions and return proper messages (Problem Details)

### ISSUE THREAD

**Issue by todor-programista** [api-platform/api-platform#316]
Hey guys,

I need to catch some exceptions and return proper ProblemDetails response.
For example:
`curl -X DELETE --header 'Accept: application/problem+json' 'https://demo.api-platform.com/books/6'`

returns:
```
Status: 500
{
  "type": "https://tools.ietf.org/html/rfc2616#section-10",
  "title": "An error occurred",
  "detail": "Internal Server Error"
}
```
which based on my case I presume is because of the foreign key constraint for the relation to 'Reviews'

In the logs there is an PDO exception that I need to catch and return `409 Conflict` for example (or somethign else)

How do I hook to the flow and return ApiProblemResponse?

**Comment by todor-programista** [comment]
Anyone?

**Comment by dunglas** [comment]
@todor-programista Does https://github.com/api-platform/docs/pull/186 help?

**Comment by todor-programista** [comment]
It actually does help. This will fit most of my cases.
I can make validation whether the relation is empty and throw an exception.

Thanks a lot.

p.s. It would be a nice feature for such relational constraint exceptions to be handled by the framework though.
