### ISSUE TITLE
Lost the templates path resolution

### ISSUE THREAD

**Issue by dmeziere** [api-platform/api-platform#318]
Hello, I tried to install api-platform this way :
`./composer.phar require api-platform/core`

I added the bundle to my AppKernel.php, the route to my routing.yml, and created an entity using the @ApiResource annotation.

On any application route I ask, I get, for example "Unable to find template "AdminBundle:Default:index..twig"", missing the "html" in the end of all my views.

If I comment-out api-platform in my AppKernel.php, it gets back to normal, and if I uncomment it, I get that behaviour, systematically.

**Comment by soyuka** [comment]
Check how things are configured here (api-platform/api-platform). Your configuration (composer.json and config) should be close to the one here to make things work by using only `api-platform/core`. Especially the assets part to link Swagger (should be enable if the base was the symfony package).

 Removing the cache may also help.

**Comment by dunglas** [comment]
It's may also be related to how the format negotiation is handled: https://github.com/api-platform/core/blob/master/src/EventListener/AddFormatListener.php

Can you provide an example reproducing the problem (an minimal repository for instance)?

**Comment by soyuka** [comment]
Format is part of the config right?

My configuration:

```
api_platform:
    title:                             'My api'
    description:                       'blabla'
    formats:
        jsonld:                        ['application/ld+json']
        json:                          ['application/json']
        xml:                           ['application/xml', 'text/xml']
        csv:                           ['text/csv']
        html:                          ['text/html']

    eager_loading:
        fetch_partial: true
    collection:
        order_parameter_name:          'order'
        order:                         'ASC'
        pagination:
            client_enabled:            true
            client_items_per_page:     true
            items_per_page:            10
    enable_swagger: true
    enable_swagger_ui: true
```

**Comment by dmeziere** [comment]
Ok, I will have a lot to read, now :) This was my very first steps with this bundle, so for the moment this seems like a Norvegian picture with Japanese subtitles :)

The doc says that no configuration is mandatory, so I thought my existing code would still work when adding the bundle. The problem is that I don't really have any problem width the API, it is working well. It's all the existing work that break when I activate the bundle. Is API-platform exclusive ? I mean can I still use my application the way it worked before adding the bundle ? Or must I make a new project from scratch using only the API ?

**Comment by dmeziere** [comment]
Soyuka: I have not added any api_platform directive in my conf for now. I just wanted to check that my existing application worked after adding api platform, for a start.

**Comment by dunglas** [comment]
It should work out of the box without config. There is something weird here. It would be nice to have a way to test and debug :)

**Comment by dmeziere** [comment]
Unfortunately this is a proprietary application, top-secret marketkiller shit. I think I can give you the complete list of used bundles without getting fired, not that i wouldn't like to.

```
    "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "3.2.*",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/swiftmailer-bundle": "^2.3.10",
        "symfony/monolog-bundle": "^3.0.2",
        "symfony/polyfill-apcu": "^1.0",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "twig/twig": "^1.0||^2.0",
        "friendsofsymfony/user-bundle": "dev-master",
        "api-platform/core": "^2.0"

```

**Comment by dmeziere** [comment]
Maybe if I could call you and discuss in French about what I think i've understood about api-platform, and why i choosed to try it, I could save some time. The question is have you got a quarter of hour to loose talking to a depressive parisian dev ;)

**Comment by dunglas** [comment]
@dmeziere we can talk on the #french or #api-platform channel of the Symfony's Slack: http://symfony.com/slack-invite

**Comment by dunglas** [comment]
And do you think you'll be able to create a [MVCE](https://stackoverflow.com/help/mcve) without including the secret elements?

**Comment by Simperfit** [comment]
@dmeziere It should be working anyway. What are the bugs do you have with you're app ?

**Comment by dmeziere** [comment]
I've tested with creating an api-platform project, instead of starting from an existing code that I didn't made. Everything seems to work fine. I guess there was an invisible problem in the existing code, that Api platform only raised.
