### ISSUE TITLE
nginx and FastCGI - "Primary script unknown"

### ISSUE THREAD

**Issue by renan-taranto** [api-platform/api-platform#319]
Hi,

I've just downloaded the framework from the master branch and after running ```docker-compose up -d```, I got the following error when requesting for ```http://localhost```:
```
nginx_1  | 2017/06/01 12:25:31 [error] 7#7: *11 FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream, client: 172.18.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.18.0.4:9000", host: "localhost"
```
nginx returns a 404 status code response with the text "File not found" in the content.

Im using Linux. Any ideas?

**Comment by teohhanhui** [comment]
I've just tried it but unable to reproduce. Can you provide more info?

**Comment by renan-taranto** [comment]
Sure @teohhanhui 

Im using:
1. Linux Mint Rosa 17.3 64bit
2. docker-compose version 1.14.0-rc1
3. Docker version 17.04.0-ce, build 4845c56

Here's everything I did:
1. From the master branch I downloaded the zip ```api-platform-master.zip``` and extracted it
2. Ran ```$ docker-compose up -d``` and the output was:  https://gist.github.com/renan-taranto/cad044c5df8ed1de1ababd6e74b595c4
3. After building I opened Chromium and navigated to ```http:\\localhost\app_dev.php```
4. I ran ```docker-compose logs -f``` and the output was
https://gist.github.com/renan-taranto/d262a2cdf57c6137099d939ef77e4836

Let me know if I can provide more info.

**Comment by teohhanhui** [comment]
You seem to have a file permissions problem. Hmm...

**Comment by Simperfit** [comment]
With what user are you running docker ? and what are the perms on the files ?

**Comment by renan-taranto** [comment]
@Simperfit I'm running with the linux mint "standard" user account which has sudo privileges. I'm used to run dockerized apps with compose using this account so I'm not sure if the problem is my local setup.

Today I downloaded the project from the master branch again and varnish breaks due to permissions:
```varnish_1  | Error: Cannot read -f file (/etc/varnish/default.vcl): Permission denied```

**Comment by teohhanhui** [comment]
There is no need to run with `sudo`, because obviously your user is in the `docker` group, otherwise it wouldn't have worked...

https://docs.docker.com/engine/installation/linux/linux-postinstall/

But also, this is probably hard for us to troubleshoot unless someone has a similar setup and can investigate.

Just off the top of my head, perhaps you are using user namespaces? https://docs.docker.com/engine/reference/commandline/dockerd/#daemon-user-namespace-options

**Comment by renan-taranto** [comment]
@teohhanhui I mentioned I had no success even with ```sudo``` because I was asked about the user I was using to run it and about permissions.
Not using user namespaces.

**Comment by Simperfit** [comment]
@renan-taranto  what are the permissions on the varnish vcl ?

**Comment by renan-taranto** [comment]
@Simperfit 

    renan@taranto ~/projects/api-platform-master/docker/varnish/conf $ ls -la
    total 12
    drwx------ 2 renan renan 4096 Jun  6 22:00 .
    drwx------ 3 renan renan 4096 Jun  6 22:00 ..
    -rw-r--r-- 1 renan renan 1934 Jun  6 15:53 default.vcl

**Comment by renan-taranto** [comment]
Yeah, it is related to file permissions. I did the following tests:
- `$ chmod a+rwx docker/varnish/conf/default.vcl` "solves" the varnish error and gives me the ``` FastCGI - "Primary script unknown"``` error back again;
- `$ chmod a+rwx -R api-platform-master/` "solves" both problems and the app works.

**Comment by teohhanhui** [comment]
Do you have SELinux enabled? That's the only similar symptom that I can find...

See https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker and http://www.projectatomic.io/blog/2016/03/dwalsh_selinux_containers/

Otherwise, I'm not sure what problem you're running into. But you're on very old Linux kernel (3.19), right?

**Comment by teohhanhui** [comment]
Oh, okay. It's actually a problem with the .zip archive. I'd suggest you do a `git clone` instead (as you should). You could also use the tarball (.tar.gz).

**Comment by renan-taranto** [comment]
Cloning instead of downloading the zip solves. Thanks.
