### ISSUE TITLE
support propel

### ISSUE THREAD

**Issue by karser** [api-platform/api-platform#32]
Hello, does api-platform support propel?

```
enjoy the popular Doctrine ORM (used by default, but fully optional: you can use the data provider you want, including but not limited to MongoDB ODM and ElasticSearch)
```

**Comment by dunglas** [comment]
Hi,

it doesn't actually but it can. It's just a matter of implementing the `DataProvider` interface, an event listener to save hydrated entities and optionally a bridge with the Symfony PropertyInfo component.

If you are interested in working on this, you can take a look at how it's done for Doctrine: https://github.com/dunglas/DunglasApiBundle/tree/1.0/Doctrine

**Comment by Simperfit** [comment]
Closing this since it's outdated.
@karser You can create an issue on api-platform/core or a PR if you want to integrate it ;).
