### ISSUE TITLE
FOSUser Bundle Integration error

### ISSUE THREAD

**Issue by summermick** [api-platform/api-platform#321]
Can someone update--elaborate the FOSUser Bundle Integration instructions or share a starter git?

I followed the instructions from symfony website and got this error
`PHP Fatal error:  Uncaught Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: Unrecognized option "csrf_provider" under "security.firewalls.main.form_login" `

After googling for solution on their github issues, I changed csrf_provider to csrf_token_generator, then 
` PHP Fatal error:  Uncaught Symfony\Component\Config\Definition\Exception\InvalidConfigurationException: The child node "from_email" at path "fos_user" must be configured.`

**Comment by Simperfit** [comment]
I think that means that from_email is a mandatory parameters in order to use FosUserBundle. You should follow the documentation directly on the [fosUserBundle](https://github.com/FriendsOfSymfony/FOSUserBundle) github.

**Comment by summermick** [comment]
I did followed the `documentation directly on the fosUserBundle github` and got the error

**Comment by summermick** [comment]
I'm using 1.3 version, the issue fixed by using 2.0
but now the new models other than Foo don't show at all.
