### ISSUE TITLE
Extract common features from normalizer to be able to decorate them easily

### ISSUE THREAD

**Issue by Lyrkan** [api-platform/api-platform#323]
Currently JSON and JSON-LD are handled by two different normalizers, both of them extending `ApiPlatform\Core\Serializer\AbstractItemNormalizer`.

I wanted to add/modify properties on one of my resources (eg. setting URLs for images managed by LiipImagineBundle) and could not find a way to do it without decorating both `api_platform.serializer.normalizer.item` and `api_platform.jsonld.normalizer.item`:

```php
    app.normalizer.image:
        class: AppBundle\Serializer\ImageNormalizer
        decorates: 'api_platform.serializer.normalizer.item'
        arguments:
            - '@app.normalizer.image.inner'
            (...)

    app.normalizer.jsonld.image:
        class: AppBundle\Serializer\ImageNormalizer
        decorates: 'api_platform.jsonld.normalizer.item'
        arguments:
            - '@app.normalizer.jsonld.image.inner'
            (...)
```

Wouldn't it make sense to have a common item normalizer injected in every other item normalizers and be able to only decorate that one?

**Comment by Simperfit** [comment]
Hey @Lyrkan,
Thanks for using Api-Platform,

There are two different normalizer, they are not giving you the same result for a giving resource.

Why do you need to decorate both ? What happens if you are not doing it ?

**Comment by Lyrkan** [comment]
Hi @Simperfit,

I understand that they are two different normalizers, but even if they don't yield the same result they still have a lot of common points (hence the `AbstractItemTransformer` they currently share).


Let's say you have an API that supports both JSON and JSON-LD with a resource that has to be modified the same way in both representations (as an example: adding a computed value).

* If you only decorate `api_platform.serializer.normalizer.item`: The computed value will not be present in the response if the client requests the JSON-LD representation
* If you only decorate `api_platform.jsonld.normalizer.item` : The computed value will not be present in the response if the client requests the JSON representation

Having a common `ItemNormalizer` injected into and used by both JSON and JSON-LD `ItemNormalizer` would be a way to allow to handle that kind of case.

**Comment by Simperfit** [comment]
WDYT @api-platform/core-team ?

**Comment by teohhanhui** [comment]
JSON and JSON-LD are two different formats. I don't see why it's a problem if you have to decorate both normalizers separately. :smile:

**Comment by Lyrkan** [comment]
There is no problem per-se but it can become really verbose really fast.

In my previous posts I was only talking about JSON and JSON-LD with one decorator applied twice.

Now imagine you also want to support JSON-HAL (since it also uses the `normalize` method of the `AbstractItemNormalizer`). It means that you'll have to decorate that normalizer too if you want your computed properties to be in the response object.

Then you may want to have another decorators to handle `n`  other resource types. You now have `n * 3` declarations in your `services.yml` instead of just `n`.

**Comment by soyuka** [comment]
IMO it's a good separation of concern. Those normalizers are handling completely different formats. I agree about the verbose argument, though keeping those separated is still better in terms of maintainability and composition.

**Comment by Lyrkan** [comment]
@soyuka Wouldn't it be possible to keep the normalizers separated but still having a "base" normalizer used by all of them ?

There is already a big part of the code that is shared between them (`ApiPlatform\Core\Serializer\AbstractItemNormalizer`) so at first I was expecting something like:

* `api_platform.serializer.normalizer.item`: do the common things, basically what AbstractItemNormalizer does nowadays
* `api_platform.json.normalizer.item`: uses `api_platform.serializer.normalizer.item` (the same way he called parent::denormalize at the end of its own denormalize method) and does specific things
* `api_platform.jsonld.normalizer.item`: same thing but with jsonld specific parts
* `api_platform.hal.normalizer.item`: same thing but with hal specific parts

That would still allow people to only decorate json/jsonld/hal normalizers if needed, or decorate the common normalizer for properties that must be added/modified in every formats.

**Comment by teohhanhui** [comment]
If we can find a way of refactoring to extract out common functionality, I say go ahead. :smile:

**Comment by Simperfit** [comment]
I'm closing here, as this doesn't get anymore feedbacks, feel free to create an RFC in the core or to create directly a PR.
