### ISSUE TITLE
Install with Composer

### ISSUE THREAD

**Issue by sebastienhouzet** [api-platform/api-platform#324]
Hello all :)

I have test your tuto for create project in 5 minutes. I have remarks about the installation with Composer.

Firt, your have Notice on install.
<img width="1115" alt="notices" src="https://user-images.githubusercontent.com/2550639/26871670-45ac9ae8-4b74-11e7-8d8d-afdd92e6adfe.png">

Second, when all is install, i launch the website http://127.0.0.1:8000.
SwaggerUI not load. Only texte result is sended.

<img width="497" alt="swagger" src="https://user-images.githubusercontent.com/2550639/26871763-8e04978c-4b74-11e7-8b71-cdf1bf476933.png">

I work on MAC OS SIERRA with APACHE 2 and PHP 5.6.30.
Composer last version
API-Plateforme via composer : composer create-project api-platform/api-platform bookshop-api

Thx for you plateforme :)

Seb

**Comment by Simperfit** [comment]
Hey @sebastienhouzet,

Thank you for using ApiPlatform,

Using PHP 5 bring you to the version 1.1 of api-platform which does not contain swagger-ui and we advice you to better use directly the version 2.0 which contains a lot improvements.

In order to use ApiPlatform 2.0 you should use PHP 7.

**Comment by sebastienhouzet** [comment]
Perfect 👍 

For people use MAMP PRO, you cant found this article to help you to use PHP 7.X on CLI.

https://gist.github.com/irazasyed/5987693

Thx :)
