### ISSUE TITLE
Web container crashes on first install with docker

### ISSUE THREAD

**Issue by vbourdeix** [api-platform/api-platform#326]
Following the documentation, I downloaded the last version (2.0.8 as I'm writing this) and was happy to have docker all configured to start working quickly.

But when running docker-compose up, the database container runs, then the web container crashes with the following message : 
![docker-issue](https://user-images.githubusercontent.com/245785/26884133-53bf49b6-4b9f-11e7-9134-5c67ad6557de.png)

web_1       |  [OK] All assets were successfully installed.
web_1       |
web_1       | > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
web_1       | > Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
web_1       | + rm -f /var/run/apache2/apache2.pid
web_1       | + exec docker/apache/start_safe_perms -DFOREGROUND
web_1       | AH00526: Syntax error on line 1 of /etc/apache2/apache2.conf:
web_1       | Error:\tApache has not been designed to serve pages while\n\trunning as root.  There are known race conditions that\n\twill allow any local user to read any file on the system.\n\tIf you still desire to serve pages as root then\n\tadd -DBIG_SECURITY_HOLE to the CFLAGS env variable\n\tand then rebuild the server.\n\tIt is strongly suggested that you instead modify the User\n\tdirective in your httpd.conf file to list a non-root\n\tuser.\n
web_1       | Action '-DFOREGROUND' failed.
web_1       | The Apache error log may have more information.
hobbeesapi_web_1 exited with code 1

For information, I'm running it on windows 10 pro.

**Comment by Simperfit** [comment]
Are you using docker for windows ?

or a VM (docker-machine) ?

**Comment by vbourdeix** [comment]
I'm using Docker CE for Windows

**Comment by teohhanhui** [comment]
I think it's a problem with git CRLF conversion. Set in your `.gitattributes` to always normalize to LF:

```
text eol=lf
```

https://help.github.com/articles/dealing-with-line-endings/

**Comment by vbourdeix** [comment]
I tried to add a .gitattributes with text eol=lf but that didn't change anything for me.

With the v2.1.0-beta.2, the setup is different and works like a charm. Seems like I'll stick with this version.

**Comment by Simperfit** [comment]
@vbourdeix I think both case should be working now :)

**Comment by garbus** [comment]
Hi guys.

Tried to install api platform stable (v 2.0.10 - https://github.com/api-platform/api-platform/releases/tag/v2.0.10 ) @ Docker CE ( Version 17.06.0-ce-win19 (12801) Channel: stable ) and got same error.

Tried to play with LF EOL but it does't help.

What is the solution for me?

Thanks!

**Comment by Simperfit** [comment]
Could you please post the stack trace ?

**Comment by garbus** [comment]
Hi @Simperfit,

Thanks for quick answer.

Actually I used api-platform-2.1.0-beta.3 and it started correctly.

Now I have another problem though:
docker-compose exec web bin/console doctrine:schema:create
No such service: web

This will be the right issue to continue fighting with this: https://github.com/api-platform/api-platform/issues/265

Thanks once again!

**Comment by sbacem** [comment]
The doc of api-platform not update use `app ` not `web`
