### ISSUE TITLE
extends class vendor in src

### ISSUE THREAD

**Issue by angelzeke** [api-platform/api-platform#329]
Hi everybody, 

I would like to retrieve a project with a bundle in vendor and expose some class by extending in src directory but they did not on swagger

namespace ArianeBundle\Entity;

use ApiPlatform\Core\Annotation\ApiProperty;
use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use VendorBundle\Entity\Class;

// in SRC directory
/**
 * srcClass
 * @ORM\Table(name="table")
 * @ORM\Entity
 * @ORM\DiscriminatorMap({
 *     srcClass=srcClass,
 *     VendorClass='srcClass,
 * })
 * @ApiResource()
 */

class srcClass extends VendorClass
{

}
 // in vendor Directory
class VendorClass
{
// method to expose
}

**Comment by angelzeke** [comment]
someone have a idea, when i test in postman it's return null and when i put propriety on extends class it's work

**Comment by Simperfit** [comment]
Could you please do the following ? 

- Fork the [API Platform Standard Edition](https://github.com/api-platform/api-platform)
- Do the minimum modification to reproduce the bug
- Post the link in here

We will test that and confirm.

**Comment by angelzeke** [comment]
After update with standart edition it's work well, i just have this error in some class
"A circular reference has been detected (configured limit: 1)."

`class Article
{
        /**
         *
         * @ORM\ManyToOne(targetEntity="Journal")
         * @ORM\JoinColumn(name="ART", referencedColumnName="ID")
         */
    private $journal;
}

class Journal
{
class Article
{
      /**
     * @ORM\OneToMany(targetEntity="Article", mappedBy="journal")
     *
     **/
    private $articles;
}
}
`
