### ISSUE TITLE
Question: Sanitize API consumer input - line break CRLF/LF conversion

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/api-platform#33]
I'm thinking of what is the best way to handle this... Let's say I want to normalize all line breaks on the server side, how would I achieve it using Symfony Serializer?

Any other suggestions for best practices are welcome...

**Comment by dunglas** [comment]
I don't understand what you're trying to do exactly. Changing line breaks in a JSON document?

**Comment by theofidry** [comment]
Windows –> NIX:
```
tr -d '\r' < windowsfile > nixfile // delete the carriage returns
```

Mac –> NIX: 
```
tr '\r' '\n' < macfile > nixfile // translate carriage returns into newlines
```

NIX –> Mac: 
```
tr '\n' '\r' < macfile > nixfile // translate newlines into carriage returns
```

If you want to do that in Git you can simply configure your git return line and do a `git add -A`. If you absolutely need to do that in PHP look for the carriage return character and replace it manually.

Can't really help much more as I have no idea of what your use case is...

**Comment by teohhanhui** [comment]
I'm not talking about source files but HTTP entity body (in JSON, for example). This question is about sanitizing user (API consumer) input.

**Comment by teohhanhui** [comment]
Windows browsers are required by HTML spec to normalize line breaks as CRLF during form submission. Not exactly our use case here, but I hope you get my point...

**Comment by dunglas** [comment]
You mean the value of a textarea encoded in a JSON document or something like that?

**Comment by teohhanhui** [comment]
@dunglas

> You mean the value of a textarea encoded in a JSON document or something like that?

Yes.

**Comment by Simperfit** [comment]
@teohhanhui What could we do about this ?

**Comment by teohhanhui** [comment]
I'm not sure, to be honest. This is an open question to hear the experiences of others and how they deal with the problem.

**Comment by Simperfit** [comment]
As this don't get any feedback, i'm closing here. Maybe we could create a proposal on the core repository ?
