### ISSUE TITLE
Create images on docker hub instead of relying on Dockerfile

### ISSUE THREAD

**Issue by akira28** [api-platform/api-platform#334]
It would be nice to create custom api-platform docker images on docker hub for "app" and "varnish", as almost everything defined in Dockerfile for both could be reused on other Symfony projects. The separation would also clean up the api-platform repo.

**Comment by teohhanhui** [comment]
Upon further consideration, I don't see the benefit of separating it into separate code repositories (and it's not really doable because we need to copy project files when building the image). But I'm still for (automated) build and push of the Docker images, for a much faster bootstrapping.

**Comment by dunglas** [comment]
@teohhanhui I'm refactoring images for Flex. It's almost ready (https://github.com/dunglas/symfony-docker-skeleton/pull/5 if you want to take a look). I agree it has no benefit to split the project.

**Comment by teohhanhui** [comment]
Yes, I love Flex and I'm using it. But it's still considered experimental. In the meantime, we can automate the build for this repository.

**Comment by Simperfit** [comment]
Thanks to @teohhanhui this has been merged ;). Not on docker hub, but still online.
