### ISSUE TITLE
How I can to debug pagination?

### ISSUE THREAD

**Issue by indapublic** [api-platform/api-platform#336]
I have some entity with filter and pagination.

> /items?category=7a93364b-4cc0-11e7-8ba8-f23c9160bfdb

> /items?category=7a93364b-4cc0-11e7-8ba8-f23c9160bfdb&page=2

Both pages return the same (but page=3 works)
But If will remove filtering, pages will have different response

Cannot find a reason of this behaviour. So how I can to debug pagination?

**Comment by dunglas** [comment]
Do you use the Varnish cache @indapublic?

**Comment by indapublic** [comment]
@dunglas Probably not, cannot find it in project (sorry, it's a legacy code)

**Comment by indapublic** [comment]
If I'm using `pagination_items_per_page` = 4, output is different.
If `pagination_items_per_page` = 5, outputs are same except last item
Cannot find a reason

**Comment by dunglas** [comment]
There is probably a cache layer somewhere.

**Comment by indapublic** [comment]
Tried clear the cache, off course. All the same. On remote and local machines.

> "symfony/symfony": "3.2.*",
> "api-platform/core": "^2.0",

**Comment by soyuka** [comment]
may be related to #1185 

>  But If will remove filtering, pages will have different response

this would unconfirm #1185 ? We may need more data, the best would be a case reproduction in a behat test on the api-platform/core repository.

**Comment by indapublic** [comment]
@soyuka Hydra data looks correct, `hydra:totalItems` is correct.

**Comment by indapublic** [comment]
Removed all items with category != 7a93364b-4cc0-11e7-8ba8-f23c9160bfdb
So I testing now without any filter, only pagination. Result is same, I have same items for first and second page.

**Comment by indapublic** [comment]
Tried recreate (with single entity) from scratch - all works :(

**Comment by indapublic** [comment]
Closing now. Inspected logs and found a strange behaviour in Mysql (you can read [here](https://stackoverflow.com/questions/44690859/identical-records-in-two-subqueries-using-limit-and-offset))

**Comment by indapublic** [comment]
So I reopened topic

**Comment by indapublic** [comment]
I inspected sql logs, api-platform using this sql for pagination:

`[2017-06-22 02:47:35] doctrine.DEBUG: SELECT DISTINCT a0_.id AS id_0, a0_.created_at AS created_at_1 FROM app_item a0_ WHERE a0_.published = 1 ORDER BY a0_.created_at DESC LIMIT 5 OFFSET 5 [] []`

Want to be sure it's correct

**Comment by indapublic** [comment]
you can download and export [this dump](https://gist.github.com/indapublic/689f00dbdcf8c75f5557f28b29c50933) and check:

```
select
  *
from
  (
    select distinct id, created_at from aaa order by created_at desc limit 5 offset 0
  ) a,
  (
    select distinct id, created_at from aaa order by created_at desc limit 5 offset 5
  ) b
where a.id = b.id
```

both subqueries return duplicate records
