### ISSUE TITLE
Custom GET item without to have to specify id

### ISSUE THREAD

**Issue by Sybio** [api-platform/api-platform#337]
I'm trying to create a custom action which could be called at GET `/me`.

I implemented JWT token and now I want to get the user data thanks to the security storage or something else (by Bearer or something else).

My problem is that I can't create a custom action to **get just one item but without giving an ID**. It seems ApiPlatform is built to always listen ID parameter for item action, when we use *_api_item_operation_name*.

Action :
```php
<?php

namespace AppBundle\Action;

use AppBundle\Repository\UserRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\Config\Definition\Exception\Exception;
use Symfony\Component\Routing\Annotation\Route;
use AppBundle\Entity\User;
use Doctrine\Common\Persistence\ManagerRegistry;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage;

class UserMe
{
    /**
     * @var UserRepository
     */
    private $repository;

    /**
     * UserMe constructor.
     *
     * @param UserRepository $repository
     */
    public function __construct(UserRepository $repository)
    {
        $this->repository= $repository;
    }

    /**
     * @Route(
     *     name="api_users_me",
     *     path="/me",
     *     defaults={"_api_resource_class"=User::class, "_api_item_operation_name"="user_me"}
     * )
     * @Method("GET")
     */
    public function __invoke($data)
    {
        // hard retrieve of an existing user in database to test
        return $this->repository->find(5);
    }
}
```
Result : 
```json
{
    "@context": "/app_dev.php/contexts/Error",
    "@type": "hydra:Error",
    "hydra:title": "An error occurred",
    "hydra:description": "Invalid identifier \"\", \"id\" has not been found.",
    ...
}
```

If you see, I don't need to specify an "id" for my action, but API Plateform is expecting an identifier "id".

Here my User entity : 
```php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * User
 *
 * @ApiResource(
 *     collectionOperations={
 *         "get"={
 *             "method"="GET",
 *             "normalization_context"={"groups"={"get_collection"}}
 *         },
 *     },
 *     itemOperations={
 *         "get"={
 *             "method"="GET",
 *             "normalization_context"={"groups"={"get_item"}}
 *         },
 *         "user_me"={
 *             "route_name"="api_users_me"
 *         },
 *     }
 * )
 * @ORM\Table(name="user")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
 */
class User implements AdvancedUserInterface
{
    // ...
}
```

In addition, here a router debug:
```bash
------------------------------------------- -------- -------- ------ ---------------------------------------
  Name                                        Method   Scheme   Host   Path
 ------------------------------------------- -------- -------- ------ ---------------------------------------
  _wdt                                        ANY      ANY      ANY    /_wdt/{token}
  _profiler_home                              ANY      ANY      ANY    /_profiler/
  _profiler_search                            ANY      ANY      ANY    /_profiler/search
  _profiler_search_bar                        ANY      ANY      ANY    /_profiler/search_bar
  _profiler_info                              ANY      ANY      ANY    /_profiler/info/{about}
  _profiler_phpinfo                           ANY      ANY      ANY    /_profiler/phpinfo
  _profiler_search_results                    ANY      ANY      ANY    /_profiler/{token}/search/results
  _profiler_open_file                         ANY      ANY      ANY    /_profiler/open
  _profiler                                   ANY      ANY      ANY    /_profiler/{token}
  _profiler_router                            ANY      ANY      ANY    /_profiler/{token}/router
  _profiler_exception                         ANY      ANY      ANY    /_profiler/{token}/exception
  _profiler_exception_css                     ANY      ANY      ANY    /_profiler/{token}/exception.css
  _twig_error_test                            ANY      ANY      ANY    /_error/{code}.{_format}
  api_entrypoint                              ANY      ANY      ANY    /{index}.{_format}
  api_doc                                     ANY      ANY      ANY    /docs.{_format}
  api_jsonld_context                          ANY      ANY      ANY    /contexts/{shortName}.{_format}
  api_bookmakers_get_collection               GET      ANY      ANY    /bookmakers.{_format}
  api_bookmakers_get_item                     GET      ANY      ANY    /bookmakers/{id}.{_format}
  api_categories_get_collection               GET      ANY      ANY    /categories.{_format}
  api_categories_get_item                     GET      ANY      ANY    /categories/{id}.{_format}
  api_comments_get_collection                 GET      ANY      ANY    /comments.{_format}
  api_comments_post_collection                POST     ANY      ANY    /comments.{_format}
  api_comments_get_item                       GET      ANY      ANY    /comments/{id}.{_format}
  api_feed_items_get_collection               GET      ANY      ANY    /feed_items.{_format}
  api_feed_items_post_collection              POST     ANY      ANY    /feed_items.{_format}
  api_feed_items_get_item                     GET      ANY      ANY    /feed_items/{id}.{_format}
  api_feed_items_put_item                     PUT      ANY      ANY    /feed_items/{id}.{_format}
  api_follows_get_collection                  GET      ANY      ANY    /follows.{_format}
  api_follows_post_collection                 POST     ANY      ANY    /follows.{_format}
  api_follows_get_item                        GET      ANY      ANY    /follows/{id}.{_format}
  api_follows_delete_item                     DELETE   ANY      ANY    /follows/{id}.{_format}
  api_moderation_cards_get_collection         GET      ANY      ANY    /moderation_cards.{_format}
  api_moderation_cards_get_item               GET      ANY      ANY    /moderation_cards/{id}.{_format}
  api_picks_get_collection                    GET      ANY      ANY    /picks.{_format}
  api_picks_post_collection                   POST     ANY      ANY    /picks.{_format}
  api_picks_get_item                          GET      ANY      ANY    /picks/{id}.{_format}
  api_picks_put_item                          PUT      ANY      ANY    /picks/{id}.{_format}
  api_report_picks_post_collection            POST     ANY      ANY    /report_picks.{_format}
  api_subpicks_get_collection                 GET      ANY      ANY    /subpicks.{_format}
  api_subpicks_post_collection                POST     ANY      ANY    /subpicks.{_format}
  api_subpicks_get_item                       GET      ANY      ANY    /subpicks/{id}.{_format}
  api_subpicks_put_item                       PUT      ANY      ANY    /subpicks/{id}.{_format}
  api_subpick_type_events_get_item            GET      ANY      ANY    /subpick_type_events/{id}.{_format}
  api_subpick_type_frees_get_item             GET      ANY      ANY    /subpick_type_frees/{id}.{_format}
  api_subscribed_bookmakers_get_collection    GET      ANY      ANY    /subscribed_bookmakers.{_format}
  api_subscribed_bookmakers_post_collection   POST     ANY      ANY    /subscribed_bookmakers.{_format}
  api_subscribed_bookmakers_get_item          GET      ANY      ANY    /subscribed_bookmakers/{id}.{_format}
  api_subscribed_bookmakers_delete_item       DELETE   ANY      ANY    /subscribed_bookmakers/{id}.{_format}
  api_users_get_collection                    GET      ANY      ANY    /users.{_format}
  api_users_post_collection                   POST     ANY      ANY    /users.{_format}
  api_users_get_item                          GET      ANY      ANY    /users/{id}.{_format}
  api_users_put_item                          PUT      ANY      ANY    /users/{id}.{_format}
  api_user_likes_get_collection               GET      ANY      ANY    /user_likes.{_format}
  api_user_likes_post_collection              POST     ANY      ANY    /user_likes.{_format}
  api_user_likes_get_item                     GET      ANY      ANY    /user_likes/{id}.{_format}
  api_user_likes_delete_item                  DELETE   ANY      ANY    /user_likes/{id}.{_format}
  api_login_check                             ANY      ANY      ANY    /login_check
  api_jwt_refresh_token                       ANY      ANY      ANY    /token/refresh
  api_users_me                                GET      ANY      ANY    /me
 ------------------------------------------- -------- -------- ------ ---------------------------------------
```
The route is here.

Documentation also generate a required "id" field, while i don't want it : 
![Users actions](http://oi63.tinypic.com/2iu6nwx.jpg)

I also tried to "cheat" by using "_api_collection_operation_name", and redapt User correctly, but i got an "Illegal offset" error even if i return an array containing the User in method `__invoke($data)`

Do you have a solution ? Anyway, thanks for this useful bundle !

**Comment by dunglas** [comment]
You need to create custom operations (https://api-platform.com/docs/core/operations#creating-custom-operations-and-controllers).

But it's generally considered a bad practice to have such stateful-like URLs. You need to be extremely careful with all HTTP cache layers. It's generated preferred to build URLs like `/token/<the-user-id>` to have a unique URL per user.

**Comment by Sybio** [comment]
In fact this is what i've done in previous snippets.

Whatever i want to return, a void data, a User data, or other, the action always return : 
`"hydra:description": "Invalid identifier \"\", \"id\" has not been found.",`

So you confirm that implementing a custom item operation don't always require "id" parameter ? I'll search if there is a route override or another problem like that...

**Comment by Sybio** [comment]
Ok as you says here : https://github.com/api-platform/api-platform/issues/217#issuecomment-274026333
The `id` is mandatory.

The only solution i see is to change the logical of my app by returning the id of the user when i request the JWT token and then to use the idwith a more convential route like /users/{id}...

**Comment by Simperfit** [comment]
@Sybio Implementing a custom operation don't always require the id parameter, but as @dunglas said, it's bad practice. :)

**Comment by Sybio** [comment]
@Simperfit I understand that but I add some security (requiring the bearer) on `/me` action.

I'm confused because of the response i get when i request `/me`, which requires an "id" parameter even if i don't specify it :s : `path="/me",`

If you have the solution, it would be great ;)

**Comment by Sybio** [comment]
Even if it doesn't respect the REST philosophy, I paste my solution for the ones who need to implement a similar action like `/me`:

Action:
```php
<?php

namespace AppBundle\Action;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\Config\Definition\Exception\Exception;
use Symfony\Component\Routing\Annotation\Route;
use AppBundle\Entity\User;
use Doctrine\Common\Persistence\ManagerRegistry;

class UserMe
{
    /**
     * @Route(
     *     name="api_users_me",
     *     path="/me",
     *     defaults={"_api_resource_class"=User::class, "_api_item_operation_name"="user_me"}
     * )
     * @Method("GET")
     * @return User|null
     */
    public function __invoke($data)
    {
        // Return the User object
        return $data;
    }
}
```
Provider:
```php
<?php

namespace AppBundle\DataProvider;

use AppBundle\Entity\User;
use ApiPlatform\Core\DataProvider\ItemDataProviderInterface;
use ApiPlatform\Core\Exception\ResourceClassNotSupportedException;
use AppBundle\Repository\UserRepository;
use Symfony\Component\HttpFoundation\RequestStack;
use Symfony\Component\Routing\Router;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorage;

final class UserItemDataProvider implements ItemDataProviderInterface
{
    /**
     * @var UserRepository
     */
    private $repository;

    /**
     * @var TokenStorage
     */
    private $tokenStorage;

    /**
     * @var RequestStack
     */
    private $request;

    /**
     * UserMe constructor.
     *
     * @param UserRepository $repository
     * @param TokenStorage   $tokenStorage
     * @param RequestStack   $request
     */
    public function __construct(UserRepository $repository, TokenStorage $tokenStorage, RequestStack $request)
    {
        $this->repository   = $repository;
        $this->tokenStorage = $tokenStorage;
        $this->request      = $request;
    }

    /**
     * @param string      $resourceClass
     * @param int|string  $id
     * @param string|null $operationName
     * @param array       $context
     *
     * @return User|null
     * @throws ResourceClassNotSupportedException
     */
    public function getItem(string $resourceClass, $id, string $operationName = null, array $context = [])
    {
        if (User::class !== $resourceClass) {
            throw new ResourceClassNotSupportedException();
        }

        // retrieves User from the security (no id needed)
        if ('api_users_me' === $this->request->getMasterRequest()->get('_route')) {
            return $this->tokenStorage->getToken()->getUser()->getId();
        }

        return $this->repository->find($id); // Retrieves User normally for other actions
    }
}
```

**Comment by dunglas** [comment]
Thanks for sharing @Sybio! It would be nice to add this snippet in the docs as its a common request (we can add a warning explaining that its not recommended).

**Comment by Sybio** [comment]
With pleasure @dunglas, I'll write documentation soon on https://github.com/api-platform/docs

**Comment by dunglas** [comment]
Thanks a lot!

**Comment by olivermack** [comment]
Just in case someone comes across this and struggles with the same issue:

It's pretty important in which order the data providers are registered. Thus, if you want to specify your provider inside the services-configs of a certain bundle it will be registered after the default dataproviders coming from the core. I was facing that in a similar scenario where my route did not provide any `id` argument and during the doctrine data provider (`ApiPlatform\Core\Bridge\Doctrine\Orm\ItemDataProvider`) execution it just failed with an exception `Invalid identifier \"\", \"id\" has not been found.`.

Therefore, to add that info to the comment from @Sybio, ensure to configure the data provider inside the applications root services.yml at `app/config/services.yml`

**Comment by meyerbaptiste** [comment]
> Therefore, to add that info to the comment from @Sybio, ensure to configure the data provider inside the applications root services.yml at app/config/services.yml

@olivermack: Or simply use the `priority` tag attribute. For example:
```yaml
tags:
  -  { name: 'api_platform.item_data_provider', priority: 5 }
```

**Comment by videni** [comment]
this code looks very ugly , can api platform provider a better way?

**Comment by videni** [comment]
@Sybio, hi， I try your solution , but my UserItemDataProvider never executed
```
app.user.item_data_provider:
        class: App\Bundle\UserBundle\DataProvider\UserItemDataProvider
        public: true
        arguments:
            - '@App\Bundle\UserBundle\Repository\UserRepository'
            - '@security.token_storage'
        tags:
            -  { name: 'api_platform.item_data_provider' }
```

**Comment by videni** [comment]
also this solution will not work at v2.3.0 , the following will throw exception if no id found 
```
 try {
            $identifiers = $this->extractIdentifiers($request->attributes->all(), $attributes);

            if (isset($attributes['item_operation_name'])) {
                $data = $this->getItemData($identifiers, $attributes, $context);
            } elseif (isset($attributes['subresource_operation_name'])) {
                // Legacy
                if (null === $this->subresourceDataProvider) {
                    throw new RuntimeException('No subresource data provider.');
                }

                $data = $this->getSubresourceData($identifiers, $attributes, $context);
            }
        } 
```

**Comment by numediaweb** [comment]
Removing `_api_item_operation_name` fixed it to me:
before
```
...
    /**
     * @Route(
...
     *     defaults={
     *       "_controller"="\Example\ApiBundle\Controller\ApiRequestController::patchApiRequest",
     *       "_api_resource_class"="AppBundle\Entity\ApiRequest",
     *       "_api_item_operation_name"="patchApiRequest"
     *     }
...
```
After
```
...
    /**
     * @Route(
...
     *     defaults={
     *       "_controller"="\Example\ApiBundle\Controller\ApiRequestController::patchApiRequest",
     *       "_api_resource_class"="AppBundle\Entity\ApiRequest",
     *     }
...
```

**Comment by Napche** [comment]
You can also just use move your action to the collection_items, since there is no required id attribute there.
```
resources:
    App\Entity\User:
        attributes:
            normalization_context:
                groups: ['read']
            denormalization_context:
                groups: ['write']
        itemOperations:
            get: ~
            put: ~
        collectionOperations:
            get: ~
            profile:
                path: '/profile'
                controller: App\Action\UserProfileAction
                method: 'GET'
                normalization_context:
                    groups: ['profile']
                swagger_context:
                    public: false
                    tags: ['Authentication']
                    summary: "Returns the profile of the logged in user."
                    parameters:
                        -   name: 'Bearer'
                            required: true
                            in: 'header'
                            description: 'Active JWT Token'
                    responses:
                        200:
                            description: "json array with personal profile"
```

**Comment by tlorens** [comment]
> @Sybio Implementing a custom operation don't always require the id parameter, but as @dunglas said, it's bad practice. :)

Bad practice says who?   I need to find a user by username/email address and API Platform is preventing me from doing that.  Even a custom operation doesn't seem to want to work properly.  The API Platform documents are out of date as some annotation parameters don't require _ (underscores anymore).  Now I'm having issues with it autowiring the parameter for the action I'm calling __invoke(User $data).  I'm using v2.5 of core.   Maybe I'm going about this the wrong way.

**Comment by yusufbiberoglu** [comment]
I tried all for symfony 5 but doesnt work for me! Is there any other example?

**Comment by lamb0tiana** [comment]
> also this solution will not work at v2.3.0 , the following will throw exception if no id found
> 
> ```
>  try {
>             $identifiers = $this->extractIdentifiers($request->attributes->all(), $attributes);
> 
>             if (isset($attributes['item_operation_name'])) {
>                 $data = $this->getItemData($identifiers, $attributes, $context);
>             } elseif (isset($attributes['subresource_operation_name'])) {
>                 // Legacy
>                 if (null === $this->subresourceDataProvider) {
>                     throw new RuntimeException('No subresource data provider.');
>                 }
> 
>                 $data = $this->getSubresourceData($identifiers, $attributes, $context);
>             }
>         } 
> ```

I'm facing of this situation, and got same error!

**Comment by lamb0tiana** [comment]
> You can also just use move your action to the collection_items, since there is no required id attribute there.
> 
> ```
> resources:
>     App\Entity\User:
>         attributes:
>             normalization_context:
>                 groups: ['read']
>             denormalization_context:
>                 groups: ['write']
>         itemOperations:
>             get: ~
>             put: ~
>         collectionOperations:
>             get: ~
>             profile:
>                 path: '/profile'
>                 controller: App\Action\UserProfileAction
>                 method: 'GET'
>                 normalization_context:
>                     groups: ['profile']
>                 swagger_context:
>                     public: false
>                     tags: ['Authentication']
>                     summary: "Returns the profile of the logged in user."
>                     parameters:
>                         -   name: 'Bearer'
>                             required: true
>                             in: 'header'
>                             description: 'Active JWT Token'
>                     responses:
>                         200:
>                             description: "json array with personal profile"
> ```

yeah, but it's concern about a item not a collection,

**Comment by warslett** [comment]
The problem I'm having is that NuxtJS Authentication tells you to do exactly what @Sybio was trying to do here. https://auth.nuxtjs.org/schemes/local#options ie. you configure one endpoint to perform a login and return a token (this works just great with lexik jwt token bundle) and then another endpoint to get a single user object back using the bearer token on the request.

I'd be very happy calling /user/{id} instead as @dunglas suggests but if you are using JWT you don't **_have_** the ID. All you have is a token. My app cannot request the current user based on id if it doesn't know what the id is. Feels like what I'm trying to do should be really standard and straight forward but I'm not seeing anyway to match up what NuxtJS auth tells you to do and what API Platform wants you to do. Maybe there is a better way that should be added to documentation?

**Comment by silverbackdan** [comment]
You can decode your JWT token data for the ID, and if it is not there you could include the user ID - https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/2-data-customization.md

**Comment by warslett** [comment]
Thank you @silverbackdan for the super quick response yesterday. After a bit of shouting and swearing I have a working solution which I will share for anyone else clashing against this.

1. First I created an event listener to add the id (in my case ulid) to the JWT:
```php
<?php declare(strict_types=1);

namespace App\Listener\JWTCreated;

use App\Domain\Entity\User;
use Lexik\Bundle\JWTAuthenticationBundle\Event\JWTCreatedEvent;

class HydrateUserUlidListener
{
    public function __invoke(JWTCreatedEvent $event)
    {
        /** @var User $user */
        $user = $event->getUser();
        $data = $event->getData();
        $data['ulid'] = $user->getUlid();
        $event->setData($data);
    }
}
```

2. Next I registered the listener in services.php (or services.yaml if you use yaml):
```php
$services->set(\App\Listener\JWTCreated\HydrateUserUlidListener)
    ->tag('kernel.event_listener', ['event' => 'lexik_jwt_authentication.on_jwt_created']);
```

3. Then I installed jwt_decode https://www.npmjs.com/package/jwt-decode

4. Then I added a custom nuxt auth scheme by extending the local scheme provided by nuxt auth:
```javascript
// frontend/auth/CustomScheme.js

import { LocalScheme } from '@nuxtjs/auth-next/dist/runtime';
import jwt_decode from 'jwt-decode';

export default class AssessmentCentreScheme extends LocalScheme {

    async fetchUser (endpoint) {
        const tokenValue = this.$auth.$storage.getUniversal(this.options.token.prefix + this.name);
        if (!tokenValue) {
            return;
        }

        const tokenString = String(tokenValue);
        const token = jwt_decode(tokenString);

        try {
            const user = await this.$auth.ctx.app.$axios.$get(`/api/users/${token.ulid}`);
            await this.$auth.setUser(user);
        } catch (err) {
            console.log(err)
        }
    }
}

```

5. Then I configured nuxt to use my new scheme and set the user endpoint to false in my nuxt.config.js:
```javascript
export default {
    ...
    auth: {
        strategies: {
            custom: {
                scheme: '~/auth/CustomScheme.js',
                token: {
                    property: 'token',
                },
                endpoints: {
                    login: { url: '/api/auth/token', method: 'post' },
                    logout: false,
                    user: false
                }
            }
        }
    }
}
```

6. Now I can login correctly using the $auth.loginWith method.
```javascript
<template>
  <main>
    <div v-if="isAuthenticated">
      Logged in as {{ user.email }}
      <button v-on:click="logout">Logout</button>
    </div>
    <form @submit.prevent="login" v-else>
      <div>
        <label for="login-email">Email</label>
        <input id="login-email" type="text" v-model="credentials.email" />
      </div>
      <div>
        <label for="login-password">Password</label>
        <input id="login-password" type="password" v-model="credentials.password" />
      </div>
      <div>
        <button type="submit">Login</button>
      </div>
    </form>
  </main>
</template>

<script>
import { mapGetters } from 'vuex';

export default {

  data: function () {
    return {
      credentials: {
        email: '',
        password: ''
      }
    }
  },

  methods: {
    async login(event) {
      try {
        await this.$auth.loginWith('custom', { data: this.credentials });
      } catch (err) {
        console.log(err)
      }

      this.credentials.password = '';
    },

    async logout(event) {
      await this.$auth.logout();
    }
  },

  computed: {
    ...mapGetters(['isAuthenticated', 'user'])
  }
}
</script>
```

I just wish front end frameworks and backend frameworks could agree on the right way to do auth!

**Comment by silverbackdan** [comment]
No worries and nice share, the other option would be to have a `/me` endpoint on your API where you can fetch your user when you have a token and store that locally, using the `user` endpoint. But for that, in your API you'd need to configure such an endpoint. I've done that in an application of mine. This looks like it'll do the job as well though.

**Comment by dawe7** [comment]
I ApiPlatform 2.6.8 you can use:

```
#[ApiResource(
  itemOperations: [
      'user_me' => [
            'method' => 'GET',
            'route_name' => 'api_users_me',
            'identifiers' => []
        ],
```

And then the identifier is not in swagger.

**Comment by jordanyoungs** [comment]
Thank you @dawe7, your fix was simple and worked for me

**Comment by sujayjaju** [comment]
There seems to be no solution for this in V3
