### ISSUE TITLE
How to define custom POST operation in YAML?

### ISSUE THREAD

**Issue by dialogik** [api-platform/api-platform#338]
I want to create a custom `POST` operation. While this works well using annotations for the routing, I get stuck using YAML.

API resource definition

    # src/AppBundle/Resources/config/api_resources/resources.yml
    AppBundle\Entity\Foo:
        collectionOperations:
            get:
                method: 'GET'
            special:
                route_name: 'foo_special'

Routing

    # app/config/routing.yml
    foo_special:
        path: '/foo/special'
        methods:  ['POST']
        defaults:
            _api_resource_class: 'AppBundle\Entity\Foo'
            _api_collection_operation_name: 'special'

Error message:

> "hydra:description": "Unable to find the controller for path \"/foo/special\". The route is wrongly configured."

Any ideas what is wrong here?

(*As I didn't get any answer on my [question on StackOverflow](https://stackoverflow.com/questions/44519233/how-to-define-custom-post-operation-in-yaml) I addressed myself to this site.*)

  [1]: https://api-platform.com/

**Comment by soyuka** [comment]
Does the special route show up in `./bin/console debug:router`?

**Comment by dialogik** [comment]
Yes it does

    ...
    foo_special          POST          ANY          ANY          /foo/special
    ...

**Comment by meyerbaptiste** [comment]
`_controller` seems to be missing in `defaults`.

**Comment by dialogik** [comment]
There is no `Controller`, thus I cannot use

    defaults:
        _controller: 'AppBundle:Foo:special'

What is the notation for using an `Action`?

**Comment by meyerbaptiste** [comment]
If you use the ADR pattern (`Action` + `__invoke()` method), you have to define your controller as a service and then use the service name as controller. (i.e. `_controler: app.special_action` or `_controller: AppBundle\Action\Special`).

You can use annotations too, see https://api-platform.com/docs/core/operations#creating-custom-operations-and-controllers.

**Comment by dialogik** [comment]
Thank you!

I wanted to avoid using annotions as I like keeping my configuration in yml files. But since registering each action is required I think I'll stick with annotations.

**Comment by dialogik** [comment]
Maybe this could be precised in the documentation?

**Comment by meyerbaptiste** [comment]
It is in the Symfony documentation: https://symfony.com/doc/current/controller/service.html#invokable-controllers 😛 

Feel free to open a PR in the doc repo. 😉
