### ISSUE TITLE
Disable Hydra from my project?

### ISSUE THREAD

**Issue by lvillarino** [api-platform/api-platform#339]
Hi:

I want to know if I can disable Hydra from my project?

Thanks

**Comment by soyuka** [comment]
Meaning? 

You may want to use another format then jsonld, try `json` for example. [See here](https://api-platform.com/docs/core/content-negotiation#enabling-several-formats) for more informations on formats.

**Comment by lvillarino** [comment]
I try 'json' but the api don't return pagination values

hydra:totalItems
hydra:first
hydra:last
hydra:next

Thanks

**Comment by soyuka** [comment]
Maybe what you want is the JSON API spec, we're currently implementing this https://github.com/api-platform/core/pull/1175. You could give it a try by forking @meyerbaptiste branch :).

**Comment by Simperfit** [comment]
We have [jsonhal](http://stateless.co/hal_specification.html) too :).

**Comment by lvillarino** [comment]
Thanks
