### ISSUE TITLE
word_start, start and end filters doesn't exist yet

### ISSUE THREAD

**Issue by AdJez** [api-platform/api-platform#34]
Hi everybody, i'm using api-platform and it's a real time gain, thw a lot for this :)
However, i just have to say that your filters are include in the doc but doesn't eist into your app.

Best,
Adrien

**Comment by dunglas** [comment]
Yes, the doc of the 1.1 version is already online... It will be fixed soon by the release of this new version.

**Comment by petervdbroek** [comment]
Hi Dunglas,

Filters still not working?
Are you planning to update this?

Regards,

Peter
