### ISSUE TITLE
Remove  apiplatform/logo-header.svg from /docs

### ISSUE THREAD

**Issue by lvillarino** [api-platform/api-platform#341]
Hi

I want to know how I can remove the logo from the /docs

Thanks

**Comment by dunglas** [comment]
It's a plain old Twig template, you can override it: http://symfony.com/doc/current/templating/overriding.html

**Comment by lvillarino** [comment]
Hi:

I try to fallow the documentation but my template don't show up, Can you verify that this the correct path  app/Resources/api-platform/views/SwaggerUi/index.html.twi

Thanks

**Comment by lvillarino** [comment]
Thanks @madarco 

the correct path is app/Resources/ApiPlatformBundle/views/SwaggerUi/index.html.twig

**Comment by BenWaNH** [comment]
I have this path for Symfony 4 overriding : 
templates\bundles\ApiPlatformBundle\views\SwaggerUi\index.html.twig
but it doesn't work... nothing happens
Anyone know what is the correct path?
Thanks

**Comment by lasekmiroslaw** [comment]
Try this path:
templates/bundles/ApiPlatformBundle/SwaggerUi/index.html.twig

**Comment by BenWaNH** [comment]
Yes! Indeed!
I don't know how i could missed this : https://api-platform.com/docs/core/swagger/#overriding-the-ui-template
Thanks

**Comment by lougaou** [comment]
> Try this path: templates/bundles/ApiPlatformBundle/SwaggerUi/index.html.twig

```
{% extends '@!ApiPlatform/SwaggerUi/index.html.twig' %}

{% block stylesheet %}
    {{ parent() }}
    <style>
        .scheme-container {
            display: none;
        }
    </style>
{% endblock %}
```
