### ISSUE TITLE
Simple Post

### ISSUE THREAD

**Issue by speeeeeed2006** [api-platform/api-platform#348]
Hello, 
how to do an easy POST without using any entity. 
For example: 
sending in a json
`{
 x1:2,
 x2:5
}`
and made an operation like addition or log or kind of thing on that json?

**Comment by sawmurai** [comment]
Just add a custom Controller + route-configuration as you would in a non-api-platform Symfony project.

**Comment by speeeeeed2006** [comment]
I've done that just like the example but when I use $request->get('data'); nothing inside (null)

**Comment by Simperfit** [comment]
$data would be map to an entity, you should get the request body and check the json validity.

**Comment by noemi-salaun** [comment]
How to get this kind of custom controllers inside the documentation UI ?
