### ISSUE TITLE
Responses not varied on Accept header

### ISSUE THREAD

**Issue by bendavies** [api-platform/api-platform#349]
Hi there,

Api platform does not `Vary` on the requested `Accept` header, so requests for the same resource to varnish with differing Accept headers will return the first cached response. Essentially, Accept headers are ignored after the first request.
e.g
```
curl -X GET "http://127.0.0.1/foos" -H  "accept: application/json"
[{"id":1,"bar":"string"}]
curl -X GET "http://127.0.0.1/foos" -H  "accept: application/ld+json"
[{"id":1,"bar":"string"}]
```

Cheers

**Comment by teohhanhui** [comment]
I've noticed this on my end as well. But I think the fix is not as simple as #1219 (it's a good first step).
