### ISSUE TITLE
Quelques informations

### ISSUE THREAD

**Issue by 3kynox** [api-platform/api-platform#35]
Sorry for english readers.

Bonjour Dunglas, j'avais quelques questions par rapport au bundle que tu propose.
- A quand la version de Symfony en 2.8LTS ?
- Tu dis présenter une solution angularjs complète incluse dans ton repo, mais mis à part une config de RestAngular sur la doc, je ne vois nul lien avec la partie Symfony ni exemple concret pour mettre en place cette solution.
-  J'ai actuellement un projet Symfony en 2.8 fonctionnel avec les bundles FOSUser, FOSRest, FOSOAuth et NelmioApiDoc d'installés et j'ai pas mal de difficultés à appréhender la partie OAuth. Tout est fonctionnel côté Symfony, mais côté angular, j'arrive par l'intermédiaire de hello.js ( http://gonzalo123.com/2015/03/02/building-a-angularjs-provider-for-hello-js-library/ ) à générer des tokens et accéder à mes quelques ressources Symfony mais pas d'exemples sur comment afficher nos entités avec un CRUD côté angular ou si on veut se servir de vues côté angular pour les pages de login / logout / profil / inscription / etc... et que toutes les informations d'un utilisateur en particulier soit récupéré en json côté Symfony (avec utilisation de OAuth). 
  Malheureusement, outre le faite que tu spécifie pour APIDoc que ce soit simple d'utiliser OAuth, de le mettre en place, et de l'utiliser avec Angular, tu donne très peu de détails, aucun exemple, et il est dur de se dire que c'est une fonction apportée par APIDoc lorsque rien d'autres que quelques lignes de présentation sont exposées. Du coup est-ce normal? Y'a t'il des choses qui seront à venir à ce sujet ?

Voilà, je nourris quelques espoirs d'avoir trouvé ton travail sur le sujet Symfony / API Rest / Angular & OAuth et j'espère qu'il y aura une suite concrète (surtout concernant les exemples Angular et OAuth).

**Comment by dunglas** [comment]
@3KyNoX I reply in english for international readers, tell me if you need a translation.

* Symfony 2.8 LTS is already supported by all API Platform bundles, just change the `composer.json` file to `2.8` and run `composer update`. We'll release a new version (1.1) supporting Symfony 3 as well and we will update this standard edition to default to `2.8` soon. All the work is done, we just wait for some dev dependencies to release new versions compliant with Symfony 2.3 (especially Behat related packages).
* There are - as you pointed out - the Restangular config. But there also are [a tutorial for integrating Angular with API Platform](https://api-platform.com/doc/1.0/getting-started/angularjs), [a working example](https://github.com/dunglas/blog-client) using Yeoman and [an (experimental) ng-admin integration](https://github.com/api-platform/admin). What would you expect? Something like a yeoman generator with the Restangular config already inside?
* Not sure to understand well what is you problem with OAuth. You're speaking about APIDoc and FOSRest, you mean API Platform? There is nothing specific in API Platform to support OAuth, but - as it's a pure Symfony app you can easily use FOSOAuthBundle and the security component to secure your API (server-side).

Just install and configure the bundle then add a config like the following and you're API will be secured using OAuth:

```
# app/config/security.yml
security:
    firewalls:
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            # Add your favorite authentication process here

        api:
            pattern:    ^/api
            fos_oauth:  true
            stateless:  true
            anonymous:  false # can be omitted as its default value

    access_control:
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
```

Then, it's 100% a standard OAuth. Client-side use any OAuth lib in JS such as `hello.js` (I don't know this one) or [oauth.io](http://go.oauth.io/angular/) (already used it and it's a good one) to authenticate against your API.

**Comment by 3KyNoX** [comment]
Hello dunglas, thanks for your answer and sorry again for french speaking; I'll try to give more details in english this time.

- Ok for 2.8 and 3.0, good to hear.
- Thanks for other angular resources link, I'll study it today.
- And yes, was meaning API-Platform (instead of APIDoc), sorry for wrong name usage.
Oauth is already configured in my Symfony project. About this subject, and because FOSUser is the enabled provider,

```yml
oauth_authorize:
            pattern:    ^/oauth/v2/auth
            # Add your favorite authentication process here
```

... is not needed. I passed some time to get this sorted out :)

Thanks for oauth.io link, as it is a pay solution, I'll find something free and open.

My biggest problem today is to remove view and security controller from symfony (used by FOSUser) and create views (login / profile / etc...) now from angular app connected to FOSUser, using OAuth. Then I have with FOSRest bundle to expose users in json. And not sure the good way to achieve this.

Anyway, thanks again for informations and keep up your project !

**Comment by dunglas** [comment]
Basically, you do not need FOSRest when using API Platform (both solutions do the same thing using different ways). You can use API Platform (APIBundle) to expose your FOSUser users. Map you FOSUser `User` entity like the following and it should be OK server-side: https://api-platform.com/doc/1.0/api-bundle/fosuser-bundle#creating-a-user-entity-with-serialization-groups

Client-side you can create the profile page like in the angular tutorial I pointed out (the `User` resource is just a standard resource when using API Platform). For the login screen, you need to do the view using Angular. Server-side, the Symfony Security Component will be used. Maybe can you give a try to https://github.com/sahat/satellizer to handle the login process Angular side.

**Comment by 3KyNoX** [comment]
I gave a try already to satellizer. Unfortunately, following satellizer documentation, it grab user informations, server have to generate a json web token and then return this token to client for further resources use. My Symfony configuration currently uses grand type client_credentials and bearer which is not exactly the same behavior. I don't think satellizer is well-designed for my problem.

Existing issue created by my own : https://github.com/sahat/satellizer/issues/693

I'll give out a try to API-Platform now and implements experimental ng-admin. Once done, I'll have a fresh reflexion on oauth implementation.

**Comment by dunglas** [comment]
I don't know if it fit your need but we generally recommend to use JWT instead of OAuth (see for instance my talk at SfLive San Francisco: https://dunglas.fr/slides/sf-live-sf-2015/#/)

JWT implementation using API Platform and Angular is very easy.

**Comment by 3KyNoX** [comment]
Ok, I'll give out a try to API-Platform, JSON-LD / Hydra and handle authentication with JWT (using LexikJWTAuthenticationBundle & GfreeauGetJWTBundle) and Satellizer.

Just hope I can use forms only from angular client side (also for login form that returns JWT Token) and get rid of any controller / views from Symfony.

If we can keep this discussion open for any encoutered problems and sharing results for it can benefit to API-Platform.

**Comment by dunglas** [comment]
You don't need Satellizer when using JWT. A simple login form and storing the JWT token in the browser session or local storage is enough.

**Comment by 3KyNoX** [comment]
login (angular) form ?

**Comment by dunglas** [comment]
Yes. You just need to send a  `POST` request with form encoded `_username` and `_password` to your Symfony security endpoint. Store the resulting JWT token and include it in all next AJAX requests and you're done.

**Comment by 3KyNoX** [comment]
Let's give a try. If you got some working examples to handle this from angular?

Actually creating my local vhosts and cloning api-platform then upgrading to 2.8.

**Comment by 3KyNoX** [comment]
For information, I'm following
> https://api-platform.com/doc/1.0/getting-started/api

schema command generate error with "SocialMediaPosting" according to your given example : 

> $ bin/schema generate-types src/ app/config/schema.yml
> [critical] Type "SocialMediaPosting" cannot be found.

Is it possible to use doctrine yml files instead of annotations ?

**Comment by Simperfit** [comment]
@3kynox Since we are in the process of releasing v2, is this still relevant ?
