### ISSUE TITLE
More than one parameter in path

### ISSUE THREAD

**Issue by mfrankiewicz** [api-platform/api-platform#353]
Hi, is it possible to pass more than one parameter to api-platform route?

For example, i need to pass to route user id and verification hash:
` path="/users/{id}/verify/{verificationHash}"`

Is there a way to handle this path (with arguments) with api-platform?

Another example, can i modify item `phone` (id 5) related to item `user` (id 1) using following uri: `/users/1/phones/5`?

**Comment by soyuka** [comment]
We implemented subresources to help with this if you want to set up routes on your relations. 

If not, you should be able to achieve this with an action or an event subscriber.

-----------

Subresources are not released yet, you can try them by using `api-platform/core#master`. [Example here](https://github.com/api-platform/core/blob/eb47c5791cc84156a849a9c2f99279a57b6e28fc/tests/Fixtures/TestBundle/Entity/Container.php#L17).

**Comment by mfrankiewicz** [comment]
Great! Thanks :+1:
