### ISSUE TITLE
Dynamic serialization groups

### ISSUE THREAD

**Issue by djoos** [api-platform/api-platform#359]
Hi,

I would like to check here whether someone would be able to give a heads up on implementing "dynamic serialization groups" (https://api-platform.com/docs/core/serialization-groups-and-relations#using-different-serialization-groups-per-operation).

Why?
I recently stumbled upon the Asana API, which has an opt_fields parameter where fields and relationships can be optionally included by making use of the opt_fields/fields parameter.

References:
https://asana.com/developers/documentation/getting-started/input-output-options -> "fields"
```
?opt_fields=followers,assignee options: { fields: ["followers", "assignee"] }
Some requests return compact representations of objects, to conserve resources and complete the request more efficiently. Other times requests return more information than you may need. This option allows you to list the exact set of fields that the API should be sure to return for the objects. The field names should be provided as paths, described below.
```

Thanks in advance for your feedback!
David

**Comment by dunglas** [comment]
It's done, it just need a documentation: https://dunglas.fr/2017/06/api-platform-2-1-feature-walkthrough-create-blazing-fast-hypermedia-apis-generate-js-apps/ ("New Filters" section)?

**Comment by djoos** [comment]
Amazing - I'll dig deeper into it and consider writing up some docs & submitting a PR.

Thank you!
