### ISSUE TITLE
ng-admin issue

### ISSUE THREAD

**Issue by 3kynox** [api-platform/api-platform#36]
Hello,

Imported ng-admin inside my angular project from repo https://github.com/api-platform/admin.

Before ng-admin import, project was working with [demo angularclient](https://api-platform.com/doc/1.0/getting-started/angularjs) project and [demo blog api-platform](https://api-platform.com/doc/1.0/getting-started/api) from Symfony.

All bower requirements are installed.

[Find here project files](https://gist.github.com/3KyNoX/eea690f24ee2096c61a4)

As results, I got blank page displayed and 5 remaining warnings : 

```
Running "newer:jshint:all" (newer) task

Running "jshint:all" (jshint) task

app/scripts/admin.js
  line 109  col 25  ['hydraDoc'] is better written in dot notation.
  line 110  col 49  ['hydraDoc'] is better written in dot notation.
  line 162  col 22  Don't make functions within a loop.
  line 7    col 9   'jsonld' is not defined.
  line 31   col 10  'fetchHydraDoc' is defined but never used.

  ‼  5 warnings

Warning: Task "jshint:all" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2016-01-06 08:28:52 UTC)
loading tasks                 217ms  ███████████████████████████ 37%
loading grunt-newer            18ms  ███ 3%
newer:jshint:all               13ms  ██ 2%
loading grunt-contrib-jshint  174ms  ██████████████████████ 30%
jshint:all                    161ms  ████████████████████ 28%
Total 584ms
```

Any idea ?

**Comment by dunglas** [comment]
Did you try to add the `--force` flag as suggested by the error message?
