### ISSUE TITLE
QueryChecker issue

### ISSUE THREAD

**Issue by mario-digitalstate** [api-platform/api-platform#360]
Does anyone know what the $relationship variable is supposed to contain? 

https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Util/QueryChecker.php#L145

I'm having an issue where in my case, the variable contains this string '\AppBundle\Entity\ServiceTranslation' with no period. Causing an undefined index error due to the explode('.')

More info: https://github.com/DigitalState/Services/issues/23

**Comment by StephenOTT** [comment]
@dunglas any ideas on this?

**Comment by soyuka** [comment]
Something like `foo.bar`. Would it be possible to have the DQL responsible for the failure?

**Comment by mario-digitalstate** [comment]
**DQL:**
SELECT o 
FROM AppBundle\Entity\Service o 
LEFT JOIN AppBundle\Entity\ServiceTranslation o_t WITH o.id = o_t.translatable 
ORDER BY o_t.title ASC

**SQL:**
SELECT a0_.id AS id_0, a0_.uuid AS uuid_1, a0_.`owner` AS owner_2, a0_.owner_uuid AS owner_uuid_3, a0_.slug AS slug_4, a0_.enabled AS enabled_5, a0_.weight AS weight_6, a0_.version AS version_7, a0_.deleted_at AS deleted_at_8, a0_.created_at AS created_at_9, a0_.updated_at AS updated_at_10 
FROM app_service a0_ 
LEFT JOIN app_service_trans a1_ ON (a0_.id = a1_.translatable_id) 
ORDER BY a1_.title ASC LIMIT 10 OFFSET 0

The content of $relationship variable found at https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/Util/QueryChecker.php#L144:
"AppBundle\Entity\ServiceTranslation"

**Comment by Simperfit** [comment]
Does @soyuka's patch fix this issue @mario-digitalstate ?
