### ISSUE TITLE
How to add FOSUserBundle actions like login, register etc., in Swagger UI?

### ISSUE THREAD

**Issue by banandam** [api-platform/api-platform#365]
We have integrated `FOSUserBundle` and `LexikJWTAuthenticationBundle`. Login and register pages are working fine. But we need REST API endpoints in Swagger UI.

**Comment by soyuka** [comment]
They're not compatible AFAIR. Are you sure that you really need FOSUserBundle?

**Comment by banandam** [comment]
We have integrated FOSUserBundle & JWT by using your documentation links. But the login, register API endpoints are not displaying in Swagger UI.

https://api-platform.com/docs/core/fosuser-bundle
https://api-platform.com/docs/core/jwt

**Comment by soyuka** [comment]
IIRC it's not supposed to show up in swagger. We have however an OAUTH implementation in swagger.

**Comment by banandam** [comment]
Can you please share documentation related to OAuth integration?

**Comment by soyuka** [comment]
Currently a work in progress: https://github.com/api-platform/docs/pull/182

**Comment by megazoll** [comment]
@Simperfit why you close this issue? Should not `login` and `register` methods are exposed to swagger?
