### ISSUE TITLE
Parse data by "username" or "slug" without using Filters

### ISSUE THREAD

**Issue by synchr0n123r** [api-platform/api-platform#367]
First, i need to get data by "username" or "slug" without exposing entity ID into url. 

example: 
= domain.com/profile/{username}   => api.domain.com/profiles/{username}
= domain.com/event/{slug}   => api.domain.com/events/{slug}

I understand we can use "filters" to solve this. But i got another annoying problem:

1. A bit tricky : single item query suppose return object, but because using filters, return are array.
 
2. We have to define for each filters. Not big deal, but if there anyway to make this more easy to maintain? I use modular system, hard to remembering or checking file every time i need.

How you make your life easier for this case on real world web app development?

#note:
I experienced this when building social network web application with reactJS. It works, but a bit tricky.

**Comment by soyuka** [comment]
Hi,

Because you want to identify an "Entity" by something else then it's real database identifier, you need to build a custom data provider.

**Comment by synchr0n123r** [comment]
Got it Thank you.
