### ISSUE TITLE
Custom output with extra information, how to use decorate?

### ISSUE THREAD

**Issue by synchr0n123r** [api-platform/api-platform#368]
I need to add extra information on output: Collections, Items & embed.

Example: 
```
{
  "name": "hello",
  "id": 8
}
}

and i want to add:
{
  "name": "hello",
  "id": 8,
  "_extra":{
    "api_version": "1.1.1",
    "timestamp": "342234324"
}
}
```
I didn't find proper solutions yet. I can use "Custom Provider", but it only work on collections and items, not when embeded with another entity.

Douglas mentions about services decorate here: https://github.com/api-platform/api-platform/issues/340

but i'm stuck to implement it.

Anyone solve this?

**Comment by Tim59** [comment]
Hello synchr0n123r,

For me you need to decorate the service : api_platform.jsonld.normalizer.item if you use json-ld format

**Comment by dunglas** [comment]
Thanks for answering this @Tim59!
