### ISSUE TITLE
Float assert not working properly

### ISSUE THREAD

**Issue by marcin-piela** [api-platform/api-platform#37]
I have property $age with assert type "float" in my entity. When I try to make POST request with age for example "2" i get response "age: This value should be of type float." How to do this working? Every value causes this error. Can I use such assertions in my entity?

**Comment by dunglas** [comment]
The posted JSON value must be a float (and not an int or a string).

Can you check that you send a float value. If it's ok can you copy your HTTP request here to allow us to debug?

**Comment by marcin-piela** [comment]
Sorry my bad, in Nelmio Sandbox everything is send as string

**Comment by cvernerie** [comment]
@dunglas I am using the latest version (2-alpha) and I have the same problem with those values :
`{"billingDate":"2016-08-30T09:33:22.917Z","trader":"Restaurant","totalAmount":240}
`

**Comment by dunglas** [comment]
@cvernerie can you copy here the HTTP request you sent to the API please?

**Comment by cvernerie** [comment]
@dunglas 

POST /notes HTTP/1.1
Host: api.exemple.com
Connection: keep-alive
Content-Length: 69
Pragma: no-cache
Cache-Control: no-cache
accept: application/ld+json
Origin: http://exemple.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36
content-type: application/ld+json
Referer: http://exemple.com/
Accept-Encoding: gzip, deflate
Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.6,en;q=0.4

**Comment by dunglas** [comment]
@cvernerie the body of the request is missing.

**Comment by cvernerie** [comment]
@dunglas 

{trader: "Restaurant", billingDate: "2016-08-31", totalAmount: "35"}

**Comment by dunglas** [comment]
Here is the problem, `totalAmount` is of type "foat" and you send an int. Try this:

`{"billingDate":"2016-08-30T09:33:22.917Z","trader":"Restaurant","totalAmount":240.0}`

**Comment by cvernerie** [comment]
The problem is that in Javascript you can't cast an int to a float :

`parseFloat('200')  // == 200`
`parseFloat('200').toFixed(2) // == '200.00'`

**Comment by dunglas** [comment]
This is indeed a problem. The JSON standard does not differentiate `float` and `int`. However JSON Schema and XML (as well as JSON-LD) do make the difference.

A possible fix is to handle this case especially: automatically cast to `float` when this type is expected and `is_numeric` returns `true`.

ping @api-platform/core-team

**Comment by dunglas** [comment]
@cvernerie I've just pushed a patch fixing this, can you test it please? https://github.com/api-platform/core/pull/714

**Comment by dunglas** [comment]
@cvernerie can you try with the `dev-master` version, it should fix the problem.

**Comment by cvernerie** [comment]
@dunglas That works fine, thanks ! :)

**Comment by Shine-neko** [comment]
@dunglas https://github.com/symfony/symfony/blob/master/src/Symfony/Component/Serializer/Normalizer/AbstractObjectNormalizer.php#L275 same problem ? :trollface:

**Comment by teohhanhui** [comment]
@dunglas @Shine-neko We cannot assume that we're dealing with JSON.

**Comment by dunglas** [comment]
@Shine-neko we should indeed do something for that in Symfony too. It's on my todo list.

**Comment by Shine-neko** [comment]
@dunglas ? :)

**Comment by dunglas** [comment]
Still on my todolist but PRs welcome :)
