### ISSUE TITLE
docker-compose build fails

### ISSUE THREAD

**Issue by laytoneverson** [api-platform/api-platform#376]
When building the docker containers I get an error stating that:

```
/bin/sh: docker-app-install-composer: not found
ERROR: compose.cli.main.main: Service 'app' failed to build: The command '/bin/sh -c set -xe    && apk add --no-cache --virtual .fetch-deps             openssl       && docker-app-install-composer  && mv composer.phar /usr/local/bin/composer     && apk del .fetch-deps' returned a non-zero code: 127
```

And here is more context if it helps:

```
Step 4/23 : RUN set -xe         && apk add --no-cache --virtual .build-deps             $PHPIZE_DEPS            icu-dev                 zlib-dev        && docker-php-ext-install             intl            pdo_mysql               zip     && pecl install                 apcu-${APCU_VERSION}    && docker-php-ext-enable --ini-name 20-apcu.ini apcu  && docker-php-ext-enable --ini-name 05-opcache.ini opcache      && apk del .build-deps
 ---> Using cache
 ---> cb491122c824
Step 5/23 : COPY docker/app/php.ini /usr/local/etc/php/php.ini
 ---> Using cache
 ---> d06549a106b9
Step 6/23 : COPY docker/app/install-composer.sh /usr/local/bin/docker-app-install-composer
 ---> Using cache
 ---> 4ffe4c9baacf
Step 7/23 : RUN chmod +x /usr/local/bin/docker-app-install-composer
 ---> Using cache
 ---> 369fac7df587
Step 8/23 : RUN set -xe         && apk add --no-cache --virtual .fetch-deps             openssl      && docker-app-install-composer     && mv composer.phar /usr/local/bin/composer   && apk del .fetch-deps
 ---> Running in b27a024f749c
+ apk add --no-cache --virtual .fetch-deps openssl
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.4/community/x86_64/APKINDEX.tar.gz
(1/2) Installing openssl (1.0.2k-r0)
(2/2) Installing .fetch-deps (0)
Executing busybox-1.24.2-r13.trigger
Executing ca-certificates-20161130-r0.trigger
OK: 66 MiB in 33 packages
+ docker-app-install-composer
/bin/sh: docker-app-install-composer: not found
ERROR: compose.cli.main.main: Service 'app' failed to build: The command '/bin/sh -c set -xe    && apk add --no-cache --virtual .fetch-deps             openssl       && docker-app-install-composer  && mv composer.phar /usr/local/bin/composer     && apk del .fetch-deps' returned a non-zero code: 127
```

Feedback would be helpful and thank you in advance.

**Comment by Simperfit** [comment]
Do you still have  `docker/app/install-composer.sh` ? You need it to run the docker-app-install-composer.

**Comment by laytoneverson** [comment]
Yes, the files is still there. I have also tried to mount the script in the
docker compose. I have copied it to a 'serverbin/install-composer.sh',
mount the serverbin folder and run it from there. I have tried lowering the
version in docker-compose thinking maybe it's a bug in the new v3 compose
files.

I am getting this error on the current master branch. Is anyone else having
this problem? I'm not sure what steps to take next...

**Comment by meyerbaptiste** [comment]
What is your version of docker and docker-compose? What is your OS? Did you try `docker-compose build --no-cache`?

I don't have any issues with the master branch.

**Comment by Simperfit** [comment]
@laytoneverson I can't reproduce either, if you still have an issue please ping us.

**Comment by redecs** [comment]
Had the same issue with Docker on Windows. I created my own composer installation procedure within the Dockerfile (no external scripts) only to have fail at the entry point script for the app container (`exec user process caused "no such file or directory"`).
It turns out that problems are caused by line endings. I configured git to keep the Unix line endings and the it worked as expected.

`git config --global core.autocrlf false`

It seems Docker for Windows doesn't like CRLF line endings.

**Comment by vdumontier** [comment]
Same issue for me with DOcker/Window.
As complement you can execute dos2unix on the file to resolve the issue :

`dos2unix.exe docker/app/install-composer.sh`

**Comment by dunglas** [comment]
Isn't https://github.com/api-platform/api-platform/blob/master/.gitattributes#L2 supposed to prevent this?

**Comment by vdumontier** [comment]
Just cloning a repos setup before this commit :) I suppose my comment can help someone in the same case. But no need to re-open the issue.

**Comment by redecs** [comment]
@dunglas I think it's something related to this: https://github.com/git/git/blob/master/Documentation/RelNotes/2.10.0.txt#L248 Will investigate further.

**Comment by dunglas** [comment]
@redecs thanks for working on this
