### ISSUE TITLE
Autowiring Monolog lead to issue

### ISSUE THREAD

**Issue by raziel057** [api-platform/api-platform#377]
I tried to inject monolog in a custom Action like this:

```php
namespace AppBundle\Action;

use AppBundle\Entity\Country;
use Doctrine\Common\Persistence\ManagerRegistry;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\Routing\Annotation\Route;
use Monolog\Logger;

class CountrySpecialOrder
{
    private $logger;
    
    public function __construct(Logger $logger)
    {
        $this->logger = $logger;
    }
    
    /**
     * @Route(
     *     name="country_special_order",
     *     path="/countries",
     *     defaults={"_api_collection_operation_name"=Country::class, "_api_item_operation_name"="special"}
     * )
     * @Method("GET")
     */
    public function __invoke($data)
    {
        $this->logger->info("...");
        
        return $data;
    }
}
```

I got this error:
Unable to autowire argument of type "Monolog\Logger" for the service "appbundle\action\countryspecialorder". Multiple services exist for this class (monolog.logger, monolog.logger.request, monolog.logger.cache, monolog.logger.translation, monolog.logger.templating, monolog.logger.profiler, monolog.logger.php, monolog.logger.event, monolog.logger.router, monolog.logger.security, monolog.logger.doctrine).

**Comment by soyuka** [comment]
I think this is not related to api platform https://github.com/symfony/symfony/issues/16639

**Comment by raziel057** [comment]
Exact
