### ISSUE TITLE
No such service: web

### ISSUE THREAD

**Issue by felixn11** [api-platform/api-platform#378]
I am not able to create the doctrine schema after following the steps in the guide (running the 'docker-compose up -d' and 'docker-compose logs -f'

![image](https://user-images.githubusercontent.com/8666510/28818571-c6e4c1fa-76ab-11e7-8e2d-d70554770a5e.png)

I am not able to run the doctrine command: 'docker-compose exec web bin/console doctrine:schema:create' on my Windows 10 machine. 

![image](https://user-images.githubusercontent.com/8666510/28818631-f377ba7e-76ab-11e7-8435-547536c91d58.png)

**Comment by Simperfit** [comment]
We should update the documentation, but this is not `web` anymore this is `app`.

**Comment by felixn11** [comment]
Perfect, that's working, thanks!

**Comment by teohhanhui** [comment]
Can you help us fix the documentation?
