### ISSUE TITLE
Custom get request

### ISSUE THREAD

**Issue by PetitBateau** [api-platform/api-platform#379]
Is there a way to perform a complete custom request ?

When I have
`public function __invoke($data)`
in my action class, the request is already sent.

I would like so send my own request to the database.

Is there any way to do that ? I read the doc and I didn't find what i'm looking for.

The only way I found is to call my entity repository in a Controller action but doesn't seems to be a good solution..

**Comment by Simperfit** [comment]
What do you want to achieve ? to alter the sql query ? or to alter the HTTP request ?

For both there are ways in the framework, for the first one could do a custom filter that will add filters to the query.

For the seconds you need to use [event listeners ](https://api-platform.com/docs/core/events)

**Comment by PetitBateau** [comment]
I think I misunderstood the way it works.
In my controller, where the `$data` arg is filled ?

thank's for your time

**Comment by Simperfit** [comment]
The `$data` is filled with the `DataProvider` like explained [here](https://api-platform.com/docs/core/operations#creating-custom-operations-and-controllers)

**Comment by hassanjuniedi** [comment]
@Simperfit am trying to get request object inside action class, can you help me with that ? thanks in advance.
