### ISSUE TITLE
Does Hydra can return xml / html response instead of json

### ISSUE THREAD

**Issue by 3kynox** [api-platform/api-platform#38]
All are in the title, FOSRESTBundle is able to return json / xml / html responses, but what's the case with Hydra ?

**Comment by dunglas** [comment]
API Platform dev-master supports JSON-LD/Hydra as well as raw JSON, XML and any custom format: https://github.com/api-platform/doc/blob/master/api-bundle/content-negotiation.md (be careful, the 2.0 version is not finished yet).

Hydra is a format built on top of JSON-LD, by definition it cannot support other format such as HTML.

**Comment by 3KyNoX** [comment]
Superb! We had a meeting with our company this morning, maybe you'll be able to add an additional company that uses api-platform soon. Display data in several formats was one of our requirements.

It looks like to get benefits of content-negociation features I'm forced to use api-bundle to dev-master from composer. Unfortunately I got error : 

> ContextErrorException in DunglasApiProvider.php line 48:
> Catchable Fatal Error: Argument 3 passed to > Nelmio\ApiDocBundle\Extractor\AnnotationsProvider\DunglasApiProvider::__construct() must be an instance of Dunglas\ApiBundle\Mapping\ClassMetadataFactoryInterface, instance of Dunglas\ApiBundle\Mapping\Factory\ClassMetadataFactory given, called in D:\clients\courtier-web\api-platform\www\app\cache\dev\appDevDebugProjectContainer.php on line 2669 and defined

I suppose it's related to 2.0 version in preparation warning you gave me just before.

A last question please, do you have some information link that show a complete list of benefits using your framework against a classical FOSRest setup ?

Thanks again.

**Comment by dunglas** [comment]
NelmioApiDoc is not yet compatible with `dev-master`. Remove NelmioApiDoc and the error it will disappear.

For a comparison with other solutions, take a look at my slides from Symfony Live 2015 (in french):  https://dunglas.fr/2015/04/mes-slides-du-symfony-live-2015-a-la-decouverte-de-api-platform/

**Comment by 3KyNoX** [comment]
Thanks for answer dunglas. I disabled already NelmioApiDoc friday but I'm facing another problem. 

I enabled another format in config.yml (supported by Content Negociation) : 

> supported_formats: [ "jsonld", "xml" ]

But PostMan return this : 

![](http://i.imgur.com/exdDvcD.png)

Everything working fine with json-ld return.

Thanks for support.

**Comment by dunglas** [comment]
You probably missed to create the XML responder: https://github.com/api-platform/doc/blob/master/api-bundle/content-negotiation.md#creating-a-responder

**Comment by 3KyNoX** [comment]
Ok, because doc indicates : 

> If the format you want to use is not supported by default in the Negotiation library...

I understood all parts below is not necessary. Looks like I was wrong :)

Then, "Registering a custom format in the Negotiation library" & "Registering a custom serializer" is only for custom format not supported by Content Negociation by default, right ?

I think documentation can involve doing mistakes.

Checking all of this and sharing a pull request soon for doc.

**Comment by 3kynox** [comment]
Morning`

Still facing : 
>   "hydra:title": "An error occurred",
>   "hydra:description": "Serialization for the format html is not supported",

src/MyBundle/EventListener/HtmlResponderViewListener.php countains :

```php
<?php

namespace ContactBundle\EventListener;

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent;
use Symfony\Component\Serializer\SerializerInterface;

class HtmlResponderViewListener
{
    const FORMAT = 'html';

    /**
     * @var SerializerInterface
     */
    private $serializer;

    public function __construct(SerializerInterface $serializer)
    {
        $this->serializer = $serializer;
    }

    public function onKernelView(GetResponseForControllerResultEvent $event)
    {
        $controllerResult = $event->getControllerResult();

        if ($controllerResult instanceof Response) {
            return $controllerResult;
        }

        $request = $event->getRequest();

        $format = $request->attributes->get('_api_format');
        if (self::FORMAT !== $format) {
            return $controllerResult;
        }

        switch ($request->getMethod()) {
            case Request::METHOD_POST:
                $status = 201;
                break;

            case Request::METHOD_DELETE:
                $status = 204;
                break;

            default:
                $status = 200;
                break;
        }

        $resourceType = $request->attributes->get('_resource_type');
        $response = new Response(
            $this->serializer->serialize($controllerResult, self::FORMAT, $resourceType->getNormalizationContext()),
            $status,
            ['Content-Type' => 'text/html']
        );

        $event->setResponse($response);
    }
}
```

... and html is activated ...

```yml
dunglas_api:
    title:       "%api_name%"
    description: "%api_description%"
    supported_formats: [ "jsonld", "xml", "html" ]
```

Am I right to think Content-negociation do not allow Html output without defining Registering a custom format in the Negotiation library throw compiler pass and I have also to register  a custom serializer ?

Thanks for help.
