### ISSUE TITLE
ApiPlatform requeset issue

### ISSUE THREAD

**Issue by achrafsmlali** [api-platform/api-platform#383]
hi 
I have two entities author and book, is it possible to get the author item and his collection of books in one request ?

book      manytoOne    author
id                                   id
idAuthor

Thanks in advance for any guidance

**Comment by Simperfit** [comment]
You need to use embedded items for this to work, look at how we are doing that with [serialization groups](https://api-platform.com/docs/core/serialization-groups-and-relations#embedding-relations)

**Comment by achrafsmlali** [comment]
In the docs exemple they get the nested author informations with the books one. in my case i want to reverse it, to get author and his books knowing that there is no reference to the book in the author entity

**Comment by Simperfit** [comment]
If you still have an issue please feel free to ping me.
