### ISSUE TITLE
How I change entity title on Swagger documentation?

### ISSUE THREAD

**Issue by lvillarino** [api-platform/api-platform#384]
Hi

I want to know How I change entity title on Swagger documentation.

For example I want to change the word "Book" for "Books XYZ" on this page https://demo.api-platform.com/

Thanks

**Comment by lvillarino** [comment]
I want to change the SECTION value

@see https://symfony.com/doc/master/bundles/NelmioApiDocBundle/the-apidoc-annotation.html

**Comment by dunglas** [comment]
See https://api-platform.com/docs/core/swagger

**Comment by Reileb** [comment]
This feature is undocumented as of today. Additionaly [the documentation](https://api-platform.com/docs/guides/extend-openapi-documentation/) is very thin and its "improve" link [directs to a 404](https://github.com/api-platform/core/edit/guides/extend-openapi-documentation.php). Links in the previous comments are also obsolete, I can find no way to change entities name in the "Swagger" doc.
