### ISSUE TITLE
Remove the filter EXACT from the Swagger documentation ?

### ISSUE THREAD

**Issue by lvillarino** [api-platform/api-platform#387]
How I can remove the filter EXACT from the Swagger documentation ?

Thanks

**Comment by Tim59** [comment]
Hello Ivillarino,

If you want to modify the swagger documentation, you need to decorate the 'api_platform.swagger.normalizer.documentation' service.

 After that you able to unset the documentation or parts.

**Comment by dunglas** [comment]
Closing as documented?
