### ISSUE TITLE
Disable "Try it Out" on Swagger Documentation

### ISSUE THREAD

**Issue by lvillarino** [api-platform/api-platform#389]
Hi:

How I can disable the "Try it Out" option on Swagger Documentation?
Ex: Go to https://demo.api-platform.com/, click 'GET Books'

Thanks

**Comment by meyerbaptiste** [comment]
Please refer to the Swagger-UI repository for this issue: https://github.com/swagger-api/swagger-ui.

BTW, I think it's currently not possible (see https://github.com/swagger-api/swagger-ui/blob/087ed203849b4dfc222046e71e5fa269ab44f989/src/core/plugins/spec/selectors.js#L257-L260) or maybe with some custom JS/CSS...

**Comment by wachirakorn** [comment]
Downgrade springfox-swagger to 2.7.0 and config bean as follow.

	@Bean
	public UiConfiguration uiConfig() {
		String[] supportedSubmitMethods = new String[] { };
		return new UiConfiguration("", supportedSubmitMethods);
	}
