### ISSUE TITLE
Symfony 3

### ISSUE THREAD

**Issue by nicodmf** [api-platform/api-platform#39]
Hello,

To begin, thanks for this usefull project.
My question is : Have you a planning for adapt api-platform to Symfony 3?

Best Regards,

**Comment by sroze** [comment]
Hi @nicodmf. Sure! Can you let us know how isn't it compatible at the moment? :)

**Comment by juliendufresne** [comment]
Hello @sroze ,

In order for this project to be able to migrate to symfony3, we need:
- new tag for the `api-platform/schema-generator` (requirement on `symfony/yaml ~2.4` only solved in the master branch)
- in `behat/mink` fix the dependency on `symfony/css-selector ~2.1`
- in `behat/mink-browserkit-driver` fix the dependency on `symfony/dom-crawler ~2.3`
