### ISSUE TITLE
How to set custom title / description for operations?

### ISSUE THREAD

**Issue by VictorKrasnov** [api-platform/api-platform#395]

**Comment by Tim59** [comment]
In swagger ?

**Comment by VictorKrasnov** [comment]
Yes.

**Comment by Tim59** [comment]
maybe this can help you : api-platform/docs#236

Modify : $docs['info']['title']

**Comment by Tim59** [comment]
@VictorKrasnov https://api-platform.com/docs/core/swagger

**Comment by dunglas** [comment]
Closed as documented
