### ISSUE TITLE
Dependencies problem

### ISSUE THREAD

**Issue by erichard** [api-platform/api-platform#397]
Hi,

When using api-platform 2.1, we cannot upgrade `symfony/symfony` to 3.3.5 (or upper) due to conflict with `phpdocumentor/reflection-docblock 3.2`.

```
$ composer why-not symfony/symfony 3.3.6
symfony/symfony  v3.3.6  conflicts  phpdocumentor/reflection-docblock (<3.0||>=3.2.0)  
```

Maybe we can upgrade phpdocumentor/reflection-docblock to 4.0 but what is the consequence for api-platform ?

**Comment by dunglas** [comment]
Would you mind opening a PR? If the test suite pass, we're all good to upgrade :)
