### ISSUE TITLE
Class SymfonyStandard\Composer is not autoloadable, can not call post-root-package-install script

### ISSUE THREAD

**Issue by keyermann** [api-platform/api-platform#40]
Hi everyone,

executing the create-project 
`composer create-project api-platform/api-platform blog-api`

leads me to this composer complain : 
`Class SymfonyStandard\Composer is not autoloadable, can not call post-root-package-install script`

Is ther anyone who has encountered the problem ?
Any idea ?

PS: Sorry for my bad french english, I'm working on it.

**Comment by 3kynox** [comment]
Can you try removing your vendor/ dir if existing and retry ?

**Comment by keyermann** [comment]
yeah I do, and than `composer install` run without any problem. But post-root-package-install isn't executed as it is only executed after the root package has been installed, during the create-project command.

So I don't know if this script is important. But for the moment every time I try to create a new project with 
`composer create-project api-platform/api-platform blog-api` I have the warning.

I'll try to use api-platform without it.

**Comment by dunglas** [comment]
It's a known problem but it doesn't have any impact.

**Comment by keyermann** [comment]
Ok, I let you the choice to close this issue then.
Thank you for your assistance @3kynox and @dunglas 
Have a nice day
