### ISSUE TITLE
How to expose only related entities?

### ISSUE THREAD

**Issue by vaibhavpandeyvpz** [api-platform/api-platform#401]
I just tried to get started with api-platform. Everything worked fine but to configure api-platform to only return entities related to the logged in `User` (via [LexikJWTAuthenticationBundle](https://github.com/lexik/LexikJWTAuthenticationBundle))? Whichever endpoint I go with, it just spits out everything in database.

**Comment by dunglas** [comment]
Take a look to https://api-platform.com/docs/core/serialization-groups-and-relations

**Comment by hpatoio** [comment]
The link above gives 404. I think the new link is https://api-platform.com/docs/core/serialization/#changing-the-serialization-context-on-a-per-item-basis
