### ISSUE TITLE
ApiSubresource trouble, $request->attributes->get('data') return NULL

### ISSUE THREAD

**Issue by vdesdoigts** [api-platform/api-platform#402]
Hello,  

I need to change the Serialization Context Dynamically, but I can't have the right `Entity`.  
Can you help me?  

Example: `/api/users/79/related_books`

```
$subject = $request->attributes->get('data');
if ($subject instanceof Book) {}
```

`$subject` return `NULL`  

Thank you

**Comment by soyuka** [comment]
This is a collection no? Therefore, `$subject` will be an array no?

**Comment by vdesdoigts** [comment]
If I use `/api/checkins?user=79` it returns `string(18) "Kol\Entity\Checkin"`, I don't understand the difference :)

**Comment by vdesdoigts** [comment]
Wrong `get()` sorry, thanks for the help!
