### ISSUE TITLE
Using entities from other bundles

### ISSUE THREAD

**Issue by benr77** [api-platform/api-platform#405]
I have my Doctrine entities stored in a separate package, so that I can share them between multiple applications.

I have added API Resource annotations to some entities but they are not found - I think because they are not in AppBundle/Entity

With v1 of API Platform there is an option `api_resources_directory` which might be what I'm looking for, but in v2.0.10 of api-platform/core there does not seem to be an equivalent.

How do I specify the location of my entities in my vendor directory? Is this possible?

Thanks

**Comment by benr77** [comment]
I have now managed to do this using YML configuration instead of Annotations - e.g.
```
# src/AppBundle/Resources/config/api_resources/resources.yml

resources:
    SomeOtherBundleBundle\Entity\Product: ~
```
In my case this is actually preferable as my Entities are in a shared repository and I don't really want to have to make them dependent on ApiPlatform.

If anybody does have a solution to using Annotations to configure entities from another package that would be useful to document it here for future reference.

**Comment by meyerbaptiste** [comment]
Hi @benr77, there is no solution for annotations in 2.0.10. In the latest 2.1.0-beta there is a new way to do it: https://github.com/api-platform/core/pull/1271

You can find the doc here: https://github.com/api-platform/docs/pull/240
