### ISSUE TITLE
No resource class found for object of type XXX with custom getter

### ISSUE THREAD

**Issue by erichard** [api-platform/api-platform#409]
When serializing an entity, I try to wrap related relations in an array, so instead of having :

```
{
    "manyToOneA": {...},
    "manyToOneB": {...}
}
```

I wish to have this 

```
{
    "wrap": {
         "A": {...} ,
         "B": {...} 
    }
}
```

I added a getter to do so but I get a serialization error `No resource class found for object of type XXX`

I reproduce the same problem with the api-platform demo by adding a custom getter in review like this : https://github.com/erichard/demo/commit/04e82fcef96968256bebf097eaf45a58fb2cdcc9

Any idea ?

**Comment by Simperfit** [comment]
I don't think the custom getter will do the trick unless you a new field.

What you could do is to use [event listener](https://api-platform.com/docs/core/events#header) to re-formatt the data before sending it.
