### ISSUE TITLE
Disable trace data

### ISSUE THREAD

**Issue by BisKri** [api-platform/api-platform#410]
Please how can i disable trace data, when an error occure, like 'Not found' exception ?
Thanks

**Comment by meyerbaptiste** [comment]
Switch to prod environment 😉

**Comment by BisKri** [comment]
thanks, i found much easier
in app_dev.php, set dev debug environment to false
$kernel = new AppKernel('dev', **false**);

**Comment by soullivaneuh** [comment]
Don't we have any api-platform scope specific option? Disabling the debug kernel option has a much more important impact than just disabling the trace on the error report.
