### ISSUE TITLE
Swagger UI can't execute due to incorrect bearer token header name

### ISSUE THREAD

**Issue by kylephp** [api-platform/api-platform#415]
I followed the documentation here: https://github.com/api-platform/docs/blob/ed356c95669307202e43aa5099a44fef0c0ac2a0/core/oauth2.md
Everything is fine but when executing with swagger, the response always return
`{
  "error": "access_denied",
  "error_description": "OAuth2 authentication required"
}` 
I have figured out the problem is the authorization header is incorrect, it should be "Bearer XXX" (capital B) instead of "bearer XXX"
Any idea about it?

**Comment by matrix818181** [comment]
Got the same issue !

I've made some research within the api-platform folder and I found 1 reference with "Bearer" but the case is correct. It must be something else that lower the string.

**Comment by alanpoulain** [comment]
It works as expected today.
