### ISSUE TITLE
How create var/jwt/private.pem and var/jwt/private.pem

### ISSUE THREAD

**Issue by sbacem** [api-platform/api-platform#416]
i can't create private.pem and  private.pem, i use this cmd 

`docker-compose exec app openssl genrsa -out var/jwt/private.pem -aes256 4096`

I have this error 

`rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "exec: \"openssl\": executable file not found in $PATH"
`

**Comment by dunglas** [comment]
You need to install `openssl` in the container. For instance you can add it here: https://github.com/api-platform/api-platform/blob/master/Dockerfile#L6

**Comment by dunglas** [comment]
It is worth mentioning it in the docs btw. A pr against the `2.1` branch of the docs would be very welcome.

**Comment by sbacem** [comment]
Thanks for help @dunglas 

Dockerfile
 
```php
RUN apk add --no-cache --virtual .persistent-deps \
		git \
		icu-libs \
		zlib \
		openssl

ENV APCU_VERSION 5.1.8

RUN set -xe \
	&& apk add --no-cache --virtual .build-deps \
		$PHPIZE_DEPS \
		icu-dev \
		zlib-dev \
		openssl \
	&& docker-php-ext-install \
		intl \
		pdo_mysql \
		zip \
	&& pecl install \
		apcu-${APCU_VERSION} \
	&& docker-php-ext-enable --ini-name 20-apcu.ini apcu \
	&& docker-php-ext-enable --ini-name 05-opcache.ini opcache \
	&& apk del .build-deps
....
```
