### ISSUE TITLE
ApiSubRequest and collectionOperations/itemOperations

### ISSUE THREAD

**Issue by julienpillias** [api-platform/api-platform#423]
Hi all.
Just new with api-plateform (was using FosRestBundle before), I would like to retrieve sub ressource in one call.

Objective is to have this : 

```json
{
    "@context": "/app_dev.php/contexts/House",
    "@id": "/app_dev.php/houses/437",
    "@type": "House",
    "id": 437,
    "name": "House name",
    "departments": [
        {
            "@id": "/app_dev.php/departments/72",
            "id": 72,
            "name": "Department name"
        }, 
        ...
    ]
}
```

Having these 2 entities : 

*HOUSE entity
```php
<?php

namespace XXX\FrontBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiSubresource;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * House : Liste des modèles disoponnible à la configuration pour création de projet
 *
 * @ApiResource(
 *     collectionOperations={
 *         "get"={"method"="GET"},
 *         "post"={"method"="POST", "access_control"="is_granted('ROLE_ADMIN')"}
 *     },
 *     itemOperations={
 *         "get"={"method"="GET"},
 *         "put"={"method"="PUT", "access_control"="is_granted('ROLE_ADMIN')"},
 *         "delete"={"method"="DELETE", "access_control"="is_granted('ROLE_HTACCESS')"},
 *         "api_houses_departments_get_subresource"={"method"="GET", "normalization_context"={"groups"={"list"}}}
 *     },
 *     attributes={"jsonld_embed_context"=true}
 * )
 * @ORM\Table(name="house")
 * @ORM\Entity(repositoryClass="XXX\FrontBundle\Repository\HouseRepository")
 */
class House
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Groups({"list", "details"})
     */
    private $id;

/**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, precision=0, scale=0, nullable=false, unique=true)
     * @Groups({"list", "details","simple"})
     */
    private $name;

    /**
     * @var Department List of item departments where the house is available
     *
     * @ORM\ManyToMany(targetEntity="XXX\FrontBundle\Entity\Department", inversedBy="houses")
     * @ORM\JoinTable(name="house_department",
     *   joinColumns={
     *     @ORM\JoinColumn(name="house_id", referencedColumnName="id", onDelete="CASCADE")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="department_id", referencedColumnName="id", onDelete="CASCADE")
     *   }
     * )
     * @ApiSubresource
     */
    private $departments;

// geters & setters
```

note the **"api_houses_departments_get_subresource"={"method"="GET", "normalization_context"={"groups"={"list"}}}** annotation, wich should diplay more informations for the department subResource ! ? ! (i can see the route name in router:debug, so route name should be ok, according to this page : https://api-platform.com/docs/core/operations )

* DEPARTMENT entity
```php
<?php

namespace XXX\FrontBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * Department
 *
 * @ApiResource(
 *     collectionOperations={
 *     },
 *     attributes={"jsonld_embed_context"=true}
 * )
 * @ORM\Table(name="department")
 * @ORM\Entity(repositoryClass="XXX\FrontBundle\Repository\DepartmentRepository")
 */
class Department
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @Groups({"list", "details"})
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, precision=0, scale=0, nullable=false, unique=true)
     * @Groups({"list", "details"})
     */
    private $name;

    /**
     * @var \Doctrine\Common\Collections\Collection
     *
     * @ORM\ManyToMany(targetEntity="XXX\FrontBundle\Entity\House", mappedBy="departments")ApiSubresource
     */
    private $houses;
```

But when retriving a house, i d'ont have the department name & id : 
```json
{
    "@context": "/app_dev.php/contexts/House",
    "@id": "/app_dev.php/houses/437",
    "@type": "House",
    "id": 437,
    "name": "La coline",
    "departments": [
        "/app_dev.php/departments/72"
    ],
}
```

What i'm i doing wrong ? Working on this since servals hours :/

Thank you for your help.

**Comment by DariuszLuber** [comment]
You need add normalization context in @APIResources attributes 
`"normalization_context"={"groups"={"list"}}`
for house entity.
Then when getting a House endpoint data it will use group "list" to normalize.
Also do you have set eager loading in config?

**Comment by julienpillias** [comment]
First, thank you for your help.

I've just tried to add 
```php
/**
     * @var Department List of item departments where the house is available
     *
     * @ORM\ManyToMany(targetEntity="XXX\FrontBundle\Entity\Department", inversedBy="houses", fetch="EAGER")
     * @ORM\JoinTable(name="house_department",
     *   joinColumns={
     *     @ORM\JoinColumn(name="house_id", referencedColumnName="id", onDelete="CASCADE")
     *   },
     *   inverseJoinColumns={
     *     @ORM\JoinColumn(name="department_id", referencedColumnName="id", onDelete="CASCADE")
     *   }
     * )
     * @ApiSubresource("normalization_context"={"groups"={"list"}})
     */
    private $departments;
```
annotation on House side.

and get this error (with or with out the EAGER set on the ManyToMany) : 

```json
{
    "@context": "/app_dev.php/contexts/Error",
    "@type": "hydra:Error",
    "hydra:title": "An error occurred",
    "hydra:description": "[Syntax Error] Expected Doctrine\\Common\\Annotations\\DocLexer::T_IDENTIFIER, got 'normalization_context' at position 534 in property XXX\\FrontBundle\\Entity\\House::$departments.",
...
}
```

Are you sure we can pass option to ApiSubresource ? When opening ApiPlatform\Core\Annotation\ApiSubresource.php, their is a final class ApiSubresource, with no options !

EAGER is only optimisation ? should still works with out it ?

**Comment by DariuszLuber** [comment]
I think not in@ApiSubresources, but in @ApiResource
I have it like this:
```
 * @ApiResource(attributes={
 *                          "filters"={"apiOrder", "searchFilter", "searchOrFilter"},
 *                          "pagination_items_per_page"=50,
 *                          "force_eager"=true,
 *                          "normalization_context"={"groups"={"doctor"}}
 *                          })
```

and in all connected entities i add on fields:
`@Groups({"doctor" })`

**Comment by julienpillias** [comment]
Ha yes, that works for sure, but i don't want to specify a group everywhere.
As descrive here  https://api-platform.com/docs/core/operations#subresources 👍 

> You may want custom groups on subresources. Because a subresource is nothing more than a collection operation, you can set normalization_context or denormalization_context on that operation. To do so, you need to override collectionOperations. Based on the above operation, because we retrieve an answer, we need to alter it’s configuration:

```php
<?php

// src/AppBundle/Entity/Answer.php

use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ApiResource(collectionOperations={"api_questions_answer_get_subresource"={"method"="GET", "normalization_context"={"groups"={"foobar"}}}})
 */
class Answer
{
    // ...
}
```

But it doesn't seems to work, or i'm doing something bad ! (but have no errors)

**Comment by DariuszLuber** [comment]
Subresource are not to load at once, but to call subresources in next request.
Ex. from documentation:
we have question with id 42, and we want get only answers connected with that, so we make a request
/question/42/answer - this will return only answers, without data of question 42

**Comment by soyuka** [comment]
@DariuszLuber yes

@julienpillias you don't need any `@ApiSubresource` here, just set your groups on the `itemOperation` `get`.

**Comment by julienpillias** [comment]
Great it works, thank you !

Here was the solution : 

in Department Entity (and not House, this was my mistake) : 
```php
/**
 * Department
 *
 * @ApiResource(
 *     itemOperations={
 *         "get"={"method"="GET"},
 *         "put"={"method"="PUT", "access_control"="is_granted('ROLE_ADMIN')"},
 *         "delete"={"method"="DELETE", "access_control"="is_granted('ROLE_ADMIN')"},
 *         "api_houses_departments_get_subresource"={"method"="GET", "normalization_context"={"groups"={"list"}}}
 *     },
 *     attributes={"jsonld_embed_context"=true}
 * )
 * @ORM\Table(name="department")
 * @ORM\Entity(repositoryClass="XXX\FrontBundle\Repository\DepartmentRepository")
 */
class Department
{
```

Important thing is : 
**"api_houses_departments_get_subresource"={"method"="GET", "normalization_context"={"groups"={"list"}}}**

**Comment by julienpillias** [comment]
NB : I think i've done a mistake, and leave 
attributes={
 *          "normalization_context"={"groups"={"list"}}
 *     }
on House ApiResource.

With out this, doesn't work as except :/ I may use groups everywhere, but it was not what I was looking for.

**Comment by soyuka** [comment]
Not sure I get your issue, to me you don't need any `Subresource` in your case.

**Comment by julienpillias** [comment]
Yes, I understood that I don't need Subresource, it's ok for this.

But still can't have : 
```json
{
    "@context": "/app_dev.php/contexts/House",
    "@id": "/app_dev.php/houses/437",
    "@type": "House",
    "id": 437,
    "name": "House name",
    "departments": [
        {
            "@id": "/app_dev.php/departments/72",
            "id": 72,
            "name": "Department name"
        }, 
        ...
    ]
}
```

without using : 
```
 * attributes={
 *          "normalization_context"={"groups"={"list"}}
 *     }
```
on the House side.

I don't know if it's possible without using groups on House. My hope was to have all House(s) informations(without using groups),  and having department informations in the same response. Possible ?

**Comment by soyuka** [comment]
> I don't know if it's possible without using groups on House. My hope was to have all House(s) informations(without using groups), and having department informations in the same response. Possible ?

I don't think you can get the relations without using groups. What's bothering you by using a group on `House`?

**Comment by julienpillias** [comment]
I have a quiete large project to manage, and lots of different case where I need to display or not some informations. So I already will have lots of groups. This will be one more...
I'll deal with it :)

**Comment by soyuka** [comment]
Use yaml to manage your groups instead of `@Groups` it gets easier ;).

**Comment by toby-griffiths** [comment]
@julienpillias Did you manage to resolve this?

If you're still having problems with this, or for anyone else coming across this, you will need to add the serialisation group to the fields in the resource you want embedded… e.g. Add `@Groups({"list"})` to at least 1 field in the resource to be embedded (Department) before it will embed the resource.

In this example, you would add `@Groups({"list"})` to the `$id` and `$name` properties of the `Department` resource.
