### ISSUE TITLE
[Question] Eliminate dynamic routes

### ISSUE THREAD

**Issue by devrck** [api-platform/api-platform#428]
Hello,

How can I eliminate from api platform routes that are dynamically generated by relationship between objects?

**Comment by Simperfit** [comment]
Could you please give us an exemple ?

Do you mean subresources ?

**Comment by devrck** [comment]
Yes it's regarding another issue i'ved opened that @soyuka answered that it does the correct behaviour.
To give you the same example:
A has a subresource B[]
B has a subresource A

Api Platform will generate routes like:
A/{id}/B
A/{id}/B/A -> this i want to eliminate 
B/{id}/A

**Comment by soyuka** [comment]
We will avoid duplicates :) 

issue: https://github.com/api-platform/core/issues/1371

I answered there.
