### ISSUE TITLE
Rename alias to FQCN in services' name

### ISSUE THREAD

**Issue by mzmgh** [api-platform/api-platform#429]
These are Symfony 3.3.9 logs
> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "api_platform.serializer.context_builder.filter.inner" service to "ApiPlatform\Core\Serializer\SerializerContextBuilder" instead.

> Autowiring services based on the types they implement is deprecated since Symfony 3.3 and won't be supported in version 4.0. You should rename (or alias) the "api_platform.listener.request.deserialize" service to "ApiPlatform\Core\EventListener\DeserializeListener" instead.

![image](https://user-images.githubusercontent.com/12869372/31010325-5b2ae792-a517-11e7-9fca-1bcaa5477bec.png)

**Comment by dunglas** [comment]
We must add new aliases, not rename the existing ones or it would be a BC break.

**Comment by Simperfit** [comment]
@dunglas Do we add aliases on every services or on just thoses twos ?
