### ISSUE TITLE
Fresh create-project install schema generator without custom RDFa support.

### ISSUE THREAD

**Issue by dav-m85** [api-platform/api-platform#43]
After following successfully the [tutorial here](https://api-platform.com/doc/1.0/getting-started/api), I intended to create my very own RDFa declaration and play with it.

When launching the schema command, I got `Type "QuestionTest" cannot be found.`, and ended up looking at my composer, found out that schema-generator is fixed to v1.0.0.

You need to update to dev-master to leverage the new vocabularyNamespace schema key, which is not obvious when reading the tutorial. Hope it'll help someone.

**Comment by Simperfit** [comment]
Thanks you for the repport.

BTW schema-generator is no more included by default with V2.
