### ISSUE TITLE
POST with nested resources : Foreign key not set on third level resource

### ISSUE THREAD

**Issue by Atala** [api-platform/api-platform#430]
Hey, 

I would need some help with a bug (?) I encounter on denormalization. Feel free to ask for more informations or debug actions.

ApiPlatform : 2.1.1
Doctrine : 2.5.10

I have an issue on POST. I have the following entities :
 - Order which can have many OrderItem 
 - OrderItem which can have many OrderItemModifier

When I POST on `/orders`, all is fine except that the foreign key on OrderItemModifier towards OrderItem is not set (`null`) in DB (although (1) the other fields for OrderItemModifier are fine and (2) the response from the POST is correct, i.e. I can see the OrderItemModifier resources in the JSON).

Order denormalization context is set [here](https://github.com/coopcycle/coopcycle-web/blob/0ef45e6c173fbfa1d242f7be59e2db5897b4dbd7/src/AppBundle/Entity/Order.php#L38). All denormalization is done with the same group "order".

Order to OrderItem relation is defined [here](https://github.com/coopcycle/coopcycle-web/blob/0ef45e6c173fbfa1d242f7be59e2db5897b4dbd7/src/AppBundle/Entity/Order.php#L78-L84) : 
```php
    /**
     * @var OrderItem The item ordered.
     *
     * @Groups({"order"})
     * @ORM\OneToMany(targetEntity="OrderItem", mappedBy="order", cascade={"all"})
     */
    private $orderedItem;
```

OrderItem to OrderItemModifier is defined [here](https://github.com/coopcycle/coopcycle-web/blob/0ef45e6c173fbfa1d242f7be59e2db5897b4dbd7/src/AppBundle/Entity/OrderItem.php#L70-L74):
```php

    /**
     * @ORM\OneToMany(targetEntity="AppBundle\Entity\OrderItemModifier", mappedBy="orderItem", cascade={"all"})
     * @Groups({"order"})
     */
    private $modifiers;
```

The project is [opensource](https://github.com/coopcycle/coopcycle-web).

Thanks for maintaining the project & for your help !

**Comment by soyuka** [comment]
Could you give the data used to POST?

**Comment by Atala** [comment]
Here's the request : 
```json
{
  "restaurant": "/api/restaurants/1",
  "orderedItem": [
    {
      "quantity": 1,
      "menuItem": "/api/menu_items/2",
      "modifiers": [
        {
          "name": "Clafoutis au sucre glace",
          "description": null,
          "modifier": "/api/menu_item_modifiers/1"
        }
      ]
    }
  ],
  "delivery": {
    "date": null,
    "deliveryAddress": "/api/addresses/198"
  }
}
```

The response is : 
```json

**Comment by soyuka** [comment]
I don't really get from where it could come, as long as you have `adders` for collections and correct `denormalization` groups it should work. Looks like the case here (or maybe a bug related to `IDENTITY` strategy?). Can you also check the symfony profiler, you should see the denormalized entity there (Request section).

**Comment by Atala** [comment]
I am querying the API from JS, maybe I can dump something [here](https://github.com/coopcycle/coopcycle-web/blob/master/src/AppBundle/Serializer/OrderNormalizer.php) ?

Hopefully it is not linked to `IDENTITY` as we are forced to use it with PostGres ([ref](https://github.com/doctrine/doctrine2/issues/6429))

**Comment by Atala** [comment]
What puzzled me is that it is working fine with the relation between `Order` and `OrderItem`. Here's generated SQL:
```
[2017-10-02 10:32:06] doctrine.DEBUG: INSERT INTO order_ (status, created_at, updated_at, customer_id, restaurant_id) VALUES (?, ?, ?, ?, ?) {"1":"CREATED","2":"2017-10-02 10:32:06","3":"2017-10-02 10:32:06","4":1,"5":1} []
[2017-10-02 10:32:06] doctrine.DEBUG: INSERT INTO order_item (quantity, name, price, menu_item_id, order_id) VALUES (?, ?, ?, ?, ?) {"1":1,"2":"Tomates fraîches à l'huile [...]","3":8.99,"4":2,"5":41} []
[2017-10-02 10:32:06] doctrine.DEBUG: INSERT INTO order_item_modifier (name, description, order_item_id, modifier_id) VALUES (?, ?, ?, ?) {"1":"Clafoutis au sucre glace","2":null,"3":null,"4":1} []
```

Could it be caused by Doctrine Cache issues?

**Comment by soyuka** [comment]
> I am querying the API from JS, maybe I can dump something here ?

You should have the profiler url in the Response headers. 

Though nesting should use the same code (in the normalizer). If the denormalized result looks good (ie the relation does show up in the profiler) it should save it correctly IMO. I sadly don't have the time to try and reproduce this for now :|.

**Comment by Atala** [comment]
Everything looks fine in the profiler.

I have a workaround for now, maybe let this issue opened and come back on it later on?

**Comment by Simperfit** [comment]
@Atala Maybe you could provide a reproducer in the project you linked in the form of a branch so we could look at it ?

**Comment by Atala** [comment]
Hey @Simperfit , I think it will be easier for you if I spin up a simpler Symfony project (and so we could see if it's reproductible). I will do that and come back to you.

**Comment by edwardselby** [comment]
Did this ever get looked at?

**Comment by Simperfit** [comment]
@Atala is it still an issue ?

**Comment by Atala** [comment]
No I don't think so.

Sorry I didn't have time to reproduce it :/

Thanks for your work!
