### ISSUE TITLE
Unnecessary count query for custom route

### ISSUE THREAD

**Issue by maximecrtmc** [api-platform/api-platform#436]
Hi

I have a custom route to retrieve some datas from the logged token (ie user id and email)

```
    /**
     * @Route(
     *     name="user_reload",
     *     path="/users/reload",
     *     defaults={"_api_resource_class"=User::class, "_api_collection_operation_name"="reload"}
     * )
     * @Method("GET")
     *
     * @return array
     */
    public function reloadAction()
    {
        return $this->getDoctrine()
                    ->getRepository('AppBundle:User\User')
                    ->getDataForToken($this->getUser());
    }
```
the entity
```
/**
 * User
 *
 * @ORM\Table(
 *     name="user",
 *     uniqueConstraints={
 *     @ORM\UniqueConstraint(name="mail", columns={"mail"})}
 * )
 * @ORM\Entity(repositoryClass="AppBundle\Repository\UserRepository")
 * @UniqueEntity(fields="mail", message="constraints.unique_email")
 * @ApiResource(
 *     collectionOperations={
 *     },
 *     itemOperations={
 *          "get"={"method"="GET", "normalization_context"={"groups"={"detail"}}, "access_control"="is_granted('ROLE_USER') and object.getId() == user.getId()"},
 *          "reload"={"route_name"="user_reload"},
 *     }
 * )
 */
```
and in the repository
```
    /**
     * @param User $user
     *
     * @return array
     */
    public function getDataForToken(User $user)
    {
        /**
         * TODO get real value for nbItemCart
         */
        return array(
            'id'         => $user->getId(),
            'email'      => $user->getMail(),
            'nbItemCart' => rand(0, 10),
        );
    }
```
it return the good values. But when I check the symfony profile, I see a count query
```
SELECT count(DISTINCT u0_.id) AS sclr_0 FROM user u0_
```

this query is not necessary, how can I avoid it ?

I tried to turn the pagination off globally and/or for the entity (with attribute annotation), but then api-platform tried to retrieve all my users which cause a memory error (database have +1M users)

**Comment by tmbdrogba** [comment]
👍

**Comment by julienpillias** [comment]
Same problem here with a custom operation on itemOperations.

**Comment by soyuka** [comment]
`_api_collection_operation_name` should be `_api_item_operation_name`

**Comment by maximecrtmc** [comment]
With `_api_item_operation_name` I have a `Not Found` error
I bet this is because for item operation, the ID is required. But I don't have the ID here

I tried to rename the route to `/usersreload` to not cause issue with `/users/{id}` but this is not working too

**Comment by meyerbaptiste** [comment]
IMO and from a REST point of view, your custom action should be an item operation and your custom route path should be `/users/{id}/reload` with an access control like `object.getId() == user.getId()`.

But if you want to keep your way doing things, just don't use custom operations for that: a normal Symfony controller does the trick.

The `COUNT` query is normal because of the pagination here.
