### ISSUE TITLE
Extending schema.org types - how to maintain custom RDF schema?

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/api-platform#44]
Is it possible to have dynamically generated RDF Schema in JSON-LD? Perhaps by adding some annotations on the classes and attributes...

Handwriting custom schemas require a steep learning curve, but they also easily become outdated / out-of-sync with the actual resource types.

An example I found (outdated; converted from schema.org RDFa): https://github.com/ruby-rdf/json-ld/blob/develop/example-files/schema.org.jsonld

**Comment by dunglas** [comment]
It should be possible relatively easily using the Symfony PropertyInfo Component: http://symfony.com/blog/new-in-symfony-2-8-propertyinfo-component

If you're interested in working on that, we can create a new project in this org that you can lead.

Another way can be to generate back the RDF definition from the YAML file of the schema generator (as it now supports custom properties).

**Comment by Simperfit** [comment]
This will not be done in core or in standard edition, closing them.
