### ISSUE TITLE
Can't group data using DQL

### ISSUE THREAD

**Issue by DariuszLuber** [api-platform/api-platform#442]
Hi.

I want to create filter which group data by date or month or year, so I created a filter as a service in which I change DQL:

`$queryFields = 'YEAR(o.date) as year, Month(o.date) as month, DAY(o.date) as day, SUM(o.quantity) as quantity, SUM(o.quantity * o.priceNet) as totalValue';

        $emConfig = $queryBuilder->getEntityManager()->getConfiguration();
        $emConfig->addCustomDatetimeFunction('YEAR', 'DoctrineExtensions\Query\Mysql\Year');
        $emConfig->addCustomDatetimeFunction('MONTH', 'DoctrineExtensions\Query\Mysql\Month');
        $emConfig->addCustomDatetimeFunction('DAY', 'DoctrineExtensions\Query\Mysql\Day');

        $queryBuilder->resetDQLPart('select');
        $queryBuilder->resetDQLPart('join');

        $queryBuilder->select($queryFields)
            ->groupBy('year')
            ->addGroupBy('month')
            ->addGroupBy('day');`

When I try to use it i get error:

> An exception occurred while executing 'SELECT count(DISTINCT d0_.id) AS sclr_0 FROM drug_sale d0_ GROUP BY , , '

I get it that this is used to recive total ammount of records.

Of cource I can create new action and enpoint for all my three cases, but tell me if I can do that by filter and overwrite the total quantity?

**Comment by Chrysweel** [comment]
Maybe you need execute in mysql:

>SET global sql_mode='STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';

**Comment by teohhanhui** [comment]
You're trying to do an invalid SQL query: https://dev.mysql.com/doc/refman/5.7/en/group-by-handling.html

Please do not change the `sql_mode` to disable this check, but fix your query instead. :smile:
