### ISSUE TITLE
MultiLevel InheritanceType not properly using Groups serialization for parent entities

### ISSUE THREAD

**Issue by Julien-Marcou** [api-platform/api-platform#443]
Hello, I'm working on a dynamic Survey building engine, which allow you to define several type of Questions and several types of Answers, so I'm using InheritanceType to make it.
The base model looked like that :

Survey has many Questions
Question has one Answer
Question inheritance type mapping was [numeric=NumericQuestion, string=StringQuestion, enum=EnumQuestion...]
Answer inheritance type mapping was [numeric=NumericAnswer, string=StringAnswer, enum=EnumAnswer...]

It worked well with API Platform until I decided to add a new type of Question/Answer that extend from an already existing Question/Answer.
The new model now looks like this :

Survey has many Questions
Question has one Answer
Question inheritance type mapping is [numeric=NumericQuestion, string=StringQuestion, enum=EnumQuestion, string_attachment=StringWithAttachmentQuestion...]
Answer inheritance type mapping is [numeric=NumericAnswer, string=StringAnswer, enum=EnumAnswer, string_attachment=StringWithAttachmentAnswer...]

Obviously StringWithAttachmentQuestion/StringWithAttachmentAnswer extends StringQuestion/StringAnswer, but now API Platform is all broken for StringQuestion and StringAnswer routes.

It looks like that StringQuestion and StringAnswer are not using the normalization_context/denormalization_context ; so all fields are returned from GET queries and all fields are fillable with a POST query (instead of restricting them to those who are marked with the correct normalization_context/denormalization_context).
Even more problematic, calling route for StringQuestion and StringAnswer also returns the fields of the StringWithAttachmentQuestion and StringWithAttachmentAnswer entities (with null values).

**Comment by Julien-Marcou** [comment]
I made a basic representation of the model to help you understand the problem :)

Working :
![before](https://user-images.githubusercontent.com/4369075/32105856-3dd76994-bb2a-11e7-98c7-9acc7075f751.PNG)

Not working (i.e. StringQuestion and StringAnswer serialization and deserialization are not used at all) :
![after](https://user-images.githubusercontent.com/4369075/32105857-3dedf128-bb2a-11e7-95ef-0eaa2c7fb354.PNG)

**Comment by soyuka** [comment]
What kind of inheritance is that ? Inheritance is usually a bad idea by the way and yes we have some issues with doctrine inheritance but they mostly end up in "wontfix".

Btw your first message is totally unreadable to me :laughing: From what I understood then, you should use a `type` column instead of using inheritance, there's no point here.

**Comment by Julien-Marcou** [comment]
Yep, should rewrite my issue 😖

I'm using Single Table inheritance :
```
/**
 * Answer
 *
 * @ORM\Table(name="answer")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\AnswerRepository")
 * @ORM\InheritanceType("SINGLE_TABLE")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({"string" = "StringAnswer", "numeric" = "NumericAnwser", "string_attachment" = "StringWithAttachmentAnwser"})
 */
```

I agree that inheritance may be a bad idea (and I'm aware that it could involves adding new columns to the base table which could lead to big crappy table).
It looks like it's not the most adequate solution in my example, but it is a simplification of the real model I have.

In my case StringWithAttachmentAnswer define a new mandatory OneToOne relation to a Document entity (so a document must be attached to that kind of answer), this is why it's quite handy for my real model to have these kind of inheritances.

**Comment by Julien-Marcou** [comment]
After a long headache, I finally found the solution, I simply have to use two different normalization contexts, one for StringWithAttachmentQuestion and one for StringQuestion and it solves the problem.

However, I've tried that before and I tought it was not working because of API Platform not rendering the right "Exemple Value" nor the right "Model".

So you can close this issue, I'll open a new one with a complete Gist to explain this bug.
