### ISSUE TITLE
Simpler way to GET/POST/PUT resources associated with a user ?

### ISSUE THREAD

**Issue by leogout** [api-platform/api-platform#449]
Hi, I am trying ApiPlatform in a sandbox project along with FosUserBundle and LexikJWTAuthenticationBundle.
I have two entities : Music and User. A User can have multiple Musics.

To POST or PUT a music, I am using an EventSubscriber to automatically associate the Music to the current User, as [described here](https://api-platform.com/docs/core/events).

To GET the musics of my current user, I am using the `@ApiSubresource` annotation which exposes the following route: `/api/users/{id}/musics.{_format}` as [described here](https://api-platform.com/docs/core/operations#subresources).

Is there a way to only use events to GET/POST/PUT ? Or to only use the ApiSubresource ? My app will articulate a lot around this User entity, so I was wondering if I had to do this everytime or if there is something simpler that I am missing.

Thanks for your time and for this cool bundle !

**Comment by soyuka** [comment]
Should the so called user be authenticated when issuing write requests?

Write support is not available yet with subresources.

**Comment by leogout** [comment]
The user should be (and is) authenticated when issuing write requests.
Okay, I'll do without it, thanks !

**Comment by soyuka** [comment]
Then I'd use the token or the session to do the link instead of using a simple ID with no authentication check (which could be dangerous). I mean that if you have the user (TokenStorage for example) you don't really need it in the url no?

**Comment by leogout** [comment]
Yeah you are right, that was a bad idea. At least I'll know it's not possible for non critical resources as well !
