### ISSUE TITLE
how to get the @value attribute working in Json-LD?

### ISSUE THREAD

**Issue by leroy0211** [api-platform/api-platform#45]
Is there any known way of how the add the @value attribute to an attribute? Or a way to alias this in the @context? 

I can't find any solution.

**Comment by dunglas** [comment]
To customize the output of the JSON (e.g. add new fields), you can decorate the service called `api.json_ld.normalizer.item` using [service decoration](http://symfony.com/doc/current/components/dependency_injection/advanced.html#decorating-services).

To change the context, you can use [JSON-LD context events](https://api-platform.com/doc/1.0/api-bundle/the-event-system#json-ld-context-builder).

But AFAIK, there is no `@value` property in JSON-LD.

**Comment by leroy0211** [comment]
Ok. Let me try that. 
But this JSON-LD documentation states that there is an `@value` property. At the `typed-values` section.

http://json-ld.org/spec/ED/json-ld-syntax/20120522/#typed-values

I was trying to use [this lib](https://github.com/lanthaler/JsonLD) as a basic client for api-platform. As for a simple test on the people api, it failed because of the `@value` attribute not available.

**Comment by dunglas** [comment]
API Platform generates JSON-LD documents in their compacted form (without `@value`). It should work with Markus lib without any modification server-side. Can you post the failing snippet?

**Comment by Simperfit** [comment]
@leroy0211 Closing this as this is old. If you want to comment on this please update this issue.
