### ISSUE TITLE
property filter on nested attributes

### ISSUE THREAD

**Issue by mcanepa** [api-platform/api-platform#452]
I'm implementing [property filters](https://api-platform.com/docs/core/filters#property-filter)...

So far it's working great on _first level_ attributes, but how can I filter on a nested property?

Having this json response as an example

```
{
	"@id": "/app_dev.php/contacts/123",
	"@type": "Contact",
	"firstName": "John",
	"lastName": "Doe",
	"addresses": [{
		"@id": "/app_dev.php/contact_addresses/456",
		"@type": "ContactAddress",
		"address": {
			"@id": "/app_dev.php/addresses/789",
			"@type": "Address",
			"street": "somewhere",
			"doorNumber": 666,
			"latitude": 34.8679771,
			"longitude": -96.7807523
		}
	}]
}
```

If i do a `GET` with `/contacts?properties[]=firstName`, the response is

```
{
	"@id": "/app_dev.php/contacts/123",
	"@type": "Contact",
	"firstName": "John"
}
```

But what if I want the latitude? How can I filter to that property? I've tried something like `/contacts?properties[]=addresses.address` but obviously it is not working

**Comment by soyuka** [comment]
`properties[adresses][]=address`

**Comment by mcanepa** [comment]
thank you very much!

**Comment by Simperfit** [comment]
Issue moved to the doc repository.
