### ISSUE TITLE
Virtual Properties

### ISSUE THREAD

**Issue by Dakhtara** [api-platform/api-platform#455]
I need for a ressource to add an absolute link that is generated when the user asks a resource, so it can't be used in the Entity but in a Service or maybe an Event. 

It seems that there is no documentation about it. Is it possible to add virtual properties ?

Do you have any example ?

Thanks

**Comment by soyuka** [comment]
just add a getter/public property in the entity and serialize it with groups.

**Comment by Dakhtara** [comment]
Thanks for the reply but that's not what I'm looking for. My entity should not depend on a service like the router of symfony to generate an absolute link. Do you have any other way to do this ?

**Comment by dunglas** [comment]
You can decorate the ItemNormalizer to add the new property then (there is a doc about this).

**Comment by Dakhtara** [comment]
As the doc show here : [https://api-platform.com/docs/core/serialization#decorating-a-serializer-and-add-extra-data](https://api-platform.com/docs/core/serialization#decorating-a-serializer-and-add-extra-data)

It looks easy, I add the example 
``` yaml    
AppBundle\Serializer\ApiNormalizer:
        decorates: 'api_platform.jsonld.normalizer.item'
        arguments: [ '@AppBundle\Serializer\ApiNormalizer.inner' ]
        autoconfigure: false
```

I copy paste the exact same ApiNormalizer in my src/AppBundle/Serializer 
``` php
<?php

namespace AppBundle\Serializer;

use ApiPlatform\Core\Serializer\AbstractItemNormalizer;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

final class ApiNormalizer extends AbstractItemNormalizer
{
    private $decorated;

    public function __construct(NormalizerInterface $decorated)
    {
        $this->decorated = $decorated;
    }

    public function supportsNormalization($data, $format = null)
    {
        return $this->decorated->supportsNormalization($data, $format);
    }

    public function normalize($object, $format = null, array $context = [])
    {
        $data = $this->decorated->normalize($object, $format, $context);
        if (is_array($data)) {
            $data['date'] = date(\DateTime::RFC3339);
        }
        return $data;
    }

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $this->decorated->supportsDenormalization($data, $type, $format);
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        return $this->decorated->denormalize($data, $class, $format, $context);
    }
}
```

And this is my output in jsonld. 
``` json
{
    "@context": "/app_dev.php/contexts/Audit",
    "@id": "/app_dev.php/audits",
    "@type": "hydra:Collection",
    "hydra:member": [],
    "hydra:totalItems": 0
}
```

As you can see there is no output of the date. 
My composer json looks for api-platform/core : "^2.1"
Is there any issue withe the ItemNormalizer for this version ?

**Comment by soyuka** [comment]
>     "hydra:totalItems": 0

Looks like there are no items in your collection therefore nothing gets normalized.

**Comment by Dakhtara** [comment]
Yes right, It was because of my token. But now i'm facing a new issue.

``` json
    "@context": "/app_dev.php/contexts/Error",
    "@type": "hydra:Error",
    "hydra:title": "An error occurred",
    "hydra:description": "Call to a member function normalize() on null",
    "trace": [
        {
            "namespace": "",
            "short_class": "",
            "class": "",
            "type": "",
            "function": "",
            "file": "/var/www/symfony/vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php",
            "line": 426,
            "args": []
        },
```

This is the new output. It goes well in the ApiNormalizer but it can't  call the normalize() on null.

**Comment by acidline** [comment]
Hi,

I have the same problem. If I decorate the "api_platform.jsonld.normalizer.item" service, serializer is null in the method getAttributeValue() of AbstractItemNormalizer class.

Same error than @Dakhtara

**Comment by Swahjak** [comment]
Was having the same problem, this is my guess on what is going wrong;

The documentation is incorrect:

- First. Since the service is decorated with api_platform.jsonld.normalizer.item there is no point in extending ApiPlatform\Core\Serializer\AbstractItemNormalizer because the constructor is not being called. That's why the errors show up; the extended AbstractItemNormalizer was never initialized.

- Second. The service as displayed in the documentation should contain both methods from Symfony\Component\Serializer\Normalizer\NormalizerInterface and Symfony\Component\Serializer\Normalizer\DenormalizerInterface. So you have to copy the entire example service, not just the methods you need.

Could be wrong, but removing the 'extends AbstractItemNormalizer' and adding all the methods seems to do the trick for me.

**Comment by Swahjak** [comment]
Ok, that worked until a cache flush. Now I'm getting Call to a member function normalize() on null in vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php:426. For some reason the serializer is not injected (or I was completely wrong to begin with).

**Comment by acidline** [comment]
Hi,

@Swahjak In your StockItemNormilizer, you implements a custom Normelizer.

For me, the problem is when I want to extend the AbstractItemNormalizer (via Decorator)

It seems that Serializer is never set, that's why null is return on object method call.

**Comment by acidline** [comment]
Doc has been updated, [Decorating a Serializer and Add Extra Data](https://api-platform.com/docs/core/serialization#decorating-a-serializer-and-add-extra-data) but problem is still there.

Doc says : 

``` yaml
# app/config/services.yml
services:
    'AppBundle\Serializer\ApiNormalizer':
        decorates: 'api_platform.jsonld.normalizer.item'
        arguments: [ '@AppBundle\Serializer\ApiNormalizer.inner' ]
```
This error is throw : 

```
[Symfony\Component\DependencyInjection\Exception\RuntimeException]
  The definition "serializer" has a reference to an abstract definition "abstract.instanceof.AppBundle\Serializer\DecoratingApiNormalizer". Abstract definitions cannot be the target of references.
```

With "autoconfigure: true" in service definition, no error throw but I have the fllowing error (same that previous) : 

```
Call to a member function normalize() on null in vendor/api-platform/core/src/Serializer/AbstractItemNormalizer.php:426.
````
We loose serializer instance on decorated object.

**Comment by meyerbaptiste** [comment]
Hi @acidline, do you think you can create a small public project to reproduce this issue? I tested, I can't reproduce, same for @Simperfit. It's just a classic decorator service, no reason it doesn't work.

**Comment by Aerendir** [comment]
Good morning at all!

I have another problem following the documentation: a circular referenc eerror:

> Circular reference detected for service "AppBundle\Serializer\ApiNormalizer", path: "AppBundle\Serializer\ApiNormalizer -> serializer -> AppBundle\Serializer\ApiNormalizer".

I have simply copied and pasted the [code found in the docs](https://api-platform.com/docs/core/serialization#decorating-a-serializer-and-add-extra-data).

Any ideas about what's going on?

**Comment by acidline** [comment]
@Aerendir 

You must copy / paste your service definition after "_default" section.

**Comment by Aerendir** [comment]
@acidline works!!! Thank you for the really fast fix! :)

**Comment by Aerendir** [comment]
Ok, I'm now on point: now I'm receiving the famous error

> Call to a member function normalize() on null

**Comment by Aerendir** [comment]
Solved for me:

```
    AppBundle\Serializer\ApiNormalizer:
        decorates: 'api_platform.jsonld.normalizer.item'
        arguments: [ '@AppBundle\Serializer\ApiNormalizer.inner' ]
        tags: ['serializer.normalizer']

    AppBundle\Serializer\ApiNormalizer.inner:
        tags: ['serializer.normalizer']
```

You have to add the tag `serializer.normalizer` to the `AppBundle\Serializer\ApiNormalizer.inner`.

The original service has this tag (https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Bundle/Resources/config/jsonld.xml#L29).

It seems that decorating the service removes the tag and so the `Serializer` is not injected.

**Comment by acidline** [comment]
+1 @Aerendir 

It's work for me too ! ;)

@meyerbaptiste Do you already need my broken demo ?

**Comment by Aerendir** [comment]
Anyway I think this is a Bug of Symfony itself, not of API Platform.

@dunglas , what do you think about? Should an issue has to be opened in the Symfony repo?

**Comment by SalvatorePollaci** [comment]
Hi guys, whats the difference between:
1)Writing a custom normalizer(https://api-platform.com/docs/core/content-negotiation/#writing-a-custom-normalizer)
2)Decorating a serializer(https://api-platform.com/docs/core/serialization#decorating-a-serializer-and-add-extra-data)
? Thanks!

**Comment by Aerendir** [comment]
@SalvatorePollaci I think that you should open a new issue for this question: it will help keep the issues organized.

**Comment by alexislefebvre** [comment]
I had the same error with Symfony 3.3 and the example from the [documentation](https://api-platform.com/docs/core/serialization/#decorating-a-serializer-and-add-extra-data).

Adding `autoconfigure: false` to the definition of `'AppBundle\Serializer\ApiNormalizer':` fixed the issue.

Thanks all.

**Comment by abysKri** [comment]
Hi
Is there a way to do the same think with json format ?
Thanks

**Comment by teohhanhui** [comment]
@abysKri Please open a new issue for your question.

**Comment by abysKri** [comment]
Sorry, thanks i found .
