### ISSUE TITLE
[Support] The property path constructor needs a string or an instance of... (speaking about relations)

### ISSUE THREAD

**Issue by Aerendir** [api-platform/api-platform#458]
I have the entity `Supplier`:

```php
/**
 * @ORM\Entity
 * @ORM\Table(name="coo_business_suppliers")
 * @ApiResource()
 */
class Supplier
{
    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", nullable=false)
     */
    protected $name;
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var Account
     *
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Account", inversedBy="suppliers")
     * @ORM\JoinColumn(name="account", referencedColumnName="id")
     * @Groups({"get"})
     */
    private $account;

    ...

    /**
     * @param Account $account
     *
     * @return Supplier
     */
    public function setAccount(Account $account): self
    {
        $this->account = $account;

        return $this;
    }
```

And obviously I have also the entity `Account`.

Now, when I create a new `Supplier` I have to pass the `account` to which it belongs, too.

But this doesn't work with the "Try it out" interface provided by ApiPlatform in the list of resources supported.

The "Example value" is this:

```json
{
  "id": 0,
  "account": "string",
  "name": "string"
}
```

So I click on "Try it out" and change the `body` to this:

```json
{
  "account": "1",
  "name": "A test supplier"
}
```

As you can see, I've removed the `id` property and set the `account` to `1` (as a `string`): `1` is the ID of the `Account` I'm currently using and I'm hardcoding it just to understand how the entire flow works.

Now, when I submit this `POST` request, I receive a "Bad request" error:

```json
{
  "@context": "/api/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "The property path constructor needs a string or an instance of \"Symfony\\Component\\PropertyAccess\\PropertyPath\". Got: \"integer\"",
...
```
Then there is the full trace that I'm omitting for brevity (ask me if you need it to help me!).

As you can see, the property `account` is handled as an integer.

But my question goes further: currently it is a simple number, while I need an `Account` object (you can see `Supplier::setAccount(Account $account)` signature: it requires a Doctrine's hydrated object.

So, I think that the problem is not limited to the `string`/`integer`.

I think that somewhere I have to get the `Account` from the database and inject it in the creating entity.

But, how can I do this?

Should have I to create a custom controller? Or maybe hooking into events is sufficient (I have read I can [hook into Doctrine's events](https://api-platform.com/docs/core/events) but currently I have not understood how to do this).

Can you help me solve this issue? Thank you!

**Comment by soyuka** [comment]
Must be a `json-ld` identifier (ie: '/api/accounts/1') or an account object (check also how serialization groups work).

**Comment by Aerendir** [comment]
`Account` isn't set to be an api resource:

```php
/**
 * Account.
 *
 * @ORM\Table(name="coo_app_accounts")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\AccountRepository")
 */
class Account
{
    use TimestampableEntity;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     * @Groups({"get", "post"})
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    ...

    /**
     * @var Collection
     *
     * @ORM\OneToMany(targetEntity="Coommercio\Bundle\BusinessBundle\Entity\Supplier", mappedBy="account")
     */
    private $suppliers;

    ...
```

Also, I'm using serialization groups to avoid circular reference errors: maybe this can cause the issue?

**Comment by Aerendir** [comment]
Ok, setting the entity `Account` as an `ApiResource` and using its IRI works:

```json
{
  "account": "api/accounts/1",
  "name": "A test supplier from ApiPlatform"
}
```

But remains the problem, I don't want `Account`s to be exposed... If I have to expose it, I'll do, but if there is another solution...

**Comment by soyuka** [comment]
What do you mean by "expose"? Just use serialization groups to hide in in `normalization` but keep it in`denormalization`.

**Comment by Simperfit** [comment]
@Aerendir is it ok for you ?

**Comment by Aerendir** [comment]
@Simperfit , excuse me if didn't reply you: I missed the notification! Anyway it's ok for me, thank you!

Excuse me...

**Comment by red-smeg** [comment]
Can you post the solution

**Comment by SundownDEV** [comment]
Could you post the solution please @Aerendir ?
