### ISSUE TITLE
Best way to implement ID obfuscation?

### ISSUE THREAD

**Issue by bwegrzyn** [api-platform/api-platform#462]
I've been using UUIDs in my application for some time now, but I find them cumbersome and long, especially when dealing with actual values in the database. I'd much rather stick with numerical IDs, but this ends up exposing them to everyone, which is undesirable for a number of reasons (even more so in a SaaS platform).

What would be the best way of implementing ID obfuscation? There are several libraries (such as [this one](https://github.com/zackkitzmiller/tiny-php/)) than can accomplish this, so I'm really more looking for insight in to how to override the serialization process to accomplish this. 

Overwriting the 'id' property is relatively simple with a custom normalizer, but overwriting the '@id' property is a different story. Any ideas on how to best accomplish this?

**Comment by soyuka** [comment]
https://github.com/api-platform/core/pull/1478 will definitely make things easier. You'd only have to use an `IdentifierNormalizer` (a service tagged `api_platform.identifier_normalizer`).

https://github.com/api-platform/core/pull/1478/files#diff-a64f26b0bdd79271630d630c078412a2R236

`id` and `@id` are basically the same.

**Comment by bwegrzyn** [comment]
Thanks @soyuka. This looks like exactly what I need, looking forward to seeing this released.

**Comment by Simperfit** [comment]
This PR has been merged.

**Comment by soyuka** [comment]
Let us know if you have issues implementing this. I added a documentation https://github.com/api-platform/docs/blob/master/core/identifiers.md
