### ISSUE TITLE
[Question] How to upgrade Api-Platform to the latest version?

### ISSUE THREAD

**Issue by Gramatton** [api-platform/api-platform#465]
I'm curious about how can I upgrade my Api-Platform project and other dependencies to the latest version using Docker environtment?
In Composer I used `composer upgrade` command to upgrade a project but I was initially created my project with Docker option.

**Comment by msitruk** [comment]
I m curious too. Is there a release note when upgrade is published ?

**Comment by teohhanhui** [comment]
For upgrading your project to follow the changes made in this distribution, you're on your own. The easiest thing to do is to compare, for example: https://github.com/api-platform/api-platform/compare/v2.2.8...v2.3.0

You'll have to go through it manually. :smile:
