### ISSUE TITLE
ApiSubresource max depth ?

### ISSUE THREAD

**Issue by Balkeo** [api-platform/api-platform#468]
Hello, 

I have a problem with the ApiSubresource function. I need for a project to be able to obtain a D entity to a url like 'a/1/b/1/c/1/d'.
But I'm getting : "[Semantical Error] line 0, col 202 near 'bs_a2.a IN(SELECT': Error: 'bs_a2' is used outside the scope of its declaration."

Ps :  the url of my sample project
https://github.com/Balkeo/Sample

**Comment by soyuka** [comment]
May you add the full SQL available in the profiler?

**Comment by Balkeo** [comment]
I just add DoctrineFixturesBundle and a Fixtures file.
