### ISSUE TITLE
Composer ambiguous class resolution with Symfony 3.3.13

### ISSUE THREAD

**Issue by Cbruyere** [api-platform/api-platform#471]
Hello, 
I just installed Api-Platform on my symfony 3.3.13 and I got those wanrnings on composer install/update :

`Warning: Ambiguous class resolution, "AppKernel" was found in both "$baseDir . '/app/AppKernel.php" and "C:\dev\io-instrumentation\visu\vendor/api-platform/api-platform/app/AppKernel.php", the first will be used.
Warning: Ambiguous class resolution, "AppCache" was found in both "$baseDir . '/app/AppCache.php" and "C:\dev\io-instrumentation\visu\vendor/api-platform/api-platform/app/AppCache.php", the first will be used.
`
Is there a solution to suppress those warnings please ?

Symfony 3.3.13 / composer 1.5.2 / api-platform 2.1.3

My composer.json :

`
{
    "name": "IO Instrumentation",
    "description": "A Symfony application",
    "license": "proprietary",
    "keywords": [
      "framework",
      "symfony",
      "io_instru",
      "bootstrap",
      "responsive"
    ],
    "type": "project",
    "config" : {
        "secure-http": false
    },
    "repositories": [
        {
            "type": "composer",
            "url": "http://xx.xx.xx.xx/server-ioinstru-composer/"
        },
    	{
       	    "packagist": false
    	}
    ],
    "autoload": {
        "psr-4": {
            "": "src/"
        },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "require": {
        "php": "^7.0",
        "symfony/symfony": "^3.3",
        "friendsofsymfony/user-bundle": "2.0.0",
        "doctrine/orm": "^2.5",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "symfony/monolog-bundle": "^3.1",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "symfony/assetic-bundle": "^2.8",
        "twig/extensions": "^1.4",
        "alcaeus/mongo-php-adapter": "^1.0",
        "doctrine/mongodb": "^1.3",
        "doctrine/mongodb-odm": "^1.1",
        "doctrine/mongodb-odm-bundle": "^3.2",
        "knplabs/knp-paginator-bundle": "^2.5",
        "ghunti/highcharts-php": "~3.0",
        "nelmio/api-doc-bundle": "^2.13",
        "friendsofsymfony/rest-bundle": "^2.1",
        "willdurand/js-translation-bundle": "^2.6",
        "jms/security-extra-bundle": "^1.6.1",
        "api-platform/api-platform": "^2.1.3",
        "mashape/unirest-php": "^3.0.4"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0",
        "phpunit/phpunit": "^4.8.0",
        "phpunit/php-code-coverage": "^2.1",
        "doctrine/doctrine-fixtures-bundle": "^2.3",
        "escapestudios/symfony2-coding-standard": "^3.0.1",
        "squizlabs/php_codesniffer": "^3.1.1",
        "site5/phantoman": "^1.1",
        "codeception/codeception": "^2.0",
        "codeception/c3": "^2.0"
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative"
    }
}

`

**Comment by Simperfit** [comment]
Feel free to ping me if you still have an issue, thanks!
