### ISSUE TITLE
Any interest in built-in Vagrant support here?

### ISSUE THREAD

**Issue by benburleson** [api-platform/api-platform#472]
It's nice to have Docker supported, but seems like there are a few of us that prefer Vagrant for our development. I prefer it because the VMs are more transparent and mimic my deployment environment.

Is there any support/interest for adding a Vagrantfile (and whatever necessary supporting scripts/configs) to make this run out of the box?

**Comment by Nightbr** [comment]
With my dev team, we use vagrant to create isolated devenv but provisionned by docker. With this, you can use the Api Platform docker env.

But if you want a Vagrant (vm) with raw php, nginx, ... I think you can create a project for this.

**Comment by dunglas** [comment]
I think it's interesting, but I would not add the config directly to the main repo becaus:

* we try to provide only one preferred way by default (and we'll stay with Docker for now)
* it will add unwanted files for most people

Do you think that it can be a documentation entry providing a good config? It can also be an official (but different) repo. Do you plan to use Homestead or Laravel directly? Maybe can it be nice to patch homestead to support API Platform natively?

**Comment by Simperfit** [comment]
As @dunglas said, if you have something already working, out-of-the-box, we could add it in the main organisation.
