### ISSUE TITLE
Column type "decimal" is expecting "string" values

### ISSUE THREAD

**Issue by byhoratiss** [api-platform/api-platform#475]
Hi, I've a column type "decimal" which is being worked as a "string".
I've made a change and set it as a "integer" and it works fine, so is there any possibilities to change the "type" of a property through configuration?
Is there any way to achieve this?

Orm Entity class (stripped)
```
class Lote
{
    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @var integer
     *
     * @ORM\Column(name="percent", type="decimal", precision=18, scale=2, nullable=true)
     * @Groups({"output"})
     */
    private $percent;
}
```

GET object response is (stripped):
```
  {
    "percent": "string"
  }
```

**Comment by soyuka** [comment]
This is correct see https://github.com/api-platform/core/issues/856.

**Comment by byhoratiss** [comment]
Ok, thanks!
