### ISSUE TITLE
How to make filter with depth relation

### ISSUE THREAD

**Issue by Dannebicque** [api-platform/api-platform#476]
Hello,

I use Api-Platform, and it is very amazing ! I use some filters and, It's OK form "direct" relation,  between two entity.

Now, I would like to make a filter, which can imply many "inner join" un classical SQL.

For example.

A document can have a semester (in university), and a semester is in relation with a year, and a year is in relation with a diploma.
With filter, I can access to document, from one semester. But, for the administration, i would like to access to all document from a year or a formation (=diploma).

I try to write an special action, but, I can't obtain the Id of the year or formation. So my question is, how to get a special parameters in GET request, in order to retrieve a collection of entities.
In a previous version, I would write "http://monsite/documents/formation/1", for all the documents associated to the formation with id 1.

<img width="1343" alt="capture d ecran 2017-11-29 a 17 24 55" src="https://user-images.githubusercontent.com/9027047/33385987-44044764-d52a-11e7-8d13-e1e80dffbf04.png">

How can I access to the id_formation param in my action ?

```
<?php
// src/AppBundle/Action/documentsFormation.php

namespace AppBundle\Action;

use AppBundle\Entity\Document;
use Doctrine\Common\Persistence\ManagerRegistry;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\Routing\Annotation\Route;

class documentsFormation
{
    private $manager;

    public function __construct(ManagerRegistry $manager)
    {
        $this->manager = $manager;
    }

    /**
     * @Route(
     *     name="documents_formation",
     *     path="/documents/formation/{id_formation}",
     *     defaults={"_api_resource_class"=Document::class, "_api_collection_operation_name"="formation"}
     * )
     * @Method("GET")
     */
    public function __invoke($id_formation)
    {
        $data = $this->manager->getRepository('AppBundle:Document')->findByFormation($id_formation);

        return $data;
    }
}
```
Entity
```
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use ApiPlatform\Core\Annotation\ApiResource;
use \Doctrine\Common\Collections\ArrayCollection;

/**
 * Document
 *
 * @ORM\Table(name="document")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\DocumentRepository")
 * @ORM\HasLifecycleCallbacks()
 * @ApiResource(
 *     attributes={"filters"={"documents.semestre_filter"}},
 *     collectionOperations={
 *      "get"={"method"="GET"},
 *      "formation"={"route_name"="documents_formation"}
 * })
 */

class Document
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;
...
```

Thanks for you help

David

**Comment by soyuka** [comment]
If want you want is "Document belonging to Relation X" you can use `@ApiSubresource` on the relation `X` inside the `Document` entity.

There's also an ability to filter on relations (or even nested properties) with most of our embed filters [see here](https://api-platform.com/docs/core/filters#filtering-on-nested-properties)

**Comment by Dannebicque** [comment]
Waouh OK ! It's amazing :)
I had not dared to write such a filter.

  documents.formation_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { semestres.annee.diplome.formation: 'exact' } ]
        tags: [ 'api_platform.filter' ]

And it works fine. Thanks
