### ISSUE TITLE
Create user with FosUser

### ISSUE THREAD

**Issue by pesseyjulien** [api-platform/api-platform#479]
Hi, 

I have enabled the FosUser bundle as per the documentation, but when I’m trying to add an user from the endpoint, I’m getting an error because the field ‘passwors’ Cannot be empty. How can I specify the password ? 

Thanks in advance,
Julien

**Comment by hotgeart** [comment]
Show us your JSON you tried to post.

**Comment by pesseyjulien** [comment]
I managed differently, thanks anyway !
