### ISSUE TITLE
2.1.4 api-platform supports Symfony 4?

### ISSUE THREAD

**Issue by hariszukanovic** [api-platform/api-platform#481]
The core project, declares support and seems to be using Symfony 4 in 2.1.4 
But the api-platform project uses Symfony 3.3.* in the same release. 
There is a reference in the composer.lock of Symfony 4 but not the composer.json
Will you bump the api-platform project to Symfony 4 as well?

**Comment by TangMonk** [comment]
Yes, I am using Symfony 4 now, it works great with api-platform

**Comment by BallisticPain** [comment]
@hariszukanovic I'm using master to use the SF4 stuff.

**Comment by hariszukanovic** [comment]
Thanx.
I have tried to update the composer.json to begin using Symfony 4.0 but I have unresolved dependencies problem. Not sure what exactly is needed to be fixed.
I will try to do my tests with master.
Perhaps not updating the composer.json to use new Symfony in api-platform project was intentional after all...

**Comment by Aerendir** [comment]
@hariszukanovic , the best way to update is starting with a fresh installation of SF4 and then move all your business code to this new version, practically rewriting the app.

Simply pushing the version will require more work and doesn't guarantee you will have the full functionalities of SF4, especially Flex.

Read here for more information: https://symfony.com/doc/current/setup/flex.html#upgrade-to-flex

**Comment by hariszukanovic** [comment]
I will try to setup from scratch. Thanx

**Comment by dleute** [comment]
Will the distribution be updated to use the flex structure? I chose to start my own app and add core because I didn't want to move to flex later. But I realized using all the pre-built container stuff requires me to go through and change paths, update docker files, update entry point scripts... etc.

Will there be a branch already in flex layout?

Thanks!

**Comment by jewome62** [comment]
@dleute master branche use actually the new flex structure

**Comment by dleute** [comment]
I missed that. IT's in the API folders and such. Awesome. switching to master.
