### ISSUE TITLE
angularjs-integration and client-generator docs lost

### ISSUE THREAD

**Issue by TangMonk** [api-platform/api-platform#484]
![image](https://user-images.githubusercontent.com/3498786/33706366-d9e7a4e8-db6e-11e7-8271-5299790bedf6.png)

![image](https://user-images.githubusercontent.com/3498786/33706367-de7a90a6-db6e-11e7-8737-d7d1ece289dd.png)

**Comment by jewome62** [comment]
That work currently.

https://api-platform.com/docs/core/angularjs-integration
https://api-platform.com/docs/client-generator/vuejs

**Comment by Simperfit** [comment]
There were issues with the website at some point, it is now stable.
