### ISSUE TITLE
How to remove $id* from Swagger docs

### ISSUE THREAD

**Issue by toby-griffiths** [api-platform/api-platform#485]
I've setup a `/users/me` endpoint to return the currently logged in user.  I've set this up as a custom GET item action, and am using an event listener to add the $id dynamically after authentication, however the Swagger is showing the $id property as a required field.

Can anyone advise how can I remove this from the Swagger docs?

**Comment by toby-griffiths** [comment]
I've actually worked this out now.  For anyone else finding this, you need to add the `swagger_context` to your operation config…

```
 * @ApiResource(
 *     ...
 *     itemOperations={
 *         "me"={
 *             "method"="GET",
 *             "route_name"="...",
 *             "swagger_context"={"parameters"={}}
 *         },
 *     },
 *     ...
 * )
```

**Comment by AntoscencoVladimir** [comment]
for me works

"openapi_context"={"parameters"={}}

**Comment by toar86** [comment]
> for me works
> 
> "openapi_context"={"parameters"={}}

not working anymore, any updates?

**Comment by s4mpl3d** [comment]
not working anymore, I tried: 
`"openapi_context"={"parameters"={}}`
and 
`"swagger_context"={"parameters"={}}`

but the id-parameter keeps showing up in swagger

**Comment by ttskch** [comment]
Decorating and customizing `api_platform.openapi.factory` service works well for me.

> refs: https://api-platform.com/docs/core/openapi/#overriding-the-openapi-specification

```php
<?php

declare(strict_types=1);

namespace App\ApiPlatform;

use ApiPlatform\Core\OpenApi\Factory\OpenApiFactoryInterface;
use ApiPlatform\Core\OpenApi\Model\Operation;
use ApiPlatform\Core\OpenApi\Model\Parameter;
use ApiPlatform\Core\OpenApi\Model\PathItem;
use ApiPlatform\Core\OpenApi\OpenApi;

class OpenApiFactory implements OpenApiFactoryInterface
{
    public function __construct(private OpenApiFactoryInterface $decorated)
    {
    }

    public function __invoke(array $context = []): OpenApi
    {
        $openApi = $this->decorated->__invoke($context);

        /**
         * @var string   $path
         * @var PathItem $pathItem
         */
        foreach ($openApi->getPaths()->getPaths() as $path => $pathItem) {
            // remove identifier parameter from operations tagged "withoutIdentifier"
            foreach (PathItem::$methods as $method) {
                $getter = 'get'.ucfirst(strtolower($method));
                $setter = 'with'.ucfirst(strtolower($method));
                /** @var Operation $operation */
                $operation = $pathItem->$getter();
                if ($operation && in_array('withoutIdentifier', $operation->getTags())) {
                    /** @var Parameter[] $parameters */
                    $parameters = $operation->getParameters();
                    foreach ($parameters as $i => $parameter) {
                        if (preg_match('/identifier/', $parameter->getDescription())) {
                            unset($parameters[$i]);
                        }
                    }
                    $openApi->getPaths()->addPath($path, $pathItem->$setter($operation->withParameters($parameters)));
                }
            }
        }

        return $openApi;
    }
}
```

```yaml
# config/services.yaml

services:
  App\ApiPlatform\OpenApiFactory:
    decorates: 'api_platform.openapi.factory'
    arguments: ['@App\ApiPlatform\OpenApiFactory.inner']
    autoconfigure: false
```

```php
/**
 * @ApiResource(
 *     ...
 *     itemOperations={
 *         "me"={
 *             "method"="GET",
 *             "route_name"="...",
 *             "openapi_context"={
 *                 "tags"={"withoutIdentifier"},
 *             },
 *         },
 *     },
 *     ...
 * )
 */
```

**Comment by ttskch** [comment]
Decorating `api_platform.openapi.factory` service works well for me. /cc @toar86 @s4mpl3d 

> refs: https://api-platform.com/docs/core/openapi/#overriding-the-openapi-specification

```php
<?php

declare(strict_types=1);

namespace App\ApiPlatform;

use ApiPlatform\Core\OpenApi\Factory\OpenApiFactoryInterface;
use ApiPlatform\Core\OpenApi\Model\Operation;
use ApiPlatform\Core\OpenApi\Model\Parameter;
use ApiPlatform\Core\OpenApi\Model\PathItem;
use ApiPlatform\Core\OpenApi\OpenApi;

class OpenApiFactory implements OpenApiFactoryInterface
{
    public function __construct(private OpenApiFactoryInterface $decorated)
    {
    }

    public function __invoke(array $context = []): OpenApi
    {
        $openApi = $this->decorated->__invoke($context);

        /**
         * @var string   $path
         * @var PathItem $pathItem
         */
        foreach ($openApi->getPaths()->getPaths() as $path => $pathItem) {
            // remove identifier parameter from operations which include "#withoutIdentifier" in the description
            foreach (PathItem::$methods as $method) {
                $getter = 'get'.ucfirst(strtolower($method));
                $setter = 'with'.ucfirst(strtolower($method));
                /** @var Operation $operation */
                $operation = $pathItem->$getter();
                if ($operation && preg_match('/#withoutIdentifier/', $operation->getDescription())) {
                    /** @var Parameter[] $parameters */
                    $parameters = $operation->getParameters();
                    foreach ($parameters as $i => $parameter) {
                        if (preg_match('/identifier/i', $parameter->getDescription())) {
                            unset($parameters[$i]);
                            break;
                        }
                    }
                    $openApi->getPaths()->addPath($path, $pathItem = $pathItem->$setter($operation->withParameters(array_values($parameters))));
                }
            }
        }

        return $openApi;
    }
}
```

```yaml
# config/services.yaml

services:
  App\ApiPlatform\OpenApiFactory:
    decorates: 'api_platform.openapi.factory'
    arguments: ['@App\ApiPlatform\OpenApiFactory.inner']
    autoconfigure: false
```

```php
/**
 * @ApiResource(
 *     ...
 *     itemOperations={
 *         "me"={
 *             "method"="GET",
 *             "route_name"="...",
 *             "openapi_context"={
 *                 "description"={"Retrieves a Foo resource. #withoutIdentifier"},
 *             },
 *         },
 *     },
 *     ...
 * )
 */
```

**Comment by toar86** [comment]
@ttskch minor modification

`<?php

namespace App\OpenApi;

use ApiPlatform\Core\OpenApi\Factory\OpenApiFactoryInterface;
use ApiPlatform\Core\OpenApi\Model\Operation;
use ApiPlatform\Core\OpenApi\Model\Parameter;
use ApiPlatform\Core\OpenApi\Model\PathItem;
use ApiPlatform\Core\OpenApi\OpenApi;

class OpenApiFactory implements OpenApiFactoryInterface
{
    private $decorated;

    public function __construct(OpenApiFactoryInterface $decorated)
    {
        $this->decorated = $decorated;
    }

    public function __invoke(array $context = []): OpenApi
    {
        $openApi = $this->decorated->__invoke($context);

        foreach ($openApi->getPaths()->getPaths() as $path => $pathItem) {
            // remove identifier parameter from operations which include "#withoutIdentifier" in the description
            foreach (PathItem::$methods as $method) {
                $getter = 'get'.ucfirst(strtolower($method));
                $setter = 'with'.ucfirst(strtolower($method));
                /** @var Operation $operation */
                $operation = $pathItem->$getter();
                //echo $operation->getDescription().'<br />';
                if ($operation && preg_match('/#withoutIdentifier/', $operation->getDescription())) {
                    /** @var Parameter[] $parameters */
                    $parameters = $operation->getParameters();
                    foreach ($parameters as $i => $parameter) {
                        if (preg_match('/identifier/i', $parameter->getDescription())) {
                            unset($parameters[$i]);
                            break;
                        }
                    }

                    $description = str_replace('#withoutIdentifier', '', $operation->getDescription());
                    $openApi->getPaths()->addPath($path, $pathItem = $pathItem->$setter($operation->withDescription($description)->withParameters(array_values($parameters))));
                }
            }
        }

        return $openApi;
    }
}`

**Comment by ayminovitch** [comment]
> Decorating `api_platform.openapi.factory` service works well for me. /cc @toar86 @s4mpl3d
> 
> > refs: https://api-platform.com/docs/core/openapi/#overriding-the-openapi-specification
> 
> ```
> <?php
> 
> declare(strict_types=1);
> 
> namespace App\ApiPlatform;
> 
> use ApiPlatform\Core\OpenApi\Factory\OpenApiFactoryInterface;
> use ApiPlatform\Core\OpenApi\Model\Operation;
> use ApiPlatform\Core\OpenApi\Model\Parameter;
> use ApiPlatform\Core\OpenApi\Model\PathItem;
> use ApiPlatform\Core\OpenApi\OpenApi;
> 
> class OpenApiFactory implements OpenApiFactoryInterface
> {
>     public function __construct(private OpenApiFactoryInterface $decorated)
>     {
>     }
> 
>     public function __invoke(array $context = []): OpenApi
>     {
>         $openApi = $this->decorated->__invoke($context);
> 
>         /**
>          * @var string   $path
>          * @var PathItem $pathItem
>          */
>         foreach ($openApi->getPaths()->getPaths() as $path => $pathItem) {
>             // remove identifier parameter from operations which include "#withoutIdentifier" in the description
>             foreach (PathItem::$methods as $method) {
>                 $getter = 'get'.ucfirst(strtolower($method));
>                 $setter = 'with'.ucfirst(strtolower($method));
>                 /** @var Operation $operation */
>                 $operation = $pathItem->$getter();
>                 if ($operation && preg_match('/#withoutIdentifier/', $operation->getDescription())) {
>                     /** @var Parameter[] $parameters */
>                     $parameters = $operation->getParameters();
>                     foreach ($parameters as $i => $parameter) {
>                         if (preg_match('/identifier/i', $parameter->getDescription())) {
>                             unset($parameters[$i]);
>                             break;
>                         }
>                     }
>                     $openApi->getPaths()->addPath($path, $pathItem = $pathItem->$setter($operation->withParameters(array_values($parameters))));
>                 }
>             }
>         }
> 
>         return $openApi;
>     }
> }
> ```
> 
> ```yaml
> # config/services.yaml
> 
> services:
>   App\ApiPlatform\OpenApiFactory:
>     decorates: 'api_platform.openapi.factory'
>     arguments: ['@App\ApiPlatform\OpenApiFactory.inner']
>     autoconfigure: false
> ```
> 
> ```
> /**
>  * @ApiResource(
>  *     ...
>  *     itemOperations={
>  *         "me"={
>  *             "method"="GET",
>  *             "route_name"="...",
>  *             "openapi_context"={
>  *                 "description"={"Retrieves a Foo resource. #withoutIdentifier"},
>  *             },
>  *         },
>  *     },
>  *     ...
>  * )
>  */
> ```

Not working for me

**Comment by ttskch** [comment]
@ayminovitch Please show your code.

**Comment by remoteclient** [comment]
This won't work, as I get this error: `Cannot access private property ApiPlatform\Core\OpenApi\Model\PathItem::$methods`
