### ISSUE TITLE
404 in Documentation

### ISSUE THREAD

**Issue by pesseyjulien** [api-platform/api-platform#487]
Hi,

Following link is not working :

https://api-platform.com/docs/core/serialization-groups-and-relations#header

Thanks in advance for your help,
Julien

**Comment by jewome62** [comment]
Hello @pesseyjulien,

Where do you found this link ?

I have find this link https://api-platform.com/docs/core/serialization#the-serialization-context-groups-and-relations
that's what you were looking for ?

**Comment by pesseyjulien** [comment]
Hi,

First result of 'serialization' search on the website (see enclosed).

Thanks,
Julien

<img width="1550" alt="capture d ecran 2017-12-18 a 10 04 27" src="https://user-images.githubusercontent.com/10850944/34097911-f2a8e996-e3da-11e7-9ac6-e9193ef8bb68.png">

**Comment by jewome62** [comment]
Bug was fixed

**Comment by meyerbaptiste** [comment]
Fixed by https://github.com/algolia/docsearch-configs/commit/117f91354baafc4720844c6d4437e2adecdd99b1.
