### ISSUE TITLE
Billing Module

### ISSUE THREAD

**Issue by gelinger777** [api-platform/api-platform#489]
Is it possible easily   integrate some kind of billing/user management where user pays fee per 1000 calls ?

**Comment by Aerendir** [comment]
I think you should use [events](https://api-platform.com/docs/core/events/), make the caller pass a token that identifies the calling app, and in the event you increment a counter persisted on the DB: once the counter reaches the amount of 1000, you do your "money things".

**Comment by gelinger777** [comment]
thanks will check that. But there is no something ready plug-and-play. Right?

**Comment by Aerendir** [comment]
More than events? What do you mean by "plug-and-play"? Something that handles billings?

**Comment by gelinger777** [comment]
forget it . Thank you for your help.
