### ISSUE TITLE
container pointing all links to localhost, which fails when in containers on mac.

### ISSUE THREAD

**Issue by dleute** [api-platform/api-platform#490]
I am running on a mac with docker toolbox. I cloned the master branch and did a docker-compose up -d

Everything started fine. So I go to my docker ip:443 and I see the welcome page. All the links on that welcome page are to localhost:whatever port which obviously won't actually work.

So I take one (in this case, the admin one) and replace with my docker ip and it refuses to contact the api because it's ajax calls are still looking for localhost.

Currently, it seems like this repo is designed to run on linux running docker natively, not in docker on other platforms (in a VM).

Did I miss something? Was there a step that setup port forwarding on my mac to the containers?

I'm curious why it isn't using relative url's. Or is there a host parameter that I can put in the environment variables?

Thanks!

**Comment by BallisticPain** [comment]
@dleute Am I correct in Docker Toolbox not being the latest Docker for Mac? I use Docker for Mac, and do not have any trouble cloning from master and booting right up and in.

**Comment by dleute** [comment]
Docker for Mac is a different implementation. I typically use toolbox because I have other requirements. (Running kubernetes, and other container things, and need VM access).

It may work because it uses hyperkit which is different virtualization than a VM. I will try that, and see if I can get the two to co-exist.

I would assume hyperkit uses the hosts networking more directly and that solves the problem. (unless I need other things on the ports the containers are launching).

**Comment by BallisticPain** [comment]
It does use the hosts networking in bridged mode. If you can come up with a way that it can work for both, I'm sure the project would be happy to have both working well... otherwise I imagine they are just using what's "easiest" to get setup and running for *most* users.

**Comment by dleute** [comment]
Yeah, this would fail on windows too (unless docker there works more like docker for mac).

The "easiest" way to fix this for all is probably to setup a local port forward service that forwards all the localhost ports to the IP of your container VM. I know things like kubectl have that so you can see the admin ui from your local system. There is probably a cli way to do it with PHP. Haven't looked into it yet.

It's re-building the containers for Docker for Mac. I expect this will work.

**Comment by dleute** [comment]
Works fine with docker for mac so far.

**Comment by BallisticPain** [comment]
@dleute 
You could also potentially point `localhost` in your `/etc/hosts` to your container VM IP.

**Comment by dleute** [comment]
That would probably break a thousand other things.

**Comment by dleute** [comment]
Any idea on if Docker for Windows works the same way? I am about to hand this code to someone who runs on windows. I'm hoping we don't have a proxy/localhost issue there.

**Comment by Simperfit** [comment]
Docker for windows does not work the same way. But it should be working with api-platform too.

Closing as this seems to be OK, feel free to open another issue if you have one with docker for windows.
