### ISSUE TITLE
Bug with Priority of Multiple Custom Item Data Providers + ORM Item Data Provider

### ISSUE THREAD

**Issue by silverbackdan** [api-platform/api-platform#491]
I've added 2 data providers - LayoutDataProvider and PageDataProvider.

The second data provider is listed after the default data provider resulting in it never being called.

This is the order of data providers in ApiPlatform\Core\DataProvider\ChainItemDataProvider but I haven't been able to trace where the constructor is being called from yet. I think it's linked with an event.
string(35) "App\DataProvider\LayoutDataProvider"
string(53) "ApiPlatform\Core\Bridge\Doctrine\Orm\ItemDataProvider"
string(33) "App\DataProvider\PageDataProvider"

If I rename PageDataProvider to AAPageDataProvider, it will be called, but LayoutDataProvider ends up after the default ItemDataProvider again.

**Comment by dunglas** [comment]
You can use the `priority` attribute of the tag to change the priority (you'll need to add manually if you rely on `autoconfigure`).

**Comment by silverbackdan** [comment]
I tried it but sed the collection_data_provider tag instead of the item_data_provider which was why that hasn't worked. Thanks for such a quick response @Dunglas
