### ISSUE TITLE
Question : How to use the serializer in a custom controller

### ISSUE THREAD

**Issue by Dannebicque** [api-platform/api-platform#492]
Hello,

I continue my initiation on API-Platform, and I try to understand how to use the serializer on an entity when I go through a custom controller.

In the following example, I wrote a controller which authenticate my user. It works. Now, I need to make the connection between a "personnel" or a "etudiant" (connected with the authentication by email).

```php
    /**
     * @Route("/api/current_user")
     * @return JsonResponse
     */
    public function currentUser(): JsonResponse
    {
        if ($this->getUser()->getTypeuser() === 'PERM') {
            $user = $this->getDoctrine()->getRepository('App:Personnel')->findOneBy(array('mailuniv' => $this->getUser()->getEmail()));
            if ($user !== null) {
                $formations = $user->getFormations();
            }
        } else {
            $user = $this->getDoctrine()->getRepository('App:Etudiant')->findOneBy(array('mailuniv' => $this->getUser()->getEmail()));
        }
        return new JsonResponse(['user' => $user, 'formation' => $formations]);
    }
```

I would like that $user and $formations are serialized. Can I Use Api-Platform and it's native serializer to do that ?

Thanks for your help.

**Comment by soyuka** [comment]
Just return the array it should work. 

When I have custom stuff like this, I usually end up creating a new class representing the custom dataset.

For example:

```
/**
 * usually you would disable any operations here as well
 * @ApiResource()
 */
class CurrentUser {
  /** User **/
  public $user;
  /** Formation **/
  public $formations;
}
```

Then, set the route defaults to `_api_resource_class: CurrentUser, _format: 'jsonld'`. Your route can return a collection of this class.

**Comment by Dannebicque** [comment]
Hello,

Thanks for your answer.
Create a class is a good Idea, I did not think about this idea.

So I create a new class

```php
<?php
namespace App\Entity;
use ApiPlatform\Core\Annotation\ApiResource;

/**
 * @ApiResource()
 */
class CurrentUser
{
    /** @var Personnel */
    private $user;

    /** @var Formation */
    private $formations;

//getters and setters
```

I modify my controller (rapidly to test)
```php
class AuthController extends Controller
{

    /**
     * @Route("/api/current_user",
     *         defaults={"_api_resource_class"=CurrentUser::class}
     * )
     */
    public function currentUser(): JsonResponse
    {
        $cu = new CurrentUser();

        if ($this->getUser()->getTypeuser() === 'PERM') {
            $user = $this->getDoctrine()->getRepository('App:Personnel')->findOneBy(array('mailuniv' => $this->getUser()->getEmail()));
            if ($user !== null) {
                $formations = $user->getFormations();
            }
        } else {
            $user = $this->getDoctrine()->getRepository('App:Etudiant')->findOneBy(array('mailuniv' => $this->getUser()->getEmail()));
        }

        $cu->setUser($user);
        $cu->setFormations($formations[0]);
        return new JsonResponse($cu);
    }
}
```

And when I call this route, I get an empty Json array. Maybe I need to create an array but not return the object ?

**Comment by jewome62** [comment]
hello @Dannebicque 
Can you remove JsonResponse object and just return the object or array

**Comment by Dannebicque** [comment]
Yes ! Many thanks. It works just by returning an array.

I obtain a collection with first my User, and then my Formation.

Can I consider that the order will always be the same? Or is it better to test the @type?

**Comment by jewome62** [comment]
The serializer serialize step by step.
If your array, collection or properties order is the same, the serialization will be the same.

**Comment by Dannebicque** [comment]
OK. Many Thanks @jewome62 and @soyuka !

**Comment by soyuka** [comment]
If you return an instance of `Response` or SerializeListener` will not use your data: 
https://github.com/api-platform/core/blob/master/src/EventListener/SerializeListener.php#L51

**Comment by Dannebicque** [comment]
Thanks for your explanation @soyuka :)
