### ISSUE TITLE
Add public getter method for doctrine object in FeatureContext class

### ISSUE THREAD

**Issue by jibla** [api-platform/api-platform#493]
If I create a custom `FeatureContext` class that extends api-platform's [FeatureContext](/api-platform/api-platform/blob/2.1/features/bootstrap/FeatureContext.php), then I don't have any access to its `->doctrine` parameter.

I think, it would be nice, if there is a public method `getDoctrine()` or `->doctrine` property is modified as  *protected*.

If this is acceptable, I can create a PR as well.

**Comment by dunglas** [comment]
This file is here to be edited, you don't have to extend it, you can add any code you need directly in it.

**Comment by jibla** [comment]
Ah, that's absolutely right. Its not part of the apiplatform core. Thanks, will close the issue.
