### ISSUE TITLE
PHP command not available from api container

### ISSUE THREAD

**Issue by timotheemoulin** [api-platform/api-platform#498]
I'm following the 5 minutes tutorial from the website and it seems that the latest master version (2.1 atm) is not working properly.

First, the container name is `api` and not `app` (as states the `docker-compose.yml` file.

Secondly, as the `docker-compose.yml` file states, only the `/api/public` directory is mounted in the container which means that I can't access the `bin/console` file.

```➜  api-platform git:(master) ✗ docker-compose exec api bin/console doctrine:schema:create AppBundle
oci runtime error: exec failed: container_linux.go:265: starting container process caused "exec: \"bin/console\": stat bin/console: no such file or directory"
```

I tried to change the container volume, to share all the `/api` folder. If I retry to launch the previous command, I get the following error.

```➜  api-platform git:(master) ✗ docker-compose exec api /srv/api/bin/console doctrine:schema:create AppBundle
env: can't execute 'php': No such file or directory
```

PHP seems not to be installed (at least accessible from the container).

Do you have any idea of what's going on?

Here are more info about my setup.

Docker version : 17.09.1-ce, build 19e2cf6
Docker Compose version : 1.17.1, build 6d101fb
OS : Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux

```➜  api-platform git:(master) ✗ docker ps
CONTAINER ID        IMAGE                     COMMAND                  CREATED             STATUS              PORTS                                                                    NAMES
4af953fe43e7        apiplatform_h2-proxy      "nginx -g 'daemon ..."   8 minutes ago       Up 8 minutes        0.0.0.0:443-444->443-444/tcp, 80/tcp, 0.0.0.0:8443-8444->8443-8444/tcp   apiplatform_h2-proxy_1
a0898195b690        apiplatform_cache-proxy   "docker-app-start"       8 minutes ago       Up 8 minutes        0.0.0.0:8081->80/tcp                                                     apiplatform_cache-proxy_1
d21891eb60e8        apiplatform_api           "nginx -g 'daemon ..."   8 minutes ago       Up 8 minutes        0.0.0.0:8080->80/tcp                                                     apiplatform_api_1
a9662686285c        apiplatform_php           "docker-entrypoint..."   8 minutes ago       Up 8 minutes        9000/tcp                                                                 apiplatform_php_1
970d8f2b24a1        apiplatform_client        "/bin/sh -c 'yarn ..."   16 minutes ago      Up 8 minutes        0.0.0.0:80->3000/tcp                                                     apiplatform_client_1
532ac017a290        apiplatform_admin         "/bin/sh -c 'yarn ..."   43 minutes ago      Up 8 minutes        0.0.0.0:81->3000/tcp                                                     apiplatform_admin_1
5e4e4bf32b10        postgres:9.6-alpine       "docker-entrypoint..."   44 minutes ago      Up 8 minutes        0.0.0.0:5432->5432/tcp                                                   apiplatform_db_1
```

**Comment by dunglas** [comment]
The `master` branch is the dev version, not 2.1 (the directory structure and Docker setup has changed a lot).
2.1 (the latest stable version) is here: https://github.com/api-platform/api-platform/tree/2.1

**Comment by dunglas** [comment]
If you want to use the master version:

    docker-compose exec php bin/console

**Comment by timotheemoulin** [comment]
Oh, my bad. I've been wronged by the last commit on `master` (Merge branch '2.1')
I'll check that and come back if needed.

**Comment by dunglas** [comment]
Yes we occasionally merge lower branches in the higher ones.
