### ISSUE TITLE
Provide a Docker Compose setup

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/api-platform#50]
Looking at #49, I think we should provide a complete Docker Compose setup.

Do you think it should be in a separate repo? I'll see if I can contribute mine as a start.

**Comment by dunglas** [comment]
Isn't more developer friendly to have a working docker setup just after doing `composer create-project api-platform/api-platform`?

**Comment by theofidry** [comment]
>Isn't it more developer friendly to have a working docker setup just after doing composer create-project api-platform/api-platform

I also think so :)

**Comment by teohhanhui** [comment]
I wonder if there could be reuse of `Dockerfile`s across the different distributions (Laravel edition etc. as planned)?

We could also look into automated builds for the Docker images (if it makes sense in our case).

**Comment by sroze** [comment]
We definitely need that Docker Compose configuration, true!

But I'm not sure it really makes sense for us to have an official _built_ Docker image.

**Comment by teohhanhui** [comment]
I actually didn't notice we already have a docker-compose.yml (but it's outdated, and only the database is in a separate container...)

**Comment by Simperfit** [comment]
Can we close this?

**Comment by teohhanhui** [comment]
Yeah, more or less...
