### ISSUE TITLE
Encode password using plain password

### ISSUE THREAD

**Issue by luchianenco** [api-platform/api-platform#505]
I work on custom User entity for API platform, and I want to ask how can I update password property. What I do now is:
I send POST request

```
{
  "firstName": "admin",
  "lastName": "admin",
  "plainPassword": "123",
  "email": "e@mail.com",
  "country": "/countries/1",
  "displayedName": "admin"
}
```

and before persist the User entity I want update password property something like that:
```
/** @var $encode UserPasswordEncoderInterface */
$encoded = $encoder->encodePassword($user, $plainPassword);
$user->setPassword($encoded);
```

where better to do this? I can use Doctrine PrePersist method, but i think entity should not depend on encoder interface. What are other solutions? Thanks

**Comment by Saphyel** [comment]
You can do it directly in the setPassword() I think is simple.

**Comment by luchianenco** [comment]
@Saphyel I have thought about this too, but I do not want to make Entity dependant on UserPasswordEncoderInterface. I think Entity should be without any external dependency, it should only keep data not to create them.

**Comment by luchianenco** [comment]
ok...I came to solution to overwrite the post controller for my User entity

- I create new route for post action
- added annotation for collectionOperations in User entity
- created new controller in symfony style and updated the created entity with encoded password there

hope this is the correct way ;)

**Comment by Alexandre-T** [comment]
I use a hash password listener implementing Event suscriber.

```
/**
 * Hash Password Listener.
 *
 * @author   Alexandre Tranchant <alexandre.tranchant@gmail.com>
 */
class HashPasswordListener implements EventSubscriber
{
    /**
     * Password encoder.
     *
     * @var UserPasswordEncoderInterface
     */
    private $passwordEncoder;

    /**
     * HashPasswordListener constructor.
     *
     * @param UserPasswordEncoderInterface $passwordEncoder
     */
    public function __construct(UserPasswordEncoderInterface $passwordEncoder)
    {
        $this->passwordEncoder = $passwordEncoder;
    }

    /**
     * Subscribes to prePersist and preUpdate Events.
     *
     * @return array
     */
    public function getSubscribedEvents()
    {
        return ['prePersist', 'preUpdate'];
    }

    /**
     * On PrePersist event.
     *
     * @param LifecycleEventArgs $args
     */
    public function prePersist(LifecycleEventArgs $args)
    {
        $entity = $args->getEntity();
        if (!$entity instanceof Player) {
            return;
        }

        $this->encodePassword($entity);
    }

    /**
     * On PreUpdate event.
     *
     * @param LifecycleEventArgs $args
     */
    public function preUpdate(LifecycleEventArgs $args)
    {
        $entity = $args->getEntity();
        if (!$entity instanceof Player) {
            return;
        }
        $this->encodePassword($entity);
        // necessary to force the update to see the change
        $em = $args->getEntityManager();
        $meta = $em->getClassMetadata(get_class($entity));
        $em->getUnitOfWork()->recomputeSingleEntityChangeSet($meta, $entity);
    }

    /**
     * Encode password.
     *
     * @param Player $entity
     */
    private function encodePassword(Player $entity)
    {
        if (preg_match('/^\$2[ayb]\$[0-9]{2}\$[A-Za-z0-9\.\/]{53}$/', $entity->getPassword())) {
//        if (!$entity->getPlainPassword()) {
            return;
        }
        $encoded = $this->passwordEncoder->encodePassword(
            $entity,
            $entity->getPassword()
        );
        $entity->setPassword($encoded);
    }
}
```
I was using a plainPassword as you can see in encodePassword method. But I encountered a bug with Assertion Constraint in the User entity when I verified that plainPassword was not Blank. Constraint exception was thrown even if I provide a plainPassword.

**Comment by luchianenco** [comment]
@Alexandre-T I was thinking about the listener, and what I don't like that your listener is subscribed for every doctrine event. In my opinion password encoding should be only when User is created and updated. That is all, and Controller as external layer is right place for some dependencies.

Or as I can see another way, trigger in the Controller an event for PasswordEncodeListener.

**Comment by Alexandre-T** [comment]
I now understand what you mean. I think your solution is better than mine. Controller is the right place for some dependencies. If you want to load PasswordEncoderListener only when necessary, I see two solutions : 
* You could create a controller in symfony style calling PasswordEncoderListener. This controller should only have these two actions, one for creation, one for changing password. (your solution)
* You could create two actions in api-platform and ADR Action-domain-responder style. (mainteners solution (I think))

https://api-platform.com/docs/core/operations#creating-custom-operations-and-controllers

**Comment by ntomka** [comment]
I think the best way is @luchianenco's way. Here's how I managed it to work:

## The entity
```PHP
// src/Entity/User.php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\AdvancedUserInterface;
use ApiPlatform\Core\Annotation\ApiResource;
use Symfony\Component\Serializer\Annotation\Groups;

/**
 * @ORM\Table(name="hd_users")
 * @ORM\Entity(repositoryClass="App\Repository\User")
 * @ApiResource(
 *  attributes={
 *      "normalization_context"={"groups"={"user", "user-read"}},
 *      "denormalization_context"={"groups"={"user", "user-write"}}
 *  }, itemOperations={
 *      "get",
 *      "delete",
 *      "put"={"route_name"="api_users_put"}
 *  }, collectionOperations={
 *      "get",
 *      "post"={"route_name"="api_users_post"}
 *  }
 * )
 */
class User implements AdvancedUserInterface, \Serializable
{
    // ...
}
```

## The controller
```PHP
namespace App\Controller;

use App\Entity\User;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

/**
 * @Route("/api")
 */
class UserController extends Controller
{
    /**
     * @Route(
     *     name="api_users_post",
     *     path="/users",
     *     methods={"POST"},
     *     defaults={
     *         "_api_resource_class"=User::class,
     *         "_api_collection_operation_name"="post"
     *     }
     * )
     */
    public function postAction(User $data, UserPasswordEncoderInterface $encoder): User
    {
        return $this->encodePassword($data, $encoder);
    }

    /**
     * @Route(
     *     name="api_users_put",
     *     path="/users/{id}",
     *     requirements={"id"="\d+"},
     *     methods={"PUT"},
     *     defaults={
     *         "_api_resource_class"=User::class,
     *         "_api_item_operation_name"="put"
     *     }
     * )
     */
    public function putAction(User $data, UserPasswordEncoderInterface $encoder): User
    {
        return $this->encodePassword($data, $encoder);
    }

    protected function encodePassword(User $data, UserPasswordEncoderInterface $encoder): User
    {
        $encoded = $encoder->encodePassword($data, $data->getPassword());
        $data->setPassword($encoded);

        return $data;
    }
}
```

This simply overrides the default behavior with password hashing.

**Comment by Simperfit** [comment]
Thanks, this seems resolved!

**Comment by Warxcell** [comment]
What about something like that:

`<?php
declare(strict_types=1);

namespace App\EventSubscriber;

use ApiPlatform\Core\EventListener\EventPriorities;
use App\Entity\User;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

final class UserSubscriber implements EventSubscriberInterface
{
    /** @var UserPasswordEncoderInterface */
    private $passwordEncoder;

    public function __construct(UserPasswordEncoderInterface $passwordEncoder)
    {
        $this->passwordEncoder = $passwordEncoder;
    }

    public static function getSubscribedEvents()
    {
        return [
            KernelEvents::VIEW => ['setPassword', EventPriorities::POST_VALIDATE],
        ];
    }

    public function setPassword(GetResponseForControllerResultEvent $event)
    {
        $user = $event->getControllerResult();

        if ($user instanceof User && $user->getPlainPassword()) {
            $password = $this->passwordEncoder->encodePassword($user, $user->getPlainPassword());
            $user->setPassword($password);
        }
    }
}`

Didn't tested it.

**Comment by xaoseric** [comment]
> What about something like that:
> 
> ```
> <?php
> declare(strict_types=1);
> 
> namespace App\EventSubscriber;
> 
> use ApiPlatform\Core\EventListener\EventPriorities;
> use App\Entity\User;
> use Symfony\Component\EventDispatcher\EventSubscriberInterface;
> use Symfony\Component\HttpKernel\Event\GetResponseForControllerResultEvent;
> use Symfony\Component\HttpKernel\KernelEvents;
> use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;
> 
> final class UserSubscriber implements EventSubscriberInterface
> {
>     /** @var UserPasswordEncoderInterface */
>     private $passwordEncoder;
> 
>     public function __construct(UserPasswordEncoderInterface $passwordEncoder)
>     {
>         $this->passwordEncoder = $passwordEncoder;
>     }
> 
>     public static function getSubscribedEvents()
>     {
>         return [
>             KernelEvents::VIEW => ['setPassword', EventPriorities::POST_VALIDATE],
>         ];
>     }
> 
>     public function setPassword(GetResponseForControllerResultEvent $event)
>     {
>         $user = $event->getControllerResult();
> 
>         if ($user instanceof User && $user->getPlainPassword()) {
>             $password = $this->passwordEncoder->encodePassword($user, $user->getPlainPassword());
>             $user->setPassword($password);
>         }
>     }
> }
> ```
> 
> Didn't tested it.

This method worked for me using the following with symfony 4

`namespace MailZippy\EventSubscriber;

use MailZippy\Entity\User;
use ApiPlatform\Core\EventListener\EventPriorities;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\ViewEvent;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class UserSubscriber implements EventSubscriberInterface {

    /**
     * @var UserPasswordEncoderInterface
     */
    private $passwordEncoder;

    public function __construct(UserPasswordEncoderInterface $userPasswordEncoder)
    {
        $this->passwordEncoder = $userPasswordEncoder;
    }

    public static function getSubscribedEvents()
    {
        return [
            KernelEvents::VIEW => ['setPassword', EventPriorities::POST_VALIDATE],
        ];
    }

    public function setPassword(ViewEvent $event)
    {
        $user = $event->getControllerResult();

        if ($user instanceof User && $user->getPassword()) {
            $password = $this->passwordEncoder->encodePassword($user, $user->getPassword());
            $user->setPassword($password);
        }
    }

}`

**Comment by mazero** [comment]
@xaoseric  I add your code like an EventSubscriber named UserSubscriber and I have add this in my services.yaml (symfony 4)  but when I try my request api on angular or postman to create the user with this password, it's not encoded.

  ```
  app.user_subcriber:
        class: App\EventSubscriber\UserSubscriber
        autowire: true
        tags:
            - { name: event_subscriber_interface }
```

My entity user with plainPassword

  ```
public function getPlainPassword()
    {
        return $this->plainPassword;
    }

    public function setPlainPassword($password)
    {
        $this->plainPassword = $password;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }
```

When I generate data via my fixture

  ```
$user       ->setEmail($username_and_simple_pwd.'@gmail.com')
                        ->setPhonenumber($this->faker->phoneNumber())
                        ->setPassword($this->passwordEncoder->encodePassword($user, $username_and_simple_pwd))
                        ->setRoles([$roles[mt_rand(0,1)]]);
```

**Comment by tomsihap** [comment]
Use a DataPersister https://symfonycasts.com/screencast/api-platform-security/encode-user-password

**Comment by develth** [comment]
Going with DataPersister described in symfonycast is the best way, but you should decorate the existing one, as described in doc, so you don´t have to 'reinvent' the persist and remove
https://api-platform.com/docs/core/data-persisters/#decorating-the-built-in-data-persisters

I using the following ```persist``` function:

```
public function persist($data, array $context = [])
    {
        if ($data instanceof UserInterface && $data->getPlainPassword() !== null) {
            $data->setPassword($this->passwordEncoder->encodePassword($data, $data->getPlainPassword()));
        }

        return $this->decorated->persist($data, $context);
    }
```

**Comment by Ninos** [comment]
Based on api platform state processors (https://api-platform.com/docs/main/core/state-processors/), do following:

In `/config/services.yaml` add new service (processor):
```yaml
    App\State\UserPasswordHasher:
        bind:
            $decorated: '@api_platform.doctrine.orm.state.persist_processor'
```

Create a new file `/src/State/UserPasswordHasher.php`:
```php
<?php

namespace App\State;

use ApiPlatform\Metadata\Operation;
use ApiPlatform\State\ProcessorInterface;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;

final class UserPasswordHasher implements ProcessorInterface
{
    private ProcessorInterface $decorated;
    private UserPasswordHasherInterface $passwordHasher;

    public function __construct(ProcessorInterface $decorated, UserPasswordHasherInterface $passwordHasher)
    {
        $this->decorated = $decorated;
        $this->passwordHasher = $passwordHasher;
    }

    public function process($data, Operation $operation, array $uriVariables = [], array $context = [])
    {
        if (!$data->getPlainPassword()) {
            return $this->decorated->process($data, $operation, $uriVariables, $context);
        }

        $hashedPassword = $this->passwordHasher->hashPassword(
            $data,
            $data->getPlainPassword()
        );
        $data->setPassword($hashedPassword);
        $data->eraseCredentials();

        return $this->decorated->process($data, $operation, $uriVariables, $context);
    }
}
```

And the entity (`/srv/Entity/User.php`) looks something like this:
```php
<?php

namespace App\Entity;

use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiProperty;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Patch;
use ApiPlatform\Metadata\Post;
use ApiPlatform\Metadata\Put;
use DateTimeImmutable;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use App\State\UserPasswordHasher;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Serializer\Annotation\Groups;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Uid\Uuid;

#[ApiResource(
    operations: [
        new GetCollection(
            name: 'getUserCollection',
        ),
        new Post(
            name: 'postUserCollection',
            processor: UserPasswordHasher::class,
        ),
        new Get(
            name: 'getUserItem',
        ),
        new Put(
            name: 'putUserItem',
            processor: UserPasswordHasher::class,
        ),
        new Patch(
            name: 'patchUserItem',
            processor: UserPasswordHasher::class,
        ),
        new Delete(
            name: 'deleteUserItem',
        ),
    ],
    normalizationContext: ['groups' => ['user:read']],
    denormalizationContext: ['groups' => ['user:create', 'user:update']],
    mercure: true,
    order: ['username' => 'ASC'],
)]
#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\Table(name: '`user`')]
#[UniqueEntity('username')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[Assert\Uuid]
    #[Groups(['user:read'])]
    #[ORM\Id]
    #[ORM\Column(type: 'uuid', unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?Uuid $id = null;

    #[Assert\NotBlank]
    #[Groups(['user:read', 'user:create', 'user:update'])]
    #[ORM\Column(length: 180, unique: true)]
    private ?string $username = null;

    #[ORM\Column]
    private ?string $password = null;

    #[Assert\NotBlank(groups: ['user:create'])]
    #[Groups(['user:create', 'user:update'])]
    private ?string $plainPassword = null;

    #[ORM\Column(type: 'json')]
    private array $roles = [];

    public function getId(): Uuid
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function getPlainPassword(): ?string
    {
        return $this->plainPassword;
    }

    public function setPlainPassword(?string $painPassword): self
    {
        $this->plainPassword = $painPassword;
        $this->password = null;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;

        $roles[] = 'IS_AUTHENTICATED_FULLY';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string)$this->username;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        $this->plainPassword = null;
    }
}
```

The user repository (`/src/Repository/UserRepository.php`) stays untouched (just for record):
```php
<?php

namespace App\Repository;

use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;
use App\Entity\User;
use Symfony\Component\Security\Core\Exception\UnsupportedUserException;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\PasswordUpgraderInterface;

/**
 * @extends ServiceEntityRepository<User>
 *
 * @method User|null find($id, $lockMode = null, $lockVersion = null)
 * @method User|null findOneBy(array $criteria, array $orderBy = null)
 * @method User[]    findAll()
 * @method User[]    findBy(array $criteria, array $orderBy = null, $limit = null, $offset = null)
 */
class UserRepository extends ServiceEntityRepository implements PasswordUpgraderInterface
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, User::class);
    }

    public function save(User $entity, bool $flush = false): void
    {
        $this->getEntityManager()->persist($entity);

        if ($flush) {
            $this->getEntityManager()->flush();
        }
    }

    public function remove(User $entity, bool $flush = false): void
    {
        $this->getEntityManager()->remove($entity);

        if ($flush) {
            $this->getEntityManager()->flush();
        }
    }

    /**
     * Used to upgrade (rehash) the user's password automatically over time.
     */
    public function upgradePassword(PasswordAuthenticatedUserInterface $user, string $newHashedPassword): void
    {
        if (!$user instanceof User) {
            throw new UnsupportedUserException(sprintf('Instances of "%s" are not supported.', \get_class($user)));
        }

        $user->setPassword($newHashedPassword);

        $this->save($user, true);
    }
}
```

**Comment by alanpoulain** [comment]
@Ninos would you mind creating a documentation PR for this?

**Comment by Ninos** [comment]
@alanpoulain Hoped no one will ask :-)

See https://github.com/api-platform/api-platform/issues/505

**Comment by julienmiclo** [comment]
@Ninos Hello, do you know how to make a state processor for multiple entities and multiple operations without add a class for each ?
I want to make an activity list of my users (create, update, delete) on specific entities.
Thank you.

**Comment by Ninos** [comment]
@julienmiclo Just use doctrine events?

https://symfony.com/doc/current/doctrine/events.html#doctrine-lifecycle-subscribers

**Comment by Warxcell** [comment]
> 

that doesnt work if you change only password, since it doesnt trigger update event.
