### ISSUE TITLE
Return an object instead of an array in response

### ISSUE THREAD

**Issue by merizoto** [api-platform/api-platform#507]
Hello everyone,

I face here a problem and i'm not able to find any similar case in the doc or issues list.

I use API Platform inside a symfony project and i want to expose a specific article data.

I use a simple guzzle client on my client side to access to these data.
My main problem is that /offers?slug=test-article will return an array no matter what.
Is it possible to return a simple json object? It would be cleaner on the client side to work with an object instead of a collection of one object. 

Best regards,

Quentin

**Comment by soyuka** [comment]
Yes this is because by definition:

- a collection returns an array (`/offers`)
- an item returns an object (`/offers/1`)

IMHO, it's really not a good practice to return an object on a collection route and if you want an object you should use the item route. 
If you want to do this you should create a custom action that returns your item (for example `/offers/by-slug/test-article`).

**Comment by merizoto** [comment]
Thank you for your answer, helped me so much. 

But something is missing in the documentation, how can i use a custom parameter like slug instead of the id?

In my case, i create a custom action in order to handle that specific case:
```php
<?php

namespace AppBundle\Action;

use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;
use Symfony\Component\Routing\Annotation\Route;
use AppBundle\Entity\Offer;


/**
 * Class OfferSlug
 *
 * @package AppBundle\Action
 */
class OfferSlug
{
    /**
     * @Route(
     *     name="offer_slug",
     *     path="/offer/by-slug/{slug}",
     *     defaults={"_api_resource_class"=Offer::class, "_api_item_operation_name"="slug"}
     * )
     * @Method("GET")
     * @return Offer|null
     */
    public function __invoke($data)
    {
        return $data;
    }
}
```

And a new item provider as well in order to override api platform own logic :
```php
<?php

namespace AppBundle\DataProvider;

use ApiPlatform\Core\DataProvider\ItemDataProviderInterface;
use AppBundle\Entity\Offer;
use AppBundle\Repository\OfferRepository;
use Doctrine\ORM\EntityManagerInterface;

/**
 * Class OfferItemDataProvider
 *
 * @package AppBundle\DataProvider
 */
final class OfferItemDataProvider implements ItemDataProviderInterface
{
    private $entityManager;

    /**
     * OfferItemDataProvider constructor.
     *
     * @param EntityManagerInterface $entityManager
     *
     */
    public function __construct(EntityManagerInterface $entityManager)
    {
        $this->entityManager   = $entityManager;
    }

    /**
     * Retrieves an item.
     *
     * @param string      $resourceClass
     * @param string  $slug
     * @param string|null $operationName
     * @param array       $context
     *
     * @return null|object
     */
    public function getItem(string $resourceClass, $slug, string $operationName = null, array $context = [])
    {
        return $this->entityManager->getRepository(Offer::class)->getOfferBySlug($slug);
    }
}
```

I registered this operation in my entity within ApiResource annotation, my new operation is well created and my route worked very well. But the only parameter asked is id instead of slug, what did i miss?

**Comment by soyuka** [comment]
Inject `requestStack` and to `$request->param->get('slug')`. By default the `ReadListener` (the one responsible for calling the `DataProvider` uses `$request->param->get('id')`.

**Comment by merizoto** [comment]
Thank you so much.

For those who are interested in it, here is the code of the custom provider:
```php
 private $entityManager;
    private $requestStack;

    /**
     * OfferItemDataProvider constructor.
     *
     * @param EntityManagerInterface $entityManager
     * @param RequestStack           $requestStack
     */
    public function __construct(EntityManagerInterface $entityManager, RequestStack $requestStack)
    {
        $this->entityManager   = $entityManager;
        $this->requestStack = $requestStack;
    }
```

And for the getItem method:
```php
/**
     * Retrieves an offer.
     *
     * @param string      $resourceClass
     * @param string  $slug
     * @param string|null $operationName
     * @param array       $context
     *
     * @return null|Offer
     */
    public function getItem(string $resourceClass, $slug, string $operationName = null, array $context = [])
    {
        $request = $this->requestStack->getCurrentRequest();
        $slug = $request->attributes->get('slug');

        return $this->entityManager->getRepository(Offer::class)->getOfferBySlug($slug);
    }

``` 

I may have an another question (the last one, i swear). The [doc](https://api-platform.com/docs/core/data-providers/) allow us to declare multiple custom providers as services. Assuming that i want to retrieve a specific resource (eg article) with a custom provider, again; how can i bind that specific provider to this entity? I do not want my offer provider to be used for my article entity. According to the doc, it looks like providers are only called by a priority system 

> The optional attribute priority allows to define the order in which the data providers are called.

Quentin

**Comment by merizoto** [comment]
Ok, does it mean that atm providers can only be managed by priority?

Supposed i have two specific itemOperations on the same resource, both requiring a custom provider
 

> eg:
>/article/by-slug/{slug}
>article/last

Provider with highest priority is going to be called in both cases, am i right?

**Comment by soyuka** [comment]
yes but you can restrict by using the above

**Comment by merizoto** [comment]
Ok thanks @soyuka for your help ! 👍

**Comment by shayanadc** [comment]
any comment on this ?

https://stackoverflow.com/questions/78631820/api-platform-returning-an-array-of-entity-in-a-processor
