### ISSUE TITLE
Error on Admin Component docs

### ISSUE THREAD

**Issue by brunoreis** [api-platform/api-platform#508]
Here: https://api-platform.com/docs/admin/getting-started#using-a-custom-validation-function-or-inject-custom-props

I imagine the following line is wrong, since hydraClient expects the api, not the entrypoint: 

```
return <AdminBuilder api={this.state.api} restClient={hydraClient(entrypoint)}/>
```

It was not working for me until I passed the api there.

**Comment by comxd** [comment]
Have you found a solution for that?

I use:

```js
export default class extends Component {
    state = {api: null};

    componentDidMount() {
        parseHydraDocumentation(entrypoint).then( ({ api })  => {
            this.setState({api: api});
            // @see https://api-platform.com/docs/admin/getting-started#customizing-the-admin

           // change property "type" for input named "url" into "brands" resource.
           const brands = api.resources.find(r => 'brands' === r.name);
            brands.writableFields.find(f => 'url' === f.name).inputProps = {
                type: 'url',
                validate: 'test'
            };

            return { api };
        });
    }

    render() {
        return <HydraAdmin api={this.state.api} apiDocumentationParser={myApiDocumentationParser} entrypoint={entrypoint} />
    }
}
```

UI load successfully but I'm unable to change inputs properties (inputProps)... :-/

**Comment by brunoreis** [comment]
I think I did, but unfortunately I don't remenber. There are a lot of weak
points in the integration of admin on rest with the api platform. So I
started using the admin on rest in it's more "pure" form. Now I've declined
the api-platform and I'm only using SF4 and admin on rest.

2018-01-13 13:41 GMT-02:00 David <notifications@github.com>:

**Comment by Simperfit** [comment]
This has been updated, thanks anyway!
