### ISSUE TITLE
[Question] : Accessing user within custom api-platform filter

### ISSUE THREAD

**Issue by mluksic** [api-platform/api-platform#509]
Hi, 

we need to access user data from within custom filter to filter record based on user properties. 
If we inject Token Interface into our filter and use:

`$user = $this->tokenStorage->getToken()->getUser();`

we get the following error:

`Call to a member function getCurrentRequest() on null`

Is there a way to access User from within custom filter?

**Comment by Simperfit** [comment]
Could you please give us more information ?

Where does the getCurrentRequest occurs ? it seems that the RequestStack is null.
