### ISSUE TITLE
How to include hydra:view on single page collections

### ISSUE THREAD

**Issue by toby-griffiths** [api-platform/api-platform#522]
Hi there,

I'm looking to cache the API collection responses, and wanted to cache them by the pagination `@id` field, however this isn't included in the API response unless there's more than 1 page of results.

Is there an easy way to enable this for all results, rather than me hacking is an building the `@id` manually client side, if it's missing?

Thanks in advance.

**Comment by toby-griffiths** [comment]
I'm not sure what's changed, but I'm not seeing a `hydra:view` object in my single page responses, although if there's only 1 page it excludes the `page=1` part on the URL (as might be expected), so I can work around this.

**Comment by toby-griffiths** [comment]
Actually, I'm not sure why this has changed, but it's now missing from my collection response again, so any advice on how to add this back would be appreciated.

**Comment by dunglas** [comment]
The problem is: if the full collection is returned (what you call "single page collection"), there is no point to tell the client that it's a partial collection.

**Comment by toby-griffiths** [comment]
I see your point @dunglas .  I'll work around this by using the request URL if the element is not included.

Thank you.
