### ISSUE TITLE
Adding fixtures

### ISSUE THREAD

**Issue by theofidry** [api-platform/api-platform#53]
Should we add some fixtures out of the box to allow the user to see how the application behave (and not an empty database)?

cc @dunglas

**Comment by Simperfit** [comment]
Hey @theofidry,

Was looking into twiits today and I saw some API-base CMS (contentful / prismic).

Why not making one to show the power of api-platform ? Something with api-platform / ng-admin / basic angular2 webpack / with little css3 style and some default entity like Content / Pages / BlogPost to make something basic like a blog / little website.

I could be fun to see if people would you go for that :).

**Comment by theofidry** [comment]
There is https://github.com/dunglas/blog-api although still in WIP. It is planned to move it under ApiPlatform once it's usable.

**Comment by Simperfit** [comment]
But why not a full-stack thingy ?

like an composer create-project with all the dependency for all the stack ?

**Comment by theofidry** [comment]
There is several reasons for that:

- What is your application: just a REST API or does it have a front-end as well (as, is it one application or two separate application?)
- If you have two applications (API + Front-end), you may have one repository or decide to split them in two repositories.
- The front-end world is very unstable and immature still, making such a full-stack project would require 1. to be highly opinionated on the technology used 2. require A LOT of time to manage it and keep it up to date 3. If you build 2 separate applications, you have already great tools to start up (ex: Yeoman)

Obviously if there was a good front-end developer willing to spend his time on it and is ready to maintain it, we would welcome it, but none of the ApiPlatform team is a front-end developer at heart with enough free-time to afford that

**Comment by Simperfit** [comment]
I totally agree with you about that.

I was just looking into that cms- api based which can be awsome to show  api-platform.
