### ISSUE TITLE
GraphQL pagination seems not working

### ISSUE THREAD

**Issue by Rebolon** [api-platform/api-platform#530]
I'm testing GraphQL on master branch.
I have a simple query:

```
query getBooksQry($first: Int, $after: String) {
	getBooks: books(first: $first, after: $after) {
		edges {
			node {
				id
				title
			}
		}
		pageInfo {
			endCursor
                        hasNextPage
		}
	}
}
```
with variables
```
{
  "after": "",
  "first": 5
}
```
and i get this
```
{
  "data": {
    "getBooks": {
      "pageInfo": {
        "endCursor": "NDg5",
        "hasNextPage": true
      },
      "edges": [
        {
          "node": {
            "id": "/api/books/2",
            "title": "20th Century Boys (Deluxe), Tome 2"
          }
        },
        {
          "node": {
            "id": "/api/books/3",
            "title": "20th Century Boys (Deluxe), Tome 3"
          }
        },
        {
          "node": {
            "id": "/api/books/4",
            "title": "20th Century Boys (Deluxe), Tome 4"
          }
        },
        {
          "node": {
            "id": "/api/books/5",
            "title": "20th Century Boys (Deluxe), Tome 5"
          }
        },
        {
          "node": {
            "id": "/api/books/6",
            "title": "20th Century Boys (Deluxe), Tome 6"
          }
        }
      ]
    }
  }
}
```
On first call it works well
But if i try to call again the api to get next page it doesn't retreive anything.

Here is the variables used for the new query
``` 
{
  "after": "NDg5",
  "first": 5
}
```
And the results
```
{
  "data": {
    "getBooks": {
      "pageInfo": {
        "endCursor": "NDg5",
        "hasNextPage": false
      },
      "edges": []
    }
  }
}
``` 

I have 490 items in my dabtabase so i should have at least 5 new datas ;-)
I know the feature is on `beta`, so maybe i'm doing wrong or the feature is not implemented.

Thanks for help

**Comment by alanpoulain** [comment]
This is the wanted behavior.

**Comment by alanpoulain** [comment]
See also: https://facebook.github.io/relay/graphql/connections.htm

**Comment by Rebolon** [comment]
thx a lot, now i understand where i were wrong. I'm used to apolloData client, i don't think there is a pagination pattern.

**Comment by dgoujard** [comment]
> This is the wanted behavior.
> `endCursor` in `pageInfo` corresponds to the last cursor of all your items. See http://graphql.org/learn/pagination/.
> You should use `cursor` in `edges` to paginate through your collection.
> Like this:
> 
> ```graphql
> query getBooksQry($first: Int, $after: String) {
>   getBooks: books(first: $first, after: $after) {
>     edges {
>       node {
>         id
>         title
>       }
>       cursor
>     }
>     pageInfo {
>       endCursor
>       hasNextPage
>     }
>   }
> }
> ```
@alanpoulain 
In Api Plateform the `endCursor` is the last cursor in all collection but in the GraphQL documentation https://graphql.org/learn/pagination/#end-of-list-counts-and-connections it's seams to be the last from the fetched slice. If you use  the playground in the end of the page with this query : 
```
{
  hero {
    name
    friendsConnection(first:2) {
      totalCount
      edges {
        node {
          name
        }
        cursor
      }
      pageInfo {
        endCursor
        hasNextPage
      }
    }
  }
}
```
You got : 
```
{
  "data": {
    "hero": {
      "name": "R2-D2",
      "friendsConnection": {
        "totalCount": 3,
        "edges": [
          {
            "node": {
              "name": "Luke Skywalker"
            },
            "cursor": "Y3Vyc29yMQ=="
          },
          {
            "node": {
              "name": "Han Solo"
            },
            "cursor": "Y3Vyc29yMg=="
          }
        ],
        "pageInfo": {
          "endCursor": "Y3Vyc29yMg==",
          "hasNextPage": true
        }
      }
    }
  }
}
```
The `endCursor` in the `pageInfo` is the last cursor in the current slice not the last in the collection (Y3Vyc29yMw==) because you have `hasNextPage` set to true.

**Comment by alanpoulain** [comment]
Yes, there is indeed a problem, contrary to what I said before. There is a PR to fix this and add a new feature (backwards pagination): https://github.com/api-platform/core/pull/2142 but it's stuck at the moment. Maybe I will try to see what I can do.

**Comment by dgoujard** [comment]
@alanpoulain Ok thank you for your reply, i didn't view this PR before.
