### ISSUE TITLE
API Platform Installation/Usage

### ISSUE THREAD

**Issue by gdharris1970** [api-platform/api-platform#531]
I installed Docker and API Platform on an Ubuntu box using the instructions on this page:

https://api-platform.com/docs/distribution

I am able to go to http://localhost and see the "foo" API page, but I can't get anything to work. I checked MySQL, and there is no database that corresponds to API Platform. If I try to run the POST operation from the web page, I get "Error: Internal Server Error." I am not sure what I have done wrong.

I did not run that following commands because I installed API Platform from the TAR.GZ file that I downloaded from GitHub:

$ composer create-project api-platform/api-platform bookshop-api
$ cd bookshop-api
$ bin/console doctrine:database:create
$ bin/console doctrine:schema:create

I was afraid that if I ran the first command, that it would re-install API Platform using Composer. So, I don't have a bookshop-api directory, and I haven't created the database or the schema. Could someone please point me in the right direction. I really want to learn API Platform and use it to create my own REST API that is secured with OAuth.

**Comment by dunglas** [comment]
1. Be sure that you have no local http nor MySQL server running locally (shut them down if it's the case)
2. Download the zip of the latest stable version on https://github.com/api-platform/api-platform/releases
3. Extract the archive, and go to the newly extracted directory
4. Run `docker-compose up` (you must have a recent version of Docker and Docker compose installed locally)

If something goes wrong, please paste the logs and the errors you get.

**Comment by gdharris1970** [comment]
I removed everything and started from scratch. I used the Composer install instructions instead of going the Docker route. I don't think we need the Docker stuff, although I'm not totally sure because I don't fully understand it. At any rate, the Foo example is working as expected! Thank you so much for your help!

**Comment by suryacaprice** [comment]
Creating demo_admin_1       ... done
Creating demo_client_1      ... done
er-compose build` or `docker-compose up --build`.
Creating demo_php_1         ... done
Creating demo_admin_1       ...
Creating demo_api_1         ... done
Creating demo_php_1         ...
Creating demo_cache-proxy_1 ... done
Creating demo_cache-proxy_1 ...
Creating demo_h2-proxy_1    ... done
Attaching to demo_client_1, demo_db_1, demo_admin_1, demo_php_1, demo_api_1, demo_cache-proxy_1, demo_h2-proxy_1
client_1       | yarn run v1.3.2
client_1       | error Couldn't find a package.json file in "/usr/src/client"
db_1           | The files belonging to this database system will be owned by user "postgres".
client_1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
db_1           | This user must also own the server process.
admin_1        | yarn run v1.3.2
db_1           |
db_1           | The database cluster will be initialized with locale "en_US.utf8".
admin_1        | error Couldn't find a package.json file in "/usr/src/admin"
php_1          | standard_init_linux.go:195: exec user process caused "no such file or directory"
db_1           | The default database encoding has accordingly been set to "UTF8".
api_1          | 2018/02/22 09:10:10 [emerg] 1#1: host not found in upstream "php" in /etc/nginx/conf.d/default.conf:11
db_1           | The default text search configuration will be set to "english".
api_1          | nginx: [emerg] host not found in upstream "php" in /etc/nginx/conf.d/default.conf:11
admin_1        | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
db_1           |
db_1           | Data page checksums are disabled.
cache-proxy_1  | standard_init_linux.go:195: exec user process caused "no such file or directory"
db_1           |
h2-proxy_1     | 2018/02/22 09:10:24 [emerg] 1#1: host not found in upstream "client" in /etc/nginx/conf.d/default.conf:9
db_1           | fixing permissions on existing directory /var/lib/postgresql/data ... ok
h2-proxy_1     | nginx: [emerg] host not found in upstream "client" in /etc/nginx/conf.d/default.conf:9
db_1           | creating subdirectories ... ok
db_1           | selecting default max_connections ... 100
db_1           | selecting default shared_buffers ... 128MB
db_1           | selecting dynamic shared memory implementation ... posix
db_1           | creating configuration files ... ok
db_1           | running bootstrap script ... ok
db_1           | performing post-bootstrap initialization ... sh: locale: not found
demo_client_1 exited with code 1
db_1           | No usable system locales were found.
db_1           | Use the option "--debug" to see details.
demo_api_1 exited with code 1
demo_php_1 exited with code 1
demo_admin_1 exited with code 1
demo_cache-proxy_1 exited with code 1
demo_h2-proxy_1 exited with code 1
db_1           | ok
db_1           | syncing data to disk ...
db_1           | WARNING: enabling "trust" authentication for local connections
db_1           | You can change this by editing pg_hba.conf or using the option -A, or
db_1           | --auth-local and --auth-host, the next time you run initdb.
db_1           | ok
db_1           |
db_1           | Success. You can now start the database server using:
db_1           |
db_1           |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1           |
db_1           | waiting for server to start....LOG:  could not bind IPv6 socket: Address not available
db_1           | HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
db_1           | LOG:  database system was shut down at 2018-02-22 09:10:09 UTC
db_1           | LOG:  MultiXact member wraparound protections are now enabled
db_1           | LOG:  database system is ready to accept connections
db_1           | LOG:  autovacuum launcher started
db_1           |  done
db_1           | server started
db_1           | CREATE DATABASE
db_1           |
db_1           | CREATE ROLE
db_1           |
db_1           |
db_1           | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1           |
db_1           | LOG:  received fast shutdown request
db_1           | LOG:  aborting any active transactions
db_1           | LOG:  autovacuum launcher shutting down
db_1           | waiting for server to shut down....LOG:  shutting down
db_1           | LOG:  database system is shut down
db_1           |  done
db_1           | server stopped
db_1           |
db_1           | PostgreSQL init process complete; ready for start up.
db_1           |
db_1           | LOG:  database system was shut down at 2018-02-22 09:11:21 UTC
db_1           | LOG:  MultiXact member wraparound protections are now enabled

**Comment by Simperfit** [comment]
@suryacaprice please feel free to open another issue if you still have one.

**Comment by pcinvent** [comment]
I made this "API-Platform-Mysql" Github Project that made API platform works with MySQL 8, please fork, star, contribute to it, you may create an issue or ask questions there in my Repository:
https://github.com/pcinvent/api-platform-mysql
