### ISSUE TITLE
GraphQL mutation : nested document not allowed

### ISSUE THREAD

**Issue by Rebolon** [api-platform/api-platform#535]
Hi,
still discovering GraphQL implementaion in ApiPlatform and i'm playing with Mutations.
With GraphiQL i can see the documentation available for my project. so i'm trying a simple mutation with one entity, and it works well. But when i'm trying to mutate embedded documents, then it fails (i'm used to do this with nodeJs implementation of GraphQL).

Here is the schema described by GraphiQL:
```
createBook(input: createBookInput): createBookPayload
```
with createBookInput fields:
```
title: String!
description: String
indexInSerie: Int
reviews: updateReviewInputInputConnection
serie: createSerieInput
authors: updateProjectBookCreationInputInputConnection
editors: updateProjectBookEditionInputInputConnection
clientMutationId: String!
```
and if i look at a nested document, i can select createSerieInput (type of property serie);
```
name: String!
clientMutationId: String!
```
So with those informations i'm quite confident on the following mutation:
```
// mutation
mutation createBook($book: createBookInput!) {
    createBook(input: $book) {
        title
        id
        serie {
            name
            id
        }
    }
}

// query variable
{
  "book": {
    "title": "montest",
    "clientMutationId": "1",
    "serie": {
      "name": "maserie",
      "clientMutationId": "2"
    }
  }
}
```
When i call this, then i get a 400 HTTP Bad Request with that content:
```
...
category: "internal"
debugMessage: "Nested documents for attribute "serie" are not allowed. Use IRIs instead."
...
message: "Internal server error"
```

So do you plan to make it works in the future ?
Am i doing something wrong ?
How to use IRIS (but i would prefer not doing this, or there won't be really difference between REST and GraphQL) whereas the GraphiQL documentation explain me that a serie is composed of a name (and a clientMutationId) ?

**Comment by dunglas** [comment]
It looks like a bug to me.

**Comment by Rebolon** [comment]
Do you need more informations ? 
Here is the app with the model https://github.com/Rebolon/php-sf-flex-webpack-encore-vuejs
Just start the app and go to /api/graphql to test the mutation

**Comment by Rebolon** [comment]
Seems that the current solution is to call sub-mutation first and then the parents mutations with IRIS for child objects (PR 1702).

Sad coz graphCool implement this since 2016/10, more info here: https://blog.graph.cool/improving-dx-with-nested-mutations-698c508339ca
