### ISSUE TITLE
DenyAccessListener priority and object state in access_control

### ISSUE THREAD

**Issue by subotin** [api-platform/api-platform#536]
Hi!
I've found a small but unpleasant moment.
So. For example I have `Conversation` resource with `participants` and `id` properties. Resource class has a method `isParticipant(User $user): bool` which checks if an user is participant of conversation or not.
Api resource`PUT` endpoint is denied for all who is not participant of a called Conversation.
>
    itemOperations = {
        "put" = {
              "method" = "PUT",
              "path" = "/users/me/conversations/{id}",
              "requirements" = { "id" = "\d+" },
              "access_control" =
                  "is_granted(constant(Permission::MESSAGE_USE')) and object.isParticipant(user)"
          }

For example my `user id` is 1.
I have `Conversation` with `participants: ["/users/1", "users/2"]` and `id: 123`
And want to exclude myself from participants through a `put` operation. 
I send a `PUT` request to `/users/me/conversations/123` with body `{"participants": ["/users/2"]}`
And have an access denied response.
The problem is: `Conversation` object has been modified in memory (not persisted) by my request before `access_control` rule is applied. As result as a user I cannot leave the conversation.

**Comment by Simperfit** [comment]
The thing that could help you in this case, is maybe to have a EventSubcriber that will be listen before/when/after the object has been modified to apply this security rules.

**Comment by terjebraten-certua** [comment]
You can use "previous_object" instead of "object" in your access_control expression.

`previous_object` is a clone of the object before it was changed by the deserialisation.

**Comment by soyuka** [comment]
Thanks @terjebraten-certua for that helpful information.
