### ISSUE TITLE
No operations defined in spec!

### ISSUE THREAD

**Issue by gdharris1970** [api-platform/api-platform#538]
I followed the instructions for creating the Book/Review API exactly as written, but when I navigate to http://localhost:8000/app_dev.php, I get the following message in the browser:

No operations defined in spec!

Does anyone know why this is happening?

**Comment by gdharris1970** [comment]
Crud! I forgot the following line of code in the Book.php and Review.php files:

* @ApiResource

Sorry for wasting anyone's time!

**Comment by 1dal** [comment]
Btw, in offical "Get started" guide is missing:

```php
use ApiPlatform\Core\Annotation\ApiResource;
```

**Comment by vatoer** [comment]
in entity file 


```
use ApiPlatform\Core\Annotation\ApiResource;
.....

/**
..
*@ApiResource
*/
```
