### ISSUE TITLE
Improve doc for including graphQL

### ISSUE THREAD

**Issue by brud** [api-platform/api-platform#541]
After `docker-compose exec app composer req webonyx/graphql-php` I trying to open [https://localhost:8443/graphql](https://localhost:8443/graphql) and I get a `ERR_CONNECTION_REFUSED `

**Comment by dunglas** [comment]
Are other pages working? Because it looks more related to Docker than to GraphQL.

**Comment by brud** [comment]
yep, all api worked as well
I'm not familiar with docker - it seems I need to connect graphQL port from docker to my host machine?

**Comment by dunglas** [comment]
No, it's just a standard HTTP endpoint. Can you try `http://localhost:8080/graphql`?

**Comment by brud** [comment]
yep, nginx handles this request to symfony

**Comment by brud** [comment]
seems I need ad new port in `docker-compose.yml`

**Comment by brud** [comment]
but better way is a hide graphQL by symfony - it will give as authentication and other useful stuff

**Comment by GregoireHebert** [comment]
It should work without touching at the docker-compose.yml.
please check that the bundle `webonyx/graphql-php` is correctly activated.
check that the route graphql is available through `docker-compose exec app bin/console debug:router`
then check clearing your cache.
Don't hesitate to reload you docker by doing a `stop` then `up` It migh act weird sometime.

GraphQL is still in BETA and should not be used in production for now, but yes, an authentication feature would be nice :)

**Comment by dunglas** [comment]
Authentication and authorization **are** already supported. I don't know exactly what you mean by "but better way is a hide graphQL by symfony", but the GraphQL implementation is 100% integrated with Symfony, and if you put `/graphql` behind a Symfony firewall, it will work.

**Comment by Simperfit** [comment]
If you still have an issue please feel free to ping me or to re-open this one.

Thanks!

**Comment by minorbug** [comment]
This is still an issue, at least for me. 

Using the composer route, I can create an API Platform project that exposes the /graphql route correctly. 

When using the docker compose setup, and after adding the graphql package, I am unable to get to the  /graphql route. It DOES show up as a route in the debug output:
` api_graphql_entrypoint              ANY      ANY      ANY    /graphql      `
