### ISSUE TITLE
How to normalize/denormalize time fields

### ISSUE THREAD

**Issue by toby-griffiths** [api-platform/api-platform#545]
I've got a couple of time fields in a resource.  These are stored as DateTimeInterface objects.

The default output of the serializer is to output them as full dates (e.g. `1970-01-01T10:36:54+00:00`).

Is there an easy way to normalize/denormalize the values to/from a time string?

I've had a search around the Symfony DateTimeNormalizer and imaging that I might be able to decorate this, however I can't see a way of getting property specific context in to the normalizer, as it's only passed `$object`, `$format`, and `$context` (which is the object's context, not the individual property).  Aside from creating a custom `Time` class, and all the work associated with getting that working, does anyone know an easier way of doing this?

**Comment by soyuka** [comment]
Use a DateTimeNormalizer ?

I had to because I use some custom classes for date indexes:

```
<?php

declare(strict_types=1);

namespace App\Api\Serializer\Normalizer;

use App\Types\IdxDate;
use App\Types\IdxDateTime;
use Symfony\Component\Serializer\Normalizer\DateTimeNormalizer as DefaultDateTimeNormalizer;

class DateTimeNormalizer extends DefaultDateTimeNormalizer
{
    private static $supportedTypes = [
        \DateTimeInterface::class => true,
        \DateTimeImmutable::class => true,
        \DateTime::class => true,
        IdxDateTime::class => true,
        IdxDate::class => true,
    ];

    public function supportsDenormalization($data, $type, $format = null)
    {
        return isset(self::$supportedTypes[$type]);
    }
}
``` 

```
<?php

declare(strict_types=1);

namespace App\Types;

class IdxDate extends \DateTime
{
    const IDXDATE_FORMAT = 'd-m-Y';

    /**
     * toString.
     *
     * @return string
     */
    public function __toString()
    {
        return $this->format();
    }

    public function format($format = 'd-m-Y')
    {
        return parent::format(self::IDXDATE_FORMAT);
    }

    public static function createFromFormat($format, $time, $object = null)
    {
        $d = \DateTime::createFromFormat($format, $time);

        $t = new self();
        $t->setTimestamp($d->getTimestamp());

        return $t;
    }
}
```

Services:

```
# services.yaml
services:
    App\Api\Serializer\Normalizer\DateTimeNormalizer:
        tags: [ { name: 'serializer.normalizer'} ]
```

Note IIRC  `__toString` is used by the normalizer.

**Comment by toby-griffiths** [comment]
I can't use the existing DateTimeNormalizer, as this exports the data as a full date string, however your post has given me the thought of overriding the Doctrine 'time' (or 'time_immutable') Type and having it return a TimeImmutable object that can then be uniquely normalized/denormalized.

**Comment by soyuka** [comment]
Exactly what you should do, the example given doesn't output any hours/minutes data only date, month, year. Closing but ping me if unsolved.

**Comment by toby-griffiths** [comment]
@soyuka Thanks for the advice.  It's much appreciated.

**Comment by ehibes** [comment]
@soyuka I need a clarification, how do you link your entity with your custom types to make this working?

**Comment by hidabe** [comment]
Any solution for it?
