### ISSUE TITLE
Get status 500 after composer require api-platform/core

### ISSUE THREAD

**Issue by krypton-code** [api-platform/api-platform#546]
Hello everyone.
I get status 500 after `composer require api-platform/core`
If I run `composer require api-platform/api-pack`, that api-platform is setup correctly.

I use: 
Symfony 4.0.4
`"api-platform/api-pack": "^1.0"`, which received on http://flexrecipes.org/recipes/api-platform/api-pack

**Comment by dunglas** [comment]
Can you paste the stack trace you get?

**Comment by krypton-code** [comment]
@dunglas I recently started working with symfony, so I do not know how to get a stack trace.
I think use `symfony/debug`, but so far I have not figured out how to use it

**Comment by krypton-code** [comment]
@dunglas I can't even open the profiler.

**Comment by Simperfit** [comment]
@krypton-code feel free to ping me if this is still an issue.

(When @dunglas asked for the trace, he means the trace you got when requesting the API, not really related to the profiler).
