### ISSUE TITLE
Coup de gueule #2

### ISSUE THREAD

**Issue by abysKri** [api-platform/api-platform#549]
Vous répondez rapido et le cloturez aussitôt ! Vous ne lisez pas ce que l'on vous poste.
Merci pour les conseils, mais avant de poster j'ai bien sure tenté d'utiliser toutes les possibilités fournies, et meme demandé 1 devis pour vous dire (coaching), j’attends une réponse depuis plusieurs semaines. Vous avez certainement beaucoup de W et je le comprend.

Alors ma question est très simple, pouvez vous m'aider ?
Merci de ne pas fermer, il n'y a qu'ici que je peux espérer avoir une réponse dsl de pourrir vote github

**Comment by dunglas** [comment]
Bonjour @abysKri,

API Platform est un projet communautaire, open source et gratuit. Les-Tilleuls.coop en est effectivement le principal sponsor (bien que pas le seul) mais le projet n'est pas directement lié à la société. Beaucoup des mainteneurs du projet (et la plupart des contributeurs) ne travaillent pas pour Les-Tilleuls.coop.

Les gens qui contribuent au framework (y compris moi) le font sur leur temps libre et ne sont pas payé pour. Les contributions ainsi que le support communautaires et donc fait selon les disponibilités et les envies de développeurs bénévoles.
Certaines sociétés (parmi lesquels Les-Tilleuls.coop, mais pas que) peuvent également payer des développeurs pour ajouter des fonctionnalités nécessaire aux projets sur lesquels elles travaillent ou réaliser proposer des fonctionnalités commandées par des clients qui n'ont pas les compétences ou le temps pour les implémenter eux même.

Le bug tracker sur GitHub ne sert qu'aux rapport de bugs et propositions de patch, et uniquement en anglais.
Le support communautaire (c'est à dire fait par des bénévoles, gratuit, et sans aucune garantie) est disponible sur StackOverflow (en anglais uniquement, afin qu'un maximum de personnes puissent bénéficier des réponses apportées) et sur Slack (également en anglais et en français). Peut-être devriez-vous commencer par ces deux canaux.
Comme pour tous les projets open source, la documentation est bien sur perfectible. Des bugs existent et doivent être corrigés. Libre à vous et à toutes les bonnes volonté de le faire (ou de payer des gens pour le faire).

Concernant votre demande de support commercial auprès de Les-Tilleuls.coop, vous êtes en contact avec l'une de nos collègues depuis quelques jours, elle vous a transmis une proposition chiffrée. Les équipes de Les-Tilleuls.coop sont actuellement très chargées, et nous avons communiqué les dates de disponibilités les plus proches dont nous disposons.
Vous comprendrez que nous ne pouvons pas "déstaffer" des développeurs de projets clients en-cours (qui ont souvent également attendus pour obtenir ces prestations) afin de répondre immédiatement à une demande plutôt qu'à une autre.

Pour répondre à votre question simple : 

* la communauté peut vous apporter de l'aide en fonction de ses moyens, disponibilités et compétences, sans aucune garantie comme tout support bénévole (sur StackOverflow et Slack)
* Les-Tilleuls.coop peuvent vous apporter de l'aide avec un niveau de prestation garantie, aux dates précisées dans le devis
* d'autres sociétés ont également des compétences API Platform et peuvent également vous aider, je vous laisse le soin de chercher lesquelles et de vérifier avec elles leurs disponibilités

Cordialement,
