### ISSUE TITLE
Question: collectionOperations / access_control

### ISSUE THREAD

**Issue by BonnieDoug** [api-platform/api-platform#552]
When trying to control access in Api Platform the documentation states you can do the following in order to limit Item Operations:

```
/**
 * @ApiResource(
 *     attributes={"access_control"="is_granted('ROLE_USER')"},
 *     collectionOperations={
 *         "get"={"method"="GET"},
 *         "post"={"method"="POST", "access_control"="is_granted('ROLE_ADMIN')"}
 *     },
 *     itemOperations={
 *         "get"={"method"="GET", "access_control"="is_granted('ROLE_USER') and object.owner == user"}
 *     }
 * )
*/
```
There is however, no mention for how you would limit a collection by the current user. I tried the following but it fails, presumably because the collection is an array, with no direct access to the interior objects, so object.user doesn't exist.

```
/**
 * @ApiResource(
 *     collectionOperations={
 *         "get"={"method"="GET",  "access_control"="is_granted('ROLE_USER') and object.getOwner() == user"}
 *     }
 * )
*/
```
>   hydra:description: Unable to call method "owner" of object "ApiPlatform\Core\Bridge\Doctrine\Orm\Paginator

I was wondering if there is a built-in way of getting around this?

**Comment by antograssiot** [comment]
I use extension to automaticaly filter collection results in addition to access filter
 https://api-platform.com/docs/core/extensions/#extensions

**Comment by BonnieDoug** [comment]
@antograssiot Thank you very much. I knew I'd read it somewhere at some point (when I first read through the entire docs I assume) I just couldn't for the life of me find it when I was looking for it 😑 thought I just have dreamt it 😅

**Comment by BonnieDoug** [comment]
@antograssiot, When you use an extension, how did you get the API-Platform to reference it? There's no mention in the docs of putting it in the annotations etc, but it's definitely not firing at present.

**Comment by antograssiot** [comment]
@BonnieDoug by tagging you service, from the doc I linked before:
> Finally register the custom extension:

```
    'AppBundle\Doctrine\ORM\Extension\CurrentUserExtension':
        tags:
            - { name: api_platform.doctrine.orm.query_extension.collection, priority: 9 }
            - { name: api_platform.doctrine.orm.query_extension.item }

**Comment by BonnieDoug** [comment]
@antograssiot, Ahh, it seems my token isn't being retrieved by this:

```    public function __construct(TokenStorageInterface $tokenStorage, AuthorizationCheckerInterface $checker)
```

And therefore not entering the:

```
if($user instanceof User::class etc...)
```
Debugging `$this->tokenStorage->getToken()` returns null.

**Comment by BonnieDoug** [comment]
@antograssiot, I have this working now, however it now affects ALL endpoints, where I only want it to affect some, where specified. For example, my `/topics` endpoint doesn't have a `User` property, so now I get the following error:

>   "hydra:description": "[Semantical Error] line 0, col 40 near 'user = :current_user': Error: Class App\\Entity\\Topic has no field or association named user",

**Comment by antograssiot** [comment]
in your ` applyToCollection(QueryBuilder $queryBuilder, QueryNameGeneratorInterface $queryNameGenerator, string $resourceClass, string $operationName = null)` method you ca nthen just return based on the resource class and/or operation name.

for example I do
```php

    /**
     * {@inheritdoc}
     */
    public function applyToCollection(QueryBuilder $queryBuilder, QueryNameGeneratorInterface $queryNameGenerator, string $resourceClass, string $operationName = null)
    {
        $this->addWhere($queryBuilder, $resourceClass, $operationName);
    }

    /**
     * @param QueryBuilder $queryBuilder
     * @param string       $resourceClass
     * @param string       $operationName
     */
    private function addWhere(QueryBuilder $queryBuilder, string $resourceClass, ?string $operationName)
    {
        $user = $this->tokenStorage->getToken()->getUser();
        if (!$user instanceof SpecificUser) {
            return;
        }

        $rootAlias = $queryBuilder->getRootAliases()[0];
        switch ($resourceClass) {
            case Foo::class:
                $queryBuilder
                    ->andWhere(...))
                    ->setParameter(...))
                ;
                break;
            case Bar::class:
            case Baz::class:
                $queryBuilder
                    ->andWhere(...)
                    ->setParameter(...)
                ;
                if ($operationName === 'custom_action') {
                     queryBuilder
                        ->innerJoin(...)
                        ->andWhere(...)
                }
                break;
            ...
}
```

i'm not sure if it is considered as a best practice or if this is the best way to handle such issue but it works great in my use cases.

**Comment by BonnieDoug** [comment]
Thank you, I think I found a slightly clearer solution (but again I'm unsure if its best practice).
In the doc's example they do a check to see if the $resourceClass == Offers, however this ties it to that class. So instead of this I've got the follow:

```
$client = $this->tokenStorage->getToken()->getUser()->getClient();
        $class = new $resourceClass;
        if ($client instanceof Client && method_exists($class, 'getClient') && !$this->authorizationChecker->isGranted('ROLE_SUPER_ADMIN')) {
            $rootAlias = $queryBuilder->getRootAliases()[0];
            $queryBuilder->andWhere(sprintf('%s.client = :current_client', $rootAlias));
            $queryBuilder->setParameter('current_client', $client->getId());
        }
```

I hope this helps someone else at some point, and thank you @antograssiot  for your help.
