### ISSUE TITLE
API-platform and forms

### ISSUE THREAD

**Issue by apfz** [api-platform/api-platform#554]
Let's say I have an API built with the api-platform.com. Then I have a separate web-application built with Symfony 3 where I would like to use forms and push the data to the API-platform. What is the recommended way of doing this?

Here for example:
https://knpuniversity.com/screencast/symfony-rest/form-post

I need the Programmer() class within my web application. But instead I don't have that entity in my web app. Could anyone of you advice?

**Comment by byhoratiss** [comment]
Hmm sounds confusing.
If you are building your API with api-platform, you want to use it right?
How are you planning to consume your api?

If you have a separated sf3 application with your own forms & others, why you want to use the "separated" api?

**Comment by apfz** [comment]
because multiple applications will be communicating with the api. One of them is a web-application, another is a mobile app. So I would like to push data from my web-application to the api.

**Comment by byhoratiss** [comment]
So the web-app should have his own mechanism of communicating with api.
If the app is a sf3, you could write a Client using Guzzle.

**Comment by antograssiot** [comment]
https://github.com/csarrazi/CsaGuzzleBundle is a great candidate

**Comment by byhoratiss** [comment]
Seems usable. I have something like that, my own service using Guzzle to publish data in another's system API. But I prefered writing the logic, but of course, I didn't knew that bundle.
Good luck with that

**Comment by apfz** [comment]
Thanks @antograssiot  and @byhoratiss. I ended up doing something like this:

```
    /**
     * Create a new Dish
     *
     * @Security("has_role('ROLE_MANAGE_DISHES') or has_role('ROLE_SUPER_ADMIN')")
     * @param Request $request
     * @return RedirectResponse|Response
     */
    public function createAction(Request $request)
    {
        $client = $this->get('eight_points_guzzle.client.api_logistics');

        $form = $this->createForm(DishType::class);
        $form->handleRequest($request);

        $new_url = $this->generateUrl('new_dish');
        $redirect_url = $this->generateUrl('manage_dishes');

        if ($form->isSubmitted() && $form->isValid()) {

            $data = json_encode($form->getData());
            try {
                $client->post('/api/dishes', array('body' => $data));
                return $this->redirect($redirect_url);
            } catch (ClientException $e) {
                $this->handleErrors($e,$form);
            }
        }

        return $this->render('MyBundle:Common:basic.html.twig', array(
            'form' => $form->createView(),
            'page_title'=> 'Maaltijd aanmaken',
            'action_path' => $new_url,
            'cancel_path'=> $redirect_url,
            'submit_button_title'  => 'Opslaan',
        ));
    }
```

Now the next architectural question I have about this is that JWT tokens expire. Would this be practical in a case where a CRUD web-application is talking to my API endpoint? I am wondering why API Platform is suggesting to use JWT instead of API tokens. 

Different clients (like mobile apps and and other web applications) will talk to my API. Would all of them need to send their token in the header, receive a message its expired, refresh/get a new token, and make the call again?

**Comment by antograssiot** [comment]
@apfz To me, the main advantages of JWT over API keys are expiration mechanism and the fact that you can embed informations in the token. If you don't need it, it is up to you.
Regarding your last question this is how I do it personaly.

**Comment by apfz** [comment]
Thanks. These have cleared my questions. Much appreciated.
