### ISSUE TITLE
[ASK] How to use different EntityManagers / ManagerRegistry

### ISSUE THREAD

**Issue by byhoratiss** [api-platform/api-platform#556]
Is it possible to somehow "change" the used ManagerRegistry in default CollectionDataProvider & ItemProvider?

I'm using multiple EntityManagers, and each one using a custom DBAL connection and each EM maps the same "entities". Like this:
```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

            sql.bar:
                host:     "%db_bar_host%"
                dbname:   "%db_bar_name%"
                user:     "%db_bar_user%"
                password: "%db_bar_password%"
                charset:  UTF8

            sql.foo:
                host:     "%db_foo_host%"
                dbname:   "%db_foo_name%"
                user:     "%db_foo_user%"
                password: "%db_foo_password%"
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                mappings:
                    AppBundle: ~
            foo:
                connection: sql.foo
                mappings:
                    MyAwesomeBundle: ~
            bar:
                connection: sql.bar
                mappings:
                    MyAwesomeBundle: ~
```

I read the issue #226 that gives me a hint about how to do this but it seems applicable only to Write actions, and I need to every action (read & write).

I'm searching some way to change the ```$manager = $this->managerRegistry->getManagerForClass($resourceClass);``` of each DataProvider and use one that I could change according another service, maybe.

Any thoughts would be appreciated and thank you for this awesome library!

**Comment by soyuka** [comment]
Hi! We're always calling `getManagerForClass`, therefore if your doctrine configuration is correct it should work seamlessly! 

The `getManagerForClass` tells doctrine to use the EntityManager you mapped the class to, so it's exactly what you need. I think that there's an issue in your mappings because it should already work.

This is what I put under mappings:

```
            mappings:
                App\Press:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Press/Entity'
                    prefix: 'App\Press\Entity'
                    alias: App\Press
```

You can find more information on the symfony documetnation: https://symfony.com/doc/current/reference/configuration/doctrine.html#mapping-configuration

**Comment by byhoratiss** [comment]
Sorry @soyuka, it does works very well indeed, but always with one EntityManager connection.

My problem is that the same entity can be managed by multiple EntityManagers, but when the Registry asks for "who is the responsible EM for this entity", it always returns the first defined one.
So, even if I've an ```MyAwesomeBundle:Post``` entity, it will always be managed by ```foo``` EntityManager, and I need to work on ```bar``` EM.
Did I explained the problem?

**Comment by soyuka** [comment]
>  the same entity can be managed by multiple EntityManagers

Okay but this looks wrong, a given entity should be mapped by one and only one entity manager or I don't see the point. Indeed, a `Foo` class present on 2 DBMS is weird.

What you want (it seems) is to use one or another `Connection` according to given parameters. 

If you want this you'd have to implement your own DataProvider and use `$registry->getConnection('my_connection_name')`.

**Comment by byhoratiss** [comment]
Why having multiple databases with same schema is weird?
Seems a very common thing to me.

So the only way is decorating the existing DataProviders (Collection & Item) for overwriting the current behaviour?

**Comment by dunglas** [comment]
It looks ok to me to have support for this in core, would you mind opening a PR (and yes, using a decorator as a workaround should do the trick).

**Comment by soyuka** [comment]
> Why having multiple databases with same schema is weird?

Apart from the different envirnoments (in which case I'd just configure the connection part) I don't see the use case but I'd be very interested in one! Or maybe you have different entity repositories per DBMS?

**Comment by byhoratiss** [comment]
I don't know what kind of approach to use if I've to "switch" the DBAL connection for an EntityManager. And it should be available for every possible request to the API, any hints?

**Comment by soyuka** [comment]
Could you try to explain your use case? 
The core repository ([here](https://github.com/api-platform/core)) is tested against multiple DMBS (postgres, sqlite, mariadb) and we're using only 1 entity manager. It's configuration may be a good start point.

**Comment by BonnieDoug** [comment]
@byhoratiss Do you want multiple entity managers because you:

1. Have multiple databases within one Mysql instance?
2. Have multiple databases spread over different servers? 

If it's **1** then where you  define the table, you can also specify the database eg:

```
/**
 * Class WorkSectorSubQuestion
 * @ApiResource()
 * @ORM\Entity()
 * @ORM\Table("foo_database.bar_table")
 */
```

**Comment by byhoratiss** [comment]
@BonnieDoug I've multiple databases over different servers

@soyuka I read the configuration of the tests, and it seems that only uses / defines only one connection for the entire application. So there is no problem at all with that.
In my case I've multiple databases over different servers so I've multiple DBAL definitions with same schema defined by Doctrine ORM associations & mapping.
So, I've:
- DBAL 1 "default": mysql, entity_manager "default", common tables, settings, roles, etc.
- DBAL 2 "foo": sqlserver, entity_manager "foo", using "foo" DBAL connection, data I want to expose
- DBAL 3 "bar": sqlserver2, entity_manager "bar", using "bar" DBAL connection, more data, same structure than others
- DBAL 4 "zar": sqlserver3, entity_manager "zar", using "zar" DBAL connection, another thingy, same.
- EntityManagers "foo", "bar" and "zar" have the same Bundle mapped.

If I want to expose entities from my Bundle but through "bar" EntityManager, can't be done. It will always use the first EntityManager defined, which in my example, is "foo".
Thats the common behaviour of ```ManagerRegistry::getManagerForClass```.

I've the same problem using https://github.com/javiereguiluz/EasyAdminBundle but I could get it working by using my own controller and using the EntityManager that I specify.

Sorry about this long answer and I hope it clarifies my problem.
Thank you guys!

**Comment by byhoratiss** [comment]
Finally I get it working as I wanted without changing anything into Api-platform.
This is how I did it, just to help others that maybe would face the same problem.

For every database connection and server I used the proper DBAL configuration and also added my own "DynamicConnection" that will be used for the API.
```
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   pdo_mysql
                host:     "%database_host%"
                port:     "%database_port%"
                dbname:   "%database_name%"
                user:     "%database_user%"
                password: "%database_password%"
                charset:  UTF8

            sql.dynamic:
                wrapper_class: MyAwesome\Bundle\Doctrine\Connection\DynamicConnection
                charset:  UTF8

            sql.bar:
                host:     "%db_bar_host%"
                dbname:   "%db_bar_name%"
                user:     "%db_bar_user%"
                password: "%db_bar_password%"
                charset:  UTF8

            sql.foo:
                host:     "%db_foo_host%"
                dbname:   "%db_foo_name%"
                user:     "%db_foo_user%"
                password: "%db_foo_password%"
                charset:  UTF8
```

When I've to define my EntityManagers I gave them a name for every one and added ONE more just to be used through the API. Of course you can't change which one will be used, but in my case, when the ```ManagerRegistry::getManagerForClass``` is called, "api" entity manager will be used and the dynamic connection will use the right connection.
How? Just naming it alphabetically so in my list of EntityManagers, "api" is the first one that maps the same Bundles as the others.

The others EntityManagers are necessary to be able to use them by specifing the EM trough a console command or Controller or whatever, without the need of the bussiness logic of "dbSwitcher" service dependency of the wrapperClass.

```
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                connection: default
                mappings:
                    AppBundle: ~

            # Uses a Dynamic connection
            # Naming is Important: the first that matches the Bundle will be used as EM inside ManagerRegistry
            api:
                connection: sql.dynamic
                mappings:
                    MyAwesomeBundle: ~
                    
            foo:
                connection: sql.foo
                mappings:
                    MyAwesomeBundle: ~
            bar:
                connection: sql.bar
                mappings:
                    MyAwesomeBundle: ~
```

The database connection is configured by my custom wrapperClass, which uses the parameters of others connections. This wrapper uses a Service that holds the bussiness logic (user, roles & stuff) to know which connection has to be used.
Not sure if this solution is the right one, but still, this is the wrapper:
```
namespace MyAwesome\Bundle\Doctrine\Connection;

use Doctrine\DBAL\Connection;
use Doctrine\DBAL\Driver;
use Doctrine\DBAL\Event\ConnectionEventArgs;
use Doctrine\DBAL\Events;
use MyAwesome\Bundle\Services\DbSwitcher;

class DynamicConnection extends Connection
{
    /** @var DbSwitcher */
    protected $dbSwitcher;

    /**
     * @var bool
     */
    private $_isConnected = false;

    /**
     * The parameters used during creation of the Connection instance.
     *
     * @var array
     */
    private $_params = array();

    /**
     * @param DbSwitcher $dbSwitcher
     */
    public function setDbSwitcher(DbSwitcher $dbSwitcher)
    {
        $this->dbSwitcher = $dbSwitcher;
    }

    /**
     * @inheritDoc
     */
    public function connect()
    {
        $container = $this->dbSwitcher->getContainer();
        
        $connection = $container->get(sprintf('doctrine.dbal.sql.%s_connection', $this->dbSwitcher->getWorkingEntityManagerName()));

        $this->_params = $connection->getParams();

        if ($this->_isConnected) {
            return false;
        }

        $driverOptions = isset($this->_params['driverOptions']) ?
            $this->_params['driverOptions'] : array();
        $user = isset($this->_params['user']) ? $this->_params['user'] : null;
        $password = isset($this->_params['password']) ?
            $this->_params['password'] : null;

        $this->_conn = $this->_driver->connect($this->_params, $user, $password, $driverOptions);
        $this->_isConnected = true;

        if (false === $this->isAutoCommit()) {
            $this->beginTransaction();
        }

        if ($this->_eventManager->hasListeners(Events::postConnect)) {
            $eventArgs = new ConnectionEventArgs($this);
            $this->_eventManager->dispatchEvent(Events::postConnect, $eventArgs);
        }

        return true;
    }
}
```

And of course the proper CompilerPass to inject my own service to the Wrapper:
```
namespace MyAwesome\Bundle\Doctrine\DependencyInjection\CompilerPass;

use Symfony\Component\DependencyInjection\Compiler\CompilerPassInterface;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Reference;

class DynamicConnectionCompilerPass implements CompilerPassInterface
{
    /**
     * @inheritDoc
     */
    public function process(ContainerBuilder $container)
    {
        $container
            ->getDefinition('doctrine.dbal.sql.dynamic_connection')
            ->addMethodCall('setDbSwitcher', [
                new Reference('myawesomebundle.dbswitcher')
            ]);
    }

}
```

Sorry for the long post, but I hope it help others.
Any ideas would be welcome and thank you again!

**Comment by Simperfit** [comment]
Moved to the doc repository, @byhoratiss if you have some time to create a cookbook for using api-platform with dynamicconnection that will be awsome, thank you!

**Comment by rixbeck** [comment]
Hi @byhoratiss,

thanks for sharing your workaround, I have also problem with using different connections. Could you attach also the class `MyAwesome\Bundle\Services\DbSwitcher` please? 

cheers

**Comment by byhoratiss** [comment]
Hi @rixbeck 

My DbSwitcher is just keeping a Session value pointing to the right "connection" (sort of).
You could also add a request listener to set the right connection by user roles, or something you find useful.

```
namespace MyAwesome\Bundle\Services;

use Doctrine\DBAL\Connection;
use Doctrine\ORM\EntityManager;
use Symfony\Component\DependencyInjection\ContainerAwareTrait;
use Symfony\Component\HttpFoundation\Session\Session;

class DbSwitcher
{
    use ContainerAwareTrait;

    const SESSION_NAME = 'switcher.current_em';

    protected $currentEntityManager;

    /**
     * @param $em string
     * @return string
     */
    public function setWorkingEntityManagerName($em)
    {
        $this->currentEntityManager = $em;

        // Save as session for further usage if has RequestStack, to avoid
        // problems with console commands without session management
        if ($this->container->get('request_stack')->getCurrentRequest()) {
            $this->container->get('session')->set(self::SESSION_NAME, $em);
        }
    }

    /**
     * @return string
     */
    public function getWorkingEntityManagerName()
    {
        $session = null;

        if ($this->container->get('request_stack')->getCurrentRequest()) {
            $session = $this->container->get('session')->get(self::SESSION_NAME);
        }

        return ($this->currentEntityManager ? $this->currentEntityManager : $session);
    }

    /**
     * @return \Doctrine\Common\Persistence\ObjectManager|object
     */
    public function getEntityManager()
    {
        return $this->container->get('doctrine')->getManager($this->getWorkingEntityManagerName());
    }

    /**
     * @return Connection
     */
    public function getDatabaseConnection()
    {
        /** @var EntityManager $em */
        $em = $this->container->get(sprintf('doctrine.orm.%s_entity_manager', $this->getWorkingEntityManagerName()));

        return $em->getConnection();
    }

}
```

```
# config/services.yml
services:
    db.switcher:
        public: true
        class: MyAwesome\Bundle\Services\DbSwitcher
        calls:
          - method: setContainer
            arguments:
                - "@service_container"
```

**Comment by rixbeck** [comment]
@byhoratiss thats great! Thanks mate!

**Comment by denis-gorin** [comment]
my way is

App\Entity\MyEntity.php
```
/**
 * @ApiResource()
 * @ORM\Entity(repositoryClass=MyEntityRepository::class)
 * @ORM\Table("MyEntity")
 */
class Company
{
...
```
App\Repository\MyEntityRepository.php

```
namespace App\Repository;

use App\Entity\MyEntity;
use Doctrine\Persistence\ManagerRegistry;
use Doctrine\ORM\EntityRepository;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepositoryInterface;

class CompanyRepository extends EntityRepository implements ServiceEntityRepositoryInterface
{
    public function __construct(ManagerRegistry $registry)
    {
        $manager = $registry->getManager('NOT_DEFAULT_entity_manager');
        parent::__construct($manager, $manager->getClassMetadata(MyEntity::class));
    }
}
```
