### ISSUE TITLE
I should be able to build Docker environment whatever project issues

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/api-platform#56]
I'm currently trying to implement this project Docker configuration in my project using API Platform 2. I may have some issues on my project as it's still in development (so I could have some issues running Symfony commands like `cache:clear`).

As [Dockerfile runs `composer install`](https://github.com/api-platform/api-platform/blob/master/Dockerfile#L23), it will try to execute some Symfony commands, which will fail, which will block my Docker build.

Dockerfile should not execute any Composer or Symfony commands, to be able to create a correct Docker environment without project dependencies.

**Comment by Simperfit** [comment]
fixed by #87
