### ISSUE TITLE
Documentation: Active Filter with symfony 4

### ISSUE THREAD

**Issue by itkg-ppottie** [api-platform/api-platform#563]
Hello , my you need to indicate the rigth path with symfony 4 to active filters with Doctrine ORM Filters
[https://api-platform.com/docs/core/filters/#search-filter](url)
with config/packages/api_filters.yml for symfony 4 

Can save times to search why it's no working while the code is exactly the same that the documentation :P

**Comment by Simperfit** [comment]
Issue has been moved to the documentation repository.
