### ISSUE TITLE
Best way to deploy in production with Docker

### ISSUE THREAD

**Issue by mvigneron** [api-platform/api-platform#568]
Hello,

I'm using apiplatform with Docker in my dev environment.
- php-fpm
- nginx
- varnish
- mysql

Now, I would like to deploy my project in production. I think to use Jenkins but maybe it's not the best way ?

In dev, I'm using .env file to set my environment variables. In Symfony Docs, it's says to set real environment variables and don't use .env file.

So, I would like to know what is the best way to do it ?

Environment variable must be in nginx conf ? php-fpm conf ? set in host environment (to use for console symfony command) ? 

How Can I do it ? Where ? ...

Thanks for yours helps, it's very confusing for me

**Comment by dunglas** [comment]
I would suggest to use Kubernetes in production: https://api-platform.com/docs/deployment/kubernetes/

**Comment by mvigneron** [comment]
Ok thanks @dunglas 

I didn't see this doc...

I'm going to see that

So, we define environment variables directly in Kubernets Pod, right ?

**Comment by Simperfit** [comment]
You will have to define the environement on the deployment (which will run the pod, if you need to scale, then it will append the event to the newly created container).
I suggest you to look at https://github.com/continuouspipe/continuouspipe too.

**Comment by mvigneron** [comment]
Thanks @Simperfit
