### ISSUE TITLE
Resource ID's - support for non-url IRIs

### ISSUE THREAD

**Issue by pasinter** [api-platform/api-platform#569]
Is there a way to use resource UIDs as their ID? Eg currently API Platform renders a user resource ID as "/api/users/1". I would prefer the ID to be simply "1". Is there a way to implement this?

**Comment by dunglas** [comment]
I would discourage doing this, but can https://github.com/api-platform/core/pull/1365 work for you?

**Comment by pasinter** [comment]
Thanks @dunglas. I see the "allow_plain_identifiers" option is not implemented for the JSON API format. The JSON API spec has no opinion on whether IDs should be IRI's - in fact all their examples only have UIDs, so I think your implementation should support the "allow_plain_identifiers" option.

Would you accept a PR if I implemented it?

**Comment by dunglas** [comment]
Again I strongly discourage using this option, but as we accepted to introduce it for other formats, OK to add it to JSON API too.

**Comment by Simperfit** [comment]
This issue has been moved to the server component.
