### ISSUE TITLE
Pagination in custom Action based on repository result

### ISSUE THREAD

**Issue by DariuszLuber** [api-platform/api-platform#570]
Hi.

I have my custom action to get data based on repository. I want to use api-platform pagination, how to do that. 
Now repository gives me all results.

```
public function getSomeData(){
    $em = $this->getEntityManager();
    $queryBuilder = $em->createQueryBuilder();
    ....
    return $queryBuilder->getQuery()->getResult();
```

**Comment by soyuka** [comment]
use the doctrine paginator we support it

**Comment by DariuszLuber** [comment]
Thanks, for reply.

I changed in Repository to:
```
 $em = $this->getEntityManager();

        $queryBuilder = $em->createQueryBuilder();


        $queryBuilder -> select('ds') -> from(Drugstore::class,'ds');
        $paginator = new Paginator($queryBuilder);
        return $paginator;
```
and send request with params: page=1&itemsPerPage=1 - and still getting all records
What I'm doing wrong?

There is also one problem with paginator - it works only if there is no GroupBy in queryBuilder, also I want to use subquery in from section (which is supported only in createNativeQuery - which is not supported by paginator).

Any sugestions?

**Comment by soyuka** [comment]
Oh if you want to use our request parameters you need to use the [`PaginationExtension`](https://github.com/api-platform/core/blob/1bd1751b9bdadc79f7873f846347277cf77a98d0/src/Bridge/Doctrine/Orm/Extension/PaginationExtension.php) in your data provider.

Note that this is implementing a [`QueryResultCollectionExtensionInterface`](https://github.com/api-platform/core/blob/1bd1751b9bdadc79f7873f846347277cf77a98d0/src/Bridge/Doctrine/Orm/Extension/QueryResultCollectionExtensionInterface.php) and you need to call `getResult` on it. See for example:

https://github.com/api-platform/core/blob/1bd1751b9bdadc79f7873f846347277cf77a98d0/src/Bridge/Doctrine/Orm/CollectionDataProvider.php#L70

I'm not sure that you can do this from a repository though and you'll need to set up a DataProvider.

**Comment by DariuszLuber** [comment]
I have weird idea. Can I overwrite basic queryBuilder?
I try to do something like this:
- build filter 
```
final class ReportSearchByFilter implements QueryCollectionExtensionInterface
{

    private $request, $em;

    public function __construct(RequestStack $requestStack, EntityManager $entityManager)
    {
        $this -> request = $requestStack->getCurrentRequest();
        $this -> em = $entityManager;
    }

    public function applyToCollection(QueryBuilder $queryBuilder, QueryNameGeneratorInterface $queryNameGenerator, string $resourceClass, string $operationName = null)
    {


        switch( $this -> request -> getPathInfo() ){

            default:
                    $queryBuilder = $this->reportDrugStoreDrugSale();
                break;
        }

//        Gives me good DQL and all Parameters
//        dump($queryBuilder->getDQL());
//        dump($queryBuilder->getParameters());
//        exit;
    }
    private function reportDrugStoreDrugSale(){
       //....
      //return queryBuilder which I have from repository method
    }
}
```

- and try to use basic filters and pagination from api-platform

but when I debug I see that default filters are fired before my filter :/ 
I set priority to filter to 100, but still the same result.
Is it good way to try? What you think?

**Comment by A-Marwan** [comment]
Using the PaginationExtension or returning a doctrine paginator does not return hydra:view for me, any idea how to handle this?

**Comment by alanpoulain** [comment]
Please open another issue for the `hydra:view` key.
