### ISSUE TITLE
Error when trying to clear the cache whilst using 'collectionOperations'.

### ISSUE THREAD

**Issue by jr-cobweb** [api-platform/api-platform#572]
I'm using the following docblock on one of my entities:

```
/**
 * @ApiResource(
 *     attributes={
 *          "normalization_context"={"groups"={"document_read"}},
 *          "denormalization_context"={"groups"={"document_write"}}
 *     },
 *     collectionOperations={"get"}
 *)
 *
 * @ORM\Entity
 * @UniqueEntity(
 *     fields={"id"},
 *     message="This document already exists. Cannot recreate"
 * )
 */
```
When I try to clear the cache using the following command:

`docker-compose exec app bin/console cache:clear --env=prod`

I receive the following error:

```
 Type error: Argument 3 passed to ApiPlatform\Core\Bridge\Symfony\Routing\Ap  
  iLoader::addRoute() must be of the type string, integer given, called in /s  
  rv/api-platform/vendor/api-platform/core/src/Bridge/Symfony/Routing/ApiLoad  
  er.php on line 88     
```

If I remove the collectionOperations part, It's possible to clear the cache.

**Comment by jr-cobweb** [comment]
If anyone has the same issue, I managed to get around this by using the explicit definition:

```
/**
 * @ApiResource(
 *     attributes={
 *          "normalization_context"={"groups"={"document_read"}},
 *          "denormalization_context"={"groups"={"document_write"}}
 *     },
 *     collectionOperations={
 *          "get"={"method"="GET"},
 *          "post"={"method"="POST"}
 *     }
 *)
 *
 * @ORM\Entity
 * @UniqueEntity(
 *     fields={"id"},
 *     message="This document already exists. Cannot create duplicate."
 * )
 */
```

[The Docs](https://api-platform.com/docs/core/operations) do state that the first method should work however, so I'll leave this open until someone more experienced can comment.

**Comment by jr-cobweb** [comment]
Bump: Anyone had any luck following the documentation? Anyone know if the documentation needs updating?

**Comment by dunglas** [comment]
Are you sure you use the latest version?
If yes, it’s a bug to fix!

**Comment by jr-cobweb** [comment]
I thought I was, but apparently not. Updating seems to have fixed the issue. Thanks.
