### ISSUE TITLE
Cannot start docker services

### ISSUE THREAD

**Issue by jon-ht** [api-platform/api-platform#575]
Hello.

I'm struggling with docker in AP 2.2.0.
When I run `docker-compose up -d`, everythings seems to work. 

```
docker-compose up -d --build

...

Successfully built d04505723c6d
Creating apiplatform220_admin_1       ... done
Creating apiplatform220_php_1         ... done
Creating apiplatform220_client_1      ... done
Creating apiplatform220_api_1         ... done
Creating apiplatform220_admin_1       ...
Creating apiplatform220_cache-proxy_1 ... done
Creating apiplatform220_cache-proxy_1 ...
Creating apiplatform220_h2-proxy_1    ... done
```

But when I try to open `https://localhost` I'm having an exception `ERR_CONNECTION_REFUSED`.

My logs :

```
docker-compose logs -f
Attaching to apiplatform220_h2-proxy_1, apiplatform220_cache-proxy_1, apiplatform220_api_1, apiplatform220_admin_1, apiplatform220_client_1, apiplatform220_php_1, apiplatform220_db_1
h2-proxy_1     | 2018/02/16 21:26:45 [emerg] 1#1: host not found in upstream "client" in /etc/nginx/conf.d/default.conf:9
api_1          | 2018/02/16 21:26:19 [emerg] 1#1: host not found in upstream "php" in /etc/nginx/conf.d/default.conf:11
h2-proxy_1     | nginx: [emerg] host not found in upstream "client" in /etc/nginx/conf.d/default.conf:9
api_1          | nginx: [emerg] host not found in upstream "php" in /etc/nginx/conf.d/default.conf:11
cache-proxy_1  | + varnishd -a :80 -f /etc/varnish/default.vcl -s malloc,256m
php_1          | Composer could not find a composer.json file in /srv/api
admin_1        | yarn run v1.3.2
client_1       | yarn run v1.3.2
cache-proxy_1  | Error: Cannot read -f file '/etc/varnish/default.vcl' (No such file or directory)
php_1          | To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
admin_1        | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
db_1           | LOG:  database system was shut down at 2018-02-16 21:07:03 UTC
client_1       | error Couldn't find a package.json file in "/usr/src/client"
cache-proxy_1  | (-? gives usage)
admin_1        | error Couldn't find a package.json file in "/usr/src/admin"
db_1           | LOG:  MultiXact member wraparound protections are now enabled
client_1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
db_1           | LOG:  database system is ready to accept connections
db_1           | LOG:  autovacuum launcher started
db_1           | LOG:  database system was interrupted; last known up at 2018-02-16 21:08:05 UTC
db_1           | LOG:  database system was not properly shut down; automatic recovery in progress
db_1           | LOG:  invalid record length at 0/14EE8E0: wanted 24, got 0
db_1           | LOG:  redo is not required
db_1           | LOG:  MultiXact member wraparound protections are now enabled
db_1           | LOG:  database system is ready to accept connections
db_1           | LOG:  autovacuum launcher started
apiplatform220_h2-proxy_1 exited with code 1
apiplatform220_api_1 exited with code 1
apiplatform220_client_1 exited with code 1
apiplatform220_php_1 exited with code 1
apiplatform220_cache-proxy_1 exited with code 255
apiplatform220_admin_1 exited with code 1
```

Anyone can help me ?

## Additional notes

OS : Windows

```
docker -v
Docker version 17.12.0-ce, build c97c6d6
```

```
docker-compose ps
            Name                          Command               State             Ports
------------------------------------------------------------------------------------------------
apiplatform220_admin_1         /bin/sh -c yarn start           Exit 1
apiplatform220_api_1           nginx -g daemon off;            Up         0.0.0.0:8080->80/tcp
apiplatform220_cache-proxy_1   docker-app-start                Exit 255
apiplatform220_client_1        /bin/sh -c yarn start           Exit 1
apiplatform220_db_1            docker-entrypoint.sh postgres   Up         0.0.0.0:5433->5432/tcp
apiplatform220_h2-proxy_1      nginx -g daemon off;            Exit 1
apiplatform220_php_1           docker-entrypoint php-fpm       Exit 1
```

**Comment by dunglas** [comment]
It looks like there is a problem with the volumes. Do you use Docker for Windows or Docker Machine?

**Comment by jon-ht** [comment]
Latest Docker for Windows (atm)

**Comment by suryacaprice** [comment]
same issue here .. i am using docker machine

**Comment by jon-ht** [comment]
I have some news about this issue. It looks like my anti-virus, Kaspersky, was blocking docker connection. If I disable the protection, I'm able to up all services and access services endpoints.

As long as my anti-virus is suspended, I can navigate through differents UI. 

I ended up by edit my firewall rules to set docker connection as safe connection

**Comment by dunglas** [comment]
Good to know! Thanks for the feedback. It deserves an entry in the « troubleshooting » guide. Would you mind opening a doc PR with a screenshot of the Kaspersky screen where this option belongs?

**Comment by jon-ht** [comment]
I'll try as soon as possible. However, I never contributed to open source projects, do you have some recommandations ?

**Comment by dunglas** [comment]
For the docs, you can edit directly https://github.com/api-platform/docs/blob/2.2/extra/troubleshooting.md using the GitHub UI.

**Comment by jon-ht** [comment]
I'll take a look, thanks!

**Comment by jon-ht** [comment]
Sorry for the late answer. After a week of investigation, I'm still not able to start services. I don't know why it worked once, and then nothing... Maybe the bug isn't related to AP but Docker. Can't find any issue on it

**Comment by Simperfit** [comment]
You could please tell us what the bug is ? it's the same ?

**Comment by jon-ht** [comment]
Exactly the same as described in OP. Services start and then down with exit code 255 or 1 (and sometimes 12x, but not sure)

**Comment by jon-ht** [comment]
@Simperfit I'll try this week and keep you up-to-date

**Comment by jon-ht** [comment]
Sad news, I'm still not able to start services (except for db and sometimes api doesn't exit).

I upgraded Docker for Windows to version 18.03.0-ce, build 0520e24, but same result... I don't know where to look.

I tried :
- Clear Docker images
- Update Docker for Windows tool
- Set up Kaspersky firewall rules for virtual hosts
- Change ports from [docker-compose.yml](https://github.com/api-platform/api-platform/blob/v2.2.5/docker-compose.yml)

Any idea ?

**Comment by Simperfit** [comment]
The errors are the same ?

**Comment by jon-ht** [comment]
Exactly the same

**Comment by teohhanhui** [comment]
> Composer could not find a composer.json file in /srv/api

:scream: :scream_cat:

**Comment by teohhanhui** [comment]
Yes, it'd seem to me like all your volumes are not working.

**Comment by teohhanhui** [comment]
https://github.com/docker/compose/issues/4303

**Comment by jon-ht** [comment]
@teohhanhui I saw that env param, it's referenced in [AP doc](https://api-platform.com/docs/extra/troubleshooting#with-docker-toolbox-on-windows). I didn't set this value for AP 2.2.5 but I'm sure I've tried with 2.2.4. I'll try this !

**Comment by jon-ht** [comment]
OK, really weird. I installed AP 2.2.5 on another computer running on Windows 10 too and all worked fine, without `COMPOSE_CONVERT_WINDOWS_PATHS=1`

**Comment by Hoxydev** [comment]
@jon-ht can you tell us if your files are using CRLF or LF.
Try to open docker-compose.yaml and bin/console and tell us about your endline.
Btw your IDE give you the info like in the bottom right.

**Comment by jon-ht** [comment]
Files are encoded using LF.

Use `COMPOSE_CONVERT_WINDOWS_PATHS=1` doesn't work...

I tried to move project to different local drives (C:, P:, S:) and I always cleared all Docker images between each `docker-compose up -d`

**Comment by Hoxydev** [comment]
@jon-ht 
You use docker-toolbox right ?
Can you give us the info about your shared folder in VirtualBox ?

**Comment by teohhanhui** [comment]
Make sure you are using Docker for Windows. Docker Toolbox, Docker Machine etc. are not supported.

> The current version of Docker for Windows runs on 64bit Windows 10 Pro, Enterprise and Education (1607 Anniversary Update, Build 14393 or later).

https://docs.docker.com/docker-for-windows/install/#what-to-know-before-you-install

**Comment by jon-ht** [comment]
I'm using Docker for Windows and I've uninstalled/installed the latest version. I don't understand what happend but I've finally succeeded to make it work with this : https://stackoverflow.com/questions/42203488/settings-to-windows-firewall-to-allow-docker-for-windows-to-share-drive/43904051#43904051

> In PowerShell granted as admin
> `Set-NetConnectionProfile -interfacealias "vEthernet (DockerNAT)" -NetworkCategory Private`

But I'm not sure about that. I've rebooted my PC and it doesn't work anymore

**Comment by teohhanhui** [comment]
The mysteries of life. :tipping_hand_woman::tipping_hand_woman::tipping_hand_woman: :laughing:

**Comment by jon-ht** [comment]
I think this is more related to a missconfiguration of my PC (firewall/Kaspersky/wamp even if turned off, maybe) rather than AP

**Comment by teohhanhui** [comment]
@msitruk Which version of api-platform/api-platform?

**Comment by teohhanhui** [comment]
@msitruk I think it's because of mismatched versions of the pre-built images. You can try to do a `docker-compose build`.

Oops @dunglas, I should have gotten this fixed!

**Comment by napestershine** [comment]
@teohhanhui  it seems not helpful :(

**Comment by teohhanhui** [comment]
@napestershine Please provide more information to help us help you.

**Comment by LoicHa** [comment]
I manage to solve my issue by doing this :

1. On Command Line: "set COMPOSE_CONVERT_WINDOWS_PATHS=1";
2. Restart Docker for Windows;
3. Go to Docker for Windows settings > Shared Drives > Reset credentials > select drive > Apply;
![image](https://user-images.githubusercontent.com/28562111/56651314-11ff2f80-6689-11e9-9176-477d78454994.png)


If select a drive and apply doesn't work (that was the case for me ), do a Reset to factory default... in Reset docker tab.
![image](https://user-images.githubusercontent.com/28562111/56651275-ff84f600-6688-11e9-9e50-4076e9295ac7.png)

4. docker-compose up -d --build --force-recreate

**Comment by teohhanhui** [comment]
@LoicHa Awesome investigation! Thanks!

Relevant issue for `COMPOSE_CONVERT_WINDOWS_PATHS`: https://github.com/docker/for-win/issues/1829

Would you like to help us by documenting this? You could open a PR in https://github.com/api-platform/docs and add a new subsection "With Docker for Windows" under this section: https://github.com/api-platform/docs/blob/2.4/extra/troubleshooting.md#using-docker
