### ISSUE TITLE
How to document choices in API docs

### ISSUE THREAD

**Issue by apfz** [api-platform/api-platform#576]
In API-platform, how do I document the choices for a specific property? I have for example a property deliveryTimeWindow:

```
/**
 * @var string The delivery timewindow of this order.
 *
 * @ORM\Column
 * @Assert\Choice(callback="getTimeWindows")
 * @Assert\NotBlank()
 */
private $deliveryTimeWindow;
```

But the only thing I see in the front-end is an example "string".
How do I inform to my end-users that only a specific choice are allowed?

**Comment by Simperfit** [comment]
Are you talking about the open api (swagger) documentation or the hydra one ?

If you are talking about swagger you can use[ the context](https://api-platform.com/docs/core/swagger/#using-the-swagger-context) to set enum (choices).
