### ISSUE TITLE
[AIDE] Mise en place fichier RDFA

### ISSUE THREAD

**Issue by yacineblr** [api-platform/api-platform#578]
Bonjour,

Après plusieurs essais, je n'arrive pas à mettre en place le fichier RDFA pour utiliser le "schema-generator".

RDFA: 
`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
  </head>

  <body>

        
        <p vocab="http://schema.org/" typeof="User">
           <span property="rdfs:label">firstname</span>
           <span property="lastname">Lastname</span>
        </p>
        
        
        <div typeof="rdfs:Class">
            <span class="h" property="rdfs:label">User</span>
        </div>
        <div typeof="rdf:Property">
            <span class="h" property="rdfs:label">firstname</span>
        </div>

  </body>
</html>
`

SCHEMA.YML
`
header: false
checkIsGoodRelations: false
namespaces:
  entity: AppBundle\Entity
  interface: AppBundle\Model
doctrine:
  useCollection: true
validator:
  assertType: false
fieldVisibility: private
accessorMethods: true
id:
  generationStrategy: auto
debug: true
rdfa:
  - /home/lenovo/Documents/api-platform-2.1.6/app/config/api_platform/vgo.rdfa

types:
  User:
    parent: BaseUser
    namespaces:
      class: null
      interface: null
    properties:
      firstname: { nullable: false }
      lastname: { nullable: false }
      mail: { nullable: false }
      phoneNumber: { nullable: false }
      newsletter: { nullable: false }
      isDriver: { nullable: false }
      carModel: { nullable: true }
`

Quand je tente le premier exemple (propriété non reconnue), j'obtiens cette erreur:

[warning] Type "Travel" cannot be found. Using "Thing" type to generate entity.
[error] The property "firstname" (type "User") has an unknown type. Add its type to the config file.
[error] The property "lastname" (type "User") has an unknown type. Add its type to the config file.
[error] The property "mail" (type "User") has an unknown type. Add its type to the config file.
[error] The property "phoneNumber" (type "User") has an unknown type. Add its type to the config file.
[error] The property "newsletter" (type "User") has an unknown type. Add its type to the config file.
[error] The property "isDriver" (type "User") has an unknown type. Add its type to the config file.
[error] The property "carModel" (type "User") has an unknown type. Add its type to the config file.
[error] The property "travelReference" (type "Thing") has an unknown type. Add its type to the config file.
[error] The property "travelDate" (type "Thing") has an unknown type. Add its type to the config file.
[error] The property "transportationTime" (type "Thing") has an unknown type. Add its type to the config file.
[error] The property "zoneStart" (type "Thing") has an unknown type. Add its type to the config file.
[error] The property "carModel" (type "Thing") has an unknown type. Add its type to the config file.
[error] The property "direction" (type "Thing") has an unknown type. Add its type to the config file.
[error] The property "transportation" (type "Thing") has an unknown type. Add its type to the config file.
[error] The property "comment" (type "Thing") has an unknown type. Add its type to the config file.
[error] The property "place" (type "Thing") has an unknown type. Add its type to the config file.
[error] The property "isDriver" (type "Thing") has an unknown type. Add its type to the config file.
[error] The property "estimatedDepartureTime" (type "Thing") has an unknown type. Add its type to the config file.
[error] The property "creationDate" (type "Thing") has an unknown type. Add its type to the config file.
[error] The property "travelId" (type "Thing") has an unknown type. Add its type to the config file.

Et quand j'utilise seulement le deuxième exemple (erreur fatale), j'obtiens cette erreur:

PHP Fatal error:  Uncaught Error: Call to a member function getValue() on null in /home/lenovo/Documents/api-platform-2.1.6/vendor/api-platform/schema-generator/src/CardinalitiesExtractor.php:81
Stack trace:
#0 /home/lenovo/Documents/api-platform-2.1.6/vendor/api-platform/schema-generator/src/CardinalitiesExtractor.php(57): ApiPlatform\SchemaGenerator\CardinalitiesExtractor->extractForProperty(Object(EasyRdf_Resource))
#1 /home/lenovo/Documents/api-platform-2.1.6/vendor/api-platform/schema-generator/src/TypesGenerator.php(99): ApiPlatform\SchemaGenerator\CardinalitiesExtractor->extract()
#2 /home/lenovo/Documents/api-platform-2.1.6/vendor/api-platform/schema-generator/src/Command/GenerateTypesCommand.php(161): ApiPlatform\SchemaGenerator\TypesGenerator->__construct(Object(Twig_Environment), Object(Symfony\Component\Console\Logger\ConsoleLogger), Array, Object(ApiPlatform\SchemaGenerator\CardinalitiesExtractor), Object(ApiPlatform\SchemaGenerator\GoodRelationsBridge))
#3 /home/lenovo/Documents/api-platform-2.1.6/vendor/symfony/ in /home/lenovo/Documents/api-platform-2.1.6/vendor/api-platform/schema-generator/src/CardinalitiesExtractor.php on line 81

**Comment by mmeloni** [comment]
Insert a comment:
<span property="rdfs:comment">Your comment</span>
