### ISSUE TITLE
unable to start in windows docker in vm with docker machine

### ISSUE THREAD

**Issue by suryacaprice** [api-platform/api-platform#579]
client_1       | yarn run v1.3.2
client_1       | error Couldn't find a package.json file in "/usr/src/client"
db_1           | The files belonging to this database system will be owned by user "postgres".
client_1       | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
db_1           | This user must also own the server process.
admin_1        | yarn run v1.3.2
db_1           |
db_1           | The database cluster will be initialized with locale "en_US.utf8".
admin_1        | error Couldn't find a package.json file in "/usr/src/admin"
php_1          | standard_init_linux.go:195: exec user process caused "no such file or directory"
db_1           | The default database encoding has accordingly been set to "UTF8".
api_1          | 2018/02/22 09:10:10 [emerg] 1#1: host not found in upstream "php" in /etc/nginx/conf.d/default.conf:11
db_1           | The default text search configuration will be set to "english".
api_1          | nginx: [emerg] host not found in upstream "php" in /etc/nginx/conf.d/default.conf:11
admin_1        | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
db_1           |
db_1           | Data page checksums are disabled.
cache-proxy_1  | standard_init_linux.go:195: exec user process caused "no such file or directory"
db_1           |
h2-proxy_1     | 2018/02/22 09:10:24 [emerg] 1#1: host not found in upstream "client" in /etc/nginx/conf.d/default.conf:9
db_1           | fixing permissions on existing directory /var/lib/postgresql/data ... ok
h2-proxy_1     | nginx: [emerg] host not found in upstream "client" in /etc/nginx/conf.d/default.conf:9
db_1           | creating subdirectories ... ok
db_1           | selecting default max_connections ... 100
db_1           | selecting default shared_buffers ... 128MB
db_1           | selecting dynamic shared memory implementation ... posix
db_1           | creating configuration files ... ok
db_1           | running bootstrap script ... ok
db_1           | performing post-bootstrap initialization ... sh: locale: not found
demo_client_1 exited with code 1
db_1           | No usable system locales were found.
db_1           | Use the option "--debug" to see details.
demo_api_1 exited with code 1
demo_php_1 exited with code 1
demo_admin_1 exited with code 1
demo_cache-proxy_1 exited with code 1
demo_h2-proxy_1 exited with code 1
db_1           | ok
db_1           | syncing data to disk ...
db_1           | WARNING: enabling "trust" authentication for local connections
db_1           | You can change this by editing pg_hba.conf or using the option -A, or
db_1           | --auth-local and --auth-host, the next time you run initdb.
db_1           | ok
db_1           |
db_1           | Success. You can now start the database server using:
db_1           |
db_1           |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db_1           |
db_1           | waiting for server to start....LOG:  could not bind IPv6 socket: Address not available
db_1           | HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
db_1           | LOG:  database system was shut down at 2018-02-22 09:10:09 UTC
db_1           | LOG:  MultiXact member wraparound protections are now enabled
db_1           | LOG:  database system is ready to accept connections
db_1           | LOG:  autovacuum launcher started
db_1           |  done
db_1           | server started
db_1           | CREATE DATABASE
db_1           |
db_1           | CREATE ROLE
db_1           |
db_1           |
db_1           | /usr/local/bin/docker-entrypoint.sh: ignoring /docker-entrypoint-initdb.d/*
db_1           |
db_1           | LOG:  received fast shutdown request
db_1           | LOG:  aborting any active transactions
db_1           | LOG:  autovacuum launcher shutting down
db_1           | waiting for server to shut down....LOG:  shutting down
db_1           | LOG:  database system is shut down
db_1           |  done
db_1           | server stopped
db_1           |
db_1           | PostgreSQL init process complete; ready for start up.
db_1           |
db_1           | LOG:  database system was shut down at 2018-02-22 09:11:21 UTC
db_1           | LOG:  MultiXact member wraparound protections are now enabled

does anyone know how to solve this?

**Comment by dunglas** [comment]
I don't have a Windows box to debug... It looks related to volumes.

**Comment by Simperfit** [comment]
Could you please try with last version ?
If you still have an issue please feel free to ping me.
