### ISSUE TITLE
Configure enable_max_depth globally

### ISSUE THREAD

**Issue by silverbackdan** [api-platform/api-platform#585]
Is there a chance we could configue the `enable_max_depth` context parameter globally from the API Platform config?

It may also be nice to have a default handler in `AbstractItemNormalizer.php` similar to the circular reference handler:
```
$this->setCircularReferenceHandler(function ($object) {
    return $this->iriConverter->getIriFromItem($object);
});
```

There would need to be a check to ensure that function exists to support older versions of the serializer, but I think it'd be a nice feature. Possibly a global max_depth configuration option too?

I'm aware I could resolve my issues by disabling force_eager as well.

I did notice that using 2.1.1 my issues disappeared and I didn't need the max_depth configured at all, but the maximum joined relations error has resurfaced with 2.2.2. I understand why as I have a circular entity reference (componentGroup -> components -> componentGroup ... etc) but I just wondered whether it may be worth keeping the eager loading and enabling max_depth.

I've tried adding the enable_max_depth into the context on a custom normalizer, but that doesn't seem to always be called and I haven't traced back why this is yet.

Happy to write a PR if this is an idea you'd consider. Thanks!

**Comment by Simperfit** [comment]
Issue moved to core.
