### ISSUE TITLE
No route found for "GET /" error with Symfony 4.0.4 

### ISSUE THREAD

**Issue by tahirm** [api-platform/api-platform#589]
I followed steps mentioned in following guide to setup new api-platform project. 
https://api-platform.com/docs/distribution#using-symfony-flex-and-composer-advanced-users
Only difference is that im using my own virtual host instead of built in php server.

But Im getting `No route found for "GET /"` error. 
<img width="1040" alt="api-platform-error" src="https://user-images.githubusercontent.com/2377539/36691216-d3659d5e-1b34-11e8-8cc2-ea742795b106.png">

I also tested it by installing the symfony only and I was able to see symfony welcome page successfully. but as soon as I install api-platform and visit the page, I get above mentioned error.

Further details:
```
api-platform:  v2.2.2
symfony: v4.0.4
PHP: 7.1
Server: Apache2
OS: ubuntu
```

**Comment by antograssiot** [comment]
did you try `bin/console debug:router` ?
I did follow those steps and the base route is `/api`

see your `config/routes/api-platform.yaml`

**Comment by tahirm** [comment]
Thanks for quick reply.
Following is output for `bin/console debug:router`

```
$ bin/console debug:router
 -------------------- -------- -------- ------ -------------------------------------
  Name                 Method   Scheme   Host   Path
 -------------------- -------- -------- ------ -------------------------------------
  api_entrypoint       ANY      ANY      ANY    /api/{index}.{_format}
  api_doc              ANY      ANY      ANY    /api/docs.{_format}
  api_jsonld_context   ANY      ANY      ANY    /api/contexts/{shortName}.{_format}
  _twig_error_test     ANY      ANY      ANY    /_error/{code}.{_format}
 -------------------- -------- -------- ------ -------------------------------------
```


And this is what I have in `config/routes/api-platform.yaml`:
```
api_platform:
    resource: .
    type: api_platform
    prefix: /api

```

I have tried `/api` as well, but i get default apache 404 page

<img width="411" alt="screen shot 2018-02-26 at 21 27 01" src="https://user-images.githubusercontent.com/2377539/36693603-15587c7a-1b3c-11e8-92bc-d6df747f61a8.png">

**Comment by antograssiot** [comment]
Well, the routes are defined, then it is likely due to your apache config because it works using the php build-in server...
to be sure you might give a try to `composer req server` and `bin/console server:run`. I don't think I can help more.

**Comment by tahirm** [comment]
Turns out I was missing proper rewrite rules, which I got by installing `composer require symfony/apache-pack` as mentioned in symfony docs:

https://symfony.com/doc/current/setup/web_server_configuration.html

After this, I was able to access api-platform on `/api`

@antograssiot, Thank you very much for pointing me to right direction.

**Comment by MarineGirardey** [comment]
Worked for me I've just copy paste `composer require symfony/apache-pack` and for some reason it worked but no `composer require --dev symfony/profiler-pack`
#newtosymfony
