### ISSUE TITLE
how to change/update only the current user

### ISSUE THREAD

**Issue by sylflo** [api-platform/api-platform#595]
So my problem is the following one
I have a user model with a one to many relationship to an Address model.

Now to add an address to the user I do the following:
`
"firstName": "string",
....
 "user": "/users/1",
`
It works correctly except I am having a security problem. Any user can add an address to any other user as long as they are connected and know the id/uid of the user they want to add the address.

So that's my question how can you protect this ?
I saw the example on the doc to get only resources which belong to an user, it works. But for this case I am lost. A bit of help would be really nice

EDIT: I suppose the answer is probably that https://api-platform.com/docs/core/serialization/#changing-the-serialization-context-on-a-per-item-basis but I am not sure

**Comment by antograssiot** [comment]
Did you try using "access_control" attribute  ?
https://api-platform.com/docs/core/security/#security

**Comment by sylflo** [comment]
Thanks you very much for your quick reply

Yeah I did it works for the get but I don't understand how it can work with the put/post.
For the get we can do something like that 
```
"access_control"="object.user.getId() == user.getId()"
```
But for the put/post how to check that when the user send that 
```
"firstName": "string", .... "user": "/users/1",
```
That the id 1 is the id of the current user and not the id of an another user ?

**Comment by antograssiot** [comment]
There are several possibilities.
I think that `is_granted` plus a custom voter will do the trick if `"object.user == user"` doesn't

Another trick would be to force/override the active user id in a listener or a custom action by yourself.

Using denormaliaztion_group you could be sure that user can't put/post the user property,  and force the active User with custom code or a Blamable behavior from [Doctrine Extensions](https://symfony.com/doc/master/bundles/StofDoctrineExtensionsBundle/index.html)

**Comment by sylflo** [comment]
Ok thanks it works by using access_control I did not realize it was possible to do `object.user == user` on all the request. 
Thank you very much your time and clear explanations.
