### ISSUE TITLE
Duplicate endpoints with Swagger UI

### ISSUE THREAD

**Issue by cduran433** [api-platform/api-platform#598]
Automatic documentation generated with swagger UI adds duplicated endpoints. This is the normal behavior but I want to keep my database as clean as possible, so it would be possible to remove one of then from the API. I was looking the doc but I didn't find how to do it.

**Comment by Simperfit** [comment]
You can use a decorator for swagger based on the DocumentationNormalizer,[ we have an exemple of this in the docs](https://api-platform.com/docs/core/swagger/#overriding-the-swagger-documentation).
