### ISSUE TITLE
Exists Filter

### ISSUE THREAD

**Issue by ahmed-hachena** [api-platform/api-platform#604]
Hi

[here](https://api-platform.com/docs/core/filters/#exists-filter) in documentation exists filter is used as follow `?exists[property]=<true|false|1|0>` while it works with this syntax: `?property[exists]=<true|false|1|0>` (tested with latest release).

I don't know which place require changes doc or filter implementation it self.

**Comment by meyerbaptiste** [comment]
This was fixed this afternoon: https://github.com/api-platform/docs/pull/430.

Thx for the report.
