### ISSUE TITLE
Docs/Feature request !=

### ISSUE THREAD

**Issue by purplefish32** [api-platform/api-platform#605]
Sorry if this is more of a question than a bug report.

I know you can do this :
http://localhost:8000/api/offers?name=shirt

Is there a way of doing the inverse ?
> http://localhost:8000/api/offers?name!=shirt
> http://localhost:8000/api/offers?name[not]=shirt

I could not find any reference in the Docs.
This is either a request for documenting an existing feature or a request to implement a new feature.

**Comment by alanpoulain** [comment]
See https://github.com/api-platform/core/issues/2400.
