### ISSUE TITLE
Excpected value of type, got string instead

### ISSUE THREAD

**Issue by TheJenne18** [api-platform/api-platform#607]
I want to create an IP Address, and the IP Address has a subnet.
But when I do the this call:

`{
	"ipAddress": "192.168.1.1",
	"hostname": "Test",
	"hostDescription": "Description Test",
	"subnet": "/api/subnets/120665"
}`

I receive this result: `"hydra:description": "Expected value of type \"App\\Entity\\Subnet\" for association field \"App\\Entity\\IpAddress#$subnet\", got \"string\" instead."`

And the route exits.
` api_subnets_get_collection         GET      ANY      ANY    /api/subnets.{_format} `

**Comment by Simperfit** [comment]
@TheJenne18 Could you please paste the entities, so we can have a look and maybe know why it's not working properly ?

**Comment by Simperfit** [comment]
Closing as we got no feedback.
