### ISSUE TITLE
Cache ban does not work with 404 responses

### ISSUE THREAD

**Issue by jr-cobweb** [api-platform/api-platform#609]
I'm having an issue with the varnish cache not being cleared (so to speak) after creating a new entity via a POST request. 

**Here's the workflow to reproduce the issue:**

Attempt to retrieve a non-existent entity:
`GET /your_entity/12345`

Create the entity:
`POST /your_entity/12345`

Attempt to retrieve the newly created entity:
`GET /your_entity/12345`

The second GET request incorrectly returns a 404 response. From what I can tell this is because `isCacheable` (AddTagsListener, Line 52) returns false for 404 responses, so the Cache-Tags are never added as a response header.

**Comment by jr-cobweb** [comment]
Also, if it helps for 404 responses, the Response instance is created at:

ExceptionAction, Line 87

And because we're not passing in any Cache-Control headers, they are added as a default in:

ResponseHeaderBag, Line 126

**Comment by Simperfit** [comment]
@jr-cobweb it is still an issue ? if it's the case could you please create one in [the core component ](https://github.com/api-platform/core)?

**Comment by jr-cobweb** [comment]
@Simperfit Yep, as far as I'm aware. I found a way around it so not really checked back since I posted this. I'll add it to the core component.
