### ISSUE TITLE
Option to return shorter cache-tag headers

### ISSUE THREAD

**Issue by silverbackdan** [api-platform/api-platform#614]
Is there a way to perhaps return cache tags of resources represented as a hash instead of each individual resource id included? On a project I'm creating, one resource can return a lot of others and this quickly means that my maximum header size on nginx proxy needs to be increased.

**Comment by jr-cobweb** [comment]
I'm having a similar issue when POSTing an entity with a lot of relations. I'm currently working around it by separating the request out into batches, but I would be interested to know if there are any plans to reduce the header size.

**Comment by silverbackdan** [comment]
I'd be happy to write a PR for this but am unsure as to whether there's a preference of just converting the requested resources that are inserted into the cache-tags header into an md5 hash or something, or making this a configurable option.

**Comment by silverbackdan** [comment]
Just reviewing some old issues I've opened that are still around - Is this an enhancement that is worthwhile or is it best just to increase the maximum header size limit?

**Comment by dunglas** [comment]
I think we should plan to move to Varnish's xkey fist.

**Comment by silverbackdan** [comment]
Sounds good, I'll close this issue in favour of moving to xkey and if required, changing the nginx maximum header size. Thanks for the quick reply.
