### ISSUE TITLE
Enable/Disable swagger documentation with .env parameters

### ISSUE THREAD

**Issue by deivid11** [api-platform/api-platform#619]
I want to disable swagger docummentation in my prod server but also use swagger in my development enviroment. So I decided to create a variable in my .env configuration like this:

`ENABLE_API_DOCUMENTATION=1
`

Then in my api_platform.yaml:

```
enable_swagger: '%env(bool:ENABLE_API_DOCUMENTATION)%'
enable_swagger_ui: '%env(bool:ENABLE_API_DOCUMENTATION)%'
```

.env files read parameters as string so I tried casting to bool but is not working, Im getting this error 'Invalid type for path "api_platform.enable_swagger". Expected boolean, but got string.'. I found some reference [here](https://stackoverflow.com/questions/49347061/symfony4-casting-env-variable-issue). Im not really sure if it has to do of how api platform is reading the parameters or if it is a symfony issue.

**Comment by ljbergmann** [comment]
Based on my understanding of envy and the loadding process of config files the simplest way to achieve this is moving the `api_platform.yaml` from `config/packages/ `to `config/packages/dev` or `config/packages/prod` and modify them as you need.

**Comment by Simperfit** [comment]
The fact is it's a string because at the moment it came into the configuration is has not been parsed so for exemple: if we allow string nodes, it will came as something like: `env_bool_ENABLE_API_DOCUMENTATION_xxxxxxxxxx`.

So the simplest way it like @ljbergmann said, to use different value based on the directory.

**Comment by Simperfit** [comment]
Closing as this has been answered, I don't think there are something to do in API-Platform for this to work.
