### ISSUE TITLE
Is there no branch left for v1.1.* and v1.0.*?

### ISSUE THREAD

**Issue by robertfausk** [api-platform/api-platform#62]
Currently there are two banches "master" and "remove_register_globals".
Both seems to be for version 2.*.

Is 1.0 and 1.1 dead or unsupported?

**Comment by Simperfit** [comment]
@robertfausk : There is not branch for V1 / V1.1 on this repository which is the standard version, there are tags on this repository and the 1.x is in [Api Platform Core](https://github.com/api-platform/core).

**Comment by teohhanhui** [comment]
We might want to consider maintaining stable branches for the Standard Edition going forward.

What do you think @api-platform/core-team?

**Comment by Simperfit** [comment]
@teohhanhui do we recommend using v1 ?

**Comment by soyuka** [comment]
As v2 will be out soon, nope. Still, we might want to consider the above for v2.

**Comment by Simperfit** [comment]
I agree, ping @api-platform/core-team WDYT ?

**Comment by theofidry** [comment]
I'm for @teohhanhui suggestion for future versions.

**Comment by teohhanhui** [comment]
It really depends on our level of commitment. If we have branches, it'll be a lot more work to maintain and sync... Unless we can cope with it, I'd say we should just use tags.

**Comment by teohhanhui** [comment]
I see that there is already a 1.x branch. Hmm...

**Comment by Simperfit** [comment]
@teohhanhui on bug fixes it is
