### ISSUE TITLE
Use custom normalizer to modify class properties

### ISSUE THREAD

**Issue by carlespibernatcreus** [api-platform/api-platform#620]
Hello!

I have an entity with 2 properties, `name` and `photo`.  The `name` property is read from the database but I have to fill the `photo` property with some other information.

I have followed the **[Writing a Custom Nomalizer](https://api-platform.com/docs/core/content-negotiation#writing-a-custom-normalizer)** tutorial from the docs and I have made my custom normalizer:

```php
<?php

namespace App\Serializer;

use App\Entity\Style;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;
use Vich\UploaderBundle\Templating\Helper\UploaderHelper;

final class StyleNormalizer implements NormalizerInterface, DenormalizerInterface
{
    private $normalizer;

    private $uploaderHelper;

    public function __construct(NormalizerInterface $normalizer, UploaderHelper $uploaderHelper)
    {
        if (!$normalizer instanceof DenormalizerInterface) {
            throw new \InvalidArgumentException('The normalizer must implement the DenormalizerInterface');
        }

        $this->normalizer = $normalizer;
        $this->uploaderHelper = $uploaderHelper;
    }

    public function denormalize($data, $class, $format = null, array $context = [])
    {
        return $this->normalizer->denormalize($data, $class, $format, $context);
    }

    public function supportsDenormalization($data, $type, $format = null)
    {
        return $this->normalizer->supportsDenormalization($data, $type, $format);
    }

    public function normalize($object, $format = null, array $context = [])
    {
        if ($object instanceof Style) {
            $object->setPhoto('http://api-platform.com');
        }

        return $this->normalizer->normalize($object, $format, $context);
    }

    public function supportsNormalization($data, $format = null)
    {
        return $this->normalizer->supportsNormalization($data, $format);
    }
}
```

But the `photo` property is not filled with the required information.

After a little bit of debug I have found that the `supportsNormalization` method is executed two times (for each database element). If I print the `$data`variable, I got the entity `name` property the first time and the `photo` property with `null` value the second time. I never got the entire `Style` entity. Then the `supportsNormalitzation` method always returns `false`.

How can I get the full `Style` entity and modify its properties?

Thanks!
Carles

**Comment by gries** [comment]
Hi,
Can you provide an example request(URI+Payload) that you are using?
It seems to me that $data should include both values name + photo.

**Comment by Simperfit** [comment]
@carlespibernatcreus Could you please answer @gries's question so we could be able to understand what's the issue ?

**Comment by carlespibernatcreus** [comment]
Hi!

Sorry, I resolved my problem adding `decorates: 'api_platform.jsonld.normalizer.item'` to the service definition, it was only working when using json.

Thanks!
Carles

**Comment by abysKri** [comment]
Hi 👍 
Is there a way to do the same think, but with json format ?
Thanks a lot

**Comment by carlespibernatcreus** [comment]
Isn't it working with `api_platform.json.normalizer.item`?

**Comment by malejulien013** [comment]
Hi,
I have a Product Entity, and I want to customize the price seen by the user.
As carlespibernatcreus did, I use a Normalizer that calls the method setCustomPrice() from my entity with a group context "get", and it works great.

`public function normalize($object, $format = null, array $context = [])
    {
        if ($object instanceof Product) {
            $object->setCustomPrice($this->tokenStorage->getToken()->getUser());
        }

        return $this->decorated->normalize($object, $format, $context);
    }`

`{"@context":"\/api\/contexts\/Product","@id":"\/api\/products\/1","@type":"Product","name":"Product1","reference":"product_1","customPrice":150}`

However, if I try to set a custom @group context (on both Item or Collection operations, "get-product" by example), I have a error 500 "Warning: get_class() expects parameter 1 to be object, float given".
I tried to troubleshoot by my own this issue with no success....
Maybe my way to get the custom price using normalizer is not the right way, but I didn't find another way to get it.
I can let the "get" group context, but I would like to customize the normalization context for some entities.
Thanks by advance for your help.

**Comment by teohhanhui** [comment]
@malejulien013 Not sure what your issue is, can you share more information? A stack trace, perhaps?

**Comment by malejulien013** [comment]
Thanks for your answer ;)
As explained, I have a Product entity class in which I use normalization context :

```
/**
 * @ApiResource(
 *     itemOperations={
 *         "get"={
 *             "normalization_context"={
 *                 "groups"={"get"}
 *             }
 *         },
...
 *     collectionOperations={
 *         "get"={
 *             "normalization_context"={
 *                 "groups"={"get"}
 *             }
 *         },
```
And I use a field to get a customPrice fot the user that call the Product resource :

```
    /**
     * @Groups({"get"})
     */
    private $customPrice;
```
This field is calculated dinamically with the normalizer :

```
public function normalize($object, $format = null, array $context = [])
 {
    if ($object instanceof Product) {
        $object->setCustomPrice($this->tokenStorage->getToken()->getUser());
    }
    return $this->decorated->normalize($object, $format, $context);
}
```
When I make a request on /api/products ou /api/products/{id}, the customPrice works great :

> {"@context":"\/api\/contexts\/Product","@id":"\/api\/products\/1","@type":"Product","name":"Product1","reference":"product_1","customPrice":150}

But if I change the group context in order to get custom context for item or collection :

```
/**
 * @ApiResource(
 *     itemOperations={
 *         "get"={
 *             "normalization_context"={
 *                 "groups"={"get-product"}
 *             }
 *         },
...
 *     collectionOperations={
 *         "get"={
 *             "normalization_context"={
 *                 "groups"={"get-products"}
 *             }
 *         },
...
/**
     * @Groups({"get-product", "get-products"})
     */
    private $customPrice;
```
I have an error 500 :

> {"@context":"\/api\/contexts\/Error","@type":"hydra:Error","hydra:title":"An error occurred","hydra:description":"Warning: get_class() expects parameter 1 to be object, float given","trace":[{"namespace":"","short_class":"","class":"","type":"","function":"","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\api-platform\\core\\src\\Util\\ClassInfoTrait.php","line":32,"args":[]},{"namespace":"ApiPlatform\\Core\\Bridge\\Symfony\\Routing","short_class":"IriConverter","class":"ApiPlatform\\Core\\Bridge\\Symfony\\Routing\\IriConverter","type":"-\u003E","function":"getObjectClass","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\api-platform\\core\\src\\Util\\ResourceClassInfoTrait.php","line":42,"args":[["float",150]]},{"namespace":"ApiPlatform\\Core\\Bridge\\Symfony\\Routing","short_class":"IriConverter","class":"ApiPlatform\\Core\\Bridge\\Symfony\\Routing\\IriConverter","type":"-\u003E","function":"getResourceClass","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\api-platform\\core\\src\\Bridge\\Symfony\\Routing\\IriConverter.php","line":120,"args":[["float",150],["boolean",true]]},{"namespace":"ApiPlatform\\Core\\Bridge\\Symfony\\Routing","short_class":"IriConverter","class":"ApiPlatform\\Core\\Bridge\\Symfony\\Routing\\IriConverter","type":"-\u003E","function":"getIriFromItem","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\api-platform\\core\\src\\Serializer\\AbstractItemNormalizer.php","line":593,"args":[["float",150]]},{"namespace":"ApiPlatform\\Core\\Serializer","short_class":"AbstractItemNormalizer","class":"ApiPlatform\\Core\\Serializer\\AbstractItemNormalizer","type":"-\u003E","function":"normalizeRelation","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\api-platform\\core\\src\\Serializer\\AbstractItemNormalizer.php","line":549,"args":[["object","ApiPlatform\\Core\\Metadata\\Property\\PropertyMetadata"],["float",150],["string","App\\Entity\\User"],["string","jsonld"],["array",{"groups":["array",[["string","get-product"]]],"operation_type":["string","item"],"item_operation_name":["string","get"],"resource_class":["string","App\\Entity\\User"],"input":["null",null],"output":["null",null],"request_uri":["string","\/api\/products\/1"],"uri":["string","http:\/\/localhost:8000\/api\/products\/1"],"enable_max_depth":["boolean",true],"resources":["object","ApiPlatform\\Core\\Serializer\\ResourceList"],"resources_to_push":["object","ApiPlatform\\Core\\Serializer\\ResourceList"],"api_sub_level":["boolean",true],"iri":["string","\/api\/products\/1"],"api_normalize":["boolean",true],"jsonld_has_context":["boolean",true],"cache_key":["string","fd9d00f432020e76fe4b7c40c36e02a8"],"circular_reference_limit_counters":["array",{"000000002eec221f000000004c3c8bbb":["integer",1]}],"api_attribute":["string","customPrice"]}]]},{"namespace":"ApiPlatform\\Core\\Serializer","short_class":"AbstractItemNormalizer","class":"ApiPlatform\\Core\\Serializer\\AbstractItemNormalizer","type":"-\u003E","function":"getAttributeValue","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\symfony\\serializer\\Normalizer\\AbstractObjectNormalizer.php","line":181,"args":[["object","App\\Entity\\Product"],["string","customPrice"],["string","jsonld"],["array",{"groups":["array",[["string","get-product"]]],"operation_type":["string","item"],"item_operation_name":["string","get"],"resource_class":["string","App\\Entity\\Product"],"input":["null",null],"output":["null",null],"request_uri":["string","\/api\/products\/1"],"uri":["string","http:\/\/localhost:8000\/api\/products\/1"],"enable_max_depth":["boolean",true],"resources":["object","ApiPlatform\\Core\\Serializer\\ResourceList"],"resources_to_push":["object","ApiPlatform\\Core\\Serializer\\ResourceList"],"api_sub_level":["boolean",true],"iri":["string","\/api\/products\/1"],"api_normalize":["boolean",true],"jsonld_has_context":["boolean",true],"cache_key":["string","b0593009b8b99136d5dc735276dd77e8"],"circular_reference_limit_counters":["array",{"000000002eec221f000000004c3c8bbb":["integer",1]}],"api_attribute":["string","customPrice"]}]]},{"namespace":"Symfony\\Component\\Serializer\\Normalizer","short_class":"AbstractObjectNormalizer","class":"Symfony\\Component\\Serializer\\Normalizer\\AbstractObjectNormalizer","type":"-\u003E","function":"normalize","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\api-platform\\core\\src\\Serializer\\AbstractItemNormalizer.php","line":151,"args":[["object","App\\Entity\\Product"],["string","jsonld"],["array",{"groups":["array",[["string","get-product"]]],"operation_type":["string","item"],"item_operation_name":["string","get"],"resource_class":["string","App\\Entity\\Product"],"input":["null",null],"output":["null",null],"request_uri":["string","\/api\/products\/1"],"uri":["string","http:\/\/localhost:8000\/api\/products\/1"],"enable_max_depth":["boolean",true],"resources":["object","ApiPlatform\\Core\\Serializer\\ResourceList"],"resources_to_push":["object","ApiPlatform\\Core\\Serializer\\ResourceList"],"api_sub_level":["boolean",true],"iri":["string","\/api\/products\/1"],"api_normalize":["boolean",true],"jsonld_has_context":["boolean",true],"cache_key":["string","b0593009b8b99136d5dc735276dd77e8"],"circular_reference_limit_counters":["array",{"000000002eec221f000000004c3c8bbb":["integer",1]}]}]]},{"namespace":"ApiPlatform\\Core\\Serializer","short_class":"AbstractItemNormalizer","class":"ApiPlatform\\Core\\Serializer\\AbstractItemNormalizer","type":"-\u003E","function":"normalize","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\api-platform\\core\\src\\JsonLd\\Serializer\\ItemNormalizer.php","line":80,"args":[["object","App\\Entity\\Product"],["string","jsonld"],["array",{"groups":["array",[["string","get-product"]]],"operation_type":["string","item"],"item_operation_name":["string","get"],"resource_class":["string","App\\Entity\\Product"],"input":["null",null],"output":["null",null],"request_uri":["string","\/api\/products\/1"],"uri":["string","http:\/\/localhost:8000\/api\/products\/1"],"enable_max_depth":["boolean",true],"resources":["object","ApiPlatform\\Core\\Serializer\\ResourceList"],"resources_to_push":["object","ApiPlatform\\Core\\Serializer\\ResourceList"],"api_sub_level":["boolean",true],"iri":["string","\/api\/products\/1"],"api_normalize":["boolean",true],"jsonld_has_context":["boolean",true]}]]},{"namespace":"ApiPlatform\\Core\\JsonLd\\Serializer","short_class":"ItemNormalizer","class":"ApiPlatform\\Core\\JsonLd\\Serializer\\ItemNormalizer","type":"-\u003E","function":"normalize","file":"D:\\Temp\\Perso\\myref_api-master\\src\\Serializer\\ProductNormalizer.php","line":46,"args":[["object","App\\Entity\\Product"],["string","jsonld"],["array",{"groups":["array",[["string","get-product"]]],"operation_type":["string","item"],"item_operation_name":["string","get"],"resource_class":["string","App\\Entity\\Product"],"input":["null",null],"output":["null",null],"request_uri":["string","\/api\/products\/1"],"uri":["string","http:\/\/localhost:8000\/api\/products\/1"],"enable_max_depth":["boolean",true],"resources":["object","ApiPlatform\\Core\\Serializer\\ResourceList"],"resources_to_push":["object","ApiPlatform\\Core\\Serializer\\ResourceList"],"api_sub_level":["boolean",true],"iri":["string","\/api\/products\/1"],"api_normalize":["boolean",true],"jsonld_has_context":["boolean",true]}]]},{"namespace":"App\\Serializer","short_class":"ProductNormalizer","class":"App\\Serializer\\ProductNormalizer","type":"-\u003E","function":"normalize","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\symfony\\serializer\\Serializer.php","line":152,"args":[["object","App\\Entity\\Product"],["string","jsonld"],["array",{"groups":["array",[["string","get-product"]]],"operation_type":["string","item"],"item_operation_name":["string","get"],"resource_class":["string","App\\Entity\\Product"],"input":["null",null],"output":["null",null],"request_uri":["string","\/api\/products\/1"],"uri":["string","http:\/\/localhost:8000\/api\/products\/1"],"enable_max_depth":["boolean",true],"resources":["object","ApiPlatform\\Core\\Serializer\\ResourceList"],"resources_to_push":["object","ApiPlatform\\Core\\Serializer\\ResourceList"]}]]},{"namespace":"Symfony\\Component\\Serializer","short_class":"Serializer","class":"Symfony\\Component\\Serializer\\Serializer","type":"-\u003E","function":"normalize","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\symfony\\serializer\\Serializer.php","line":125,"args":[["object","App\\Entity\\Product"],["string","jsonld"],["array",{"groups":["array",[["string","get-product"]]],"operation_type":["string","item"],"item_operation_name":["string","get"],"resource_class":["string","App\\Entity\\Product"],"input":["null",null],"output":["null",null],"request_uri":["string","\/api\/products\/1"],"uri":["string","http:\/\/localhost:8000\/api\/products\/1"],"enable_max_depth":["boolean",true],"resources":["object","ApiPlatform\\Core\\Serializer\\ResourceList"],"resources_to_push":["object","ApiPlatform\\Core\\Serializer\\ResourceList"]}]]},{"namespace":"Symfony\\Component\\Serializer","short_class":"Serializer","class":"Symfony\\Component\\Serializer\\Serializer","type":"-\u003E","function":"serialize","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\api-platform\\core\\src\\EventListener\\SerializeListener.php","line":92,"args":[["object","App\\Entity\\Product"],["string","jsonld"],["array",{"groups":["array",[["string","get-product"]]],"operation_type":["string","item"],"item_operation_name":["string","get"],"resource_class":["string","App\\Entity\\Product"],"input":["null",null],"output":["null",null],"request_uri":["string","\/api\/products\/1"],"uri":["string","http:\/\/localhost:8000\/api\/products\/1"],"enable_max_depth":["boolean",true],"resources":["object","ApiPlatform\\Core\\Serializer\\ResourceList"],"resources_to_push":["object","ApiPlatform\\Core\\Serializer\\ResourceList"]}]]},{"namespace":"ApiPlatform\\Core\\EventListener","short_class":"SerializeListener","class":"ApiPlatform\\Core\\EventListener\\SerializeListener","type":"-\u003E","function":"onKernelView","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\symfony\\event-dispatcher\\Debug\\WrappedListener.php","line":126,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\ViewEvent"],["string","kernel.view"],["object","Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"]]},{"namespace":"Symfony\\Component\\EventDispatcher\\Debug","short_class":"WrappedListener","class":"Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener","type":"-\u003E","function":"__invoke","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\symfony\\event-dispatcher\\EventDispatcher.php","line":258,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\ViewEvent"],["string","kernel.view"],["object","Symfony\\Component\\HttpKernel\\Debug\\TraceableEventDispatcher"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"-\u003E","function":"doDispatch","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\symfony\\event-dispatcher\\EventDispatcher.php","line":233,"args":[["array",[["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"]]],["string","kernel.view"],["object","Symfony\\Component\\HttpKernel\\Event\\ViewEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"-\u003E","function":"callListeners","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\symfony\\event-dispatcher\\EventDispatcher.php","line":73,"args":[["array",[["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"],["object","Symfony\\Component\\EventDispatcher\\Debug\\WrappedListener"]]],["string","kernel.view"],["object","Symfony\\Component\\HttpKernel\\Event\\ViewEvent"]]},{"namespace":"Symfony\\Component\\EventDispatcher","short_class":"EventDispatcher","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"-\u003E","function":"dispatch","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\symfony\\event-dispatcher\\Debug\\TraceableEventDispatcher.php","line":168,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\ViewEvent"],["string","kernel.view"]]},{"namespace":"Symfony\\Component\\EventDispatcher\\Debug","short_class":"TraceableEventDispatcher","class":"Symfony\\Component\\EventDispatcher\\Debug\\TraceableEventDispatcher","type":"-\u003E","function":"dispatch","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\symfony\\http-kernel\\HttpKernel.php","line":156,"args":[["object","Symfony\\Component\\HttpKernel\\Event\\ViewEvent"],["string","kernel.view"]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E","function":"handleRaw","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\symfony\\http-kernel\\HttpKernel.php","line":68,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"HttpKernel","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E","function":"handle","file":"D:\\Temp\\Perso\\myref_api-master\\vendor\\symfony\\http-kernel\\Kernel.php","line":198,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"],["integer",1],["boolean",true]]},{"namespace":"Symfony\\Component\\HttpKernel","short_class":"Kernel","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"-\u003E","function":"handle","file":"D:\\Temp\\Perso\\myref_api-master\\public\\index.php","line":25,"args":[["object","Symfony\\Component\\HttpFoundation\\Request"]]}]}

When I tried to troubleshoot by myself, I supposed that the problem occured when the normalize method is called just after the setCustomPrice was called.
It seems there is a problem with the normalization/serialization of the Product object just after the custom price field was set, the float type being the type of the custom price...

**Comment by teohhanhui** [comment]
First of all, how you name your serializer groups does not matter.

I see you pass a `User` to `setCustomPrice`, that's unexpected. You should name your method differently if it's not a setter. :smile:

**Comment by malejulien013** [comment]
You're right, my mistake, getUserCustomPrice should be a more suitable name.

I customized  most of my serializer groups name with no problem, and I have no problem with my other Normalizer.

But this normalizer is different than others, it overrides an object attribute (the customPrice field) when other ones just customize the context group.
And it seems that in this specific case, changing the name of the serializer group matters, but I don't understand why...
