### ISSUE TITLE
[Best Practices] Events & EventHandlers for CRUD Operations?

### ISSUE THREAD

**Issue by ljbergmann** [api-platform/api-platform#622]
I've recently discovered this beautiful project and started using it for a new project. In the context of the new project i encountered a "problem". 

I have an user entity, if a new User is created i want to create other entities that depend on the new user. After a bit of reading in the docs i came across the event system and thought this could be a good method to trigger the creation of the depending entities.

My problem is, how do i subscribe a listener to the creation of a new User ? Do i have to create a event listener that is subscribed to kernel.view and then check every triggered event if it was a User? 
If this is the case it sounds very inefficient.

Best regards
ljbergmann

**Comment by dunglas** [comment]
Thanks for the kind words :)

Yes, and it's very efficient (almost costless as far as your return early when there is nothing to do). Symfony itself uses this method for its built-in listeners.

Some handy constants are defined to ease the process: https://api-platform.com/docs/core/events/

**Comment by ljbergmann** [comment]
Hey @dunglas thanks for the very fast reply and the clarification.

As far as I'm concerned, this issue can be closed and marked as solve.
