### ISSUE TITLE
How to create custom GraphQL Endpoints?

### ISSUE THREAD

**Issue by christoph-hautzinger** [api-platform/api-platform#626]
Hallo,

I implemented a nearby search for locations which is no problem over a custom rest endpoint:

    /**
     * @ORM\Entity
     * @ApiResource(collectionOperations={
     *     "get",
     *     "post",
     *     "special"={
     *         "method"="get",
     *         "path"="/locations/by-distance/{latitude}/{longitude}/{distance}",
     *         "controller"=LocationByDistance::class,
     *         "swagger_context"={
     *             "parameters"={
     *                 {"name"="latitude",  "type"="string", "required"=true, "in"="path"},
     *                 {"name"="longitude", "type"="string", "required"=true, "in"="path"},
     *                 {"name"="distance",  "type"="string", "required"=true, "in"="path"}
     *             }
     *         }
     *     }
     * })
     */
    class Location
    {
        /**
         * @ORM\Id
         * @ORM\Column(type="integer")
         * @ORM\GeneratedValue(strategy="AUTO")
         *
         * @var integer|null
         */
        private $id;
        
        /**
         * @ORM\Column(type="decimal", nullable=true, precision=10, scale=7)
         *
         * @var float|null
         */
        private $mapLongitude;
        
        /**
         * @ORM\Column(type="decimal", nullable=true, precision=10, scale=7)
         *
         * @var float|null
         */
        private $mapLatitude;
        
        /**
         * @ORM\Column(type="integer", nullable=true, options={"default":15})
         *
         * @var integer|null
         */
        private $mapDefaultZoom;
    }

the "special" action is handled in this way:

        <?php
        
        namespace App\Action;
        
        use App\Repository\LocationRepository;
        use Symfony\Component\HttpFoundation\RequestStack;
        
        class LocationByDistance
        {
            /**
             * @var LocationRepository
             */
            private $repository;
        
            /**
             * @var RequestStack
             */
            private $requestStack;
        
            /**
             * LocationByDistance constructor.
             *
             * @param LocationRepository $repository
             * @param RequestStack       $requestStack
             */
            public function __construct(LocationRepository $repository, RequestStack $requestStack)
            {
                $this->repository = $repository;
                $this->requestStack = $requestStack;
            }
        
            /**
             * @return iterable
             */
            public function __invoke()
            {
                return $this
                    ->repository
                    ->findAroundPointWithDistance(
                        (float) $this->getParameter('latitude'),
                        (float) $this->getParameter('longitude'),
                        (int)   $this->getParameter('distance', 10)
                    );
            }
        
            /**
             * @param string $name
             * @param null   $default
             *
             * @return string
             */
            protected function getParameter(string $name, $default = null): string
            {
                return $this->requestStack->getMasterRequest()->attributes->get($name, $default);
            }
        }
 
 my problem is, that this behavior is not supported via graphql. Am I wrong in solving this problem or is this a bug? Thanks for your reply

**Comment by michilehr** [comment]
Any updates on this?

**Comment by devhero-tech** [comment]
i have the same problem :/

**Comment by aokby** [comment]
Any updates on this?

**Comment by alanpoulain** [comment]
Custom queries will be available soon in master.

**Comment by danaki** [comment]
Any updates please?

**Comment by alanpoulain** [comment]
It's available in master but no documentation yet (I'm adding more possibilities before doing the documentation).

**Comment by danaki** [comment]
Yes, trying to get along with this https://github.com/api-platform/core/pull/2447

**Comment by alanpoulain** [comment]
Documentation about custom queries/mutations can be found here: https://api-platform.com/docs/master/core/graphql/
