### ISSUE TITLE
Logs dir name change in sf4

### ISSUE THREAD

**Issue by silverbackdan** [api-platform/api-platform#628]
In Symfony 4 the directory `/var/logs` was changed to `/var/log`

Would the simplest way to accommodate this in the docker configs be to create both directories?

https://github.com/api-platform/api-platform/blob/master/api/Dockerfile#L57
https://github.com/api-platform/api-platform/blob/master/api/docker/php/docker-entrypoint.sh#L10

**Comment by purplefish32** [comment]
I second that, /var/logs should now be /var/log

**Comment by dunglas** [comment]
Would you mind opening a PR?

**Comment by dunglas** [comment]
Closed by #630.
