### ISSUE TITLE
Update the package

### ISSUE THREAD

**Issue by vinset** [api-platform/api-platform#63]
I'm a bit confused. I have installed api-platform via composer with the command "composer create-project api-platform/api-platform my-api".

Now I want to update to version 1.1 of the core via composer.

Can you explane me how?

**Comment by teohhanhui** [comment]
Change in composer.json:

```json
    "require": {
        ...
        "dunglas/api-bundle": "~1.1@beta",
        ...
    }
```

and then run `composer update`

**Comment by Simperfit** [comment]
@vinset you can try now with the V2  :)
