### ISSUE TITLE
[suggestion] use `npm ci` instead of `yarn install`

### ISSUE THREAD

**Issue by karser** [api-platform/api-platform#631]
There are 2 reasons:
- yarn produces node_modules folder 1.5 times bigger comparing to npm one
- `npm ci` (install from lock file) works 3 times faster than npm/yarn install

![image](https://user-images.githubusercontent.com/1675033/38276297-36ce2f8a-379d-11e8-9e3c-d950cb6ac6aa.png)

**Comment by Simperfit** [comment]
@karser do you want to make a PR to test this ?

**Comment by soyuka** [comment]
I think most of the team is in favor of keeping react. Anyway I'm +1 on using default provided tools like `npm`.

**Comment by soyuka** [comment]
I think most of the team is in favor of keeping react. Anyway I'm +1 on using default provided tools like `npm`.

**Comment by Simperfit** [comment]
Thanks @karser for the benchmark! I'm closing here as I don't think we should inscrease the node_module folder for that amount of time
