### ISSUE TITLE
Incoherent Varnish backend host

### ISSUE THREAD

**Issue by yokoloko** [api-platform/api-platform#636]
I downloaded the api platform project.

Then started it with `docker-compose up` but it appears the varnish cache is not used when accessing localhost:8081 as specified in the client.

Either, the client `Welcome.js` should be updated with the correct url `api:8081` or the `default.vcl` should declare a 

```
backend default {
  .host = "localhost";
  .port = "80";
}
```

**Comment by dunglas** [comment]
It's intended, in dev mode, you probably want to not use the cache (because it's a pain to debug), in prod, you'll use a static website hosting for the client, not the Docker dev container.

**Comment by JeremieBAP** [comment]
If you don't want to use the cache in dev why won't you just use the 8080 port?
But ok for the answer, why not.

Thanks a lot for your nice and useful project :)

**Comment by teohhanhui** [comment]
> in dev mode, you probably want to not use the cache (because it's a pain to debug)

But then you don't really know if your caching proxy is working as intended, especially that the invalidation logic might miss something. And then it'd come to bite you in production... :smile:
