### ISSUE TITLE
Defining api filter properties in yaml

### ISSUE THREAD

**Issue by jcerri** [api-platform/api-platform#638]
In the documentation, there is an example about how to define api filter properties using annotation :
`@ApiFilter(SearchFilter::class, properties={"id": "exact", "price": "exact", "name": "partial"})`

Is it possible to do the same using yaml ? I'm trying to define which entity fields the filter can be applied on.

For example, I have a custom SearchFilter (i'm not using doctrine) and a Video entity. I only want my filter to be applied on name and body properties.

**Comment by soyuka** [comment]
Yes, there is an example for this:

https://api-platform.com/docs/core/filters#basic-knowledge

Also, the filter annotation only declares the service for you, it's therefore not related to doctrine :)

**Comment by jcerri** [comment]
I saw that example but it seems i’m forced to declare my filter and to inject a list of properties. 
Using the annotation, I can set a filter and a list of properties for an entity. The FilterPass does the rest. I can apply my SearchFilter on property name of entity A and the same filter on property title of entity B. 
Using yaml, out of the box, I have the feeling I have to declare my filter as a service twice. 

I may be missing something. 
I only got specific about Doctrine to precise everything is custom in my project (data providers, extensions and filters management) althought it will be heavily inspired.

**Comment by soyuka** [comment]
You got that right and yes you'd have to declare one service per filter (which is what the anootation does)

**Comment by yivi** [comment]
Would be really nice if a less verbose method existed to define this via YAML.

Defining a service per property gets old quickly. I like having most of my configuration centralized in YAML files vs annotations, but for filters it gets really cumbersome.

One can dream on 3.0 I guess. :)

**Comment by yivi** [comment]
Because if I understand correctly, this annotation would need to be converted into 4 different service definitions, right?

```
/**
*  @ApiFilter(SearchFilter::class, properties={"id": "exact", "score": "exact", "leadId": "exact", "reviewerName":"partial" })
*/
```

**Comment by antograssiot** [comment]
One is enough... see https://github.com/api-platform/core/blob/df7087816254085741820cd1513aeb5fdaaf13a1/tests/Fixtures/app/config/config_orm.yml#L5 @yivi
