### ISSUE TITLE
Explain errors when request is not valid

### ISSUE THREAD

**Issue by samusenkoiv** [api-platform/api-platform#64]
I ran into this time, for example I'm trying to create new entity sending POST request and  put invalid json (or forgot put the json at all), then I got not really informative response

> {
>   "@context": "\/api\/contexts\/Error",
>   "@type": "Error",
>   "hydra:title": "An error occurred",
>   "hydra:description": "Syntax error",
>   "trace": [
>     {
>       "function": "cpostAction",
>       "class": "Dunglas\ApiBundle\Controller\ResourceController",
>       "type": "-\u003E",
>       "args": [
>         {
>           "attributes": {},
>           "request": {},
>           "query": {},
>           "server": {},
>           "files": {},
>           "cookies": {},
>           "headers": {}
>         }
>       ]
>     },
>     {
>       "file": "\/var\/www\/v3\/app\/bootstrap.php.cache",
>       "line": 3210,
>       "function": "call_user_func_array",
>       "args": [
>         [
>           {},
>           "cpostAction"
>         ],
>         [
>           {
>             "attributes": {},
>             "request": {},
>             "query": {},
>             "server": {},
>             "files": {},
>             "cookies": {},
>             "headers": {}
>           }
>         ]
>       ]
>     },

It would be great to get message which explains me that the json is invalid.

**Comment by Simperfit** [comment]
Errors are now better. But anyway you should be careful of the input
