### ISSUE TITLE
how to handle multy/form-data?

### ISSUE THREAD

**Issue by videni** [api-platform/api-platform#642]

**Comment by soyuka** [comment]
Really? Typo in the title, no description? No attempt at trying something? 

A quick research: https://github.com/api-platform/core/issues/1242

Good luck.

**Comment by teohhanhui** [comment]
@soyuka Let's not be so mean... :sweat_smile:

**Comment by videni** [comment]
@teohhanhui, no problem,  I end up using symfony form without serialization. this can be closed.
