### ISSUE TITLE
Symfony Flex expects `.env.dist` to be present

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/api-platform#643]
The way we use the `.env` (`api/.env`) file to serve double purpose - Docker Compose and Symfony - prevents Symfony Flex from configuring the environment variables from recipes.

See https://github.com/symfony/flex/blob/51d7ddce85ca8b73a1fc16771f607b7d56692dbd/src/Configurator/EnvConfigurator.php#L35-L40

Thanks @Darkweak for discovering this issue.

**Comment by Simperfit** [comment]
Adding `.env.dist` will fix this bug right or should we remove completely .env too and ask users to move it manually?

**Comment by teohhanhui** [comment]
It's tricky, because we want to support `docker-compose up` out of the box. If only Docker Compose supports a `.dist` fallback... 😂😂

**Comment by teohhanhui** [comment]
Yeah, the easiest solution for now is to add `.env.dist` which is just a copy of `.env`.

**Comment by dunglas** [comment]
or a symlink

**Comment by teohhanhui** [comment]
Let's not open that can of worms... :rofl:
