### ISSUE TITLE
Debug Final query

### ISSUE THREAD

**Issue by anacicconi** [api-platform/api-platform#647]
Hello,

I've been testing the different filters available on api platform. In order to be sure if the generated query matches what I'm trying to do I was debugging the $queryBuilder in each filter file. Ex:

ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter

```
if (1 === \count($values)) {
                $this->addWhereByStrategy($strategy, $queryBuilder, $queryNameGenerator, $alias, $field, $values[0], $caseSensitive);
                //var_dump($queryBuilder->getDQL());
                return;
            }
```

However, I think I can have the final query if I debug the Filter Extension file:

ApiPlatform\Core\Bridge\Doctrine\Orm\Extension\FilterExtension

```
foreach ($resourceFilters as $filterId) {
            if (!($filter = $this->getFilter($filterId)) instanceof FilterInterface) {
                continue;
            }

            $context['filters'] = $context['filters'] ?? [];

            $filter->apply($queryBuilder, $queryNameGenerator, $resourceClass, $operationName, $context);
        }

var_dump($queryBuilder->getDQL());exit;
```

Is this the right place to get the final query that will be implemented by Doctrine? If not, could you please point me in the right direction?

Thanks!

**Comment by Simperfit** [comment]
To get the final query you need to debug in `FilterExtension` because when using multiple filters it will add the dql to the querybuilder ;).

**Comment by anacicconi** [comment]
Thanks @Simperfit. It was the right place ;)
