### ISSUE TITLE
Limitations of the table mapping model...

### ISSUE THREAD

**Issue by AbsSimon** [api-platform/api-platform#650]
Hello,

I am new to api plattform.

I have an old Symfony 2.8 Api (FosRestBundle) and would
like to replace it. I cant change much.

Calls for example

	POST /login
	- session_id
	- user (bycrypt)
	- password (bycrypt)
	- Client Browser and IP (to avoid session highjacking)

	POST {session_id}/price
	- product_id
	- user_id
	- country 
	(prices depends on user group and country, and here
	are also calls to the erp system)

So how to realize this with api platform?

I have a user table, so the call might be POST: user/login
and with custom controllers an can realise the logic.

But, I do not have a price table. (prices comes from erp system)
Do I have to write an dummy entity to write my route? And have the
a useless object in my custom controller? 

How usefull is the api plattform concept when plain database 
request are the exception? Is an entity the right place to 
define any api route?

Thank you & Best Regard
Simon

**Comment by gries** [comment]
Hi,
Have a look at custom data providers https://api-platform.com/docs/core/data-providers/
You can define an entity which is not mapped via doctrine and write a DataProvider that aggregates it from the ERP System.

**Comment by AbsSimon** [comment]
Hallo gries,

thank you very much.
 
Maybe it would be helpfull for many new users, if there is an advanced showcase-project (simular to symfony-demo). The current demo is so tiny ... and reading the full manual needs a lot time ;)

Best Regards
Simon
