### ISSUE TITLE
Doc Not complet

### ISSUE THREAD

**Issue by paoloBirdOffice** [api-platform/api-platform#651]
Hi there is missing element on the doc https://api-platform.com/docs/core/data-providers#injecting-extensions-pagination-filter-eagerloading-etc
We miss the end of the BlogItemDataProvider for filter injection
Thanks

**Comment by soyuka** [comment]
indeed, in the mean time you can have a look at https://github.com/api-platform/core/blob/master/src/Bridge/Doctrine/Orm/ItemDataProvider.php#L95

**Comment by paoloBirdOffice** [comment]
Actually where i got the probleme is with the declaration of the Service with the !tagged in Symfony4.
I have the feeling that he doesn't see reconnize it and give me empty itemExtension

**Comment by alanpoulain** [comment]
This is just an example and it needs to be adapted.
