### ISSUE TITLE
API over complex DQL

### ISSUE THREAD

**Issue by mi5ha** [api-platform/api-platform#652]
Hi there,

I have a lot of complex DQL that I want to turn into API endpoints (read only).
I managed to create extension to alter the QB, and custom normalizer to alter returned data fields.

But how do I turn off default ID ordering? I want ordering to be determined by altered QB.

And if I try to give ordering field name it complains it doesn't exist on entity. And it does not, its determined by DQL not entity structure.

Thank you!

**Comment by mi5ha** [comment]
thanks for answering, but I am not sure I understand you :-) Are there some examples, docs of the feature you are recommending?

I thought that extension approach will be simpler then to create custom data provider.

Example of custom data provider given in docs doesnt have paging, filtering part. Just says its possible.

**Comment by soyuka** [comment]
I see, try this: https://api-platform.com/docs/core/default-order/

**Comment by teohhanhui** [comment]
You can use `order=null`
