### ISSUE TITLE
[question] Add new subresource

### ISSUE THREAD

**Issue by nikophil** [api-platform/api-platform#655]
Hello,
i'm really new to ApiPlatform, and i'm wondering what's the url i should call to add a subessource to a resource.
Let's say i have blog post and comments and i want to add a comment to a blog post.
Which POST url should i call ? and how should i reference the bog post id ?

thank you for your answer

**Comment by gries** [comment]
Hi,
this is currently not supported have a look at: https://github.com/api-platform/api-platform/issues/571
But as far as I know there is currently work being done to support this.

**Comment by nikophil** [comment]
Hi, thanks for your answer
maybe i was not clear enough : i just want to add a comment object to the OneToMany relationship...
I can't find the right POST url 
I was on another issue in github that i should do like this :
POST /api/comments
{
    "content" : "blah blah",
    "blogPost" : "/api/blogpost/1"
}
with an application/ld+json header but that just doesn't work...

**Comment by BatsaxIV** [comment]
If you want to directly POST on comment, something like :

```json
{
  "content": "new comment",  
  "blogPost": "/blogPosts/$ID"
}
```
should work.

**Comment by nikophil** [comment]
okay, thanks, that works

**Comment by smilesrg** [comment]
@dunglas @soyuka sorry, but why this important thing is not added to the documentation?
