### ISSUE TITLE
Create a new element with an associated id without providing it [POST Operation]

### ISSUE THREAD

**Issue by LukA888** [api-platform/api-platform#656]
Hi, 

first of all, thank you for this awesome project! 

I've read that you can retrieve all the entity related to one user using:
A) Filter: https://api-platform.com/docs/core/filters#using-doctrine-filters
B) Custom extensions: https://api-platform.com/docs/core/extensions#example

As the title points, I want to create a new Entity without sending the associated id of the subresource. I'm using JSON format. For example, I have the entity Dog with the following properties: id, name and user(ManyToOne).

If I make a POST request to /api/dogs with the body:
```
{
  "name": "Dog",
  "user": 12
}
```
I receive a 201 response code. 

My question is, can I only send this body:
```
{
  "name": "Dog"
}
```
and the user_id value is set automatically with the id from logged in user?

The option A) (Filters) is based upon an article posted on [Michaël Perrin's blog](http://blog.michaelperrin.fr/2014/12/05/doctrine-filters/) and I found the same question:

![question](https://user-images.githubusercontent.com/18327422/38999685-a701b8ec-43f2-11e8-99f1-2ac907b03fbe.png)

Thank you!

**Comment by soyuka** [comment]
Inject the Token in your data persister or in a pre-write listener to alter the data.

**Comment by LukA888** [comment]
It worked like a charm! Thanks 😄

**Comment by hpatoio** [comment]
@LukA888 would you share the relevant code ?
