### ISSUE TITLE
Install API platform whitout docker

### ISSUE THREAD

**Issue by alberto-leon-crespo** [api-platform/api-platform#657]
I need install API Platform without docker. Reading documentation first i try to install symfony:

# Create a new Symfony Flex project
$ composer create-project symfony/skeleton api
# Enter the project folder
$ cd api
# Install the API Platform's server component in this skeleton
$ composer req api

I put "DATABASE_URL=mysql://root:645058001@127.0.0.1:3306/root" in my .env file and execute commands:

$ bin/console doctrine:database:create
$ bin/console doctrine:schema:create

When i go to "http://localhost" i can see symfony welcome page but api platform wellcome page is not here.

When i try to undestand project structure and documentation i see incoherences and missing files:

YAML:
# api/config/api_platform/resources.yaml not in the project tree
resources:
    App\Entity\Product: ~
    App\Entity\Offer:
        shortName: 'Offer'                   # optional
        description: 'An offer from my shop' # optional
        iri: 'http://schema.org/Offer'       # optional
        attributes:                          # optional
            pagination_items_per_page: 25    # optional

Anything can explain me how i can setup a basic api platform project and structure?

**Comment by teohhanhui** [comment]
You're confusing api-platform/core with api-platform/api-platform. You could clone api-platform/api-platform and customize it to your needs. :smile:

**Comment by Simperfit** [comment]
This seems to be out of context. @teohhanhui told you how to create a basic api-platform project :).

**Comment by dunglas** [comment]
The API Platform docs will be at `http://localhost/api` when installing through Flex. Maybe the docs need to be updated accordingly.

**Comment by jpprade** [comment]
Yes I had the same issue, I spend 2 hours trying to figure out why I keept seeing the symfony welcome page, it was just under /api. Yes please update the docs here : https://api-platform.com/docs/distribution

**Comment by dunglas** [comment]
@jpprade would you mind opening a doc PR? Please mention that the API is registered under /api only if you use the Flex recipe. When using the standard distribution it is registered at the root.
