### ISSUE TITLE
How to: DELETE multiple records

### ISSUE THREAD

**Issue by khom-outsourcify** [api-platform/api-platform#659]
Sorry my English is limited, I use Symfony with API platform and Vue.JS for frontend.
Do you have a way to delete multiple records with only 1 query ? Now I only fond how to delete 1 record. 

Thanks.

**Comment by soyuka** [comment]
That's not supported. There are some discussion open on batch endpoint though: https://github.com/api-platform/core/pull/1645

**Comment by khom-outsourcify** [comment]
@soyuka Thanks for your advice. :D

**Comment by EstebanRacine** [comment]
Heyy, I have the same issue. Has it been resolved with the latest versions or not?
