### ISSUE TITLE
Default filtering like default ordering 

### ISSUE THREAD

**Issue by emir** [api-platform/api-platform#662]
Hello, 

Like [default ordering](https://api-platform.com/docs/core/default-order) I need something like /api/books always returned with `WHERE status = 1`. Status field is not optional. Is there any easy way to achieve this?

**Comment by Simperfit** [comment]
Hello @emir thanks for using API-Platform,

You need to use a Custom [DoctrineExtension](https://api-platform.com/docs/core/extensions/#custom-extension) to do this.

I'm closing here, if you still needs anything feel free to re-open.

**Comment by kirya-dev** [comment]
So simplest task resolved so huge class ? its the best decision

**Comment by lebadapetru** [comment]
@Simperfit , is that the only way? It looks way too much for such a simply task....

**Comment by J3m5** [comment]
I agree with @lebadapetru , this would be a nice feature.

**Comment by cb1986ster** [comment]
:+1:

**Comment by felixgeissler** [comment]
It's a real bummer, that API Platform doesn't support this feature atm. 😕

**Comment by alzee** [comment]
You can write an API yourself, something like `/api/filteredbooks`, it's kind of one minute work in symfony.

**Comment by Disput** [comment]
> Using API-Platform, you can still write your own APIs, a route like `/api/filteredbooks` will do the job. It's kind of one minute work in symfony.

How does that help? How do you easily apply default filters to that new filteredbooks API ?
