### ISSUE TITLE
don't show stack trace when in product environment  when throw an exception

### ISSUE THREAD

**Issue by videni** [api-platform/api-platform#668]
the  `ApiPlatform\Core\Action\ExceptionAction` doesn't care about the environment,  it will show stack trace when an exception happened. I think we should hide this info.

**Comment by meyerbaptiste** [comment]
Is the value of `kernel.debug` `true` in your production env?

**Comment by videni** [comment]
@meyerbaptiste , yep,  now I replace ExceptionAction service my custom one which will hide stack trace if the environment is prod
