### ISSUE TITLE
Swagger generation does not output yaml

### ISSUE THREAD

**Issue by danielclariondoor** [api-platform/api-platform#670]
`docker-compose exec php bin/console api:swagger:export --yaml` results in 
" The "--yaml" option does not exist." althought the documentation plainly states this as the way to get yyaml output.

**Comment by dunglas** [comment]
Docs updated. Thanks for reporting, and @antograssiot for fixing it!

**Comment by danielclariondoor** [comment]
But I need that feature. Any idea when this will be merged?

**Comment by antograssiot** [comment]
You can already use the master branch...

**Comment by danielclariondoor** [comment]
Thanks
