### ISSUE TITLE
Demo Application  (like symfony-demo) ?

### ISSUE THREAD

**Issue by AskanSimon** [api-platform/api-platform#671]
Hello,

I think for the Api Platform project, it would be very
helpful if there is a more advanced demo application.

So people can see
- Okay (with the Entity and Event System) is it possible
  to build good projects.
- Many people like to learn with a complete and
  running application.
- It will also help to define a best practices. 
  (use events instead of custom controllers, use groups 
  to use joints, use jwt authentication instead 
  of fosres, use annotations ... etc.) A better
  orientation.

Is there something planned in the future? 

Best Regards
Simon

**Comment by sylflo** [comment]
That would be really awesome, I am working on a big project with API Platform and even tough the documentation is pretty good (but outdated sometimes) having a fully complete example would be pretty awesome and useful.

**Comment by soyuka** [comment]
https://github.com/api-platform/demo/

**Comment by AbsSimon** [comment]
@sylflo the api platform demo is a hello world example. symfony demo is pretty advanced with many techniques ;)

**Comment by teohhanhui** [comment]
It's not just a hello world.

**Comment by sylflo** [comment]
It's not an hello world but it's pretty basic. I plan to do a complete example (users management, access_control, annotations...) in a few weeks.

**Comment by slavo2** [comment]
I think it would be nice, if there would be a working example which would not be mixing DB models (ORM) with API Resources, but using DataProviders ( https://api-platform.com/docs/core/data-providers/ )
Complete working example with relations, authentication... 
Preferably under MIT license. :)
Is your example somewhere available, @sylflo ?

**Comment by alanpoulain** [comment]
Demo has been improved recently with custom data providers.
