### ISSUE TITLE
Security per class property for graphql

### ISSUE THREAD

**Issue by amouhzi** [api-platform/api-platform#674]
Hello,

This is my entity:

```php
/**
 * @ApiResource(
 *   attributes={
 *     "access_control"="is_granted('ROLE_USER')",
 *     "normalization_context"={"groups"={"read"}},
 *     "denormalization_context"={"groups"={"write"}}
 *   }
 * )
 * ...
 */
class MyEntity
{
    /**
     * @var string
     *
     * @Groups({"super_partner"})
     */
    private $superPartner;

    /**
     * @var string
     *
     * @Groups({"partner"})
     */
    private $partner;
}
```
With ContextBuilder I can dynamicly inject a Serialization Group as explained here: https://api-platform.com/docs/core/serialization.

Each partner should only get data that concern him.

I didn't find how to do for graphql. The ContextBuilder is never called when using graphql queries.

**Comment by Siregacvek** [comment]
@amouhzi as far as I understand changing serialization context on-the-fly is meaningless for graphql, because you get only requested fields. Even if you change context during executing of your query, you will receive only requested data, passed in a query explicitly.

**Comment by amouhzi** [comment]
@Siregacvek What I want is to avoid giving a data to a user who is not allowed to have it just because he asked for it via the request. I want to delete it in the results before sending them.

The serializer will be used to filter the fields the user has requested and then execute the query. Or send to the user an error that tells him that he has requested non-existing / unauthorized fields.

**Comment by Siregacvek** [comment]
As you noticed ContextBuilder doesn't work for graphql. But you can register your own serializer and filter data there
https://api-platform.com/docs/core/serialization#changing-the-serialization-context-on-a-per-item-basis

**Comment by amouhzi** [comment]
@Siregacvek I did it, but the ContextBuilder was never used when using GraphQl. Maybe now the situation is changed. I didn't check because we abandoned graphql just for this case and switched to json-ld.

**Comment by alanpoulain** [comment]
You can now use the `SerializerContextBuilder` as in REST in master:
https://api-platform.com/docs/master/core/graphql/#changing-the-serialization-context-dynamically
