### ISSUE TITLE
React Client - Router and Redux-router dependencies mismatch

### ISSUE THREAD

**Issue by kayneth** [api-platform/api-platform#675]
Hi ! 

I started to work on the client side of my project using this repository configuration. 
I saw in `package.json` that you use 
```
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^4.0.8",
```
But on the github repository of `react-router-redux` they say that you need v5 to work with `react-router`  v4. 
I tried and `const history = syncHistoryWithStore(createBrowserHistory(), store);` is not working on this repository due to this mismatch on dependencies. 

Did you manage to make it work ? 

It's not critical for my project because i don't need it and i changed my package.json dependencies. I only wanted to know if you were aware of this. :)

**Comment by dunglas** [comment]
Hi,

Thanks for reporting. Would you mind opening a PR changing the `package.json`?
