### ISSUE TITLE
api 

### ISSUE THREAD

**Issue by padydgan** [api-platform/api-platform#676]
Hello
We have about 10 sites. Each of these sites has its own database.
We created a subdomain that is shared between 10 sites.
Now we want to be logged in to 9 other sites when logged in to our system, even when logged into one of the sites.

Our project has been implemented with Symfony.

The sample site that is similar to the project is the envato.com website.

How can we make this link between sites? Please provide guidance and explain the solutions available for this.

**Comment by dunglas** [comment]
Closing as not an issue. Support requests must be done on StackOverflow or Slack.
