### ISSUE TITLE
CONTAINER_REGISTRY_BASE in docker-compose.yml

### ISSUE THREAD

**Issue by samkooker** [api-platform/api-platform#677]
Hi.
What does the variable "CONTAINER_REGISTRY_BASE" in the docker-compose.yml file mean?

**Comment by dunglas** [comment]
It allows to use quay.io instead of DockerHub to retrieve pre-built images. The env var allows to change easily the registry.

**Comment by samkooker** [comment]
I don't know quay.io.
Please how to set this variable et what is the default value ?

**Comment by dunglas** [comment]
Can you explain the error you get? It's a simple environment variable. It's default value is set here: https://github.com/api-platform/api-platform/blob/master/.env

You can change it by setting like this: https://docs.docker.com/compose/environment-variables/

**Comment by samkooker** [comment]
Excuse me. I made a bad copy of the files. The .env file was not in my directory.
Thank you for your help.
