### ISSUE TITLE
UUID strategy can't generate ids in postgresql

### ISSUE THREAD

**Issue by GonzaloRodriguezBlanco** [api-platform/api-platform#679]
If we change the Greeting entity id to uuid, the post request fails with the following error description:

```
An exception occurred while executing 'SELECT UUID_GENERATE_V4()':

SQLSTATE[42883]: Undefined function: 7 ERROR:  function uuid_generate_v4() does not exist
LINE 1: SELECT UUID_GENERATE_V4()
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
```

It looks like the uuid-ossp postgresql extension which contains uuid_generate_v4() function is not loaded. I didn't find any documentation in api_platform about that.

The entity has been changed to:
```
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * This is a dummy entity. Remove it!
 *
 * @ApiResource
 * @ORM\Entity
 */
class Greeting
{
    /**
     * @var string The entity Id
     *
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column(type="string")
     */
    private $id;

    /**
     * @var string A nice person
     *
     * @ORM\Column
     * @Assert\NotBlank
     */
    public $name = '';

    public function getId(): string
    {
        return $this->id;
    }
}
```
Here is a commit with the changed entity:
[https://github.com/GonzaloRodriguezBlanco/api-platform/commit/f533e7015dc7446322422cbcecb1d6a8665a675b](https://github.com/GonzaloRodriguezBlanco/api-platform/commit/f533e7015dc7446322422cbcecb1d6a8665a675b)

Steps to reproduce:

1. Clone fork [https://github.com/GonzaloRodriguezBlanco/api-platform.git](https://github.com/GonzaloRodriguezBlanco/api-platform.git)
2. Checkout uuid_strategy branch
3. Start services: docker-compose up -d
4. Do POST request
```
curl -X POST "http://localhost:8080/greetings" -H "accept: application/ld+json" -H "Content-Type: application/ld+json" -d "{ \"name\": \"World\"}"
```

**Comment by GonzaloRodriguezBlanco** [comment]
Hi @dunglas, thanks for your response. I have changed the doctrine type but that does not fix the error:

[https://github.com/GonzaloRodriguezBlanco/api-platform/commit/7f57429b6f67bcaca38c0fdac54ff465643bcca8](https://github.com/GonzaloRodriguezBlanco/api-platform/commit/7f57429b6f67bcaca38c0fdac54ff465643bcca8)

**Comment by dunglas** [comment]
You also need to enable UUID support for Postgres: https://stackoverflow.com/a/22446521/1352334

**Comment by GonzaloRodriguezBlanco** [comment]
@dunglas for this to work I have to connect to the database with a db client and execute
```
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
```

Shouldn't we have this "out-of-the-box" in api-platform?
I did a change in the docker-entrypoint.sh for this. You can check it in [https://github.com/GonzaloRodriguezBlanco/api-platform/commit/965db428f4428cbe5d167c83e23a9b7fdca66ed9](https://github.com/GonzaloRodriguezBlanco/api-platform/commit/965db428f4428cbe5d167c83e23a9b7fdca66ed9)

Now it works. Thanks.

**Comment by dunglas** [comment]
@GonzaloRodriguezBlanco why not adding it as a comment (not everybody needs UUID support).
@teohhanhui if the ID isn't provided by the client, it's better (faster and more secure because lower level) to delegate to the RDBMS right?

**Comment by GonzaloRodriguezBlanco** [comment]
@teohhanhui I agree with @dunglas about to delegate the ID creation  to the RDBMS.

@dunglas Adding it as a comment could be a way to not "annoy" anybody that does not need UUID. But I think that a comment is a little hidden for those who use UUID. What do you think about a environment variable configuration to enable/disable it with a default disable value?

In .env.dist file:
```
ENABLE_UUID_POSTGRES=false
```

Check UUID explicitly enabled and Postgres as RDBMS. In docker-entrypoint.sh:
```bash
#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

if [ "$1" = 'php-fpm' ] || [ "$1" = 'bin/console' ]; then
	mkdir -p var/cache var/log var/sessions

    if [ "$APP_ENV" != 'prod' ]; then
		composer install --prefer-dist --no-progress --no-suggest --no-interaction
		bin/console doctrine:schema:update --force --no-interaction

                if [ "$ENABLE_UUID_POSTGRES" = 'true'  ] && [ -z "${DATABASE_URL##*"pgsql"*}" ]; then
                    bin/console doctrine:query:sql 'CREATE EXTENSION IF NOT EXISTS "uuid-ossp";'
                fi
	fi

	# Permissions hack because setfacl does not work on Mac and Windows
	chown -R www-data var
fi

exec docker-php-entrypoint "$@"
```

Check the commit: [https://github.com/GonzaloRodriguezBlanco/api-platform/commit/e94868de7fee17adc1a7055694a4ffa9af719c67](https://github.com/GonzaloRodriguezBlanco/api-platform/commit/e94868de7fee17adc1a7055694a4ffa9af719c67)

**Comment by teohhanhui** [comment]
@dunglas:
> if the ID isn't provided by the client, it's better (faster and more secure because lower level) to delegate to the RDBMS right?

I disagree. There are advantages to having the ID generated by the app. If it's generated by the RDBMS, you cannot know the ID before it's committed to the database. Anyway, we don't know if that's faster and more secure (definitely not more secure just because it's lower level).

**Comment by teohhanhui** [comment]
@GonzaloRodriguezBlanco There is no reason to execute that from the php container. You should do it in the postgres container instead: https://github.com/docker-library/docs/tree/master/postgres#how-to-extend-this-image :smile:

**Comment by GonzaloRodriguezBlanco** [comment]
@teohhanhui You are right. Following your references finally I came up with this solution:

[https://github.com/GonzaloRodriguezBlanco/api-platform/commit/94a6873e7950e6ddaee1df911341e6cc5dfe7941](https://github.com/GonzaloRodriguezBlanco/api-platform/commit/94a6873e7950e6ddaee1df911341e6cc5dfe7941)

**Comment by dunglas** [comment]
pgcrypto is written in C. In the cryptography field, using a low level language makes it easier to make the implementation as detrrministic and side-effect free. Unlike in C, it’s not possible to inline ASM code in PHP, and it is very hard (almost impossible actually) to write deterministic implementations.
Crypto or random number generation related algos are almost always faster (and better) when wrote “close to the metal” (and it’s even better it it’s delegated to the hardware directly).

I don’t know how is implemented Ramsey’s UUID. I bet it delegates sensitive computations to a C extension for this exact same reason. But in this field, the less abstractions layers the better (and pgcrypto is close of the metal).

Using pgcrypto also ensure that all inserted UUID are of the same quality, generated by a same algo. It you delegate to the client (several clients can connect to the same DB), you loose this guarantee.

You use case is valid, but specific. In this case ok to use something like Ramsey, but it’s not a very common one in my experience. (Generating a UUID client-side, in JS or in a native webapp is more common on my experience).

**Comment by teohhanhui** [comment]
https://github.com/ramsey/uuid/blob/master/src/Generator/RandomBytesGenerator.php

It should be safe in PHP 7+
