### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by Aurelyn10** [api-platform/api-platform#683]
I am new for this platform.
According to sing the Official Distribution (recommended), I downloaded zip file from here:

> https://github.com/api-platform/api-platform/releases/tag/v2.2.6

And  in the folder of "api-platform-2.2.6", typed this:

> $ docker-compose up -d # Running in detached mode

But it shows error, I installed docker and running now, its version is  18.03.0-ce-mac60 (23751)

> workstation1:api-platform-2.2.6 admin$ docker-compose up -d # Running in detached mode
> Building php
> Step 1/22 : ARG PHP_VERSION=7.2
> Step 2/22 : ARG ALPINE_VERSION=3.7
> Step 3/22 : FROM php:${PHP_VERSION}-fpm-alpine${ALPINE_VERSION}
>  ---> d2d7e49f2235
> Step 4/22 : RUN apk add --no-cache 		git
>  ---> Running in 20380127f201
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
> fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
> WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz: IO ERROR
> WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz: IO ERROR
> ERROR: unsatisfiable constraints:
>   git (missing):
>     required by: world[git]
> ERROR: Service 'php' failed to build: The command '/bin/sh -c apk add --no-cache 		git' returned a non-zero code: 1
>

**Comment by Aurelyn10** [comment]
Ok thank you 
It was from my network setting.

**Comment by teohhanhui** [comment]
Can we add a note so that nobody downloads the .zip file? Or is it possible to hide the .zip file in the release but show the .tar.gz instead?

**Comment by dunglas** [comment]
What's the problem with the ZIP?

**Comment by teohhanhui** [comment]
We've seen several issues opened here before because of wrong file permissions. It doesn't always happen, but the chances of the .zip file restoring the correct metadata is lower than that of using the .tar.gz.

https://superuser.com/a/173995/379322
