### ISSUE TITLE
The schema generator doesn't run using docker

### ISSUE THREAD

**Issue by danielclariondoor** [api-platform/api-platform#684]
Running  "docker-compose exec php vendor/bin/schema" as mentioned in the documentation results in 
```
Warning: require_once(/srv/api/vendor/bin/../vendor/autoload.php): failed to open stream: No such file or directory in /srv/api/vendor/bin/schema on line 15

Fatal error: require_once(): Failed opening required '/srv/api/vendor/bin/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /srv/api/vendor/bin/schema on line 15
```

**Comment by teohhanhui** [comment]
Moved to https://github.com/api-platform/schema-generator/issues/129

**Comment by teohhanhui** [comment]
Sorry, I wasn't thinking straight. This issue you had is due to the composer install not being complete yet...

**Comment by teohhanhui** [comment]
As pointed out by @theofidry at https://github.com/api-platform/schema-generator/issues/129#issuecomment-391052240, this was caused by a composer install that was not yet complete.

After you do `docker-compose up -d`, you need to check the logs with `docker-compose logs php -f` to see when it's done before proceeding.

**Comment by danielclariondoor** [comment]
This is happening after composer is fully installed.
The path should be "../autoload.php"

**Comment by theofidry** [comment]
`/srv/api/vendor/bin/../vendor/autoload.php` should indeed be `/srv/api/vendor/bin/../autoload.php`

**Comment by danielclariondoor** [comment]
I just cloned this repo and then ran "docker-compose up".

**Comment by teohhanhui** [comment]
Unable to reproduce the problem...

**Comment by danielclariondoor** [comment]
According to the docs, https://api-platform.com/docs/schema-generator/getting-started
the generator is run like this: 
`docker-compose exec php vendor/bin/schema`
so __DIR__ is not 'vendor/api-platform/schema-generator/bin'

**Comment by teohhanhui** [comment]
Please read what I've mentioned above about the symlink. :smile:

And `__DIR__` also resolves symlinks.

**Comment by danielclariondoor** [comment]
Thanks. I did read that. What I'm trying to point is that there is an error in the documentation.
The documentation says to run `docker-compose exec php vendor/bin/schema` which for me results in the error.
`docker-compose exec php vendor/api-platform/schema-generator/bin/schema` does work, but that is not in the documentation.

**Comment by teohhanhui** [comment]
`vendor/bin/schema` should be a symlink to `vendor/api-platform/schema-generator/bin/schema`. Is that not the case for you?
