### ISSUE TITLE
The schema generator puts the files in the wrong folder

### ISSUE THREAD

**Issue by danielclariondoor** [api-platform/api-platform#685]
Running "vendor/bin/schema generate-types api/src/ api/config/schema.yaml"
The files are placed into src/AppBundle/Entity/ with a namespace to match, instead of in src/Entity, which is where services.yaml expects to find them. This causes a fatal error in the api frontend:
```
(2/2) FileLoaderLoadException
Expected to find class "App\AppBundle\Entity\PostalAddress" in file "/srv/api/src/AppBundle/Entity/PostalAddress.php" while importing services from resource "../src/*", but it was not found! Check the namespace prefix used with the resource in /srv/api/config/services.yaml (which is loaded in resource "/srv/api/config/services.yaml").
```

**Comment by meyerbaptiste** [comment]
Moved to api-platform/schema-generator#128.
