### ISSUE TITLE
ApiPlatform 2.0: How to change default routes name?

### ISSUE THREAD

**Issue by nobady90** [api-platform/api-platform#687]
Hello,
I wanted to know if there is a way to change the name of the routes generated automatically with the name of the entity. (eg updated the @ApiResource annotation)
example:
```
/ **
* Class Pippo
*
* @ApiResource (
* "RENAME PATH" = "pluto"
*)
* /
Pippo class
{[....]
```

so that all automatically generated routes take the name Pluto instead of the original one of the entity (in this case Pippo).

I tried to look for something but I should always specify for each action (GET, SET, POST etc. ..) the new path, it becomes less demanding at that point to change the name of the entity.

thank you!

**Comment by Maels1991** [comment]
What you're looking for is the "shortName" property defineable on the` ApiResource()` annotation.

`@ApiResource(shortName="what you want ...")`

**Comment by nobady90** [comment]
thanks so much, it works!
I had not noticed this annotation in the documentation :-D
good day!

**Comment by Bizkaitarra** [comment]
I want to diference tagname and shortname.
In spanish I have some resources that like accion that the plural form is accciones.
If the shortname is set to accione Api Plataform turns resource into acciones, wich is ok, but the tag name is also Accione.
Is not something that affects the API, only documentation.

I tried with tag and tagName and doesn't work

**Comment by mrtnzagustin** [comment]
Same problem as @Bizkaitarra . Maybe @Maels1991 can help us ->
is there a way to change just the shortname and not the endpoint?
My example: i have a class named "Accion". By default api-platform create:

"@context": "/api/contexts/Accion"
"@id": "/api/accions"
If i change shortName to "Acciones" (spanish) i get:

"@context": "/api/contexts/Acciones"
"@id": "/api/acciones"
What i want (just change the endpoint):

"@context": "/api/contexts/Accion"
"@id": "/api/acciones"
Is there another property to do that?
is there a apiresource options doc reference?

**Comment by mrtnzagustin** [comment]
Quick fix. Please let me know if there is a way to change the endpoint prefix globally for al item and collection operations. Regards.

```php
/**
 * Accion
 * @ORM\Table(name="portal_accion", indexes={@ORM\Index(name="fk_estado_actual", columns={"id_estado_actual"}), @ORM\Index(name="fk_estado_siguiente", columns={"id_estado_siguiente"})})
 * @ORM\Entity
 * @ApiResource(
 *      normalizationContext={"groups"={"getCollectionAccion"}},
 *      collectionOperations={
 *          "get"={
 * 				"path"="acciones"
 * 			}
 *      },
 *      itemOperations={
 *          "get"={
 * 				"path"="acciones/{id}"
 * 			}
 *      }
 * )
 * @ApiFilter(SearchFilter::class , properties={"tipoTramite.id":"exact","estadoActual.id":"exact"})
 * @ApiFilter(AccionUserFilter::class , properties={"null"})
 */
class Accion
{
```

**Comment by ahmed-bhs** [comment]
Does there any way to change the name of the resource without affecting the path name. I need a global conf ?:
```
resources:
    App\Entity\Repos\WorkPlace:
        shortName: environment de travail
        path: workplace
```

**Comment by nathansalter** [comment]
You can override the name of the resource and then explicitly set the path names:

```
 * @ApiResource(
 *     shortName="foo_bar",
 *     collectionOperations={},
 *     itemOperations={
 *         "put"={
 *             "path"="/never/mind/{id}"
 *         },
 *         "get"={
 *             "path"="/never/mind/{id}"
 *         },
 *     },
 * )
```
