### ISSUE TITLE
Errors in running docker-compose

### ISSUE THREAD

**Issue by micheldumontier** [api-platform/api-platform#689]
I get the following errors using docker on windows:

c:\code\api-platform-2.2.6>docker-compose up -d
api-platform-226_db_1 is up-to-date
Starting api-platform-226_admin_1  ... error
Starting api-platform-226_client_1 ...
Starting api-platform-226_php_1    ...

Starting api-platform-226_client_1 ... error
e/api-platform-2.2.6/admin': mkdir /host_mnt/c/code: file exists

ERROR: for api-platform-226_client_1  Cannot start service client: error while creating mount source path '/host_mnt/c/cStarting api-platform-226_php_1    ... error

ERROR: for api-platform-226_php_1  Cannot start service php: error while creating mount source path '/host_mnt/c/code/api-platform-2.2.6/api': mkdir /host_mnt/c/code: file exists

ERROR: for admin  Cannot start service admin: error while creating mount source path '/host_mnt/c/code/api-platform-2.2.6/admin': mkdir /host_mnt/c/code: file exists

ERROR: for client  Cannot start service client: error while creating mount source path '/host_mnt/c/code/api-platform-2.2.6/client': mkdir /host_mnt/c/code: file exists

ERROR: for php  Cannot start service php: error while creating mount source path '/host_mnt/c/code/api-platform-2.2.6/api': mkdir /host_mnt/c/code: file exists
ERROR: Encountered errors while bringing up the project.

**Comment by teohhanhui** [comment]
Maybe related: https://github.com/docker/for-win/issues/1560

**Comment by micheldumontier** [comment]
with docker for windows, i easily provide credentials for docker to access the shared drive. but something else is happening... i wonder if it is related to paths in docker-compose.yml

**Comment by micheldumontier** [comment]
ok. it was because i had the api-platform directory in a symbolic link directory. feel free to close this!
