### ISSUE TITLE
How can I add some fields to exposed recourse ? 

### ISSUE THREAD

**Issue by samusenkoiv** [api-platform/api-platform#69]
Hi everyone, 
We have User resource. 
We also have tables ("custom_attributes" and "user_custom_attributes"). In "custom_attributes" we declare fields, and in "user_custom_attributes" we have attr_id, user_id, value.
The "custom_attributes" is always different and I think it is too complicated to treat those user custom user attributes as separate recourse (because in fact they are not separate entities, it is just a way to make it flexible).

So what I want to is send such json:

> {
>    "first_name": "Ihor",
>    "email" : "someemail@gmail.com"
>    "custom_attributes" : {
>        "age" : 26,
>        "another_key" : "another_value" 
>    }
> }

And another way around, when somebody is trying to make GET request, the result should be in the same way.

I guess I need to implement custom Normalizer. 
I would really appreciate any tips. Thank you.

**Comment by teohhanhui** [comment]
Are you sure you need such flexibility of arbitrary key-value pairs, or is it just lazy modelling? That said, if you're sticking with this, you can simply use the `json_array` Doctrine type.

**Comment by samusenkoiv** [comment]
Yes, I would do it with json_array, but unfortunately I'm building API on top of existed database.

**Comment by teohhanhui** [comment]
In which case, yes, I think the solution would be a custom normalizer for the User class...

**Comment by Simperfit** [comment]
@samusenkoiv Did you follow's @teohhanhui comments ?
