### ISSUE TITLE
ManyToMany references

### ISSUE THREAD

**Issue by dridi93** [api-platform/api-platform#691]
Hi,
I have a problem with POST manytomany relation,

### Provider entity
`
/**
     * @var Service
     *
     * @Groups({"provider", "user"})
     *
     * @Assert\Valid
     *
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Service", inversedBy="providers")
     * @ORM\JoinTable(name="providers_services")
     * @MaxDepth(1)
     */
    private $services;
`
### Service entity
`
/**
     * @var Provider
     *
     * @ORM\ManyToMany(targetEntity="AppBundle\Entity\Provider", mappedBy="services")
     */
    private $providers;
`

and this is my object 

`
{
  "type": "string",
  "logo": "string",
  "estimatedCost": "string",
  "businessName": "string",
  "phone": "string",
  "contactName": "string",
  "contactMobile": "string",
  "commercialRegistry": "string",
  "services": ["/services/1"]
}
`

The problem is when submiting the form i need to set references of the service passed in services array.

**Comment by Maels1991** [comment]
That depends on which is the owning/inverse side.
If relation is "inverted", then you have to set reference to the other in your adder method.
