### ISSUE TITLE
Specify ORM Column type gives error on SubResources

### ISSUE THREAD

**Issue by SundownDEV** [api-platform/api-platform#693]
This code

~~~php
/**
     * @ORM\Column(type="json_array", nullable=true)
     * @ORM\OneToMany(targetEntity="Response", mappedBy="question", cascade={"persist", "remove"})
     * @ApiSubresource()
     */
    private $responses;
~~~

gives this error : 
~~~
FatalThrowableError
Call to a member function getClassName() on null
~~~

But it works without the column type : 
~~~php
/** @ORM\Column(type="json_array", nullable=true) */
~~~

**Comment by soyuka** [comment]
I've never seen a relation column that could have a `json_array` type, is this really a thing?

**Comment by SundownDEV** [comment]
@soyuka it does exist but seems deprecated. So I tried with `json` but it gives me this error : 
~~~
Call to a member function isCollection() on null
~~~

So I don't know what to use instead.

**Comment by soyuka** [comment]
Yes because this is a relation column it should be left as-is (ie the column will have the id of the relation, type is already defined by the relation id).

**Comment by SundownDEV** [comment]
Alright, thank you. But how can I set it nullable ? or set a default value ?

**Comment by soyuka** [comment]
I didn't got that. What are you trying to do?

**Comment by SundownDEV** [comment]
For example column response define the parent response that get the user to a question. If there is not parent question I have to set it to null, right ?

**Comment by soyuka** [comment]
A `OneToMany` relation doesn't have a `Column` annotation AFAIR... You should read doctrine docs: https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/association-mapping.html#one-to-many-bidirectional. 
Nullable can be set on the `JoinColumn(nullable=true)` annotation.

**Comment by SundownDEV** [comment]
Alright, thanks for replying! Closing since it's invalid.
