### ISSUE TITLE
Working with different DTO

### ISSUE THREAD

**Issue by akorz** [api-platform/api-platform#694]
Hello,

My project is using CQRS architecture and almost all operations are built with DTO. 

So, for example, for creating User I have CreateUserDTO with small set of properties from User entity and with some extra properties. As a result of queuing of users I have a array of PublicUserDTO again with some fields from User entity without some private data.

So is there a way how to use API Platform in that case? Thanks.

**Comment by teohhanhui** [comment]
I don't think we have that kind of flexibility yet, out of the box. But personally it's something that's been bothering me a lot... I think a lot of times having one model for every step of the process just results in too many compromises.

**Comment by akorz** [comment]
Thank you for reply. Do you know any good alternatives for building REST API with Simfony?

**Comment by teohhanhui** [comment]
I think it should still be possible for you to use API Platform. You just (maybe) need to unregister some of the default listeners and use your own. No need to start from scratch!

**Comment by teohhanhui** [comment]
Maybe https://github.com/api-platform/core/issues/1747#issuecomment-391241134 would be helpful too.

**Comment by teohhanhui** [comment]
Uhh... There are actually some docs on using DTOs: https://api-platform.com/docs/core/dto

**Comment by akorz** [comment]
Thanks. I'm checking you links right now. Btw. I found I good blog post https://stefanoalletti.wordpress.com/2018/03/07/symfony-api-platform-cqrs-part-1/

**Comment by soyuka** [comment]
With api-platform 2.4 we know support DTO's and coupled to the messenger you can implement a CQRS architecture! Closing this, feel free to ping me if you have questions.
