### ISSUE TITLE
No resource found for object of type one to many relation

### ISSUE THREAD

**Issue by hatimox** [api-platform/api-platform#70]
hydra:description: "No resource found for object of type "AppBundle\Document\article"",
i have two mongo db documents user and article and each user has multiple articles so i'm trying to list all the users with all their articles titles so i can get something like this :

{
@id: "/user/53edb6200cf2400d584c2617",
@type: "user",
class: "de.freelancer.mongo.domain.User",
email: "feer@de.com",
displayname: "feer",
withnewsletter: false,
language: "de_DE",
active: true,
admin: false,
**articles : ['article1','article2','article3']**
}

here is my code :

**user Document **

`<?php
namespace AppBundle\Document;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;
use Dunglas\ApiBundle\Annotation\Iri;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * @MongoDB\Document
 * @MongoDB\Document(collection="user")
 */
class User
{
    /**
     * @MongoDB\Id(strategy="AUTO")
     */
    private $id;

    /**
     * @MongoDB\ReferenceMany(targetDocument="articles", mappedBy="user") 
     */
    private $articles;

    public function __construct()
    {
        $this->articles = new ArrayCollection();
    }

    /**
     */
    public function getArticles()
    {
        return $this->articles;
    }
}`

**articles document : **

`<?php

namespace AppBundle\Document;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ODM\MongoDB\Mapping\Annotations as MongoDB;
use Dunglas\ApiBundle\Annotation\Iri;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @MongoDB\Document
 * @MongoDB\Document(collection="article")
 */
class article
{
    /**
     * @MongoDB\Id(strategy="AUTO")
     */
    private $id;

   
    /**
     * @MongoDB\ReferenceOne(targetDocument="user", inversedBy="articles")
     */
    private $user;

    /**
     * 
     */
    public function setUser(userProfile $user)
    {
        $this->user = $user;
        return $this;
    }

    /**
     * 
     */
    public function getUser()
    {
         return $this->user;
    }

}
`
can any one help me to get the list of the user articles 

thanks

**Comment by kmehmety** [comment]
+1

**Comment by dunglas** [comment]
MongoDB isn't supported yet but there is a PR open to add it: api-platform/core#461.
Tests and review on this PR are very welcome!
