### ISSUE TITLE
OAI-PMH Standard Support?

### ISSUE THREAD

**Issue by jlayt** [api-platform/api-platform#706]
We're scoping a project for a client (a major museum) to replace their collections database with a new API backend and web frontend, and we're looking to use API Platform especially for the JSON-LD API to feed out to the wider academic and museum LOD community. One requirement though is to continue to provide their existing OAI-PMH API without breakage and we're wondering about extending API Platform to provide this too.

OAI-PMH (https://www.openarchives.org/pmh/) is an old but widely used API standard in the museum and archive sector. It's fairly simple, a single stable URL using query parameters and results returned in XML with Dublin Core metadata, so not too much effort, but I'm not sure how well this maps to API Platform's RESTful / Content Negotiation model. Would this be a sensible course for us to take, and if we do would this be a welcome contribution to the upstream codebase, or best kept downstream?

For comparison, here are some existing OAI-PMH bundles, it might be quicker to use one but I'd prefer all my APIs in one basket to simplify future support requirements!

https://github.com/subugoe/OaiBundle
https://github.com/naoned/OaiPmhServerBundle
https://github.com/picturae/OaiPmh
https://github.com/fccn/oai-pmh-core

Many thanks!

**Comment by teohhanhui** [comment]
I think it should be in another project, as it's not a general-use format. Maybe we could list community extensions in the docs... :)

**Comment by dunglas** [comment]
Hi, I agree with @teohhanhui, it should be in an external bundle, not in core. However we'll be happy to merge low level changes in core that enable the possibility to create such bundles.

**Comment by Simperfit** [comment]
@jlayt I think we all agree that could be in a external bundle, It should not be that hard to achieve, we can add it in the documentation, do you plan on doing something like this ?

(for exemple the Pomm project supports api-platform with a bundle).
