### ISSUE TITLE
The filter class "PropertyFilter" does not implement "ApiPlatform\Core\Api\FilterInterface".

### ISSUE THREAD

**Issue by JensvdHeydt** [api-platform/api-platform#708]
When decorating my entity class with a Propertyfilter like this one

> @ApiFilter(PropertyFilter::class, arguments={"parameterName": "properties", "overrideDefaultProperties": true, "whitelist": {"allowed_property"}})

whenever I'm clear then cache or call the api I'm getting the error message 

> The filter class "PropertyFilter" does not implement "ApiPlatform\Core\Api\FilterInterface".

Using other filters like "@ApiFilter(SearchFilter::class, properties={"id": "exact", "title": "partial"})" works. The class PropertyFilter does implement the FilterInterface so I'm not exactly sure what I'm doing wrong. I'm using v2.2.6 of api-platform.

**Comment by JensvdHeydt** [comment]
My bad:

> use ApiPlatform\Core\Serializer\Filter\PropertyFilter;

solved my issue.

**Comment by mrtnzagustin** [comment]
> My bad:
> 
> > use ApiPlatform\Core\Serializer\Filter\PropertyFilter;
> 
> solved my issue.

where did you add that line and why? is that in api platform docs?
