### ISSUE TITLE
[Question] Subresources and access control

### ISSUE THREAD

**Issue by nikophil** [api-platform/api-platform#709]
Hello,

i'm wondering how i can access to the "parent" object of a subresource in the voter ?

thanks

**Comment by Maels1991** [comment]
Hello,

Not sure to understand your question but I guess this can be achieved through a two-way relationship between your entities so that you can access A from B and B from A.

`access_control="is_granted('my_action', object)"`

**Comment by Maels1991** [comment]
Hello,

Not sure to understand your question but I guess this can be merely achieved through the relationship between your entities so that you can access A from B, or B from A, or both in case you have a two-way relationship.


`access_control="is_granted('my_action', object)"`

**Comment by Maels1991** [comment]
Hello @nikophil ,

I'm facing the same issue. Not found any "good" solution yet but to reach my goal, I retrieve the parent ID from the request and load it using Doctrine.

I keep you informed if I found any other better way to achieve it 😃

**Comment by alexsegura** [comment]
I don't know if this is a "better" way, but you can play with the event system.

The code is borrowed from [DenyAccessListener](https://github.com/api-platform/core/blob/6c15002da5c2ca0e79d1fd20213051ff217b007f/src/Security/EventListener/DenyAccessListener.php)

In this example, I have restaurants, and orders. Orders are subresources of a restaurant. 
The route `/api/restaurants/{id}/orders` is able to check if the restaurant is owned by the authenticated user. 
This is using `ItemDataProviderInterface` instead of the EntityManager itself. 

```php
<?php

namespace AppBundle\Api\EventSubscriber;

use AppBundle\Entity\Restaurant;
use ApiPlatform\Core\DataProvider\ItemDataProviderInterface;
use ApiPlatform\Core\EventListener\EventPriorities;
use ApiPlatform\Core\Security\ResourceAccessCheckerInterface;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\GetResponseEvent;
use Symfony\Component\HttpKernel\KernelEvents;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

final class RestaurantSubscriber implements EventSubscriberInterface
{
    private $itemDataProvider;
    private $resourceAccessChecker;

    public function __construct(
        ItemDataProviderInterface $itemDataProvider,
        ResourceAccessCheckerInterface $resourceAccessChecker)
    {
        $this->itemDataProvider = $itemDataProvider;
        $this->resourceAccessChecker = $resourceAccessChecker;
    }

    public static function getSubscribedEvents()
    {
        return [
            KernelEvents::REQUEST => ['accessControl', EventPriorities::PRE_READ],
        ];
    }

    public function accessControl(GetResponseEvent $event)
    {
        $request = $event->getRequest();

        if ('api_restaurants_orders_get_subresource' !== $request->attributes->get('_route')) {
            return;
        }

        $id = $request->attributes->get('id');

        $restaurant = $this->itemDataProvider->getItem(Restaurant::class, $id, 'get');

        $extraVariables = [];
        $extraVariables['object'] = $restaurant;
        $extraVariables['request'] = $request;

        $isGranted = "is_granted('ROLE_RESTAURANT') and user.ownsRestaurant(object)";

        if (!$this->resourceAccessChecker->isGranted(Restaurant::class, $isGranted, $extraVariables)) {
            throw new AccessDeniedException('Access Denied.');
        }
    }
}

```

**Comment by soyuka** [comment]
https://github.com/api-platform/api-platform/issues/748 looks relevant here

**Comment by tomsykes** [comment]
There's actually enough within the context of the annotation expression to pass to a voter and get the parent entity...

```php
/*     subresourceOperations={
 *          "api_questions_answers_get_subresource"= {
 *              "security"="is_granted('GET_SUB_RESOURCE', _api_normalization_context['subresource_resources'])",
 *          },
 *     }
 */
class Answer
```

I then have a generic sub-resource voter, but you could create one per parent resource easily...

```php
class SubresourceVoter extends Voter
{
    /** @var EntityManagerInterface */
    protected $manager;

    public function __construct(EntityManagerInterface $manager)
    {
        $this->manager = $manager;
    }

    protected function supports($attribute, $subject)
    {
        if (($attribute !== 'GET_SUB_RESOURCE') || !is_array($subject)) return false;

        [$className, $id] = $this->getClassAndId($subject);
        return (class_exists($className));
    }

    protected function voteOnAttribute($attribute, $subject, TokenInterface $token)
    {
        [$className, $id] = $this->getClassAndId($subject);
        $entity = $this->manager->getRepository($className)->find($id);

        return // some logic;
    }

    protected function getClassAndId($subject) {
        $className = array_keys($subject)[0];
        $id = $subject[$className]['id'] ?? null;
        return [$className, $id];
    }
}
```

Final note - if you want to know what else is available in the context of the security expression, just put something random in there like "badger". It'll throw an exception, and somewhere in the stack trace (`Symfony\Component\ExpressionLanguage\ExpressionLanguage->evaluate`) is a list of all the variables, and their values.

**Comment by soyuka** [comment]
Closing this, might be useful to specify this in the documentation though!
