### ISSUE TITLE
Accessing a property through a hasser

### ISSUE THREAD

**Issue by BatsaxIV** [api-platform/api-platform#710]
Hi, 

It seems that a property that has to be accessed through a hasser is not output on a GET request.

With API Platform 2.2.6 and the standard installation, add a new field to the _Greeting_ class and make it accessible through a **hasXXX** method  :

```php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * This is a dummy entity. Remove it!
 *
 * @ApiResource()
 * @ORM\Entity
 */
class Greeting
{
    /**
     * @var int The entity Id
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string A nice person
     *
     * @ORM\Column
     * @Assert\NotBlank
     */
    public $name = '';

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $arrived;

    public function getId(): int
    {
        return $this->id;
    }

    public function hasArrived()
    {
        return $this->arrived;
    }
}
```  
GET Output is the following : 
![image](https://user-images.githubusercontent.com/1379286/40924597-f6a88968-6817-11e8-82d0-b38ac0f15bcc.png)

With a **getXXX** or **isXXX** method, it's working.

**Comment by BatsaxIV** [comment]
After a bit of searching, it seems that the _problem_ comes from the `Symfony\Component\PropertyInfo\Extractor\ReflectionExtractor`, **has** is not part of the `$defaultAccessorPrefixes`.

```php
class ReflectionExtractor implements PropertyListExtractorInterface, PropertyTypeExtractorInterface, PropertyAccessExtractorInterface
{
    /**
     * @internal
     */
    public static $defaultMutatorPrefixes = array('add', 'remove', 'set');

    /**
     * @internal
     */
    public static $defaultAccessorPrefixes = array('is', 'can', 'get');
```

It seems a bit odd to me that this class **has** (:sunglasses:) a problem, is there a bug or am I missing something? (ping @dunglas)

**Comment by dunglas** [comment]
Support has been added in Symfony 4.1.

**Comment by soyuka** [comment]
For the mean time I guess that you have to override the class in your stack! 

Thanks for the report @BatsaxIV, closing this as fixed I guess :p.

**Comment by BatsaxIV** [comment]
Yes, I was about to close it :)  
For anyone interesting, here's the commit in the property-info component : https://github.com/symfony/property-info/commit/bb50d9f132d91633e8b7c912795d9ed81a902377

Thanks for the answer @dunglas !
