### ISSUE TITLE
[Question] Mandatory server-side filters and resource collection aliases

### ISSUE THREAD

**Issue by dvc** [api-platform/api-platform#712]
Hello everybody! Here some cases confused for me...

1. I want to have mandatory server-side only configured filters (not just for security reason). For example:

```
client: [GET] /some_resource_items/?some_field=123
server-side modified to: [GET] /some_resource_items/?some_field=123&status[]='active'&status[]='draft'
```

2. I want to have custom collections routes as alias to common resource with filters:

```
[GET] /some_resource_items/some_custom_collection
is alias to:
[GET] /some_resource_items/?some_field=123
```

3. I want to have custom parametrized collections routes as alias to common resource with search exact filter:

```
route path: [GET] /some_resource_items/{some_field}/some_custom_collection/{some_other_field}

[GET] /some_resource_items/123/some_custom_collection/qwerty
is alias to:
[GET] /some_resource_items/?some_field=123&some_other_field=qwerty
```

May be it is an option {"in": "path"} for search filter.

4. I want to customize (de)normalization context in all above cases. So, it could be a custom operations. 

**It is similar to subresources, but more intuitive to me. And more powerfull too, IMHO.**

The best way is configuration, but i need simplest workaround for now.

I think about forward request. But, what about normalization context?

Or may be just use replace|edit the Request object on 'kernel.request' event?

**Comment by teohhanhui** [comment]
1. You can use event listeners.
2. You can use event listeners and do a HTTP 301 redirect.

**Comment by dvc** [comment]
3. Why? 
I want to use default functional from most external layer. Route aliases like API syntax shugar.
IMHO, subresources - is real bad idea. Too many problems for just an route alias...

Anyway, it`s not trivial to add more query params for filter because of https://github.com/api-platform/core/blob/master/src/Util/RequestParser.php#L88

I can`t modify already parsed Request.query.parameters, because they not used in ReadListener.

I will not modify server QUERY_STRING - it`s really bad idea.

301 redirect... no. I don`t like it.

So, continue looking in deep of ReadListener... :(

Thank you, @teohhanhui
