### ISSUE TITLE
Service 'php' failed to build: Please provide a source image with `from` prior to commit

### ISSUE THREAD

**Issue by claudiunicolaa** [api-platform/api-platform#716]
Hello there,

I have some problems with installing process of api-platform 2.2.7.

**Info:** 
- Ubuntu 16.04 LTS
- docker-compose version 1.21.2, build a133471
- Docker version 1.13.1, build 092cba3

**Issue:**
`docker-compose up -d`

Building php
Step 1/22 : ARG PHP_VERSION=7.2
ERROR: Service 'php' failed to build: Please provide a source image with `from` prior to commit

**Comment by bennukem** [comment]
in api/DockerFile
use FROM php:7.2-fpm-alpine

**Comment by dunglas** [comment]
Can you try with the last version of Docker (18) please?

**Comment by claudiunicolaa** [comment]
With the last version of Docker, everything works great. 
Thanks!
