### ISSUE TITLE
How can i translate the entities without to custom the controller?

### ISSUE THREAD

**Issue by lekeutch** [api-platform/api-platform#72]
Hi Everyone,
Thank you for your work shot. I have a preoccupation about API Platform.

I'm using API Platform 1.0 for one of my projects. I need to translate some fields of my entities in some languages into the API. 

I will want to know: 
Is it possible to make these translations without to custom the controller? if so, how can i do it? otherwise what solutions you offered me?

Thank you in advance.

**Comment by lekeutch** [comment]
Finally, for those who're interested in, I created an event listener on the event "PRE_CREATE" to put the necessary translations via StofDoctrineExtensionBundle.

**Comment by dunglas** [comment]
Nice! Can you share you're code (a gist or something like that), it may help some people.

**Comment by lekeutch** [comment]
Okay, but unfortunately I had to overload the **ResourceController** and create my own **DataEvent** recovering resource and a collection of any object.

**Comment by lekeutch** [comment]
For example: Let's assume an article  created in english :
json data: `{
   "title": "my article in english",
   "description": "Description of my article."
}`
endpoint: `/en/articles/1`
I will want to translate it in French : PUT `/fr/articles/1` => `{ "title": "Mon article en français", "description": "Description de mon article" }`
I used **StofDoctrineExtensions** for translation, I invite you to look at the documentation of the [library DoctrineExtension](https://github.com/Atlantic18/DoctrineExtensions/blob/master/doc/translatable.md#personal-translations)

To do so,

- I had to change in **DataEvent** to put any object
![capture d ecran 2016-04-19 a 19 26 52](https://cloud.githubusercontent.com/assets/248206/14650738/dd0dbbca-0664-11e6-9213-d57da1aeee11.png)

- i had to overload the controller of API Platform : **ResourceController**. I created a custom operation PUT in which I work with an object matching json data and the source object
![capture d ecran 2016-04-19 a 19 36 55](https://cloud.githubusercontent.com/assets/248206/14651051/2380f9cc-0666-11e6-9c71-6445fc94431b.png)

- I had to create an event listener on **Pre_Update**. In this function, 
![capture d ecran 2016-04-19 a 19 49 57](https://cloud.githubusercontent.com/assets/248206/14651508/04c450ea-0668-11e6-9bf1-e517491e34b3.png)

And that's all. If someone finds a simpler way, I am ready to read

**Comment by Simperfit** [comment]
This is great !

But with the release of V2 @lekeutch did you try it out ? if so we could made an [documentation](https://github.com/api-platform/docs) exemple ?
