### ISSUE TITLE
cURL error 56: Recv failure: Connection reset by peer: When too many entities associated to oneToMany

### ISSUE THREAD

**Issue by sylflo** [api-platform/api-platform#721]
I don't understand why but I am having this error `"hydra:description": "cURL error 56: Recv failure: Connection reset by peer (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"`

I know how to produce the bug but I don't understand why it's happening.
In summary I have an object `Campaign` and in this object I have a field `PersonalizedArticle` which is a `OneToMany` and in this `PersonalizedArticle`, I have an object `Price`. The problem is I have 1000 prices per `PersonalizedArticle`, if I remove the `Prices` or lower the quantity the bug is not produced.

I thought it was a problem because of a rate limit in php and/or nginx so I tried to increase `client_max_body_size` in `nginx.conf` and also `memory_limit` in `php.ini` without success

That's the response from the server, any help would be really nice.
[response from the server](https://pastebin.com/q4jpfrE9)

**Comment by teohhanhui** [comment]
It seems like you have some problem with the Varnish container? Was it running properly?

Have you managed to resolve the issue? If not, please help us reproduce the issue.

**Comment by teohhanhui** [comment]
Uhh, so it's a problem with having too many items to be purged from the Varnish cache? Perhaps https://github.com/api-platform/core/issues/1776 could help.

**Comment by teohhanhui** [comment]
I think this might be a duplicate of https://github.com/api-platform/core/issues/1856?

**Comment by sylflo** [comment]
yeah it is, I will close this issue then
