### ISSUE TITLE
Remove /api prefix from all the endpoints 

### ISSUE THREAD

**Issue by MustaphaGhlissi** [api-platform/api-platform#728]
Hi guys 

I am working within API platform symfony 4 

My virtual host is api.site.local

my actual api behave like that : api.site.local/api/addresses : as an example

I want to remove the prefix /api which means the endpoints will be like this : api.site.local/addresses as an example

Any help please 

Regards

**Comment by dunglas** [comment]
Just remove the `prefix: /api` line in `config/routes/api_platform.yaml` and you're all set!

**Comment by MustaphaGhlissi** [comment]
I resolved it by doing this : 

api:
    resource: '.'
    type:     'api_platform'
    prefix: '/' 


Thanks.

**Comment by nicolasbonnici** [comment]
For those who come here, with APIP 2.6+ 

`
api_platform:
    defaults:
      route_prefix: '/'
`
