### ISSUE TITLE
Route no found on public folder (css/js) when deploying with Kubernetes

### ISSUE THREAD

**Issue by sylflo** [api-platform/api-platform#729]
I am trying to deploy an application I developed using api-platform. For the CI I am using Auto DevOps from Gitlab I modified their template to deploy the app.
So far I am able to deploy the app correctly, I have the connection to the database. I can call my different routes and everything work as expected. But I am having one problem is that when I am trying to go to the documentation of the api, I can not get the css neither the js
```
[24-Jun-2018 21:16:48] WARNING: [pool www] child 7 said into stderr: "2018-06-24T21:16:48+00:00 [error] Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /bundles/apiplatform/swagger-u
i/swagger-ui.css" (from "http://35.186.252.125/")" at /srv/api/vendor/symfony/http-kernel/EventListener/RouterListener.php line 139"
```
I don't understand why because I have the css and js files in the public folder, and I try to put a chmod 777 (in recursive) without any success

**Comment by dunglas** [comment]
The web server is probably misconfigured. Do you use the provided Nginx config?

**Comment by sylflo** [comment]
That was exactly this, I actually misconfigured the nginx pod. I added the files in the "symfony/php" pod but not in the nginx pod.
Thank you for your help

**Comment by Sermanes** [comment]
Works for me really thanks

**Comment by gun1x** [comment]
What was the solution to this issue? Can you post the working nginx config?
