### ISSUE TITLE
[Production] Kubernetes, database using Google Cloud

### ISSUE THREAD

**Issue by sylflo** [api-platform/api-platform#731]
Hello,

I have a question about using a managed DBMS, this is the recommended way in the  [documentation](https://api-platform.com/docs/deployment/kubernetes).
I would like to know if it's necessary to follow this [ step ](https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine)to connect the database and the Kubernetes cluster

I am sorry if my question sounds stupid even though I know Docker, I am pretty new around Kubernetes and struggling a bit to understand everything.

**Comment by dunglas** [comment]
Unfortunately yes, it's still necessary for GCP.

**Comment by sylflo** [comment]
Ok thank you for your quick answer
