### ISSUE TITLE
Event system for GraphQL

### ISSUE THREAD

**Issue by Sybio** [api-platform/api-platform#734]
Hi,

I enabled GraphQL and all works like a charm, except the event system.

When calling a mutation, it seems like EventSubscribers are not triggered : 
```php
<?php

namespace App\EventSubscriber;

// ...

final class NotebookSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents()
    {
        return [
            KernelEvents::VIEW => [
                ['preWrite', EventPriorities::PRE_WRITE],
                ['preValidate', EventPriorities::PRE_VALIDATE],
            ],
        ];
    }

    public function preValidate(GetResponseForControllerResultEvent $event)
    {
        $notebook = $event->getControllerResult();
        $method   = $event->getRequest()->getMethod();

        dump('Triggered'); // Not happening...
        exit;
    }

   // Could be PRE_WRITE, same result : not triggered
}
```

Event well registered : 
```bash
php bin/console debug:event-dispatcher
```
![2018-06-26_16h02_50](https://user-images.githubusercontent.com/1507731/41917500-d5fa26dc-795a-11e8-93de-8b067da6e7e6.png)

Entity : 
```php
<?php
namespace App\Entity;

// ...

/**
 * @ApiResource(
 *     graphql={
 *         "query"={"normalization_context"={"groups"={"notebooks_get_item"}}},
 *         "create"={
 *             "normalization_context"={"groups"={"notebooks_get_item"}},
 *             "denormalization_context"={"groups"={"notebooks_post_denormalization"}},
 *             "validation_groups"={"create"}
 *         }
 *     }
 * )
 * @ApiFilter(OrderFilter::class, properties={"title", "lang1", "lang2", "dateCreation"}, arguments={"orderParameterName"="order"})
 * @ApiFilter(OwnedFilter::class)
 * @ORM\Entity(repositoryClass="App\Repository\NotebookRepository")
 */
class Notebook
{
    /**
     * @var string
     *
     * @ORM\Id
     * @ORM\Column(type="guid")
     * @ORM\GeneratedValue(strategy="UUID")
     * @Groups({
     *     "notebooks_get_collection",
     *     "notebooks_get_item",
     * })
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=30)
     * @Groups({
     *     "notebooks_get_collection",
     *     "notebooks_get_item",
     *     "notebooks_post_denormalization",
     * })
     * @Assert\NotBlank(groups={"create"})
     */
    private $title;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="notebooks")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     * @Groups({
     *     "notebooks_get_collection",
     *     "notebooks_get_item",
     * })
     */
    private $user;

   // ...
```

The mutation : 
```graphql
mutation CreateNotebookMutation(
    $title: String!
) {
    createNotebook(input: {
        title: $title,
        clientMutationId: "randomId"
    }) {
        title
    }
}
```

This mutation requires a `$title` as input. And the server should assign the author and some others field, on the backend side, before the object is saved.

Validation happens when title is left blank : 
```json
{"errors":[{"message":"title: This value should not be blank.","category":"graphql","locations":[{"line":2,"column":3}],"path":["createNotebook"]}],"data":{"createNotebook":null}}
```

When title has value, got empty SQL fields error because user and others fields should be populated inside an event subscriber before saving happens :
```json
{"errors":[{"debugMessage":"An exception occurred while executing \u0027INSERT INTO notebook (id, title, lang1, lang2, date_creation, date_update, user_id) VALUES (?, ?, ?, ?, ?, ?, ?)\u0027 with params [\u0022f66cf056-794b-11e8-9dce-b06ebf1b7b06\u0022, \u0022JJIo\u0022, null, \u0022en\u0022, \u00222018-06-26 14:18:36\u0022, \u00222018-06-26 14:18:36\u0022, null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Le champ \u0027lang1\u0027 ne peut \u00eatre vide (null)","message":"Internal server error","category":"internal","locations":[{"line":2,"column":3}],"path":["createNotebook"]}],"data":{"createNotebook":null}}
```

My problem is that I want to hydrate fields based on the logged user (thanks to JWT and security) when creating a new Notebook object (via a mutation), via NotebookSubscriber::preValidate or preWrite.

![2018-06-26_16h28_32](https://user-images.githubusercontent.com/1507731/41919175-23a9b26e-795e-11e8-9165-7a79d6d04fe2.png)

Do you have a solution for this problem ? Thanks.

**Comment by dunglas** [comment]
They are not, events are tight to HTTP, and only work for rest. We need to find a solution to trigger events in GraphQL.

What we may do is add a new kind of "domain" events that will be triggered by both HttpKernel listeners and GraphQL resolvers.

**Comment by Sybio** [comment]
It could be a great feature !

So currently there is no solution (and no GraphQL resolvers ?). So curretly I should mix GraphQL and HTTP REST when needed. Or get User information in frontend and submit it with validation in backend (to check it's the same var). I think i'll do that in a first time.

**Comment by Sybio** [comment]
**So here my temporary solution :**

I updated my mutation to accept a user ID (logged user id stored in frontend, like localStorage or redux on a JS app), which is validated in backend :
```graphql
mutation CreateNotebookMutation(
    $title: String!,
    $user: String!,
    $clientMutationId: String!,
) {
    createNotebook(input: {
        title: $title,
        user: $user,
        clientMutationId: $clientMutationId
    }) {
        id
    }
}
```

A custom assert validates this is the logged user (via UserSameThanLoggedOne validor) :
```php
<?php
class Notebook
{
    // ...

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User", inversedBy="notebooks")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     * @Groups({
     *     "notebooks_get_collection",
     *     "notebooks_get_item",
     *     "notebooks_mutation",
     * })
     * @Assert\NotBlank(groups={"create"})
     * @AppAssert\UserSameThanLoggedOne(groups={"create"})
     */
    private $user;

    // ...
}
?>
```

The validator : 
```php
<?php

namespace App\Validator\Constraints;

// ...

class UserSameThanLoggedOneValidator extends ConstraintValidator
{
    /**
     * @var TokenStorage
     */
    private $tokenStorage;

    /**
     * UserSameThanLoggedOneValidator constructor.
     *
     * @param TokenStorage $tokenStorage
     */
    public function __construct(TokenStorage $tokenStorage)
    {
        $this->tokenStorage = $tokenStorage;
    }

    /**
     * @param mixed      $value
     * @param Constraint $constraint
     */
    public function validate($value, Constraint $constraint)
    {
        if (null !== $value &&
            $value instanceof User &&
            ($token = $this->tokenStorage->getToken()) &&
            ($user = $token->getUser()) &&
            $value->getId() !== $user->getId()
        ) {
            $this->context->buildViolation($constraint->message)
                          ->addViolation();
        }
    }
}
```

Not a long time solution, because we need to : 
- store in our frontend, all data which should be hydrated on the backend side.
- validate each received data, so it adds a lot of time of coding (and complexity).

If I have time and capabilities (🤣), I could help to implement Event Subscriber for GraphQL.

**Comment by nblaudez** [comment]
You can Doctrine event : 

https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/events.html#lifecycle-events

That works for me.

<?php
namespace App\EventSubscriber;

use Doctrine\ORM\Event\LifecycleEventArgs;
use App\Entity\Product;
use Symfony\Component\DependencyInjection\ContainerInterface as Container;
use App\Entity\Profile;

class ProfileSubscriber
{
    private $container;

    public function __construct(Container $container) {
        $this->container = $container;
    }

    public function postLoad(LifecycleEventArgs $args)
    {
        $profile = $args->getEntity();
        $em = $args->getEntityManager();

        if ($profile instanceof Profile) {
            $user = $this->container->get('token_storage')->getToken();
            if ($user->getId() != $Profile->getUser()->getId()) {
                $profileVisit = new ProfileVisit();
                $profileVisit->setProfile($profile);
                $profileVisit->setUser($user);
                $em->persist($datingProfileVisit);
                $em->getEntityManager()->flush();
            }
        }
    }
}


    app.datingprofile_subscriber:
        class: App\EventSubscriber\ProfileSubscriber
        arguments: ['@service_container']

        tags:
            - { name: doctrine.event_listener, event: postLoad }

**Comment by SkvokeN** [comment]
Hello, any news on the events?

**Comment by dunglas** [comment]
Yes, see api-platform/core#2329

**Comment by alanpoulain** [comment]
See: https://api-platform.com/docs/core/graphql/#events
