### ISSUE TITLE
502 Bad Gateway - php container missing ip address

### ISSUE THREAD

**Issue by MartinSkytte** [api-platform/api-platform#735]
When following the tutorial, i get a "502 Bad Gateway" when trying to access the api.

I think i have located where the error is but I do not know how to fix it as both docker and api-platform are new to me.

**The setup**:
windows 10 home (have also tried windows 10 pro with hyper-v using docker for windows)
api-platform 2.28
vagrant ubuntu box (have also tried directly in windows both versions)
docker 1.21.2

The vagrant setup have been tried on a Macbook and it works there

When looking at the boxes it seems like they are running normal.

After some digging around, i found that the php box is missing an ip address. If i do a

`docker-compose up -d` 

followed quickly by a 

`docker inspect vagrant_php_1`

`"Networks": {
                "vagrant_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "php",
                        "fe406ae7aa80"
                    ],
                    "NetworkID": "121b01343a406f9923ad05efcbaa7df2414721d7a07b9fa548fdcc645073c80c",
                    "EndpointID": "3e6fb3feca8b79fdde7c327e2d31a90c98f9b601eb13dfd4536720cee7f32c37",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.5",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:05"
                }
}`

I can see a ip address, but if I do it again the ip address is gone.

`"Networks": {
                "vagrant_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "php",
                        "fe406ae7aa80"
                    ],
                    "NetworkID": "121b01343a406f9923ad05efcbaa7df2414721d7a07b9fa548fdcc645073c80c",
                    "EndpointID": "",
                    "Gateway": "",
                    "IPAddress": "",
                    "IPPrefixLen": 0,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": ""
                }
}`

If I take a look at the network vagrant_default the php box is also not listed

`docker network inspect vagrant_default`

`"Containers": {
            "409841bbb3df4b48d24256b3970de3754f35e2f38fbb3a53ef037103b6a8d176": {
                "Name": "vagrant_db_1",
                "EndpointID": "e6a24ae5dd52d2eea2424580d6ab4c151b98f6b2ddbf49b5835d54f53ee31ff0",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "c0306df00d9db6269693e7324905ea75c67104b42acfc11fd7cddd91b27a3f48": {
                "Name": "vagrant_api_1",
                "EndpointID": "4e4aed27c7593c64e1c031a46124e6dfdfc76b058056af1a8a76f0b5f3ec6ea8",
                "MacAddress": "02:42:ac:12:00:06",
                "IPv4Address": "172.18.0.6/16",
                "IPv6Address": ""
            },
            "d527197edd78c62f65e89c6241a4116e11f6e2f57a80e721d206fb0f746c5624": {
                "Name": "vagrant_admin_1",
                "EndpointID": "5a32759b373d2c2e335df6ec89b52b08686d3455b9290938f2173634f41e618c",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            },
            "e40797968a67eb79ee6fb2ba4debac5c91839a3a4e62fe148372dde7e0ff4949": {
                "Name": "vagrant_h2-proxy_1",
                "EndpointID": "b875b45b80d35b7c0040e6218b7425ce3e88a6d3887763bd06bfcb6886509dac",
                "MacAddress": "02:42:ac:12:00:08",
                "IPv4Address": "172.18.0.8/16",
                "IPv6Address": ""
            },
            "f297e67b4a4e9a3a0b3a5a7058d04d40d7e047cddd1d4b066df16038cc75a011": {
                "Name": "vagrant_client_1",
                "EndpointID": "89ff63c2f8255350bbc1d6093b132ad414b2b72971f073076ca9f58aea08418f",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            }
}`

Anyone who have had this problem, or do know how to solve it?

**Comment by teohhanhui** [comment]
Did the `php` container die?

Please give us the output of

```
docker-compose logs -f php
```

to help with debugging.

**Comment by MartinSkytte** [comment]
it dies and exits. I do not know why, but did not see that before now (newbie mistake)

according to the logs, it gets a permission denied on bin/console

`
hp_1          | Loading composer repositories with package information
php_1          | Installing dependencies (including require-dev) from lock file
php_1          | Nothing to install or update
php_1          | Generating autoload files
php_1          | Executing script cache:clear [OK]
php_1          | 
php_1          | Executing script assets:install [OK]
php_1          | /usr/local/bin/docker-entrypoint: line 19: bin/console: Permission denied
php_1          | Loading composer repositories with package information
php_1          | Installing dependencies (including require-dev) from lock file
php_1          | Nothing to install or update
php_1          | Generating autoload files
php_1          | Executing script cache:clear [OK]
php_1          | 
php_1          | Executing script assets:install [OK]
php_1          | /usr/local/bin/docker-entrypoint: line 19: bin/console: Permission denied
php_1          | Loading composer repositories with package information
php_1          | Installing dependencies (including require-dev) from lock file
php_1          | Nothing to install or update
php_1          | Generating autoload files
php_1          | Executing script cache:clear [OK]
php_1          | 
php_1          | Executing script assets:install [OK]
php_1          | /usr/local/bin/docker-entrypoint: line 19: bin/console: Permission denied
php_1          | Loading composer repositories with package information
php_1          | Installing dependencies (including require-dev) from lock file
php_1          | Nothing to install or update
php_1          | Generating autoload files
php_1          | Executing script cache:clear [OK]
php_1          | 
php_1          | Executing script assets:install [OK]
php_1          | /usr/local/bin/docker-entrypoint: line 19: bin/console: Permission denied
`

I have totally overlooked this in my search.

**Comment by teohhanhui** [comment]
Uhh, I think it's a legit bug.

We should add this line

```shell
chmod +x bin/console; sync
```

before

https://github.com/api-platform/api-platform/blob/ea5a3748ed202556eda1b7cb5784c87fac2f9db3/api/docker/php/docker-entrypoint.sh#L20

Can you try that (you need to do a `docker-compose build php` before you try to do `docker-compose up -d` again) and let us know if it works for you? If yes, you may also create a PR to fix it.

**Comment by teohhanhui** [comment]
Uhh, you're using version `2.2.8`, so the line should be added before

https://github.com/api-platform/api-platform/blob/154534a27597cb150a2c19d25934606ad1017f31/api/docker/php/docker-entrypoint.sh#L14

**Comment by MartinSkytte** [comment]
Just tried it, and it did not work.

`
php_1          | Loading composer repositories with package information
php_1          | Installing dependencies (including require-dev) from lock file
php_1          | Nothing to install or update
php_1          | Generating autoload files
php_1          | Executing script cache:clear [OK]
php_1          | 
php_1          | Executing script assets:install [OK]
php_1          | /usr/local/bin/docker-entrypoint: line 20: bin/console: Permission denied
vagrant_php_1 exited with code 126
`

Still with a permission denied

**Comment by teohhanhui** [comment]
Hmm... It might be a problem with VirtualBox shared folders.

**Comment by teohhanhui** [comment]
This might help: https://unix.stackexchange.com/questions/52667/file-permission-issues-with-shared-folders-under-virtual-box-ubuntu-guest-wind

**Comment by MartinSkytte** [comment]
it could be. will check it on my windows 10 pro with hyper-v in a minute

**Comment by MartinSkytte** [comment]
It must be, because now it works in windows 10 pro using docker for windows by default. Thank you so much for your help.
