### ISSUE TITLE
Fresh API-Platform 2.2.8 package, not working with docker-compose.

### ISSUE THREAD

**Issue by alpha1125** [api-platform/api-platform#736]
$> docker --version
Docker version 18.03.1-ce, build 9ee9f40
$> docker-compose --version
docker-compose version 1.21.1, build 5a3f1a3

YARN failed to install.

<snip>

 ---> bb5b1f3f8f2f
Successfully built bb5b1f3f8f2f
Successfully tagged quay.io/api-platform/varnish:latest
WARNING: Image for service cache-proxy was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Building client
Step 1/8 : FROM node:9.11-alpine
9.11-alpine: Pulling from library/node
605ce1bd3f31: Pull complete
80491f9a9817: Pull complete
31850368c53f: Pull complete
Digest: sha256:487e8ea41281a356376d72b563dbf8946ef58e2a43bdb5a1a4429c7c5e708611
Status: Downloaded newer image for node:9.11-alpine
 ---> d09e5c5dcaa0
Step 2/8 : RUN mkdir -p /usr/src/client
 ---> Running in af214fd4235e
Removing intermediate container af214fd4235e
 ---> 8873c3bb48c1
Step 3/8 : WORKDIR /usr/src/client
Removing intermediate container 6dc00b2d78c8
 ---> fa8ebc8429aa
Step 4/8 : RUN yarn global add @api-platform/client-generator
 ---> Running in d9709348a07a
yarn global v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Installed "@api-platform/client-generator@0.1.16" with binaries:
      - generate-api-platform-client
Done in 6.79s.
Removing intermediate container d9709348a07a
 ---> 0d56a9ea6f0f
Step 5/8 : COPY package.json yarn.lock ./
 ---> 6e2be1e3caad
Step 6/8 : RUN yarn install
 ---> Running in 3d1af2c9077a
yarn install v1.5.1
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/braces/-/braces-1.8.5.tgz: Request failed \"500 Internal Server Error\"".
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/client/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'client' failed to build: The command '/bin/sh -c yarn install' returned a non-zero code: 1

Ideas on how to resolve this?  The registry.yanpkg.com link works... so I'm not sure what's going on.

**Comment by teohhanhui** [comment]
Have you tried running it again? Could be an intermittent problem?

**Comment by alpha1125** [comment]
I did... but now that I gave it an hour, it's ran past that now. and now it works... thanks.
