### ISSUE TITLE
Setters execute before @Assert

### ISSUE THREAD

**Issue by sylflo** [api-platform/api-platform#737]
I am wondering what is the best way to do this so I have a OneToOne relationship and I am using getter and setter to set this

Something like this
```
 public function setColorPrice(RawArticlePriceColor $colorPrice): RawArticle
    {
        $this->colorPrice = $colorPrice;
        if ($colorPrice->getRawArticle() !== $this) {
            $colorPrice->setRawArticle($this);
        }
        return $this;
    }
```

I use Assert like this
```
 /**
     * @Groups({"normalization_raw_article", "denormalization_raw_article"})
     * @Assert\Valid
     * @Assert\NotBlank
     * @Assert\NotNull
     * @ORM\OneToOne(targetEntity="RawArticlePriceColor", mappedBy="rawArticle", cascade={"persist"})
    */
    public $colorPrice;
```

The problem I have is that if I send my object like this using null, it creates some problem
```
{
....
colorPrice: null
}
```

I don't know why exactly but when I send the POST request, it goes directly into the `setColorPrice` method. And not the Assert first. Does someone has any idea about this, is this normal behavior ?

I could do something like this in the setter, it solves the problem but it looks really gross
```
 public function setColorPrice($colorPrice): RawArticle
    {
        if ($colorPrice == NULL)
            throw new \Exception('Should not be null');
        $this->colorPrice = $colorPrice;
        if ($colorPrice->getRawArticle() !== $this) {
            $colorPrice->setRawArticle($this);
        }
        return $this;
    }
```
If I send my object like this I don't have any problem
```
colorPrice: {}
```

For me the setter should only set and do nothing else.

I thank you in advance for your answer

**Comment by Steveb-p** [comment]
This behaves consistently with how Symfony framework does those checks. I doubt there is anything that Api platform can do in this matter.

This comes down to Form component first applying changes to objects (calling your setter, or acquiring access to property in any other way - check PropertyAccessor) and only after that in `FormEvents::POST_SUBMIT` calling `ValidationListener` (with a priority set for this listener as well as I recall).
