### ISSUE TITLE
Support to Angular 6

### ISSUE THREAD

**Issue by zukko1** [api-platform/api-platform#739]
This is not a bug or anything like that, I just have a huge doubt, I'm currently developing a SPA with api-platform and I think I made the huge mistake of choosing Angular as my framework front, this because I have not absolutely no trace of documentation about the integration of the two, I only find for AngularJS VueJS and React, my question is will not any support for current versions of Angular?

**Comment by soyuka** [comment]
I'm using angular, it's not much different from react. To facilitate queries I'm using [rxrest](https://github.com/soyuka/rxrest) but the default `http` service from angular will work just fine.

What are your issues/questions regarding the use of angular with Api Platform?

**Comment by dunglas** [comment]
There is a community client generator for Angular: https://github.com/momenttech/lysis
And, for the record, we'll be glad to merge an Angular skeleton in the main client-generator project.

**Comment by zukko1** [comment]
@soyuka my problem basically is that when I generate a typescript interface for example:

`export interface User {
  '@id': string;
  '@type': string;
  username: string;
  salt?: any;
  password: string;
  roles: string[];
  isActive: boolean;
  groups: string[];
}`

the @id and @type attributes I can not access, this is my service method:

` public GetList() {
    return this.http.get<User[]>(this.url)
            .pipe(map(data => data['hydra:member']))
            .subscribe(
                 (restItems: User[]) => this.usersSubject.next(restItems)
      );
  }`

when i try to access restItems[0].'@id'  I know that this attribute can not be accessed but it is what I am trying to do.

and @dunglas i will to try use that library tks!

**Comment by dunglas** [comment]
`restItems[0]['@id']` (same as in JS).

**Comment by er1z** [comment]
I bless someone who could have ran lysis with no issue. Everytime I try to generate SPA API, it produces an empty service and properties. Any *working* tutorial on this piece of software?

**Comment by dunglas** [comment]
I think it would be easier to port lysis in client-generator. It would allow shared maintenance with other generators.

**Comment by er1z** [comment]
@zukko1 — I've done something working via generating using ``swagger.json``. It's not first class quality generator code but seems to be working. I'll post an update to this issue with repo link.

**Comment by panakour** [comment]
This repo https://github.com/cyclosproject/ng-openapi-gen will automatically generate your models and services. In a minutes you are be able to request your data from api-platform.

**Comment by er1z** [comment]
Yup, but you have no access to JSON-LD benefits using OpenAPI-compatible tools.

**Comment by panakour** [comment]
> Yup, but you have no access to JSON-LD benefits using OpenAPI-compatible tools.

they also generate jsonld models 

```
export interface GreetingJsonld {
  '@context'?: string;
  '@id'?: string;
  '@type'?: string;

  /**
   * The entity Id
   */
  id?: number;

  /**
   * A nice person
   */
  name: string;
}

```
