### ISSUE TITLE
Question : How to deal with external resources ? (Using URL as URI ?)

### ISSUE THREAD

**Issue by MLKiiwy** [api-platform/api-platform#74]
I use API Platform since a year now, and I have a problem to solve about external resource and I request opinion of the API Platform community to deal with it.
# The case : My API use external resources provided by other APIs

Example : A Comment API for Movies.
![szkeduxyg1mwykmlfpaxmzw](https://cloud.githubusercontent.com/assets/619217/14680586/14df71e2-071e-11e6-932a-d3d1d490532c.png)

I think the usage of JSON-LD help us to deal with this kind of resources. 
Instead having internal resources like : "/movies/1" we use the full url resources like "http://api.imdb.com/movies/1" or "http://api.allocine.fr/films/one". So we can use URL as URI for our POST/PUT/GET requests.
# Questions
- In the API return, if we are using external resources we must have the full URL right ? 
- How to store a link with an External resource in database ? A string ? What's your opinion about performance, etc ... ?
- How to deal with Doctrine entities ? Its kind of relation but through an API ...
- Have you some experience with this kind of thing to share with me ? 

Thanks for your returns !

**Comment by teohhanhui** [comment]
I think a string would be right. And it's not treated as a relation... What do you need to do with it?

**Comment by vincentchalamon** [comment]
Consider your url as a regular string like any textual value, not as a relation (as it's not one in your Doctrine schema).

**Comment by Simperfit** [comment]
@MLKiiwy Did you find the solution, did @vincentchalamon respond to your answer ?

**Comment by bartlomiejmarszal** [comment]
Hi! I'm looking for example for using external resources in our api. Where can I find some hints about this problem?
