### ISSUE TITLE
api-platform/demo installation problem 

### ISSUE THREAD

**Issue by adrienrn** [api-platform/api-platform#740]
I finally tried api-platform after seeing you guys at the Symfony Live earlier this year. 🍻 

I was having problems on the online demo:

`curl -X GET "https://demo.api-platform.com/books" -H  "accept: application/ld+json"`

<img width="1221" alt="capture d ecran 2018-07-01 a 18 05 01" src="https://user-images.githubusercontent.com/5598481/42136321-4fc6f8bc-7d59-11e8-8544-bb1821746ab7.png">

```
{"@context":"\/contexts\/Error","@type":"hydra:Error","hydra:title":"An error occurred","hydra:description":"Internal Server Error"}
```

I decided to install the demo locally to try to look it up myself. Clone the repository and lauched docker-compose successfully. I was able to go on the homepage but trying to reach the api on :8080 returned a 502 Bad Gateway error.

I wasn't able to understand what was wrong (suspected my setup for a while with docker inside a vagrant vms on MacOs). I browsed a lot of issue which got me on the trail, php container was starting and then exited around 3 seconds after. I launched `docker-compose up -d` and got this:

<img width="999" alt="capture d ecran 2018-07-01 a 18 09 03" src="https://user-images.githubusercontent.com/5598481/42136356-deb49214-7d59-11e8-9ac5-0737f344662d.png">

```
php_1          | Executing script security-checker security:check [KO]
php_1          |  [KO]
php_1          | Script security-checker security:check returned with error code 1
[...]
php_1          | !!  
php_1          | Script @auto-scripts was called via post-install-cmd
apiplatformdemo_php_1 exited with code 1
```

Removed the post-install-script in the composer.json, relaunched and it's working.
Is it just me ? Is it know (couldn't find another issue on this) ? Is it the same thing that made the online demo crash ? 😣

Bonsoir messieurs!

**Comment by teohhanhui** [comment]
This means we need to update Symfony.
