### ISSUE TITLE
Unknown Type in entity class

### ISSUE THREAD

**Issue by kpn13** [api-platform/api-platform#741]
Hi,

I would like to structure on of my entity like that : 

```php
<?php
namespace App\Entity;

/**
 * @ApiResource(attributes={
 *     "normalization_context"={"groups"={"read"}},
 *     "denormalization_context"={"groups"={"write"}}
 * })
 */
class Document
{
 ...
    /**
     * @var Client
     * @Type(type="Client")
     * @Groups({"read", "write"})
     * @ApiProperty(
     *     attributes={
     *         "swagger_context" = {"type" = "Client" }
     *     }
     * )
     */
    public $client;
  ...
}
```
But in the SwaggerUI description I have this error message : "client": "Unknown Type: Client".

![image](https://user-images.githubusercontent.com/864114/42207254-cc32bdc2-7ea9-11e8-9150-8a1e54ced48f.png)

The Client class is not tagged as "ApiResource". I also don't want Client to be a "sub resource". 

```php
<?php
namespace App\Entity;

class Client
{
....
    /**
     * @var string api key identifier
     * @Groups({"read", "write"})
     */
    public $name;
}
```

I just want my API accept something like this for a POST /documents:

```json
{
    "oid": "",
    "client": {
        "id": "",
        "name": ""
    }
}
```

I probably miss something obvious... Could you help me please ?

Thank you in advance !

Best regards.

**Comment by dunglas** [comment]
If the `Client` class isn't an API Resource, you need to add yourself the corresponding JSON schema to the Swagger documentation.

You can override the Swagger documentation: https://api-platform.com/docs/core/swagger/
And https://github.com/dunglas/php-to-json-schema may help to generate the JSON schema.

**Comment by kpn13** [comment]
Ok thanks ! 

And declare my Clent class as an API Resource in order to benefit of the built-in API Plateform doc but without having the generated route could be an other solution ?

**Comment by kpn13** [comment]
Hi,

Finally I just do what you suggest by using  a "swaggerdecorator" like that : 

```php
<?php
$docs['definitions']['Document-read']['properties']['client']['type'] = 'object';
$docs['definitions']['Document-read']['properties']['client']['properties'] = ['id', 'name'];
$docs['definitions']['Document-read']['properties']['client']['properties']['name']['type'] = 'string';
$docs['definitions']['Document-read']['properties']['client']['properties']['name']['example'] = 'foo';
```

Thanks !
