### ISSUE TITLE
ClassNotFoundException just after installing api-platform bundle

### ISSUE THREAD

**Issue by justinas-kazanavicius** [api-platform/api-platform#745]
After I run `composer require api` on my Symfony 4.1 project, I get:

```
ClassNotFoundException

Attempted to load class "NelmioCorsBundle" from namespace "Nelmio\CorsBundle".
Did you forget a "use" statement for another namespace?
```

Any ideas on how do I fix this?

**Comment by dunglas** [comment]
Weird. What version of PHP do you use? Can you paste the output of `composer info`?

**Comment by justinas-kazanavicius** [comment]
Whoops, I ran `composer install` outside of my VM. After running it inside vagrant its working fine.
