### ISSUE TITLE
POST collection

### ISSUE THREAD

**Issue by mcanepa** [api-platform/api-platform#747]
Is it possible to post more than one item at once?

If I `POST` with
```
{
	"name": "test item"
}
```

Then I get a succesfull `201`

but if I try:
```

[{
	"name": "test item 1"
}, {
	"name": "test item 2"
}, {
	"name": "test item 3"
}]
```

Then I get

> Type error: Argument 2 passed to ApiPlatform\\Core\\Metadata\\Property\\Factory\\CachedPropertyMetadataFactory::create() must be of the type string, integer given, called in E:\\Pro\\dirigentes\\api\\vendor\\api-platform\\core\\src\\Serializer\\AbstractItemNormalizer.php on line 158

**Comment by soyuka** [comment]
Not possible, ongoing discussion https://github.com/api-platform/core/pull/1645

**Comment by NicolasFCO** [comment]
So why POST method is defined like a "Collection operations" [in the documentation](https://api-platform.com/docs/core/operations/) ?

**Comment by dunglas** [comment]
Because it’s how REST works. You add a new element to an existing collection: it’s an operation on a collection. Then you can manipulate this element directly using PUT, PATCH or DELETE.

**Comment by NicolasFCO** [comment]
Ok so what is the difference with PUT method which is in "Item operations"? Indeed, we could think the same way : you can create element with PUT so it’s an operation on a collection then manipulate this element...

**Comment by dunglas** [comment]
> The POST method is used to request that the origin server accept the
   entity enclosed in the request as a new **subordinate** of the resource
   identified by the Request-URI in the Request-Line. [...]
> If a resource has been created on the origin server, the response
   SHOULD be 201 (Created) and contain an entity which describes the
   status of the request and refers to the new resource, and a Location
   header (see section 14.30).

https://tools.ietf.org/html/rfc2616#section-9.5 (emphasize mine)

> The PUT method requests that the enclosed entity be stored under the
   supplied Request-URI. If the Request-URI refers to an already
   existing resource, the enclosed entity SHOULD be considered as a
   modified version of the one residing on the origin server.

https://tools.ietf.org/html/rfc2616#section-9.6

**Comment by dunglas** [comment]
Anyway, a PHP error must not be thrown, it should be a 400. To me it's a bug.

**Comment by slavcodev** [comment]
> The POST method is used to request that the origin server accept the
entity enclosed in the request as a new subordinate of the resource
identified by the Request-URI in the Request-Line. [...]
If a resource has been created on the origin server, the response
SHOULD be 201 (Created) and contain an entity which describes the
status of the request and refers to the new resource, and a Location
header (see section 14.30).

I believe by the "the entity eclosed in the request" is not meant the collection item. It can be a segment of collection.

**Comment by dunglas** [comment]
I agree, but it’s not supported (yet) in API Platform. PR welcome!

**Comment by NicolasFCO** [comment]
Do you have a simply way to achieve that ? For instance override the controller only for a PUT request :
`[{
        "id": 1,
	"name": "test item 1"
}, {
        "id": 2,
	"name": "test item 2"
}, {
        "id": 2,
	"name": "test item 3"
}]`

I'm trying to implement custom operation with DTO and messenger but I'm afraid you must either override all requests of a given entity or create a new entity which contains a collection of the given entity. 

Is it really that or am I wrong ?

**Comment by dominiquefournier** [comment]
In the PR, maybe with a configuration parameter : "allowMultiple", set to false by default ? If set to true, allow an array of entity or an entity ?

**Comment by dunglas** [comment]
Note that with HTTP/2 and 3, which support multiplexing, sending several parallel post request is usually not an issue.
