### ISSUE TITLE
subresource and access_control

### ISSUE THREAD

**Issue by Lobosque** [api-platform/api-platform#748]
I came accross #529 while trying to add access control logic to a subresource. 
However, adding this to the parent Entity `@ApiResource` is not working, you see I added an expression that will always evaluate to false only to see if is being executed:

```
 *     subresourceOperations={
 *         "address_get_subresource"= {
 *             "method"="GET",
 *             "access_control"="1 == 5"
 *         }
 *     }
```
I also tried using the full route name without success (`api_users_address_get_subresource`).

--
On a related note:
What I ultimately want to do is validate if when updating the nested resource, the user is changing its id. So I Also wonder if its possible to force `api-platform`  to always update the current nested resource on OneToOne relations. The default behaviour is "create if no id is present and update if id is present". And changing it to "always update the current one" would completely solve my problem.

**Comment by soyuka** [comment]
> The default behaviour is "create if no id is present and update if id is present". And changing it to "always update the current one" would completely solve my problem.

Custom data persister?

The access_control annotation above looks legit though.

**Comment by BatsaxIV** [comment]
I just faced the same issue and it works when adding the code in the subresouce entity not in the main one.

**Comment by Lobosque** [comment]
thanks @BatsaxIV, adding it to the subresource worked.

**Comment by soyuka** [comment]
> @soyuka is this by design?

Yes but we have an ongoing discussion somewhere to change this. We def should do an RFC on the subresources.

**Comment by tomsykes** [comment]
There's actually enough within the context of the annotation expression to pass to a voter...

```php
/*     subresourceOperations={
 *          "api_questions_answers_get_subresource"= {
 *              "security"="is_granted('GET_SUB_RESOURCE', _api_normalization_context['subresource_resources'])",
 *          },
 *     }
 */
```

I then have a generic sub-resource voter, but you could create one per parent resource easily...

```php
class SubresourceVoter extends Voter
{
    /** @var Security */
    protected $security;

    /** @var EntityManagerInterface */
    protected $manager;

    public function __construct(Security $security, EntityManagerInterface $manager)
    {
        $this->security = $security;
        $this->manager = $manager;
    }

    protected function supports($attribute, $subject)
    {
        if (($attribute !== 'GET_SUB_RESOURCE') || !is_array($subject)) return false;

        [$className, $id] = $this->getClassAndId($subject);
        return (class_exists($className));
    }

    protected function voteOnAttribute($attribute, $subject, TokenInterface $token)
    {
        [$className, $id] = $this->getClassAndId($subject);
        $entity = $this->manager->getRepository($className)->find($id);

        return // some logic;
    }

    protected function getClassAndId($subject) {
        $className = array_keys($subject)[0];
        $id = $subject[$className]['id'] ?? null;
        return [$className, $id];
    }
}
```

Final note - if you want to know what else is available in the context of the security expression, just put something random in there like "badger". It'll throw an exception, and somewhere in the stack trace (`Symfony\Component\ExpressionLanguage\ExpressionLanguage->evaluate`) is a list of all the variables, and their values.
