### ISSUE TITLE
Microservice question

### ISSUE THREAD

**Issue by vinyvicente** [api-platform/api-platform#756]
Hi,

How I can use API Platform to provide documentation to my external APIs?

For example: I use API Platform to some services, as customer, as product, and other.
But, I have others REST services that connect into, with others languages and others PHP micro frameworks, using shared database. Which better strategy to provide documentation into services, using API Platform as principal? Sure, I need uses pattern principle of API Platform to others services (Node.js, Go, anyway)

Using docker, and in future, Kubernetes, what a better strategy?

Thanks, advance.

**Comment by dunglas** [comment]
JSON-LD is a good way to describe to other services the types and operations exposed by your API Platform service. Alternatively, you can use OpenAPI (Swagger). Both formats are automatically generated and available for other services (`/docs.jsonld` and `/docs.json`).

**Comment by dunglas** [comment]
We also support the specific flavor of OpenAPI required to use AWS API Gateway: https://api-platform.com/docs/core/swagger/#enable-swagger-doc-for-api-gateway

**Comment by vinyvicente** [comment]
Thanks @dunglas !
