### ISSUE TITLE
[1.x] Filters are corrupted on hydra:firstPage & hydra:lastPage JSON-LD response keys

### ISSUE THREAD

**Issue by vincentchalamon** [api-platform/api-platform#76]
When I call `/reservations?meal.startedAt[after]=2015-01-02+14:00:00` (so with filter `meal.startedAt`), this filter is corrupted on `hydra:firstPage` & `hydra:lastPage` JSON-LD response keys:

```json
{
    "@context": "/contexts/Reservation",
    "@id": "/reservations?meal.startedAt[after]=2015-01-02+14:00:00",
    "@type": "hydra:PagedCollection",
    "hydra:totalItems": 2,
    "hydra:itemsPerPage": 30,
    "hydra:firstPage": "/reservations?meal_startedAt%5Bafter%5D=2015-01-02+14%3A00%3A00",
    "hydra:lastPage": "/reservations?meal_startedAt%5Bafter%5D=2015-01-02+14%3A00%3A00",
    "hydra:member": []
}
```

As you can see, `meal.startedAt` filter is converted to `meal_startedAt`, which is invalid.

**Comment by teohhanhui** [comment]
This bug should be filed under `api-platform/core`.

**Comment by Simperfit** [comment]
@vincentchalamon it's ok now :) ?

**Comment by vincentchalamon** [comment]
Perfect, thank you very much @Simperfit
