### ISSUE TITLE
[BUG] Plain Ids not working with JSON

### ISSUE THREAD

**Issue by do-web** [api-platform/api-platform#763]
I have enabled allow_plain_identifiers and set the header "Accept: application/json"

The PATCH ist working fine with this:

```
{
"id": 1,
"articles": [
  "article": "20"
]
}
```

But then the response is in IRI format
```
{
"id": 1,
"articles": [
  "article": "/articles/20"
]
}
```

Expected result should be:

```
{
"id": 1,
"articles": [
  "article": "20"
]
}
```

**Comment by teohhanhui** [comment]
I see you've moved this to https://github.com/api-platform/core/issues/2101
