### ISSUE TITLE
Wish list : Security (JWT) + Custom login operations

### ISSUE THREAD

**Issue by Larzack** [api-platform/api-platform#764]
Hello,

Is it possible to add in the default example, the security ?

Most API are secured and have a User Entity, and this is not easy to add security in API platform when you'r new.

It would be nice to add an extra User Entity which manage Security ( JWT Token + Refresh Token ) and add some custom routes : 
- POST /users/register  (email + pass + username ? + xx)
- POST /users/login  (email + pass + username ?) => can login with email or username ?
- POST /users/forgotpassword (email)
- POST /users/refresh (refresh_token)
- GET /users/me

We can now protect a entry like 
- DELETE /greetings/delete with access to a logged user, or with a user role.

This will explain better **Security** and **Custom Actions**
Most API have this actions and with only this few extra method, this will reduce the learning curve of ApiPlatform.

I have in mind this bundles 
- https://packagist.org/packages/lexik/jwt-authentication-bundle ( JWT )
- https://packagist.org/packages/gesdinet/jwt-refresh-token-bundle ( Refresh )
- https://packagist.org/packages/friendsofsymfony/user-bundle

Maybe it could be an extra recipe ?

Look how many person are looking for a working implementation of the security mechanism and custom action like /me 
 
Best regards

**Comment by Larzack** [comment]
@dunglas , any feedback ?

**Comment by msitruk** [comment]
In my case how I did : 

1) Create a User entity implementing UserInterface and \Serializable expoed trough @ApiResource with groups write/read for password field.
2) Install https://packagist.org/packages/lexik/jwt-authentication-bundle ( JWT )
3) Install https://packagist.org/packages/gesdinet/jwt-refresh-token-bundle ( Refresh )
4) Edit security.yaml to add provider and firewall for "login", "/login_check", "/token/refresh" and "/api_doc", same for access_control part
5) Edit routes.yaml to add swagger_ui, api_login_check and gesdinet_jwt_refresh_token
6) Edit api_platform.yaml for swagger

If that can help.

**Comment by ikerib** [comment]
> In my case how I did :
> 
> 1. Create a User entity implementing UserInterface and \Serializable expoed trough @ApiResource with groups write/read for password field.
> 2. Install https://packagist.org/packages/lexik/jwt-authentication-bundle ( JWT )
> 3. Install https://packagist.org/packages/gesdinet/jwt-refresh-token-bundle ( Refresh )
> 4. Edit security.yaml to add provider and firewall for "login", "/login_check", "/token/refresh" and "/api_doc", same for access_control part
> 5. Edit routes.yaml to add swagger_ui, api_login_check and gesdinet_jwt_refresh_token
> 6. Edit api_platform.yaml for swagger
> 
> If that can help.

Do you have your code in any repo where we can see?

**Comment by Larzack** [comment]
I think many persons would like this code. This is why I asked to implement It directly is the ApiPlatform example code. It's better to understand with a working example and then remove the code than produce doc.
Only persons with good skills can do this and this is the beginning of an API.
99,9% of API are not opened ? Less ? More ?

Regards

**Comment by Rebolon** [comment]
It would be interesting to add sample with usage of a DataProvider coz it doesn't seems to use access_control annotation

**Comment by GregoireHebert** [comment]
Example of usage have been set up in the demo.
You can have a look at the 2 following PR:
https://github.com/api-platform/demo/commit/9d61e551d6ebb62bb94d66c9de2b84ae4412f072
https://github.com/api-platform/demo/commit/534ccab2fe371939e8d37d781f70255d57151cc1
