### ISSUE TITLE
Less descriptive error messages

### ISSUE THREAD

**Issue by tomekpolska** [api-platform/api-platform#766]
Can't find a way to show less descriptive error messages. Now I can see filenames and complete trace in response body, don't want to reveal the information to users. How to disable it or return less data?

Eg. 500 Error: Internal Server Error generates:

`{
  "@context": "/api/contexts/Error",
  "@type": "hydra:Error",
  "hydra:title": "An error occurred",
  "hydra:description": "Full authentication is required to access this resource.",
  "trace": [
    {
      "namespace": "",
      "short_class": "",
      "class": "",
      "type": "",
      "function": "",
      "file": "/home/www/someproject/vendor/symfony/security/Http/Firewall/ExceptionListener.php",
      "line": 126,
      "args": []
    },`

and so on.

**Comment by dunglas** [comment]
Just switch to the `prod` environment, stack traces will be hidden automatically.
