### ISSUE TITLE
Subresource query builder needs identifier custom type

### ISSUE THREAD

**Issue by maaxxicarvalho** [api-platform/api-platform#767]
I found a possible problem when using UUIDs as primary keys and relationship fields.
The `Doctrine/Orm/SubresourceDataProvider.php` will not build the query properly in this case.

I'm using the package [https://github.com/ramsey/uuid-doctrine](https://github.com/ramsey/uuid-doctrine) with [InnoDB-optimised binary UUIDs](https://github.com/ramsey/uuid-doctrine#innodb-optimised-binary-uuids) so it requires the parameter `type` to be explicitly declared when building a query.

The code at `vendor/api-platform/core/src/Bridge/Doctrine/Orm/SubresourceDataProvider.php:197` sets the parameter for each of the normalized identifiers without specifing the parameters `type` with the following instruction:

```php
// Add where clause for identifiers
foreach ($normalizedIdentifiers as $key => $value) {
    $placeholder = $queryNameGenerator->generateParameterName($key);
    $qb->andWhere("$alias.$key = :$placeholder");
    $topQueryBuilder->setParameter($placeholder, $value);
}
```

I change to the code below solved the problem:
```php
// Add where clause for identifiers
foreach ($normalizedIdentifiers as $key => $value) {
    $placeholder = $queryNameGenerator->generateParameterName($key);
    $qb->andWhere("$alias.$key = :$placeholder");
    $topQueryBuilder->setParameter($placeholder, $value, , $classMetadata->getTypeOfField($identifier));
}
```

Now I'd like to know if the change is doable and if it makes sense, the extra code is `, $classMetadata->getTypeOfField($identifier)` as you probably noticed.

Thank you for your help.

**Comment by soyuka** [comment]
Doctrine should handle the parameter type if it is represented by a correct class (eg `instance of UuidBinaryOrderedTimeType`) and that the same class is registered as a doctrine Type.

Is it possible that you need a custom identifier normalizer (the `$value` is not an instance of `UuidBinaryOrderedTimeType`? See https://github.com/api-platform/docs/blob/master/core/identifiers.md#custom-identifier-normalizer.

**Comment by soyuka** [comment]
May you give a shot at my patch?

**Comment by maaxxicarvalho** [comment]
Hi @soyuka 

That's exactly the fix I applied on my end. I'm sorry if I didn't submit an MR, I didn't understand the Unit Test stack properly.

**Comment by soyuka** [comment]
Will be available in the next release, thanks for the detailed bug report.
