### ISSUE TITLE
Make sure there is a loader supporting the "api_platform" type

### ISSUE THREAD

**Issue by kevinimbrechts** [api-platform/api-platform#774]
Hi.

I have installed API Platform in my Symfony 4 project and I have this exception when I go to /api :
`An exception occurred in driver: could not find driver in . (which is being imported from "/var/www/html/sf4proj/config/routes/api_platform.yaml"). Make sure there is a loader supporting the "api_platform" type.`

Here is a part of my composer.json :
```
... 
   "require": {
        "php": "^7.1.3",
        "ext-iconv": "*",
        "api-platform/api-pack": "^1.1",
        "doctrine/orm": "^2.6",
        "jms/serializer-bundle": "^2.3",
        "sensio/framework-extra-bundle": "^5.1",
        "symfony/console": "^4.0",
        "symfony/flex": "^1.0",
        "symfony/framework-bundle": "^4.0",
        "symfony/lts": "^4@dev",
        "symfony/maker-bundle": "^1.4",
        "symfony/monolog-bundle": "^3.2",
        "symfony/orm-pack": "^1.0",
        "symfony/translation": "^4.0",
        "symfony/yaml": "^4.0"
    },
...
```

And my /config/routes/api_platform.yaml file :
```
api_platform:
    resource: .
    type: api_platform
    prefix: /api
```

I use 3 containers : PHP-FPM 7.2.5, NginX 1.14 and Postgres 10.4.

I did not find anything on this error...

**Comment by teohhanhui** [comment]
What is `driver`? :rofl:

**Comment by kevinimbrechts** [comment]
I don't know ¯\_(ツ)_/¯
I don't understand :(

**Comment by teohhanhui** [comment]
Uhh, it's an exception from Doctrine.

**Comment by kevinimbrechts** [comment]
Seriously ? 😱
If that's it, I'm really too tired... I'll check Monday at work.
Thanks

**Comment by kevinimbrechts** [comment]
Hello,
My DATABASE_URL was properly set and `bin/console doctrine:database:create` works. :(

**Comment by teohhanhui** [comment]
Do you get the same exception when you do `bin/console cache:clear`?

**Comment by kevinimbrechts** [comment]
I don't have any exception with `bin/console cache:clear`. The exception is displayed in Firefox.
I changed nothing. With Docker for Windows, it was working but not in my Ubuntu VM with Docker. It's very strange and I don't see any difference.

**Comment by teohhanhui** [comment]
Then it could be that you have a mismatch of the environment variables between the shell and php-fpm.

**Comment by kevinimbrechts** [comment]
Ok, I have restarted the Docker service and now, it works...

**Comment by jeanphiB** [comment]
Hi, useful exchanges for me, but `docker-compose build` has been the better solution for me. Thank to @vincentchalamon for his help.

**Comment by nombrekeff** [comment]
Restarting docker worked for me as well

**Comment by KalinichenkoRoman** [comment]
composer install helps for me

**Comment by hycmedia** [comment]
I encountered the issue when setting up my project with circleci.
However, explicitly mentioning the server version and the driver solved it: 
```
server_version: 'mariadb-10.5.9'
driver: 'pdo_mysql'
```

**Comment by ludgourdon** [comment]
> I encountered the issue when setting up my project with circleci.
> However, explicitly mentioning the server version and the driver solved it:
> 
> ```
> server_version: 'mariadb-10.5.9'
> driver: 'pdo_mysql'
> ```

Hi, same problem for me with github actions, may I ask you where did you mention server version and driver ? I've already done it in config/packages/doctrine.yaml but it doesn't resolve the issue. Thanks

**Comment by MarkEhr** [comment]
I was having this same error. It turned out that for me it was because of special characters in the database url in the .env file. Even though they were urlencoded.
I opted for changing the db password.
