### ISSUE TITLE
Unrecognized option "validator" under "framework" Exception after fresh install

### ISSUE THREAD

**Issue by finwe** [api-platform/api-platform#781]
Following [composer installation from the quickstart][1], all composer commands (on scripts) as well as web requests fail on an exception `Unrecognized option "validator" under "framework"` from `ArrayNode.php line 311`

Console steps to reproduce:

```
composer create-project symfony/skeleton project
cd project
composer require api
```

Commenting out `validator` and subsequent lines from `config/packages/validator.yml` resolves the issue.

Package versions:

- symfony/skeleton: v4.1.2.2
- api-platform/core: v2.3.0

PHP 7.1, Ubuntu

[1]: https://api-platform.com/docs/distribution#using-symfony-flex-and-composer-advanced-users

**Comment by teohhanhui** [comment]
It was a problem with the Symfony recipe for Validator component. It's been fixed in https://github.com/symfony/recipes/pull/445
