### ISSUE TITLE
Distinct killing performance

### ISSUE THREAD

**Issue by irmantas** [api-platform/api-platform#792]
Hi, not sure is this right place to ask, maybe this issue should be referenced to Doctrine project. Anyway maybe you can help solve this issue. When getting some resource collection from backend it seems that all queries a have DISTINCT in it.

For example when fetching articles collections api-platform/doctrine creates this kind of query:
```sql
SELECT DISTINCT a0_.id AS id_0, a0_.date_created AS date_created_1 FROM articles a0_ ORDER BY a0_.date_created DESC LIMIT 30
```
Where DISTINCT is totally unnecessary and killing all application performance. At this case query runs quite fast, but if eager loading is enabled, and there are some joins query may took more than 1 min because of DISTINCT.

**Comment by dunglas** [comment]
Indeed, this should be discussed on the Doctrine side because this behavior is the one of Doctrine Paginator. Except if we can find an API Platform-specific way of improving this query in some cases.
IIRC Doctrine implemented this query like this because it’s the only working implementation for the general case.

**Comment by soyuka** [comment]
Use the partial pagination it won't do any distinct anyway :).

**Comment by irmantas** [comment]
Thank you @soyuka this tip solved issue for me.

**Comment by jorismak** [comment]
partial pagination enabled, but it's still doing it.

It's also quering a relation using something like
```
SELECT DISTINCT i0_.customer_id AS CUSTOMER_ID_0, i0_.customer_id AS CUSTOMER_ID_1 FROM customer i0_ INNER JOIN contacts  i1_ ON i0_.customer_id = i1_.customer_id WHERE i0_.customer_id IN (SELECT i2_.customer_id FROM customer i2_ INNER JOIN customer_contacts i3_ ON i2_.customer_id = i3_.customer_id WHERE i2_.email_address LIKE '%@test%' OR i3_.email_address LIKE '%@test%') ORDER BY i0_.customer_id ASC;
```

where is the 'SELECT DISTINCT' coming from? And where is the 'WHERE customer_id IN ()' part coming from?

**Comment by goetas** [comment]
Doctrine now supports a query hit to disable the `distinct` when the developer considers it superfluous
