### ISSUE TITLE
Getter/Setter 

### ISSUE THREAD

**Issue by TwiSka** [api-platform/api-platform#800]
Hi, 

I have :
`"job": [
    "/jobs/1"
  ]`

but I want 
`{
      "shortName": "DevBack",
      "longName1": "Developper",
      "longName2": "Backend",
      "familyJob": "/family_jobs/1",
      "valide": true,
      "site": "/sites/1",
      "planning": null,
      "lastAuthor": "/users/1",
      "user": [
        "/users/1"
      ],
      "users": [
        "/users/1"
      ],
      "id": 1,
      "deletedAt": null,
      "deleted": false,
      "createdAt": "2018-08-06T09:10:11+00:00",
      "updatedAt": "2018-08-06T09:10:11+00:00"
    }`

Someone has an idea ?
 
I try "Fetch: EAGER"
But he don't work

**Comment by soyuka** [comment]
Use serialization groups.

**Comment by TwiSka** [comment]
I try with serialization groups But he don't work to

**Comment by myAwesome** [comment]
Hi, @TwiSka !
You can look at graphql, and make queries with it.
 I don't really sure, that you can do it with classic rest api.

**Comment by antograssiot** [comment]
Closing as it's been a long time without activity,  and because serialization groups are likely the solution.
Feel free to reopen or ping me if needed
