### ISSUE TITLE
GraphQL - filter item in array

### ISSUE THREAD

**Issue by maximilienGilet** [api-platform/api-platform#801]
Hi, thanks for the amazing work you're doing with this project.

I'm looking for a way to filter my entities by an array of values. 

As said in documentation : `Another difference with the REST API filters is that the keyword _list must be used instead of the traditional [] to filter over multiple values.`

So my GraphQL request should look like : 
```graphql
{
  offers(product_color_list: ["red", "green"]) {
    edges {
      node {
        id
        product {
          name
          color
        }
      }
    }
  }
}
```

documentation reference : https://api-platform.com/docs/core/graphql/#filtering-on-nested-properties

However it's not working for me... GraphiQL shows an error `Unknown argument`

How can I make this work ?

**Comment by alanpoulain** [comment]
I think it's because it has been fixed recently. No release with the fix has been made yet.

**Comment by alanpoulain** [comment]
I think the documentation should be "released" like the code ;)
