### ISSUE TITLE
I cannot find my bundles directory inside my nginx image

### ISSUE THREAD

**Issue by vbourdeix** [api-platform/api-platform#805]
Hello, I just found out that when I docker build nginx, there is a line "COPY public /srv/api/public" in the Dockerfile.nginx, but for some reason, the bundles directory which is inside the public directory is not copied.

To be sure about that, I added a RUN ls /srv/api/public inside the Dockerfile.nginx and launched the docker build and it prints out : 
favicon.ico
images
index.php

I'm getting crazy as I don't understand why this directory in particular would not be included in the COPY. And  I don't have any error.

Do you have an idea why this is happening ?

BTW I'm building it on Windows, don't know if this is related.

**Comment by vbourdeix** [comment]
Ok I got it, there is a public/bundles/ inside .dockerignore.

Does this mean I'm supposed to generate the bundles directory during the build phase ? This makes sense for the php container which can run an assets install but it feels weird for the nginx container.

Any advice about this ?

**Comment by dunglas** [comment]
I think we should remove it. Ping @teohhanhui

**Comment by teohhanhui** [comment]
It **should** be docker-ignored, because the directory should not be copied from your project directory. `.dockerignore` should have no effect on `COPY --from`: https://github.com/moby/moby/issues/33923

**Comment by teohhanhui** [comment]
I can confirm that the files are there. How to test:

```console
docker-compose pull
docker-compose run --rm --no-deps api ls -la public/bundles/apiplatform
```

**Comment by teohhanhui** [comment]
Uhh @vbourdeix, since you speak of `Dockerfile.nginx`, you must be using a setup that is a little old. :smile:
