### ISSUE TITLE
 [Question] Add custom header to all requests from api documentation

### ISSUE THREAD

**Issue by kolinko-ant** [api-platform/api-platform#808]
Hi guys!

I searched through the internet about this topic, but did not find anything useful. So my question - is it possible to add an input to api documentation in order to send some additional header? Or maybe there is another way of doing this? I am not sure is it related to api platform itself, maybe it.s about swagger ui. Hope some of you know the direction.

**Comment by henres** [comment]
Hello,
I have the same question.
Thanks in advance for you answer.

**Comment by GermanKrutov** [comment]
+1

**Comment by smatyas** [comment]
Hi, maybe a custom swagger decorator can help you here. 
Check the example: https://api-platform.com/docs/core/swagger/#overriding-the-openapi-specification

Adding something like this to all routes might work:
```
        $customDefinition = [
            'name' => 'custom-header',
            'description' => 'custom header',
            'default' => 'default-value',
            'in' => 'header',
        ];
```

**Comment by franmomu** [comment]
Just in case someone ends up here, I used: https://api-platform.com/docs/core/jwt/#documenting-the-authentication-mechanism-with-swaggeropen-api
