### ISSUE TITLE
[Question] Is there a way to have an embedded object without an access point

### ISSUE THREAD

**Issue by aledeg** [api-platform/api-platform#81]
I'd like to have an Object (child) within an Object (parent). I followed what's in the documentation for serialization/deserialization group and it works. I can post and get my object with its relation.

I've got something similar to this:
```json
{
    "@context": "/app_dev.php/contexts/Contact",
    "@id": "/app_dev.php/contacts/1",
    "@type": "http://schema.org/Person",
    "address": {
        "@id": "/app_dev.php/addresses/1",
        "@type": "http://schema.org/PostalAddress",
        "addressCountry": "Some country",
        "addressLocality": "Some city",
        "postalCode": "Some code",
        "streetAddress": "Some address"
    },
    "birthDate": "1814-04-01T00:00:00+01:00",
    "email": "contact@email.com",
    "familyName": "Doe",
    "gender": "male",
    "givenName": "John"
}
```

As I don't need to access the address resource, I would like to get something like:
```json
{
    "@context": "/app_dev.php/contexts/Contact",
    "@id": "/app_dev.php/contacts/1",
    "@type": "http://schema.org/Person",
    "address": {
        "addressCountry": "Some country",
        "addressLocality": "Some city",
        "postalCode": "Some code",
        "streetAddress": "Some address"
    },
    "birthDate": "1814-04-01T00:00:00+01:00",
    "email": "contact@email.com",
    "familyName": "Doe",
    "gender": "male",
    "givenName": "John"
}
```

I've naively removed the service for my address but I've got errors.

Is there a way to achieve what I am trying to do whit api-platform?

Note: I am using v1.0.1 of api-platform and symfony v2.8.4

**Comment by teohhanhui** [comment]
Conceptually, it's not wrong to not have an IRI if you don't want to expose something as its own resource (in JSON-LD / REST terminology), but merely as part of another resource.

Practically speaking, the `@id` is necessary for retrieving the existing entity when you try to update (PUT). Otherwise new entities will be created each time.

**Comment by dunglas** [comment]
I agree with @teohhanhui, however you can use the firewall to prevent direct access to the `address` endpoint.

You can also try to use https://github.com/dunglas/doctrine-json-odm. It will work out of the box with API Platform v2 but you'll need a custom normalizer in the v1.

**Comment by aledeg** [comment]
Thanks
