### ISSUE TITLE
Does Api-platform supports GrapQL Subscriptions ?

### ISSUE THREAD

**Issue by Larzack** [api-platform/api-platform#815]
Does Api-platform supports GrapQL Subscriptions ?

**Comment by dunglas** [comment]
Not yet. But I’m working on something.

**Comment by Larzack** [comment]
@dunglas , in one of your presentations ( https://speakerdeck.com/dunglas/rest-vs-graphql-illustrated-examples-with-the-api-platform-framework?slide=31 ), you wrote that subscriptions are not supported in PHP.
- This will be supported soon or not ?
- Will APi-Platform support it natively ? Soon ?

I'm going to make an App with GraphQL and Api-Platform, but I need subscriptions for chat.
I prefer writing code in PHP but i don't know if I have to start with Api-platform and wait for Subscriptions or doing the BackEnd with NodeJS ( and I have to learn NodeJS )

Regards

**Comment by Larzack** [comment]
Just saw this : https://graphql.org/code/#php and Siler ( https://siler.leocavalcante.com/graphql/ )

**Comment by slipo** [comment]
@dunglas any update on this? Is what you're working on public? Would love to hear about where this is at and I could potentially lend a hand.

**Comment by GregoireHebert** [comment]
@Larzack @slipo As it is right now, API Platform does not handle subscriptions as you would expect.
But, as @dunglas told you, he was working on something. That something is **Mercure**. You can find more informations in it's repository https://github.com/dunglas/mercure . This is a solution that is already used in production, do not hesitate to give it a go. It's integrated with API Platform and Symfony, you can take a look at [Kevin's slides from Lisbon SymfonyCon](https://dunglas.fr/2018/12/symfonycon-slides-progressively-enhance-your-symfony-4-app-using-vue-api-platform-mercure-and-panther/)

**Comment by alanpoulain** [comment]
See: https://github.com/api-platform/core/issues/3124
