### ISSUE TITLE
Varnish "pass" if there are cookies sent

### ISSUE THREAD

**Issue by teohhanhui** [api-platform/api-platform#817]
Cookies could be from elsewhere, especially relevant for `localhost` as the user might use it for other projects too.

**Comment by dunglas** [comment]
It's intended right? It's a well known behavior of Varnish and we shouldn't change this: https://varnish-cache.org/docs/3.0/tutorial/cookies.html

**Comment by teohhanhui** [comment]
Hmm... Indeed it's tricky. I thought we could safely strip cookies since we're a stateless API, but then cookies could still be used in a stateless way (for example as a storage and transport for JWT).

**Comment by teohhanhui** [comment]
Could add a mention in the docs somewhere, perhaps?

**Comment by dunglas** [comment]
Yes, I fear it's the only reasonable thing to do.

**Comment by alanpoulain** [comment]
Varnish is not used anymore.
