### ISSUE TITLE
ERROR: Service 'api' failed to build

### ISSUE THREAD

**Issue by Mellgood** [api-platform/api-platform#819]
I'm trying to install api-platform using docker-compose but I'm getting the following error after throwing the command `docker-copose up -d`

`Step 24/27 : FROM nginx:${NGINX_VERSION}-alpine AS api_platform_nginx
1.15-alpine: Pulling from library/nginx
ERROR: Service 'api' failed to build: no matching manifest for unknown in the manifest list entries
`

Can anyone help me to figure out how to complete the installation and run api-platform, please?
I tried to search for the error on google and i found the problem may be a nginx version related problem but i have no idea how to fix it.

**Comment by daFish** [comment]
I fixed it by changing `NGINX_VERSION` to `stable`. That worked.

**Comment by Mellgood** [comment]
Where do I have to do that change?

**Comment by daFish** [comment]
Oh, sorry. You can change that in your `Dockerfile`. The variable is being initialized at the beginning of the file.

**Comment by Mellgood** [comment]
Thank you so much daFish, it solved my issue

**Comment by teohhanhui** [comment]
It's an issue with the upstream `nginx` Docker image tags...
