### ISSUE TITLE
JSON API support?

### ISSUE THREAD

**Issue by luispabon** [api-platform/api-platform#82]
Any plans to support [JSON API](http://jsonapi.org/) at all? It's not too dissimilar in philosophy to JSON-LD, although it does enforce its own routing standard.

**Comment by dunglas** [comment]
It could be added easily in [core](https://github.com/api-platform/core). It's a matter of implementing a JSON API serializer.

If you want to work on that, I can help you and I'll be pleased to merge it!

**Comment by hectorh30** [comment]
Hi there, I'm quite interested in working on this.

I've never done any open source major contribution so a little help would be very much appreciated :-) On the other hand I think I know my way around Symfony.

Since JSON-API has its own `Content-Type` I would think content negotation should determine if using a possible JSON API serializer, right?

**Comment by luispabon** [comment]
Been looking into this as I'm working on a project which reads and writes
from such an API format. The serialiser and headers should be
straightforward enough to implement; however, json API mandates a very
specific url format which at this point I'm unsure it's compatible with
what API platform is currently using. Need to check in a bit more detail.

Would be a winner to have both available at the switch of an accept header!

On Fri, 3 Jun 2016, 00:23 Hector Hurtarte, <notifications@github.com> wrote:

> Hi there, I'm quite interested in working on this.
>
> I've never done any open source major contribution so a little help would
> be very much appreciated :-) On the other hand I think I know my way around
> Symfony.
>
> Since JSON-API has its own Content-Type I would think content negotation
> should determine if using a possible JSON API serializer, right?
>
> —
> You are receiving this because you authored the thread.
>
> Reply to this email directly, view it on GitHub
> <https://github.com/api-platform/api-platform/issues/82#issuecomment-223451529>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AGF8Vx1qj4mSsBQusaiBx53H3cZjBV_0ks5qH2XfgaJpZM4IeIHM>
> .
>
-- 
Kind regards,
Luis Pabon

**Comment by dunglas** [comment]
It is possible to customize the URL format too by creating route loader based on https://github.com/api-platform/core/blob/master/src/Bridge/Symfony/Routing/ApiLoader.php

**Comment by luispabon** [comment]
👍 

Would you be in favour of integrating a third party package to provide with serialisation, or implement our own?

**Comment by dunglas** [comment]
It depends :) If an existing fit our needs and is maintained we can use it, but I doubt such library exists.

**Comment by luispabon** [comment]
There are options such as https://github.com/neomerx/json-api which we could piggyback on

**Comment by dunglas** [comment]
IMO it will be difficult to make such libraries working with the internal infrastructure of API Platform (metadata and so on). The easiest path is probably creating a normalizer for JSON API (and maybe a route loader).

**Comment by luispabon** [comment]
👍

**Comment by renz-ken** [comment]
@luispabon have you had any progress on this? We're quite keen to put some work into developing jsonapi support in the next couple of weeks so if you have started we could potentially build this further

**Comment by dunglas** [comment]
@renz-ken I think JSONAPI support can now be done more easily than before. The HAL implementation is a good example of how JSONAPI can be implemented: https://github.com/api-platform/core/tree/master/src/Hal/Serializer

I know @Simperfit (the author of the HAL support) has started to think about JSONAPI support but I don't think there is any code yet. Your contribution will be greatly appreciated!

**Comment by Simperfit** [comment]
Yup, I leak a little bit of time.

I totally agree with @dunglas, It would be easy to implement JsonApi since it is relatively close to HAL. @renz-ken If you want to work on this you could start it and I will be glad to help you on this if you want to ;).

**Comment by Simperfit** [comment]
This is in progress in api-platform/core#785, could you test it  @renz-ken  ?

**Comment by Simperfit** [comment]
JSON API has been merged 👍
