### ISSUE TITLE
Graphql testing

### ISSUE THREAD

**Issue by SkvokeN** [api-platform/api-platform#820]
Hello! Do you have examples of how to test graphql api?

**Comment by alanpoulain** [comment]
Hello. We use Behat to test the core. The tests are here:
https://github.com/api-platform/core/tree/master/features/graphql
The related context is here:
https://github.com/api-platform/core/blob/master/features/bootstrap/GraphqlContext.php
But you are free to test your API like you want :slightly_smiling_face:

**Comment by SkvokeN** [comment]
Thank you 👍
