### ISSUE TITLE
Why does api platform force an INNER JOIN?

### ISSUE THREAD

**Issue by anacicconi** [api-platform/api-platform#826]
Hello,

For some of my endpoints, I need to be able to filter in a way that the query adds a LEFT JOIN to an associated resource. However, I just noticed that Api Platform forces to always use an INNER JOIN. 

Example: the SearchFilter extends from the AbstractFilter which adds the join part using the addJoinsForNestedProperty method. As the parameter $joinType is null and the Query Builder has no joins, the joins added are always INNER. 

Even if I create my custom filter, I will also extends from the AbstractContextAwareFilter which extends from the AbstractFilter and have an INNER JOIN.

Is this on purpose? And if yes, could you tell me the reason?

Thanks!

**Comment by soyuka** [comment]
Hi! 

Policy about joins in filters should be as follow IIRC:
- association nullable
  - LEFT
- association not nullable
  - if no previous joins INNER
  - else LEFT

If this isn't the case it's a bug, please give me a way to reproduce with some entities in a gist :). 

Please note that there was a recent fix on the OrderFilter that wasn't joining properly and created such bugs (see https://github.com/api-platform/core/issues/2109): https://github.com/api-platform/core/commit/34bb2ff3aea4ecc3a002f9849e8530889f6b91ee (has landed in 2.3.1).

**Comment by anacicconi** [comment]
@soyuka my bad! I thought I had the nullable true but I had forgot it. When I added it, the left join appeared :) Thanks for your reply!

**Comment by anacicconi** [comment]
@soyuka sorry for the last reply. I did a mistake. Before you told me about the nullable, I was doing tests where I was forcing to pass the "LEFT JOIN" as a parameter to the "addJoinsForNestedProperty" method of the AbstractFilter. This made me think the nullable was the solution. Now I updated my vendors, everything is clear and I can see that the nullable does not change anything. 

I've been debugging it all morning and I think the problem is in the "addJoinsForNestedProperty" method. When the "OrderFilter" was fixed, the "$joinType" was added as a parameter. However, it is commented. Is it normal? 

Here I have a test with two entities using a ManyToOne nullable association. I added a "SearchFilter" and I get only "INNER JOINs" in the query.

```
// The entities

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Book
 *
 * @ORM\Table(name="Book")
 * @ORM\Entity
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var Author
     *
     * @ORM\ManyToOne(targetEntity="Author")
     * @ORM\JoinColumn(name="author_id", referencedColumnName="id", nullable=true)
     */
    private $author;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return Author
     */
    public function getAuthor(): Author
    {
        return $this->author;
    }

    /**
     * @param Author $author
     *
     * @return Book
     */
    public function setAuthor(Author $author): Book
    {
        $this->author = $author;
        return $this;
    }
}

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Author
 *
 * @ORM\Table(name="Author")
 * @ORM\Entity
 */
class Author
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="first_name", type="string", nullable=false)
     */
    private $firstName;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getFirstName(): string
    {
        return $this->firstName;
    }

    /**
     * @param string $firstName
     *
     * @return Author
     */
    public function setFirstName(string $firstName): Author
    {
        $this->firstName = $firstName;
        return $this;
    }
}

// The API resources

App\Entity\Author:
        collectionOperations:
            get: ~
        itemOperations:
            get: ~

App\Entity\Book:
        collectionOperations:
            get:
                filters: ['book.search_filter']
        itemOperations:
            get: ~

// The filter definition

book.search_filter:
        parent: 'api_platform.doctrine.orm.search_filter'
        arguments: [ { "author.firstName": "exact" } ]
        tags:  [ 'api_platform.filter' ]

// The query generated by API platform

SELECT 
b0_.id AS id_0, 
b0_.author_id AS author_id_1 
FROM Book b0_ 
INNER JOIN Author a1_ ON b0_.author_id = a1_.id 
WHERE b0_.id IN (
    SELECT b2_.id 
    FROM Book b2_ 
    INNER JOIN Author a3_ ON b2_.author_id = a3_.id 
    WHERE a3_.first_name = ?) 
ORDER BY b0_.id ASC LIMIT 30

**Comment by anacicconi** [comment]
Yes, I just saw the func_get_arg. Thanks ;)

Humm... I'm not sure about the filter. This means we will never get the null values. 

I did a custom filter because I needed a "or search filter": https://github.com/api-platform/api-platform/issues/639

Now, I see that I can let the front decide if it wants the "LEFT" or the "INNER" join. However, I think it's a pity to have a custom search filter doing almost exactly the same thing that the original "SearchFilter" does and I'm not sure if this is a good strategy. Do you know how people have been dealing with this case?

**Comment by teohhanhui** [comment]
> Humm... I'm not sure about the filter. This means we will never get the null values.

If you asked to filter by a property, and it doesn't match, then the item should not be in the results.

The behaviour is correct.
