### ISSUE TITLE
Disabling jsonld @id ref: No item route associated with the type

### ISSUE THREAD

**Issue by trsteel88** [api-platform/api-platform#829]
I have a entity which I do not want to show the id or @id value which comes from jsonld.

I have disabled all the itemOperations and collectionOperations as this entity will only ever show within a OneToOne relationship. It cannot be viewed on its own.

However, when I disable all the operations, when outputting the data from the I get the error "No item route associated with the type" because it can't map the @id field.

Is there a way to disable jsonld/iri on a specific resource and all the operations?

**Comment by soyuka** [comment]
Nope but I've a workaround for this which is to decorate the IriConverter: https://gist.github.com/soyuka/a7a58732792872f000a09f79741042a4. Or maybe even better in your case, decorate the ItemNormalizer.

**Comment by trsteel88** [comment]
Thanks @soyuka. I already have a denormalizer/normalizer so I used that:

```php
/**
     * @param mixed $data
     * @param null  $format
     *
     * @return bool
     */
    public function supportsNormalization($data, $format = null)
    {
        return $data instanceof File;
    }

    /**
     * @param object $object
     * @param null   $format
     * @param array  $context
     *
     * @return array|\Symfony\Component\Serializer\Normalizer\scalar
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $data = $this->decorated->normalize($object, $format, $context);

        if ($object instanceof File) {
            $data['write_token'] = '[Firebase Custom Token Here]';
            $data['read_url'] = '[Url to Download File]';

            unset($data['id']);
            unset($data['@id']);
            unset($data['@type']);
        }

        return $data;
    }
```
