### ISSUE TITLE
Normalise the url domain/#/virtual_users/%2Fvirtual_users%2F1 to remove the duplicated section?

### ISSUE THREAD

**Issue by christhomas** [api-platform/api-platform#832]
Hi,

Is there a nicer way to format the urls in the admin component so it displays in a more readable fashion?

I have an example: http://website.develop/#/virtual_users/%2Fvirtual_users%2F1
I would like to show: http://website.develop/#/virtual_users/1

I think the extra section with the url encoded data is just a bit weird and I want to remove it and let the system use that internally, but not display it externally.

Anybody know a way that I can do that?

**Comment by alanpoulain** [comment]
Since API Platform Admin is using IRIs, it's not possible.
