### ISSUE TITLE
Best way to add slug to IRI

### ISSUE THREAD

**Issue by stepotronic** [api-platform/api-platform#833]
First, I would like to thank everybody involved in api-platform. It is an amazing project and I really like it.

I would like to use the slug generation offered in the [doctrine extensions](https://symfony.com/doc/master/bundles/StofDoctrineExtensionsBundle/index.html) and make it part of the IRI. That works really well however I am stuck in adding this the IRI. I am asking here, because I believe there might be something that I can use. If you have any hints or pointers, please let me know.

```
 *     itemOperations={
 *         "get"={"method"="GET", "path"="/entity/{slug}/{id}", "requirements"={"id"="[a-f\d\-]+", "slug"="\w+"}},
 *         "put"={"method"="PUT", "path"="/entity/{slug}/{id}", "requirements"={"id"="[a-f\d\-]+", "slug"="\w+"}}
 *     }
`

Cheers,
Stepo

**Comment by mmplanet** [comment]
I have also described a similar problem [here](https://github.com/api-platform/api-platform/issues/831#issuecomment-419724623).

**Comment by soyuka** [comment]
Hi,

I think that the easiest is to decorate the IriConverter. I made an example [in this gist](https://gist.github.com/soyuka/a7a58732792872f000a09f79741042a4) for one of my use cases. Obviously you'd need to change [this guard](https://gist.github.com/soyuka/a7a58732792872f000a09f79741042a4#file-iriconverter-php-L51) and use whatever suits your needs.

**Comment by gnumoksha** [comment]
I'm wondering why one can't simply set the IRI for a given resource manually. It seems to me that API Platform tries to do a lot of magic but ignores people who prefer coding instead of magic/convention.

**Comment by gnumoksha** [comment]
I'm wondering why one can't simply set the IRI for a given resource manually. It seems to me that API Platform tries to do a lot of magic but ignores people who prefer coding instead of relying on magic or memorizing conventions.

**Comment by soyuka** [comment]
You can, just specify the iri attribute in your annotation or resource configuration
