### ISSUE TITLE
Custom Collection "GET" Method - API Platform

### ISSUE THREAD

**Issue by KilMer56** [api-platform/api-platform#834]
Hi everyone,

I have an entity that i can get with the standard get operation (collection / or id one) :

```
/**
 * Insee
 *
 * @ApiResource(
 *     collectionOperations={"get"},
 *     itemOperations={"get"},
 *     attributes={
 *     }
 * )
 * @ApiFilter(SearchFilter::class, properties={"insCode": "exact", "insLibelle": "partial"})
 * @ORM\Table(name="dif_zonages.insee", indexes={@ORM\Index(name="FK_INSEE_CANTON", columns={"CAN_CODE"})})
 * @ORM\Entity
 */
class Insee
{

    /**
     * @var string
     *
     * @ORM\Column(name="INS_CODE", type="string", length=5, nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $insCode = '';

    /**
     * @var string|null
     *
     * @ORM\Column(name="INS_LIBELLE", type="string", length=254, nullable=true)
     */
    private $insLibelle;

    /**
     * @var float|null
     *
     * @ORM\Column(name="INS_LATITUDE", type="float", precision=10, scale=0, nullable=true, options={"comment"="Latitude de la commune (coordonnées géographiques)"})
     */
    private $insLatitude;

    /**
     * @var float|null
     *
     * @ORM\Column(name="INS_LONGITUDE", type="float", precision=10, scale=0, nullable=true, options={"comment"="Longitude de la commune (coordonnées géographiques)"})
     */
    private $insLongitude;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->insdCodeSource = new \Doctrine\Common\Collections\ArrayCollection();
    }

Etc .....

    /**
     * @return float|null
     */
    public function getInsLatitude(): ?float
    {
        return $this->insLatitude;
    }

    /**
     * @param float|null $insLatitude
     */
    public function setInsLatitude(?float $insLatitude): void
    {
        $this->insLatitude = $insLatitude;
    }

    /**
     * @return float|null
     */
    public function getInsLongitude(): ?float
    {
        return $this->insLongitude;
    }

    /**
     * @param float|null $insLongitude
     */
    public function setInsLongitude(?float $insLongitude): void
    {
        $this->insLongitude = $insLongitude;
    }

}
```
However, i want to add a custom "GET"opération so i can get a list of **Insee** object from 2 parameters : latitude and longitude. Can you help me what should i use? I saw that we can create Extension but the doc is very limited so....

Thanks in advance !

**Comment by soyuka** [comment]
Check out the following documentation:
- https://api-platform.com/docs/core/operations#creating-custom-operations-and-controllers
- https://api-platform.com/docs/core/data-providers/

You should add an operation, then add a data provider and you're done :).

**Comment by simocheccoli** [comment]
I agree with @yivi, an example would be really useful.

**Comment by simocheccoli** [comment]
I don't understand if it is mandatory create a custom operation (using a custom controller) to manage the data returned from a **collectionOperations**.

I mean, i have a entity (not mapped by orm), that can be exposed by an api for a collection (static types like enums, static datas, read from other sources...) and i just create my custom data provider like that:

```
namespace App\DataProvider;

use ApiPlatform\Core\DataProvider\CollectionDataProviderInterface;
use ApiPlatform\Core\DataProvider\RestrictedDataProviderInterface;
use App\Type\MemberType;

final class MemberTypeDataProvider implements CollectionDataProviderInterface, RestrictedDataProviderInterface
{
    public function supports(string $resourceClass, string $operationName = null, array $context = []): bool
    {
        return MemberType::class === $resourceClass;
    }
    public function getCollection(string $resourceClass, string $operationName = null)
    {
       return [
           new MemberType(MemberType::SUPER_ADMIN),
           new MemberType(MemberType::ADMIN),
           new MemberType(MemberType::USER)
       ];
    }
}
```
and entity like that:

```
namespace App\Type;

use ApiPlatform\Core\Annotation\ApiProperty;
use ApiPlatform\Core\Annotation\ApiResource;
use App\Controller\MemberTypeController;

/**
 *
 * @ApiResource(
 *     collectionOperations={
 *          "get"={
 *              "method"="GET",
 *              "path"="/role-members",
 *              "controller"=MemberTypeController::class
 *          }
 *     },
 *     itemOperations={"get"},
 * )
 */
class MemberType
{

    const SUPER_ADMIN = 'SUPER_ADMIN';
    const ADMIN = 'ADMIN';
    const USER = 'USER';

    /**
     * @ApiProperty(identifier=true)
     */
    public $code;

    /**
     * MemberType constructor.
     * @param $code
     */
    public function __construct($code)
    {
        $this->code = $code;
    }
}
```
Is mandatory create a **MemberTypeController**? 
that if it's invoked, return just a collection of my entity?

```
namespace App\Controller;

use App\DataProvider\MemberTypeDataProvider;
use App\Type\MemberType;

class MemberTypeController
{

    private $memberTypeDataProvider;

    public function __construct(MemberTypeDataProvider $memberTypeDataProvider)
    {
        $this->memberTypeDataProvider = $memberTypeDataProvider;
    }

    public function __invoke($params = null)
    {
        return $this->memberTypeDataProvider->getCollection(MemberType::class);
    }
}

```
In this case, could it be possible indicate a configuration of the api configuration? like that:

```
/**
 *
 * @ApiResource(
 *     collectionOperations={
 *          "get"={
 *              "method"="GET",
 *              "path"="/role-members",
 *              "dataProvider"=MemberTypeDataProvider::class
 *          }
 *     }
 * )
 */
class MemberType
....
```

**Comment by gnutix** [comment]
Same questionning for me right now, trying to create an endpoint that returns a list of supported currencies.

**Comment by foxsdev** [comment]
> I don't understand if it is mandatory create a custom operation (using a custom controller) to manage the data returned from a **collectionOperations**.
> 
> I mean, i have a entity (not mapped by orm), that can be exposed by an api for a collection (static types like enums, static datas, read from other sources...) and i just create my custom data provider like that:
> 
> ```
> namespace App\DataProvider;
> 
> use ApiPlatform\Core\DataProvider\CollectionDataProviderInterface;
> use ApiPlatform\Core\DataProvider\RestrictedDataProviderInterface;
> use App\Type\MemberType;
> 
> final class MemberTypeDataProvider implements CollectionDataProviderInterface, RestrictedDataProviderInterface
> {
>     public function supports(string $resourceClass, string $operationName = null, array $context = []): bool
>     {
>         return MemberType::class === $resourceClass;
>     }
>     public function getCollection(string $resourceClass, string $operationName = null)
>     {
>        return [
>            new MemberType(MemberType::SUPER_ADMIN),
>            new MemberType(MemberType::ADMIN),
>            new MemberType(MemberType::USER)
>        ];
>     }
> }
> ```
> 
> and entity like that:
> 
> ```
> namespace App\Type;
> 
> use ApiPlatform\Core\Annotation\ApiProperty;
> use ApiPlatform\Core\Annotation\ApiResource;
> use App\Controller\MemberTypeController;
> 
> /**
>  *
>  * @ApiResource(
>  *     collectionOperations={
>  *          "get"={
>  *              "method"="GET",
>  *              "path"="/role-members",
>  *              "controller"=MemberTypeController::class
>  *          }
>  *     },
>  *     itemOperations={"get"},
>  * )
>  */
> class MemberType
> {
> 
>     const SUPER_ADMIN = 'SUPER_ADMIN';
>     const ADMIN = 'ADMIN';
>     const USER = 'USER';
> 
>     /**
>      * @ApiProperty(identifier=true)
>      */
>     public $code;
> 
>     /**
>      * MemberType constructor.
>      * @param $code
>      */
>     public function __construct($code)
>     {
>         $this->code = $code;
>     }
> }
> ```
> 
> Is mandatory create a **MemberTypeController**?
> that if it's invoked, return just a collection of my entity?
> 
> ```
> namespace App\Controller;
> 
> use App\DataProvider\MemberTypeDataProvider;
> use App\Type\MemberType;
> 
> class MemberTypeController
> {
> 
>     private $memberTypeDataProvider;
> 
>     public function __construct(MemberTypeDataProvider $memberTypeDataProvider)
>     {
>         $this->memberTypeDataProvider = $memberTypeDataProvider;
>     }
> 
>     public function __invoke($params = null)
>     {
>         return $this->memberTypeDataProvider->getCollection(MemberType::class);
>     }
> }
> ```
> 
> In this case, could it be possible indicate a configuration of the api configuration? like that:
> 
> ```
> /**
>  *
>  * @ApiResource(
>  *     collectionOperations={
>  *          "get"={
>  *              "method"="GET",
>  *              "path"="/role-members",
>  *              "dataProvider"=MemberTypeDataProvider::class
>  *          }
>  *     }
>  * )
>  */
> class MemberType
> ....
> ```

Using only your DataProvider and your Entity with correct annotations should be enough. I use this without creating any special controller for this entity.

**Comment by simocheccoli** [comment]
> Using only your DataProvider and your Entity with correct annotations should be enough. I use this without creating any special controller for this entity.

@foxsdev 
Any usefull example? 
I'have already try by tagging DataProvider ([custom-collection-data-provider](https://api-platform.com/docs/core/data-providers/#custom-collection-data-provider)) but it's doesn't work as expected

**Comment by darielvicedo** [comment]
I'm stuck right now with the same: how I link a custom DataProvider to a custom operation (put in my case with a controller).
Thank you guys, this is the best framework ever.

**Comment by tlarsonlgdor** [comment]
There might be a way to import a custom controller into a custom DataProvider in its constructor after it is tagged and declared as a service in service.yaml. However, I don't think Api Platform recommends using a custom controller with a custom DataProvider. I think you use one or the other. Given that, the documentation recommends using custom DataProvider over a custom controller because the prior allows you to use all the built-in extensions Api Platform has available like filtering, pagination, ordering, etc. See [Creating Custom Operations and Controllers](https://api-platform.com/docs/core/controllers/). 

Api Platform's document is lacking in this area.

Given that, it looks like a custom DataProvider is called by all the operations and is actually run when its supports function returns as true. You can use it to test when your entity class in question matches the requested class. When it returns true, it will then run its getCollection or getItem functions, which you use to add any additional functionality you need. You can add that functionality direct here or make a custom extension to add that functionality. If you want this custom DataProvider to automatically run all the custom and built in extensions, you must import them in construct, then use a for loop to go through them all. I can provide an example I got working for a custom Data Provider I used to require a filter parameter to be set on one of my collectionOperation get operations. The filter was defined as normal in the entity's annotations, then it ran automatically when the custom Data Provider's getCollection ran through all the built-in extensions. Let me know if you want me to add the code.

**Comment by Faint-fr** [comment]
@tlarsonlgdor 
Your code interests me, can you please share it ?

**Comment by tlarsonlgdor** [comment]
You can check it out [on stackoverflow here](https://stackoverflow.com/questions/55020369/filter-required-in-api-platform/58460863#58460863).
Not perfectly all of the use cases asked about above, but I got a custom data provider to enforce a filter, which might be an option to using the custom controller. The custom data provider works for a collectionOperation get call and it makes use of all the built in operation extensions for Api Platform. Custom controller probably can't do that.

**Comment by benblub** [comment]
a Custom Controller is discouraged, see https://api-platform.com/docs/core/controllers/
A DataProvider should solve the Problem https://api-platform.com/docs/core/data-providers/
A QueryCollectionExtension will do the job too.
