### ISSUE TITLE
Enum management

### ISSUE THREAD

**Issue by snoob** [api-platform/api-platform#842]
Hi,

I followed the Api Platform documentation to add enum values on an api field.
On the swagger [demo](http://petstore.swagger.io/), enum fields are validated with values and appear as a select box on /GET filter.

According to OpenApi specification (https://tools.ietf.org/html/draft-fge-json-schema-validation-00#section-5.5.1), enum can be used for validation purposes.

On ApiPlatform, if i havent' missed something, we have to override @ApiProperty and @ApiFilter swagger context to define the enum values and we have to add the validation. 

Moreover, i didn't success to use my static method (getStatusesList) on the swagger_context annotation attribute to define enum values

**Comment by teohhanhui** [comment]
Did you find a solution? It'd be good if you can share it for the benefit of others who might have the same issue. :smile:

**Comment by snoob** [comment]
You are right sorry i will share what i have found. 

Using statics methods is impossible with the current annotation system.
Concerning enums, ApiPlatform uses `ValidatorPropertyMetadataFactory` to collect every `NotBlank` constraints and set automatically the Swagger `required` property to true. 

For me, the best solution is to decorate this service to add `Choice` constraint support and bind automatically choices with Swagger `enum` property. 
I'll try to spend some time to add others validators support in ApiPlatform (maxLength, minLength, pattern...). 

There is another solution to make it works manually. First decorate `SwaggerDecorator` to add a `BookStatus` schema :

```
final class SwaggerDecorator implements NormalizerInterface
{
    /**
     * @var NormalizerInterface
     */
    private $decorated;

    /**
     * @param NormalizerInterface $decorated
     */
    public function __construct(NormalizerInterface $decorated)
    {
        $this->decorated = $decorated;
    }

    /**
     * {@inheritdoc}
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $docs['components']['schemas']['BookStatus'] = [
            'type' => 'string',
            'enum' => Book::getStatusesList(),
        ];
		/////
```
			
And reference it on your ApiRessource :

```
 /**
     * @var string
     *
     * @ApiProperty(
     *     openapiContext={"$ref": "#/components/schema/BookStatus"}
     * )
     */
	private $status
```

And voilà !

**Comment by dahse89** [comment]
Great! I really like this solution. Here same issues i was facing (just want to help people using this):
> ```
>  public function normalize($object, $format = null, array $context = [])
> ```
now required string type for format
> ```
>  /**
>   * @var string
>   *
>   * @ApiProperty(
>   *     openapiContext={"$ref": "#/components/schema/BookStatus"}
>   * )
>   */
There is a typo in the ref path, should be "schemas".
Also i was wondering there docs come from, here again the full example:
```
final class SwaggerDecorator implements NormalizerInterface
{
    /**
     * @var NormalizerInterface
     */
    private $decorated;

    /**
     * @param NormalizerInterface $decorated
     */
    public function __construct(NormalizerInterface $decorated)
    {
        $this->decorated = $decorated;
    }

    /**
     * {@inheritdoc}
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $docs = $this->decorated->normalize($object, $format, $context);
        $docs['components']['schemas']['BookStatus'] = [
            'type' => 'string',
            'enum' => Book::getStatusesList(),
        ];
		/////
```
and
```
 /**
   * @var string
   *
   * @ApiProperty(
   *     openapiContext={"$ref": "#/components/schemas/BookStatus"}
   * )
   */
   private $status
```

**Comment by Renrhaf** [comment]
Really helpful, thanks !
