### ISSUE TITLE
SearchFilter on relation / nested attribute

### ISSUE THREAD

**Issue by Lobosque** [api-platform/api-platform#843]
I'm trying to filter on a relation property, and following [ the docs ](https://api-platform.com/docs/core/filters#apifilter-annotation) I added an annotation on the property:
```
    /**
     * @Groups({"campaign:get",  "campaign:post"})
     *
     * @ApiFilter(SearchFilter::class, properties={"product.name": "ipartial"})
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\product", inversedBy="campaigns")
     * @ORM\JoinColumn(nullable=false)
     */
    private $product;
```

Then, acessing the resource at `{{url}}/api/campaigns/?product.name=CAM` return all resources, including those that do not match the search.

Am I missing anything else in order to enable the filter?

**Comment by soyuka** [comment]
I think that this should be a class annotation, not a property annotation since you specified a property.

Also, make sure to clear your cache just in case.

**Comment by Lobosque** [comment]
Hi @soyuka 

I forgot to mention but I tried both on the property and on the class. I was actually hoping my url syntax was not correct.
I tried clearing the cache with the class annotation and the property annotation and I still get everything. In fact, looking at the query generated, it doesn't add anything related to the search.

**Comment by Lobosque** [comment]
Coincidentally I have an `approved` field both on `Campaign` and `Product`.
I added the following annotation to the `Campaign` class:
```
@ApiFilter(BooleanFilter::class, properties={"approved", "product.approved"})
```
`{{url}}/api/campaigns/?approved=true` works as expected
while `{{url}}/api/campaigns/?product.approved=true` brings all results without filtering.

Are there specific conditions that the related entity needs to match in order for the filter to be taken into account?

**Comment by soyuka** [comment]
Please take a look at the sql query in the profiler to make sure that the filter reaches that part. 

```
{{url}}/api/campaigns?product.approved=true
```
Does work here and brings back campaigns having the `approved` property of the `product` relation to `true`. I have a similar example in my codebase.

You can also check (if using Hydra) that the filters show up in the `hydra:search => hydra:mapping` json node.

**Comment by Lobosque** [comment]
@soyuka the problem was appending a slash and getting a 301 redirect:
```
{{url}}/api/campaigns/?product.name=art ---> do not work
{{url}}/api/campaigns?product.name=art  ----> works
```
I only figured this out thanks to your tip about using the Hydra serialization. It looks like with the redirect, the dot get translated to an underscore somewhere:
```
    "hydra:view": {
        "@id": "/api/campaigns?product_name=art",
        "@type": "hydra:PartialCollectionView"
    },
```

While this is definitely a bug, this is probably not related to Api Platform.

**Comment by soyuka** [comment]
Nice, please close this issue when you've resolved your case. Lmk if I can be of some more assistance.

**Comment by teohhanhui** [comment]
Indeed, it's how PHP processes the query parameters. There's nothing we could do about it if the original information is lost.
