### ISSUE TITLE
TLS (HTTPS) on Kubernetes

### ISSUE THREAD

**Issue by comxd** [api-platform/api-platform#844]
About [this page](https://api-platform.com/docs/deployment/kubernetes/), my cluster working fine on Google Cloud but I'm trying to add TLS support with self-signed certificates (Let's Encrypt) without success :/

Can anyone provide working **Helm charts with HTTPS/TLS support** for exemple please? (GCE or Nginx LB `kubernetes.io/ingress.class: "gce"`/`kubernetes.io/ingress.class: "nginx"`)

**Comment by Hoxydev** [comment]
Enjoy !
https://github.com/ahmetb/gke-letsencrypt/blob/master/20-install-cert-manager.md

**Comment by comxd** [comment]
Hi @Hoxydev! I have found this useful link some hours after published my post ^^ Big thanks for our reply.
