### ISSUE TITLE
Question: best way to make api-platform and DataTables work together ?

### ISSUE THREAD

**Issue by gwenl** [api-platform/api-platform#845]
I'm trying to use a [DataTables](https://datatables.net/) component in [server-side processing mode](https://datatables.net/manual/server-side), with api-platform as a data provider. DataTables expects [a rather simple JSON response](https://datatables.net/manual/server-side#Returned-data): it's just a 2-level JSON with pagination info and a an array of key > values. Anyhow, it seems unexpectedly difficult to obtain with api-platform.

I'm wondering what's the best way of doing that ? I've considered several (convoluted) options but I think I must be missing the easy way. Any ideas ?

**Comment by soyuka** [comment]
IMO you need a custom collection normalizer because DataTables doesn't seem to support hydra/jsonld.

See those examples:
- [hydra](https://github.com/api-platform/core/tree/master/src/Hydra/Serializer)
- [hal](https://github.com/api-platform/core/tree/master/src/Hal/Serializer)

**Comment by xavirp** [comment]
We use Material Datatables with DataSources in Angular

**Comment by soyuka** [comment]
> We use Material Datatables with DataSources in Angular

Hi, and did you had to change something in the serialization? How did you do it?

On a second thought, maybe that it'd be easier to add Hydra support to the DataTables client code.

**Comment by gwenl** [comment]
Just to let you know: it seems the easiest way was to reorder the JSON response on the client side, using the **dataFilter** setting in jQuery.ajax():

```javascript
$('#mytable').DataTable({
        'serverSide': true,
        'ajax': {
            'url': '/api/my_api',
            'headers': { 'Accept': "application/ld+json" },
            'dataFilter' : function (data) {
                var json = JSON.parse(data);
                json.recordTotal = json['hydra:totalItems'];
                json.recordsFiltered = json['hydra:totalItems'];
                json.data = json['hydra:member'];

                return JSON.stringify(json);
            }
        }
);
```

This means converting the JSON back to an object and then to a string again, though, but it works.
