### ISSUE TITLE
Automatically assign user to Object (OneToMany)

### ISSUE THREAD

**Issue by wildcard27** [api-platform/api-platform#846]
I'm pretty disapointed that there is no documentation around this as user-assignment must be a very common thing. Here is my scenario:

I have an `Article` entity. Each Article has an owner (a `User`). A user can own many articles. The user can post an article over the API.

I want to have the `user_id` column for the article set automatically based on the Bearer token (I am using JWT auth).

I cannot find any documentation anywhere on how to do this. Can someone please help with how to achieve this?

**Comment by antograssiot** [comment]
That'a not api-platform related but I guess that you can use Blameable form [DoctrineExtension](https://symfony.com/doc/master/bundles/StofDoctrineExtensionsBundle/index.html) for this.

**Comment by soyuka** [comment]
I see two solutions without using doctrine:

1. Implement a DataPersister, trade-off is that there is one persister per entity and we can't chain them 
2. Implement a PRE_WRITE listener (see https://api-platform.com/docs/core/events/#the-event-system), you could use the same listener for every class implementing an interface (say `BlameableInterface`) :).

Getting the user is as simple as injecting the `Symfony\Component\Security\Core\Authentication\Token\Storage\TokenStorageInterface`:

```
        $token = $this->tokenStorage->getToken();

        if (!$token) {
            throw new TokenNotFoundException();
        }

        $user = $token->getUser();

        if (!($user instanceof User)) {
            throw new AccessDeniedException();
        }
```

**Comment by maxhelias** [comment]
You can use a Voter like this : https://medium.com/@galopintitouan/using-symfony-security-voters-to-check-user-permissions-with-ease-9a48e2d45540
