### ISSUE TITLE
[Question] how to format dates with the DateTimeNormalizer?

### ISSUE THREAD

**Issue by aledeg** [api-platform/api-platform#85]
I'd like to use the new DateTimeNormalizer but I have no idea how to use that. I search the web but the information is scarce.

Do I need to pass some kind of attribute in the ApiProperty annotation? I tried that without success but I might be using the wrong attribute.
Do I need to implement my own normalizer for my date fields?

**Comment by aledeg** [comment]
I found out how to use the datetime normalizer:
```php
/**
 * @ApiResource(
 * attributes={
 *     "normalization_context"={
 *         "groups"={"group1"},
 *         "datetime_format" = "Y-m-d"
 *     }
 * }
 * )
 */
class MyEntity
{
...
    /**
     * @ORM\Column(type="date")
     */
    private $dateOfBirth;
....
    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;
....
}
```

Now all my dates are formatted with the selected format. But that's not exactly what I need!
How do I format my dates with different formats?
In my case, I want to use the default format for ```createdAt``` and the inputed format for ```dateOfBirth```.

**Comment by teohhanhui** [comment]
See api-platform/core#482
