### ISSUE TITLE
varnish configuration in kubernetes can work?

### ISSUE THREAD

**Issue by mmeloni** [api-platform/api-platform#851]
I'm try to understand how api-platform varnish configuration can works inside a kubernetes cluster.
```
# Hosts allowed to send BAN requests
acl invalidators {
  "localhost";
  "php";
}
```
To accomplish that is mandatory that from a pod A managed in to the service PHP is call the service VARNISH. In the request (received in pod B) is preserved the IP of the service PHP not the IP of the pod A.

But this is impossible due the fact that networking kubernetes model is based on these rules:

all containers can communicate with all other containers without NAT
all nodes can communicate with all containers (and vice-versa) without NAT
the IP that a container sees itself as is the same IP that others see it as

I think it's better to use https://kubernetes.io/docs/concepts/services-networking/network-policies/ and not to rely to a ip-based whitelist in the varnish vcl config.

I'm wrong?

**Comment by Neirda24** [comment]
@mmeloni : Did you succeed ? Because just using the networking policy does not seems to allow us to restrict the `BAN` to an IP or a pod.

**Comment by dunglas** [comment]
@mmeloni you're totally, right. We're in the process of upgrading the chart. The demo has already be patched some time ago, but the fix hasn't been backported yet.
Here is it: https://github.com/api-platform/demo/blob/master/api/docker/varnish/conf/default.vcl#L22-L25

**Comment by alanpoulain** [comment]
We are not using Varnish anymore.

**Comment by yukccy** [comment]
> 

According to the current docs from [here](https://api-platform.com/docs/core/performance/), it stated that Varnish is included in the docker setup provided. Do you mean api-platform is not using Varnish only on kubernetes setup anymore? Is there any replacement for Varnish on kubernetes setup?
