### ISSUE TITLE
Best way to return result after a long job

### ISSUE THREAD

**Issue by MatthD** [api-platform/api-platform#862]
Hello,

I am using api-platform,
One route is doing a long job :calling n other api, then returning the result .

I was thinking about the best way to return the result ? Is it possible to do it asynchronously (I am calling n  externals api [a,b,c] but it's not a problem if "c" answer first & I would like to return some result to my front  )
What is the best way to think about it ? returning the result on the fly ? with some special status-code ? using queue jobs ?
I think sockets could not be used in this case because the api is an HTTP api.

Thanks for advises

**Comment by teohhanhui** [comment]
You can return HTTP 202 status code: https://tools.ietf.org/html/rfc7231#section-6.3.3

> 6.3.3.  202 Accepted
>
>    The 202 (Accepted) status code indicates that the request has been
>    accepted for processing, but the processing has not been completed.
>    The request might or might not eventually be acted upon, as it might
>    be disallowed when processing actually takes place.  There is no
>    facility in HTTP for re-sending a status code from an asynchronous
>    operation.
>
>    The 202 response is intentionally noncommittal.  Its purpose is to
>    allow a server to accept a request for some other process (perhaps a
>    batch-oriented process that is only run once per day) without
>    requiring that the user agent's connection to the server persist
>    until the process is completed.  The representation sent with this
>    response ought to describe the request's current status and point to
>    (or embed) a status monitor that can provide the user with an
>    estimate of when the request will be fulfilled.

**Comment by dunglas** [comment]
You could also been interested in Mercure: https://mercure.rocks
Mercure is being integrated in API Platform, see https://github.com/api-platform/core/pull/2282
