### ISSUE TITLE
Swagger Export Command to YAML broken? [BUG]

### ISSUE THREAD

**Issue by farazive** [api-platform/api-platform#865]
When running `bin/console api:swagger:export` it prints out

```
{
    "swagger": "2.0",
    "basePath": "\/",
    "info": {
        "title": "",
        "version": "0.0.0"
    },
    "paths": {
        "\/api\/books": {
            "get": {
                "tags": [
                    "Book"
                ],
    ....
```

When running the command `bin/console api:swagger:export -y` we get
```
swagger: '2.0'
basePath: /
info:
    title: ''
    version: 0.0.0
paths: null
definitions: null
```

Is there something I'm missing?

**Comment by antograssiot** [comment]
@farazive would you mind trying https://github.com/api-platform/core/pull/2256 and giving us feedback. It should do the trick, thanks by advance

**Comment by soyuka** [comment]
cool thanks @antograssiot
