### ISSUE TITLE
ERROR: Service 'php' failed to build: 

### ISSUE THREAD

**Issue by mozgbrasil** [api-platform/api-platform#867]
Good Morning

See the errors in attempting to use the application

![captura de tela de 2018-10-17 16-01-02](https://user-images.githubusercontent.com/17202780/47110004-1a803480-d226-11e8-8685-3c0862e1ea96.png)
![captura de tela de 2018-10-17 16-01-14](https://user-images.githubusercontent.com/17202780/47110005-1a803480-d226-11e8-82a3-1fcc809aa464.png)
![captura de tela de 2018-10-17 16-01-19](https://user-images.githubusercontent.com/17202780/47110007-1b18cb00-d226-11e8-85c1-bb5020e11238.png)
![captura de tela de 2018-10-17 16-01-27](https://user-images.githubusercontent.com/17202780/47110008-1b18cb00-d226-11e8-846c-63cd339e3ff9.png)
![captura de tela de 2018-10-17 16-01-32](https://user-images.githubusercontent.com/17202780/47110009-1b18cb00-d226-11e8-9635-fabd358a6b79.png)

**Comment by teohhanhui** [comment]
The actual error is here:

```
ERROR: Failed to create /usr/lib/libc.a: I/O error
ERROR: musl-dev-1.1.19-r10: IO ERROR
```

Anyway, it seems like a problem on your machine. Did you run out of disk space?

(It'd be better next time if you copy and paste the text in a code block, or as a GitHub Gist. Cheers.)
