### ISSUE TITLE
Warning : typing ObjectManager for entityManager is incorrect in filter documentation ? 

### ISSUE THREAD

**Issue by Miniplop** [api-platform/api-platform#871]
Hello,

I followed the documentation about [filters](https://api-platform.com/docs/core/filters)

And when I used PHPStan on my project, I found a weird typing on the documentation example.

In the documentation, we use ObjectManager for $em, but we call the getFilters() method which is not declared in this interface. I found the EntityManagerInterface which declares this method and extends ObjectManager.

Did I miss something ? Or should we fix it ?

Here the documentation : 
```
final class UserFilterConfigurator
{
    private $em;
    private $tokenStorage;
    private $reader;

    public function __construct(ObjectManager $em, TokenStorageInterface $tokenStorage, Reader $reader)
    {
        $this->em = $em;
        $this->tokenStorage = $tokenStorage;
        $this->reader = $reader;
    }

    public function onKernelRequest(): void
    {
        if (!$user = $this->getUser()) {
            throw new \RuntimeException('There is no authenticated user.');
        }

        $filter = $this->em->getFilters()->enable('user_filter');
        $filter->setParameter('id', $user->getId());
        $filter->setAnnotationReader($this->reader);
    }
```

**Comment by dunglas** [comment]
You're right, this should be fixed. Would you mind opening a PR?
Thanks for reporting!

**Comment by mBbkr** [comment]
I'm sorry but it does'nt work with EntityManagerInteface but works with ObjectManager. I've just lost 3h to figure out this issue due to this change...

Error log with EntityManagerInterface :
Cannot autowire service "App\EventListener\UserFilterConfigurator": argument "$em" of method "__construct()" has type "Doctrine\Orm\EntityManagerInterface" but this class was not found.

**Comment by martingtheodo** [comment]
Which implementation of ObjectManager do you use in your project ?
We will check on our project
