### ISSUE TITLE
/api/.env changes are not being picked up

### ISSUE THREAD

**Issue by mudahater** [api-platform/api-platform#874]
Changes in .env file are not being parsed even after deleting cache

**Comment by mudahater** [comment]
@dunglas Thank you.  Seems like "APP_DEBUG"  is also not parsed.

**Comment by teohhanhui** [comment]
```shell
docker-compose down php
docker-compose up php
```

**Comment by mudahater** [comment]
@teohhanhui Yes, just making sure that is how it's supposed to be.

**Comment by acassan** [comment]
You can also remove the load of .env file in docker compose configuration and use dotenv in development
With this you can avoid restarting container or use env var with phpunit
