### ISSUE TITLE
HTTPS api entrypoint returns HTTP @vocab ?

### ISSUE THREAD

**Issue by danyPatient** [api-platform/api-platform#875]
After migrating to Symfony 4.1.6 (Api Platform 2.1 to 2.3.3), when I'm in HTTPS and my API calls the following url : https://api-test/docs.jsonld

→ the value of the `@vocab` data is in http : http://api-test/docs.jsonld 

I can not access the admin anymore, because I have the following error : Blocking active mixed content «http://api-test/docs.jsonld» 

Would anyone have any idea where this HTTPS / HTTP error came from?

**Comment by dunglas** [comment]
It looks like a trusted proxies related issue: https://symfony.com/doc/current/deployment/proxies.html

**Comment by danyPatient** [comment]
Thank you Kevin !! : )
