### ISSUE TITLE
[Question] How to verify that an entity exists

### ISSUE THREAD

**Issue by aledeg** [api-platform/api-platform#88]
I have the following entities (stripped to the bare minimum):
```php
/**
 * @ORM\Entity
 * @ORM\Table
 * @ApiResource
 */
class Package
{

    /**
     * @ORM\Column(type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @ORM\Column(nullable=true)
     */
    private $description;

    /**
     * @ORM\Column()
     */
    private $name;

    /**
     * @ORM\OneToMany(targetEntity="PackageElement", mappedBy="package")
     * @ORM\JoinColumn(name="id", referencedColumnName="packageId")
     */
    private $packageElements;

}
```
```php
/**
 * @ORM\Entity
 * @ORM\Table
 * @ApiResource
 */
class PackageElement
{

    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="Package", inversedBy="packageElements")
     * @ORM\JoinColumn(name="packageId", referencedColumnName="id")
     */
    private $package;

    /**
     * @ORM\Column(type="integer")
     */
    private $quantity;

}
```
When I am posting data for the ```PackageElement``` resource with a package *iri* pointing to a nonexistant resource, I receive a 500 HTTP status code with the following error message:

> Entity of type 'Package' for IDs id(xxx) was not found

I found that api-platform creates proxy object for doctrine entities even though they are nonexisting.

I found that I can force api-platform to retrieve the real object instead of the proxy in ```ApiPlatform\Core\JsonLd\Serializer\ItemNormalizer::denormalizeRelation``` method:
```php
// Original method
private function denormalizeRelation(string $resourceClass, string $attributeName, PropertyMetadata $propertyMetadata, string $className, $value, array $context)
{
    if (is_string($value)) {
        try {
            return $this->iriConverter->getItemFromIri($value);
        } catch (InvalidArgumentException $e) {
            // Give a change to other normalizers (e.g.: DateTimeNormalizer)
        }
    }
...
```
```php
// Modified method
private function denormalizeRelation(string $resourceClass, string $attributeName, PropertyMetadata $propertyMetadata, string $className, $value, array $context)
{
    if (is_string($value)) {
        try {
            return $this->iriConverter->getItemFromIri($value, true);
        } catch (InvalidArgumentException $e) {
            // Give a change to other normalizers (e.g.: DateTimeNormalizer)
        }
    }
...
```
With the modified version, I receive a 400 HTTP status with the following message:

> Expected IRI or nested object for attribute "package" of "PackageElement", "string" given.

Is there a way to override that in a clean way? If so, how?
Could it be possible to configure that in the ```ApiProperty``` annotation? If so, I will open an other ticket for a feature request.

**Comment by theofidry** [comment]
>When I am posting data for the PackageElement resource with a package iri pointing to a nonexistant resource, I receive a 500 HTTP status code with the following error message:

>Entity of type 'Package' for IDs id(xxx) was not found

That doesn't sound right, if the form is invalid you should get a `400` not a `500`.

**Comment by aledeg** [comment]
The thing is that the form is valid since it holds a proxy of an entity. The problems comes when persisting the relation.

Here is what I have in my log file it it's any help

> Uncaught PHP Exception Doctrine\ORM\EntityNotFoundException

**Comment by theofidry** [comment]
>The thing is that the form is valid

Point is it should not. Not saying it's your fault or you did something from, but that's an abnormal behaviour and is the reason of your bug.

**Comment by aledeg** [comment]
So what should we do?
Do you need info to see what's going on?

**Comment by theofidry** [comment]
That's something that should be fixed and tested in https://github.com/api-platform/core; I can't work on it right now however :/

**Comment by theofidry** [comment]
Closing in favour of https://github.com/api-platform/core/issues/549
