### ISSUE TITLE
Project without symfony/flex

### ISSUE THREAD

**Issue by franbenz** [api-platform/api-platform#885]
Is it advisable to use api-platform v2.1 for a project with no flex?
Looking at v2.1 documentation, it seems that was the last version that supported a no flex project.
Thanks!

**Comment by antograssiot** [comment]
you can perfectly use api-platform/core 2.3 without flex, you just need to configure it.
I have app what were developed before flex and that works without issue with latest api-platform.

**Comment by franbenz** [comment]
I read the current documentation and the steps there assume a flex project.
Am I missing something?

**Comment by tezvi** [comment]
You can use any bundle without flex support. Flex is basically a composer plugin that installs bundles using recipes and does some extra configuration. It's definitely a powerful an handy tool though.
We are not using it because our development is behind a very strict corporate firewall that blocks symfony.sh

**Comment by elpoutro** [comment]
(For Symfony2/3)
1) Use this package with composer:
`composer require api-platform/core`

2) Configure the bundle manually in AppKernel.php:
`$bundles = [`
`        // [...]`
`        new ApiPlatform\Core\Bridge\Symfony\Bundle\ApiPlatformBundle(),`
` ];`

3) Add this in your app/config/routing.yml
`api:`
`    resource: '.'`
`    type:     'api_platform'`
`    prefix:   '/api' # Optional`

4) If needed, add your specific configuration in app/config/config.yml
`api_platform:`
`    title: 'specific name'`
(complete configuration [here](https://api-platform.com/docs/core/configuration/))

I hope it will help.

**Comment by crmpicco** [comment]
> (For Symfony2/3)
> 
>     1. Use this package with composer:
>        `composer require api-platform/core`
> 
>     2. Configure the bundle manually in AppKernel.php:
>        `$bundles = [`
>        `        // [...]`
>        `        new ApiPlatform\Core\Bridge\Symfony\Bundle\ApiPlatformBundle(),`
>        ` ];`
> 
>     3. Add this in your app/config/routing.yml
>        `api:`
>        `    resource: '.'`
>        `    type:     'api_platform'`
>        `    prefix:   '/api' # Optional`
> 
>     4. If needed, add your specific configuration in app/config/config.yml
>        `api_platform:`
>        `    title: 'specific name'`
>        (complete configuration [here](https://api-platform.com/docs/core/configuration/))
> 
> 
> I hope it will help.

Thanks for providing this. What version of Symfony were you/are you on and were you restricted to the version of API platform?

**Comment by CocoJr** [comment]
Trying to do the same with symfony 3.4.21 project, result in composer error when trying `composer require api-platform/core`:  
  

> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Conclusion: don't install api-platform/core v2.4.3
>     - Conclusion: don't install api-platform/core v2.4.2
>     - Conclusion: don't install api-platform/core v2.4.1
>     - Conclusion: remove symfony/symfony v3.4.21
>     - Installation request for api-platform/core ^2.4 -> satisfiable by api-platform/core[v2.4.0, v2.4.1, v2.4.2, v2.4.3].
>     - Conclusion: don't install symfony/symfony v3.4.21
>     - api-platform/core v2.4.0 requires symfony/web-link ^4.1 -> satisfiable by symfony/web-link[v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.1, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8].
>     - don't install symfony/web-link v4.1.0|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.1.1|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.1.10|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.1.11|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.1.12|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.1.2|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.1.3|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.1.4|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.1.5|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.1.6|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.1.7|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.1.8|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.1.9|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.2.0|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.2.1|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.2.2|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.2.3|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.2.4|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.2.5|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.2.6|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.2.7|don't install symfony/symfony v3.4.21
>     - don't install symfony/web-link v4.2.8|don't install symfony/symfony v3.4.21
>     - Installation request for symfony/symfony 3.4.21 -> satisfiable by symfony/symfony[v3.4.21].

**Comment by crmpicco** [comment]
> Trying to do the same with symfony 3.4.21 project, result in composer error when trying `composer require api-platform/core`:
> 
> > Your requirements could not be resolved to an installable set of packages.
> > Problem 1
> > - Conclusion: don't install api-platform/core v2.4.3
> > - Conclusion: don't install api-platform/core v2.4.2
> > - Conclusion: don't install api-platform/core v2.4.1
> > - Conclusion: remove symfony/symfony v3.4.21
> > - Installation request for api-platform/core ^2.4 -> satisfiable by api-platform/core[v2.4.0, v2.4.1, v2.4.2, v2.4.3].
> > - Conclusion: don't install symfony/symfony v3.4.21
> > - api-platform/core v2.4.0 requires symfony/web-link ^4.1 -> satisfiable by symfony/web-link[v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.1, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8].
> > - don't install symfony/web-link v4.1.0|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.1.1|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.1.10|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.1.11|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.1.12|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.1.2|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.1.3|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.1.4|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.1.5|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.1.6|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.1.7|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.1.8|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.1.9|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.2.0|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.2.1|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.2.2|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.2.3|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.2.4|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.2.5|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.2.6|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.2.7|don't install symfony/symfony v3.4.21
> > - don't install symfony/web-link v4.2.8|don't install symfony/symfony v3.4.21
> > - Installation request for symfony/symfony 3.4.21 -> satisfiable by symfony/symfony[v3.4.21].

Hmmm, it looks like it is reliant on Symfony 4 now. Can @dunglas confirm how compatible API Platform is with a Symfony 3.4 LTS project?

**Comment by crmpicco** [comment]
I had a similar outcome attempting to install API Platform 2.4 on my Symfony 3.4.27 installation.

> Using version ^2.4 for api-platform/core                       
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)                  
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Conclusion: remove symfony/symfony v3.4.27
>     - Conclusion: don't install symfony/symfony v3.4.27
>     - api-platform/core v2.4.0 requires symfony/web-link ^4.1 -> satisfiable by symfony/web-link[v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.1, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8].
>     - api-platform/core v2.4.1 requires symfony/web-link ^4.1 -> satisfiable by symfony/web-link[v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.1, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8].
>     - api-platform/core v2.4.2 requires symfony/web-link ^4.1 -> satisfiable by symfony/web-link[v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.1, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8].
>     - api-platform/core v2.4.3 requires symfony/web-link ^4.1 -> satisfiable by symfony/web-link[v4.1.0, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.1, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8].
>     - don't install symfony/web-link v4.1.0|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.1.1|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.1.10|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.1.11|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.1.12|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.1.2|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.1.3|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.1.4|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.1.5|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.1.6|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.1.7|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.1.8|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.1.9|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.2.0|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.2.1|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.2.2|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.2.3|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.2.4|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.2.5|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.2.6|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.2.7|don't install symfony/symfony v3.4.27
>     - don't install symfony/web-link v4.2.8|don't install symfony/symfony v3.4.27
>     - Installation request for symfony/symfony (locked at v3.4.27, required as 3.4.*) -> satisfiable by symfony/symfony[v3.4.27].
>     - Installation request for api-platform/core ^2.4 -> satisfiable by api-platform/core[v2.4.0, v2.4.1, v2.4.2, v2.4.3].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

**Comment by CocoJr** [comment]
I check all dependencies and i found the API Platform need  `symfony/web-link` in version 4 wich require `symfonny/http-kernel` in version 4.1 wich is not compatible with the symfony 3.4 distribution.  
We can use API-Platform in version 2.2 max for now.

**Comment by CocoJr** [comment]
This is due to the require of  `symfony/http-link` in version 4 instead of version 3.4. It is possible to downgrade this dependencies to 3.4 ? Or the version 4 is mandatory ?

**Comment by teohhanhui** [comment]
It's normal. If you want to use `symfony/symfony`, you must use the version that satisfies our minimum version requirements for all components. While it's possible to use some individual components at higher versions while still using a lower version of `symfony/symfony`, the setup is more complicated and I'd not really advise that.

**Comment by teohhanhui** [comment]
It's better if you require the components separately. You are not forced to use Symfony Flex as that's not really related.

**Comment by CocoJr** [comment]
@teohhanhui thx for your answer.  

You have a requirement for `symfony/http-kernel: ^3.4|^4.0` and `symfony/web-link: ^4.1`, but together is not possible. In this case, can u update the requirement for `symfony/http-kernel` to `4.3` (in the require-dev maybe?) to match the requirement of `symfony/web-link: ^4.1` ?

**Comment by teohhanhui** [comment]
As I said, it's possible to use different versions for different Symfony components. You just need to stop requiring `symfony/symfony` package. Cheers. :smile:

**Comment by teohhanhui** [comment]
Uhh, okay, I see what you mean now. It's because of version constraints in Symfony packages. It's okay, I think we don't need to worry about that. That's exactly why each package has its own version constraints. It's already taken care of.

**Comment by CocoJr** [comment]
I'm sorry, but i didn't see how to install my 3.4 symfony component with only the web-link in 4 like your requirement suggest in packagist:  
  
Your requirement:
```
requires:
  symfony/http-kernel: ^3.4 || ^4.0
  symfony/web-link: ^4.1
```

The symfony/web-link requirement in 4.1:
```
requires (dev):
  symfony/http-kernel: ^4.3
```

So in this case i think you need to restrict the htt-kernel to v4.3 if you want the compatibilities, no ?

**Comment by aleksandr-shch** [comment]
> (For Symfony2/3)
> 
> 1. Use this package with composer:
>    `composer require api-platform/core`
> 2. Configure the bundle manually in AppKernel.php:
>    `$bundles = [`
>    `        // [...]`
>    `        new ApiPlatform\Core\Bridge\Symfony\Bundle\ApiPlatformBundle(),`
>    ` ];`
> 3. Add this in your app/config/routing.yml
>    `api:`
>    `    resource: '.'`
>    `    type:     'api_platform'`
>    `    prefix:   '/api' # Optional`
> 4. If needed, add your specific configuration in app/config/config.yml
>    `api_platform:`
>    `    title: 'specific name'`
>    (complete configuration [here](https://api-platform.com/docs/core/configuration/))
> 
> I hope it will help.

hallelujah!

**Comment by npmhieu** [comment]
Can use api ver 2.2, just include api pack version 1.2, it will auto install api platform 2.2
This is my composer.json

`"require": {
        "php": ">=7.1",
        "api-platform/api-pack": "^1.2",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/orm": "^2.5",
        "incenteev/composer-parameter-handler": "^2.0",
        "knplabs/knp-snappy-bundle": "^1.6",
        "lexik/jwt-authentication-bundle": "^2.5",
        "nelmio/cors-bundle": "^1.4",
        "nesbot/carbon": "^1.39",
        "paypal/paypal-checkout-sdk": "^1.0",
        "php-amqplib/php-amqplib": "^2.8",
        "ramsey/uuid": "^3.8",
        "sensio/distribution-bundle": "^5.0.19",
        "sensio/framework-extra-bundle": "^5.0.0",
        "sentry/sentry-symfony": "^3.2",
        "symfony/monolog-bundle": "^3.1.0",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/swiftmailer-bundle": "^2.6.4",
        "symfony/symfony": "3.4.*",
        "twig/twig": "^1.0||^2.0",
        "vich/uploader-bundle": "^1.8"
    },`

**Comment by benjaminrau** [comment]
@teohhanhui @CocoJr I followed your conversation and face the same issue. We have an old project and want to update to symfony/symfony 3.4 and api-platform/core ^2.4.

How did you resolve the conflict in version constraints within api-platform/core composer.json?

Thanks for any hints!

**Comment by benjaminrau** [comment]
@teohhanhui @CocoJr We face the same issue. But i think the reason is another one than the above mentioned one. symfony/symfony lists symfony/web-link in replace section in composer.json with self.version (3.4).

In api-platform/core symfony/web-link is required with version ^4.1. 

Would this break the replace functionality in composer? I am not very experience with composer - so just "guessing".
