### ISSUE TITLE
Correct way to get DateTime serialized in GraphQL

### ISSUE THREAD

**Issue by christoph-hautzinger** [api-platform/api-platform#887]
What ist the correct way to serialize DateTime fields in GraphQL?

My generated Type schema looks like this:

    type Airport implements Node {
      id: ID!
      _id: Int! @deprecated
      abbr: String! @deprecated
      name: String! @deprecated
      createdAt: String! @deprecated
      updatedAt: String! @deprecated
    }

so the datetime fields (createdAt and updatedAt) are considered to be from the type "String" bon on serializing, i receive 

```
query {
  airport(id: "/api/airports/1") {
    createdAt
  }
}
```

```
{
  "errors": [
    {
      "debugMessage": "String cannot represent non scalar value: array(0)",
      "message": "Internal server error",
      "category": "internal",
      "locations": [
        {
          "line": 30,
          "column": 5
        }
      ],
      "path": [
        "airport",
        "createdAt"
      ]
    }
  ],
  "data": {
    "airport": null
  }
}
```

Is there a way to change "String" to "DateTime" in the schema definition? And how to tell my model about this? :-)

**Comment by christoph-hautzinger** [comment]
funny... always hitting my own questions again on api platform related questions

**Comment by epourail** [comment]
Did you get any response ?

**Comment by alanpoulain** [comment]
There has been a first step to add a custom type: https://github.com/api-platform/core/pull/2492.
I need to document it though and to add a way to register a "converter".
See also: https://github.com/webonyx/graphql-php/issues/228. Maybe you don't need to use a DateTime type.

**Comment by alanpoulain** [comment]
Custom types can now be added if necessary: https://api-platform.com/docs/master/core/graphql/#custom-types
