### ISSUE TITLE
Untrusted host while running with url different than localhost

### ISSUE THREAD

**Issue by kniziol** [api-platform/api-platform#897]
## Environment
* Docker for Mac 18.06.1-ce-mac73
* macOS High Sierra

## Steps to reproduce
1. Install API Platform as described here: https://api-platform.com/docs/distribution#installing-the-framework (download package & run `docker-compose up -d`)
2. Open `https://localhost` in browser. It works.
3. (problem starts here) Add `127.0.0.1    myproject.dev` to `/etc/hosts`
4. ~~Edit `src/Welcome.js` and replace `localhost` with `myproject.dev`~~ (not required nowadays, *2019-07-03, kniziol*)
5. Open `http://myproject.dev` in browser. It works.
6. Click any link in first/left box of `AVAILABLE SERVICES` section (`API` or `CACHED API`)
7. You will see the `Untrusted host` exception:

<img width="1178" alt="Untrusted host exception" src="https://user-images.githubusercontent.com/947620/60623117-2fb3e800-9de2-11e9-8b9e-13287f60fe5d.png">

8. Open `api/.env`
9. Add `myproject.dev` to `TRUSTED_HOSTS` (before: `localhost,api`, after: `localhost,api,myproject.dev`)
10.  Go to step `6`. Doesn't work.
11. Clear cache & restart all containers by running `docker-compose exec php bin/console c:c && docker-compose restart`. Doesn't work.
12. In `api/public/index.php:31` value of `$_SERVER['TRUSTED_HOSTS']` is still `localhost,api`, but it should be `localhost,api,myproject.dev`.

## Solution
1. Open `api/config/packages/framework.yaml`
2. Add `framework.trusted_hosts` parameter:
```
framework:
    secret: '%env(APP_SECRET)%'
    trusted_hosts:
        - localhost
        - api
        - myproject.dev
```
3. Click any link in first/left box of `AVAILABLE SERVICES` section (`API` or `CACHED API`)
4. It works.

## Problem
Host added to `TRUSTED_HOSTS` is not included.

**Comment by kniziol** [comment]
@dunglas Problem is not solved still.

Why I did:
1. Add `myproject.dev` to `TRUSTED_HOSTS` (before: `localhost,api`, after: `localhost,api,myproject.dev`)
2. `docker-compose restart`
3. `docker-compose stop && docker-compose start`
4. Quit Docker. Start Docker. `docker-compose start`.

None of above was helpful. Any other solutions?

**Comment by ghanbari** [comment]
@kniziol i had the same problem, you can change `public/index.php` and set proxies in it, i replace values in php `entrypoint.sh`:

```
        sed -i.bak 's/\^ Request::HEADER_X_FORWARDED_HOST//' public/index.php
        sed -i.bak "s;explode(',', \$trustedProxies);['10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/20', '127.0.0.1/20'];" public/index.php
```

**Comment by kniziol** [comment]
@ghanbari Sorry, doesn't work

**Comment by botnyx** [comment]
i can confirm, got the exact same problem/behaviour as @kniziol

**Comment by stepotronic** [comment]
Also needed to manually add them to framework after upgrading.

**Comment by dunglas** [comment]
It’s not a bug, it’s perfectly intended (and necessary for security reasons). By default only the host “localhost” is whitelisted. Custom domains must be whitelisted manually. 
However it could be nice to add a docs entry about that.

**Comment by teohhanhui** [comment]
@botnyx @stepotronic Can you elaborate? The API Platform distribution already comes with Symfony DotEnv component now, so if you set `TRUSTED_HOSTS` in `.env.local`, it should get picked up.

**Comment by kniziol** [comment]
# Solution

Domains should be separated by `|` (not by `,`).

#### Incorrect

```bash
TRUSTED_HOSTS='^localhost,api,myproject.dev$'
```

#### Correct

```bash
TRUSTED_HOSTS='^localhost|api|myproject.dev$'
```

<img width="1178" alt="Zrzut ekranu 2019-07-18 o 14 37 42" src="https://user-images.githubusercontent.com/947620/61457917-ab2ca200-a969-11e9-8b13-b316c9d7468f.png">

@teohhanhui @dunglas Problem solved. Thanks.

**Comment by treadmillian** [comment]
I get this issue, not when viewing the site or API, but when trying view the Symfony Profiler from the web debug toolbar;

This is the Stack Trace;

```
wig\Error\RuntimeError:
An exception has been thrown during the rendering of a template ("Untrusted Host "localhost".").

  at vendor/symfony/web-profiler-bundle/Resources/views/Profiler/layout.html.twig:111
  at Twig\Template->displayBlock()
     (var/cache/dev/twig/bf/bf12d20c267291994bfc0d5a4b846de275078686a9fccb5f5b0fd626ae1d0c88.php:76)
  at __TwigTemplate_9102b89c893e179c91ea85832b18f46998eea5494cd633f70b4cdd3e29ce6a17->doDisplay()
     (vendor/twig/twig/src/Template.php:405)
  at Twig\Template->displayWithErrorHandling()
     (vendor/twig/twig/src/Template.php:378)
  at Twig\Template->display()
     (var/cache/dev/twig/10/104477248445284e8d32cc7eefe233df929fb6d50050bcb9876c2e0a9f72a4bd.php:50)
  at __TwigTemplate_05509a347546813a6b94f12d615ba9543a7d7d8691d677c374ac16aac863a105->doDisplay()
     (vendor/twig/twig/src/Template.php:405)
  at Twig\Template->displayWithErrorHandling()
     (vendor/twig/twig/src/Template.php:378)
  at Twig\Template->display()
     (var/cache/dev/twig/6f/6f02f7ba6d86e2b9ca1bcb4ede44b100df6ea6f17e6e55fe4e11fb4bb62b8f54.php:50)
  at __TwigTemplate_829a4f5e0b60e96f12de1e08e8917f34f9c166d6e6a46d4986b0ad51984afdf2->doDisplay()
     (vendor/twig/twig/src/Template.php:405)
  at Twig\Template->displayWithErrorHandling()
     (vendor/twig/twig/src/Template.php:378)
  at Twig\Template->display()
     (vendor/twig/twig/src/Template.php:390)
  at Twig\Template->render()
     (vendor/twig/twig/src/TemplateWrapper.php:45)
  at Twig\TemplateWrapper->render()
     (vendor/twig/twig/src/Environment.php:318)
  at Twig\Environment->render()
     (vendor/symfony/web-profiler-bundle/Controller/ProfilerController.php:123)
  at Symfony\Bundle\WebProfilerBundle\Controller\ProfilerController->panelAction()
     (vendor/symfony/http-kernel/HttpKernel.php:158)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw()
     (vendor/symfony/http-kernel/HttpKernel.php:80)
  at Symfony\Component\HttpKernel\HttpKernel->handle()
     (vendor/symfony/http-kernel/Kernel.php:201)
  at Symfony\Component\HttpKernel\Kernel->handle()
     (vendor/baldinof/roadrunner-bundle/src/Http/KernelHandler.php:45)
  at Baldinof\RoadRunnerBundle\Http\KernelHandler->handle()
  at Generator->current()
     (vendor/baldinof/roadrunner-bundle/src/Http/MiddlewareStack.php:94)
  at Baldinof\RoadRunnerBundle\Http\Runner->getResponse()
     (vendor/baldinof/roadrunner-bundle/src/Http/MiddlewareStack.php:72)
  at Baldinof\RoadRunnerBundle\Http\Runner->handle()
     (vendor/baldinof/roadrunner-bundle/src/Integration/PHP/NativeSessionMiddleware.php:34)
  at Baldinof\RoadRunnerBundle\Integration\PHP\NativeSessionMiddleware->process()
  at Generator->current()
     (vendor/baldinof/roadrunner-bundle/src/Http/MiddlewareStack.php:94)
  at Baldinof\RoadRunnerBundle\Http\Runner->getResponse()
     (vendor/baldinof/roadrunner-bundle/src/Http/MiddlewareStack.php:80)
  at Baldinof\RoadRunnerBundle\Http\Runner->handle()
     (vendor/baldinof/roadrunner-bundle/src/Integration/Doctrine/DoctrineORMMiddleware.php:59)
  at Baldinof\RoadRunnerBundle\Integration\Doctrine\DoctrineORMMiddleware->process()
  at Generator->current()
     (vendor/baldinof/roadrunner-bundle/src/Http/MiddlewareStack.php:94)
  at Baldinof\RoadRunnerBundle\Http\Runner->getResponse()
     (vendor/baldinof/roadrunner-bundle/src/Http/MiddlewareStack.php:80)
  at Baldinof\RoadRunnerBundle\Http\Runner->handle()
     (vendor/baldinof/roadrunner-bundle/src/Http/MiddlewareStack.php:34)
  at Baldinof\RoadRunnerBundle\Http\MiddlewareStack->handle()
  at Generator->current()
     (vendor/baldinof/roadrunner-bundle/src/Worker/Worker.php:61)
  at Baldinof\RoadRunnerBundle\Worker\Worker->start()
     (vendor/baldinof/roadrunner-bundle/src/Command/WorkerCommand.php:68)
  at Baldinof\RoadRunnerBundle\Command\WorkerCommand->execute()
     (vendor/symfony/console/Command/Command.php:255)
  at Symfony\Component\Console\Command\Command->run()
     (vendor/symfony/console/Application.php:1027)
  at Symfony\Component\Console\Application->doRunCommand()
     (vendor/symfony/framework-bundle/Console/Application.php:97)
  at Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand()
     (vendor/symfony/console/Application.php:273)
  at Symfony\Component\Console\Application->doRun()
     (vendor/symfony/framework-bundle/Console/Application.php:83)
  at Symfony\Bundle\FrameworkBundle\Console\Application->doRun()
     (vendor/symfony/console/Application.php:149)
  at Symfony\Component\Console\Application->run()
     (bin/console:42)   
```
