### ISSUE TITLE
Expose some fields when show entity relations

### ISSUE THREAD

**Issue by samusenkoiv** [api-platform/api-platform#90]
Hi everyone, 
I have an "Author" entity and it has many-to-many "Book" relation.

I'd like to show some fields instead of just the ids of relations. So instead of:

```
"books" : [
    "/books/23",
    "/books/24"
]
```
I want to show:
```
"books": [
   { 
     "@type: "/contexts/Book",
     "@id" : "/books/23",
     "title" : "book title",
     "cover_image" : "url/to/im.png"
  },
  {
    ....
  }
]
```
 What would be the best way to do that ?

One more question: is this okey to return url of the book cover as a string, or is it better to return an object like: 
```
{
   "@type" : "Image",
   "@id" : "http://absolute.path/to/my/img.png" //
}
```

Thank you

**Comment by theofidry** [comment]
Hello, you can achieve that by using [serialization groups](https://api-platform.com/doc/1.0/api-bundle/serialization-groups-and-relations).

Regarding your second questions, it's up to you and your consumers. If your Image is a dedicated objects, this should be treated as such, if it's an embeddable, the object should be shown.

**Comment by samusenkoiv** [comment]
To be honest with you, I'm not sure how I can use groups for this purpose.
Also, I'm already using serialization groups, but I use them to alter the scope of available for read and write entity attributes.

**Comment by theofidry** [comment]
You have an example on how to transform:

```json
{
  "@context": "/contexts/Offer",
  "@id": "/offer/62",
  "@type": "Offer",
  "price": 31.2,
  "product": "/products/59"
}
```

to:

```json
{
  "@context": "/contexts/Offer",
  "@id": "/offer/62",
  "@type": "Offer",
  "price": 31.2,
  "product": {
    "@id": "/products/59",
    "@type": "Product",
    "name": "Lyle and Scott polo skirt"
  }
}
```

You're free to have different groups and cumulate them :)

**Comment by samusenkoiv** [comment]
yes you're right. Thank you !

**Comment by theofidry** [comment]
Glad to be of a help
