### ISSUE TITLE
Reduce strictness of types

### ISSUE THREAD

**Issue by trsteel88** [api-platform/api-platform#904]
Is it possible to reduce the strictness of the API and types?

e.g. when sending a null value for a string the API throws an error of "The type of the "type" attribute must be "string", "NULL" given.".

I can trust my validation to catch incorrect values, can I disable these errors and let validation handle it?

**Comment by BonnieDoug** [comment]
I think this is already possible. Unless I'm misunderstanding your question the following should suffice.
Supposing you have a property as below, which is causing the not a string error:
```
    /**
     * @var string
     * @ORM\Column(nullable=true)
     */
    private $property = null;

    /**
     * @return string
     */
    public function getProperty (): string
    {
        return $this->property;
    }

    /**
     * @param string $property
     * @return MyClass
     */
    public function setProperty (string $property): MyClass
    {
        $this->property = $property;
        return $this;
    }
```

By replacing this with `?string` and `string|null` in the annotations you'll be able to provide a string or null:

```
    /**
     * @var string|null
     * @ORM\Column(nullable=true)
     */
    private $property = null;

    /**
     * @return null|string
     */
    public function getProperty (): ?string
    {
        return $this->property;
    }

    /**
     * @param null|string $property
     * @return MyClass
     */
    public function setProperty (?string $property): MyClass
    {
        $this->property = $property;
        return $this;
    }
```

Hope this helps.

**Comment by dunglas** [comment]
You can disable this feature totally if you want: https://symfony.com/doc/current/components/serializer.html#recursive-denormalization-and-type-safety

**Comment by trsteel88** [comment]
Thanks. I'll try it out.
