### ISSUE TITLE
Data model generation from schema.yml

### ISSUE THREAD

**Issue by mbckwa** [api-platform/api-platform#91]
Hello,

I have a question about the data model generation from schema.yml.
From what I understood, the model contained in the "schema.yml" must use data models provided by Schema.org.
My question is : is it possible to use data models which aren't provided by Schema.org ?
For instance if I want to create a model with a field 'Chair', 'Pen' or any field which isn't provided by Schema.org , how can I do that ?

Thanks.

**Comment by dunglas** [comment]
@mbckwa Hi,

* You can use any Doctrine entity, created "by hand" or using the generator doesn't matter
* If you want to use the generator and add custom fields, you can do it to: https://github.com/api-platform/doc/blob/master/getting-started/api.md#generating-the-data-model (the `kevinReview` field is a custom one)
