### ISSUE TITLE
Can I change {id} to a different name?

### ISSUE THREAD

**Issue by lfjeff** [api-platform/api-platform#910]
I am using api-platform with Symfony 4. It works fine, but I would like to change a GET url from: `/booking/{id}` to `/booking/{bookingId}
`
I'm using my own DTO object and custom data provider (not Doctrine ORM).

Here are the current `@ApiResource` and `@ApiProperty` definitions that work fine:
```
/**
 *
 * @ApiResource(
 *      itemOperations={
 *          "get"={
 *              "path"="/booking/{id}",
 *          },
 *          "api_bookings_get_item"={
 *              "swagger_context"={
 *                  "operationId"="getBookingItem",
 *                  "summary"="Retrieves details on a booking",
 *                  "parameters"= {
 *                      {
 *                          "name"="id",
 *                          "description"="Booking ID",
 *                          "default"="15000",
 *                          "in"="path",
 *                          "required"=true,
 *                          "type"="string"
 *                      }
 *                  },
 *                  "responses"={
 *                      "200"={
 *                          "description"="Results retrieved"
 *                      },
 *                      "404"={
 *                          "description"="Booking not found"
 *                      }
 *                  }
 *              }
 *          }
 *      },
 *      collectionOperations={}
 * )
 */
final class Booking
{
    /**
     * @var string
     * @Assert\NotBlank
     *
     * @ApiProperty(
     *    identifier=true,
     *    attributes={
     *        "swagger_context"={
     *            "description"="Booking ID",
     *            "required"=true,
     *            "type"="string",
     *            "example"="123456"
     *        }
     *     }
     * }
     */
     public $id;

     // other variables

 }
```
However, if I change all the references from `'id'` to `'bookingId'` it stops working and I get a 404 error. Here are the changes I made to the above code:

```
"path"="/booking/{bookingId}"

"name"="bookingId"

public $bookingId;
```
Is api-platform hard-coded to use `'id'` as an identifier? Is there any way to change this?

From what I can tell, it appears to be hard-coded in the `extractIdentifiers()` function.  I've been trying to figure out the code, but it is quite complex.  I don't know if making a change there will work or may have unintended consequences.

It seems to me that it should use whatever variable is tagged by the `@apiProperty(identifier=true)` annotation, but it does not appear to work like this.  It appears that the `getIdentifiersFromResourceClass()` function that checks the identifier annotation is being called AFTER `extractIdentifiers()`, which does not make sense to me.

**Comment by l-vo** [comment]
`id` seems to be hardcoded:
https://github.com/api-platform/core/blob/76722a74b479cab0c0b262e8dfa689fad68e1d8d/src/Bridge/Symfony/Routing/IriConverter.php#L124

**Comment by Tarasovych** [comment]
Same here

**Comment by soyuka** [comment]
Yes this is a known issue that I want to work on. Please see also a WIP proposal that you could vote on/use in your own project: https://github.com/api-platform/core/pull/2126.

**Comment by lamb0tiana** [comment]
@soyuka ,how to get started with that @lfjeff please, 
otherwise, what are process to do that, thank you.

**Comment by freakheart** [comment]
Any info on this please?

**Comment by LeoBenoist** [comment]
https://api-platform.com/docs/core/identifiers/

**Comment by soyuka** [comment]
this will be fixed by https://github.com/api-platform/core/pull/3664 but I need to finish the work to be backward compatible

**Comment by lazka** [comment]
Since 2.6 all those IDs changed from `{id}` to the class property name. Is there a way to change this now or do I have to change the property names?

**Comment by soyuka** [comment]
Yes you can use `identifiers=> ["id": [Class, "property"]]` within the metadata. How does this affect the API behavior?

**Comment by lazka** [comment]
Thanks! I don't think it affects the behavior, only the API docs.

**Comment by soyuka** [comment]
user-defined docs then?

**Comment by lazka** [comment]
yes, I meant the openapi parameter descriptions I added myself. all good.

**Comment by lazka** [comment]
Adding

```
 *     attributes={
 *          "identifiers": {"id": {Organization::class, "identifier"}}
 *     }
```
works as far as the API docs then use "id" again like with 2.5, but all the endpoints throw an error:

```
"Unable to generate an IRI for \"App\\\\Entity\\Organization\"."
```

Am I missing anything? :(

**Comment by soyuka** [comment]
Wait what is your full example? You should specify a path and correlation between parameters => [class, property]:

```
path="/organization/{myCustomName}",
identifiers=["myCustomName" => [Organization::class, "identifier"]]
```

**Comment by lazka** [comment]
I initially tried to keep my code working with both 2.5 and 2.6 to make reverts easier, but I've successfully updated to 2.6 (thanks for the nice improvements!) now an dropped 2.5 support, so this isn't that important anymore.

Here is an example:

```php
<?php
/**
 * @ApiResource(
 *     collectionOperations={
 *         "get"
 *     },
 *     itemOperations={
 *         "get"
 *     },
 *     iri="https://schema.org/Place",
 *     normalizationContext={
 *         "groups" = {"Place:output"},
 *         "jsonld_embed_context" = true
 *     },
 *     denormalizationContext={
 *         "groups" = {"Place:input"},
 *         "jsonld_embed_context" = true
 *     },
 *     attributes={
 *          "identifiers": {"id": {Place::class, "identifier"}}
 *     }
 * )
 */
class Place
{
    /**
     * @ApiProperty(identifier=true)
     */
    private $identifier;

   //...
}
```

I still get the `"Unable to generate an IRI..` error if I set the path manually.

**Comment by soyuka** [comment]
you're missing the `path="/places/{id}` the parameter name is still `identifier` but it tries to retrieve it via `id`.

**Comment by lazka** [comment]
do you mean like:
```php
/**
 * @ApiResource(
 *     collectionOperations={
 *         "get"
 *     },
 *     itemOperations={
 *         "get" = {"path"="/places/{id}"}
 *     },
 *     iri="https://schema.org/Place",
 *     normalizationContext={
 *         "groups" = {"Place:output"},
 *         "jsonld_embed_context" = true
 *     },
 *     denormalizationContext={
 *         "groups" = {"Place:input"},
 *         "jsonld_embed_context" = true
 *     },
 *     attributes={
 *          "identifiers": {"id": {Place::class, "identifier"}}
 *     }
 * )
 */
```

this still throws the same error.

**Comment by soyuka** [comment]
Yes as `{id}` is the parameter name that must match `"id"` inside the identifiers attributes. Try removing the cache?

**Comment by lazka** [comment]
Same with cache removed. The error seems to happen when it tries to serialize out the object returned from the dataprovider.

getIdentifiersFromItem() gives `['identifier' => 'foo']` and then complains that it expected `id`:

> Unable to generate an IRI for \"API\\Bundle\\Entity\\Place\". at /application/vendor/api-platform/core/src/Bridge/Symfony/Routing/IriConverter.php:158, Symfony\\Component\\Routing\\Exception\\MissingMandatoryParametersException(code: 0): Some mandatory parameters are missing (\"id\") to generate a URL for route \"api_places_get_item\". at /application/vendor/symfony/routing/Generator/UrlGenerator.php:177

**Comment by aelfannir** [comment]
> new Get(
>             uriTemplate: 'sound_hooks/{soundId}',
>             uriVariables: 'soundId',
>         )

```php
#[Get(uriVariables: 'soundId')]
``` 
it works without defining `uriTemplate`
