### ISSUE TITLE
upload file blob

### ISSUE THREAD

**Issue by itokia** [api-platform/api-platform#911]
Hello,
I would like to store documents in a blob field.
For that I have the following entity:
```
/**
 * @ApiResource(
 *     collectionOperations={
 *       "get"={"method"="GET", "normalization_context"={"groups"={ "get_document"}}},
 *       "post"={"method"="POST", "denormalization_context"={"groups"={"post_document"}}},
 *     },
 *     itemOperations={
 *       "get"={"method"="GET", "normalization_context"={"groups"={"get_document"}}},
 *       "put"={"method"="PUT", "denormalization_context"={"groups"={"put_document"}}},
 *       "delete"={"method"="DELETE"},
 *     },
 *     attributes={"order"={"dateDocument": "ASC"}}
 * )
 * @ApiFilter(SearchFilter::class, properties={"logement.id": "exact"})
 * @ORM\Entity(repositoryClass="App\Repository\DocumentRepository")
 */
class Document
{
    /**
     * @ORM\Id()
     * @Groups({"get_document"})
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", name="id_document")
     */
    private $id;

    /**
     * @Groups({"get_document"})
     * @ORM\Column(type="blob")
     */
    private $contenuDocument;

...
```

When I do a get_document, I get the following message:

```
title :  An error occurred
detail: An unexpected value could not be normalized: NULL
```

Do you have an idea please?

**Comment by teohhanhui** [comment]
Please refer to the Doctrine documentation: https://www.doctrine-project.org/projects/doctrine-dbal/en/2.8/reference/types.html#blob

You'd get either a stream or `null`.

But of course the column is `NOT NULL` as `nullable` is `false` by default: https://www.doctrine-project.org/projects/doctrine-orm/en/2.6/reference/annotations-reference.html#column

It seems like you have a `null` value in that property for some reason? (It's not supposed to be `null`, as mentioned above.)

**Comment by jguyenot** [comment]
Hi,

i have the same bug. I stor a thumbnail of a document into a blob column but when i want to return them i have the same error

"hydra:description": "An unexpected value could not be normalized: NULL",

I confirm that the data is in my table and the cell is not NULL.

**Comment by jguyenot** [comment]
@itokia have you resolve your problem?

**Comment by teohhanhui** [comment]
Okay, so the exception message is misleading. It's actually because `var_export` is used here: https://github.com/symfony/serializer/blob/v4.3.1/Serializer.php#L176 (it doesn't handle resource streams but just gives `NULL`).

Looks like you have to add a custom normalizer that handles a resource stream (converting it to a string?) - but is that really a good idea? Maybe it should at least be base64 encoded?

**Comment by teohhanhui** [comment]
Anyway, I'm not sure embedding binary data in JSON makes sense...

**Comment by jguyenot** [comment]
Thanks for your quikly answer.

I think i will create a custom controller to return the filestream directly. I think i=it's a best practice that retourne this stream in base64 (front js is not the best for decoding)

Thanks.
