### ISSUE TITLE
Saving nested relations [JSON:API]

### ISSUE THREAD

**Issue by mdix** [api-platform/api-platform#914]
Are you going to implement saving nested relations via JSON:API anywhere soon? When I try to save nested relations I always get

> {"type":"https:\/\/tools.ietf.org\/html\/rfc2616#section-10","title":"An error occurred","detail":"Only resource linkage supported currently, see: http:\/\/jsonapi.org\/format\/#document-resource-object-linkage."}

Is there any workaround to this?

**Comment by elboletaire** [comment]
How are you trying to save nested relations? I already save them without issues using the json as payload :confused:

**Comment by gte451f** [comment]
I to am looking to save the foreign key from a related table, just as described in the JSON API spec:
https://jsonapi.org/format/#crud-creating

Here is the canonical example provided where there appears to be a M-1 relationships from photos to photographer.  Is this supported in API Platform out of the box or must we resort to the serialization process?

```json
{
  "data": {
    "type": "photos",
    "attributes": {
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    },
    "relationships": {
      "photographer": {
        "data": { "type": "people", "id": "9" }
      }
    }
  }
}
```

**Comment by LewisMcFly** [comment]
@gte451f Yes, this works out of the box. You would just need to put an IRI as the photographer id.

```
{
  "data": {
    "type": "photos",
    "attributes": {
      "title": "Ember Hamster",
      "src": "http://example.com/images/productivity.png"
    },
    "relationships": {
      "photographer": {
        "data": { "type": "people", "id": "/api/photographers/9" }
      }
    }
  }
}
```
