### ISSUE TITLE
How to implement this custom operation on a subresource?

### ISSUE THREAD

**Issue by z31fbras** [api-platform/api-platform#915]
Hi everyone!

I don't know how to implement what I want to do.
I have a Building entity. In a Building, there are Rooms.

Although, Building and Room come from another API so what we store in the Building entity is the resource identifier that comes from the external API.

Rooms can only be created by fetching them through the external API.

I'd like to have a route that triggers the fetching of the rooms and links them to the specified building, for example: POST /buildings/{id}/rooms.

How can I do this the best way?

Thanks a lot for your help!

**Comment by z31fbras** [comment]
Solved by using this method! =D
https://api-platform.com/docs/core/operations/#alternative-method

**Comment by duhamelstuff** [comment]
> Solved by using this method! =D
> https://api-platform.com/docs/core/operations/#alternative-method

Hello, 
Thanks for you subject. I have the same concern and thanks to your reply, I pay attention to the doc. My concern is for the GET operation, it only return me the building (if we consider your example) - with list of rooms associated. It should normally not proceed so; it should give me list of rooms directly -with detailed infos.

This is how it answer to me 
```
{
  "@context": "/api/contexts/Conference",
  "@id": "/api/conferences/16/participants",
  "@type": "Conference",
  "id": 16,
  "title": "string",
  "address": "string",
  "dateStart": "2019-11-02T00:00:00+01:00",
  "hourStart": "1970-01-01T08:30:12+01:00",
  "dateEnd": "2019-11-02T00:00:00+01:00",
  "hourEnd": "1970-01-01T08:30:12+01:00",
  "user": "/api/users/1",
  "participants": [
    "/api/participants/1"
  ],
  "speakers": []
}
```

Instead of that way 
```
{
  "@context": "/api/contexts/Participant",
  "@id": "/api/conferences/15/participants",
  "@type": "hydra:Collection",
  "hydra:member": [
    {
      "@id": "/api/participants/1",
      "@type": "Participant",
      "id": 1,
      "name": "Duhamel",
      "phone": "0758723942",
      "email": "test@test.com",
      "user": "/api/users/1"
    },
    {
      "@id": "/api/participants/2",
      "@type": "Participant",
      "id": 2,
      "name": "Gildas",
      "phone": "0938438343",
      "email": "test@mail.com",
      "user": "/api/users/1"
    }
  ],
  "hydra:totalItems": 2
}
```
**And here is a part of my controller (it might look light)**
```
...
    /**
     * @Route(
     *     name="list_conference_carticipants",
     *     path="/api/conferences/{id}/participants",
     *     methods={"GET"},
     *     defaults={
     *         "_api_resource_class"=Conference::class,
     *         "_api_item_operation_name"="list_conference_carticipants"
     *     }
     * )
     */
    public function __invoke($data)
    {
        return $data;
    }
...
```
When I change _api_item_operation_name into _api_collection_operation_name; I have an error : "Unable to generate an IRI for XXXX"

Can you please help me ?
Thank you.

**Comment by mxmp210** [comment]
Having same problems over and over without any solution, when you fix one thing other part of application gets broken. Seems API platform is broken at many points that it is not usable in way it advertises, at least thats my experience so far. Can anyone answer these questions, you cannot use DTO's with graphql, you cannot use Custom Operations with custom bodies, you cannot utilize any other aspect of api paltform except it's default providers. If that's the case why it is not documented? or if that's not case could anyone experienced elaborate possible solutions for such use-cases. Documentation has it's limits getting around these edge cases and going through issues is no help at the moment.
Thank in Advance.
