### ISSUE TITLE
Merging two collections 

### ISSUE THREAD

**Issue by mcbuckets** [api-platform/api-platform#917]
Hello guys/girls,

I'm trying to setup a `collectionOperation` which returns two merged collections as a result.

Basically, i have to have a operation that returns two subresources(collections) of an entity merged as one. Ie. `/api/users/{id}/friends-combined` should return list that contains `User` objects which are the representations of 'friends' of requested user and all users that have this user as a friend. 

My idea was to create a custom collection operation(is this correct since there is no actual collection that represents the desired data per se?) and custom data provider in which i would merge two relations to obtain "friends" and "have-me-as-a-friend-but-not-in-my-friends-list". Btw. i'm aware that naming these relations as friends is not good. 

The thing is, i know its possible to make it work this way but not really sure this is the way i want to go. Not sure pagination will work this way etc.

Any advice is welcomed!

**Comment by teohhanhui** [comment]
> should return list that contains User objects which are the representations of 'friends' of requested user and all users that have this user as a friend.

Isn't "friends" a necessarily mutual relationship?

**Comment by mcbuckets** [comment]
@teohhanhui it is, but it should return `friends` and `befriendedMe` combined. Because single User can be a friend and befriended. Friend is maybe a wrong noun as i said in the question originally.
