### ISSUE TITLE
What is the best way to handle collection and item in event subscriber?

### ISSUE THREAD

**Issue by z31fbras** [api-platform/api-platform#919]
Hi everyone!

After having searched for an answer for hours on the internet, I can't find the best way to create my event subscriber.
In my PRE_SERIALIZE event subscriber, both collections and items are concerned by this event.
It's really easy to handle such a case when there is a single suscriber in the project, this is the code.

Although, when I add another subscriber in the project, when I perform a GET request to fetch a collection, how can I ensure that the collection is about the right entity?

I could find a way, but I'd like to know how API Platform best handles this. This can't be found in the documentation.

This is what I have so far:

```
public static function getSubscribedEvents()
{
	return [
		KernelEvents::VIEW => ["preSerialize", EventPriorities::PRE_SERIALIZE],
	];
}

public function preSerialize(GetResponseForControllerResultEvent $event)
{
	$controllerResult = $event->getControllerResult();
	$method = $event->getRequest()->getMethod();

	if(Request::METHOD_GET !== $method) {
		return;
	}

	if($controllerResult instanceof Building) {
		$this->enhanceBuilding($controllerResult);
	} else if($controllerResult instanceof \Traversable) {
		foreach ($controllerResult as &$building) {
			if(!$building instanceof Building) {
				return;
			}

			$this->enhanceBuilding($building);
		}
	}
}

private function enhanceBuilding(Building $building)
{
	// Do some stuff...
}
```

Thanks a lot for your help!

**Comment by soyuka** [comment]
Hi,

try to use this:

```
$attributes = ApiPlatform\Core\Util\RequestAttributesExtractor::extractAttributes($event->getRequest());
dump($attributes);
```

You'll see that you can use some of them to check if it's a collection, or a particular operation etc.

**Comment by z31fbras** [comment]
Thanks a lot @soyuka!
I'll have a look at it very soon ;)

**Comment by z31fbras** [comment]
Indeed, it helped me a lot!
Thank you very much for your speed and reliabilty @soyuka !
