### ISSUE TITLE
Sub-Resources and custom controler

### ISSUE THREAD

**Issue by skhattane** [api-platform/api-platform#92]
Hi, 
first : Thanks for this amazing bundle. Awesome Work !
I use this bundle 1.1 for Rest API with OAuth2 and everything works great.

In the 2.0 Alpha 1,  I waited the possibility to use sub-resources like that : 
groups/{id}/comments
groups/{id}/comments/{id}

I have read this little introduction with few lines of code.
https://les-tilleuls.coop/fr/blog/article/la-premiere-alpha-d-api-platform-2-0-est-disponible

But do you have a more consistent documentation about this important feature ?
Why a custom controller for that ? Do you have an example ?
Is it not easier to work with parent resources in annotation ? Something like that or similar : 

```
/**
 * This is Comment Entity
 * @ORM\Entity
 * @ORM\Table(name="comment")
 * @ApiResource(
 *      parent_resource = "/groups"
 * )
 */ 
```

**Comment by skhattane** [comment]
# #

**Comment by teohhanhui** [comment]
See api-platform/core#186

**Comment by dunglas** [comment]
Possible in v2 using custom operations and documented: https://github.com/api-platform/docs/blob/master/core/operations.md
