### ISSUE TITLE
[Feature Request] Default authentication system installed

### ISSUE THREAD

**Issue by chiqui3d** [api-platform/api-platform#921]
Hello,
I have started to use, but I see that there is no token authentication system installed by default, adding in the documentation the possibility of the bundle FosUserBundle, which is very outdated with the new versions of Symfony, so I do not understand why there is no system installed by default, and with user administrator creator by default. Which can be easily disabled the authentication system from the configuration of api_plataform.yml or security.yml.

My request is to come integrated.

Thanks and great work.

**Comment by alanpoulain** [comment]
Hello,
There are many ways to add authentication in Symfony. That's why there is no authentication system by default.
You need to choose and implement the one that is the best suited for your project.
