### ISSUE TITLE
Custom operation, Parameter "id" not found

### ISSUE THREAD

**Issue by paulbonneau** [api-platform/api-platform#922]
Hello,

I'm trying to add a custom route to my application in order to collect data from two entity.
I have an entity "Card" and an entity "ScenarioCard". I created my custom operation in ScenarioCard like that : 

```
Class ScenarioCard
  @package App\ShidoCardBundle\Entity
  @ORM\Entity
  @ApiResource(itemOperations={
      "get",
      "group_card_info_card_scenario_info"={
          "swagger_context" = {
            "summary" = "Retrieve a card object with ScenarioCard info",
            "parameters" = {
              {
                 "name" = "scenario_id",
                 "in" = "path",
                 "required" = "true",
                 "type" = "string"
              },
              {
                 "name" = "card_id",
                 "in" = "path",
                 "required" = "true",
                 "type" = "string"
              }
           }
          },
         "method"="GET",
          "path"="/scenario/{scenario_id}/card/{card_id}",
          "controller"=RetrieveScenarioCard::class,
      }
  })
```

Then I created the following handler (as specified in the documentation)
```
<?php
namespace App\ShidoCardBundle\Controller;

use App\ShidoCardBundle\Entity\ScenarioCard;

class RetrieveScenarioCard
{
    private $retrieveScenarioCardHandler;

    public function __construct(RetrieveScenarioCardHandler $retrieveScenarioCardHandler)
    {
        $this->retrieveScenarioCardHandler = $retrieveScenarioCardHandler;
    }

    public function __invoke(ScenarioCard $data): ScenarioCard
    {
        $this->retrieveScenarioCardHandler->handle($data);
        return $data;
    }
}
```

My problem here is that Hydra send me back the error "Parameter "id" not found" when I try to request the api endpoint associated with this route. If I understood it correctly, the parameter id is mandatory. If it's true I don't understand how I will be able to aggregate datas from those two Entities and send back thoses data.

Are Custom operations even the good way to do what I want to do ?

**Comment by soyuka** [comment]
Does your route shows up in `bin/console debug:router`? It looks fine although api platform won't be able to retrieve the data automatically from this route, you need to handle this in your controller.

**Comment by paulbonneau** [comment]
Yes, sorry I didn't include this information in my last post 
 ```
------------------------------------------------------------ -------- -------- ------ -------------------------------------------- 
  Name                                                         Method   Scheme   Host   Path                                        
 ------------------------------------------------------------ -------- -------- ------ -------------------------------------------- 
  app_shidocard_default_index                                  ANY      ANY      ANY    /                                           
  api_entrypoint                                               ANY      ANY      ANY    /api/{index}.{_format}                      
  api_doc                                                      ANY      ANY      ANY    /api/docs.{_format}                         
  api_jsonld_context                                           ANY      ANY      ANY    /api/contexts/{shortName}.{_format}         
  api_cards_get_collection                                     GET      ANY      ANY    /api/cards.{_format}                        
  api_cards_post_collection                                    POST     ANY      ANY    /api/cards.{_format}                        
  api_cards_get_item                                           GET      ANY      ANY    /api/cards/{id}.{_format}                   
  api_cards_delete_item                                        DELETE   ANY      ANY    /api/cards/{id}.{_format}                   
  api_cards_put_item                                           PUT      ANY      ANY    /api/cards/{id}.{_format}                   
  api_scenarios_get_collection                                 GET      ANY      ANY    /api/scenarios.{_format}                    
  api_scenarios_post_collection                                POST     ANY      ANY    /api/scenarios.{_format}                    
  api_scenarios_get_item                                       GET      ANY      ANY    /api/scenarios/{id}.{_format}               
  api_scenarios_delete_item                                    DELETE   ANY      ANY    /api/scenarios/{id}.{_format}               
  api_scenarios_put_item                                       PUT      ANY      ANY    /api/scenarios/{id}.{_format}               
  api_decks_get_collection                                     GET      ANY      ANY    /api/decks.{_format}                        
  api_decks_post_collection                                    POST     ANY      ANY    /api/decks.{_format}                        
  api_decks_get_item                                           GET      ANY      ANY    /api/decks/{id}.{_format}                   
  api_decks_delete_item                                        DELETE   ANY      ANY    /api/decks/{id}.{_format}                   
  api_decks_put_item                                           PUT      ANY      ANY    /api/decks/{id}.{_format}                   
  api_scenario_cards_get_collection                            GET      ANY      ANY    /api/scenario_cards.{_format}               
  api_scenario_cards_post_collection                           POST     ANY      ANY    /api/scenario_cards.{_format}               
  api_scenario_cards_get_item                                  GET      ANY      ANY    /api/scenario_cards/{id}.{_format}          
  api_scenario_cards_group_card_info_card_scenario_info_item   GET      ANY      ANY    /api/scenario/{scenario_id}/card/{card_id}  
  _twig_error_test                                             ANY      ANY      ANY    /_error/{code}.{_format}                    
 ------------------------------------------------------------ -------- -------- ------ -------------------------------------------- 
```
For the moment I created a Dummy Controller that is just returning the data object without altering him. Is there a particular way to handle this route detection in the controller ? (maybe I miss something in the documentation but I searched it a lot and can't find this information)

**Comment by GregoireHebert** [comment]
API Platform is trying to map a `ScenarioCard` from your custom operation path. For this it need a parameter called `id`. You need to change  your configuration from "path"="/scenario/{scenario_id}/card/{card_id}",` to `"path"="/scenario/{id}/card/{card_id}",` so it can retrieve it for you.

**Comment by GregoireHebert** [comment]
Still you'll need to get the card by yourself.
I suggest you to rename the `card` section to `cards` to fit the url definition pattern. so your path would look like `"path"="/scenario/{id}/cards/{card_id}"`.
Could it be a nice addition to the API Platform subresources ?
Anyhow it feels weird to ask for a resource from another one.

**Comment by paulbonneau** [comment]
I think I wasn't clear about what I want to do. I don't want to get a specific Card associated with a ScenarioCard (as if it was a subressource). I want to get the ScenarioCard Data + Card Data using a scenario_id and card_id

To contextualize, Card and Scenario are linked By ScenarioCard where each tuple give the next card associated with each choices of a given card for a given Scenario. I could do two api call on my client in order to fetch that information but I don't want to.

**Comment by GregoireHebert** [comment]
I think you'll need to fetch the data by yourself with a dataProvider, and you'll need to add `_api_receive` at false for this operation. otherwise it'll try to get it automatically.

**Comment by soyuka** [comment]
Can't it be a subresource actually? I think that you can deserialize the inverse of the relation and you would get what you need.

**Comment by paulbonneau** [comment]
I managed to get the data I wanted to use filter. My bad, totally overlooked this part of the documentation.

**Comment by Julobel** [comment]
Final solution in our entity:
`@ApiFilter(SearchFilter::class, properties={"scenario": "exact", "card": "exact"})`
Indeed, we are not sure that this is the best way to proceed, but we have the information we wanted.

**Comment by soyuka** [comment]
Closing this, hope that we were helpful.
