### ISSUE TITLE
Error: failed to reach build target api_platform_php in Dockerfile

### ISSUE THREAD

**Issue by Cliko** [api-platform/api-platform#927]
Hello, 

I would like to install the distribution 2.3.4, but I have a problem when I run : `docker-compose up -d`

The error : 

> Step 23/33 : VOLUME /srv/api/var
 ---> Running in 6ada260490ac
 ---> 54d855296991
Removing intermediate container 6ada260490ac
Step 24/33 : COPY docker/php/docker-entrypoint.sh /usr/local/bin/docker-entrypoint
 ---> a14e83eac9fa
Removing intermediate container 1ebf915ec3c5
Step 25/33 : RUN chmod +x /usr/local/bin/docker-entrypoint
 ---> Running in e97de244bb4a
 ---> 19dae1d4e434
Removing intermediate container e97de244bb4a
Step 26/33 : ENTRYPOINT docker-entrypoint
 ---> Running in 80176aa48243
 ---> 8aad8269ed38
Removing intermediate container 80176aa48243
Step 27/33 : CMD php-fpm
 ---> Running in 603ee08826c6
 ---> 9d13e50d64ce
Removing intermediate container 603ee08826c6
Step 28/33 : FROM nginx:${NGINX_VERSION}-alpine AS api_platform_nginx
 ---> 6884a281e9a4
Step 29/33 : COPY docker/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
 ---> 4eacfbbe7aaa
Removing intermediate container 2d463003c7aa
Step 30/33 : WORKDIR /srv/api
 ---> a4eb8a8fd79f
Removing intermediate container 14d11d05caea
Step 31/33 : COPY --from=api_platform_php /srv/api/public public/
 ---> 9339ba28b182
Removing intermediate container 7b566a9e43ee
Step 32/33 : FROM cooptilleuls/varnish:${VARNISH_VERSION}-alpine AS api_platform_varnish
 ---> b3e1e0e9ebcc
Step 33/33 : COPY docker/varnish/conf/default.vcl /usr/local/etc/varnish/default.vcl
 ---> f165a3d64faf
Removing intermediate container ecc65d8cad4e
ERROR: Service 'php' failed to build: failed to reach build target api_platform_php in Dockerfile

I also tested with the git version, everything starts correctly but only the php service does not seem to exist.
When I try: `docker-compose exec bin php/console d:s:u --force`
Return that the php service is not found

Would you have a solution?

Thanks !

**Comment by maxhelias** [comment]
You probably have a bad docker cache somewhere.
Try this command : `docker-composer build --no-cache php`

**Comment by maxhelias** [comment]
Maybe, i don't know, which version do you use and which OS ?
Can you try to erase your docker project with the following command :  `docker-compose down -v --rmi all --remove-orphans` and re build it with `docker-compose up -d`

**Comment by z31fbras** [comment]
What is the exact situation: are you on your local version?
Maybe it is a proxy issue?

**Comment by Janak** [comment]
Same  case happened on Ubuntu

docker-compose up -d
Pulling db (postgres:10-alpine)...
10-alpine: Pulling from library/postgres
cd784148e348: Already exists
67451ade031c: Pull complete
a9990a72e3ae: Pull complete
afd7f1c75cf9: Pull complete
708d7481af88: Pull complete
2fa3627e06f9: Pull complete
d1bdf7f14050: Pull complete
314813461935: Pull complete
88d74fac6218: Pull complete
Digest: sha256:1bb96e26d1cb23a699951083a16be946275fd005178ca9d62f682f974d45f348
Status: Downloaded newer image for postgres:10-alpine
Building php
Step 1/27 : ARG PHP_VERSION=7.2
Step 2/27 : ARG NGINX_VERSION=1.15
Step 3/27 : ARG VARNISH_VERSION=6.0
Step 4/27 : FROM php:${PHP_VERSION}-fpm-alpine AS api_platform_php
7.2-fpm-alpine: Pulling from library/php
cd784148e348: Already exists
d207535cd57f: Already exists
1167ab95319c: Already exists
bff34bff7f50: Already exists
39491f92b47e: Already exists
7fc8b2a4aa78: Already exists
ebf34b9a7120: Already exists
feaf85939116: Already exists
97922d1e5c13: Already exists
2d80873bfa59: Already exists
b55a0c24ee51: Already exists
Digest: sha256:bf1752f6ea37f575cb4625d91a75931afa0fe3eaf93551ed1eb8fdd509e0c682
Status: Downloaded newer image for php:7.2-fpm-alpine
 ---> 262e46e3d43c
Step 5/27 : RUN apk add --no-cache 		acl 		file 		gettext 		git 	;
 ---> Running in 9bcbed181e8f
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz: temporary error (try again later)
WARNING: Ignoring http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz: temporary error (try again later)
ERROR: unsatisfiable constraints:

**Comment by Cliko** [comment]
I use the last release version (2.3.4) and i'm on Debian 9. 

I try to create a local version and I don't use a proxy.

When I try `docker-compose down -v --rmi all --remove-orphans` :+1: 
> Removing network apiplatform234_default
Removing volume apiplatform234_db-data
Removing image quay.io/api-platform/admin
Removing image postgres:10-alpine
Removing image quay.io/api-platform/client
Removing image quay.io/api-platform/php
ERROR: Failed to remove image for service php: 404 Client Error: Not Found ("No such image: quay.io/api-platform/php:latest")
Removing image quay.io/api-platform/nginx
ERROR: Failed to remove image for service api: 404 Client Error: Not Found ("No such image: quay.io/api-platform/nginx:latest")
Removing image quay.io/api-platform/varnish
ERROR: Failed to remove image for service cache-proxy: 404 Client Error: Not Found ("No such image: quay.io/api-platform/varnish:latest")
Removing image apiplatform234_h2-proxy
ERROR: Failed to remove image for service h2-proxy: 404 Client Error: Not Found ("No such image: apiplatform234_h2-proxy:latest")

**Comment by Janak** [comment]
https://github.com/gliderlabs/docker-alpine/issues/386#issuecomment-437698540

This will solve issue

**Comment by spolischook** [comment]
I've just tested last version of api platform with brand new Ubuntu 18.04 on DigitalOcean - and it's works fine.

**Comment by tabok** [comment]
Ech, I had the same issue on my Linux Mint.

That's because I had installed older docker engine (16.X) but docker-compose 3.4 requires version 17.09.0+

```
sudo apt-get upgrade docker
```

Solved my problem.
I hope it'll be helpful for someone else too, cheers!
