### ISSUE TITLE
Is it possible to generate typescript interfaces for API responses?

### ISSUE THREAD

**Issue by kiyanov** [api-platform/api-platform#930]
Hi, in ideal world I want to have typescript interfaces be generated  based on  API responses.  Is it somehow possible with your system?

**Comment by dunglas** [comment]
Yes, it is using the `typescript` generator of API Platform client generator: https://api-platform.com/docs/client-generator

Basically, you'll run `npx @api-platform/client-generator https://demo.api-platform.com src/ --resource book -g typescript`

Unfortunately, this feature isn't documented. It would be awesome to add a doc entry about this.

**Comment by luca-nardelli** [comment]
Hey, I just found this issue by chance while I was looking for other ways to get typescript interfaces than swagger to typescript.

I might be able to help with the documentation for the typescript generator. 

Is someone working on the documentation already?

**Comment by dunglas** [comment]
No I don't think so, some docs for this would be awesome!

**Comment by luca-nardelli** [comment]
I've opened a PR with a first draft of the page, have a look!

**Comment by luca-nardelli** [comment]
This should probably be closed, right?

**Comment by dunglas** [comment]
Indeed, thanks
