### ISSUE TITLE
Deep default order

### ISSUE THREAD

**Issue by unkndono** [api-platform/api-platform#932]
Hello, 

I would need to add a sort (by default) to different resources that are hierarcally related together. 
I want to always sort a the uppest $name (ResourceA)
I might be doing something wrong,  here is my use case : 

```php
class ResourceA
{
    private $name;
}

class ResourceB
{
    private $name;

    /**
     * @var ResourceA
     */
    private $category;
}

class ResourceC
{
    /**
     * @var ResourceB
     * @ORM\ManyToOne(targetEntity="App\Entity\ResourceB", inversedBy="myResourcesC")
     */
    private $parent;
}

class ResourceD
{
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ResourceC", inversedBy="myResourcesD")
     * @var ResourceC
     */
    private $parent;
}

class ResourceE
{
    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\ResourceE", inversedBy="myResourcesE")
     * @var ResourceD
     */
    private $parent;
}
``` 

Then i add attributes in my resources.yaml
example on Resource C : 
```yaml
attributes:
      order:
        parent.category.name: 'ASC'
```

I get the following message : 
[Semantical Error] line 0, col ... near 'name ASC': Error: Class App\\Entity\\MyEntityC has no field or association named category.name

I looked at the [OrderExtension](https://github.com/api-platform/core/blob/30d82137b9701b7501e8a976af95ec07006a8bb9/src/Bridge/Doctrine/Orm/Extension/OrderExtension.php#L69) class, and it seems it doesn't handle a deep (more than one level?) sorting:
```php
$field = sprintf('%s.%s', $alias, substr($field, $pos + 1));
```

EDIT: my first error, is that it's seems to not be possible to do 'parent.category.name' in Doctrine (am i right ?). I should find a way to do resourceAalias.name ?

Could you advice me ? 
Thanks

**Comment by soyuka** [comment]
I don't think we support more than 1 level indeed. Could you try tweaking the order filter to see if you can manage to hack it?

**Comment by unkndono** [comment]
We found a different approach, and made cleanings in our application structure.

Thanks
