### ISSUE TITLE
Access control feature

### ISSUE THREAD

**Issue by FrodeMMeling** [api-platform/api-platform#94]
Is there a way to limit operations based on User Role and also in some cases Row level access verification?

Reason for asking is that your bundle generate routes automatically and it would be nice to have access_control also to be based on resource config and not the debug:router output by using access_control config manually.

Can Event system be used to implement row-level authorisation?
I do not see a "api.pre_retrieve_list"

**Comment by teohhanhui** [comment]
For v2, use Symfony Security voters.

**Comment by FrodeMMeling** [comment]
Is there any upgrade instructions?

**Comment by teohhanhui** [comment]
Not at the moment. You could open an issue at https://github.com/api-platform/doc :)

**Comment by andreas-glaser** [comment]
Has this been implemented? And if so, is it documented?

**Comment by Simperfit** [comment]
@andreas-glaser what do you mean ?
