### ISSUE TITLE
Support nested inclusion in jsonapi

### ISSUE THREAD

**Issue by RikudouSage** [api-platform/api-platform#940]
Are there any plans on supporting nested relations in jsonapi according to their [documentation](https://jsonapi.org/format/#fetching-includes)?

Examples:

```
GET /articles/1?include=comments.author HTTP/1.1
Accept: application/vnd.api+json
```

Notice the `comments.author` in `include`.

**Comment by antograssiot** [comment]
closing as duplicate of https://github.com/api-platform/core/issues/2365 @RikudouSage 
A PR to support this would be very welcome, it is on my TODO but I lack time at the moment.

**Comment by RikudouSage** [comment]
@antograssiot Is there at least option to fetch all subresources recursively?

I have a structure of `Claim` -> `Activity` -> `Invoice` (`Claim` is OneToMany to `Activity` and `Activity` is OneToMany to `Invoice`).

I basically need to query claims (both `GET /claims` and `GET /claims/{id}`) and fetch all related info, e.g. activities and invoices. I really can't find in any documentation how to do this.
