### ISSUE TITLE
[Feature Request] Apply filters only on specific operations

### ISSUE THREAD

**Issue by raresserban** [api-platform/api-platform#942]
Hello,
I want to apply a NumericFilter for a customerId property, and I want that filter to only be available to the collection operation for admins (I have one collection operation that gets all the orders for the current customer and another for admins that can retrieve all orders).
This is currently not possible without a custom filter, even though the `filterProperty` function from the NumericFilter class has the `$operationName` as an argument.
And even after creating the custom filter, I also have to override the `getDescription` function since that function does not have the operation as an argument so I can not generate swagger documentation for only a specific operation.

I do not know why this is not possible by default, it seems to me that this is a very useful feature.
Thank you.

**Comment by soyuka** [comment]
For the documentation, just add a DocumentationNormalizer on top of the normal one that disables this filter by your criterias. 
For the "allow this filter for admin only", I'd do a ReadListener on the PRE_READ event. Do your checks are rewrite the query parameters inside the request should be feasible.

**Comment by d0niek** [comment]
Can you explain where exactly add `DocumentationNormalizer` to disable/enable filter for specific operation?

**Comment by d0niek** [comment]
I put filters under operations like here:

```
   * @ApiResource(
   *   collectionOperations={
   *     "get"={
   *       "filters"={
   *         Filter\Search::class,
   *         Filter\Customer::class
   *       }
   *     },
   *     "for_contact_person"={
   *       "controller"=ContactPersonController\Customers::class,
   *       "method"="GET",
   *       "path"="/contact_people/{contactPersonId}/customers.{_format}",
   *       "read"=false,
   *       "requirements"={"contactPersonId"="\d+"},
   *       "filters"={
   *         Filter\RelatedCustomer::class
   *       }
   *     },
```

and everything works :-)

**Comment by raresserban** [comment]
@d0niek So that works?Then I am guessing that this was implemented at some point then. Haven't had the time to test it myself yet but will take a look.

**Comment by soyuka** [comment]
Closing feel free to ping me to re-open !
