### ISSUE TITLE
GraphQL id_list returns all records instead of specified amount

### ISSUE THREAD

**Issue by RiseAndCry** [api-platform/api-platform#943]
1. Is this a bug or did i misconfigure something ? (see image below):
when i use `companies(id_list: [1, 2])` i get all of my records instead of specified 2.
Also, if i use `companies(id: 1])` i still get all the records. I feel that this is a problem with IRI. 

![image](https://user-images.githubusercontent.com/11545302/50836131-1feea600-1361-11e9-89ba-78f62fbd47a6.png)

2. I'm also wondering why i need to use IRI when using `company(id: "/api/companies/1")` but i need to pass an integer into `companies(id: 1])` ( tried both options for "allow_plain_identifiers").

my relevant php part:

```
/**
 * @ApiResource
 * @ApiFilter(SearchFilter::class, properties={"id": "exact", "name": "ipartial", "bic": "iexact"})
 */
class Company
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;
...
```

**Comment by RiseAndCry** [comment]
Also, is there a way to completely get rid of IRI ? i'd prefer the old and tried integer id. I'm not using json-ld either way.

**Comment by RiseAndCry** [comment]
Oh, i figured out the reason for the first one:
I had to use `@ApiFilter(NumericFilter::class, properties={"id"})` instead of SearchFilter.

But i am still interested in how to get rid of IRI, o ar least how to be able to use 
`company(id: 1)` instead of `company(id: "/api/companies/1")`.

**Comment by alanpoulain** [comment]
There is no way to use ID instead of IRI by design.

**Comment by onionpsy** [comment]
had the same issue with IRI. found a (dirty) work-around:

New filter:
```
namespace App\Filter;

use ApiPlatform\Core\Bridge\Doctrine\Orm\Filter\SearchFilter;

class IriFilter extends SearchFilter
{
    /**
     * {@inheritdoc}
     */
    protected function getType(string $doctrineType): string
    {
        return 'string';
    }
}
```

Entity:
```
#[ApiFilter(IriFilter::class, properties: ['id'])]
```

Query:
```
query {
  regions(id_list: ["/entity/2", "/entity/5"]) {
    id
    name
  }
}
```

I think it would be great to have a proper `IriFilter`. `SearchFilter` just doesn't work in this case because it's based on Doctrine typing (int/string).
