### ISSUE TITLE
Use Symfony ExpressionFunctionProviders with api_platform.security.expression_language

### ISSUE THREAD

**Issue by tezvi** [api-platform/api-platform#944]
Hi everyone!

I'm not sure if I got this right but the api_platform.security.expression_language service seems to extend the symfony expression language base class instead of using a composition pattern or an additional compiler pass.

`<service id="api_platform.security.expression_language" class="ApiPlatform\Core\Security\ExpressionLanguage" public="false" />`

As a result custom ExpressionLanguageFunctionProviders are not applied to api_platform.security.expression_language instance. In another words I am not able to register my own expression language functions and use them either in yaml definitions or annotations (access_control).

This could be resolved relatively easy if service _api_platform.security.expression_language_ is an actual decorator or depends on the service instance _security.expression_language_ which has already registered additional function providers.
Another option is to use a compiler pass that applies all tagged function providers (default symfony behavior):

```
class ExpressionFunctionProvidersPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container)
    {
        $definition = $container->findDefinition('api_platform.security.expression_language');
        foreach ($container->findTaggedServiceIds('security.expression_language_provider') as $id => $attributes) {
            $definition->addMethodCall('registerProvider', [new Reference($id)]);
        }
    }
}
```

**Comment by soyuka** [comment]
IMO we need this, feel free to patch and open a pull request! Thanks!

**Comment by tezvi** [comment]
Sure no problem, I'll provide PR.

**Comment by tezvi** [comment]
@soyuka , it seems this has been already resolved by Yanick Witschi on master branch https://github.com/api-platform/core/pull/2289 with a slightly different approach.
Not sure if released yet.

**Comment by soyuka** [comment]
Nice! We merged this as a new feature!
