### ISSUE TITLE
Followed "Getting Started" and locked up AWS Instance

### ISSUE THREAD

**Issue by frey1esm** [api-platform/api-platform#946]
I have an Amazon Linux 2 instance and after running through[ Getting Started](http://api-platform.com/docs/distribution) and executing the following:

`docker-compose up -d # Running in detached mod`

...and getting positive feedback as follows:

```
Starting apip_client_1 ... done
Starting apip_db_1     ... done
Starting apip_admin_1  ... done
Creating apip_php_1    ... done
Creating apip_api_1    ... done
Creating apip_cache-proxy_1 ... done
Creating apip_h2-proxy_1    ... done
```

...the instance went to 100% CPU and basically locked up. I'll try to disable all other services but there wasn't much running. I had already stopped apache. MySQL was running. Any suggestions ?

**Comment by dunglas** [comment]
The Docker Compose setup is designed for the development environment (on your local computer). The dev mode requires much more resources than the prod mode.

In production, we recommend using the provided Kubernetes setup (https://api-platform.com/docs/deployment/kubernetes/#deploying-to-a-kubernetes-cluster), with Amazon EKS if you want to use AWS, or any other deployment method supported by Symfony:  https://symfony.com/doc/current/deployment.html

**Comment by frey1esm** [comment]
Running fine on Mac. Closing issue.
