### ISSUE TITLE
SearchFilter like DateFilter

### ISSUE THREAD

**Issue by keyermann** [api-platform/api-platform#948]
Hi,

First of all thank you for your awsome products ! <3

I have just one question : why can't we add SearchFilter with open strategy as for the DateFilter ?

For DateFilter the user can choose the strategy : 

> Syntax: ?property[<after|before|strictly_after|strictly_before>]=value

For SearchFilter the strategy is fixed by annotation : 

> * @ApiFilter(SearchFilter::class, properties={"product": "exact"})

But if I want to permit more strategy ? Can't we do the same as for DateFilter : 

As annotation : 
> * @ApiFilter(SearchFilter::class, properties={"product"})  

As Syntax :  

> Syntax: ?product[<partial|start|end|word_start>]=value

There is maybe a very good reason this not to be possible, and I am far from being a professional. 

PS : As a good basic french people my english may be awful... Sorry about that, I do my best to improve myself.

**Comment by jewome62** [comment]
Hello,

You can copy SearchFilter with [custom filter ](https://api-platform.com/docs/core/filters/)to adapt with content of DateFilter
`/vendor/api-platform/core/src/Bridge/Doctrine/Orm/Filter/SearchFilter.php`
`/vendor/api-platform/core/src/Bridge/Doctrine/Orm/Filter/DateFilter.php`

**Comment by alanpoulain** [comment]
Partial and exact search usually suffice. We don't want to maintain too much strategies. You can create your own filter if you need more strategies.
