### ISSUE TITLE
@ApiResource does not have a property named "deprecationReason"

### ISSUE THREAD

**Issue by numediaweb** [api-platform/api-platform#949]
In the [docs](https://api-platform.com/docs/core/deprecations/#deprecating-resource-classes-operations-and-properties) the example suggests a way to handle deprecations:

`@ApiResource(deprecationReason="Create a Book instead")`

But this throws an AnnotationException:

`[Creation Error] The annotation @ApiResource declared on class ... does not have a property named "deprecationReason". Available properties: shortName, description, iri, itemOperations, collectionOperations, subresourceOperations, graphql, attributes`

**Comment by antograssiot** [comment]
you're likely using  v2.2.x, that was added in 2.3, update api-*platform/core should do the trick
