### ISSUE TITLE
Request parameters in data providers

### ISSUE THREAD

**Issue by maechler** [api-platform/api-platform#95]
It feels like the **CollectionDataProviderInterface** needs to be extended / changed. I was trying to implement a paginated collection and I did not find any other way to access the "current page" parameter other than using $_GET['page']. 
In addition we would like to filter collections with additional parameters, so I feel like all the parameters should be passed to the method getCollection. The **ItemDataProviderInterface** could be extended in the same way because it could also be a need to access additional request parameters there.

Possible solutions could be:
1. Pass request object to getCollection and getItem
2. Create a new parameters object, that could have methods to access resourceClass, id, operationName, fetchData and a generic method for all additional parameters. Pass only the new parameters object to the methods getItem and getCollection.
3. Pass simply an associative array containing the parameters
4. Define an api-platform way of using a page parameter and additionally pass this parameter to getCollection. (Does not allow additional parameters for filtering)

What do you think? Is there probably a way to access these parameters I have not seen so far?

**Comment by teohhanhui** [comment]
@maechler:
> I was trying to implement a paginated collection and I did not find any other way to access the "current page" parameter other than using $_GET['page']. 

You're supposed to inject `@request_stack` into the service (through the constructor).

**Comment by maechler** [comment]
@teohhanhui Thanks!
