### ISSUE TITLE
[Bug] Default *DataProvider priority is the same than custom Providers

### ISSUE THREAD

**Issue by Cethy** [api-platform/api-platform#950]
Since I updated to `v2.3.5`, the order of my project's DataProvider is messed up : the default CollectionDataProvider is tagged before my custom ones, so it is called instead.

As per the [documentation](https://api-platform.com/docs/core/data-providers/#custom-item-data-provider), one will expect the custom DataProviders to be always called before the default ones. Additionally, this is really error-prone since it could be hard to catch.

Shouldn't the default DataProviders have a negative priority by default ?

**Comment by mmarynich** [comment]
@Cethy Read it, solution is here https://github.com/symfony/symfony/issues/29836

**Comment by Cethy** [comment]
@mmarynich Thx a lot for the read. :)

I'll keep explicit configuration for now then (positive priority for custom DataProvider). 
But I still think API-Platform should be patch to not rely on the *magic* default mechanism (opposed to explicit priority).

**Comment by mmarynich** [comment]
I have done a PR
https://github.com/symfony/symfony/pull/29853

**Comment by do-web** [comment]
I also have this problem now, after update my composer packages. :(
I tried to set the priority like this
```
    App\DataProvider\SettingItemDataProvider:
        tags:
            - { name: api_platform.collection_data_provider, priority: 3 }
        autoconfigure: false
```

But now i get an error on some requests:

```
Attempted to call an undefined method named "getCollection" of class "App\DataProvider\SettingItemDataProvider".

----

api-platform/core/src/DataProvider/ChainCollectionDataProvider.php"
function: ""
line: 47
```

**Comment by antograssiot** [comment]
Given the name of your  class `SettingItemDataProvider` are you sure it is a collection data provider and not item data provider `api_platform.item_data_provider`?

**Comment by suyar** [comment]
I think it should be fixed.
