### ISSUE TITLE
[Question] Filter API-Response based on query params for jsonb attributes

### ISSUE THREAD

**Issue by mschmie** [api-platform/api-platform#951]
I am using the jsonb datatype with postgreSQL on my API. GroupsFilters and SearchFilters works pretty well on common entities and relations. But how to modify API-Response concering nested jsonb object attributes?

Given there is a text object wich contains different languages like in:

```
{
    "#type": "App\\Entity\\Text",
    "class": "title",
    "texts": {
        "de-DE": "Titel Text de",
        "en-EN": "Title Text en",
        "fr-FR": "Titre Texte fr"
    }
}
```
Now there should be the possibility to query one or more languages via get param `?languages=en,fr` or `?languages[]=en&languages[]=fr` 
What's the recommended procedure around the result which contains only the two languages? 
And how to handle a fallback-language i.e. if there is no language found via `&language=it`?

Thanks for your help!

**Comment by jewome62** [comment]
You can create a custom filter https://api-platform.com/docs/core/filters/#creating-custom-filters
to apply a new where with your condition.

Into condition, you can handle the value's filter to add a fallback language

**Comment by mschmie** [comment]
Thanks for your Answer. 
I am still wondering how to query the jsonb relations with a custom filter. Because when I am extend my CustomFilter with AbstractContextAwareFilter, I've only got a Doctrine Filter. Not sure, but I think what I need is the possibility to do a native query. Do you have any idea how to do that?

**Comment by tezvi** [comment]
Not sure if I understood, what do you mean with "Doctrine Filter". Did you mean ORM QueryBuilder instance? You can apply where conditions to query builder instance. If you need native query because of SQL specifics than you might have difficulties with ORM as ApiPlatform data provider works with ORMc query builder only.
I've resolved that by using a custom DataProvider that uses DBAL query builder internally. However that is another story for another purpose as you have to write a lot of additional code.
Another possible solution is to extend DQL to support your specifics.

**Comment by mschmie** [comment]
You're right. I ment the ORM Querybuilder which is used by default. 

So I had to write either a custom DataProvider using DBAL to offer a native SQL Query support or extend DQL for my Query needs? Propably with the DataProvider option I had to implement each built-in Filter (e.g. GroupsFilter, SearchFilter) by myself. Then the DQL solution may be more purposeful. Is there documentation for this? 

As a reminder, I only want to expose the texts which are in the requested language param. 
The titleText is stored as jsonb object in the db. 
If I get the whole object anyway, would it make sense to remove the corresponding languages e.g. in a custom serializer or controller?
```
{
 "pageId": "10000",
 "id": 22,
 "code": "Dr. Tremaine Kohler",
 "titleText": {
  "texts": {
      "de-DE": "Titel Text de",
      "en-EN": "Title Text en",
      "fr-FR": "Titre Texte fr"
  }
 }
}
```

**Comment by tezvi** [comment]
Yes, you are correct. Writing a custom DataProvider opens a Pandora's box :)

Perhaps you can have fun with this https://github.com/opsway/doctrine-dbal-postgresql.
Note DQL support for postgres JSON_AGG. You could extract jsonb data from titleText column with locale condition. Not really sure if that will work, just a theory.

Serializer approach is also ok, just make sure not to introduce a performance hit if your API will be used excessively.

**Comment by mschmie** [comment]
Thanks for your help. At the moment I've solved it via serializer. I'll have to see if there are performance issues on larger queries.
