### ISSUE TITLE
Is it possible to expose a collection without exposing single items?

### ISSUE THREAD

**Issue by mnapoli** [api-platform/api-platform#964]
I would like to expose a Doctrine entities as a read-only collection only. E.g. `GET /taxes`. I don't want `GET /taxes/{taxId}` to be available.

Here is what I am trying:

```php
/**
 * @ApiResource(
 *     collectionOperations={"get"},
 *     itemOperations={}
 * )
 *
 * @ORM\Entity
 */
class Tax
```

but that is not working. The only way I can make it work is by exposing the single item as well:

```php
/**
 * @ApiResource(
 *     collectionOperations={"get"},
 *     itemOperations={"get"}
 * )
 *
 * @ORM\Entity
 */
class Tax
```

Is this by design?

**Comment by z31fbras** [comment]
What routes are available in the two cases?
I tested on my project and the first option works fine: I have /taxes routes but not /taxes/{id} ones.

As precised here in the docs : https://api-platform.com/docs/core/operations/#enabling-and-disabling-operations : `itemOperations and collectionOperations are arrays containing a list of operation. Each operation is defined by a key corresponding to the name of the operation that can be anything you want and an array of properties as value. If an empty list of operations is provided, all operations are disabled.`

**Comment by mnapoli** [comment]
Thanks, then the problem might be on my end. That may be related to Hydra (or JSON-LD) links to sub-entities. I'll investigate and report back here if necessary.
