### ISSUE TITLE
Swagger.yaml file -> openapi: 3.0.0

### ISSUE THREAD

**Issue by rubenvdlinde** [api-platform/api-platform#966]
How do I change the "swagger: '2.0'"  at the top of the swagger to "openapi: 3.0.0"?

**Comment by antograssiot** [comment]
you need to use api-platform/core master branch and use the `--spec-version=3` 
You can find the doc on [the master branch](https://github.com/api-platform/docs/blob/4a6e7e8d02af249d47e0fc5f910cfcad09bb3089/core/swagger.md#using-the-openapi-command)

**Comment by rubenvdlinde** [comment]
![openapi](https://user-images.githubusercontent.com/4021899/51386827-1c5adc00-1b24-11e9-9f77-1959981e7b81.JPG)

would sugest that i'm nor curently on the core master branche, correct?

**Comment by rubenvdlinde** [comment]
oke, so i'm a bit at a los how i should get my build on core-master branche trough composer. (sorry not much of coposer genius), I tried composer require api-platform/api-pack:dev-master but that failed wit the following error:

![openapi](https://user-images.githubusercontent.com/4021899/51387157-642e3300-1b25-11e9-89c0-56870999ddee.JPG)

**Comment by antograssiot** [comment]
not sure if it's the best option as I don't use packs in Flex, but `composer require api-platform/core:dev-master` should do the trick

**Comment by rubenvdlinde** [comment]
That did the trick, thanxs!
