### ISSUE TITLE
OpenAPI vs Swagger file

### ISSUE THREAD

**Issue by rubenvdlinde** [api-platform/api-platform#967]
Currently using redoc to look at my yaml file's

When generating a file with  swagger everything is fine
`api:swagger:export --output=/var/www/api/public/schema/openapi.yaml --yaml
`![swagger_file](https://user-images.githubusercontent.com/4021899/51392549-a7909d80-1b35-11e9-9a6c-634a48e22b7c.JPG)

However, if i switch to openApi everything goes awol
`api:openapi:export --output=/var/www/api/public/schema/openapi.yaml --yaml  --spec-version=3
` ![openapi file](https://user-images.githubusercontent.com/4021899/51392592-c8f18980-1b35-11e9-9dcf-7d3fcf78fe97.JPG)

**Comment by antograssiot** [comment]
do you use some specific tweaks in your API ?
I've just tried ReDoc with the OpenAPI 3 spec extracted from our test-app.
The spec is quite large but I didn't get any warnings

here the spec uploaded on a [gist](https://gist.githubusercontent.com/antograssiot/cd5cc85a6cee4ac645e1e11615b4da30/raw/403ccccafbe13069a15fce33eb7df0b036cebe1d/swagger.yaml)
