### ISSUE TITLE
[question] many relations ManyToOne to same entity

### ISSUE THREAD

**Issue by Gulivertx** [api-platform/api-platform#969]
Hi,
A question about relations with API-Plaform, I have an entity which have 3 ManyToOne relations to same entity (User). In swagger I can see the result JSON object looking correctly but when I do a query to the API I got only the first relation but the next two relations seems to be ignored and they are not returned. Did I make something not correct ?

Here is me first entity 
```php
/**
 * @ApiResource(normalizationContext={"groups"={"patient"}})
 * @ApiFilter(SearchFilter::class, properties={"user": "exact"})
 * @ApiFilter(BooleanFilter::class, properties={"active"})
 * @ApiFilter(OrderFilter::class, properties={"lastname"}, arguments={"orderParameterName"="order"})
 * @ORM\Entity(repositoryClass="App\Repository\PatientRepository")
 * @ORM\Table(indexes={@ORM\Index(name="search_idx", columns={"active"})})
 */
class Patient
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column(type="guid", unique=true)
     * @Groups({"patient"})
     */
    private $id;
    .....
    
    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="patients")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     * @Groups({"patient"})
     */
    private $user;

    /**
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="created_by", referencedColumnName="id")
     * @Groups({"patient"})
     */
    private $created_by;

    /**
     * @ORM\ManyToOne(targetEntity="User")
     * @ORM\JoinColumn(name="modified_by", referencedColumnName="id")
     * @Groups({"patient"})
     */
    private $modified_by;
....
```
And here my User entity
```php
/**
 * @ApiResource(
 *     collectionOperations={"get"},
 *     itemOperations={"get"},
 *     normalizationContext={"groups"={"read"}},
 *     denormalizationContext={"groups"={"write"}}
 * )
 * @ApiFilter(SearchFilter::class, properties={"role": "exact"})
 * @ApiFilter(BooleanFilter::class, properties={"isActive"})
 * @ORM\Entity(repositoryClass="App\Repository\UserRepository")
 * @ORM\Table(indexes={@ORM\Index(name="search_idx", columns={"role", "is_active"})})
 */
class User implements UserInterface, \Serializable
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue(strategy="UUID")
     * @ORM\Column(type="guid", unique=true)
     * @Groups({"read", "write", "patient", "appointment"})
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=155, unique=true)
     * @Assert\NotBlank()
     * @Groups({"read", "write", "patient", "appointment"})
     */
    private $username;

    /**
     * @ORM\Column(type="string", length=500)
     * @Assert\NotBlank()
     * @Groups("write")
     */
    private $password;
    .....
```
Swagger show my this as JSON result for the patient entity
```json
[
  {
    "id": "string",
    ....
    "user": {
      "id": "string",
      "username": "string",
      "firstname": "string",
      "lastname": "string",
      "role": "string",
      "email": "string",
      "isActive": true
    },
    "created_by": {
      "id": "string",
      "username": "string",
      "firstname": "string",
      "lastname": "string",
      "role": "string",
      "email": "string",
      "isActive": true
    },
    "modified_by": {
      "id": "string",
      "username": "string",
      "firstname": "string",
      "lastname": "string",
      "role": "string",
      "email": "string",
      "isActive": true
    }
  }
]
```
This result is exactly what I want but when I do an API request with Postman or my React client I got this 
```json
{
    "@context": "/api/contexts/Patient",
    "@id": "/api/patients/5c79461c-1c98-11e9-83ab-4ca03f5a0611",
    "@type": "Patient",
    "id": "5c79461c-1c98-11e9-83ab-4ca03f5a0611",
    ....
    "user": {
        "@id": "/api/users/5c791598-1c98-11e9-83ab-4ca03f5a0611",
        "@type": "User",
        "id": "5c791598-1c98-11e9-83ab-4ca03f5a0611",
        "username": "doctor_01",
        "firstname": "Adrienne",
        "lastname": "Evrard",
        "role": "doctor",
        "email": "camille65@desousa.com"
    },
    "created": "2019-01-20T10:47:12+01:00",
    "updated": "2019-01-20T10:47:12+01:00",
    "contentChanged": null
}
```
As you can see first relation call user is there but not the created_by and modified_by...
Any advise ? Did I make something wrong.
Thank you in advance.

**Comment by Gulivertx** [comment]
Ok, found something, if I removed `normalizationContext={"groups"={"patient"}}` and `@Groups({"patient"})` inside my **Patient** entity I get a correct return with properties **user**, **createdBy** and **modifiedBy**
```json
{
    "@context": "/api/contexts/Patient",
    "@id": "/api/patients/2e75a4f4-1cb6-11e9-83ab-4ca03f5a0611",
    "@type": "Patient",
    "id": "2e75a4f4-1cb6-11e9-83ab-4ca03f5a0611",
    ...
    "user": "/api/users/2e756fde-1cb6-11e9-83ab-4ca03f5a0611",
    "createdBy": "/api/users/2e756fde-1cb6-11e9-83ab-4ca03f5a0611",
    "modifiedBy": "/api/users/2e756fde-1cb6-11e9-83ab-4ca03f5a0611",
    "created": "2019-01-20T14:20:40+01:00",
    "updated": "2019-01-20T14:20:40+01:00",
    "contentChanged": null
}
```
My only problem is that I would like this properties returning the entity and not the link. It was why I did a group

**Comment by DejanVuj** [comment]
Inside postman as I can see, you are getting ld+json response. If you want to get response as json, instead of using "Content-Type:application/json" try using "Accept:application/json"

**Comment by Gulivertx** [comment]
My problem is not about in which format the response is received but about my entity relations.
I just want to get the JSON object (LD or not) for my embedded relations and not the IRI.
To do that I just used serialisation groups as explain [here](https://api-platform.com/docs/core/serialization/#embedding-relations)

The point is, if I create my group, **only the first relation is serialised as an object** and the two next seems to be ignore and disappear in response (I think my problem is only because my three relations point to the same User entity). What is strange for me the example of the response in Swagger doc return the correct response as an example. But unfortunately not the real server response.
I would like to avoid to do extra call to the API to get the properties "user", "created_by", "modified_by".

I do not know if it is a bug or something I'm doing wrong, this is my first try with API-Platform...

**Comment by GrisonDavid** [comment]
It's being almost one year, but,
did you find a solution ?
I encounter the same problem.
Calling my Societe class twice(societe_id, initial_societe_id) and only one returned from the API :/
Thanks

**Comment by Gulivertx** [comment]
I finally abandoned API Platform in favor of FOS Rest bundle which I found more flexible. 
But I will be happy to see if someone has a solution

**Comment by alanpoulain** [comment]
I may be a bug related to the name converter and the normalization using groups.
It would be great if you could try using camelCased properties (for instance `modifiedBy` instead of `modified_by`).
