### ISSUE TITLE
All collection operations have the same title

### ISSUE THREAD

**Issue by Jarablus** [api-platform/api-platform#97]
> ```
> resource.product.item_operation.get:
>      class:     "Dunglas\\ApiBundle\\Api\\Operation\\Operation"
>      public:    false
>      factory:   [ "@api.operation_factory", "createItemOperation" ]
>      arguments: [ "@resource.product", "GET" ]
> resource.product.collection_operation.get:
>      class:     "Dunglas\\ApiBundle\\Api\\Operation\\Operation"
>      public:    false
>      factory:   [ "@api.operation_factory", "createCollectionOperation" ]
>      arguments: [ "@resource.product", "GET" ]
> resource.product.collection_operation.search:
>      class: "Dunglas\\ApiBundle\\Api\\Operation\\Operation"
>      public: false
>      factory: [ "@api.operation_factory", "createCollectionOperation" ]
>      arguments:
>           - "@resource.product"
>           - [ "GET", "HEAD"]
>           - "/products/search"
>           - "AppBundle:Product:search"
>           - "product_search"
>           - # Context
>               "@type": "hydra:Operation"
>               "hydra:title": "Product Search"
>               "returns": "json/string"
> resource.product:
>      parent:    "api.resource"
>      arguments: [ "AppBundle\\Entity\\Catalog\\Product" ]
>      calls:
>          -      [ "initItemOperations", [ [ "@resource.product.item_operation.get" ] ] ]
>          -      [ "initCollectionOperations", [ [ "@resource.product.collection_operation.search", "@resource.product.collection_operation.get" ] ] ]
>      tags:      [ { name: "api.resource" } ]
> ```

title is always  "Product Search" for any collection operation (title of the first operation)

**Comment by dunglas** [comment]
Which version are you using?

**Comment by napalm33700** [comment]
It was v1 i will try with v2

**Comment by napalm33700** [comment]
Same thing with V2 even with annotation

**Comment by Simperfit** [comment]
Could you please past the entity ?

**Comment by napalm33700** [comment]
I can't before wednesday I used apiplatform at work and i'm on vacation until that time

**Comment by Simperfit** [comment]
@napalm33700 If you can update this asap ;)

**Comment by napalm33700** [comment]
` * @ApiResource(
 *     attributes={"filters"={"product.search"}},
 *     collectionOperations={
 *         "get"={"method"="GET", "normalization_context"={"groups"={"product"}}},
 *         "search"={
 *            "path"="/products/search",
 *            "method"="GET",
 *            "normalization_context"={"groups"={"product"}},
 *            "controller"="AppBundle:Product:search",
 *            "hydra_context"={"@type"="hydra:Operation", "hydra:title"="Recherche de produits Sider", "returns"="jsonld"}
 *         }
 *     },
 *     itemOperations={
 *         "get"={"method"="GET", "normalization_context"={"groups"={"product"}}},
 *     }
 * )`

**Comment by dunglas** [comment]
See https://api-platform.com/docs/core/swagger
