### ISSUE TITLE
Feature Request - Puppeteer Docker Website Crawler

### ISSUE THREAD

**Issue by dannylewis-sheffield** [api-platform/api-platform#971]
The official distribution makes great use of Docker and favours frontends developed with javascript, I would like to see an additional docker component that indexes the site and produces static html content for SEO and initial page load and users who disable javascript.

Headless Chrome and Puppeteer can provide this functionality.

Crawler example: https://github.com/GoogleChromeLabs/puppeteer-examples/blob/master/crawlsite.js

Running puppeteer in docker: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-in-docker

**Comment by dunglas** [comment]
I would prefer a docs entry, or an example in the [demo](https://github.com/api-platform/demo) app. But we try to keep the focus on direct API Platform features in this repository.

Also, but it's a personal opinion, I prefer true SSR such as Next.js than this kind of hacks :)

**Comment by dannylewis-sheffield** [comment]
Up to you guys and I can see your perspective but right now I can get a get a developer to download the distribution and deliver a project with minimal intervention, well, some of the testing docs and code could do with an update since the Symfony 4 changes ;>, and I know it will be delivered with a good architecture and tech stack.  This is thanks to you guys and this wonderful project.

But what it is not doing is showing up on search engines without changes to the client component, and it seems a shame to bin or significantly change it on a per project basis when an optional component, just like the admin and client, could solve the issue and allow the world to easily find the great tools and sites people are building.

As for Next.js and others, I like them but I'd rather keep running node on the servers to a minimum, some bright spark always suggests writing the API in node as well and it'd rather not have that conversation again :)

I'm also not sure if running a crawler to generate static HTML is a hack or just a different approach, it does have the benefit of not limiting developers to a specific stack or framework, or worse rolling their own, and it also allows them to focus on writing clean testable frontend code that interacts with clean testable APIs, ultimatly delivering business or community needs.
