### ISSUE TITLE
Using DTO : No resource class found for object of type "App\Dto\***Output".

### ISSUE THREAD

**Issue by Neirda24** [api-platform/api-platform#972]
- ApiPlatform version: `Version 2.4.0 beta 1`
- Linked documentation: https://api-platform.com/docs/core/dto/
- Description: When using the `inputClass` and `outputClass` feature of the `Version 2.4.0 beta 1` it seems that the `ApiPlatform\Core\Hydra\Serializer\CollectionNormalizer` is throwing an error. Instead when using the `Accept: application/json` header no more problems.
- Steps to reproduce:

1. Create an `ApiResource`
2. Declare two Different Dto's in `inputClass` and `outputClass`
3. Make a call to get the collection on this resource with format=`jsonld`

**Comment by dunglas** [comment]
Do you have a data provider for the output class?

**Comment by KonstantinCodes** [comment]
I experience the same behavior, when there is no data provider defined.

**Comment by Neirda24** [comment]
@dunglas : Hi. Yes I have both a `CollectionDataProvider` and an `ItemDataProvider`. both also implementing `RestrictedDataProviderInterface`

**Comment by soyuka** [comment]
This error usually means that the data provider wasn't able to retrieve your output. Would you be able to give me a small reproduction case based on the api-platform/api-platform repo? Tyvm!

**Comment by Neirda24** [comment]
Hi. It seems it was just a mistake I made. Sorry for the bother. The fact is I didn't understood fully ApiPlatform and when it says that you should create a custom data provider it doesn't specify that if using doctrine extensions you must provide the original resourceClass. In my case my resource is `Thread` and the outputClass is `ThreadOutput` in the support of the custom data provider I must use `ThreadOutput` but in the doctrine extensions I must provide `Thread::class`.

I don't know if I am being clear enough. Although this seems to be resolved I have other issues. With the collection provider of the same resource. Still working on that I'll get back to you if I get stuck.
