### ISSUE TITLE
Consider replacing GraphiQL with GraphQL Playground

### ISSUE THREAD

**Issue by esistgut** [api-platform/api-platform#975]
https://github.com/prisma/graphql-playground seems to offer more features and a more refined design. Is there a reason to prefer GraphiQL?

**Comment by dunglas** [comment]
I wasn’t aware of this one, we could probably support both as for Swagger UI / ReDoc.

**Comment by alanpoulain** [comment]
Done in master :slightly_smiling_face: https://api-platform.com/docs/master/core/graphql/#graphql-playground.
