### ISSUE TITLE
Doctrine error when generating getters/setters

### ISSUE THREAD

**Issue by mbckwa** [api-platform/api-platform#98]
Hi, 

I have my PHP entity with my fields and '@ORM' annotations. Then, I add the `use ApiPlatform\Core\Annotation\ApiResource as Resource` and annotation `@Resource` to register resources.

But when I try to generate Getters and Setters with Doctrine command line `orm:generate-entities --update-entities=true --generate-methods=true` (which works when the `@Resource` and `use...` are not added), I get the following Doctrine error :

`[Doctrine\Common\Annotations\AnnotationException]
[Semantical Error] The annotation "@ApiPlatform\Core\Annotation\ApiResource" in class AppBundle\Entity\Bed does not exist, or could not be auto-loaded.`

Thanks.

**Comment by dunglas** [comment]
This is probably a bug in Doctrine (or Symfony) related to annotation autoloading. You should reopen it on the Doctrine bug tracker.

**Comment by teohhanhui** [comment]
Are you using v1 or v2?

**Comment by mbckwa** [comment]
@dunglas Ok, I'll do that.

@teohhanhui I'm using v2.

**Comment by teohhanhui** [comment]
It'd be great if you can provide a repository to reproduce the problem. Also, I'm not sure why you're using Doctrine's command directly, instead of using Symfony's `bin/console`?

**Comment by mbckwa** [comment]
I'm using Doctrine's command because the options `--update-entities=true --generate-methods=true` aren't available with Symfony's `bin/console`.

I'll try to provide a repository soon.

**Comment by dunglas** [comment]
> I'm using Doctrine's command because the options --update-entities=true --generate-methods=true aren't available with Symfony's bin/console.

It's probably the problem. Doctrine command may not load properly Symfony annotations (it uses a special autoloading system).

**Comment by teohhanhui** [comment]
> Doctrine command may not load properly Symfony annotations (it uses a special autoloading system).

I thought it's just the Composer autoloader (PSR-4 etc.). And aren't annotations loaded using the Doctrine annotation reader? https://github.com/symfony/framework-bundle/blob/f340f7e96329c1d2b4f174318aa8e22a96bf2f71/Resources/config/annotations.xml

**Comment by dunglas** [comment]
Annotations use a special autoloader: http://doctrine-orm.readthedocs.io/projects/doctrine-common/en/latest/reference/annotations.html#registering-annotations

**Comment by Simperfit** [comment]
Is it still on our side ?
