### ISSUE TITLE
@ApiResource annotation is causing api platform to crash

### ISSUE THREAD

**Issue by michaelrachlitz** [api-platform/api-platform#987]
I am adding the @ApiResource annotation to my entity, and this causes the entire platform to crash and complain about "Make sure there is a loader supporting the "api_platform" type."

[Gist](https://gist.github.com/michaelrachlitz/2922e2c8d81e430762d83dd6a8d91c5d)

If I leave out the annotation service works, but my swagger specific annotation comments are ignored. I refer to the documentation here. I have 
https://api-platform.com/docs/core/swagger/#using-the-openapi-and-swagger-contexts

**Comment by z31fbras** [comment]
This code works:

```
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiProperty;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
/**
 * Class Consent
 * @ApiResource
 * @ORM\Entity
 */
class Consent
{
    /**
     * @var int
     *
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }
}
```

**Comment by z31fbras** [comment]
You cannot create an entity with an @ORM\Entity annotation without an attribute with the @ORM\Id annotation ;)

**Comment by michaelrachlitz** [comment]
@z31fbras I do have that, however I just simplified the example too much I guess.

Code is 

`<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use ApiPlatform\Core\Annotation\ApiProperty;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Class Consent
 * @ApiResource
 * @ORM\Entity
 */
class Consent
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="IDENTITY")
     */
    private $id;

    /**
     * @param date-time $created_at A date property - containing consent creation date-time.
     *
     * @ORM\Column(type="datetime", name="created_at")
     * @Assert\NotBlank
     *
     * @ApiProperty(
     *     attributes={
     *         "swagger_context"={"type"="string", "format"="date-time"}
     *     }
     * )
     */
    public $created_at;

    /**
     * Consent constructor.
     */
    public function __construct()
    {
        $this->setCreatedAt(new \DateTime());
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set id
     *
     * @param $id
     * @return Consent
     */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
     * Get created at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->created_at;
    }

    /**
     * Set created at
     *
     * @param $created_at
     * @return Consent
     */
    public function setCreatedAt($created_at)
    {
        $this->created_at = $created_at;

        return $this;
    }
}
`

**Comment by z31fbras** [comment]
@michaelrachlitz Works fine on my computer, I pasted your code into my project and your entity appears in my Swagger 
![image](https://user-images.githubusercontent.com/43874795/52200183-5b996480-2868-11e9-862b-16407dca9adb.png)

**Comment by z31fbras** [comment]
@michaelrachlitz Maybe it has to do with your API Platform version?
What is yours?

**Comment by z31fbras** [comment]
@michaelrachlitz Do you have any other entity on this project that works fine?

**Comment by michaelrachlitz** [comment]
@z31fbras sigh, I found the error. Was a typo in the doctrine wrapper class which caused an unwanted error. Had nothing to do with the ApiResource class

**Comment by lekeutch** [comment]
> Was a typo in the doctrine wrapper class

Hi @michaelrachlitz, i have a similar problem with Api-platform. I haven't understand what you wrote. "Typo in the Doctrine Wrapper" ??

**Comment by mouataz1** [comment]
> > Was a typo in the doctrine wrapper class
> 
> Hi @michaelrachlitz, i have a similar problem with Api-platform. I haven't understand what you wrote. "Typo in the Doctrine Wrapper" ??

i had the same issue i solved it by following the next steps  : 
first create a normal entity : symfony console make:entity EntityName
and compleat all fields
then on the entityfile add this use :
use ApiPlatform\Core\Annotation\ApiResource;
and add the annotation @ApiResource
this works just fine for me.
