### ISSUE TITLE
Embedded relations with alpha2.0

### ISSUE THREAD

**Issue by cfuerst** [api-platform/api-platform#99]
Hi,

since the documentation in master (https://github.com/api-platform/doc/blob/master/core/serialization-groups-and-relations.md) seems outdated, it would be great if someone can tell me how to achive embedded releations with the v2.0.0-alpha.1 branch.

Edit: there is no service "api.resource" at all.

Thnx

**Comment by dunglas** [comment]
The doc has been updated now: https://github.com/api-platform/doc/blob/master/core/serialization-groups-and-relations.md
