### ISSUE TITLE
[Bug?] GraphQL Does not Filter Related Collections

### ISSUE THREAD

**Issue by kiler129** [api-platform/api-platform#994]
Consider a simple `Location` object containing collection of `Link`s. The links are attached using M2M relationship (I also tested with O2M). When executing a query like the following:
```
location(id: "/api/location/some_uuid") {
  links {
    edges {
      node {
        id,
        name
      }
    }
  }
}
```

I get the following output in the profiler:
![huhwtf](https://user-images.githubusercontent.com/1227834/52575124-48941080-2de3-11e9-8565-7007d93c01f0.png)

As you can see the topmost query (4) contains `WHERE` for the id of location, while 6 counts ALL links and 7 fetches ALL links (not just assigned to the `Location`).
I tried with and without repository defined on the `Link` entity - the behavior is the same. I'm currently running `v2.4.0-beta.1`.

Am I doing something wrong or this is a rather scary bug?

**Comment by alanpoulain** [comment]
Not sure why but it shouldn't be the case. The issue is possibly in the `CollectionResolverFactory`.

**Comment by kiler129** [comment]
From preliminary debugging it seems like the intention was that all related paths (`$location->links` here) will be marked with `@ApiSubresource`. While doing this allows expected requests in REST (`/location/some_uuid/links`) leading to proper results it does nothing for GraphQL.

This fragment seems to be responsible:
```php
            if (isset($rootClass, $source[$rootProperty = $info->fieldName], $source[ItemNormalizer::ITEM_KEY])) {
                $rootResolvedFields = $this->identifiersExtractor->getIdentifiersFromItem(unserialize($source[ItemNormalizer::ITEM_KEY]));
                $subresource = $this->getSubresource($rootClass, $rootResolvedFields, array_keys($rootResolvedFields), $rootProperty, $resourceClass, true, $dataProviderContext);
                $collection = $subresource ?? [];
            } else {
                $collection = $this->collectionDataProvider->getCollection($resourceClass, null, $dataProviderContext);
            }
```

The second path leads to whole collection access without `WHERE`. Intuitively looking the first path should lead to subresource query, but it does not since the last part of `isset()` (` $source[ItemNormalizer::ITEM_KEY]` -> `$source['#item']`) is never there.

@alanpoulain: Maybe you can give me some clue in debugging this?

**Comment by kiler129** [comment]
Ok, that was a PEBKAC. This came from the normalizers priority and the fact my custom normalizer was called before GraphQL one and the custom one was composing `api_platform.serializer.normalizer.item` instead of `api_platform.jsonld.normalizer.item`

**Comment by mxmp210** [comment]
I know too late to comment on closed issue but, I tried similar with DTO's and REST part is functioning properly and fetching related objects, yet graphql is not respecting the output and completely ignores DTO context, it fetches all the object not related to entity, which is not desired behavior. I thought it was the way to go with collections have OneToMany or ManyToMany relations. I do not have any normalizers except DTO's logic. Can you give some insight why api platform is ignoring DTO output but taking it's structure in consideration.  I'm planning to do custom operations with other DTO pattern & Messenger, I cannot quite figure out why it is not grokking as intended or may be I'm doing something wrong from the information provided in docs?

**Comment by tobyski-tdsultra** [comment]
I found this post through google and had exactly the same issue, my related collections were not auto filtered by the parent entity.  To fix I just needed to ensure my custom Doctrine serializers included a format check to not run if $format == 'graphql'.
