### ISSUE TITLE
Limiting Collection Access To Only via Subresource

### ISSUE THREAD

**Issue by kiler129** [api-platform/api-platform#996]
Imagine a CMS where you have `Page`s and `Content`s. It's beneficial to return all `Content`s assigned to a `Page`, but giving access to **all** `Content`s defined in the whole system poses problems. Now add a `User` entity to that mix - you surely don't want to expose all users via API, but list of editors for a `Page` is perfectly fine.

As far as I can see in the docs and from observed behavior there're two problems:
 - As soon as you define `collectionOperations={"get"}` everything is accessible (which where kind of expected is problematic)
 - The `collectionOperations={}` is ignored by GraphQL and even causes issues like #994

Is there a way of limiting this? I don't really know if this is a functionality problem or just docs.

**Comment by alanpoulain** [comment]
Using Doctrine extensions is the way to go: https://api-platform.com/docs/core/extensions/.
