### ISSUE TITLE
openAPI v3 output is not valid for authorization

### ISSUE THREAD

**Issue by Eydamos** [api-platform/api-platform#997]
If I call /docs.json?spec_version=3 I should get openAPI v3 compatible output. But if authorization is set up the node is still called securityDefinitions.
According to the [documentation](https://swagger.io/docs/specification/authentication/) is should be called securitySchemes along with some other changes.

**Comment by antograssiot** [comment]
it should already be the case, I'll try to have a look soon. 
Meanwhile can you check what happen here please ?
https://github.com/api-platform/core/blob/2bb6f950b4fe3568e5c87d3bbe56fbf87f1901da/src/Swagger/Serializer/DocumentationNormalizer.php#L759-L768

it seems that the keys are correct and the generated JSO schema is validated in the CI so it seems strange

**Comment by Eydamos** [comment]
I'm still on version 2.3.6 as the 2.4 is only marked as beta. So I will just have to wait for a stable version.
Thanks
