### ISSUE TITLE
Swagger schema generate string instead of object in swagger

### ISSUE THREAD

**Issue by Arkowsky** [api-platform/api-platform#999]
Hi,

I got some example schema from test file - api-platform/schema-generator/tests/config/ecommerce.yaml and generate some php code:

![image](https://user-images.githubusercontent.com/19975089/52707589-53d47100-2f88-11e9-9573-e43ebb6c3f89.png)

Some values as swagger schema are showed as "string" but relation is defined. Is there any way to have there object instead of string?

![image](https://user-images.githubusercontent.com/19975089/52707505-27b8f000-2f88-11e9-890a-a3e949766feb.png)

I know that I can define all relation as swagger_context but it is not friendly solution. If I add some field then I have to update all schemas.

```
 * @ApiResource(
 *     iri="http://schema.org/Thing",
 *     normalizationContext={"jsonld_embed_context"=true, "groups"={"pickup_point"}},
 *     collectionOperations={
 *          "get"={
 *               "method"="GET",
 *                  "swagger_context" = {
 *                  "responses" = {
 *                      "200" = {
 *                          "description" = "PickupPoint resource response",
 *                          "schema" = {
 *                              "type" = "object",
 *                              "properties" = {
 *                                   "id" = {
 *                                      "type" = "integer"
 *                                   },
 *                                   "parcelService" = {
 *                                      "$ref" = "#/definitions/ParcelService"
 *                                   },
 *                                   "pickupLocation" = {
 *                                      "type" = "object",
 *                                      "properties" = {
 *                                          "address" = {
 *                                              "type" = "string"
 *                                          },
```

**Comment by er1z** [comment]
Not so sure if understand correctly, but look: https://github.com/api-platform/api-platform/issues/606

**Comment by Arkowsky** [comment]
Finally I found solution:
We can avoid using swagger_context in most cases.

The solution is:
1) using serializations groups - https://api-platform.com/docs/core/serialization/#using-serialization-groups
2) don't forget that if you want nested objects in result:

![image](https://user-images.githubusercontent.com/19975089/55318025-077abd00-5472-11e9-9400-5573485a8488.png)

You have to tell in 1st child(here DeliveryMethod) that your object is in normalization context from parent(here Offer) and group "offer".
![image](https://user-images.githubusercontent.com/19975089/55318135-50cb0c80-5472-11e9-8838-3223d6ec2ad2.png)
